// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../Graphic ../../core/lang ../../geometry/SpatialReference ../../geometry/support/aaBoundingBox ../../geometry/support/aaBoundingRect ../../geometry/support/quantizationUtils ./dehydratedFeatureComparison".split(" "),function(A,d,l,m,x,g,h,k,y){function n(a){switch(a){case "esriGeometryPoint":return"point";case "esriGeometryMultipoint":return"multipoint";case "esriGeometryPolyline":return"polyline";case "esriGeometryPolygon":return"polygon";case "esriGeometryEnvelope":return"extent"}}
function p(a,b,c,f){return{uid:l.generateUID(),objectId:f&&a.attributes?a.attributes[f]:null,attributes:a.attributes,geometry:q(a.geometry,b,c),visible:!0}}function q(a,b,c){if(!a)return null;switch(b){case "point":return a={x:a.x,y:a.y,z:a.z,m:a.m,hasZ:null!=a.z,hasM:null!=a.m,type:b,spatialReference:c};case "polyline":return a={paths:a.paths,hasZ:!!a.hasZ,hasM:!!a.hasM,type:b,spatialReference:c};case "polygon":return a={rings:a.rings,hasZ:!!a.hasZ,hasM:!!a.hasM,type:b,spatialReference:c};case "multipoint":return a=
{points:a.points,hasZ:!!a.hasZ,hasM:!!a.hasM,type:b,spatialReference:c};case "extent":return a={xmin:a.xmin,ymin:a.ymin,zmin:a.zmin,mmin:a.mmin,xmax:a.xmax,ymax:a.ymax,zmax:a.zmax,mmax:a.mmax,hasZ:!!a.hasZ,hasM:!!a.hasM,type:b,spatialReference:c}}}function r(a){return"declaredClass"in a}function z(a){var b=a.spatialReference.toJSON();switch(a.type){case "point":return{x:a.x,y:a.y,z:a.z,m:a.m,spatialReference:b};case "polygon":var c=a.hasZ,f=a.hasM;return{rings:a.rings,hasZ:c,hasM:f,spatialReference:b};
case "polyline":var d=a.paths,c=a.hasZ,f=a.hasM;return{paths:d,hasZ:c,hasM:f,spatialReference:b};case "extent":var d=a.xmin,e=a.xmax,g=a.ymin,h=a.ymax,k=a.zmin,l=a.zmax,m=a.mmin,n=a.mmax,c=a.hasZ,f=a.hasM;return{xmin:d,xmax:e,ymin:g,ymax:h,zmin:k,zmax:l,mmin:m,mmax:n,hasZ:c,hasM:f,spatialReference:b};case "multipoint":return d=a.points,c=a.hasZ,f=a.hasM,{points:d,hasZ:c,hasM:f,spatialReference:b}}}function t(a,b){g.empty(b);"mesh"===a.type&&(a=a.extent);switch(a.type){case "point":b[0]=b[3]=a.x;b[1]=
b[4]=a.y;a.hasZ&&(b[2]=b[5]=a.z);break;case "polyline":for(var c=0;c<a.paths.length;c++)g.expandWithNestedArray(b,a.paths[c],a.hasZ);break;case "polygon":for(c=0;c<a.rings.length;c++)g.expandWithNestedArray(b,a.rings[c],a.hasZ);break;case "multipoint":g.expandWithNestedArray(b,a.points,a.hasZ);break;case "extent":b[0]=a.xmin,b[1]=a.ymin,b[3]=a.xmax,b[4]=a.ymax,null!=a.zmin&&(b[2]=a.zmin),null!=a.zmax&&(b[5]=a.zmax)}}function u(a,b){h.empty(b);"mesh"===a.type&&(a=a.extent);switch(a.type){case "point":b[0]=
b[2]=a.x;b[1]=b[3]=a.y;break;case "polyline":for(var c=0;c<a.paths.length;c++)h.expandWithNestedArray(b,a.paths[c]);break;case "polygon":for(c=0;c<a.rings.length;c++)h.expandWithNestedArray(b,a.rings[c]);break;case "multipoint":h.expandWithNestedArray(b,a.points);break;case "extent":b[0]=a.xmin,b[1]=a.ymin,b[2]=a.xmax,b[3]=a.ymax}}Object.defineProperty(d,"__esModule",{value:!0});d.equals=y.equals;d.isPoint=function(a){return"point"===a.type};d.mapJSONGeometryType=n;d.fromFeatureSetJSON=function(a){var b=
n(a.geometryType),c=x.fromJSON(a.spatialReference),d=a.transform;return a.features.map(function(f){f=p(f,b,c,a.objectIdFieldName);var e=f.geometry;if(e&&d)switch(e.type){case "point":f.geometry=k.hydratePoint(d,e,e,e.hasZ,e.hasM);break;case "multipoint":f.geometry=k.hydrateMultipoint(d,e,e,e.hasZ,e.hasM);break;case "polygon":f.geometry=k.hydratePolygon(d,e,e,e.hasZ,e.hasM);break;case "polyline":f.geometry=k.hydratePolyline(d,e,e,e.hasZ,e.hasM)}return f})};d.fromJSON=p;d.fromJSONGeometry=q;d.makeDehydratedPoint=
function(a,b,c,d){return{x:a,y:b,z:c,hasZ:null!=c,hasM:!1,spatialReference:d,type:"point"}};d.isHydratedGeometry=function(a){return"declaredClass"in a};d.isHydratedGraphic=r;d.hydrateGraphic=function(a,b){if(!a||r(a))return a;b=new l({layer:b,sourceLayer:b});b.visible=a.visible;b.symbol=m.clone(a.symbol);b.attributes=m.clone(a.attributes);a.geometry&&("mesh"===a.geometry.type?b.geometry=a.geometry:b.read({geometry:z(a.geometry)}));return b};d.computeAABB=t;d.expandAABB=function(a,b){t(a,v);g.expand(b,
v)};d.computeAABR=u;d.expandAABR=function(a,b){u(a,w);h.expand(b,w)};var v=g.create(),w=h.create()});