// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/generatorHelper ../core/tsSupport/awaiterHelper ../Basemap ../Ground ../WebScene ../core/JSONSupport ../core/MultiOriginJSONSupport ../core/accessorSupport/ensureType ../core/accessorSupport/extensions/serializableProperty/type ../layers/GroupLayer ../layers/mixins/OperationalLayer".split(" "),function(Z,v,f,e,J,K,L,M,N,D,O,E,F){function r(a,b){return e(this,void 0,void 0,function(){var d;return f(this,function(c){switch(c.label){case 0:d=a.typeName;switch(d){case "array":return[3,
1];case "union":return[3,3];case "json":return[3,5];case "native":return[3,7];case "enum":return[3,9]}return[3,11];case 1:return[4,P(a,b)];case 2:return c.sent(),[3,12];case 3:return[4,Q(a,b)];case 4:return c.sent(),[3,12];case 5:return[4,t(a,b)];case 6:return c.sent(),[3,12];case 7:return[4,R(a,b)];case 8:return c.sent(),[3,12];case 9:return[4,S(a,b)];case 10:return c.sent(),[3,12];case 11:c.label=12;case 12:return[2]}})})}function R(a,b){return e(this,void 0,void 0,function(){return f(this,function(d){b.addProperty({path:b.pathString,
type:q(a)});return[2]})})}function T(a){a=a.slice();a.sort();return a}function S(a,b){return e(this,void 0,void 0,function(){return f(this,function(d){b.addProperty({path:b.pathString,type:q(a),enum:T(a.values).map(function(a){return""+a}).join("|")});return[2]})})}function P(a,b){return e(this,void 0,void 0,function(){return f(this,function(d){switch(d.label){case 0:return b.pushPath(b.popPath()+"[]"),[4,r(a.elementType,b)];case 1:return d.sent(),[2]}})})}function U(a){return V[a]||a}function Q(a,
b){return e(this,void 0,void 0,function(){var d,c,g,u,k,l;return f(this,function(m){switch(m.label){case 0:d=b.pathString,c=b.popPath(),g=[],u=0,k=a.types,m.label=1;case 1:if(!(u<k.length))return[3,5];l=k[u];if("native"!==l.type.typeName)return[3,2];g.push(l.type);return[3,4];case 2:return b.pushPath(c+"\x3c"+U(l.value)+"\x3e"),[4,r(l.type,b)];case 3:m.sent(),b.popPath(),m.label=4;case 4:return u++,[3,1];case 5:return g.length&&b.addProperty({type:g.map(q).join("|"),path:d}),b.pushPath(c),[2]}})})}
function W(a,b,d){return e(this,void 0,void 0,function(){return f(this,function(c){switch(c.label){case 0:return a.type!==L||"layers"!==b?[3,2]:[4,p("web-scene/operational-layers")];case 1:return[2,c.sent()];case 2:return a.type!==J||"baseLayers"!==b?[3,4]:[4,p("web-scene/basemap")];case 3:return[2,c.sent()];case 4:return a.type!==K||"layers"!==b?[3,6]:[4,p("web-scene/ground")];case 5:return[2,c.sent()];case 6:return a.type!==E||"layers"!==b?[3,8]:[4,p("web-scene/operational-layers",function(a){return a!==
E})];case 7:return[2,c.sent()];case 8:return[2,X(d)]}})})}function t(a,b){return e(this,void 0,void 0,function(){var d,c,g,u,k,l,m,e,G,h,q,p,A,x,y,w,v,r,B,t;return f(this,function(n){switch(n.label){case 0:d=a.type.__accessorMetadata__;c=a.type.prototype.declaredClass.replace(/\./g,"/");g=d&&d.properties;c&&b.classPaths&&(b.classPaths[b.pathString]=c);if(!g)return b.addProperty({path:b.pathString,type:"unknown"}),[2];if(u=b.seen.get(a.type)){k=0;for(l=u;k<l.length;k++)m=l[k],b.pushPath(m.path),b.addProperty({path:b.pathString,
type:m.type}),b.popPath();return[2]}e=b.flatProperties.length;G=b.pathString;h=[];for(q in g)h.push(q);p=0;n.label=1;case 1:if(!(p<h.length))return[3,7];A=h[p];x=g[A];if(x.json){n=x.json.origins;var f=x.json.write,z=n&&n["web-document"]&&n["web-document"].write;y=n&&n["web-scene"]&&n["web-scene"].write||z||f||null}else y=null;if(!y||!y.enabled)return[3,6];w=y.target;return"string"!==typeof w&&null!=w?[3,4]:[4,W(a,A,x)];case 2:return(v=n.sent())?[4,H(v,"string"===typeof w?w:A,b)]:[3,6];case 3:return n.sent(),
[3,6];case 4:return[4,Y(w,b)];case 5:n.sent(),n.label=6;case 6:return p++,[3,1];case 7:if(b.flatProperties.length===e)return b.addProperty({path:b.pathString,type:"unknown"}),[2];r=[];for(B=e;B<b.flatProperties.length;B++)t=b.flatProperties[B],r.push({path:t.path.slice(G.length+1),type:t.type});b.addSeen(a.type,r);return[2]}})})}function H(a,b,d){return e(this,void 0,void 0,function(){return f(this,function(c){switch(c.label){case 0:return d.pushPath(b),[4,r(a,d)];case 1:return c.sent(),d.popPath(),
[2]}})})}function Y(a,b){return e(this,void 0,void 0,function(){var d,c,g;return f(this,function(e){for(d in a)c=a[d],g=void 0,g=c.types?z(c.types):h(c.type),H(g,d,b);return[2]})})}function p(a,b){return e(this,void 0,void 0,function(){var d,c,g,e,k,l,m,h;return f(this,function(f){switch(f.label){case 0:d=F.supportedTypes[a];c={typeName:"union",key:"layerType",types:[]};g=[];for(e in d)g.push(e);k=0;f.label=1;case 1:if(!(k<g.length))return[3,4];l=g[k];return[4,F.typeModuleMap[l]()];case 2:m=f.sent();
if(!m||b&&!b(m))return[3,3];c.types.push({type:{typeName:"json",type:m},value:l});f.label=3;case 3:return k++,[3,1];case 4:if(0===c.types.length)return[2,null];h={typeName:"array",elementType:1===c.types.length?c.types[0].type:c};return[2,h]}})})}function q(a){switch(a.typeName){case "array":return q(a.elementType)+"[]";case "union":return""+a.types.map(function(a){return q(a.type)}).join(" | ");case "native":switch(a.type){case Number:return"number";case D.Integer:return"integer";case String:return"string";
case Boolean:return"boolean";default:return"unknown"}case "json":return a.type.prototype.declaredClass;case "enum":return"string"}}function X(a){return a.types?z(a.types):h(a.json&&a.json.type||a.type)}function z(a){if(Array.isArray(a))return{typeName:"array",elementType:z(a[0])};var b=[],d;for(d in a.typeMap){var c=a.typeMap[d];b.push({type:h(c),value:C(c)?null:d})}return 1===b.length?b[0].type:{typeName:"union",key:"string"===typeof a.key?a.key:"type",types:b}}function h(a){if(!a)return{typeName:"native",
type:null};if(Array.isArray(a))return"string"===typeof a[0]||"number"===typeof a[0]?{typeName:"enum",values:a}:{typeName:"array",elementType:h(a[0])};if(O.isCollection(a)){var b;if(a=a.prototype.itemType&&a.prototype.itemType.Type)if("function"===typeof a)b={typeName:"array",elementType:h(a)};else if(a.typeMap){var d=[];for(b in a.typeMap){var c=a.typeMap[b];d.push({type:h(c),value:C(c)?null:b})}b={typeName:"array",elementType:{typeName:"union",key:"string"===typeof a.key?a.key:"type",types:d}}}else b=
void 0;else b={typeName:"array",elementType:{typeName:"native",type:null}};return b}if(C(a))return{typeName:"native",type:a};b=(b=a._meta&&a._meta.bases)?-1!==b.indexOf(M)||-1!==b.indexOf(N):!1;return b?{typeName:"json",type:a}:{typeName:"native",type:null}}function C(a){return a===String||a===Boolean||a===Number||a===D.Integer}Object.defineProperty(v,"__esModule",{value:!0});v.scan=function(a){return e(this,void 0,void 0,function(){var b,d;return f(this,function(c){switch(c.label){case 0:return b=
new I,[4,t({typeName:"json",type:a},b)];case 1:return c.sent(),d=b.flatProperties,d.sort(function(a,b){return a.path.localeCompare(b.path)}),[2,d]}})})};v.collectClassPaths=function(a){return e(this,void 0,void 0,function(){var b;return f(this,function(d){switch(d.label){case 0:return b=new I({classPaths:{},cacheEnabled:!1}),[4,t({typeName:"json",type:a},b)];case 1:return d.sent(),[2,b.classPaths]}})})};var V={"unique-value":"uniqueValue","class-breaks":"classBreaks","point-3d":"PointSymbol3D","line-3d":"LineSymbol3D",
"mesh-3d":"MeshSymbol3D","polygon-3d":"PolygonSymbol3D","label-3d":"LabelSymbol3D","web-style":"styleSymbolReference",text:"Text",object:"Object",icon:"Icon",fill:"Fill",extrude:"Extrude",line:"Line",path:"Path","point-cloud-class-breaks":"pointCloudClassBreaksRenderer","point-cloud-rgb":"pointCloudRGBRenderer","point-cloud-stretch":"pointCloudStretchRenderer","point-cloud-unique-value":"pointCloudUniqueValueRenderer","fixed-size":"pointCloudFixedSizeAlgorithm",splat:"pointCloudSplatAlgorithm",bitfield:"pointCloudBitfieldFilter",
return:"pointCloudReturnFilter",value:"pointCloudValueFilter"},I=function(){function a(a){this.flatProperties=[];this.path=[];this.seen=new Map;a&&a.classPaths&&(this.classPaths=a.classPaths);this.cacheEnabled=!(!a||!a.cacheEnabled)}a.prototype.addProperty=function(a){this.flatProperties.push(a)};a.prototype.addSeen=function(a,d){this.cacheEnabled&&this.seen.set(a,d)};a.prototype.pushPath=function(a){this.path.push(a)};a.prototype.popPath=function(){return this.path.pop()};Object.defineProperty(a.prototype,
"pathString",{get:function(){return this.path.join(".")},enumerable:!0,configurable:!0});return a}()});