// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/assignHelper ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/promise/all ../Basemap ../Viewpoint ../core/Collection ../core/collectionUtils ../core/JSONSupport ../core/lang ../core/Logger ../core/promiseUtils ../core/accessorSupport/decorators ../core/accessorSupport/ensureType ../support/basemapUtils ../views/3d/lib/gl-matrix ../webdoc/support/Thumbnail ./Environment ./Lighting ./support/Description ./support/SlideGround ./support/Title".split(" "),
function(I,J,p,t,d,z,A,B,u,C,h,D,E,f,c,k,v,w,l,q,F,g,m,n){var G=0,x=function(f){function b(){var a=null!==f&&f.apply(this,arguments)||this;a.id="";return a}t(b,f);a=b;b.prototype.clone=function(){return new a({id:this.id})};var a;d([c.property({type:String,json:{write:!0}})],b.prototype,"id",void 0);return b=a=d([c.subclass()],b)}(c.declared(h)),r=u.ofType(x),H=E.getLogger("esri.webscene.Slide");return function(h){function b(a){a=h.call(this,a)||this;a._currentAnimation=null;a.id=Date.now().toString(16)+
"-slide-"+G++;a.title=new n.default;a.description=new g.default;a.thumbnail=new l.default;a.viewpoint=null;a.basemap=null;a.ground=null;a.environment=new q;a.visibleLayers=new r;return a}t(b,h);b.prototype.castTitle=function(a){return"string"===typeof a?new n.default({text:a}):k.ensureType(n.default,a)};b.prototype.castDescription=function(a){return"string"===typeof a?new g.default({text:a}):k.ensureType(g.default,a)};b.prototype.castThumbnail=function(a){return"string"===typeof a?new l.default({url:a}):
k.ensureType(l.default,a)};b.prototype.castBasemap=function(a){return v.ensureType(a)};Object.defineProperty(b.prototype,"visibleLayers",{set:function(a){this._set("visibleLayers",C.referenceSetter(a,this._get("visibleLayers"),r))},enumerable:!0,configurable:!0});b.prototype.castVisibleLayers=function(a){return a&&"function"===typeof a.map?a.map(function(a){if("string"===typeof a)return{id:a};if(a.id)return{id:a.id};H.warn('Invalid visible layer, expected { id }, Layer or "id"');return a}):a};b.prototype.clone=
function(){return new this.constructor({id:this.id,title:this.title.clone(),thumbnail:this.thumbnail.clone(),description:this.description&&this.description.clone()||null,viewpoint:this.viewpoint&&this.viewpoint.clone()||null,basemap:this.basemap&&this.basemap.clone()||null,ground:this.ground&&this.ground.clone()||null,visibleLayers:this.visibleLayers.clone(),environment:this.environment&&this.environment.clone()||null})};b.prototype._updateVisibleLayersFrom=function(a){var b=this,y=[];return f.eachAlways(this._allLayers(a.map).map(function(b){return a.whenLayerView(b).then(function(a){a.visible&&
y.push(new x({id:a.layer.id}))})}).toArray()).then(function(){b.visibleLayers.removeAll();b.visibleLayers.addMany(y)})};b.prototype.updateFrom=function(a,b){var e=this;b=p({screenshot:p({format:"jpeg",quality:80,width:120,height:75},b&&b.screenshot)},b);return a.when(function(){e.viewpoint=a.viewpoint.clone();e.environment.lighting=F.prototype.clone.apply(a.environment.lighting);e.basemap=a.map.basemap&&a.map.basemap.clone()||null;e.ground=a.map.ground?m.default.fromGround(a.map.ground):null;return e._updateVisibleLayersFrom(a)}).then(function(){return a.takeScreenshot(b.screenshot)}).then(function(a){e.thumbnail=
new l.default({url:a.dataUrl});return e})};b.prototype.applyTo=function(a,b){var e=this,c=p({animate:!0},b);return this._applyBasemap(a).then(function(){return z([e._applyViewpoint(a,c),e._applyLayerVisibility(a,c),e._applyGround(a)])}).then(function(){return e})};b.prototype._applyBasemap=function(a){var b=this;return this.basemap?this.basemap.load().always(function(){a.map.basemap=v.clonePreservingTiledLayers(b.basemap,a.map.basemap)}):f.resolve()};b.prototype._applyGround=function(a){this.ground&&
(a.map.ground=this.ground.cloneAndApplyTo(a.map.ground));return f.resolve()};b.prototype._allLayers=function(a){var b=new u;this._collectLayers(a,b);this._collectLayers(a.ground,b);return b};b.prototype._collectLayers=function(a,b){var e=this;a.layers.forEach(function(a){b.add(a);a.layers&&e._collectLayers(a,b)})};b.prototype._applyLayerVisibility=function(a,b){var e=this;if(this.visibleLayers){var c=this._allLayers(a.map);if(b.applyToLayerViews)return f.eachAlways(c.map(function(b){return a.whenLayerView(b).then(function(a){a.visible=
e.visibleLayers.some(function(b){return b.id===a.layer.id})})}).toArray());c.forEach(function(a){return a.visible=e.visibleLayers.some(function(b){return b.id===a.id})});return f.resolve()}};b.prototype._applyViewpoint=function(a,b){if(this.viewpoint){this.viewpoint.camera.fov=a.camera.fov;if(b.animate){if(this.get("environment.lighting.date"))return this._animateToLighting(a,b);a.environment.lighting=this.environment.lighting.clone();return a.goTo(this.viewpoint,b)}a.viewpoint=this.viewpoint;a.environment.lighting=
this.environment.lighting.clone()}return f.resolve()};b.prototype._animateToLighting=function(a,b){var e=this,c;"global"===a.viewingMode&&(c=this._animateLightingWithCamera(a));this._currentAnimation&&(this._currentAnimation.cancel(),this._currentAnimation=null);a.environment.lighting.cameraTrackingEnabled=!1;a.environment.lighting.directShadowsEnabled=this.environment.lighting.directShadowsEnabled;null!=this.environment.lighting.displayUTCOffset&&(a.environment.lighting.displayUTCOffset=this.environment.lighting.displayUTCOffset);
var d=a.goTo(this.viewpoint,b);this._currentAnimation=d;this._currentAnimation.always(function(){c&&c.remove();e._currentAnimation===d&&(a.environment.lighting.cameraTrackingEnabled=!0)});this._currentAnimation.then(function(){a.environment.lighting=e.environment.lighting.clone()});return this._currentAnimation};b.prototype._getTime=function(a){var b=a.getTime();a=3600*a.getUTCHours()+60*a.getUTCMinutes()+a.getUTCSeconds();return[b,a]};b.prototype._setTime=function(a,b,c){a.setTime(b);a.setUTCHours(c/
3600);a.setUTCMinutes(c%3600/60);a.setUTCSeconds(c%3600%60);return a};b.prototype._animateLightingWithCamera=function(a){var b=this,c=this._getTime(new Date(a.environment.lighting.date.toString())),d=c[0],f=c[1],c=this._getTime(this.environment.lighting.date),h=c[0],l=c[1],g=a.renderCoordsHelper,n=[0,0,0];g.toRenderCoords(a.camera.position,n);var p=[0,0,0];g.toRenderCoords(this.viewpoint.camera.position,p);var k=[0,0,0],q=new Date;return a.watch("camera",function(c){g.toRenderCoords(c.position,k);
c=w.vec3d.dist2(n,k);var e=w.vec3d.dist2(p,k),m=0;0!==c+e&&(m=c/(c+e));a.environment.lighting.date=b._setTime(q,d+(h-d)*m,f+(l-f)*m)})};b.createFrom=function(a,b){return(new this).updateFrom(a,b)};b.sanitizeJSON=function(a){var b;b=void 0!==a.visibleLayers&&Array.isArray(a.visibleLayers)?D.clone(a.visibleLayers):[];b={id:a.id||"",title:a.title||{text:""},thumbnail:a.thumbnail||{url:""},viewpoint:a.viewpoint,baseMap:a.baseMap,visibleLayers:b};void 0!==a.description&&(b.description=a.description);void 0!==
a.environment&&(b.environment=q.sanitizeJSON(a.environment));void 0!==a.ground&&(b.ground=m.default.sanitizeJSON(a.ground));return b};d([c.property({type:String,json:{write:{isRequired:!0}}})],b.prototype,"id",void 0);d([c.property({type:n.default,json:{write:{isRequired:!0}}})],b.prototype,"title",void 0);d([c.cast("title")],b.prototype,"castTitle",null);d([c.property({type:g.default,json:{write:{overridePolicy:function(a){return{enabled:!(!a||!a.text)}}}}})],b.prototype,"description",void 0);d([c.cast("description")],
b.prototype,"castDescription",null);d([c.property({type:l.default,json:{write:{isRequired:!0}}})],b.prototype,"thumbnail",void 0);d([c.cast("thumbnail")],b.prototype,"castThumbnail",null);d([c.property({type:B,json:{write:{isRequired:!0}}})],b.prototype,"viewpoint",void 0);d([c.property({type:A,json:{read:{source:"baseMap"},write:{target:"baseMap"}}})],b.prototype,"basemap",void 0);d([c.cast("basemap")],b.prototype,"castBasemap",null);d([c.property({type:m.default,json:{write:!0}})],b.prototype,"ground",
void 0);d([c.property({type:r,json:{write:{isRequired:!0}}})],b.prototype,"visibleLayers",null);d([c.cast("visibleLayers")],b.prototype,"castVisibleLayers",null);d([c.property({type:q,json:{write:!0}})],b.prototype,"environment",void 0);return b=d([c.subclass("esri.webscene.Slide")],b)}(c.declared(h))});