// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper dojo/errors/CancelError dojo/promise/all ../../../core/Accessor ../../../core/arrayUtils ../../../core/Evented ../../../core/Handles ../../../core/has ../../../core/Logger ../../../core/PooledArray ../../../core/Promise ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../core/sql/WhereClause ../../../geometry/support/aaBoundingBox ../../IntegratedMeshLayer ../../SceneLayer ../../../views/3d/layers/i3s/I3SIndex ../../../views/3d/layers/i3s/I3SLodHandling ../../../views/3d/layers/i3s/I3SNodeLoader ../../../views/3d/layers/i3s/I3SUtil ../../../views/3d/layers/i3s/I3SViewportQueries ../../../views/3d/layers/i3s/IdleQueue ../../../views/3d/lib/gl-matrix ../../../views/3d/support/projectionUtils ../../../views/3d/support/ResourceController".split(" "),
function(k,S,A,f,l,B,C,D,E,F,u,G,H,I,x,J,d,K,L,y,q,M,N,r,m,O,P,g,z,Q){function t(d,c){return d.length===c.length&&d.every(function(a){return 0<=v(c,a.name)})}function v(d,c){c=c.toLowerCase();for(var a=0;a<d.length;a++)if(d[a].name.toLowerCase()===c)return a;return-1}var h=G.getLogger("esri.layers.graphics.controllers.I3SOnDemandController");k=function(k){function c(a){a=k.call(this)||this;a.nodeIndex={};a.screenSizeFactor=0;a.featureTarget=5E4;a.updating=!0;a.updatingPercentage=0;a.leafsReached=
!1;a.uncompressedTextureDownsamplingEnabled=!1;a.alwaysLoadEverythingModeEnabled=!1;a._lodFactorProperty=null;a._featureLOD=1;a._stableFeatureLOD=!1;a._isIdle=!1;a._cameraDirty=!0;a._hasFeatures=!1;a._downloadingNodes=new Set;a._loadingNodes=new Set;a._updatingNodes=new Map;a._progressMaxNumNodes=1;a._poi=null;a._requiredAttributesDirty=!0;a._updatesDisabled=!1;a.disableCache=!1;a._restartNodeLoading=!1;a._fields=null;a._attributeStorageInfo=null;a._handles=new F;a._idleQueue=new P.IdleQueue;a._errorCount=
0;return a}A(c,k);Object.defineProperty(c.prototype,"isMeshPyramid",{get:function(){return"mesh-pyramids"===this.layer.profile||"MeshPyramid"===this.layer.store.lodType},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"streamDataSupplier",{get:function(){return this.layerView.view.resourceController.getStreamDataSupplier(Q.ClientType.SCENE,{trackRequests:!0})},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"parsedDefinitionExpression",{get:function(){if(this.layer instanceof
q&&this.layer.definitionExpression)try{var a=K.create(this.layer.definitionExpression);if(!a.isStandardized())return h.error("definitionExpression is using non standard function"),null;var b=[],c=a.getFields();m.findFieldsCaseInsensitive(c,this.layer.fields,{missingFields:b});return 0<b.length?(h.error("definitionExpression references unknown fields: "+b.join(", ")),null):a}catch(e){return h.error("Failed to parse definitionExpression: "+e),null}else return null},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,
"definitionExpressionFields",{get:function(){if(this.parsedDefinitionExpression){var a=this.parsedDefinitionExpression.getFields();return m.findFieldsCaseInsensitive(a,this._fields)}return null},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"crsVertex",{get:function(){return m.getVertexCrs(this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"crsIndex",{get:function(){return m.getIndexCrs(this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,
"rootNodeVisible",{get:function(){var a=this._rootNodeId&&this.nodeIndex[this._rootNodeId];return a&&this._viewportQueries?this._viewportQueries.isNodeVisible(a):!0},enumerable:!0,configurable:!0});c.prototype.initialize=function(){var a=this;this.updateEventListener={needsUpdate:function(){return!1},idleBegin:function(){a._updateIdleState(!0)},idleEnd:function(){a._updateIdleState(!1)}};this.updateEventListenerWhileSuspended={idleBegin:function(){return a._startNodeLoadingWhileSuspended()}};this._lodHandling=
new N(this.layerView,function(){return a.updatingChanged()});var b=this.layerView.layer;this.layer=b;this._defaultGeometrySchema=b.store.defaultGeometrySchema;this._rootNodeUrl=b.store.rootNode;var c=this._rootNodeUrl.split("/");this._rootNodeId=c[c.length-1];this.disableCache=u("disable-feature:idb-cache");b instanceof q?("mesh"===b.geometryType?this._lodFactorProperty="qualitySettings.sceneService.3dObject.lodFactor":"point"===b.geometryType&&(this._lodFactorProperty="qualitySettings.sceneService.point.lodFactor"),
this._fields=b.fields,this._attributeStorageInfo=b.attributeStorageInfo):b instanceof y&&(this._lodFactorProperty="qualitySettings.sceneService.integratedMesh.lodFactor");b=B([this.layer.when(),this.layerView.when()]).then(function(){if(!a.destroyed&&a.layerView&&!a.layerView.destroyed){var b=a.layerView.view;a.setClippingArea(b.clippingArea);a._centerOnSurface=b.pointsOfInterest.centerOnSurfaceFrequent;a._handles.add(a._centerOnSurface.watch("renderLocation",function(){return a._pointOfInterestChanged()}));
var c=a.layerView.view.resourceController;c.memoryEvents.on("quality-changed",function(){return a._setCameraDirty()});a._handles.add(J.init(a.layerView,"suspended",function(b){a._idleFrameWorker&&(a._idleFrameWorker.remove(),a._idleFrameWorker=null,a.restartNodeLoading());a._frameWorker&&(a._frameWorker.remove(),a._frameWorker=null);b?a._idleFrameWorker=c.registerIdleFrameWorker(a.updateEventListenerWhileSuspended):(a._idleFrameWorker=c.registerIdleFrameWorker(a.updateEventListener),a._frameWorker=
c.registerFrameWorker(function(b){return a._frame(b)}))}),"layerview");a._handles.add(a.layer.watch("elevationInfo",function(b){return a._elevationInfoChanged(b)}),"layer");a.watch("uncompressedTextureDownsamplingEnabled",function(){return a.restartNodeLoading()});a.watch("alwaysLoadEverythingModeEnabled",function(){return a.restartNodeLoading()});a._handles.add(b.state.watch("camera",function(){return a._setCameraDirty()}));a._handles.add(a.watch("featureTarget",function(){a._stableFeatureLOD=!1}));
a._lodFactorProperty&&a._handles.add(a.layerView.view.watch(a._lodFactorProperty,function(){return a._setCameraDirty()}),"quality")}});this.addResolvingPromise(b);this.when(function(){return a._startNodeLoading()})};c.prototype.destroy=function(){this._idleFrameWorker&&(this._idleFrameWorker.remove(),this._idleFrameWorker=null);this._frameWorker&&(this._frameWorker.remove(),this._frameWorker=null);this._handles.destroy();this._nodeLoader=null};c.prototype._getRequiredAttributes=function(){if(!(null!=
this._attributeStorageInfo&&this.layer instanceof q&&this._fields))return[];var a=Object.create(null);this.layer.renderer&&this.layer.renderer.collectRequiredFields(a);this.layer.labelsVisible&&this.layer.labelingInfo&&this.layer.labelingInfo.forEach(function(b){b._collectRequiredFields(a)});if(null!=this.definitionExpressionFields)for(var b=0,c=this.definitionExpressionFields;b<c.length;b++)a[c[b]]=!0;var e=this._attributeStorageInfo,w=this._fields,d=this.layer.objectIdField;return Object.keys(a).map(function(a){var b=
v(e,a);a=v(w,a);return 0<=b&&0<=a?{index:b,name:w[a].name,field:w[a],attributeStorageInfo:e[b]}:null}).filter(function(a){return null!=a&&a.name!==d}).sort(function(a,b){return b.index-a.index}).filter(function(a,b,c){return 0===b||c[b-1].index!==a.index})};c.prototype._requiredFieldsChange=function(){this._requiredAttributesDirty=!0;this.restartNodeLoading()};c.prototype._labelingChanged=function(){var a=this._requiredAttributes,b=this._getRequiredAttributes();t(a,b)||this._requiredFieldsChange()};
c.prototype.setClippingArea=function(a){var b=L.create();z.extentToBoundingBox(a,b,this.layerView.view.renderSpatialReference)?this._clippingArea=b:this._clippingArea=null};c.prototype._pointOfInterestChanged=function(){this._poi&&(this._calculatePointOfInterest(this._poi),this._viewportQueries&&(this._viewportQueries.updatePointOfInterest(this._poi),this._index&&(this._index.progressiveLoadPenalty=n.distancePenalty*this._viewportQueries.distCameraToPOI(),this._index.requestReload())))};c.prototype._calculatePointOfInterest=
function(a){void 0===a&&(a=g.vec3d.create());var b=this._centerOnSurface.renderLocation,c=g.vec3d.create();g.vec3d.subtract(b,this.camPos,c);g.vec3d.normalize(c);var e=this.layerView.view.renderCoordsHelper,d=g.vec3d.create();e.worldUpAtPosition(b,d);c=Math.acos(g.vec3d.dot(d,c))-.5*Math.PI;g.vec3d.lerp(this.camPos,b,Math.max(0,Math.min(1,c/(.5*Math.PI))),a);return a};c.prototype.updateClippingArea=function(a){this.setClippingArea(a);this._cameraDirty=!0;this._viewportQueries&&this._viewportQueries.updateExtent(this._clippingArea)};
c.prototype._setCameraDirty=function(){this._cameraDirty=!0;this.updatingChanged()};c.prototype.getBaseUrl=function(){return this.layer.parsedUrl.path};c.prototype.updateElevationChanged=function(a,b,c){m.findIntersectingNodes(a,b,this.nodeIndex.root,this.crsIndex,this.nodeIndex,function(a){c.push(a)});for(a=0;a<c.length;a++)b=c.data[a],this._viewportQueries.invalidateCache(b.id),b.id===this._rootNodeId&&this.notifyChange("rootNodeVisible");c.length&&this.restartNodeLoading()};c.prototype._elevationInfoChanged=
function(a){this._viewportQueries.invalidateCache();this._initViewData()};c.prototype.restartNodeLoading=function(){this._restartNodeLoading=!0;this.updatingChanged()};c.prototype.schedule=function(a,b){var c=this;return this._idleQueue.push(b).then(function(b){if(!c._loadingNodes.has(a)&&!c._updatingNodes.has(a))throw new l;return b})};c.prototype.reschedule=function(a,b){var c=this;return this._idleQueue.unshift(b).then(function(b){if(!c._loadingNodes.has(a)&&!c._updatingNodes.has(a))throw new l;
return b})};c.prototype.getUnloadedMemoryEstimate=function(){return this._index?this._index.getUnloadedMemoryEstimate()*this._getLodDropFactor():0};c.prototype._frame=function(a){null!==this._viewportQueries&&this._viewportQueries.setCameraIdle(!this._cameraDirty);this.layerView.visible&&this._processLogError(a,!1)};c.prototype._processLogError=function(a,b){void 0===b&&(b=!0);try{this._process(a,b)}catch(R){50>this._errorCount?h.error("Error during processing: "+R):50===this._errorCount&&h.error("Too many errors for this layer. Further errors will not be displayed."),
this._errorCount++}};c.prototype._process=function(a,b){var c=this;this._restartNodeLoading&&(this.cancelNodeLoading(),this._startNodeLoading());if(null!=this._nodeLoader&&null!=this._index){this._updateViewData()&&(b=!1);var e=function(c){(b||!a.done())&&c()&&(b=!1)};e(function(){return c._processIndex()});for(e(function(){return c._processNodes(a,b)});0<this._idleQueue.length()&&(b||!a.done());)b=!1,this._idleQueue.process();this._updateFeatureLOD();e(function(){return c._prefetchIndex()});this.updatingChanged();
this._lodHandling.lodGlobalHandling()}};c.prototype._processIndex=function(){var a=Math.min(10-this._index.getIndexLoading(),this._getAvailableLoadTokens(1));this._index.update(D.keysOfSet(this._loadingNodes));var b=this._index.getFeatureEstimate().leafsReached;this._index.isLoading()||b===this._get("leafsReached")||this._set("leafsReached",b);return this._index.load(a)};c.prototype._prefetchIndex=function(){if(0<this._loadingNodes.size)return!1;var a=Math.min(10-this._index.getIndexLoading(),this._getAvailableLoadTokens(1));
return this._index.prefetch(a)};c.prototype._updateFeatureLOD=function(){var a=this._index.getFeatureEstimate(),b=this.featureTarget*this._getLOD()/this._featureLOD;if(a.estimate){var c=!this._index.isLoading();if(!c&&!this._index.isPrefetching()&&500<this._index.getIndexMissing()){if(1E-4>=this._featureLOD)return;this._featureLOD/=1.5;this._stableFeatureLOD=!1}else if(c&&a.estimate<b){if(1E4<=this._featureLOD||a.leafsReached||this._stableFeatureLOD)return;c=this._featureLOD;this._featureLOD*=1+Math.min(.1*
(b/a.estimate-1),.1);if(!this._index.checkFeatureTarget(b,this._getLOD())){this._featureLOD=c;this._stableFeatureLOD=!0;return}}else if(a.estimate>1.2*b||c&&a.estimate>b){if(1E-4>=this._featureLOD)return;this._featureLOD/=1+.25*(a.estimate/b-1);this._stableFeatureLOD=!1}else return;this._featureLOD=Math.min(1E4,Math.max(1E-4,this._featureLOD));this._viewportQueries.updateScreenSpaceErrorBias(this._getLOD());this._index.requestReload()}};c.prototype._processNodes=function(a,b){var c=this,e=this._index.getUpdates((this._isIdle?
100:2)-this._loadingNodes.size);e.cancel.forEach(this._cancelNodeIdLoading,this);e.update.forEach(function(e){if(b||!a.done())b=!1,c._updateLoadedNode(e)});e.add.forEach(function(e){if(b||!a.done())b=!1,c._loadNode(e)});return!b};c.prototype._cancelNodeLoading=function(){var a=this;this._loadingNodes.clear();this._downloadingNodes.clear();this._updatingNodes.forEach(function(b,c){return a._updatingNodes.get(c).cancel()});this._updatingNodes.clear()};c.prototype._cancelNodeIdLoading=function(a){this._loadingNodes.delete(a);
this._downloadingNodes.delete(a)};c.prototype._getAvailableLoadTokens=function(a){return Math.floor((12-1*this._index.getIndexLoading()-2*this._downloadingNodes.size)/a)};c.prototype._hasNodeLoadToken=function(){return this._downloadingNodes.size>=(this._isIdle?5:2)?!1:0<this._getAvailableLoadTokens(2)};c.prototype.updatingChanged=function(){var a=this._index?this._index.getIndexMissing():0,b=this._index?this._index.getNodesMissing():0,a=a+3*b+2*this._loadingNodes.size,b=!(!(0<a||0<this._updatingNodes.size||
this._index&&this._index.isPrefetching()||this._restartNodeLoading||this._cameraDirty||0<this._idleQueue.length()||this._lodHandling&&this._lodHandling.requiresLODGlobalHandling)&&this._isIdle);0===a&&(this._progressMaxNumNodes=1);this._progressMaxNumNodes=Math.max(a,this._progressMaxNumNodes);b!==this._get("updating")&&this._set("updating",b);a=100*a/this._progressMaxNumNodes;a!==this._get("updatingPercentage")&&this._set("updatingPercentage",a)};c.prototype._initViewData=function(){var a=this.layerView.view,
b=a.state.camera,c=a.renderCoordsHelper;this.camPos=g.vec3d.create(a.pointsOfInterest.renderPointOfView);this.screenSizeFactor=1/b.perPixelRatio;this._poi=this._calculatePointOfInterest();var e=this._getLOD();this._viewportQueries=new O(this.crsIndex,c,b,this._poi,this._clippingArea,a.elevationProvider,this.layer.elevationInfo,{progressiveLoadFactor:this._getProgressiveLoadFactor(this.layer,e),screenspaceErrorBias:e,angleDependentLoD:.5>e,disableLod:this.alwaysLoadEverythingModeEnabled});this._cameraDirty=
!1;this.notifyChange("rootNodeVisible")};c.prototype._updateViewData=function(){if(!this._cameraDirty||!this._index)return!1;var a=this.layerView.view,b=a.state.camera;this.camPos=g.vec3d.create(a.pointsOfInterest.renderPointOfView);this.screenSizeFactor=1/b.perPixelRatio;this._poi=this._calculatePointOfInterest(this._poi);this._viewportQueries.updateCamera(b);this._viewportQueries.updatePointOfInterest(this._poi);a=this._getLOD();this._viewportQueries.updateScreenSpaceErrorBias(a);this._index.progressiveLoadPenalty=
n.distancePenalty*this._viewportQueries.distCameraToPOI();this._index.requestReload();this._stableFeatureLOD=!1;a=!this.alwaysLoadEverythingModeEnabled&&this._removeInvisibleNodes();this._cameraDirty=!1;this.notifyChange("rootNodeVisible");return a};c.prototype._getProgressiveLoadFactor=function(a,b){return a instanceof q&&"mesh"===a.geometryType?(a=1<=b&&u("enable-feature:progressive-3dobject"))?n.factor3dObject:1:a instanceof y?(a=1<=b&&!u("disable-feature:progressive-im"))?n.factorIM:1:1};c.prototype._getLOD=
function(){return(this._lodFactorProperty&&this.layerView.view.get(this._lodFactorProperty)||1)*this.layerView.view.resourceController.memoryFactor*this._featureLOD};c.prototype._getLodDropFactor=function(){return Math.min(this.layerView.view.resourceController.memoryFactor,.5)/.5};c.prototype._startNodeLoadingWhileSuspended=function(){this._initViewData();this.alwaysLoadEverythingModeEnabled&&this.layerView.visible&&!this.layerView.get("parent.suspended")||this._removeInvisibleNodes()};c.prototype.isGeometryVisible=
function(a){return this._viewportQueries.isGeometryVisible(a)};c.prototype.updateVisibility=function(a){return this._viewportQueries.updateNode(a)};c.prototype._shouldLoadNode=function(a){if(!this._lodHandling.shouldLoadNode(a))return!1;var b=this._getLodDropFactor();return 0<b&&0<this._viewportQueries.maxDistance&&this._lodHandling.childrenEmpty(a)&&this._viewportQueries.distToPOI(a)>this._viewportQueries.maxDistance*b?!1:a.obb?this._viewportQueries.isGeometryVisible(a):!0};c.prototype._startNodeLoading=
function(){var a=this;this._restartNodeLoading=!1;if(!this._updatesDisabled&&null!=this.streamDataSupplier){this._initViewData();this._requiredAttributesDirty&&(this._requiredAttributes=this._getRequiredAttributes(),this._requiredAttributesDirty=!1,this._handles.add([this.layer.watch("renderer",function(){return a._requiredFieldsChange()}),this.layer.watch("definitionExpression",function(){return a._requiredFieldsChange()}),this.layer.watch("labelsVisible",function(){return a._labelingChanged()}),
this.layer.watch("labelingInfo",function(){return a._labelingChanged()})],"requiredAttributes"));var b=r.TextureFormat.Normal;this.layerView.useCompressedTextures?b=r.TextureFormat.Compressed:this.uncompressedTextureDownsamplingEnabled&&(b=r.TextureFormat.Downsampled);var c=this._defaultGeometrySchema;this._nodeLoader=new r(this.streamDataSupplier,h,c,this._requiredAttributes,{textureFormat:b,loadTextureData:this.layerView.rendererNeedsTextures,loadFeatureData:!this.isMeshPyramid||null==c||null==
c.ordering});b=n.distancePenalty*this._viewportQueries.distCameraToPOI();this._index=new M(this.getBaseUrl(),this._rootNodeUrl,this._rootNodeId,b,this.nodeIndex,this.streamDataSupplier,this._viewportQueries,h,function(b){return a.layerView.isNodeLoaded(b)},function(b){return a._shouldLoadNode(b)},function(b){return a._enableFromGPUCache(b)},function(b){return a._needsUpdate(b)});b=this.layerView.view.renderSpatialReference;b=this.crsIndex.equals(b)||this.crsIndex.isWGS84&&b.equals(z.SphericalECEFSpatialReference);
this._index.ignoreServiceOBB=!b;this.alwaysLoadEverythingModeEnabled||this._removeInvisibleNodes();this._lodHandling.startNodeLoading(function(b){return a._viewportQueries.isNodeVisible(b)},function(b){return a._viewportQueries.isGeometryVisible(b)},function(b){return a._index.nodeTraversalState(b)},this.nodeIndex,this._rootNodeId,{maxLodLevel:this._viewportQueries.maxLodLevel});this.updatingChanged()}};c.prototype.isNodeLoading=function(){return null!=this._nodeLoader&&null!=this._index};c.prototype.cancelNodeLoading=
function(){this.isNodeLoading()&&(this._nodeLoader.cancelAll(),this.streamDataSupplier.cancelAll(),this._idleQueue.cancelAll(),this._cancelNodeLoading(),this._poi=this._index=this._nodeLoader=null,this.layerView.additionalCancelNodeLoadingHandler&&this.layerView.additionalCancelNodeLoadingHandler(),this.updatingChanged())};c.prototype._removeInvisibleNodes=function(){var a=this.layerView.getLoadedNodeIDs(),b=this._getLodDropFactor(),c=this._viewportQueries.maxDistance*b,b=0<b&&0<c;p.clear();for(var e=
0;e<a.length;e++){var d=this.nodeIndex[a[e]];if(!this._viewportQueries.isGeometryVisible(d)||b&&this._lodHandling.childrenEmpty(d)&&this._viewportQueries.distToPOI(d)>c)this._lodHandling.setLodGlobalDirty(),p.push(d)}return 0<p.length?(this.layerView.removeNodeData(p),p.clear(),!0):!1};c.prototype._needsUpdate=function(a){if(null==a.featureData||0===a.featureData.length||this._updatingNodes.has(a.id))return!1;a=this.layerView.getLoadedAttributes(a);return null!=a&&a!==this._requiredAttributes};c.prototype._updateLoadedNode=
function(a){var b=this,c=a.baseUrl,e=this.layerView.getLoadedAttributes(a),c=t(e,this._requiredAttributes)?x.resolve(this.layerView.getAttributeData(a)):this._nodeLoader.loadAttributes(a,c,this._requiredAttributes);this._updatingNodes.set(a.id,c);c.then(function(c){return b.schedule(a.id).then(function(){return b.layerView.setAttributeData(a,b._requiredAttributes,c)})}).catch(function(c){c instanceof l||b.layerView.setAttributeData(a,b._requiredAttributes,{})}).always(function(){b._updatingNodes.delete(a.id);
b.updatingChanged()});this.updatingChanged()};c.prototype._loadNode=function(a){var b=this;if(!a.notInCache||this._hasNodeLoadToken())this._loadingNodes.add(a.id),this.updatingChanged(),this._loadAndAddBundle(a).always(function(){b._loadingNodes.delete(a.id);b._hasFeatures=b._hasFeatures||!!a.numFeatures;b.updatingChanged()})};c.prototype._loadAndAddBundle=function(a){1!==a.featureData.length&&h.warn("Node ${node.id} has ${node.featureData.length} bundles. Only the first bundle will be loaded.");
return a.notInCache?this._loadUncached(a):this._loadCached(a).then(function(b){b||(a.notInCache=!0)}).catch(function(b){b instanceof l||(a.notInCache=!0)})};c.prototype._enableFromGPUCache=function(a){if(this.disableCache||!this.layerView.loadCachedGPUData||!this.layerView.addCachedGPUData)return!1;var b=this.layerView.loadCachedGPUData(a);if(!b||null==b.loadedAttributes||null==b.attributeData||!t(b.loadedAttributes,this._requiredAttributes))return!1;this.layerView.addCachedGPUData(a,b,b);this._lodHandling.lodSwapBundleLoaded(a);
return!0};c.prototype._loadCached=function(a){var b=this,c=this.layerView;return!this.disableCache&&c.loadCachedNodeData&&c.addCachedNodeData?this.schedule(a.id).then(function(){return c.loadCachedNodeData(a,function(a,c){return b._nodeLoader.loadTextures(a,c)})}).then(function(d){if(null==d)return!1;var e=b._requiredAttributes;return null!=d.loadedAttributes&&null!=d.attributeData&&t(d.loadedAttributes,e)?b.reschedule(a.id).then(function(){return c.addCachedNodeData(a,d,d)}).then(function(){b._lodHandling.lodSwapBundleLoaded(a);
return!0}):b.reschedule(a.id).then(function(){return b._nodeLoader.loadAttributes(a,a.baseUrl,e)}).then(function(c){return b.reschedule(a.id,{loadedAttributes:e,attributeData:c})}).then(function(b){return c.addCachedNodeData(a,d,b)}).then(function(){b._lodHandling.lodSwapBundleLoaded(a);return!0})}):x.resolve(!1)};c.prototype._loadUncached=function(a){var b=this;this._downloadingNodes.add(a.id);return this._nodeLoader.loadBundleData(a,0).then(function(c){b._downloadingNodes.delete(a.id);return b.schedule(a.id,
c)}).then(function(c){return b.layerView.addNodeData(a,c)}).then(function(){b._lodHandling.lodSwapBundleLoaded(a);a.notInCache=!1}).catch(function(b){b instanceof l||(h.error("Failed to load node '"+a.id+"' bundle 0: "+b),a.failed=!0)})};c.prototype._updateIdleState=function(a){a!==this._isIdle&&(this._isIdle=a,this._viewportQueries&&this._viewportQueries.setCameraIdle(!0),this.updatingChanged())};c.prototype.updateStats=function(a){a.index=Object.keys(this.nodeIndex).length;this._hasFeatures&&(a.detail=
this._featureLOD,a.target=Math.round(this.featureTarget*this._getLOD()/this._featureLOD));this._index&&this._index.updateStats(a)};f([d.property({readOnly:!0})],c.prototype,"isMeshPyramid",null);f([d.property({readOnly:!0})],c.prototype,"streamDataSupplier",null);f([d.property({readOnly:!0,dependsOn:["layer.definitionExpression"]})],c.prototype,"parsedDefinitionExpression",null);f([d.property({readOnly:!0,dependsOn:["parsedDefinitionExpression"]})],c.prototype,"definitionExpressionFields",null);f([d.property({readOnly:!0})],
c.prototype,"crsVertex",null);f([d.property({readOnly:!0})],c.prototype,"crsIndex",null);f([d.property({readOnly:!0})],c.prototype,"nodeIndex",void 0);f([d.property()],c.prototype,"camPos",void 0);f([d.property()],c.prototype,"screenSizeFactor",void 0);f([d.property()],c.prototype,"featureTarget",void 0);f([d.property()],c.prototype,"layerView",void 0);f([d.property()],c.prototype,"layer",void 0);f([d.property({readOnly:!0})],c.prototype,"updating",void 0);f([d.property({readOnly:!0})],c.prototype,
"updatingPercentage",void 0);f([d.property({readOnly:!0})],c.prototype,"leafsReached",void 0);f([d.property({readOnly:!0})],c.prototype,"rootNodeVisible",null);f([d.property({aliasOf:"layerView.uncompressedTextureDownsamplingEnabled"})],c.prototype,"uncompressedTextureDownsamplingEnabled",void 0);f([d.property({aliasOf:"layerView.alwaysLoadEverythingModeEnabled"})],c.prototype,"alwaysLoadEverythingModeEnabled",void 0);return c=f([d.subclass("esri.layers.graphics.controllers.I3SOnDemandController")],
c)}(d.declared(C,I,E));var p=new H,n={factorIM:.2,factor3dObject:.05,distancePenalty:10};return k});