// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ./common ../../lib/gl-matrix ../../state/utils/navigationUtils ../../state/utils/viewUtils ../../support/earthUtils ../../support/mathUtils".split(" "),function(E,p,m,h,B,u,w,k){function v(c,a,b,d,f){void 0===b&&(b=m.defaultApplyOptions);void 0===d&&(d=a);void 0===f&&(f=!0);a!==d&&d.copyFrom(a);q.eyeCenterDistance=0;q.requiresTwoSteps=!1;var e=x(c,a,b,void 0,q);if(0===e)return!1;h.mat4d.identity(r);h.mat4d.rotate(r,-e,a.viewRight);switch(b.tiltMode){case 1:h.mat4d.multiplyVec3(r,
a.viewForward,l);h.vec3d.scale(l,q.eyeCenterDistance);h.vec3d.add(a.eye,l,d.center);break;case 0:h.vec3d.subtract(a.center,a.eye,l),h.mat4d.multiplyVec3(r,l),h.vec3d.subtract(a.center,l,d.eye)}h.mat4d.multiplyVec3(r,d.up);d.markViewDirty();return q.requiresTwoSteps&&f?v(c,d,b,d,!1):!0}function x(c,a,b,d,f){void 0===b&&(b=m.defaultApplyOptions);void 0===d&&(d=m.defaultApplyOptions);if(!c.state.constraints.tilt)return 0;var e=c.state.constraints.tilt(a.distance,C);var g=b;if(0!==g.interactionType){var n=
g.interactionStartCamera,l=g.interactionFactor,q=e.min,r=e.max,p=x(c,n,m.defaultApplyOptions,g),v=0===p?0:u.viewAngle(c.renderCoordsHelper,n.center,n.eye);e.min=q;e.max=r;2===g.interactionType?(m.hasConstraintType(g.selection,2)&&z(c,n,e),m.adjustRangeForInteraction(p,v,!0,l,A,e)):m.adjustRangeForInteraction(p,v,!1,l,A,e)}2===d.interactionType&&m.hasConstraintType(d.selection,2)&&z(c,d.interactionStartCamera,e);if(1===b.tiltMode||1===d.tiltMode){a:{f&&(f.requiresTwoSteps=!1);switch(c.viewingMode){case "global":b=
D;g=c.pointsOfInterest.centerOnSurfaceFrequent.estimatedSurfaceAltitude;d=g+w.earthRadius;g=c.renderCoordsHelper.intersectManifold(a.eye,a.viewForward,g,t);b.eyeCenterDistance=a.distance;g?(b.eyeCenterDistance=h.vec3d.dist(a.eye,t),b.tiltAtCenter=u.viewAngle(c.renderCoordsHelper,t,a.eye)):c.state.isLocal?b.tiltAtCenter=u.viewAngle(c.renderCoordsHelper,a.center,a.eye):(B.closestPointOnCenteredSphereSilhouette(d,a.eye,a.viewForward,t),b.eyeCenterDistance=h.vec3d.dist(a.eye,t),b.tiltAtCenter=k.acos(-h.vec3d.dot(a.viewForward,
h.vec3d.normalize(t))));b.radius=d;b.eyeRadius=h.vec3d.length(a.eye);b.constraints=c.state.constraints;b.centerIsOnSurface=g;a=k.clamp(b.tiltAtCenter,e.min,e.max);if(1E-9<Math.abs(b.tiltAtCenter-a)){if(b.centerIsOnSurface){a=b.constraints;c=d=b.tiltAtCenter;e=a.clampTilt(b.eyeCenterDistance,d);g=y(b,e);if(a.clampTilt(g,d)!==e)for(d=0;10>d&&1E-9<Math.abs(e-c);)g=(c+e)/2,n=y(b,g),n=a.clampTilt(n,g),1E-9<Math.abs(n-g)?c=g:e=g,d++;a=e;e=a;c=k.asin(b.radius/b.eyeRadius*Math.sin(b.tiltAtCenter));e=k.asin(b.radius/
b.eyeRadius*Math.sin(e));c=b.eyeRadius>b.radius?c-e:e-c}else a=b.constraints.clampTilt(b.eyeCenterDistance,b.tiltAtCenter),f&&a<Math.PI/2&&(f.requiresTwoSteps=!0,a=Math.PI/2-1E-5),c=b.tiltAtCenter-Math.PI/2-(a-Math.PI/2);f&&(f.eyeCenterDistance=y(b,a));f=c}else f=0;break a;case "local":d=u.viewAngle(c.renderCoordsHelper,a.center,a.eye);b=k.clamp(d,e.min,e.max);e=d-b;1E-9<Math.abs(e)?(f&&(d=c.pointsOfInterest.centerOnSurfaceFrequent.estimatedSurfaceAltitude,c=c.renderCoordsHelper.getAltitude(a.eye)-
d,b=Math.cos(b),f.eyeCenterDistance=1E-4<Math.abs(b)?c/b:a.distance),f=e):f=0;break a}f=void 0}return f}f=u.viewAngle(c.renderCoordsHelper,a.center,a.eye);a=k.clamp(f,e.min,e.max);f-=a;f=1E-9<Math.abs(f)?f:0;return f}function y(c,a){if(!c.centerIsOnSurface)return c.eyeCenterDistance;a=Math.PI-k.clamp(a,0,Math.PI);var b=k.asin(c.radius/c.eyeRadius*Math.sin(a)),d=Math.sin(Math.PI-a-b)/Math.sin(a);return c.eyeRadius<c.radius&&1<d?Math.sin(Math.PI-a-(Math.PI-b))/Math.sin(a)*c.eyeRadius:d*c.eyeRadius}
function z(c,a,b){if(!c.state.isLocal){var d=c.state.constraints;if(d.altitude){c=h.vec3d.length2(a.center);var f=Math.sqrt(c);a=a.distance;var e=d.altitude.min+w.earthRadius,d=d.altitude.max+w.earthRadius,e=(e*e-a*a-c)/(-2*f*a);b.min=Math.max(b.min,Math.min(Math.PI-k.acos((d*d-a*a-c)/(-2*f*a)),b.max));b.max=Math.min(b.max,Math.PI-k.acos(e))}}}Object.defineProperty(p,"__esModule",{value:!0});p.apply=v;p.error=x;var l=h.vec3d.create(),r=h.mat4d.create(),t=h.vec3d.create(),A=k.deg2rad(5),C={min:0,max:0},
D={constraints:null,radius:0,eyeRadius:0,centerIsOnSurface:!0,eyeCenterDistance:0,tiltAtCenter:0},q={eyeCenterDistance:0,requiresTwoSteps:!1}});