// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../geometry/support/aaBoundingBox ../../../lib/gl-matrix ../../../support/mathUtils ../../lib/ComponentUtils ../../lib/doublePrecisionUtils ../../lib/screenSizePerspectiveUtils ../../lib/Util".split(" "),function(ga,f,n,h,aa,K,ba,C,L){function M(a,b,c,d,g){var e=N(b,c,O);n.setMin(l,a.getBBMin());n.setMax(l,a.getBBMax());if(r(l,b,e,d)){var e=a.getPrimitiveIndices(),f=a.getIndices(),h=a.getPosition(),k=e?e.length:f.length/3;if(k>ca&&(a=a.getChildren(),void 0!==a)){for(e=
0;8>e;++e)void 0!==a[e]&&M(a[e],b,c,d,g);return}y(b,c,0,k,f,h,e,g)}}function y(a,b,c,d,g,e,f,h){var k=e.data,B=e.offsetIdx;e=e.strideIdx;var P=a[0],t=a[1];a=a[2];var l=b[0]-P,n=b[1]-t;for(b=b[2]-a;c<d;c++){var r=f?f[c]:c,p=B+e*g[3*r],v=B+e*g[3*r+1],w=B+e*g[3*r+2],x=k[p],z=k[p+1],A=k[p+2],p=k[v]-x,D=k[v+1]-z,v=k[v+2]-A,E=k[w]-x,F=k[w+1]-z,w=k[w+2]-A,m=n*w-F*b,u=b*E-w*l,y=l*F-E*n,q=p*m+D*u+v*y,x=P-x,G=t-z,H=a-A,z=G*v-D*H,A=H*p-v*x,J=x*D-p*G;if(q>I){m=x*m+G*u+H*y;if(0>m||m>q)continue;u=l*z+n*A+b*J;if(0>
u||m+u>q)continue}else if(q<-I){m=x*m+G*u+H*y;if(0<m||m<q)continue;u=l*z+n*A+b*J;if(0<u||m+u<q)continue}else continue;q=(E*z+F*A+w*J)/q;0<=q&&(p=Q(p,D,v,E,F,w,da),h(q,p,r))}}function Q(a,b,c,d,g,e,f){h.vec3d.set3(a,b,c,R);h.vec3d.set3(d,g,e,S);return h.vec3d.normalize(h.vec3d.cross(R,S,f))}function N(a,b,c){return h.vec3d.set3(1/(b[0]-a[0]),1/(b[1]-a[1]),1/(b[2]-a[2]),c)}function r(a,b,c,d){var g=(a[0]-d-b[0])*c[0],e=(a[3]+d-b[0])*c[0],f=Math.min(g,e),g=Math.max(g,e),e=(a[1]-d-b[1])*c[1],h=(a[4]+
d-b[1])*c[1],f=Math.max(f,Math.min(e,h)),g=Math.min(g,Math.max(e,h));if(f>g)return!1;e=(a[2]-d-b[2])*c[2];a=(a[5]+d-b[2])*c[2];f=Math.max(f,Math.min(e,a));g=Math.min(g,Math.max(e,a));return f<=g}function T(a,b){b=b?T(b):{};for(var c in a){var d=a[c];d&&d.forEach&&(d=ea(d));null==d&&c in b||(b[c]=d)}return b}function ea(a){var b=[];a.forEach(function(a){return b.push(a)});return b}Object.defineProperty(f,"__esModule",{value:!0});var U=h.mat4d.create(),l=n.create(),V=L.VertexAttrConstants;f.IDENTITY=
h.mat4d.identity();f.intersectTriangleGeometry=function(a,b,c,d,g,e,f){L.assert("triangle"===a.data.primitiveType);b=b&&b.componentVisibilities;d=d.tolerance;if(1<a.componentCount){c=N(g,e,O);var h=a.boundingInfo;n.setMin(l,h.getBBMin());n.setMax(l,h.getBBMax());if(r(l,g,c,d))for(var k=a.data,h=a.componentCount,B=k.getIndices(V.POSITION),C=k.getAttribute(V.POSITION),k=k.componentOffsets,t=0;t<h;t++)if(!b||K.getVisibility(b,t)){var I=a.getComponentAABB(t,l);r(I,g,c,d)&&y(g,e,k[t]/3,k[t+1]/3,B,C,void 0,
f)}}else b&&!K.getVisibility(b,0)||M(a.boundingInfo,g,e,d,f)};var O=h.vec3d.create(),I=Math.pow(2,-52),da=h.vec3d.create();f.intersectTriangles=y;var R=h.vec3d.create(),S=h.vec3d.create();f.computeNormal=Q;f.intersectAabbInvDir=r;f.transformToWorld=function(a,b,c){return h.vec4d.set4(a[0]-b[0],a[1]-b[1],a[2]-b[2],1,c)};f.transformToView=function(a,b,c,d){h.mat4d.translate(c,b,U);c=U;return h.mat4d.multiplyVec4(c,a,d)};f.transformToProjection=function(a,b,c,d){d[0]=a[0]+c[0];d[1]=a[1]+c[1];d[2]=a[2]+
c[2];d[3]=a[3];return h.mat4d.multiplyVec4(b,d)};f.transformToNDC=function(a,b){return h.vec4d.scale(a,1/Math.abs(a[3]),b)};f.applyScreenSizePerspectiveScale=function(a,b,c,d,g){return C.scale(a,d,c,g)};f.verticalOffsetAtDistance=function(a,b,c,d,g){var e=c.screenLength||0;g&&(e=C.scale(e,d,b,g));return aa.clamp(e*Math.tan(.5*a.fovY)/(.5*a.fullHeight)*b,c.minWorldLength||0,null!=c.maxWorldLength?c.maxWorldLength:Infinity)};f.aquireIfNotUndefined=function(a,b,c){if(void 0!==a)return b.aquire(a,c)};
f.releaseIfNotUndefined=function(a,b){void 0!==a&&b.release(a)};var W=h.mat4.create();f.bindView=function(a,b,c){h.mat4d.translate(b,a,W);c.setUniform3fv("localOrigin",a);c.setUniformMatrix4fv("view",W)};f.bindCamPos=function(a,b,c){c.setUniform3f("camPos",b[3]-a[0],b[7]-a[1],b[11]-a[2])};var X=h.vec3d.create(),Y=h.vec3d.create();f.bindViewOriginDouble=function(a,b){ba.encodeDoubleArraySplit(a,X,Y,3);b.setUniform3fv("viewOriginHi",X);b.setUniform3fv("viewOriginLo",Y)};var Z=h.vec3d.create();f.bindSlicePlane=
function(a,b,c){h.vec3d.subtract(b.origin,a,Z);c.setUniform3fv("slicePlaneOrigin",Z);c.setUniform3fv("slicePlaneBasis1",b.basis1);c.setUniform3fv("slicePlaneBasis2",b.basis2)};f.bindVerticalOffset=function(a,b,c){if(a){var d=b.fovY,g=b.viewport[3],e=void 0;void 0===e&&(e=fa);e.screenLength=a.screenLength;e.perDistance=Math.tan(.5*d)/(.5*g);e.minWorldLength=a.minWorldLength;e.maxWorldLength=a.maxWorldLength;a=e;c.setUniform4f("verticalOffset",a.screenLength*(b.pixelRatio||1),a.perDistance,a.minWorldLength,
a.maxWorldLength)}};f.bindScreenSizePerspective=function(a,b,c,d){void 0===d&&(d="screenSizePerspectiveAlignment");if(a){var g=a.parameters;c.setUniform4f(d,g.divisor,g.offset,g.minPixelSize*(b.pixelRatio||1),a.paddingPixelsOverride)}};f.copyParameters=T;f.updateParameters=function(a,b){var c=!1,d;for(d in b){var g=b[d];void 0!==g&&(c=!0,Array.isArray(g)?a[d]=g.slice():a[d]=g)}return c};(function(a){function b(a){return(a.shadowMappingEnabled?1:0)|(a.ssaoEnabled?2:0)}a.create=function(a,d){for(var c=
[],e=0;2>e;e++)for(var f=0;2>f;f++){var h=b({shadowMappingEnabled:1===e,ssaoEnabled:1===f}),k=b({shadowMappingEnabled:1===e,ssaoEnabled:1===f&&a.receiveSSAO});c[h]=c[k]||d({receiveShadows:1===e,receiveSSAO:1===f&&a.receiveSSAO})}return{programs:c.filter(function(a){return null!=a}),byParameter:c}};a.lookup=function(a,d){return a.byParameter[b(d)]};a.programs=function(a){return a.programs}})(f.BindParametersMap||(f.BindParametersMap={}));f.colorMixModes={multiply:1,ignore:2,replace:3,tint:4};var ca=
1E3,fa={screenLength:0,perDistance:0,minWorldLength:0,maxWorldLength:0}});