// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
require({cache:{"esri/core/tsSupport/awaiterHelper":function(){define(["../promiseUtils"],function(t){function l(e){return e&&"function"===typeof e.then?e:t.resolve(e)}return function(e,k,g,n){var m=null;return t.create(function(g,v){function r(c){try{d(n.next(c))}catch(p){v(p)}}function f(c){try{d(n["throw"](c))}catch(p){v(p)}}function d(c){c.done?(m=l(c.value),m.then(g,v)):(m=l(c.value),m.then(r,f))}d((n=n.apply(e,k||[])).next())},function(g){m&&m.cancel(g)})}})},"esri/core/tsSupport/generatorHelper":function(){define([],
function(){return function(t,l){function e(g){return function(f){return k([g,f])}}function k(e){if(n)throw new TypeError("Generator is already executing.");for(;g;)try{if(n=1,m&&(q=e[0]&2?m["return"]:e[0]?m["throw"]||((q=m["return"])&&q.call(m),0):m.next)&&!(q=q.call(m,e[1])).done)return q;if(m=0,q)e=[e[0]&2,q.value];switch(e[0]){case 0:case 1:q=e;break;case 4:return g.label++,{value:e[1],done:!1};case 5:g.label++;m=e[1];e=[0];continue;case 7:e=g.ops.pop();g.trys.pop();continue;default:if(!(q=g.trys,
q=0<q.length&&q[q.length-1])&&(6===e[0]||2===e[0])){g=0;continue}if(3===e[0]&&(!q||e[1]>q[0]&&e[1]<q[3]))g.label=e[1];else if(6===e[0]&&g.label<q[1])g.label=q[1],q=e;else if(q&&g.label<q[2])g.label=q[2],g.ops.push(e);else{q[2]&&g.ops.pop();g.trys.pop();continue}}e=l.call(t,g)}catch(f){e=[6,f],m=0}finally{n=q=0}if(e[0]&5)throw e[1];return{value:e[0]?e[1]:void 0,done:!0}}var g={label:0,sent:function(){if(q[0]&1)throw q[1];return q[1]},trys:[],ops:[]},n,m,q,v;return v={next:e(0),"throw":e(1),"return":e(2)},
"function"===typeof Symbol&&(v[Symbol.iterator]=function(){return this}),v}})},"esri/views/3d/support/meshProcessing":function(){define(["require","exports","./mathUtils"],function(t,l,e){Object.defineProperty(l,"__esModule",{value:!0});l.computeNeighbors=function(e,n){for(var g=e.length/3,k=new Uint32Array(n+1),l=new Uint32Array(n+1),r=function(a,b){a<b?k[a+1]++:l[b+1]++},f=0;f<g;f++){var d=e[3*f],c=e[3*f+1],p=e[3*f+2];r(d,c);r(c,p);r(p,d)}for(f=c=d=0;f<n;f++)p=k[f+1],r=l[f+1],k[f+1]=d,l[f+1]=c,
d+=p,c+=r;for(var u=new Uint32Array(6*g),w=k[n],r=function(a,b,c){if(a<b){var h=k[a+1]++;u[2*h]=b;u[2*h+1]=c}else h=l[b+1]++,u[2*w+2*h]=a,u[2*w+2*h+1]=c},f=0;f<g;f++)d=e[3*f],c=e[3*f+1],p=e[3*f+2],r(d,c,f),r(c,p,f),r(p,d,f);d=function(a,b){var h=2*a;a=b-a;for(b=1;b<a;b++){var c=u[h+2*b],y=u[h+2*b+1],d=b-1;for(d;0<=d&&u[h+2*d]>c;d--)u[h+2*d+2]=u[h+2*d],u[h+2*d+3]=u[h+2*d+1];u[h+2*d+2]=c;u[h+2*d+3]=y}};for(f=0;f<n;f++)d(k[f],k[f+1]),d(w+l[f],w+l[f+1]);for(var x=new Int32Array(3*g),t=function(a,b){return a===
e[3*b]?0:a===e[3*b+1]?1:a===e[3*b+2]?2:-1},g=function(a,b){a=t(a,b);x[3*b+a]=-1},d=function(a,b,c,d){a=t(a,b);x[3*b+a]=d;c=t(c,d);x[3*d+c]=b},f=0;f<n;f++){for(var c=k[f],p=k[f+1],r=l[f],B=l[f+1];c<p&&r<B;){var a=u[2*c],b=u[2*w+2*r];a===b?(d(f,u[2*c+1],b,u[2*w+2*r+1]),c++,r++):a<b?(g(f,u[2*c+1]),c++):(g(b,u[2*w+2*r+1]),r++)}for(;c<p;)g(f,u[2*c+1]),c++;for(;r<B;)b=u[2*w+2*r],g(b,u[2*w+2*r+1]),r++}return x};var k=null;l.deduplicate=function(g,n,m,l,v){void 0===m&&(m=0);void 0===l&&(l=0);void 0===v&&
(v=g.byteLength/(4*n));g=new Uint32Array(g,l,v*n);l=new Uint32Array(v);var r=Math.floor(1.1*v)+1;if(null==k||k.length<2*r)k=new Uint32Array(e.nextHighestPowerOfTwo(2*r));for(var f=0;f<2*r;f++)k[f]=0;for(var d=0,c=0!==m?Math.ceil(7.84*1.96/(m*m)*m*(1-m)):v,f=0;f<v;f++){if(f===c){var p=1-d/f;if(p+1.96*Math.sqrt(p*(1-p)/f)<m)return null;c*=2}for(var p=f*n,u,w=u=0;w<n;w++)u=g[p+w]+u|0,u=u+(u<<11)+(u>>>2)|0;u>>>=0;for(var w=u%r,q=d;0!==k[2*w+1];){if(k[2*w]===u){var t=k[2*w+1]-1,B=t*n;a:{for(var a=0;a<
n;a++)if(g[p+a]!==g[B+a]){B=!1;break a}B=!0}if(B){q=l[t];break}}w++;w>=r&&(w-=r)}q===d&&(k[2*w]=u,k[2*w+1]=f+1,d++);l[f]=q}if(0!==m&&1-d/v<m)return null;m=new Uint32Array(n*d);for(f=d=0;f<v;f++)if(l[f]===d){r=g;c=f*n;p=m;u=d*n;w=n;for(q=0;q<w;q++)p[u+q]=r[c+q];d++}return{buffer:m.buffer,indices:l,uniqueCount:d}}})},"esri/views/3d/support/mathUtils":function(){define(["require","exports","../lib/gl-matrix"],function(t,l,e){function k(c){return Math.asin(1<c?1:-1>c?-1:c)}function g(c){return Math.acos(1<
c?1:-1>c?-1:c)}function n(c,d,f){return c<d?d:c>f?f:c}function m(c){for(var d in c){var f=c[d];f instanceof Function&&(c[d]=f.bind(c))}return c}Object.defineProperty(l,"__esModule",{value:!0});l.deg2rad=function(c){return c*Math.PI/180};l.rad2deg=function(c){return 180*c/Math.PI};l.asin=k;l.acos=g;l.sign=Math.sign||function(c){return+(0<c)-+(0>c)||+c};l.log2=Math.log2||function(c){return Math.log(c)/Math.LN2};l.isPowerOfTwo=function(c){return 0===(c&c-1)};l.nextHighestPowerOfTwo=function(c){--c;for(var d=
1;32>d;d<<=1)c|=c>>d;return c+1};l.nextHighestPowerOfTen=function(c){return Math.pow(10,Math.ceil(Math.LOG10E*Math.log(c)))};l.fovx2fovy=function(c,d,f){return 2*Math.atan(f*Math.tan(.5*c)/d)};l.fovy2fovx=function(c,d,f){return 2*Math.atan(d*Math.tan(.5*c)/f)};l.makeOrthonormal=function(c,d,f){f=f||c;var p=e.vec3d.dot(c,d);e.vec3d.set3(c[0]-p*d[0],c[1]-p*d[1],c[2]-p*d[2],f);e.vec3d.normalize(f)};l.tangentFrame=function(c,d,f){Math.abs(c[0])>Math.abs(c[1])?e.vec3d.set3(0,1,0,d):e.vec3d.set3(1,0,0,
d);e.vec3d.cross(c,d,f);e.vec3d.normalize(d);e.vec3d.cross(f,c,d);e.vec3d.normalize(f)};l.cartesianToSpherical=function(c,d){var f=e.vec3d.length(c),p=k(c[2]/f);e.vec3d.set3(f,p,Math.atan2(c[1]/f,c[0]/f),d)};l.sphericalToCartesian=function(c,d){var f=c[0],p=c[1];c=c[2];var g=Math.cos(p);e.vec3d.set3(f*g*Math.cos(c),f*g*Math.sin(c),f*Math.sin(p),d)};l.lerp=function(c,d,f){return c+(d-c)*f};l.bilerp=function(c,d,f,e,g,k){c+=(d-c)*g;return c+(f+(e-f)*g-c)*k};l.slerp=function(c,p,g,k){void 0===k&&(k=
c);var u=e.vec3d.length(c),n=e.vec3d.length(p),m=e.vec3d.dot(c,p)/(u*n);if(.9999999999999999>m){var m=Math.acos(m),a=((1-g)*u+g*n)/Math.sin(m),n=a/n*Math.sin(g*m);e.vec3d.scale(c,a/u*Math.sin((1-g)*m),f);e.vec3d.scale(p,n,d);return e.vec3d.add(f,d,k)}return e.vec3d.lerp(c,p,g,k)};l.angle=function(c,p,u){c=e.vec3d.normalize(c,f);p=e.vec3d.normalize(p,d);var k=g(e.vec3d.dot(c,p));return u&&(c=e.vec3d.cross(c,p,r),0>e.vec3d.dot(c,u))?-k:k};l.clamp=n;l.isFinite=Number.isFinite||function(c){return"number"===
typeof c&&window.isFinite(c)};l.isNaN=Number.isNaN||function(c){return c!==c};l.makePiecewiseLinearFunction=function(c){var d=c.length;return function(f){if(f<=c[0][0])return c[0][1];if(f>=c[d-1][0])return c[d-1][1];for(var p=1;f>c[p][0];)p++;var e=c[p][0];f=(e-f)/(e-c[p-1][0]);return f*c[p-1][1]+(1-f)*c[p][1]}};l.vectorEquals=function(c,d){if(null==c||null==d)return c!==d;if(c.length!==d.length)return!1;for(var f=0;f<c.length;f++)if(c[f]!==d[f])return!1;return!0};l.floatEqualRelative=function(c,
d,f){void 0===f&&(f=1E-6);if(l.isNaN(c)||l.isNaN(d))return!1;if(c===d)return!0;var e=Math.abs(c-d),p=Math.abs(c),g=Math.abs(d);if(0===c||0===d||1E-12>p&&1E-12>g){if(e>.01*f)return!1}else if(e/(p+g)>f)return!1;return!0};l.floatEqualAbsolute=function(c,d,f){void 0===f&&(f=1E-6);return l.isNaN(c)||l.isNaN(d)?!1:(c>d?c-d:d-c)<=f};t=function(){function c(c,d){this.min=c;this.max=d;this.range=d-c}c.prototype.ndiff=function(c,d){void 0===d&&(d=0);return Math.ceil((c-d)/this.range)*this.range+d};c.prototype._normalize=
function(c,d,f,e){void 0===e&&(e=0);f-=e;f<c?f+=this.ndiff(c-f):f>d&&(f-=this.ndiff(f-d));return f+e};c.prototype.normalize=function(c,d){return this._normalize(this.min,this.max,c,d)};c.prototype.clamp=function(c,d){void 0===d&&(d=0);return n(c-d,this.min,this.max)+d};c.prototype.monotonic=function(c,d,f){return c<d?d:d+this.ndiff(c-d,f)};c.prototype.minimalMonotonic=function(c,d,f){return this._normalize(c,c+this.range,d,f)};c.prototype.center=function(c,d,f){d=this.monotonic(c,d,f);return this.normalize((c+
d)/2,f)};c.prototype.diff=function(c,d,f){return this.monotonic(c,d,f)-c};c.prototype.contains=function(c,d,f){d=this.minimalMonotonic(c,d);f=this.minimalMonotonic(c,f);return f>c&&f<d};return c}();l.Cyclical=t;l.planeFromPoints=function(c,d,f,g){e.vec3d.subtract(d,c,q);e.vec3d.subtract(f,c,v);e.vec3d.cross(q,v,g);e.vec3d.normalize(g,g);g[3]=-e.vec3d.dot(c,g)};var q=e.vec3d.create(),v=e.vec3d.create();l.cyclical2PI=m(new t(0,2*Math.PI));l.cyclicalPI=m(new t(-Math.PI,Math.PI));l.cyclicalDeg=m(new t(0,
360));var r=e.vec3d.create(),f=e.vec3d.create(),d=e.vec3d.create()})},"esri/views/3d/lib/gl-matrix":function(){define([],function(){var t={};(function(l,e){e(l,!0);e(l,!1)})(t,function(l,e){var k={};(function(){if("undefined"!=typeof Float32Array){var a=new Float32Array(1),b=new Int32Array(a.buffer);k.invsqrt=function(h){a[0]=h;b[0]=1597463007-(b[0]>>1);var c=a[0];return c*(1.5-.5*h*c*c)}}else k.invsqrt=function(a){return 1/Math.sqrt(a)}})();var g=Array;"undefined"!=typeof Float32Array&&(g=e?Float32Array:
Array);var n={create:function(a){var b=new g(3);a?(b[0]=a[0],b[1]=a[1],b[2]=a[2]):b[0]=b[1]=b[2]=0;return b},createFrom:function(a,b,h){var c=new g(3);c[0]=a;c[1]=b;c[2]=h;return c},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},set3:function(a,b,h,c){c[0]=a;c[1]=b;c[2]=h;return c},equal:function(a,b){return a===b||1E-6>Math.abs(a[0]-b[0])&&1E-6>Math.abs(a[1]-b[1])&&1E-6>Math.abs(a[2]-b[2])},max:function(a,b,h){h[0]=Math.max(a[0],b[0]);h[1]=Math.max(a[1],b[1]);h[2]=Math.max(a[2],b[2]);
return h},min:function(a,b,h){h[0]=Math.min(a[0],b[0]);h[1]=Math.min(a[1],b[1]);h[2]=Math.min(a[2],b[2]);return h},add:function(a,b,h){if(!h||a===h)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;h[0]=a[0]+b[0];h[1]=a[1]+b[1];h[2]=a[2]+b[2];return h},subtract:function(a,b,h){if(!h||a===h)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;h[0]=a[0]-b[0];h[1]=a[1]-b[1];h[2]=a[2]-b[2];return h},multiply:function(a,b,h){if(!h||a===h)return a[0]*=b[0],a[1]*=b[1],a[2]*=b[2],a;h[0]=a[0]*b[0];h[1]=a[1]*b[1];h[2]=a[2]*b[2];
return h},negate:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b},scale:function(a,b,h){if(!h||a===h)return a[0]*=b,a[1]*=b,a[2]*=b,a;h[0]=a[0]*b;h[1]=a[1]*b;h[2]=a[2]*b;return h},normalize:function(a,b){b||(b=a);var h=a[0],c=a[1];a=a[2];var d=Math.sqrt(h*h+c*c+a*a);if(!d)return b[0]=0,b[1]=0,b[2]=0,b;if(1===d)return b[0]=h,b[1]=c,b[2]=a,b;d=1/d;b[0]=h*d;b[1]=c*d;b[2]=a*d;return b},cross:function(a,b,h){h||(h=a);var c=a[0],d=a[1];a=a[2];var f=b[0],e=b[1];b=b[2];h[0]=d*b-a*e;h[1]=
a*f-c*b;h[2]=c*e-d*f;return h},length:function(a){var b=a[0],h=a[1];a=a[2];return Math.sqrt(b*b+h*h+a*a)},length2:function(a){var b=a[0],h=a[1];a=a[2];return b*b+h*h+a*a},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]},direction:function(a,b,h){h||(h=a);var c=a[0]-b[0],d=a[1]-b[1];a=a[2]-b[2];b=Math.sqrt(c*c+d*d+a*a);if(!b)return h[0]=0,h[1]=0,h[2]=0,h;b=1/b;h[0]=c*b;h[1]=d*b;h[2]=a*b;return h},lerp:function(a,b,h,c){c||(c=a);c[0]=a[0]+h*(b[0]-a[0]);c[1]=a[1]+h*(b[1]-a[1]);c[2]=a[2]+h*(b[2]-
a[2]);return c},dist:function(a,b){var h=b[0]-a[0],c=b[1]-a[1];a=b[2]-a[2];return Math.sqrt(h*h+c*c+a*a)},dist2:function(a,b){var h=b[0]-a[0],c=b[1]-a[1];a=b[2]-a[2];return h*h+c*c+a*a}},m=null,q=new g(4);n.unproject=function(a,b,h,c,d){d||(d=a);m||(m=w.create());var f=m;q[0]=2*(a[0]-c[0])/c[2]-1;q[1]=2*(a[1]-c[1])/c[3]-1;q[2]=2*a[2]-1;q[3]=1;w.multiply(h,b,f);if(!w.inverse(f))return null;w.multiplyVec4(f,q);if(0===q[3])return null;d[0]=q[0]/q[3];d[1]=q[1]/q[3];d[2]=q[2]/q[3];return d};var v=n.createFrom(1,
0,0),r=n.createFrom(0,1,0),f=n.createFrom(0,0,1),d=n.create();n.rotationTo=function(a,b,h){h||(h=x.create());var c=n.dot(a,b);if(1<=c)x.set(t,h);else if(-.999999>c)n.cross(v,a,d),1E-6>n.length(d)&&n.cross(r,a,d),1E-6>n.length(d)&&n.cross(f,a,d),n.normalize(d),x.fromAngleAxis(Math.PI,d,h);else{var c=Math.sqrt(2*(1+c)),e=1/c;n.cross(a,b,d);h[0]=d[0]*e;h[1]=d[1]*e;h[2]=d[2]*e;h[3]=.5*c;x.normalize(h)}1<h[3]?h[3]=1:-1>h[3]&&(h[3]=-1);return h};var c=n.create(),p=n.create();n.project=function(a,b,h,d){d||
(d=a);n.direction(b,h,c);n.subtract(a,b,p);a=n.dot(c,p);n.scale(c,a,d);n.add(d,b,d)};n.str=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"};var u={create:function(a){var b=new g(9);a?(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8]):b[0]=b[1]=b[2]=b[3]=b[4]=b[5]=b[6]=b[7]=b[8]=0;return b},createFrom:function(a,b,h,c,d,f,e,p,k){var y=new g(9);y[0]=a;y[1]=b;y[2]=h;y[3]=c;y[4]=d;y[5]=f;y[6]=e;y[7]=p;y[8]=k;return y},add:function(a,b,h){h||(h=a);h[0]=a[0]+
b[0];h[1]=a[1]+b[1];h[2]=a[2]+b[2];h[3]=a[3]+b[3];h[4]=a[4]+b[4];h[5]=a[5]+b[5];h[6]=a[6]+b[6];h[7]=a[7]+b[7];h[8]=a[8]+b[8];return h},subtract:function(a,b,h){h||(h=a);h[0]=a[0]-b[0];h[1]=a[1]-b[1];h[2]=a[2]-b[2];h[3]=a[3]-b[3];h[4]=a[4]-b[4];h[5]=a[5]-b[5];h[6]=a[6]-b[6];h[7]=a[7]-b[7];h[8]=a[8]-b[8];return h},determinant:function(a){var b=a[3],h=a[4],c=a[5],d=a[6],f=a[7],e=a[8];return a[0]*(e*h-c*f)+a[1]*(-e*b+c*d)+a[2]*(f*b-h*d)},inverse:function(a,b){var h=a[0],c=a[1],d=a[2],f=a[3],e=a[4],g=
a[5],p=a[6],k=a[7];a=a[8];var n=a*e-g*k,m=-a*f+g*p,l=k*f-e*p,r=h*n+c*m+d*l;if(!r)return null;r=1/r;b||(b=u.create());b[0]=n*r;b[1]=(-a*c+d*k)*r;b[2]=(g*c-d*e)*r;b[3]=m*r;b[4]=(a*h-d*p)*r;b[5]=(-g*h+d*f)*r;b[6]=l*r;b[7]=(-k*h+c*p)*r;b[8]=(e*h-c*f)*r;return b},multiply:function(a,b,h){h||(h=a);var c=a[0],d=a[1],f=a[2],e=a[3],g=a[4],p=a[5],k=a[6],n=a[7];a=a[8];var m=b[0],l=b[1],r=b[2],u=b[3],q=b[4],w=b[5],x=b[6],v=b[7];b=b[8];h[0]=m*c+l*e+r*k;h[1]=m*d+l*g+r*n;h[2]=m*f+l*p+r*a;h[3]=u*c+q*e+w*k;h[4]=u*
d+q*g+w*n;h[5]=u*f+q*p+w*a;h[6]=x*c+v*e+b*k;h[7]=x*d+v*g+b*n;h[8]=x*f+v*p+b*a;return h},multiplyVec2:function(a,b,h){h||(h=b);var c=b[0];b=b[1];h[0]=c*a[0]+b*a[3]+a[6];h[1]=c*a[1]+b*a[4]+a[7];return h},multiplyVec3:function(a,b,h){h||(h=b);var c=b[0],d=b[1];b=b[2];h[0]=c*a[0]+d*a[3]+b*a[6];h[1]=c*a[1]+d*a[4]+b*a[7];h[2]=c*a[2]+d*a[5]+b*a[8];return h},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},equal:function(a,b){return a===
b||1E-6>Math.abs(a[0]-b[0])&&1E-6>Math.abs(a[1]-b[1])&&1E-6>Math.abs(a[2]-b[2])&&1E-6>Math.abs(a[3]-b[3])&&1E-6>Math.abs(a[4]-b[4])&&1E-6>Math.abs(a[5]-b[5])&&1E-6>Math.abs(a[6]-b[6])&&1E-6>Math.abs(a[7]-b[7])&&1E-6>Math.abs(a[8]-b[8])},identity:function(a){a||(a=u.create());a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},transpose:function(a,b){if(!b||a===b){b=a[1];var h=a[2],c=a[5];a[1]=a[3];a[2]=a[6];a[3]=b;a[5]=a[7];a[6]=h;a[7]=c;return a}b[0]=a[0];b[1]=a[3];b[2]=a[6];
b[3]=a[1];b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b},toMat4:function(a,b){b||(b=w.create());b[15]=1;b[14]=0;b[13]=0;b[12]=0;b[11]=0;b[10]=a[8];b[9]=a[7];b[8]=a[6];b[7]=0;b[6]=a[5];b[5]=a[4];b[4]=a[3];b[3]=0;b[2]=a[2];b[1]=a[1];b[0]=a[0];return b},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"}},w={create:function(a){var b=new g(16);4===arguments.length?(b[0]=arguments[0],b[1]=arguments[1],b[2]=arguments[2],b[3]=arguments[3],
b[4]=arguments[4],b[5]=arguments[5],b[6]=arguments[6],b[7]=arguments[7],b[8]=arguments[8],b[9]=arguments[9],b[10]=arguments[10],b[11]=arguments[11],b[12]=arguments[12],b[13]=arguments[13],b[14]=arguments[14],b[15]=arguments[15]):a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b},createFrom:function(a,b,h,c,d,f,e,p,k,n,m,l,r,u,q,w){var y=new g(16);y[0]=a;y[1]=b;y[2]=
h;y[3]=c;y[4]=d;y[5]=f;y[6]=e;y[7]=p;y[8]=k;y[9]=n;y[10]=m;y[11]=l;y[12]=r;y[13]=u;y[14]=q;y[15]=w;return y},createFromMatrixRowMajor:function(a){var b=new g(16);b[0]=a[0];b[4]=a[1];b[8]=a[2];b[12]=a[3];b[1]=a[4];b[5]=a[5];b[9]=a[6];b[13]=a[7];b[2]=a[8];b[6]=a[9];b[10]=a[10];b[14]=a[11];b[3]=a[12];b[7]=a[13];b[11]=a[14];b[15]=a[15];return b},createFromMatrix:function(a){var b=new g(16);b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];
b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},setRowMajor:function(a,b){b[0]=a[0];b[4]=a[1];b[8]=a[2];b[12]=a[3];b[1]=a[4];b[5]=a[5];b[9]=a[6];b[13]=a[7];b[2]=a[8];b[6]=a[9];b[10]=a[10];b[14]=a[11];b[3]=a[12];b[7]=a[13];b[11]=a[14];b[15]=a[15];return b},equal:function(a,b){return a===
b||1E-6>Math.abs(a[0]-b[0])&&1E-6>Math.abs(a[1]-b[1])&&1E-6>Math.abs(a[2]-b[2])&&1E-6>Math.abs(a[3]-b[3])&&1E-6>Math.abs(a[4]-b[4])&&1E-6>Math.abs(a[5]-b[5])&&1E-6>Math.abs(a[6]-b[6])&&1E-6>Math.abs(a[7]-b[7])&&1E-6>Math.abs(a[8]-b[8])&&1E-6>Math.abs(a[9]-b[9])&&1E-6>Math.abs(a[10]-b[10])&&1E-6>Math.abs(a[11]-b[11])&&1E-6>Math.abs(a[12]-b[12])&&1E-6>Math.abs(a[13]-b[13])&&1E-6>Math.abs(a[14]-b[14])&&1E-6>Math.abs(a[15]-b[15])},identity:function(a){a||(a=w.create());a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=
0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},transpose:function(a,b){if(!b||a===b){b=a[1];var h=a[2],c=a[3],d=a[6],f=a[7],e=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=b;a[6]=a[9];a[7]=a[13];a[8]=h;a[9]=d;a[11]=a[14];a[12]=c;a[13]=f;a[14]=e;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b},determinant:function(a){var b=
a[0],h=a[1],c=a[2],d=a[3],f=a[4],e=a[5],g=a[6],p=a[7],k=a[8],n=a[9],m=a[10],l=a[11],r=a[12],u=a[13],q=a[14];a=a[15];return r*n*g*d-k*u*g*d-r*e*m*d+f*u*m*d+k*e*q*d-f*n*q*d-r*n*c*p+k*u*c*p+r*h*m*p-b*u*m*p-k*h*q*p+b*n*q*p+r*e*c*l-f*u*c*l-r*h*g*l+b*u*g*l+f*h*q*l-b*e*q*l-k*e*c*a+f*n*c*a+k*h*g*a-b*n*g*a-f*h*m*a+b*e*m*a},inverse:function(a,b){b||(b=a);var h=a[0],c=a[1],d=a[2],f=a[3],e=a[4],g=a[5],p=a[6],k=a[7],n=a[8],m=a[9],l=a[10],r=a[11],u=a[12],q=a[13],w=a[14];a=a[15];var x=h*g-c*e,v=h*p-d*e,t=h*k-f*
e,A=c*p-d*g,z=c*k-f*g,B=d*k-f*p,E=n*q-m*u,D=n*w-l*u,F=n*a-r*u,G=m*w-l*q,N=m*a-r*q,O=l*a-r*w,C=x*O-v*N+t*G+A*F-z*D+B*E;if(!C)return null;C=1/C;b[0]=(g*O-p*N+k*G)*C;b[1]=(-c*O+d*N-f*G)*C;b[2]=(q*B-w*z+a*A)*C;b[3]=(-m*B+l*z-r*A)*C;b[4]=(-e*O+p*F-k*D)*C;b[5]=(h*O-d*F+f*D)*C;b[6]=(-u*B+w*t-a*v)*C;b[7]=(n*B-l*t+r*v)*C;b[8]=(e*N-g*F+k*E)*C;b[9]=(-h*N+c*F-f*E)*C;b[10]=(u*z-q*t+a*x)*C;b[11]=(-n*z+m*t-r*x)*C;b[12]=(-e*G+g*D-p*E)*C;b[13]=(h*G-c*D+d*E)*C;b[14]=(-u*A+q*v-w*x)*C;b[15]=(n*A-m*v+l*x)*C;return b},
toRotationMat:function(a,b){b||(b=w.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},toMat3:function(a,b){b||(b=u.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b},toInverseMat3:function(a,b){var h=a[0],c=a[1],d=a[2],f=a[4],e=a[5],g=a[6],p=a[8],k=a[9];a=a[10];var n=a*e-g*k,m=-a*f+g*p,l=k*f-e*p,r=h*n+c*m+d*l;if(!r)return null;
r=1/r;b||(b=u.create());b[0]=n*r;b[1]=(-a*c+d*k)*r;b[2]=(g*c-d*e)*r;b[3]=m*r;b[4]=(a*h-d*p)*r;b[5]=(-g*h+d*f)*r;b[6]=l*r;b[7]=(-k*h+c*p)*r;b[8]=(e*h-c*f)*r;return b},multiply:function(a,b,h){h||(h=a);var c=a[0],d=a[1],f=a[2],e=a[3],g=a[4],p=a[5],k=a[6],n=a[7],m=a[8],r=a[9],l=a[10],u=a[11],q=a[12],w=a[13],x=a[14];a=a[15];var v=b[0],t=b[1],A=b[2],z=b[3];h[0]=v*c+t*g+A*m+z*q;h[1]=v*d+t*p+A*r+z*w;h[2]=v*f+t*k+A*l+z*x;h[3]=v*e+t*n+A*u+z*a;v=b[4];t=b[5];A=b[6];z=b[7];h[4]=v*c+t*g+A*m+z*q;h[5]=v*d+t*p+A*
r+z*w;h[6]=v*f+t*k+A*l+z*x;h[7]=v*e+t*n+A*u+z*a;v=b[8];t=b[9];A=b[10];z=b[11];h[8]=v*c+t*g+A*m+z*q;h[9]=v*d+t*p+A*r+z*w;h[10]=v*f+t*k+A*l+z*x;h[11]=v*e+t*n+A*u+z*a;v=b[12];t=b[13];A=b[14];z=b[15];h[12]=v*c+t*g+A*m+z*q;h[13]=v*d+t*p+A*r+z*w;h[14]=v*f+t*k+A*l+z*x;h[15]=v*e+t*n+A*u+z*a;return h},multiplyVec3:function(a,b,h){h||(h=b);var c=b[0],d=b[1];b=b[2];h[0]=a[0]*c+a[4]*d+a[8]*b+a[12];h[1]=a[1]*c+a[5]*d+a[9]*b+a[13];h[2]=a[2]*c+a[6]*d+a[10]*b+a[14];return h},multiplyVec4:function(a,b,h){h||(h=b);
var c=b[0],d=b[1],f=b[2];b=b[3];h[0]=a[0]*c+a[4]*d+a[8]*f+a[12]*b;h[1]=a[1]*c+a[5]*d+a[9]*f+a[13]*b;h[2]=a[2]*c+a[6]*d+a[10]*f+a[14]*b;h[3]=a[3]*c+a[7]*d+a[11]*f+a[15]*b;return h},translate:function(a,b,h){var c=b[0],d=b[1];b=b[2];var f,e,g,p,k,n,m,r,l,u,q,w;if(!h||a===h)return a[12]=a[0]*c+a[4]*d+a[8]*b+a[12],a[13]=a[1]*c+a[5]*d+a[9]*b+a[13],a[14]=a[2]*c+a[6]*d+a[10]*b+a[14],a[15]=a[3]*c+a[7]*d+a[11]*b+a[15],a;f=a[0];e=a[1];g=a[2];p=a[3];k=a[4];n=a[5];m=a[6];r=a[7];l=a[8];u=a[9];q=a[10];w=a[11];
h[0]=f;h[1]=e;h[2]=g;h[3]=p;h[4]=k;h[5]=n;h[6]=m;h[7]=r;h[8]=l;h[9]=u;h[10]=q;h[11]=w;h[12]=f*c+k*d+l*b+a[12];h[13]=e*c+n*d+u*b+a[13];h[14]=g*c+m*d+q*b+a[14];h[15]=p*c+r*d+w*b+a[15];return h},scale:function(a,b,h){var c=b[0],d=b[1];b=b[2];if(!h||a===h)return a[0]*=c,a[1]*=c,a[2]*=c,a[3]*=c,a[4]*=d,a[5]*=d,a[6]*=d,a[7]*=d,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;h[0]=a[0]*c;h[1]=a[1]*c;h[2]=a[2]*c;h[3]=a[3]*c;h[4]=a[4]*d;h[5]=a[5]*d;h[6]=a[6]*d;h[7]=a[7]*d;h[8]=a[8]*b;h[9]=a[9]*b;h[10]=a[10]*b;h[11]=a[11]*
b;h[12]=a[12];h[13]=a[13];h[14]=a[14];h[15]=a[15];return h},maxScale:function(a){return Math.max(Math.max(Math.sqrt(a[0]*a[0]+a[4]*a[4]+a[8]*a[8]),Math.sqrt(a[1]*a[1]+a[5]*a[5]+a[9]*a[9])),Math.sqrt(a[2]*a[2]+a[6]*a[6]+a[10]*a[10]))},rotate:function(a,b,h,c){var d=h[0],f=h[1];h=h[2];var e=Math.sqrt(d*d+f*f+h*h),g,p,k,y,n,m,r,l,u,q,w,x,v,t,z,B,E,D,F,G;if(!e)return null;1!==e&&(e=1/e,d*=e,f*=e,h*=e);g=Math.sin(b);p=Math.cos(b);k=1-p;b=a[0];e=a[1];y=a[2];n=a[3];m=a[4];r=a[5];l=a[6];u=a[7];q=a[8];w=a[9];
x=a[10];v=a[11];t=d*d*k+p;z=f*d*k+h*g;B=h*d*k-f*g;E=d*f*k-h*g;D=f*f*k+p;F=h*f*k+d*g;G=d*h*k+f*g;d=f*h*k-d*g;f=h*h*k+p;c?a!==c&&(c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=b*t+m*z+q*B;c[1]=e*t+r*z+w*B;c[2]=y*t+l*z+x*B;c[3]=n*t+u*z+v*B;c[4]=b*E+m*D+q*F;c[5]=e*E+r*D+w*F;c[6]=y*E+l*D+x*F;c[7]=n*E+u*D+v*F;c[8]=b*G+m*d+q*f;c[9]=e*G+r*d+w*f;c[10]=y*G+l*d+x*f;c[11]=n*G+u*d+v*f;return c},rotateX:function(a,b,h){var c=Math.sin(b);b=Math.cos(b);var d=a[4],f=a[5],e=a[6],g=a[7],p=a[8],k=a[9],n=
a[10],m=a[11];h?a!==h&&(h[0]=a[0],h[1]=a[1],h[2]=a[2],h[3]=a[3],h[12]=a[12],h[13]=a[13],h[14]=a[14],h[15]=a[15]):h=a;h[4]=d*b+p*c;h[5]=f*b+k*c;h[6]=e*b+n*c;h[7]=g*b+m*c;h[8]=d*-c+p*b;h[9]=f*-c+k*b;h[10]=e*-c+n*b;h[11]=g*-c+m*b;return h},rotateY:function(a,b,h){var c=Math.sin(b);b=Math.cos(b);var d=a[0],f=a[1],e=a[2],g=a[3],p=a[8],k=a[9],n=a[10],m=a[11];h?a!==h&&(h[4]=a[4],h[5]=a[5],h[6]=a[6],h[7]=a[7],h[12]=a[12],h[13]=a[13],h[14]=a[14],h[15]=a[15]):h=a;h[0]=d*b+p*-c;h[1]=f*b+k*-c;h[2]=e*b+n*-c;h[3]=
g*b+m*-c;h[8]=d*c+p*b;h[9]=f*c+k*b;h[10]=e*c+n*b;h[11]=g*c+m*b;return h},rotateZ:function(a,b,h){var c=Math.sin(b);b=Math.cos(b);var d=a[0],f=a[1],e=a[2],g=a[3],p=a[4],k=a[5],n=a[6],m=a[7];h?a!==h&&(h[8]=a[8],h[9]=a[9],h[10]=a[10],h[11]=a[11],h[12]=a[12],h[13]=a[13],h[14]=a[14],h[15]=a[15]):h=a;h[0]=d*b+p*c;h[1]=f*b+k*c;h[2]=e*b+n*c;h[3]=g*b+m*c;h[4]=d*-c+p*b;h[5]=f*-c+k*b;h[6]=e*-c+n*b;h[7]=g*-c+m*b;return h},frustum:function(a,b,h,c,d,f,e){e||(e=w.create());var g=b-a,p=c-h,k=f-d;e[0]=2*d/g;e[1]=
0;e[2]=0;e[3]=0;e[4]=0;e[5]=2*d/p;e[6]=0;e[7]=0;e[8]=(b+a)/g;e[9]=(c+h)/p;e[10]=-(f+d)/k;e[11]=-1;e[12]=0;e[13]=0;e[14]=-(f*d*2)/k;e[15]=0;return e},perspective:function(a,b,h,c,d){a=h*Math.tan(a*Math.PI/360);b*=a;return w.frustum(-b,b,-a,a,h,c,d)},ortho:function(a,b,h,c,d,f,e){e||(e=w.create());var g=b-a,p=c-h,k=f-d;e[0]=2/g;e[1]=0;e[2]=0;e[3]=0;e[4]=0;e[5]=2/p;e[6]=0;e[7]=0;e[8]=0;e[9]=0;e[10]=-2/k;e[11]=0;e[12]=-(a+b)/g;e[13]=-(c+h)/p;e[14]=-(f+d)/k;e[15]=1;return e},lookAt:function(a,b,h,c){c||
(c=w.create());var d,f,e,g,p,k,n,m,r=a[0],l=a[1];a=a[2];e=h[0];g=h[1];f=h[2];n=b[0];h=b[1];d=b[2];if(r===n&&l===h&&a===d)return w.identity(c);b=r-n;h=l-h;n=a-d;m=1/Math.sqrt(b*b+h*h+n*n);b*=m;h*=m;n*=m;d=g*n-f*h;f=f*b-e*n;e=e*h-g*b;(m=Math.sqrt(d*d+f*f+e*e))?(m=1/m,d*=m,f*=m,e*=m):e=f=d=0;g=h*e-n*f;p=n*d-b*e;k=b*f-h*d;(m=Math.sqrt(g*g+p*p+k*k))?(m=1/m,g*=m,p*=m,k*=m):k=p=g=0;c[0]=d;c[1]=g;c[2]=b;c[3]=0;c[4]=f;c[5]=p;c[6]=h;c[7]=0;c[8]=e;c[9]=k;c[10]=n;c[11]=0;c[12]=-(d*r+f*l+e*a);c[13]=-(g*r+p*l+
k*a);c[14]=-(b*r+h*l+n*a);c[15]=1;return c},fromRotationTranslation:function(a,b,h){h||(h=w.create());var c=a[0],d=a[1],f=a[2],e=a[3],g=c+c,p=d+d,k=f+f;a=c*g;var m=c*p,c=c*k,n=d*p,d=d*k,f=f*k,g=e*g,p=e*p,e=e*k;h[0]=1-(n+f);h[1]=m+e;h[2]=c-p;h[3]=0;h[4]=m-e;h[5]=1-(a+f);h[6]=d+g;h[7]=0;h[8]=c+p;h[9]=d-g;h[10]=1-(a+n);h[11]=0;h[12]=b[0];h[13]=b[1];h[14]=b[2];h[15]=1;return h},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+
a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"}},x={create:function(a){var b=new g(4);a?(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]):b[0]=b[1]=b[2]=b[3]=0;return b},createFrom:function(a,b,h,c){var d=new g(4);d[0]=a;d[1]=b;d[2]=h;d[3]=c;return d},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},equal:function(a,b){return a===b||1E-6>Math.abs(a[0]-b[0])&&1E-6>Math.abs(a[1]-b[1])&&1E-6>Math.abs(a[2]-b[2])&&1E-6>Math.abs(a[3]-b[3])},identity:function(a){a||(a=x.create());
a[0]=0;a[1]=0;a[2]=0;a[3]=1;return a}},t=x.identity();x.calculateW=function(a,b){var h=a[0],c=a[1],d=a[2];if(!b||a===b)return a[3]=-Math.sqrt(Math.abs(1-h*h-c*c-d*d)),a;b[0]=h;b[1]=c;b[2]=d;b[3]=-Math.sqrt(Math.abs(1-h*h-c*c-d*d));return b};x.dot=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};x.inverse=function(a,b){var h=a[0],c=a[1],d=a[2],f=a[3],h=(h=h*h+c*c+d*d+f*f)?1/h:0;if(!b||a===b)return a[0]*=-h,a[1]*=-h,a[2]*=-h,a[3]*=h,a;b[0]=-a[0]*h;b[1]=-a[1]*h;b[2]=-a[2]*h;b[3]=a[3]*h;
return b};x.conjugate=function(a,b){if(!b||a===b)return a[0]*=-1,a[1]*=-1,a[2]*=-1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b};x.length=function(a){var b=a[0],h=a[1],c=a[2];a=a[3];return Math.sqrt(b*b+h*h+c*c+a*a)};x.normalize=function(a,b){b||(b=a);var h=a[0],c=a[1],d=a[2];a=a[3];var f=Math.sqrt(h*h+c*c+d*d+a*a);if(0===f)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;f=1/f;b[0]=h*f;b[1]=c*f;b[2]=d*f;b[3]=a*f;return b};x.add=function(a,b,h){if(!h||a===h)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a[3]+=
b[3],a;h[0]=a[0]+b[0];h[1]=a[1]+b[1];h[2]=a[2]+b[2];h[3]=a[3]+b[3];return h};x.multiply=function(a,b,h){h||(h=a);var c=a[0],d=a[1],f=a[2];a=a[3];var e=b[0],g=b[1],p=b[2];b=b[3];h[0]=c*b+a*e+d*p-f*g;h[1]=d*b+a*g+f*e-c*p;h[2]=f*b+a*p+c*g-d*e;h[3]=a*b-c*e-d*g-f*p;return h};x.multiplyVec3=function(a,b,h){h||(h=b);var c=b[0],d=b[1],f=b[2];b=a[0];var e=a[1],g=a[2];a=a[3];var p=a*c+e*f-g*d,k=a*d+g*c-b*f,m=a*f+b*d-e*c,c=-b*c-e*d-g*f;h[0]=p*a+c*-b+k*-g-m*-e;h[1]=k*a+c*-e+m*-b-p*-g;h[2]=m*a+c*-g+p*-e-k*-b;
return h};x.scale=function(a,b,c){if(!c||a===c)return a[0]*=b,a[1]*=b,a[2]*=b,a[3]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;c[3]=a[3]*b;return c};x.toMat3=function(a,b){b||(b=u.create());var c=a[0],d=a[1],f=a[2],e=a[3],g=c+c,p=d+d,k=f+f;a=c*g;var m=c*p,c=c*k,n=d*p,d=d*k,f=f*k,g=e*g,p=e*p,e=e*k;b[0]=1-(n+f);b[1]=m+e;b[2]=c-p;b[3]=m-e;b[4]=1-(a+f);b[5]=d+g;b[6]=c+p;b[7]=d-g;b[8]=1-(a+n);return b};x.toMat4=function(a,b){b||(b=w.create());var c=a[0],d=a[1],f=a[2],e=a[3],g=c+c,p=d+d,k=f+f;a=c*g;var m=
c*p,c=c*k,n=d*p,d=d*k,f=f*k,g=e*g,p=e*p,e=e*k;b[0]=1-(n+f);b[1]=m+e;b[2]=c-p;b[3]=0;b[4]=m-e;b[5]=1-(a+f);b[6]=d+g;b[7]=0;b[8]=c+p;b[9]=d-g;b[10]=1-(a+n);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};x.slerp=function(a,b,c,d){d||(d=a);var h=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3],f,e;if(1<=Math.abs(h))return d!==a&&(d[0]=a[0],d[1]=a[1],d[2]=a[2],d[3]=a[3]),d;f=Math.acos(h);e=Math.sqrt(1-h*h);if(.001>Math.abs(e))return d[0]=.5*a[0]+.5*b[0],d[1]=.5*a[1]+.5*b[1],d[2]=.5*a[2]+.5*b[2],d[3]=.5*a[3]+
.5*b[3],d;h=Math.sin((1-c)*f)/e;c=Math.sin(c*f)/e;d[0]=a[0]*h+b[0]*c;d[1]=a[1]*h+b[1]*c;d[2]=a[2]*h+b[2]*c;d[3]=a[3]*h+b[3]*c;return d};x.fromRotationMatrix=function(a,b){b||(b=x.create());var c=a[0]+a[4]+a[8],d;if(0<c)d=Math.sqrt(c+1),b[3]=.5*d,d=.5/d,b[0]=(a[7]-a[5])*d,b[1]=(a[2]-a[6])*d,b[2]=(a[3]-a[1])*d;else{d=x.fromRotationMatrix.s_iNext=x.fromRotationMatrix.s_iNext||[1,2,0];c=0;a[4]>a[0]&&(c=1);a[8]>a[3*c+c]&&(c=2);var f=d[c],e=d[f];d=Math.sqrt(a[3*c+c]-a[3*f+f]-a[3*e+e]+1);b[c]=.5*d;d=.5/
d;b[3]=(a[3*e+f]-a[3*f+e])*d;b[f]=(a[3*f+c]+a[3*c+f])*d;b[e]=(a[3*e+c]+a[3*c+e])*d}return b};u.toQuat4=x.fromRotationMatrix;(function(){var a=u.create();x.fromAxes=function(b,c,d,f){a[0]=c[0];a[3]=c[1];a[6]=c[2];a[1]=d[0];a[4]=d[1];a[7]=d[2];a[2]=b[0];a[5]=b[1];a[8]=b[2];return x.fromRotationMatrix(a,f)}})();x.identity=function(a){a||(a=x.create());a[0]=0;a[1]=0;a[2]=0;a[3]=1;return a};x.fromAngleAxis=function(a,b,c){c||(c=x.create());a*=.5;var d=Math.sin(a);c[3]=Math.cos(a);c[0]=d*b[0];c[1]=d*b[1];
c[2]=d*b[2];return c};x.toAngleAxis=function(a,b){b||(b=a);var c=a[0]*a[0]+a[1]*a[1]+a[2]*a[2];0<c?(b[3]=2*Math.acos(a[3]),c=k.invsqrt(c),b[0]=a[0]*c,b[1]=a[1]*c,b[2]=a[2]*c):(b[3]=0,b[0]=1,b[1]=0,b[2]=0);return b};x.str=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"};var B={create:function(a){var b=new g(4);a?(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]):b[0]=b[1]=b[2]=b[3]=0;return b},createFrom:function(a,b,c,d){var h=new g(4);h[0]=a;h[1]=b;h[2]=c;h[3]=d;return h},set:function(a,b){b[0]=
a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},equal:function(a,b){return a===b||1E-6>Math.abs(a[0]-b[0])&&1E-6>Math.abs(a[1]-b[1])&&1E-6>Math.abs(a[2]-b[2])&&1E-6>Math.abs(a[3]-b[3])},identity:function(a){a||(a=B.create());a[0]=1;a[1]=0;a[2]=0;a[3]=1;return a},transpose:function(a,b){if(!b||a===b)return b=a[1],a[1]=a[2],a[2]=b,a;b[0]=a[0];b[1]=a[2];b[2]=a[1];b[3]=a[3];return b},determinant:function(a){return a[0]*a[3]-a[2]*a[1]},inverse:function(a,b){b||(b=a);var c=a[0],d=a[1],f=a[2];a=a[3];var e=
c*a-f*d;if(!e)return null;e=1/e;b[0]=a*e;b[1]=-d*e;b[2]=-f*e;b[3]=c*e;return b},multiply:function(a,b,c){c||(c=a);var d=a[0],h=a[1],f=a[2];a=a[3];c[0]=d*b[0]+h*b[2];c[1]=d*b[1]+h*b[3];c[2]=f*b[0]+a*b[2];c[3]=f*b[1]+a*b[3];return c},rotate:function(a,b,c){c||(c=a);var d=a[0],h=a[1],f=a[2];a=a[3];var e=Math.sin(b);b=Math.cos(b);c[0]=d*b+h*e;c[1]=d*-e+h*b;c[2]=f*b+a*e;c[3]=f*-e+a*b;return c},multiplyVec2:function(a,b,c){c||(c=b);var d=b[0];b=b[1];c[0]=d*a[0]+b*a[1];c[1]=d*a[2]+b*a[3];return c},scale:function(a,
b,c){c||(c=a);var d=a[1],h=a[2],f=a[3],e=b[0];b=b[1];c[0]=a[0]*e;c[1]=d*b;c[2]=h*e;c[3]=f*b;return c},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};e=e?"":"d";l["glMath"+e]=k;l["vec2"+e]={create:function(a){var b=new g(2);a?(b[0]=a[0],b[1]=a[1]):(b[0]=0,b[1]=0);return b},createFrom:function(a,b){var c=new g(2);c[0]=a;c[1]=b;return c},add:function(a,b,c){c||(c=b);c[0]=a[0]+b[0];c[1]=a[1]+b[1];return c},subtract:function(a,b,c){c||(c=b);c[0]=a[0]-b[0];c[1]=a[1]-b[1];return c},multiply:function(a,
b,c){c||(c=b);c[0]=a[0]*b[0];c[1]=a[1]*b[1];return c},divide:function(a,b,c){c||(c=b);c[0]=a[0]/b[0];c[1]=a[1]/b[1];return c},scale:function(a,b,c){c||(c=a);c[0]=a[0]*b;c[1]=a[1]*b;return c},dist:function(a,b){var c=b[0]-a[0];a=b[1]-a[1];return Math.sqrt(c*c+a*a)},dist2:function(a,b){var c=b[0]-a[0];a=b[1]-a[1];return c*c+a*a},set:function(a,b){b[0]=a[0];b[1]=a[1];return b},set2:function(a,b,c){c[0]=a;c[1]=b;return c},equal:function(a,b){return a===b||1E-6>Math.abs(a[0]-b[0])&&1E-6>Math.abs(a[1]-
b[1])},negate:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];return b},normalize:function(a,b){b||(b=a);var c=a[0]*a[0]+a[1]*a[1];0<c?(c=Math.sqrt(c),b[0]=a[0]/c,b[1]=a[1]/c):b[0]=b[1]=0;return b},cross:function(a,b,c){a=a[0]*b[1]-a[1]*b[0];if(!c)return a;c[0]=c[1]=0;c[2]=a;return c},length:function(a){var b=a[0];a=a[1];return Math.sqrt(b*b+a*a)},length2:function(a){var b=a[0];a=a[1];return b*b+a*a},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]},direction:function(a,b,c){c||(c=a);var d=a[0]-b[0];a=a[1]-
b[1];b=d*d+a*a;if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/Math.sqrt(b);c[0]=d*b;c[1]=a*b;return c},lerp:function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);return d},str:function(a){return"["+a[0]+", "+a[1]+"]"}};l["vec3"+e]=n;l["vec4"+e]={create:function(a){var b=new g(4);a?(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]):(b[0]=0,b[1]=0,b[2]=0,b[3]=0);return b},createFrom:function(a,b,c,d){var f=new g(4);f[0]=a;f[1]=b;f[2]=c;f[3]=d;return f},add:function(a,b,c){c||(c=b);c[0]=a[0]+b[0];
c[1]=a[1]+b[1];c[2]=a[2]+b[2];c[3]=a[3]+b[3];return c},subtract:function(a,b,c){c||(c=b);c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];c[3]=a[3]-b[3];return c},multiply:function(a,b,c){c||(c=b);c[0]=a[0]*b[0];c[1]=a[1]*b[1];c[2]=a[2]*b[2];c[3]=a[3]*b[3];return c},divide:function(a,b,c){c||(c=b);c[0]=a[0]/b[0];c[1]=a[1]/b[1];c[2]=a[2]/b[2];c[3]=a[3]/b[3];return c},scale:function(a,b,c){c||(c=a);c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;c[3]=a[3]*b;return c},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];
b[3]=a[3];return b},set4:function(a,b,c,d,f){f[0]=a;f[1]=b;f[2]=c;f[3]=d;return f},equal:function(a,b){return a===b||1E-6>Math.abs(a[0]-b[0])&&1E-6>Math.abs(a[1]-b[1])&&1E-6>Math.abs(a[2]-b[2])&&1E-6>Math.abs(a[3]-b[3])},negate:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=-a[3];return b},length:function(a){var b=a[0],c=a[1],d=a[2];a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)},length2:function(a){var b=a[0],c=a[1],d=a[2];a=a[3];return b*b+c*c+d*d+a*a},dot:function(a,b){return a[0]*b[0]+
a[1]*b[1]+a[2]*b[2]+a[3]*b[3]},lerp:function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);d[3]=a[3]+c*(b[3]-a[3]);return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};l["mat2"+e]=B;l["mat3"+e]=u;l["mat4"+e]=w;l["quat4"+e]=x});return t})},"esri/views/3d/support/buffer/typedArrayUtil":function(){define(["require","exports"],function(t,l){Object.defineProperty(l,"__esModule",{value:!0});l.forEach=function(e,k){if(e.forEach)e.forEach(k);
else for(var g=0;g<e.length;g++)k(e[g],g,e)};l.slice=function(e,k,g){if(e.slice)return e.slice(k,g);void 0===k?k=0:(0>k&&(k+=e.length),k=Math.min(e.length,Math.max(0,k)));void 0===g?g=e.length:(0>g&&(g+=e.length),g=Math.min(e.length,Math.max(0,g)));g=Math.max(0,g-k);for(var n=new e.constructor(g),m=0;m<g;m++)n[m]=e[k+m];return n};l.isArrayBuffer=function(e){return e instanceof ArrayBuffer||e&&e.constructor&&"ArrayBuffer"===e.constructor.name};l.isInt8Array=function(e){return e instanceof Int8Array||
e&&e.constructor&&"Int8Array"===e.constructor.name};l.isUint8Array=function(e){return e instanceof Uint8Array||e&&e.constructor&&"Uint8Array"===e.constructor.name};l.isInt16Array=function(e){return e instanceof Int16Array||e&&e.constructor&&"Int16Array"===e.constructor.name};l.isUint16Array=function(e){return e instanceof Uint16Array||e&&e.constructor&&"Uint16Array"===e.constructor.name};l.isInt32Array=function(e){return e instanceof Int32Array||e&&e.constructor&&"Int32Array"===e.constructor.name};
l.isUint32Array=function(e){return e instanceof Uint32Array||e&&e.constructor&&"Uint32Array"===e.constructor.name};l.isFloat32Array=function(e){return e instanceof Float32Array||e&&e.constructor&&"Float32Array"===e.constructor.name};l.isFloat64Array=function(e){return e instanceof Float64Array||e&&e.constructor&&"Float64Array"===e.constructor.name}})},"esri/views/3d/support/buffer/workerHelper":function(){define(["require","exports","../../../../core/tsSupport/assignHelper","./BufferView","./InterleavedLayout"],
function(t,l,e,k,g){function n(g){var k=[];g.fields.forEach(function(f,d){var c=f.constructor;f=e({},f,{constructor:c.ElementType+"_"+c.ElementCount});k.push([d,f])});return{stride:g.stride,fields:k,fieldNames:g.fieldNames}}function m(k){var m=g.newLayout();m.stride=k.stride;m.fieldNames=k.fieldNames;k.fields.forEach(function(f){return m.fields.set(f[0],e({},f[1],{constructor:q.get(f[1].constructor)}))});return m}Object.defineProperty(l,"__esModule",{value:!0});l.packInterleavedBuffer=function(e,
g){g.push(e.buffer);return{buffer:e.buffer,layout:n(e.layout)}};l.unpackInterleavedBuffer=function(e){return m(e.layout).createView(e.buffer)};l.packLayout=n;l.unpackLayout=m;t=[k.BufferViewFloat,k.BufferViewVec2f,k.BufferViewVec3f,k.BufferViewVec4f,k.BufferViewMat4f,k.BufferViewFloat64,k.BufferViewVec2f64,k.BufferViewVec3f64,k.BufferViewVec4f64,k.BufferViewUint8,k.BufferViewVec2u8,k.BufferViewVec3u8,k.BufferViewVec4u8,k.BufferViewUint16,k.BufferViewVec2u16,k.BufferViewVec3u16,k.BufferViewVec4u16,
k.BufferViewUint32,k.BufferViewVec2u32,k.BufferViewVec3u32,k.BufferViewVec4u32,k.BufferViewInt8,k.BufferViewVec2i8,k.BufferViewVec3i8,k.BufferViewVec4i8,k.BufferViewInt16,k.BufferViewVec2i16,k.BufferViewVec3i16,k.BufferViewVec4i16,k.BufferViewInt32,k.BufferViewVec2i32,k.BufferViewVec3i32,k.BufferViewVec4i32];var q=new Map;t.forEach(function(e){return q.set(e.ElementType+"_"+e.ElementCount,e)})})},"esri/views/3d/support/buffer/BufferView":function(){define("require exports ../../../../core/tsSupport/extendsHelper ./internals/Mat3 ./internals/Mat4 ./internals/Single ./internals/Vec2 ./internals/Vec3 ./internals/Vec4".split(" "),
function(t,l,e,k,g,n,m,q,v){Object.defineProperty(l,"__esModule",{value:!0});t=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Float32Array,d,c,f)||this;d.elementType="f32";return d}e(f,g);f.ElementType="f32";return f}(n.BufferViewSingle);l.BufferViewFloat=t;t=function(g){function f(d,c,f,e){void 0===c&&(c=0);d=g.call(this,Float32Array,d,c,f,e)||this;d.elementType="f32";return d}e(f,g);f.ElementType="f32";return f}(m.BufferViewVec2Impl);l.BufferViewVec2f=t;t=function(g){function f(d,
c,f,e){void 0===c&&(c=0);d=g.call(this,Float32Array,d,c,f,e)||this;d.elementType="f32";return d}e(f,g);f.ElementType="f32";return f}(q.BufferViewVec3Impl);l.BufferViewVec3f=t;t=function(g){function f(d,c,f,e){void 0===c&&(c=0);d=g.call(this,Float32Array,d,c,f,e)||this;d.elementType="f32";return d}e(f,g);f.ElementType="f32";return f}(v.BufferViewVec4Impl);l.BufferViewVec4f=t;k=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Float32Array,d,c,f)||this;d.elementType="f32";return d}e(f,g);
f.ElementType="f32";return f}(k.BufferViewMat3);l.BufferViewMat3f=k;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Float32Array,d,c,f)||this;d.elementType="f32";return d}e(f,g);f.ElementType="f32";return f}(g.BufferViewMat4);l.BufferViewMat4f=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Float64Array,d,c,f)||this;d.elementType="f64";return d}e(f,g);f.ElementType="f64";return f}(n.BufferViewSingle);l.BufferViewFloat64=g;g=function(g){function f(d,c,f){void 0===
c&&(c=0);d=g.call(this,Float64Array,d,c,f)||this;d.elementType="f64";return d}e(f,g);f.ElementType="f64";return f}(m.BufferViewVec2Impl);l.BufferViewVec2f64=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Float64Array,d,c,f)||this;d.elementType="f64";return d}e(f,g);f.ElementType="f64";return f}(q.BufferViewVec3Impl);l.BufferViewVec3f64=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Float64Array,d,c,f)||this;d.elementType="f64";return d}e(f,g);f.ElementType="f64";
return f}(v.BufferViewVec4Impl);l.BufferViewVec4f64=g;g=function(g){function f(d,c,f,e){void 0===c&&(c=0);d=g.call(this,Uint8Array,d,c,f,e)||this;d.elementType="u8";return d}e(f,g);f.ElementType="u8";return f}(n.BufferViewSingle);l.BufferViewUint8=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Uint8Array,d,c,f)||this;d.elementType="u8";return d}e(f,g);f.ElementType="u8";return f}(m.BufferViewVec2Impl);l.BufferViewVec2u8=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,
Uint8Array,d,c,f)||this;d.elementType="u8";return d}e(f,g);f.ElementType="u8";return f}(q.BufferViewVec3Impl);l.BufferViewVec3u8=g;g=function(g){function f(d,c,f,e){void 0===c&&(c=0);d=g.call(this,Uint8Array,d,c,f,e)||this;d.elementType="u8";return d}e(f,g);f.ElementType="u8";return f}(v.BufferViewVec4Impl);l.BufferViewVec4u8=g;g=function(g){function f(d,c,f,e){void 0===c&&(c=0);d=g.call(this,Uint16Array,d,c,f,e)||this;d.elementType="u16";return d}e(f,g);f.ElementType="u16";return f}(n.BufferViewSingle);
l.BufferViewUint16=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Uint16Array,d,c,f)||this;d.elementType="u16";return d}e(f,g);f.ElementType="u16";return f}(m.BufferViewVec2Impl);l.BufferViewVec2u16=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Uint16Array,d,c,f)||this;d.elementType="u16";return d}e(f,g);f.ElementType="u16";return f}(q.BufferViewVec3Impl);l.BufferViewVec3u16=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Uint16Array,d,c,f)||
this;d.elementType="u16";return d}e(f,g);f.ElementType="u16";return f}(v.BufferViewVec4Impl);l.BufferViewVec4u16=g;g=function(g){function f(d,c,f,e){void 0===c&&(c=0);d=g.call(this,Uint32Array,d,c,f,e)||this;d.elementType="u32";return d}e(f,g);f.ElementType="u32";return f}(n.BufferViewSingle);l.BufferViewUint32=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Uint32Array,d,c,f)||this;d.elementType="u32";return d}e(f,g);f.ElementType="u32";return f}(m.BufferViewVec2Impl);l.BufferViewVec2u32=
g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Uint32Array,d,c,f)||this;d.elementType="u32";return d}e(f,g);f.ElementType="u32";return f}(q.BufferViewVec3Impl);l.BufferViewVec3u32=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Uint32Array,d,c,f)||this;d.elementType="u32";return d}e(f,g);f.ElementType="u32";return f}(v.BufferViewVec4Impl);l.BufferViewVec4u32=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int8Array,d,c,f)||this;d.elementType=
"i8";return d}e(f,g);f.ElementType="i8";return f}(n.BufferViewSingle);l.BufferViewInt8=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int8Array,d,c,f)||this;d.elementType="i8";return d}e(f,g);f.ElementType="i8";return f}(m.BufferViewVec2Impl);l.BufferViewVec2i8=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int8Array,d,c,f)||this;d.elementType="i8";return d}e(f,g);f.ElementType="i8";return f}(q.BufferViewVec3Impl);l.BufferViewVec3i8=g;g=function(g){function f(d,
c,f){void 0===c&&(c=0);d=g.call(this,Int8Array,d,c,f)||this;d.elementType="i8";return d}e(f,g);f.ElementType="i8";return f}(v.BufferViewVec4Impl);l.BufferViewVec4i8=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int16Array,d,c,f)||this;d.elementType="i16";return d}e(f,g);f.ElementType="i16";return f}(n.BufferViewSingle);l.BufferViewInt16=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int16Array,d,c,f)||this;d.elementType="i16";return d}e(f,g);f.ElementType="i16";
return f}(m.BufferViewVec2Impl);l.BufferViewVec2i16=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int16Array,d,c,f)||this;d.elementType="i16";return d}e(f,g);f.ElementType="i16";return f}(q.BufferViewVec3Impl);l.BufferViewVec3i16=g;g=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int16Array,d,c,f)||this;d.elementType="i16";return d}e(f,g);f.ElementType="i16";return f}(v.BufferViewVec4Impl);l.BufferViewVec4i16=g;n=function(g){function f(d,c,f){void 0===c&&(c=0);d=
g.call(this,Int32Array,d,c,f)||this;d.elementType="i32";return d}e(f,g);f.ElementType="i32";return f}(n.BufferViewSingle);l.BufferViewInt32=n;m=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int32Array,d,c,f)||this;d.elementType="i32";return d}e(f,g);f.ElementType="i32";return f}(m.BufferViewVec2Impl);l.BufferViewVec2i32=m;q=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int32Array,d,c,f)||this;d.elementType="i32";return d}e(f,g);f.ElementType="i32";return f}(q.BufferViewVec3Impl);
l.BufferViewVec3i32=q;v=function(g){function f(d,c,f){void 0===c&&(c=0);d=g.call(this,Int32Array,d,c,f)||this;d.elementType="i32";return d}e(f,g);f.ElementType="i32";return f}(v.BufferViewVec4Impl);l.BufferViewVec4i32=v})},"esri/views/3d/support/buffer/internals/Mat3":function(){define(["require","exports"],function(t,l){Object.defineProperty(l,"__esModule",{value:!0});t=function(){function e(e,g,n,m){void 0===n&&(n=0);this.TypedArrayConstructor=e;this.elementCount=9;e=this.TypedArrayConstructor;
void 0===m&&(m=9*e.BYTES_PER_ELEMENT);this.data=new e(g,0===g.byteLength?0:n);this.elementStride=m/e.BYTES_PER_ELEMENT}e.prototype.getMat=function(e,g){e*=this.elementStride;for(var k=0;9>k;k++)g[k]=this.data[e+k];return g};e.prototype.setMat=function(e,g){e*=this.elementStride;for(var k=0;9>k;k++)this.data[e+k]=g[k]};e.prototype.get=function(e,g){return this.data[e*this.elementStride+g]};e.prototype.set=function(e,g,n){this.data[e*this.elementStride+g]=n};Object.defineProperty(e.prototype,"count",
{get:function(){return Math.ceil(this.data.length/this.elementStride)},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"buffer",{get:function(){return this.data.buffer},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"typedBuffer",{get:function(){return this.data},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"stride",{get:function(){return this.elementStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT},enumerable:!0,configurable:!0});e.ElementCount=
9;return e}();l.BufferViewMat3=t})},"esri/views/3d/support/buffer/internals/Mat4":function(){define(["require","exports"],function(t,l){Object.defineProperty(l,"__esModule",{value:!0});t=function(){function e(e,g,n,m){void 0===n&&(n=0);this.TypedArrayConstructor=e;this.elementCount=16;e=this.TypedArrayConstructor;void 0===m&&(m=16*e.BYTES_PER_ELEMENT);this.data=new e(g,0===g.byteLength?0:n);this.elementStride=m/e.BYTES_PER_ELEMENT}e.prototype.getMat=function(e,g){e*=this.elementStride;for(var k=0;16>
k;k++)g[k]=this.data[e+k];return g};e.prototype.setMat=function(e,g){e*=this.elementStride;for(var k=0;16>k;k++)this.data[e+k]=g[k]};e.prototype.get=function(e,g){return this.data[e*this.elementStride+g]};e.prototype.set=function(e,g,n){this.data[e*this.elementStride+g]=n};Object.defineProperty(e.prototype,"count",{get:function(){return Math.ceil(this.data.length/this.elementStride)},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"buffer",{get:function(){return this.data.buffer},
enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"typedBuffer",{get:function(){return this.data},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"stride",{get:function(){return this.elementStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT},enumerable:!0,configurable:!0});e.ElementCount=16;return e}();l.BufferViewMat4=t})},"esri/views/3d/support/buffer/internals/Single":function(){define(["require","exports"],function(t,l){Object.defineProperty(l,"__esModule",{value:!0});
t=function(){function e(e,g,n,m,l){void 0===n&&(n=0);this.TypedArrayConstructor=e;this.elementCount=1;e=this.TypedArrayConstructor;void 0===m&&(m=e.BYTES_PER_ELEMENT);var k=0===g.byteLength?0:n;this.data=null==l?new e(g,k):new e(g,k,(l-n)/e.BYTES_PER_ELEMENT);this.elementStride=m/e.BYTES_PER_ELEMENT}e.prototype.get=function(e){return this.data[e*this.elementStride]};e.prototype.set=function(e,g){this.data[e*this.elementStride]=g};Object.defineProperty(e.prototype,"count",{get:function(){return Math.ceil(this.data.length/
this.elementStride)},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"buffer",{get:function(){return this.data.buffer},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"typedBuffer",{get:function(){return this.data},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"stride",{get:function(){return this.elementStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT},enumerable:!0,configurable:!0});e.ElementCount=1;return e}();l.BufferViewSingle=t})},"esri/views/3d/support/buffer/internals/Vec2":function(){define(["require",
"exports","../../../lib/gl-matrix"],function(t,l,e){Object.defineProperty(l,"__esModule",{value:!0});t=function(){function k(e,k,m,l,v){void 0===m&&(m=0);this.TypedArrayConstructor=e;this.elementCount=2;e=this.TypedArrayConstructor;void 0===l&&(l=2*e.BYTES_PER_ELEMENT);var g=0===k.byteLength?0:m;this.data=null==v?new e(k,g):new e(k,g,(v-m)/e.BYTES_PER_ELEMENT);this.elementStride=l/e.BYTES_PER_ELEMENT}k.prototype.getVec=function(g,k){return e.vec2d.set2(this.data[g*this.elementStride],this.data[g*
this.elementStride+1],k)};k.prototype.setVec=function(e,k){this.data[e*this.elementStride]=k[0];this.data[e*this.elementStride+1]=k[1]};k.prototype.get=function(e,k){return this.data[e*this.elementStride+k]};k.prototype.set=function(e,k,m){this.data[e*this.elementStride+k]=m};Object.defineProperty(k.prototype,"count",{get:function(){return Math.ceil(this.data.length/this.elementStride)},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"buffer",{get:function(){return this.data.buffer},
enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"typedBuffer",{get:function(){return this.data},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"stride",{get:function(){return this.elementStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"typedBufferStride",{get:function(){return this.elementStride},enumerable:!0,configurable:!0});k.ElementCount=2;return k}();l.BufferViewVec2Impl=t})},"esri/views/3d/support/buffer/internals/Vec3":function(){define(["require",
"exports","../../../lib/gl-matrix"],function(t,l,e){Object.defineProperty(l,"__esModule",{value:!0});t=function(){function k(e,k,m,l,v){void 0===m&&(m=0);this.TypedArrayConstructor=e;this.elementCount=3;e=this.TypedArrayConstructor;void 0===l&&(l=3*e.BYTES_PER_ELEMENT);var g=0===k.byteLength?0:m;this.data=null==v?new e(k,g):new e(k,g,(v-m)/e.BYTES_PER_ELEMENT);this.elementStride=l/e.BYTES_PER_ELEMENT}k.prototype.getVec=function(g,k){return e.vec3d.set3(this.data[g*this.elementStride],this.data[g*
this.elementStride+1],this.data[g*this.elementStride+2],k)};k.prototype.setVec=function(e,k){this.data[e*this.elementStride]=k[0];this.data[e*this.elementStride+1]=k[1];this.data[e*this.elementStride+2]=k[2]};k.prototype.get=function(e,k){return this.data[e*this.elementStride+k]};k.prototype.set=function(e,k,m){this.data[e*this.elementStride+k]=m};Object.defineProperty(k.prototype,"count",{get:function(){return Math.ceil(this.data.length/this.elementStride)},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,
"buffer",{get:function(){return this.data.buffer},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"typedBuffer",{get:function(){return this.data},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"stride",{get:function(){return this.elementStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"typedBufferStride",{get:function(){return this.elementStride},enumerable:!0,configurable:!0});k.ElementCount=
3;return k}();l.BufferViewVec3Impl=t})},"esri/views/3d/support/buffer/internals/Vec4":function(){define(["require","exports","../../../lib/gl-matrix"],function(t,l,e){Object.defineProperty(l,"__esModule",{value:!0});t=function(){function k(e,k,m,l,v){void 0===m&&(m=0);this.TypedArrayConstructor=e;this.elementCount=4;e=this.TypedArrayConstructor;void 0===l&&(l=4*e.BYTES_PER_ELEMENT);var g=0===k.byteLength?0:m;this.data=null==v?new e(k,g):new e(k,g,(v-m)/e.BYTES_PER_ELEMENT);this.elementStride=l/e.BYTES_PER_ELEMENT}
k.prototype.getVec=function(g,k){return e.vec4d.set4(this.data[g*this.elementStride],this.data[g*this.elementStride+1],this.data[g*this.elementStride+2],this.data[g*this.elementStride+3],k)};k.prototype.setVec=function(e,k){this.data[e*this.elementStride]=k[0];this.data[e*this.elementStride+1]=k[1];this.data[e*this.elementStride+2]=k[2];this.data[e*this.elementStride+3]=k[3]};k.prototype.get=function(e,k){return this.data[e*this.elementStride+k]};k.prototype.set=function(e,k,m){this.data[e*this.elementStride+
k]=m};Object.defineProperty(k.prototype,"count",{get:function(){return Math.ceil(this.data.length/this.elementStride)},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"buffer",{get:function(){return this.data.buffer},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"typedBuffer",{get:function(){return this.data},enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"stride",{get:function(){return this.elementStride*this.TypedArrayConstructor.BYTES_PER_ELEMENT},
enumerable:!0,configurable:!0});Object.defineProperty(k.prototype,"typedBufferStride",{get:function(){return this.elementStride},enumerable:!0,configurable:!0});k.ElementCount=4;return k}();l.BufferViewVec4Impl=t})},"esri/views/3d/support/buffer/InterleavedLayout":function(){define(["require","exports","./BufferView"],function(t,l,e){Object.defineProperty(l,"__esModule",{value:!0});var k=function(){function e(e,g){this.layout=e;this.buffer="number"===typeof g?new ArrayBuffer(g*e.stride):g;g=0;for(var k=
e.fieldNames;g<k.length;g++){var m=k[g],f=e.fields.get(m);this[m]=new f.constructor(this.buffer,f.offset,this.stride)}}Object.defineProperty(e.prototype,"stride",{get:function(){return this.layout.stride},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"count",{get:function(){return this.buffer.byteLength/this.stride},enumerable:!0,configurable:!0});e.prototype.getField=function(e,g){return(e=this[e])&&e.elementCount===g.ElementCount&&e.elementType===g.ElementType?e:null};e.prototype.slice=
function(g,k){return new e(this.layout,this.buffer.slice(g*this.stride,k*this.stride))};return e}(),g=function(){function g(){this.stride=0;this.fields=new Map;this.fieldNames=[]}g.prototype.vec2f=function(g,k){this.fields.set(g,{size:8,constructor:e.BufferViewVec2f,offset:this.stride,optional:k});this.stride+=8;this.fieldNames.push(g);return this};g.prototype.vec2f64=function(g,k){this.fields.set(g,{size:16,constructor:e.BufferViewVec2f64,offset:this.stride,optional:k});this.stride+=16;this.fieldNames.push(g);
return this};g.prototype.vec3f=function(g,k){this.fields.set(g,{size:12,constructor:e.BufferViewVec3f,offset:this.stride,optional:k});this.stride+=12;this.fieldNames.push(g);return this};g.prototype.vec3f64=function(g,k){this.fields.set(g,{size:24,constructor:e.BufferViewVec3f64,offset:this.stride,optional:k});this.stride+=24;this.fieldNames.push(g);return this};g.prototype.vec4f=function(g,k){this.fields.set(g,{size:16,constructor:e.BufferViewVec4f,offset:this.stride,optional:k});this.stride+=16;
this.fieldNames.push(g);return this};g.prototype.vec4f64=function(g,k){this.fields.set(g,{size:32,constructor:e.BufferViewVec4f64,offset:this.stride,optional:k});this.stride+=32;this.fieldNames.push(g);return this};g.prototype.mat3f=function(g,k){this.fields.set(g,{size:36,constructor:e.BufferViewMat3f,offset:this.stride,optional:k});this.stride+=36;this.fieldNames.push(g);return this};g.prototype.mat4f=function(g,k){this.fields.set(g,{size:64,constructor:e.BufferViewMat4f,offset:this.stride,optional:k});
this.stride+=64;this.fieldNames.push(g);return this};g.prototype.vec4u8=function(g,k){this.fields.set(g,{offset:this.stride,size:4,optional:k,constructor:e.BufferViewVec4u8});this.stride+=4;this.fieldNames.push(g);return this};g.prototype.f32=function(g,k){this.fields.set(g,{offset:this.stride,size:4,optional:k,constructor:e.BufferViewFloat});this.stride+=4;this.fieldNames.push(g);return this};g.prototype.f64=function(g,k){this.fields.set(g,{offset:this.stride,size:8,optional:k,constructor:e.BufferViewFloat64});
this.stride+=8;this.fieldNames.push(g);return this};g.prototype.u8=function(g,k){this.fields.set(g,{offset:this.stride,size:1,optional:k,constructor:e.BufferViewUint8});this.stride+=1;this.fieldNames.push(g);return this};g.prototype.u16=function(g,k){this.fields.set(g,{offset:this.stride,size:2,optional:k,constructor:e.BufferViewUint16});this.stride+=2;this.fieldNames.push(g);return this};g.prototype.i8=function(g,k){this.fields.set(g,{offset:this.stride,size:1,optional:k,constructor:e.BufferViewInt8});
this.stride+=1;this.fieldNames.push(g);return this};g.prototype.vec2i8=function(g,k){this.fields.set(g,{offset:this.stride,size:2,optional:k,constructor:e.BufferViewVec2i8});this.stride+=2;this.fieldNames.push(g);return this};g.prototype.vec2i16=function(g,k){this.fields.set(g,{offset:this.stride,size:4,optional:k,constructor:e.BufferViewVec2i16});this.stride+=4;this.fieldNames.push(g);return this};g.prototype.vec2u8=function(g,k){this.fields.set(g,{offset:this.stride,size:2,optional:k,constructor:e.BufferViewVec2u8});
this.stride+=2;this.fieldNames.push(g);return this};g.prototype.vec4u16=function(g,k){this.fields.set(g,{offset:this.stride,size:8,optional:k,constructor:e.BufferViewVec4u16});this.stride+=8;this.fieldNames.push(g);return this};g.prototype.u32=function(g,k){this.fields.set(g,{offset:this.stride,size:4,optional:k,constructor:e.BufferViewUint32});this.stride+=4;this.fieldNames.push(g);return this};g.prototype.hasField=function(e){return 0<=this.fieldNames.indexOf(e)};g.prototype.createBuffer=function(e){return new k(this,
e)};g.prototype.createView=function(e){return new k(this,e)};g.prototype.clone=function(){var e=new g;e.stride=this.stride;e.fields=new Map;this.fields.forEach(function(g,k){return e.fields.set(k,g)});e.fieldNames=this.fieldNames.slice();e.BufferType=this.BufferType;return e};return g}();l.InterleavedLayout=g;l.newLayout=function(){return new g}})},"esri/views/3d/webgl-engine/lib/edgeRendering/bufferLayouts":function(){define(["require","exports","../../../support/buffer/glUtil","../../../support/buffer/InterleavedLayout"],
function(t,l,e,k){Object.defineProperty(l,"__esModule",{value:!0});l.EdgeInputBufferLayout=k.newLayout().vec3f("position").u16("componentIndex").u16("_padding");l.VertexLayout=k.newLayout().vec2u8("sideness");l.glVertexLayout=e.glLayout(l.VertexLayout,{prefixA:!0});l.CommonInstancesLayout=k.newLayout().vec3f("position0").vec3f("position1").u16("componentIndex").vec2u8("packedAttributes").u8("variantOffset",{glNormalized:!0}).u8("variantStroke").u8("variantExtension",{glNormalized:!0}).u8("_padding",
{glPadding:!0});l.RegularEdgeInstancesLayout=l.CommonInstancesLayout.clone().vec3f("normal");l.SilhouetteEdgeInstancesLayout=l.CommonInstancesLayout.clone().vec3f("normalA").vec3f("normalB");l.EdgeShaderAttributeLocations={aPosition0:0,aPosition1:1,aComponentIndex:2,aPackedAttributes:3,aVariantOffset:4,aVariantStroke:5,aVariantExtension:6,aNormal:7,aNormalA:7,aNormalB:8,aSideness:9}})},"esri/views/3d/support/buffer/glUtil":function(){define(["require","exports","../../../../core/tsSupport/assignHelper"],
function(t,l,e){Object.defineProperty(l,"__esModule",{value:!0});var k={divisor:0,prefixA:!1};l.glLayout=function(l,m){void 0===m&&(m={});m=e({},k,m);var n=l.stride;return l.fieldNames.filter(function(e){e=l.fields.get(e).optional;return!(e&&e.glPadding)}).map(function(e){var k=l.fields.get(e),f=k.constructor.ElementCount,d;d=g[k.constructor.ElementType];if(!d)throw Error("BufferType not supported in WebGL");var c=k.offset,k=!(!k.optional||!k.optional.glNormalized);return{name:m.prefixA?"a"+e[0].toUpperCase()+
e.substr(1):e,stride:n,count:f,type:d,offset:c,normalized:k,divisor:m.divisor}})};var g={u8:5121,u16:5123,u32:5125,i8:5120,i16:5122,i32:5124,f32:5126}})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgeBufferWriters":function(){define("require exports ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/extendsHelper ../../../lib/gl-matrix ../../../support/buffer/glUtil ./bufferLayouts".split(" "),function(t,l,e,k,g,n,m){Object.defineProperty(l,"__esModule",{value:!0});var q=
function(){function c(){}c.prototype.updateSettings=function(c){this.settings=c};c.prototype.write=function(c,e,g){var k=v;k[0]=g.position0[0];k[1]=g.position0[1];k[2]=g.position0[2];k[3]=g.position1[0];k[4]=g.position1[1];k[5]=g.position1[2];f[0]=5381;for(k=0;k<r.length;k++)f[0]=31*f[0]+r[k];d.reseed(f[0]);var k=d.randomRangeInt(0,255),p=d.randomRangeInt(0,this.settings.variants-1),a=d.randomFloat(),a=-(1-Math.min(a/.7,1))+Math.max(0,a-.7)/(1-.7),a=255*(Math.pow(Math.abs(a),1.2)*(0>a?-1:1)*.5+.5);
c.position0.setVec(e,g.position0);c.position1.setVec(e,g.position1);c.componentIndex.set(e,g.componentIndex);c.variantOffset.set(e,k);c.variantStroke.set(e,p);c.variantExtension.set(e,a)};c.prototype.trim=function(c,d){return c.slice(0,d)};return c}();l.CommonBufferWriter=q;var v=new Float32Array(6),r=new Uint32Array(v.buffer),f=new Uint32Array(1),d=new (function(){function c(c){void 0===c&&(c=1);this.seed=c}c.prototype.randomFloat=function(){return this.step()/c.LARGE_PRIME};c.prototype.randomRangeInt=
function(c,d){d-=c;return Math.round(c+this.randomFloat()*d)};c.prototype.reseed=function(c){this.seed=c};c.prototype.step=function(){return this.seed=this.seed*c.SMALL_PRIME%c.LARGE_PRIME};c.LARGE_PRIME=2147483647;c.SMALL_PRIME=16807;return c}());t=function(){function d(){this.commonWriter=new q}d.prototype.updateSettings=function(c){this.commonWriter.updateSettings(c)};d.prototype.allocate=function(c){return m.RegularEdgeInstancesLayout.createBuffer(c)};d.prototype.write=function(d,f,e){this.commonWriter.write(d,
f,e);e=g.vec3d.normalize(g.vec3d.add(e.faceNormal0,e.faceNormal1,c));d.normal.setVec(f,e)};d.prototype.trim=function(c,d){return this.commonWriter.trim(c,d)};d.Layout=m.RegularEdgeInstancesLayout;d.glLayout=n.glLayout(m.RegularEdgeInstancesLayout,{prefixA:!0,divisor:1});return d}();l.RegularEdgeBufferWriter=t;t=function(){function c(){this.commonWriter=new q}c.prototype.updateSettings=function(c){this.commonWriter.updateSettings(c)};c.prototype.allocate=function(c){return m.SilhouetteEdgeInstancesLayout.createBuffer(c)};
c.prototype.write=function(c,d,f){this.commonWriter.write(c,d,f);c.normalA.setVec(d,f.faceNormal0);c.normalB.setVec(d,f.faceNormal1)};c.prototype.trim=function(c,d){return this.commonWriter.trim(c,d)};c.Layout=m.SilhouetteEdgeInstancesLayout;c.glLayout=n.glLayout(m.SilhouetteEdgeInstancesLayout,{prefixA:!0,divisor:1});return c}();l.SilhouetteEdgeBufferWriter=t;var c=g.vec3d.create()})},"esri/views/3d/webgl-engine/lib/edgeRendering/edgePreprocessing":function(){define("require exports ../../../../../core/arrayUtils ../../../lib/gl-matrix ../../../support/mathUtils ../../../support/buffer/typedArrayUtil".split(" "),
function(t,l,e,k,g,n){function m(c,d){var f=Math.acos(c.cosAngle),e=r.fwd,g=r.ortho;k.vec3d.normalize(k.vec3d.direction(c.position0,c.position1,e));c=0<k.vec3d.dot(k.vec3d.cross(c.faceNormal0,c.faceNormal1,g),e)?-1:1;return f*c>d}function q(c){var d=c.faces.length/3,f=c.faces;c=c.neighbors;for(var e=0,g=0;g<d;g++)var k=c[3*g+0],l=c[3*g+1],a=c[3*g+2],b=f[3*g+0],h=f[3*g+1],m=f[3*g+2],e=e+(-1===k||b<h?1:0),e=e+(-1===l||h<m?1:0),e=e+(-1===a||m<b?1:0);for(var e=new Int32Array(4*e),n=0,g=0;g<d;g++){k=c[3*
g+0];l=c[3*g+1];a=c[3*g+2];b=f[3*g+0];h=f[3*g+1];m=f[3*g+2];if(-1===k||b<h)e[n++]=b,e[n++]=h,e[n++]=g,e[n++]=k;if(-1===l||h<m)e[n++]=h,e[n++]=m,e[n++]=g,e[n++]=l;if(-1===a||m<b)e[n++]=m,e[n++]=b,e[n++]=g,e[n++]=a}return e}function v(c){var d=c.faces.length/3,e=c.vertices.position;c=c.faces;for(var g=f.v0,l=f.v1,m=f.v2,n=new Float32Array(3*d),a=0;a<d;a++){var b=c[3*a+1],h=c[3*a+2];e.getVec(c[3*a+0],g);e.getVec(b,l);e.getVec(h,m);k.vec3d.subtract(l,g);k.vec3d.subtract(m,g);k.vec3d.normalize(k.vec3d.cross(l,
m,g));n[3*a+0]=g[0];n[3*a+1]=g[1];n[3*a+2]=g[2]}return n}Object.defineProperty(l,"__esModule",{value:!0});l.extractEdges=function(c,f,l,w){void 0===w&&(w=d);var p=c.vertices.position,u=c.vertices.componentIndex,t=g.deg2rad(w.anglePlanar);w=g.deg2rad(w.angleSignificantEdge);var a=Math.cos(w),b=Math.cos(t),h=r.edge,y=h.position0,R=h.position1,L=h.faceNormal0,P=h.faceNormal1,I=v(c),J=q(c),M=J.length/4;c=f.allocate(M);w=0;var T=l.allocate(M),U=0,V=0,W=0,X=e.range(0,M),Q=new Float32Array(M);n.forEach(Q,
function(a,b,c){p.getVec(J[4*b+0],y);p.getVec(J[4*b+1],R);c[b]=k.vec3d.dist(y,R)});X.sort(function(a,b){return Q[b]-Q[a]});for(var Y=[],Z=[],S=0;S<M;S++){var H=X[S],A=Q[H],z=J[4*H+0],aa=J[4*H+1],K=J[4*H+2],H=J[4*H+3],D=-1===H;p.getVec(z,y);p.getVec(aa,R);if(D)k.vec3d.set3(I[3*K+0],I[3*K+1],I[3*K+2],L),k.vec3d.set(L,P),h.componentIndex=u.get(z),h.cosAngle=k.vec3d.dot(L,P);else if(k.vec3d.set3(I[3*K+0],I[3*K+1],I[3*K+2],L),k.vec3d.set3(I[3*H+0],I[3*H+1],I[3*H+2],P),h.componentIndex=u.get(z),h.cosAngle=
k.vec3d.dot(L,P),h.cosAngle>b)continue;V+=A;W++;D||h.cosAngle<a?(f.write(c,w++,h),Y.push(A)):m(h,t)&&(l.write(T,U++,h),Z.push(A))}u=new Float32Array(Y.reverse());t=new Float32Array(Z.reverse());return{regular:{instancesData:f.trim(c,w),lodInfo:{lengths:u}},silhouette:{instancesData:l.trim(T,U),lodInfo:{lengths:t}},averageEdgeLength:V/W}};var r={edge:{position0:k.vec3d.create(),position1:k.vec3d.create(),faceNormal0:k.vec3d.create(),faceNormal1:k.vec3d.create(),componentIndex:0,cosAngle:0},ortho:k.vec3d.create(),
fwd:k.vec3d.create()},f={v0:k.vec3d.create(),v1:k.vec3d.create(),v2:k.vec3d.create()},d={anglePlanar:4,angleSignificantEdge:35}})},"esri/core/arrayUtils":function(){define(["require","exports"],function(t,l){function e(e,d,c){for(var f=e.length,g=0;g<f;g++)if(d.call(c,e[g],g,e))return g;return-1}function k(e,d,c,g){void 0===c&&(c=e.length);g=g||r;for(var f=Math.max(0,g.last-10),k=-1,l=f;l<c;++l)if(e[l]===d){k=l;break}if(-1===k){for(l=0;l<f;++l)if(e[l]===d){k=l;break}if(-1===k)return}e[k]=e[c-1];e.pop();
g.last=k;return d}function g(e,d,c,g){void 0===c&&(c=e.length);var f=[];d.forEach(function(d){void 0!==k(e,d,c,g)&&(f.push(d),--c)});return f}function n(e,d){return-1===e.indexOf(d)}function m(e,d,c){return!e.some(d.bind(null,c))}function q(e){return e}Object.defineProperty(l,"__esModule",{value:!0});l.findIndex=e;l.find=function(e,d,c){for(var f=e.length,g=0;g<f;g++){var k=e[g];if(d.call(c,k,g,e))return k}};l.unique=function(e){return e.filter(function(d,c,e){return e.indexOf(d)===c})};l.equals=
function(e,d,c){if(!e&&!d)return!0;if(!e||!d||e.length!==d.length)return!1;if(c)for(var f=0;f<e.length;f++){if(!c(e[f],d[f]))return!1}else for(f=0;f<e.length;f++)if(e[f]!==d[f])return!1;return!0};l.difference=function(e,d,c){var f;c?(f=d.filter(m.bind(null,e,c)),e=e.filter(m.bind(null,d,c))):(f=d.filter(n.bind(null,e)),e=e.filter(n.bind(null,d)));return{added:f,removed:e}};l.intersect=function(f,d,c){return f&&d?c?f.filter(function(f){return-1<e(d,function(d){return c(f,d)})}):f.filter(function(c){return-1<
d.indexOf(c)}):[]};l.constant=function(e,d){for(var c=Array(e),f=0;f<e;f++)c[f]=d;return c};l.range=function(e,d){void 0===d&&(d=e,e=0);for(var c=Array(d-e),f=e;f<d;f++)c[f-e]=f;return c};l.binaryIndexOf=function(e,d,c){for(var f=e.length,g=0,k=f-1;g<k;){var l=g+Math.floor((k-g)/2);d>e[l]?g=l+1:k=l}k=e[g];return c?d>=e[f-1]?-1:k===d?g:g-1:k===d?g:-1};var v=function(){return function(){this.last=0}}();l.RemoveHint=v;var r=new v;t=function(){return function(e){var d=this;this._array=e;this._hint=new v;
this.remove=function(c){return k(d._array,c,d._array.length,d._hint)};this.removeMany=function(c){return g(d._array,c,d._array.length,d._hint)}}}();l.UnorderedRemover=t;l.removeUnordered=k;l.removeUnorderedMany=g;l.keysOfMap=function(e){var d=[];e.forEach(function(c,e){return d.push(e)});return d};l.keysOfSet=function(e,d){void 0===d&&(d=q);var c=[];e.forEach(function(e){return c.push(d(e))});return c};l.fromMapValues=function(e){if(Array.from)return Array.from(e.values());var d=Array(e.size),c=0;
e.forEach(function(e){d[c++]=e});return d}})},"*noref":1}});
define("require exports ../../../../../core/tsSupport/awaiterHelper ../../../../../core/tsSupport/generatorHelper ../../../support/meshProcessing ../../../support/buffer/typedArrayUtil ../../../support/buffer/workerHelper ./bufferLayouts ./edgeBufferWriters ./edgePreprocessing".split(" "),function(t,l,e,k,g,n,m,q,v,r){return function(){function f(){this.regularWriter=new v.RegularEdgeBufferWriter;this.silhouetteWriter=new v.SilhouetteEdgeBufferWriter}f.prototype.process=function(d,c){return e(this,
void 0,void 0,function(){var e,f,g;return k(this,function(k){switch(k.label){case 0:if(!c)return[3,2];e=[];f=this.packInput(d,e);this.wrappedWork;return[4,c.invoke("wrappedWork",f,e)];case 1:return g=k.sent(),[2,this.unpackOutput(g)];case 2:return[2,this.work(d)]}})})};f.prototype.wrappedWork=function(d){return e(this,void 0,void 0,function(){var c,e,f,g;return k(this,function(k){c=this.unpackInput(d);e=this.work(c);f=[];this.packInputTransferables(c,f);g=this.packOutput(e,f);return[2,{result:g,transferList:f}]})})};
f.prototype.work=function(d){var c=this.extractEdgeInformation(d.data,d.skipDeduplicate,d.originalIndices);this.regularWriter.updateSettings(d.writerSettings);this.silhouetteWriter.updateSettings(d.writerSettings);return r.extractEdges(c,this.regularWriter,this.silhouetteWriter)};f.prototype.packInputTransferables=function(d,c){c.push(d.data.buffer)};f.prototype.packInput=function(d,c){this.packInputTransferables(d,c);c={dataBuffer:d.data.buffer,writerSettings:d.writerSettings,skipDeduplicate:d.skipDeduplicate};
d.originalIndices&&(c.originalIndicesBuffer=d.originalIndices.buffer,c.originalIndicesType=n.isUint32Array(d.originalIndices)?"Uint32Array":"Uint16Array");return c};f.prototype.unpackInput=function(d){return{data:q.EdgeInputBufferLayout.createView(d.dataBuffer),originalIndices:"Uint32Array"===d.originalIndicesType?new Uint32Array(d.originalIndicesBuffer):"Uint16Array"===d.originalIndicesType?new Uint16Array(d.originalIndicesBuffer):void 0,writerSettings:d.writerSettings,skipDeduplicate:d.skipDeduplicate}};
f.prototype.packOutput=function(d,c){c.push(d.regular.lodInfo.lengths.buffer);c.push(d.silhouette.lodInfo.lengths.buffer);return{regular:{instancesData:m.packInterleavedBuffer(d.regular.instancesData,c),lodInfo:{lengths:d.regular.lodInfo.lengths.buffer}},silhouette:{instancesData:m.packInterleavedBuffer(d.silhouette.instancesData,c),lodInfo:{lengths:d.silhouette.lodInfo.lengths.buffer}},averageEdgeLength:d.averageEdgeLength}};f.prototype.unpackOutput=function(d){return{regular:{instancesData:m.unpackInterleavedBuffer(d.regular.instancesData),
lodInfo:{lengths:new Float32Array(d.regular.lodInfo.lengths)}},silhouette:{instancesData:m.unpackInterleavedBuffer(d.silhouette.instancesData),lodInfo:{lengths:new Float32Array(d.silhouette.lodInfo.lengths)}},averageEdgeLength:d.averageEdgeLength}};f.prototype.extractEdgeInformation=function(d,c,e){if(c&&e)return c=g.computeNeighbors(e,d.count),{faces:e,neighbors:c,vertices:d};d=g.deduplicate(d.buffer,d.stride/4);e=this.selectIndexData(d.indices,e);c=g.computeNeighbors(e,d.uniqueCount);return{faces:e,
neighbors:c,vertices:q.EdgeInputBufferLayout.createView(d.buffer)}};f.prototype.selectIndexData=function(d,c){if(c){c=n.slice(c);for(var e=0;e<c.length;e++)c[e]=d[c[e]];return c}return d};return f}()});