// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/assignHelper ../../../../../core/tsSupport/awaiterHelper ../../../../../core/tsSupport/generatorHelper ../../../../../core/arrayUtils ../../../../../core/promiseUtils ../../../../../core/requireUtils ../../../../../core/workers ../../../lib/gl-matrix ../../../support/mathUtils ../../../support/buffer/BufferView ../../../support/buffer/bufferViewUtil ../../../support/buffer/typedArrayUtil ../localOriginHelper ../LocalOriginManager ../PreinterleavedGeometryData ../RegularGridLocalOriginFactory ../TextureBackedBuffer/BufferManager ./bufferLayouts ./edgeBufferWriters ./EdgeProcessingWorker ./EdgeRenderer ./strokes ./util ../../../../webgl/BufferObject ../../../../webgl/VertexArrayObject module".split(" "),
function(P,G,I,m,B,Q,J,R,S,A,K,T,U,L,V,W,M,X,Y,z,N,Z,t,aa,q,F,O,ba){Object.defineProperty(G,"__esModule",{value:!0});var ea=function(){function e(a,c,b){this.rctx=a;this.programRepository=c;this.callbacks=b;this.profilingCallback=null;this.perObjectData=new Map;this.renderers=new Map;this.localOrigins=new W.LocalOriginManager(new X(1E4));this.gpuMemoryUsage=this.numberOfRenderedEdges=0;this.worker=new Z;this.workerThread=null;this.destroyed=!1;this.tmpModelPosition=A.vec3d.create();this.tmpCameraPosition=
A.vec3d.create();this.componentColorManager=new Y.BufferManager(this.rctx,2)}e.prototype.initialize=function(){var a=this;S.open(R.getAbsMid("./EdgeProcessingWorker",P,ba),{client:this}).then(function(b){a.destroyed?b.close():a.workerThread=b});for(var c=z.VertexLayout.createBuffer(4),b=0;4>b;b++)c.sideness.set(b,0,0===b||3===b?0:1),c.sideness.set(b,1,0===b||1===b?0:1);this.verticesBufferObject=F.createVertex(this.rctx,35044,c.buffer)};e.prototype.destroy=function(){this.destroyed||(this.workerThread&&
(this.workerThread.close(),this.workerThread=null),this.verticesBufferObject&&(this.verticesBufferObject.dispose(),this.verticesBufferObject=null),this.destroyed=!0)};e.prototype.getGpuMemoryUsage=function(){return this.gpuMemoryUsage};Object.defineProperty(e.prototype,"numberOfRenderedPrimitives",{get:function(){return this.numberOfRenderedEdges},enumerable:!0,configurable:!0});e.prototype.shouldRender=function(){return 0<this.renderers.size};e.prototype.addObject=function(a,c,b){return m(this,void 0,
void 0,function(){var d,f,k,C,h,g,e;return B(this,function(n){switch(n.label){case 0:if(this.hasObject(a))return[2];d=[];k={loaded:J.create(function(a){return f=a}),renderables:[]};this.perObjectData.set(a,k);if(b&&b.mergeGeometries&&1<a.geometries.length&&this.canMergeGeometries(a))d.push(this.addObjectMergedGeometries(a,k,c));else for(C=0;C<a.geometries.length;C++)h=a.geometries[C],g=a.geometryRecords[C],e=g.materials[0],e.supportsEdges&&(h.data instanceof M?d.push(this.addGeometryPreinterleaved(a,
k,h,h.data,g,c)):d.push(this.addGeometryNonPreinterleaved(a,k,h,h.data,g,c[0])));return[4,J.all(d)];case 1:return n.sent(),this.callbacks.setNeedsRender(),f(),[2]}})})};e.prototype.hasObject=function(a){return this.perObjectData.has(a)};e.prototype.updateAllComponentOpacities=function(a,c){return m(this,void 0,void 0,function(){var b,d;return B(this,function(f){switch(f.label){case 0:return(b=this.perObjectData.get(a))?[4,b.loaded]:[2];case 1:return f.sent(),d=c instanceof Array?function(a){return c[a]}:
function(a){return c},b.renderables.forEach(function(a){for(var b=a.components.meta.length,c=0;c<b;c++){var f=d(c),k=a.components.meta[c],e=k.index;k.material.opacity=f;a.components.buffer.textureBuffer.setDataElement(e,1,3,255*f)}a.allTransparent=q.determineAllTransparent(a.components.meta)}),this.callbacks.setNeedsRender(),[2]}})})};e.prototype.updateAllComponentMaterials=function(a,c){return m(this,void 0,void 0,function(){var b,d=this;return B(this,function(f){switch(f.label){case 0:return(b=
this.perObjectData.get(a))?[4,b.loaded]:[2];case 1:return f.sent(),b.renderables.forEach(function(a){var b=c[0],f=q.determineRequiresUberRenderer(c),g=t.EdgeRenderer.getKey(f,b.type,b.slicePlaneEnabled);if(g!==a.rendererKey){var k=d.renderers.get(a.rendererKey),b=d.aquireRenderer(f,b);k.removeRenderable(a);k.refCount.decrement();a.rendererKey=g;b.addRenderable(a)}for(g=0;g<c.length;g++)a.components.meta[g].material=c[g];d.updateComponentBuffer(a.components);a.allTransparent=q.determineAllTransparent(a.components.meta)}),
this.callbacks.setNeedsRender(),[2]}})})};e.prototype.updateObjectVisibility=function(a,c){return m(this,void 0,void 0,function(){var b;return B(this,function(d){switch(d.label){case 0:return(b=this.perObjectData.get(a))?[4,b.loaded]:[2];case 1:return d.sent(),b.renderables.forEach(function(a){a.visible=c}),this.callbacks.setNeedsRender(),[2]}})})};e.prototype.removeObject=function(a){var c=this,b=this.perObjectData.get(a);b&&(this.perObjectData.delete(a),b.loaded.then(function(){b.renderables.forEach(function(a){c.removeRenderable(a)});
c.callbacks.setNeedsRender()}))};e.prototype.removeAll=function(){var a=this;this.perObjectData.forEach(function(c,b){a.removeObject(b)})};e.prototype.createSolidEdgeMaterial=function(a){return I({},ca,a,{type:"solid"})};e.prototype.createSketchEdgeMaterial=function(a){return I({},da,a,{type:"sketch"})};e.prototype.render=function(a){var c=this;this.localOrigins.updateViewMatrices(a.view);this.renderers.forEach(function(a){0===a.refCount.value&&(c.renderers.delete(a.key),a.dispose())});this.componentColorManager.garbageCollect();
this.componentColorManager.updateTextures();var b=a.view,d=0,f=0;this.renderers.forEach(function(a){a.forEachRenderable(function(a){d+=a.statistics.averageEdgeLength;f++})});var k={distanceFalloffFactor:d/f*40,minimumEdgeLength:q.estimateLengthAtDistance(a.viewport[3],a.fovY,1,3.5)},e=this.rctx.capabilities.blendMinMax;e?(this.rctx.setDepthWriteEnabled(!1),this.rctx.setBlendingEnabled(!0),this.rctx.setBlendEquationSeparate(32774,e.MAX),this.rctx.setBlendFunctionSeparate(1,0,1,1)):(this.rctx.setDepthWriteEnabled(!0),
this.rctx.setBlendingEnabled(!1));this.rctx.setDepthTestEnabled(!0);this.rctx.setDepthFunction(515);this.updateObjectCameraDistances(a);this.numberOfRenderedEdges=0;this.renderers.forEach(function(b){c.renderRegularEdges(b,a,k);c.renderSilhouetteEdges(b,a,k)});this.rctx.setDepthWriteEnabled(!0);this.rctx.setDepthFunction(513);this.rctx.setBlendEquationSeparate(32774,32774);this.rctx.setBlendFunctionSeparate(1,0,1,1);a.view=b};e.prototype.computeModelTransformWithLocalOrigin=function(a,c,b){a.getCombinedStaticTransformation(c,
b);c.origin?this.localOrigins.register(c.origin):(a=A.vec3d.set3(b[12],b[13],b[14],this.tmpModelPosition),c.origin=this.localOrigins.aquire(a));V.applyToModelMatrix(c.origin.vec3,b);return b};e.prototype.updateComponentBuffer=function(a){var c=a.meta;a=a.buffer;for(var b=0;b<c.length;b++){var d=c[b].material,f=c[b].index,k=K.clamp(Math.round(d.size*t.LINE_WIDTH_FRACTION_FACTOR),0,255),e=K.clamp(d.extensionLength,-t.EXTENSION_LENGTH_OFFSET,255-t.EXTENSION_LENGTH_OFFSET)+t.EXTENSION_LENGTH_OFFSET,h=
"solid"===d.type?0:1,g=255*d.opacity,d=d.color;a.textureBuffer.setData(f,0,255*d[0],255*d[1],255*d[2],255*d[3]);a.textureBuffer.setData(f,1,k,e,h,g)}};e.prototype.createComponentBuffers=function(a){for(var c=[],b=this.componentColorManager.getBuffer(a.length),d=0;d<a.length;d++){var f=a[d],e=b.aquireIndex();c.push({index:e,material:f})}a={meta:c,buffer:b};this.updateComponentBuffer(a);return a};e.prototype.extractEdges=function(a,c,b,d){return this.worker.process({data:c,originalIndices:d,writerSettings:a,
skipDeduplicate:b},this.workerThread)};e.prototype.createEdgeResources=function(a){var c={};if(0<a.regular.lodInfo.lengths.length){var b=new O(this.rctx,z.EdgeShaderAttributeLocations,{vertices:z.glVertexLayout,instances:N.RegularEdgeBufferWriter.glLayout},{vertices:this.verticesBufferObject,instances:F.createVertex(this.rctx,35044,a.regular.instancesData.buffer)});c.regular={vao:b,lod:a.regular.lodInfo}}0<a.silhouette.lodInfo.lengths.length&&(b=new O(this.rctx,z.EdgeShaderAttributeLocations,{vertices:z.glVertexLayout,
instances:N.SilhouetteEdgeBufferWriter.glLayout},{vertices:this.verticesBufferObject,instances:F.createVertex(this.rctx,35044,a.silhouette.instancesData.buffer)}),c.silhouette={vao:b,lod:a.silhouette.lodInfo});return c};e.prototype.disposeEdgeResources=function(a){a.regular&&(a.regular.vao.vertexBuffers.instances.dispose(),a.regular.vao.dispose(!1),a.regular.vao=null);a.silhouette&&(a.silhouette.vao.vertexBuffers.instances.dispose(),a.silhouette.vao.dispose(!1),a.silhouette.vao=null)};e.prototype.addGeometryNonPreinterleaved=
function(a,c,b,d,f,e){return m(this,void 0,void 0,function(){var b,k,g,r;return B(this,function(h){switch(h.label){case 0:return b=d.getAttribute("position"),k=this.computeModelTransformWithLocalOrigin(a,f,A.mat4d.create()),g=f.origin,r={position:b,indices:d.getIndices("position"),modelTransform:k,origin:g},[4,this.addNonPreinterleaved(a,c,r,e)];case 1:return h.sent(),[2]}})})};e.prototype.addNonPreinterleaved=function(a,c,b,d){return m(this,void 0,void 0,function(){var a,e,C,h,g,r,n,l,x,u,D,y,p,
w,v;return B(this,function(f){switch(f.label){case 0:a=this.aquireRenderer(!1,d);e=b.modelTransform;C=b.origin;h=b.indices;g=b.position;r=g.data.length/g.strideIdx;n=z.EdgeInputBufferLayout.createBuffer(r);for(l=0;l<r;l++)n.position.set(l,0,g.data[g.offsetIdx+l*g.strideIdx+0]),n.position.set(l,1,g.data[g.offsetIdx+l*g.strideIdx+1]),n.position.set(l,2,g.data[g.offsetIdx+l*g.strideIdx+2]);x=this.createComponentBuffers([d]);q.fillComponenBufferIndices(x.meta,[0,n.componentIndex.count],n.componentIndex);
return[4,this.extractEdges(a.writerSettings,n,!1,h)];case 1:return u=f.sent(),D=this.createEdgeResources(u),y=D.regular,p=D.silhouette,w=(y?y.vao.size:0)+(p?p.vao.size:0),v={regular:y,silhouette:p,transform:{modelMatrix:e,origin:C},statistics:{gpuMemoryUsage:w,averageEdgeLength:u.averageEdgeLength},components:x,visible:!0,allTransparent:q.determineAllTransparent(x.meta),distanceToCamera:0,rendererKey:a.key},c.renderables.push(v),a.addRenderable(v),this.gpuMemoryUsage+=w,[2]}})})};e.prototype.addGeometryPreinterleaved=
function(a,c,b,d,f,e){return m(this,void 0,void 0,function(){var b,k,g,r,n,l,x,u,D,y,p,w,v,H,m,t,E;return B(this,function(h){switch(h.label){case 0:b=d.getAttribute("position");if(!b||!L.isFloat32Array(b.data))return console.warn("Geometry has no float32 `position` attribute, skipping it."),[2];k=e[0];g=q.determineRequiresUberRenderer(e);r=this.aquireRenderer(g,k);n=this.computeModelTransformWithLocalOrigin(a,f,A.mat4d.create());l=f.origin;x=d.getIndices("position");u=new T.BufferViewVec3f(b.data.buffer,
4*b.offsetIdx,4*b.strideIdx);D=z.EdgeInputBufferLayout.createBuffer(u.count);U.unrolledCopyVec3(D.position,u);y=this.createComponentBuffers(e);q.fillComponenBufferIndices(y.meta,d.componentOffsets,D.componentIndex,x);p=d.hasPositionData;return[4,this.extractEdges(r.writerSettings,D,p,x)];case 1:return w=h.sent(),v=this.createEdgeResources(w),H=v.regular,m=v.silhouette,t=(H?H.vao.size:0)+(m?m.vao.size:0),E={regular:H,silhouette:m,transform:{modelMatrix:n,origin:l},statistics:{gpuMemoryUsage:t,averageEdgeLength:w.averageEdgeLength},
components:y,visible:!a.isHidden(f),allTransparent:q.determineAllTransparent(y.meta),distanceToCamera:0,rendererKey:r.key},c.renderables.push(E),r.addRenderable(E),this.gpuMemoryUsage+=t,[2]}})})};e.prototype.canMergeGeometries=function(a){for(var c=null,b=null,d=0;d<a.geometries.length;d++){var f=a.geometryRecords[d];if(f.materials[0].supportsEdges){if(a.geometries[d].data instanceof M)return!1;if(!c)c=f.transformation;else if(!Q.equals(c,f.transformation))return!1;if(!b&&f.origin)b=f;else if(b&&
f.origin&&b.origin.id!==f.origin.id)return!1}}return!0};e.prototype.addObjectMergedGeometries=function(a,c,b){return m(this,void 0,void 0,function(){var d,f,e,m,h,g,r,n,l,x,u,t,y,p,w,v,q,z,F,E,G;return B(this,function(k){switch(k.label){case 0:d=new Map;f=0;m=e=null;for(h=0;h<a.geometries.length;h++)if(g=a.geometries[h],r=a.geometryRecords[h],n=r.materials[0],n.supportsEdges&&(!m&&r.origin&&(m=r),l=g.data.getIndices("position"),f+=l?l.length:0,l&&null==e||e===Uint16Array))e=L.isUint16Array(l)?Uint16Array:
Uint32Array;x=f?new e(f):null;u=[];for(h=t=0;h<a.geometries.length;h++)if(g=a.geometries[h],y=a.geometryRecords[h],n=y.materials[0],n.supportsEdges){p=g.data.getAttribute("position");l=g.data.getIndices("position");w=d.get(p.data);if(null==w){w=u.length/3;for(v=p.offsetIdx;v<p.data.length;v+=p.strideIdx)u.push(p.data[v+0]),u.push(p.data[v+1]),u.push(p.data[v+2]);d.set(p.data,w)}if(l)for(q=0;q<l.length;q++)x[t++]=w+l[q]}z=m||a.geometryRecords[0];F=this.computeModelTransformWithLocalOrigin(a,z,A.mat4d.create());
E=z.origin;for(h=0;h<a.geometryRecords.length;h++)a.geometryRecords[h].origin=E;G={position:{data:u,offsetIdx:0,strideIdx:3},indices:x,modelTransform:F,origin:E};return[4,this.addNonPreinterleaved(a,c,G,b[0])];case 1:return k.sent(),[2]}})})};e.prototype.aquireRenderer=function(a,c){var b=t.EdgeRenderer.getKey(a,c.type,c.slicePlaneEnabled),d=this.renderers.get(b);this.strokesTexture||(this.strokesTexture=aa.generateStrokesTexture(this.rctx));d||(d=new t.EdgeRenderer(this.rctx,this.programRepository,
{type:c.type,slicePlaneEnabled:c.slicePlaneEnabled,strokesTexture:this.strokesTexture,uber:a}),this.renderers.set(b,d));d.refCount.increment();return d};e.prototype.removeRenderable=function(a){var c=this.renderers.get(a.rendererKey);c.removeRenderable(a);c.refCount.decrement();this.disposeEdgeResources(a);this.localOrigins.release(a.transform.origin);this.gpuMemoryUsage-=a.statistics.gpuMemoryUsage;for(var c=0,b=a.components.meta;c<b.length;c++)a.components.buffer.releaseIndex(b[c].index)};e.prototype.updateObjectCameraDistances=
function(a){var c=this;a=a.viewInvTransp;A.vec3d.set3(a[3],a[7],a[11],this.tmpCameraPosition);this.perObjectData.forEach(function(a,d){var b=A.vec3d.dist(d.getCenter(),c.tmpCameraPosition);a.renderables.forEach(function(a){return a.distanceToCamera=b})})};e.prototype.renderRegularEdges=function(a,c,b){var d=this;a.bindRegularEdges(c,b);a.forEachRenderable(function(f){if(f.visible&&f.regular&&!f.allTransparent){var e=q.computeEdgeCount(f.regular.lod.lengths,f.distanceToCamera,b);c.view=d.localOrigins.getViewMatrix(f.transform.origin);
a.renderRegularEdges(f,c,e);d.numberOfRenderedEdges+=e}})};e.prototype.renderSilhouetteEdges=function(a,c,b){var d=this;a.bindSilhouetteEdges(c,b);a.forEachRenderable(function(e){if(e.visible&&e.silhouette&&!e.allTransparent){var f=q.computeEdgeCount(e.silhouette.lod.lengths,e.distanceToCamera,b);c.view=d.localOrigins.getViewMatrix(e.transform.origin);a.renderSilhouetteEdges(e,c,f);d.numberOfRenderedEdges+=f}})};return e}();G.EdgeView=ea;var ca={color:A.vec4d.createFrom(0,0,0,.2),size:1,extensionLength:0,
opacity:1,slicePlaneEnabled:!1},da={color:A.vec4d.createFrom(0,0,0,.2),size:1,extensionLength:0,opacity:1,slicePlaneEnabled:!1}});