// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/extendsHelper ../../../lib/gl-matrix ../../../webgl-engine/lib/glUtil3D ../../../webgl-engine/lib/RenderSlot ../../../webgl-engine/lib/Util ../../../webgl-engine/materials/internal/MaterialUtil ../../../webgl-engine/shaders/LaserLinePrograms ../../../../webgl/programUtils".split(" "),function(A,B,C,a,t,u,v,p,w,x){function q(c,e,h,f){var r=l,b=y;a.mat4d.multiplyVec3(f,e,r);a.vec3d.set(h,b);b[3]=0;a.mat4d.multiplyVec4(f,b);a.vec4d.set4(b[0],b[1],
b[2],-a.vec3d.dot(b,r),c)}var l=a.vec3d.create(),y=a.vec4d.create(),z={glowColor:[1,.5,0],glowWidth:8,innerColor:[1,1,1],innerWidth:1,globalAlpha:.75};return function(){function c(e,c){void 0===c&&(c={});this._projInfo=a.vec4d.create();this._zScale=a.vec2d.create();this._segmentActive=this._focusSphereActive=this._focusPlaneActive=!1;this._focusPosition=a.vec3d.create();this._focusSpherePosition=a.vec3d.create();this._segmentStartPosition=a.vec3d.create();this._segmentEndPosition=a.vec3d.create();
this._needsRender=!1;this._tempNormal=a.vec3d.create();this._tempDir=a.vec3d.create();this._tempUp=a.vec3d.create();this._tempVec3=a.vec3d.create();this._tempVec4=a.vec4d.create();this.didRender=!1;this._renderCoordsHelper=e;this._params=p.copyParameters(c,z)}Object.defineProperty(c.prototype,"needsRender",{get:function(){return this._needsRender},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"renderSlots",{get:function(){return[u.POSTPROCESSING_EXTERNAL]},enumerable:!0,configurable:!0});
Object.defineProperty(c.prototype,"needsLinearDepth",{get:function(){return!0},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"focusPlaneActive",{get:function(){return this._focusPlaneActive},set:function(a){a!==this._focusPlaneActive&&(this._focusPlaneActive=a,this._needsRender=!0)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"focusSphereActive",{get:function(){return this._focusSphereActive},set:function(a){a!==this._focusSphereActive&&(this._focusSphereActive=
a,this._needsRender=!0)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"segmentActive",{get:function(){return this._segmentActive},set:function(a){a!==this._segmentActive&&(this._segmentActive=a,this._needsRender=!0)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"focusPosition",{get:function(){return this._focusPosition},set:function(e){a.vec3d.set(e,this._focusPosition);this._needsRender=!0},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,
"focusSpherePosition",{get:function(){return this._focusSpherePosition},set:function(e){a.vec3d.set(e,this._focusSpherePosition);this._needsRender=!0},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"segmentStartPosition",{get:function(){return this._segmentStartPosition},set:function(e){a.vec3d.set(e,this._segmentStartPosition);this._needsRender=!0},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"segmentEndPosition",{get:function(){return this._segmentEndPosition},
set:function(e){a.vec3d.set(e,this._segmentEndPosition);this._needsRender=!0},enumerable:!0,configurable:!0});c.prototype.setParameterValues=function(a){p.updateParameters(this._params,a)&&(this._needsRender=!0)};c.prototype.initializeRenderContext=function(a){a=a.rctx;this._quadVAO=t.createQuadVAO(a);this._laserLineProgram=x.createProgram(a,w.program)};c.prototype.uninitializeRenderContext=function(a){this._quadVAO.dispose();this._quadVAO=null;this._laserLineProgram.dispose();this._projInfo=this._laserLineProgram=
null};c.prototype.resetNeedsRender=function(){this.didRender&&(this._needsRender=this.didRender=!1)};c.prototype.render=function(c){var h=c.rctx,f=c.camera,e=this._renderCoordsHelper,b=this._laserLineProgram,d=this._projInfo,g=this._zScale;h.bindProgram(b);v.inverseProjectionInfo(f.projectionMatrix,f.fullWidth,f.fullHeight,d,g);b.setUniform4fv("projInfo",d);b.setUniform2fv("zScale",g);b.setUniform2f("nearFar",f.near,f.far);b.setUniform1f("maxPixelDistance",2*f.computePixelSizeAt(this._focusPosition));
if(this._focusPlaneActive){var d=this._focusPosition,g=this._tempVec3,k=this._tempVec4;e.worldUpAtPosition(d,g);q(k,d,g,f.viewMatrix);b.setUniform4fv("focusPlane",k)}else b.setUniform4fv("focusPlane",[0,0,0,1E10]);this._focusSphereActive?(g=this._tempVec4,d=this._tempVec3,a.vec3d.set(this._focusSpherePosition,g),a.mat4d.multiplyVec3(f.viewMatrix,g),a.vec3d.set(this._focusPosition,d),a.mat4d.multiplyVec3(f.viewMatrix,d),g[3]=a.vec3d.dist(g,d),b.setUniform4fv("focusSphere",g)):b.setUniform4fv("focusSphere",
[0,0,0,1E10]);if(this._segmentActive){var d=this._tempVec4,g=this._tempVec3,k=this._tempUp,m=this._tempDir,n=this._tempNormal;a.vec3d.lerp(this._segmentStartPosition,this._segmentEndPosition,.5,g);e.worldUpAtPosition(g,k);a.vec3d.subtract(this._segmentEndPosition,this._segmentStartPosition,m);a.vec3d.normalize(m);a.vec3d.cross(k,m,n);a.vec3d.normalize(n);q(d,this._segmentStartPosition,n,f.viewMatrix);b.setUniform4fv("segmentPlane",d)}else b.setUniform4fv("segmentPlane",[0,0,0,1E10]);d=l;a.vec3d.set(this._segmentStartPosition,
d);e.setAltitude(0,d);a.mat4d.multiplyVec3(f.viewMatrix,d);b.setUniform3fv("segmentStart",d);d=l;a.vec3d.set(this._segmentEndPosition,d);e.setAltitude(0,d);a.mat4d.multiplyVec3(f.viewMatrix,d);b.setUniform3fv("segmentEnd",d);b.setUniform1i("depthMap",0);h.bindTexture(c.depth.colorTexture,0);b.setUniform3fv("innerColor",this._params.innerColor);b.setUniform1f("innerWidth",this._params.innerWidth);b.setUniform3fv("glowColor",this._params.glowColor);b.setUniform1f("glowWidth",this._params.glowWidth);
b.setUniform1f("globalAlpha",this._params.globalAlpha);h.bindVAO(this._quadVAO);h.setDepthTestEnabled(!1);h.setDepthWriteEnabled(!1);h.setBlendFunctionSeparate(1,771,770,771);h.setBlendingEnabled(!0);h.drawArrays(5,0,4);h.setDepthTestEnabled(!0);h.setDepthWriteEnabled(!0);h.setBlendingEnabled(!1);return!0};return c}()});