// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.31/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/WebMapsUtil","dojo/_base/lang dojo/_base/Deferred esri/dijit/geoenrichment/when esri/kernel esri/arcgis/utils esri/geometry/Extent esri/request esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(g,q,m,r,n,u,w,p){var f={};p.isPageRunOnWebService()||(r.id.getCredential=function(){var a=new q;a.reject(Error("Can't get credentials"));return a});var v={_itemsCache:{},_siCache:{},loadItem:function(a){this._itemsCache[a]||(this._itemsCache[a]=
n.getItem(a));return m(this._itemsCache[a],function(a){return a&&g.clone(a)})},loadServiceInfo:function(a,e){this._siCache[a]||(this._siCache[a]=e({url:a,content:{f:"json"}}));return this._siCache[a]}};f.getItem=function(a){return v.loadItem(a)};f.isWebMapType=function(a){return a&&"Web Map"===a.type};f.createMap=function(a,e,c){c=c||{};if(a&&a.item)return f.isWebMapType(a.item)&&c.additionalLayerInfos&&f._addAdditionalLayerInfosToOperationalLayers(a.itemData.operationalLayers,c.additionalLayerInfos),
m(!f.isWebMapType(a.item)&&f.createItemDataForNonWebMapItem(a,{defaultBasemapId:c.defaultBasemapId,additionalLayerInfos:c.additionalLayerInfos}),function(){return n.createMap(a,e,{usePopupManager:!0,mapOptions:c.mapOptions||{}})})};f.createItemDataForNonWebMapItem=function(a,e){function c(){d.url=function(b){["FeatureServer","MapServer","ImageServer"].some(function(a){if(-1!==b.indexOf(a))return b=b.substr(0,b.lastIndexOf(a)+a.length),!0});return b}(d.url);var b=e.requestFunc||w;p.registerCORS(d.url);
return v.loadServiceInfo(d.url,b).then(function(b){return m(function(b,a){b.extent||(a=a.initialExtent||a.fullExtent||a.extent,!a||a instanceof u||(a=new u(a)),b.extent=a)}(d,b),function(){return b})})}function h(b){a.itemData={baseMap:null,operationalLayers:b};e.additionalLayerInfos&&f._addAdditionalLayerInfosToOperationalLayers(b,e.additionalLayerInfos);return m(!1!==e.defaultBasemapId&&f.provideDefaultBaseMapForItemData(a.itemData,e),function(){return a})}function n(b,a){return-1!==b.indexOf(a)?
b.substr(b.lastIndexOf(a)+a.length,b.length):null}function t(b,a){var c=b.id;return{url:p.combine(d.url,c),capabilities:a.capabilities||"Query",id:a.idPrefix+c,visibility:a.visibility||b.defaultVisibility,mode:1,title:b.title,description:b.description}}function q(b,a){var c;b.layers.some(function(b){a==b.id&&(c=b);return a==b.id});return c}e=e||{};var d=a.item,k=a.itemData;if("Feature Service"===d.type){var l=n(d.url,"FeatureServer/");return c().then(function(b){var a=[],c=l&&q(b,l);if(c)a.push(t(c,
{capabilities:b.capabilities,idPrefix:"featureServiceLayer_",visibility:!0}));else for(c=0;c<b.layers.length;c++)a.unshift(t(b.layers[c],{capabilities:b.capabilities,idPrefix:"featureServiceLayer_"}));return h(a)})}if("Map Service"===d.type)return l=n(d.url,"MapServer/"),c().then(function(a){a=l&&a.layers[l]?t(a.layers[l],{capabilities:a.capabilities,idPrefix:"mapServiceLayer_",visibility:!0}):{url:d.url,id:"mapServiceLayer01",visibility:!0,title:a.title};a=[g.mixin(a,{opacity:1},k)];return h(a)});
if("Image Service"===d.type)return c().then(function(a){a=[g.mixin({url:d.url,id:"imageServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("Vector Tile Service"===d.type)return c().then(function(a){a=[g.mixin({url:d.url,id:"vectorTileServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMSServer"===d.type)return c().then(function(a){a=[g.mixin({url:d.url,id:"wmsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMTS"===d.type)return c().then(function(a){a=
[g.mixin({url:d.url,id:"wmtsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WFS"===d.type)return c().then(function(a){a=[g.mixin({url:d.url,id:"wfsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("KML"===d.type){p.registerCORS(d.url);var r=[g.mixin({url:d.url,id:"kmlLayer01",visibility:!0,opacity:1,title:"KML Layer",type:"KML"},k)];return h(r)}};f.provideDefaultBaseMapForItemData=function(a,e){e=e||{};if(!a.baseMap)return m(function(){var a={title:"My basemap",
baseMapLayers:[{id:"basemapLayer01",opacity:e.hideBasemap?0:1,visibility:!e.hideBasemap,url:"http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer"}]};return e.defaultBasemapId?f.getItem(e.defaultBasemapId).then(function(c){return c&&c.itemData&&c.itemData.baseMap||a}):a}(),function(c){a.baseMap=c;return a})};f._addAdditionalLayerInfosToOperationalLayers=function(a,e){e.forEach(function(c,e){a.push({url:c.url,id:"additionalLayer"+e,visibility:!0,opacity:1})})};return f});