// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../geometry/Extent ../../../geometry/SpatialReference ../../../geometry/support/webMercatorUtils ../lib/gl-matrix ./cameraUtilsInternal ./earthUtils ./mathUtils".split(" "),function(J,k,G,w,H,b,B,C,m){function D(d,a,e,l){void 0===l&&(l=B.createDirectionUp());b.vec3d.cross(d,E,q);0===b.vec3d.dot(q,q)&&b.vec3d.cross(d,F,q);b.mat4d.identity(p);b.mat4d.rotate(p,-m.deg2rad(a),d);b.mat4d.rotate(p,-m.deg2rad(e),q);a=l.up;e=l.direction;b.vec3d.cross(q,d,a);b.vec3d.normalize(a);
b.mat4d.multiplyVec3(p,a);b.vec3d.normalize(d,e);b.mat4d.multiplyVec3(p,b.vec3d.negate(e));return l}function z(d){var a=d[1];d[1]=-d[2];d[2]=a}function A(d,a){a=D(a,d.heading,d.tilt);d.up=a.up;return d}Object.defineProperty(k,"__esModule",{value:!0});var E=b.vec3d.createFrom(0,0,1),F=b.vec3d.normalize(b.vec3d.createFrom(1,1,1)),I=new m.Cyclical(-180,180),p=b.mat4d.create(),q=b.vec3d.create(),n=b.vec3d.create();k.headingTiltToDirectionUp=D;k.directionToHeadingTilt=function(d,a,e,l){var c=q;b.vec3d.normalize(d,
c);b.vec3d.cross(c,E,n);0===b.vec3d.dot(n,n)&&b.vec3d.cross(c,F,n);b.vec3d.cross(n,c,n);return B.directionToHeadingTilt(a,e,l,c,n)};k.eyeForCenterWithHeadingTilt=function(d,a,e,l){var c={eye:b.vec3d.create(),up:null,tilt:l,heading:e},g=q;g[0]=d[0];g[1]=d[2];g[2]=-d[1];e=m.deg2rad(e);var f=m.deg2rad(l);l=Math.sin(e);e=Math.cos(e);var h=Math.sin(f),x=Math.cos(f),u=b.vec3d.length(g);if(1E-8>Math.abs(f))f=a+u;else var v=u/h,k=m.asin(a/v),f=v*Math.sin(Math.PI-f-k);var v=h*a,x=x*a,k=e*v,n=f-x,p=n*n,y=a*
a*h*h,h=e*e*y,y=l*l*y,r=g[1]*n,t=h*(h+p-g[1]*g[1]);if(0>t)return b.vec3d.scale(g,f/u,c.eye),c.tilt=0,c;var w=Math.sqrt(t),t=h+p,r=0<e?-w+r:w+r;if(1E-8>Math.abs(t))return 1E-8>u?(c.eye[0]=0,c.eye[1]=0,c.eye[2]=a):b.vec3d.scale(g,f/u,c.eye),c.tilt=0,z(c.eye),A(c,d);c.eye[1]=r/t;t=c.eye[1]*c.eye[1];a=1-t;r=Math.sqrt(a);k=h*t+y-2*k*c.eye[1]*r*n+a*p;if(1E-8>Math.abs(k))return b.vec3d.scale(g,f/u,c.eye),c.tilt=0,z(c.eye),A(c,d);c.eye[0]=(a*(f*g[0]-x*g[0])-v*r*(g[0]*c.eye[1]*e+g[2]*l))/k;c.eye[2]=(a*(f*
g[2]-x*g[2])-v*r*(g[2]*c.eye[1]*e-g[0]*l))/k;b.vec3d.scale(c.eye,f);z(c.eye);return A(c,d)};k.lookAtTiltToEyeTilt=function(d,a,e){d=b.vec3d.length(d);a=m.asin(a/(Math.sqrt(a*a+d*d-2*a*d*Math.cos(Math.PI-e))/Math.sin(e)));return m.rad2deg(e-a)};k.eyeTiltToLookAtTilt=function(d,a,e){e=m.deg2rad(e);d=b.vec3d.length(d);return m.asin(a/(d/Math.sin(e)))+e};k.toExtent=function(d,a,e,b,c){function g(a){var b=Math.PI/2;a=m.cyclical2PI.normalize(a,-b);a>b&&(a=Math.PI-a);return a}var f;f=a.latitude;a=a.longitude;
var h=C.getLonDeltaForDistance(a,f,e)/2;e=a-h;a+=h;f=m.deg2rad(f);h=C.earthRadius;f=(1+Math.sin(f))/(1-Math.sin(f));var k=(f+1)*Math.tan(b/h/2);f=1.5*Math.PI-2*Math.atan(.5*(k+Math.sqrt(4*f+k*k)));b=f+b/h;f=g(f);b=g(b);b<f&&(h=b,b=f,f=h);f=Math.max(m.rad2deg(f),-90);b=Math.min(m.rad2deg(b),90);a=I.monotonic(e,a);180<a-e&&(h=(a-e-180)/2,e+=h,a-=h);c?(c.xmin=e,c.ymin=f,c.xmax=a,c.ymax=b,c.spatialReference=w.WGS84):c=new G(e,f,a,b,w.WGS84);d.spatialReference&&d.spatialReference.isWebMercator&&H.geographicToWebMercator(c,
!1,c);return c}});