// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","../../../core/lang","../../../core/PooledArray"],function(e,p,h,n){var g=new n;e=function(){function a(a,k,b){this._namespace=a;this._storage=k;this._priority=0;this._removeFunc=!1;this._miss=this._hit=0;g.push(this);this._namespace+=":";b&&(this._storage.registerRemoveFunc(this._namespace,b),this._removeFunc=!0)}Object.defineProperty(a.prototype,"priority",{get:function(){return this._priority},set:function(a){isNaN(a)||(this._priority=Math.max(0,a))},enumerable:!0,configurable:!0});
Object.defineProperty(a.prototype,"namespace",{get:function(){return this._namespace.slice(0,-1)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"hitRate",{get:function(){return this._hit/(this._hit+this._miss)},enumerable:!0,configurable:!0});a.prototype.resetHitRate=function(){this._hit=this._miss=0};a.prototype.destroy=function(){this._storage.clear(this._namespace);this._removeFunc&&this._storage.deregisterRemoveFunc(this._namespace);g.removeUnordered(this)};a.prototype.put=
function(a,k,b){this._storage.put(this._namespace+a,k,b,this._priority)};a.prototype.pop=function(a){a=this._storage.pop(this._namespace+a);void 0===a?++this._miss:++this._hit;return a};a.prototype.clear=function(){this._storage.clear(this._namespace)};a.prototype.clearAll=function(){this._storage.clearAll()};a.prototype.getSize=function(){return this._storage.getSize()};a.prototype.getMaxSize=function(){return this._storage.maxSize};a.prototype.getStats=function(){return this._storage.getStats()};
a.prototype.resetStats=function(){this._storage.resetStats()};return a}();(function(a){var e=function(){function a(){this._db=new Map;this._miss=this._hit=this._age=this._size=0;this._maxSize=10485760;this._removeFuncs=[]}a.prototype.registerRemoveFunc=function(a,d){this._removeFuncs.push([a,d])};a.prototype.deregisterRemoveFunc=function(a){this._removeFuncs=this._removeFuncs.filter(function(b){return b[0]!==a})};Object.defineProperty(a.prototype,"maxSize",{get:function(){return this._maxSize},set:function(a){this._maxSize=
Math.max(a,0);this._size>this._maxSize&&this._removeEntries()},enumerable:!0,configurable:!0});a.prototype.put=function(a,d,c,f){if(c>this._maxSize){if(this._db.has(a)){var b=this._db.get(a);this._size-=b.size;this._db.delete(a)}this._notifyRemoved(a,d)}else!c||0>c?console.warn("Refusing to cache entry with invalid size "+c):(this._db.has(a)?(b=this._db.get(a),this._notifyRemoved(a,b.entry),this._size+=c-b.size,b.entry=d,b.lastUsed=this._age+f,b.size=c):(this._db.set(a,{entry:d,size:c,lastUsed:this._age+
f}),this._size+=c),++this._age,this._size>this._maxSize&&this._removeEntries())};a.prototype.pop=function(a){if(this._db.has(a)){var b=this._db.get(a);this._size-=b.size;this._db.delete(a);++this._hit;return b.entry}++this._miss};a.prototype.getSize=function(){return this._size};a.prototype.getStats=function(){var a=this,d={Size:Math.round(this._size/1048576)+"/"+Math.round(this._maxSize/1048576)+"MB","Hit rate":Math.round(100*this._getHitRate())+"%",Entries:this._db.size.toString()},c={},f=this._age,
l=this._age;this._db.forEach(function(a,b){f=Math.min(f,a.lastUsed);l=Math.max(l,a.lastUsed);g.forEach(function(d){d=d.namespace;if(h.startsWith(b,d))return c[d]=(c[d]||0)+a.size,!1})});d.Entries+=" / "+f+" - "+l;var m={};g.forEach(function(a){var b=a.namespace;!isNaN(a.hitRate)&&0<a.hitRate?(c[b]=c[b]||0,m[b]=Math.round(100*a.hitRate)+"%"):m[b]="0%"});var e=Object.keys(c);e.forEach(function(b){return c[b]=c[b]/a._size*100});e.sort(function(a,b){return c[b]-c[a]});e.forEach(function(a){return d[a]=
Math.round(c[a])+"% / "+m[a]});return d};a.prototype.resetStats=function(){this._hit=this._miss=0;g.forEach(function(a){return a.resetHitRate()})};a.prototype.clear=function(a){var b=this;this._db.forEach(function(c,d){h.startsWith(d,a)&&(b._size-=c.size,b._db.delete(d),b._notifyRemoved(d,c.entry))})};a.prototype.clearAll=function(){var a=this;this._db.forEach(function(b,c){a._notifyRemoved(c,b.entry)});this._size=0;this._db.clear()};a.prototype._getHitRate=function(){return this._hit/(this._hit+
this._miss)};a.prototype._notifyRemoved=function(a,d){this._removeFuncs.forEach(function(b){if(h.startsWith(a,b[0]))b[1](d)})};a.prototype._removeEntries=function(){var a=[];this._db.forEach(function(b,c){a.push([b.lastUsed,c])});a.sort(function(a,b){return a[0]-b[0]});for(var d=0;d<a.length;d++){var c=a[d][1],e=this._db.get(c);this._size-=e.size;this._db.delete(c);this._notifyRemoved(c,e.entry);if(this._size<=.9*this.maxSize)break}};return a}();a.Storage=e})(e||(e={}));return e});