// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/extendsHelper ../../geometry/ScreenPoint ../3d/support/mathUtils ./InputHandler".split(" "),function(h,k,n,p,q,r){function l(g){return!!t[g]}function u(g){for(var e=0;e<g.length;e++)if(!l(g[e]))return!1;return!0}Object.defineProperty(k,"__esModule",{value:!0});var t={click:!0,"double-click":!0,"immediate-click":!0,hold:!0,drag:!0,"key-down":!0,"key-up":!0,"pointer-down":!0,"pointer-move":!0,"pointer-up":!0,"pointer-drag":!0,"mouse-wheel":!0,"pointer-enter":!0,
"pointer-leave":!0,gamepad:!0},m;(function(g){g[g.Left=0]="Left";g[g.Middle=1]="Middle";g[g.Right=2]="Right"})(m||(m={}));h=function(){function g(e){this.handlers=new Map;this.counter=0;this.handlerCounts=new Map;this.view=e;this.inputManager=null}g.prototype.connect=function(e){var b=this;e&&this.disconnect();this.inputManager=e;this.handlers.forEach(function(a,c){return b.inputManager.installHandlers(c,[a])})};g.prototype.disconnect=function(){var e=this;this.inputManager&&this.handlers.forEach(function(b,
a){return e.inputManager.uninstallHandlers(a)});this.inputManager=null};g.prototype.destroy=function(){this.disconnect();this.handlers.clear();this.view=null};g.prototype.register=function(e,b,a){var c=this,d=Array.isArray(e)?e:e.split(",");if(!u(d))return d.some(l)&&console.error("Error: registering input events and other events on the view at the same time is not supported."),null;e=Array.isArray(b)?b:[];a=Array.isArray(b)?a:b;var f=this.createUniqueGroupName();b=new v(this.view,d,e,a);this.handlers.set(f,
b);for(a=0;a<d.length;a++){e=d[a];var w=this.handlerCounts.get(e)||0;this.handlerCounts.set(e,w+1)}this.inputManager&&this.inputManager.installHandlers(f,[b]);return{remove:function(){return c.removeHandler(f,d)}}};g.prototype.hasHandler=function(e){return!!this.handlerCounts.get(e)};g.prototype.removeHandler=function(e,b){if(this.handlers.has(e)){this.handlers.delete(e);for(var a=0;a<b.length;a++){var c=b[a],d=this.handlerCounts.get(c);void 0===d?console.error("Trying to remove handler for event that has no handlers registered: ",
c):1===d?this.handlerCounts.delete(c):this.handlerCounts.set(c,d-1)}}this.inputManager&&this.inputManager.uninstallHandlers(e)};g.prototype.createUniqueGroupName=function(){this.counter+=1;return"viewEvents_"+this.counter};return g}();k.ViewEvents=h;var v=function(g){function e(b,a,c,d){var f=g.call(this,!0)||this;f.view=b;for(b=0;b<a.length;b++)switch(a[b]){case "click":f.registerIncoming("click",c,function(a){return d(f.wrapClick(a))});break;case "double-click":f.registerIncoming("double-click",
c,function(a){return d(f.wrapDoubleClick(a))});break;case "immediate-click":f.registerIncoming("immediate-click",c,function(a){return d(f.wrapImmediateClick(a))});break;case "hold":f.registerIncoming("hold",c,function(a){return d(f.wrapHold(a))});break;case "drag":f.registerIncoming("drag",c,function(a){(a=f.wrapDrag(a))&&d(a)});break;case "key-down":f.registerIncoming("key-down",c,function(a){return d(f.wrapKeyDown(a))});break;case "key-up":f.registerIncoming("key-up",c,function(a){return d(f.wrapKeyUp(a))});
break;case "pointer-down":f.registerIncoming("pointer-down",c,function(a){return d(f.wrapPointer(a,"pointer-down"))});break;case "pointer-move":f.registerIncoming("pointer-move",c,function(a){return d(f.wrapPointer(a,"pointer-move"))});break;case "pointer-up":f.registerIncoming("pointer-up",c,function(a){return d(f.wrapPointer(a,"pointer-up"))});break;case "pointer-drag":f.registerIncoming("pointer-drag",c,function(a){return d(f.wrapPointerDrag(a))});break;case "mouse-wheel":f.registerIncoming("mouse-wheel",
c,function(a){return d(f.wrapMouseWheel(a))});break;case "pointer-enter":f.registerIncoming("pointer-enter",c,function(a){return d(f.wrapPointer(a,"pointer-enter"))});break;case "pointer-leave":f.registerIncoming("pointer-leave",c,function(a){return d(f.wrapPointer(a,"pointer-leave"))});break;case "gamepad":f.registerIncoming("gamepad",c,function(a){d(f.wrapGamepad(a))})}return f}n(e,g);e.prototype.wrapClick=function(b){var a=b.data,c=a.x,d=a.y;return{type:"click",pointerType:a.pointerType,button:a.button,
buttons:a.buttons,x:c,y:d,native:a.native,timestamp:b.timestamp,screenPoint:new p(c,d),mapPoint:this.view.toMap(c,d),stopPropagation:function(){return b.stopPropagation()}}};e.prototype.wrapDoubleClick=function(b){var a=b.data,c=a.x,d=a.y;return{type:"double-click",pointerType:a.pointerType,button:a.button,buttons:a.buttons,x:c,y:d,native:a.native,timestamp:b.timestamp,mapPoint:this.view.toMap(c,d),stopPropagation:function(){return b.stopPropagation()}}};e.prototype.wrapImmediateClick=function(b){var a=
b.data,c=a.x,d=a.y;return{type:"immediate-click",pointerType:a.pointerType,button:a.button,buttons:a.buttons,x:c,y:d,native:a.native,timestamp:b.timestamp,mapPoint:this.view.toMap(c,d),stopPropagation:function(){return b.stopPropagation()}}};e.prototype.wrapHold=function(b){var a=b.data,c=a.x,d=a.y;return{type:"hold",pointerType:a.pointerType,button:a.button,buttons:a.buttons,x:c,y:d,native:a.native,timestamp:b.timestamp,mapPoint:this.view.toMap(c,d),stopPropagation:function(){return b.stopPropagation()}}};
e.prototype.wrapDrag=function(b){var a=b.data,c=a.center,d=c.x,c=c.y,f=a.action,e=a.pointerType,g=a.button;"start"===f&&(this.latestDragStart=a);if(this.latestDragStart){var h=a.pointer.native,k=a.buttons,l=b.timestamp,m={x:this.latestDragStart.center.x,y:this.latestDragStart.center.y};"end"===f&&(this.latestDragStart=void 0);return{type:"drag",action:f,x:d,y:c,origin:m,pointerType:e,button:g,buttons:k,radius:a.radius,angle:q.rad2deg(a.angle),native:h,timestamp:l,stopPropagation:function(){return b.stopPropagation()}}}};
e.prototype.wrapKeyDown=function(b){var a=b.data;return{type:"key-down",key:a.key,repeat:a.repeat,native:a.native,timestamp:b.timestamp,stopPropagation:function(){return b.stopPropagation()}}};e.prototype.wrapKeyUp=function(b){var a=b.data;return{type:"key-up",key:a.key,native:a.native,timestamp:b.timestamp,stopPropagation:function(){return b.stopPropagation()}}};e.prototype.wrapPointer=function(b,a){var c=b.data,d=c.native;return{type:a,x:c.x,y:c.y,pointerId:d.pointerId,pointerType:d.pointerType,
button:c.button,buttons:c.buttons,native:d,timestamp:b.timestamp,stopPropagation:function(){return b.stopPropagation()}}};e.prototype.wrapPointerDrag=function(b){var a=b.data.currentEvent;return{type:"pointer-drag",x:a.x,y:a.y,pointerId:b.data.startEvent.native.pointerId,pointerType:b.data.startEvent.native.pointerType,button:b.data.startEvent.button,buttons:a.buttons,action:b.data.action,origin:{x:b.data.startEvent.x,y:b.data.startEvent.y},native:a.native,timestamp:b.timestamp,stopPropagation:function(){return b.stopPropagation()}}};
e.prototype.wrapMouseWheel=function(b){var a=b.data;return{type:"mouse-wheel",x:a.x,y:a.y,deltaY:a.deltaY,native:a.native,timestamp:b.timestamp,stopPropagation:function(){return b.stopPropagation()}}};e.prototype.wrapGamepad=function(b){var a=b.data,c=a.state;return{type:"gamepad",device:a.device,timestamp:b.timestamp,action:a.action,buttons:c.buttons,axes:c.axes,stopPropagation:function(){return b.stopPropagation()}}};return e}(r.InputHandler)});