// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/extendsHelper ../definitions ../GeometryUtils ./WGLBrush ../shaders/BackgroundPrograms ../shaders/TileInfoPrograms ../../../tiling/enums ../../../../webgl/BufferObject ../../../../webgl/programUtils ../../../../webgl/Texture ../../../../webgl/VertexArrayObject".split(" "),function(g,h,q,r,t,u,k,l,v,m,n,w,p){Object.defineProperty(h,"__esModule",{value:!0});g=function(g){function c(){var a=g.call(this)||this;a._initialized=!1;a._maxWidth=0;a._color=
new Float32Array([1,0,0,1]);return a}q(c,g);c.prototype.dispose=function(){this._outlineProgram&&(this._outlineProgram.dispose(),this._outlineProgram=null);this._tileInfoProgram&&(this._tileInfoProgram.dispose(),this._tileInfoProgram=null);this._outlineVertexArrayObject&&(this._outlineVertexArrayObject.dispose(),this._outlineVertexArrayObject=null);this._tileInfoVertexArrayObject&&(this._tileInfoVertexArrayObject.dispose(),this._tileInfoVertexArrayObject=null);this._canvas=null};c.prototype.draw=
function(a,b){a=a.context;if(b.status!==v.TileStatus.INITIALIZED){this._initialized||this._initialize(a);a.bindVAO(this._outlineVertexArrayObject);a.bindProgram(this._outlineProgram);this._outlineProgram.setUniformMatrix4fv("u_transformMatrix",b.tileTransform.transform);this._outlineProgram.setUniform2fv("u_normalized_origin",b.tileTransform.displayCoord);this._outlineProgram.setUniform1f("u_coord_range",r.TILE_SIZE);this._outlineProgram.setUniform1f("u_depth",0);this._outlineProgram.setUniform4fv("u_color",
this._color);a.setLineWidth(2);a.drawArrays(3,0,4);a.bindVAO();var f=this._getTexture(a,b);f&&(a.bindVAO(this._tileInfoVertexArrayObject),a.bindProgram(this._tileInfoProgram),a.bindTexture(f,0),this._tileInfoProgram.setUniformMatrix4fv("u_transformMatrix",b.tileTransform.transform),this._tileInfoProgram.setUniform2fv("u_normalized_origin",b.tileTransform.displayCoord),this._tileInfoProgram.setUniform1f("u_depth",0),this._tileInfoProgram.setUniform1f("u_coord_ratio",1),this._tileInfoProgram.setUniform2f("u_delta",
8,8),this._tileInfoProgram.setUniform2f("u_dimensions",f.descriptor.width,f.descriptor.height),a.drawArrays(5,0,4),a.bindVAO())}};c.prototype._initialize=function(a){if(this._initialized)return!0;var b=n.createProgram(a,k.background),f=n.createProgram(a,l.tileInfo),d={geometry:[{name:"a_pos",count:2,type:5120,offset:0,stride:2,normalized:!1,divisor:0}]},e=new Int8Array([0,0,1,0,1,1,0,1]),e=m.createVertex(a,35044,e),e=new p(a,k.background.attributes,d,{geometry:e}),c=new Int8Array([0,0,1,0,0,1,1,1]),
c=m.createVertex(a,35044,c);a=new p(a,l.tileInfo.attributes,d,{geometry:c});this._outlineProgram=b;this._tileInfoProgram=f;this._outlineVertexArrayObject=e;this._tileInfoVertexArrayObject=a;return this._initialized=!0};c.prototype._getTexture=function(a,b){if(b.texture)return b.texture;this._canvas||(this._canvas=document.createElement("canvas"),this._canvas.setAttribute("id","canvas2d"),this._canvas.setAttribute("width","256"),this._canvas.setAttribute("height","32"),this._canvas.setAttribute("style",
"display:none"));var c=b.key.id,d=this._canvas.getContext("2d");d.font="24px sans-serif";d.textAlign="left";d.textBaseline="middle";var e=d.measureText(c),e=Math.pow(2,Math.ceil(t.log2(e.width+2)));e>this._maxWidth&&(this._maxWidth=e);d.clearRect(0,0,this._maxWidth,32);d.fillStyle="blue";d.fillText(c,0,16);b.texture=new w(a,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728},this._canvas);return b.texture};return c}(u.default);h.default=g});