// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/extendsHelper ../enums ../Utils ./WGLGeometryBrush ../shaders/MaterialPrograms ../../../../webgl/VertexArrayObject".split(" "),function(m,k,v,w,r,x,t,u){Object.defineProperty(k,"__esModule",{value:!0});m=function(l){function g(){var b=null!==l&&l.apply(this,arguments)||this;b._lineVertexAttributeLayout={geometry:[{name:"a_pos",count:2,type:5122,offset:0,stride:32,normalized:!1,divisor:0},{name:"a_id",count:4,type:5121,offset:4,stride:32,normalized:!0,
divisor:0},{name:"a_color",count:4,type:5121,offset:8,stride:32,normalized:!0,divisor:0},{name:"a_offsetAndNormal",count:4,type:5120,offset:12,stride:32,normalized:!1,divisor:0},{name:"a_accumulatedDistanceAndHalfWidth",count:2,type:5123,offset:16,stride:32,normalized:!1,divisor:0},{name:"a_tlbr",count:4,type:5123,offset:20,stride:32,normalized:!1,divisor:0},{name:"a_segmentDirection",count:4,type:5120,offset:28,stride:32,normalized:!1,divisor:0}],visibility:[{name:"a_visible",count:1,type:5121,offset:0,
stride:1,normalized:!0,divisor:0}]};b._lineVertexAttributeLayoutVV={geometry:[{name:"a_pos",count:2,type:5122,offset:0,stride:44,normalized:!1,divisor:0},{name:"a_id",count:4,type:5121,offset:4,stride:44,normalized:!0,divisor:0},{name:"a_color",count:4,type:5121,offset:8,stride:44,normalized:!0,divisor:0},{name:"a_offsetAndNormal",count:4,type:5120,offset:12,stride:44,normalized:!1,divisor:0},{name:"a_accumulatedDistanceAndHalfWidth",count:2,type:5123,offset:16,stride:44,normalized:!1,divisor:0},
{name:"a_tlbr",count:4,type:5123,offset:20,stride:44,normalized:!1,divisor:0},{name:"a_segmentDirection",count:4,type:5120,offset:28,stride:44,normalized:!1,divisor:0},{name:"a_vv",count:3,type:5126,offset:32,stride:44,normalized:!1,divisor:0}],visibility:[{name:"a_visible",count:1,type:5121,offset:0,stride:1,normalized:!0,divisor:0}]};b._spritesTextureSize=new Float32Array(2);return b}v(g,l);g.prototype.dispose=function(){};g.prototype.getGeometryType=function(){return w.WGLGeometryType.LINE};g.prototype.drawGeometry=
function(b,f,d,c){c=b.context;var n=b.painter,e=b.rendererInfo,g=b.requiredLevel,l=d.indexFrom,m=d.indexCount,h=d.materialInfo;d=h.materialKeyInfo;var a=n.materialManager.getProgram(h.materialKey,b.drawPhase);if(a){c.bindProgram(a);var p=this._getVAO(c,f,d.hasVV());c.bindVAO(p);p=1/b.pixelRatio;if(0<h.texBindingInfo.length){var h=h.texBindingInfo[0],q=h.pageId,k=n.textureManager.sprites;this._spritesTextureSize[0]=k.getWidth(q);this._spritesTextureSize[1]=k.getHeight(q);n.textureManager.bindSpritePage(c,
q,h.unit);a.setUniform1i(h.semantic,h.unit);a.setUniform2fv("u_mosaicSize",this._spritesTextureSize)}b=Math.pow(2,g-f.key.level)/b.pixelRatio;a.setUniform1f("u_zoomFactor",b);a.setUniformMatrix4fv("u_transformMatrix",f.tileTransform.transform);a.setUniformMatrix4fv("u_extrudeMatrix",n.extrudeMatrix);a.setUniform2fv("u_normalized_origin",f.tileTransform.displayCoord);a.setUniform1f("u_opacity",1);a.setUniform1f("u_blur",0+p);a.setUniform1f("u_antialiasing",p);a.setUniform1f("u_zoomFactor",b);d.vvSizeMinMaxValue&&
a.setUniform4fv("u_vvSizeMinMaxValue",e.vvSizeMinMaxValue);d.vvSizeScaleStops&&a.setUniform1f("u_vvSizeScaleStopsValue",e.vvSizeScaleStopsValue);d.vvSizeFieldStops&&(a.setUniform1fv("u_vvSizeFieldStopsValues",e.vvSizeFieldStopsValues),a.setUniform1fv("u_vvSizeFieldStopsSizes",e.vvSizeFieldStopsSizes));d.vvSizeUnitValue&&a.setUniform1f("u_vvSizeUnitValueWorldToPixelsRatio",e.vvSizeUnitValueToPixelsRatio);d.vvColor&&(a.setUniform1fv("u_vvColorValues",e.vvColorValues),a.setUniform4fv("u_vvColors",e.vvColors));
d.vvOpacity&&(a.setUniform1fv("u_vvOpacityValues",e.vvOpacityValues),a.setUniform1fv("u_vvOpacities",e.vvOpacities));c.setFaceCullingEnabled(!0);c.setFrontFace(2305);c.setCullFace(1029);c.drawElements(4,m,5125,4*l);c.setFaceCullingEnabled(!1);c.bindVAO(null)}};g.prototype._getVAO=function(b,f,d){if(f.lineGeometry.vao)return f.lineGeometry.vao;var c=f.lineGeometry.vertexBufferMap[r.C_VBO_GEOMETRY],g=f.lineGeometry.vertexBufferMap[r.C_VBO_VISIBILITY],e=f.lineGeometry.indexBuffer;if(!c||!e)return null;
f.lineGeometry.vao=d?new u(b,t.line.attributes,this._lineVertexAttributeLayoutVV,{geometry:c,visibility:g},e):new u(b,t.line.attributes,this._lineVertexAttributeLayout,{geometry:c,visibility:g},e);return f.lineGeometry.vao};return g}(x.default);k.default=m});