// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/extendsHelper ../enums ../Utils ./WGLGeometryBrush ../shaders/MaterialPrograms ../../../../webgl/VertexArrayObject".split(" "),function(m,n,t,u,p,v,h,r){Object.defineProperty(n,"__esModule",{value:!0});m=function(k){function c(){var a=null!==k&&k.apply(this,arguments)||this;a._isInitialized=!1;a._spritesTextureSize=new Float32Array(2);return a}t(c,k);c.prototype.dispose=function(){};c.prototype.getGeometryType=function(){return u.WGLGeometryType.FILL};
c.prototype.drawGeometry=function(a,d,b,f){f=a.context;var c=a.painter,g=a.rendererInfo,k=a.requiredLevel,m=a.stationary,n=b.indexCount,p=b.indexFrom;this._initialize();var q=b.materialInfo.materialKeyInfo,e=a.painter.materialManager.getProgram(b.materialInfo.materialKey,a.drawPhase);if(e){f.bindProgram(e);var l=this._getVAO(f,d,q.hasVV());f.bindVAO(l);if(0<b.materialInfo.texBindingInfo.length){b=b.materialInfo.texBindingInfo[0];var l=b.pageId,h=a.painter.textureManager.sprites;this._spritesTextureSize[0]=
h.getWidth(l);this._spritesTextureSize[1]=h.getHeight(l);e.setUniform1f("u_zoomFactor",1/Math.pow(2,k-d.key.level)/a.pixelRatio);c.textureManager.bindSpritePage(f,l,b.unit,m?9728:9729);e.setUniform1i(b.semantic,b.unit);e.setUniform2fv("u_mosaicSize",this._spritesTextureSize)}e.setUniformMatrix4fv("u_transformMatrix",d.tileTransform.transform);e.setUniform2fv("u_normalized_origin",d.tileTransform.displayCoord);e.setUniform1f("u_opacity",1);q.vvColor&&(e.setUniform1fv("u_vvColorValues",g.vvColorValues),
e.setUniform4fv("u_vvColors",g.vvColors));q.vvOpacity&&(e.setUniform1fv("u_vvOpacityValues",g.vvOpacityValues),e.setUniform1fv("u_vvOpacities",g.vvOpacities));f.drawElements(4,n,5125,4*p);f.bindVAO(null)}};c.prototype._initialize=function(){if(this._isInitialized)return!0;this._fillVertexAttributeLayout={geometry:[{name:"a_pos",count:2,type:5122,offset:0,stride:24,normalized:!1,divisor:0},{name:"a_id",count:4,type:5121,offset:4,stride:24,normalized:!0,divisor:0},{name:"a_color",count:4,type:5121,
offset:8,stride:24,normalized:!0,divisor:0},{name:"a_tlbr",count:4,type:5123,offset:12,stride:24,normalized:!1,divisor:0},{name:"a_aux",count:4,type:5121,offset:20,stride:24,normalized:!1,divisor:0}],visibility:[{name:"a_visible",count:1,type:5121,offset:0,stride:1,normalized:!0,divisor:0}]};this._fillVertexAttributeLayoutVV={geometry:[{name:"a_pos",count:2,type:5122,offset:0,stride:32,normalized:!1,divisor:0},{name:"a_id",count:4,type:5121,offset:4,stride:32,normalized:!0,divisor:0},{name:"a_color",
count:4,type:5121,offset:8,stride:32,normalized:!0,divisor:0},{name:"a_tlbr",count:4,type:5123,offset:12,stride:32,normalized:!1,divisor:0},{name:"a_aux",count:4,type:5121,offset:20,stride:32,normalized:!1,divisor:0},{name:"a_vv",count:2,type:5126,offset:24,stride:32,normalized:!1,divisor:0}],visibility:[{name:"a_visible",count:1,type:5121,offset:0,stride:1,normalized:!0,divisor:0}]};this._isInitialized=!0};c.prototype._getVAO=function(a,d,b){if(d.fillGeometry.vao)return d.fillGeometry.vao;var f=
d.fillGeometry.vertexBufferMap[p.C_VBO_GEOMETRY],c=d.fillGeometry.vertexBufferMap[p.C_VBO_VISIBILITY],g=d.fillGeometry.indexBuffer;if(!f||!g)return null;d.fillGeometry.vao=b?new r(a,h.fill.attributes,this._fillVertexAttributeLayoutVV,{geometry:f,visibility:c},g):new r(a,h.fill.attributes,this._fillVertexAttributeLayout,{geometry:f,visibility:c},g);return d.fillGeometry.vao};return c}(v.default);n.default=m});