// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/has ../../../../../../core/Logger ../../../../../../core/libs/earcut/earcut ../../color ../../definitions ../../enums ../../enums ../../number ../../TileClipper ../../WGLDisplayRecord ../Tesselator ./WGLMeshTemplate".split(" "),function(w,E,H,I,J,K,L,C,D,M,m,N,F,O,P){Object.defineProperty(E,"__esModule",{value:!0});var Q=J.getLogger("esri.views.2d.engine.webgl.mesh.templates.WGLFillTemplate"),v=[],B=[];w=
function(w){function l(b,a,d,e,c,g,f,h){var k=w.call(this)||this;k.fillColor=e;k.tl=c;k.br=g;k.aux=f;k.isBFS=h;k.geometryType=D.WGLGeometryType.FILL;k.useLibtess=!1;e=I("esri-featurelayer-webgl");k.useLibtess="libtess"===((e||{}).tesselator||"libtess");k.useLibtess&&(k._tesselator=new O.default);k.vvFlags=a;k._materialStore=b;k.materialId=k._materialStore.createSpriteMaterial(d,k.geometryType,a);k._tileClipper=new N.TileClipper(0,0,0,1,8);k._tileClipper.setExtent(C.TILE_SIZE);return k}H(l,w);l.fromSimpleFill=
function(b,a,d,e,c,g){void 0===g&&(g=!1);d=(c=d.color)&&"none"!==d.style&&L.premultiplyAlphaRGBA(c)||0;if(!e)return new l(b,a,null,d,0,0,0,g);var f=e.rect;c=f.x+1;var h=f.y+1,k=f.x+1+e.width,G=f.y+1+e.height,f=m.i1616to32(c,h),x=m.i1616to32(k,G);c=m.i8888to32(m.nextHighestPowerOfTwo(k-c),m.nextHighestPowerOfTwo(G-h),0,0);return new l(b,a,e,d,f,x,c,g)};l.fromPictureFill=function(b,a,d,e,c,g){void 0===g&&(g=!1);c=C.PICTURE_FILL_COLOR;var f=e.rect,h=f.x+1+e.width,k=f.y+1+e.height,f=m.i1616to32(f.x+1,
f.y+1),h=m.i1616to32(h,k);d=m.i8888to32(m.nextHighestPowerOfTwo(d.width),m.nextHighestPowerOfTwo(d.height),0,0);return new l(b,a,e,c,f,h,d,g)};l.prototype.writeMesh=function(b,a,d,e,c,g,f){v.length=0;if(this.vvFlags&M.WGLVVFlag.COLOR||0!==this.fillColor)if("esriGeometryPolygon"!==d)Q.error("Unable to handle geometryType: "+d);else{var h=c.geometry,h=(c=this._isClippingRequired(h))?this._clip(h,!this.useLibtess):h.rings;return this.useLibtess?this._writeMeshLibtess(b,a,d,e,h,c,g,f):this._writeMeshEarcut(b,
a,d,e,h,c,g,f)}};l.prototype._isClippingRequired=function(b){var a=C.TILE_SIZE+8,d=0;for(b=b.rings;d<b.length;d++){var e=b[d],c=e.length;if(!(3>c)){var g=e[0][0],f=e[0][1];if(-8>g||g>a||-8>f||f>a)return!0;for(var h=1;h<c;++h)if(g+=e[h][0],f+=e[h][1],-8>g||g>a||-8>f||f>a)return!0}}return!1};l.prototype._clip=function(b,a){var d;this._tileClipper.reset(3);for(var e=0,c=b.rings;e<c.length;e++){var g=c[e],f=g.length;if(!(3>f)){b=g[0][0];d=g[0][1];this._tileClipper.moveTo(b,d);for(var h=1;h<f;++h)b+=g[h][0],
d+=g[h][1],this._tileClipper.lineTo(b,d);this._tileClipper.close()}}return this._tileClipper.result(a)};l.prototype._writeMeshLibtess=function(b,a,d,e,c,g,f,h){if(c&&c.length){d=this._materialStore.get(this.materialId);f=[];var k=a.indexVector,l=a.get("geometry");a=a.get("visibility");var x=new F(e,this.geometryType,this.materialId),r=this._getOffset(l,d);x.vertexFrom=r;x.indexFrom=k.length;b.push(x);this._tesselator.beginPolygon(v,f);for(b=0;b<c.length;b++){var t=c[b];if(!(3>t.length)){this._tesselator.beginContour();
var p=void 0,u=void 0;g?(p=t[0].x,u=t[0].y):(p=t[0][0],u=t[0][1]);var n=[p,u,0];this._tesselator.addVertex(n,n);for(n=1;n<t.length-1;n++){var q=void 0,m=void 0;g?(p=t[n].x,u=t[n].y):(q=t[n][0],m=t[n][1],p+=q,u+=m);q=[p,u,0];this._tesselator.addVertex(q,q)}this._tesselator.endContour()}}this._tesselator.endPolygon();this._writeVerticesLibTess(x,l,a,e,v,d,h);this._writeIndicesLibTess(x,k,r,f)}};l.prototype._writeMeshEarcut=function(b,a,d,e,c,g,f,h){if(c&&c.length){d=this._materialStore.get(this.materialId);
f=a.indexVector;var k=a.get("geometry");a=a.get("visibility");var l=new F(e,this.geometryType,this.materialId),m=this._getOffset(k,d);l.vertexFrom=m;l.indexFrom=f.length;b.push(l);for(var r=b=0,t=0;t<c.length;t++){var p=c[t],u=r,n=void 0,q=void 0;g?(n=p[0].x,q=p[0].y):(n=p[0][0],q=p[0][1]);v[r++]=n;v[r++]=q;for(var w=0,y=1;y<p.length;++y){var z=void 0,A=void 0;g?(z=n,A=q,n=p[y].x,q=p[y].y,z=n-z,A=q-A):(z=p[y][0],A=p[y][1],n+=z,q+=A);w-=z*(q+q+A);v[r++]=n;v[r++]=q}0<w?(0<u-b&&(this._write(l,f,k,a,
m,e,v,B,b,u,d,h),b=u),B.length=0):0>w?0<u-b?B.push(.5*(u-b)):r=u:r=u}0<r-b&&this._write(l,f,k,a,m,e,v,B,b,r,d,h);v.length=B.length=0}};l.prototype._write=function(b,a,d,e,c,g,f,h,k,l,m,r){c=K(f.slice(k,l),h,2);c.length&&(k=this._getOffset(d,m),this._writeVertices(b,d,e,g,f,h,m,r),this._writeIndices(b,a,k,c))};l.prototype._getOffset=function(b,a){a=a.materialKeyInfo.hasVV()?8:6;return b.length/a};l.prototype._writeVertices=function(b,a,d,e,c,g,f,h){for(g=0;g<c.length;g+=2){var k=m.i1616to32(c[g],c[g+
1]);a.push(k);a.push(e);a.push(this.fillColor);a.push(this.tl);a.push(this.br);a.push(this.aux);this._writeVV(a,h,f);d.push(255);b.vertexCount++}};l.prototype._writeIndices=function(b,a,d,e){for(var c=0;c<e.length;c+=3)a.push(d+e[c]),a.push(d+e[c+1]),a.push(d+e[c+2]),b.indexCount+=3};l.prototype._writeVerticesLibTess=function(b,a,d,e,c,g,f){for(var h=0;h<c.length;h+=2){var k=m.i1616to32(c[h],c[h+1]);a.push(k);a.push(e);a.push(this.fillColor);a.push(this.tl);a.push(this.br);a.push(this.aux);this._writeVV(a,
f,g);d.push(255);b.vertexCount++}};l.prototype._writeIndicesLibTess=function(b,a,d,e){for(var c=0;c<e.length;c++)a.push(d+e[c]),b.indexCount++};l.prototype._writeVV=function(b,a,d){d.materialKeyInfo.hasVV()&&(this.isBFS?(b.push(4294967295),b.push(4294967295)):(b.push(a[D.VVType.COLOR]),b.push(a[D.VVType.OPACITY])))};return l}(P.default);E.default=w});