// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Logger ../../../../../../core/screenUtils ../../../../../../core/libs/gl-matrix/mat2d ../../../../../../core/libs/gl-matrix/vec2 ../../color ../../definitions ../../enums ../../number ../../WGLDisplayRecord ./WGLMeshTemplate".split(" "),function(u,z,C,D,r,x,v,A,E,w,t,F,G){Object.defineProperty(z,"__esModule",{value:!0});var B=D.getLogger("esri.views.2d.engine.webgl.WGLMeshTemplate");u=function(u){function d(c,
a,b,p,f,h,g,m,k,y,n){var l=u.call(this)||this;l.geometryType=w.WGLGeometryType.MARKER;var e=v.create(),q=x.create(),d=n.sdf?.5:1;x.translate(q,q,new Float32Array([d*b,d*-p]));f&&x.rotate(q,q,3.14159265359/180*f);l._materialStore=c;l.vvFlags=a;l._materialId=c.createSpriteMaterial(n,l.geometryType,a);l._fillColor=h;l._outlineColor=k;l._sizeOutlineWidth=t.i8888to32(g,m,y,0);c=Math.round(n.rect.x/4)-128;a=Math.round(n.rect.y/4)-128;f=c+Math.round(n.rect.width/4);n=a+Math.round(n.rect.height/4);e.set([-.5*
g,-.5*m]);v.transformMat2d(e,e,q);l._offsetAndTexUpperLeft=t.i8888to32(e[0],e[1],c,a);e.set([.5*g,-.5*m]);v.transformMat2d(e,e,q);l._offsetAndTexUpperRight=t.i8888to32(e[0],e[1],f,a);e.set([-.5*g,.5*m]);v.transformMat2d(e,e,q);l._offsetAndTexBottomLeft=t.i8888to32(e[0],e[1],c,n);e.set([.5*g,.5*m]);v.transformMat2d(e,e,q);l._offsetAndTexBottomRight=t.i8888to32(e[0],e[1],f,n);l.height=m;l.width=g;l.xOffset=b;l.yOffset=p;return l}C(d,u);d.fromPictureMarker=function(c,a,b,p,f){f=Math.round(r.pt2px(b.width));
var h=Math.round(r.pt2px(b.height)),g=E.PICTURE_FILL_COLOR,m=Math.round(r.pt2px(b.xoffset||0)),k=Math.round(r.pt2px(b.yoffset||0));return new d(c,a,m,k,b.angle,g,f,h,0,0,p)};d.fromSimpleMarker=function(c,a,b,p,f){f=A.premultiplyAlphaRGBA(b.color);var h=Math.round(r.pt2px(b.size)),g=Math.round(r.pt2px(b.xoffset||0)),m=Math.round(r.pt2px(b.yoffset||0)),k=b.outline,y=(k&&k.color&&A.premultiplyAlphaRGBA(k.color))|0,k=(k&&k.width&&Math.round(r.pt2px(k.width)))|0;return new d(c,a,g,m,b.angle,f,h,h,y,k,
p)};d.prototype.writeMesh=function(c,a,b,p,f,h,g){h=this._materialStore.get(this._materialId);var m=a.indexVector,k=a.get("geometry");a=a.get("visibility");var d=new F(p,this.geometryType,this._materialId),n=this._getOffset(k,h);c.push(d);d.vertexFrom=n;d.indexFrom=m.length;switch(b){case "esriGeometryPoint":b=f.geometry;c=b.x;b=b.y;this._writeVertices(d,k,a,p,this._getPos(c,b),h,g);this._writeIndices(d,m,n);break;case "esriGeometryPolyline":this._writeMany(d,m,k,a,n,p,f.geometry.paths[0],h,g);break;
case "esriGeometryPolygon":(b=f.centroid)?(c=b.x,b=b.y,this._writeVertices(d,k,a,p,this._getPos(c,b),h,g),this._writeIndices(d,m,n)):B.error("Tried to render polygon geometries as markers, but found no centroid!");break;case "esriGeometryMultipoint":this._writeMany(d,m,k,a,n,p,f.geometry.points,h,g);break;default:B.error("Unable to handle geometryType: "+b)}};d.prototype._getPos=function(c,a){return t.i1616to32(c,a)};d.prototype._writeMany=function(c,a,b,d,f,h,g,m,k){for(var p=0,n=0,l=0,e=0;e<g.length;e++){var q=
g[e],r=q[0],q=q[1];this._writeVertices(c,b,d,h,this._getPos(r+p,q+n),m,k);this._writeIndices(c,a,f+l);p+=r;n+=q;l+=4}};d.prototype._getOffset=function(c,a){a=a.materialKeyInfo.hasVV()?10:6;return c.length/a};d.prototype._writeVertices=function(c,a,b,d,f,h,g){a.push(f);a.push(this._offsetAndTexUpperLeft);a.push(d);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,g,h);b.push(255);a.push(f);a.push(this._offsetAndTexUpperRight);a.push(d);a.push(this._fillColor);
a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,g,h);b.push(255);a.push(f);a.push(this._offsetAndTexBottomLeft);a.push(d);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,g,h);b.push(255);a.push(f);a.push(this._offsetAndTexBottomRight);a.push(d);a.push(this._fillColor);a.push(this._outlineColor);a.push(this._sizeOutlineWidth);this._writeVV(a,g,h);b.push(255);c.vertexCount+=4};d.prototype._writeVV=function(c,a,b){b.materialKeyInfo.hasVV()&&
(c.push(a[w.VVType.SIZE]),c.push(a[w.VVType.COLOR]),c.push(a[w.VVType.OPACITY]),c.push(a[w.VVType.ROTATION]))};d.prototype._writeIndices=function(c,a,b){a.push(b+0);a.push(b+1);a.push(b+2);a.push(b+1);a.push(b+3);a.push(b+2);c.indexCount+=6};return d}(G.default);z.default=u});