// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/Error ../../../../../../core/Logger ../../../../../../core/promiseUtils ../../enums ./WGLFillTemplate ./WGLLineTemplate ./WGLMarkerTemplate ./WGLTextTemplate ../../util/BidiText ../../util/vvFlagUtils".split(" "),function(p,q,u,v,k,l,r,m,t,w,x,h){function y(b,a){return b.acquire().then(function(){return a()}).then(function(){return b.release()})}Object.defineProperty(q,"__esModule",{value:!0});var n=v.getLogger("esri.views.2d.engine.webgl.mesh.templates.WGLTemplateStore"),
z=[],A=function(){function b(){this._resolver=this._promise=null}b.prototype.isHeld=function(){return!!this._promise};b.prototype.acquire=function(){var a=this;if(this._promise)return this._promise.then(function(){return a.acquire()});this._promise=k.create(function(d){return a._resolver=d});return k.resolve()};b.prototype.release=function(){var a=this._resolver;this._promise=this._resolver=null;a()};return b}();p=function(){function b(a,d){this._templateIdCounter=this._idCounter=0;this._idToTemplateGroup=
new Map;this._symbolToTemplate=new Map;this._fetchQueue=[];this._idToResolver=new Map;this._pixelRatio=1;this._lock=new A;this._fetchResource=a;this._pixelRatio=d}b.prototype.createTemplateGroup=function(a,d,c,b){var g=this._hashSymbol(a);if(!this._symbolToTemplate.has(g)){var f=[];d&&this._createMeshTemplates(f,c,d,b,this._pixelRatio,!0);this._createMeshTemplates(f,c,a,b,this._pixelRatio,!1);a=this._createGroupId();this._idToTemplateGroup.set(a,f);this._symbolToTemplate.set(g,a)}return this._symbolToTemplate.get(g)};
b.prototype.getTemplateGroup=function(a){return this._idToTemplateGroup.has(a)?this._idToTemplateGroup.get(a):z};b.prototype.finalize=function(){return this._fetchQueue.length||this._lock.isHeld()?y(this._lock,this._fetchAllQueuedResources.bind(this)):k.resolve()};b.prototype._fetchAllQueuedResources=function(){var a=this;if(!this._fetchQueue.length)return k.resolve();var d=this._fetchQueue;this._fetchQueue=[];return this._fetchResource(d).then(function(c){for(var d=0;d<c.length;d++){var b=c[d],h=
b.id,b=b.mosaicItem;a._idToResolver.get(h)(b);a._idToResolver.delete(h)}}).catch(function(c){"cancel"===c.dojoType?a._fetchQueue=a._fetchQueue.concat(d):n.error(u("mapview-template-store","Unable to fetch requested texture resources",c))})};b.prototype._createGroupId=function(){return this._idCounter++};b.prototype._createTemplateId=function(){return this._templateIdCounter++};b.prototype._getCodepoints=function(a){a=x.bidiText(a.text)[0];for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c));return b};
b.prototype._getMosaicItem=function(a){var b=this,c=this._createTemplateId(),f="text"===a.type&&this._getCodepoints(a),g=k.create(function(a){return b._idToResolver.set(c,a)});this._fetchQueue.push({symbol:a.toJSON(),id:c,glyphIds:f});return g};b.prototype._hashSymbol=function(a){return JSON.stringify(a)};b.prototype._createMeshTemplates=function(a,b,c,f,g,k){if(-1!==c.type.indexOf("3d"))return n.error("3D symbols are not supported with MapView"),a;var d=a.length;a.push(null);switch(c.type){case l.EsriSymbolTypeKebab.SIMPLE_MARKER:return this._getMosaicItem(c).then(function(e){a[d]=
t.default.fromSimpleMarker(b,h.getMarkerVVFlags(f),c,e.spriteMosaicItem,g)}),a;case l.EsriSymbolTypeKebab.PICTURE_MARKER:return this._getMosaicItem(c).then(function(e){a[d]=t.default.fromPictureMarker(b,h.getMarkerVVFlags(f),c,e.spriteMosaicItem,g)}),a;case l.EsriSymbolTypeKebab.SIMPLE_FILL:return this._getMosaicItem(c).then(function(e){a[d]=r.default.fromSimpleFill(b,h.getFillVVFlags(f),c,e.spriteMosaicItem,g,k)}),c.outline&&(a.push(null),this._getMosaicItem(c.outline).then(function(e){a[d+1]=m.default.fromSimpleLine(b,
h.getLineVVFlags(f,!0),c.outline,e.spriteMosaicItem,g)})),a;case l.EsriSymbolTypeKebab.PICTURE_FILL:return this._getMosaicItem(c).then(function(e){a[d]=r.default.fromPictureFill(b,h.getFillVVFlags(f),c,e.spriteMosaicItem,g,k)}),c.outline&&(a.push(null),this._getMosaicItem(c.outline).then(function(e){a[d+1]=m.default.fromSimpleLine(b,h.getLineVVFlags(f,!0),c.outline,e.spriteMosaicItem,g)})),a;case l.EsriSymbolTypeKebab.SIMPLE_LINE:return this._getMosaicItem(c).then(function(e){a[d]=m.default.fromSimpleLine(b,
h.getLineVVFlags(f,!1),c,e.spriteMosaicItem,g)}),a;case l.EsriSymbolTypeKebab.TEXT:return this._getMosaicItem(c).then(function(e){a[d]=w.default.fromText(b,h.getTextVVFlags(f),c,g,e.glyphMosaicItems)}),a;default:return n.error("Unable to create mesh template for unknown symbol type: "+c.type),a}};return b}();q.default=p});