// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../geometry ../../Graphic ../../core/Accessor ../../core/Evented ../../core/Handles ../../core/watchUtils ../../core/accessorSupport/decorators ../../layers/GraphicsLayer ../../symbols/SimpleFillSymbol ../../symbols/SimpleLineSymbol ../../symbols/SimpleMarkerSymbol ../../views/2d/draw/Draw ../../views/2d/draw/support/Box ../../views/2d/draw/support/GraphicMover ../../views/2d/draw/support/Reshape ./support/sketchUtils".split(" "),
function(ha,ia,x,r,t,n,y,z,E,w,p,F,A,B,v,G,C,H,D,q){var I=function(g){function d(){return null!==g&&g.apply(this,arguments)||this}x(d,g);r([p.property()],d.prototype,"reset",void 0);return d=r([p.subclass()],d)}(p.declared(y,z)),u=function(g){function d(){var a=null!==g&&g.apply(this,arguments)||this;a.type=null;return a}x(d,g);r([p.property()],d.prototype,"type",void 0);r([p.property()],d.prototype,"canUndo",void 0);r([p.property()],d.prototype,"canRedo",void 0);r([p.property()],d.prototype,"complete",
void 0);r([p.property()],d.prototype,"cancel",void 0);r([p.property()],d.prototype,"undo",void 0);r([p.property()],d.prototype,"redo",void 0);return d=r([p.subclass()],d)}(p.declared(y,z)),J=function(){return function(g){this.tool=g;this.type="create-init"}}(),K=function(){return function(g,d){this.tool=g;this.geometry=d;this.type="create-start"}}(),L=function(){return function(g,d){this.tool=g;this.geometry=d;this.type="create"}}(),M=function(){return function(g){this.tool=g;this.type="create-cancel"}}(),
N=function(){return function(g,d){this.tool=g;this.geometry=d;this.type="create-complete"}}(),O=function(){return function(g){this.geometry=g;this.type="update-init"}}(),P=function(){return function(g){this.geometry=g;this.type="update"}}(),Q=function(){return function(g){this.geometry=g;this.type="update-cancel"}}(),R=function(){return function(g){this.geometry=g;this.type="update-complete"}}(),S=function(){return function(){this.type="reset"}}(),T=function(){return function(g,d){this.geometry=g;
this.angle=d;this.type="rotate-start"}}(),U=function(){return function(g,d){this.geometry=g;this.angle=d;this.type="rotate"}}(),V=function(){return function(g,d){this.geometry=g;this.angle=d;this.type="rotate-complete"}}(),W=function(){return function(g,d,a){this.geometry=g;this.xScale=d;this.yScale=a;this.type="scale-start"}}(),X=function(){return function(g,d,a){this.geometry=g;this.xScale=d;this.yScale=a;this.type="scale"}}(),Y=function(){return function(g,d,a){this.geometry=g;this.xScale=d;this.yScale=
a;this.type="scale-complete"}}(),Z=function(){return function(g,d,a){this.geometry=g;this.dx=d;this.dy=a;this.type="move-start"}}(),aa=function(){return function(g,d,a){this.geometry=g;this.dx=d;this.dy=a;this.type="move"}}(),ba=function(){return function(g,d,a){this.geometry=g;this.dx=d;this.dy=a;this.type="move-complete"}}(),ca=function(){return function(g){this.geometry=g;this.type="reshape-start"}}(),da=function(){return function(g){this.geometry=g;this.type="reshape"}}(),ea=function(){return function(g){this.geometry=
g;this.type="reshape-complete"}}(),fa=function(){return function(g){this.geometry=g;this.type="undo"}}(),ga=function(){return function(g){this.geometry=g;this.type="redo"}}();return function(g){function d(a){a=g.call(this,a)||this;a._activeLineGraphic=null;a._centerGraphic=null;a._centerSymbol=new v({type:"simple-marker",style:"circle",size:3,color:[255,255,255],outline:{color:[100,100,100]}});a._defaultGraphicsLayer=null;a._defaultSegmentOffset=48;a._handles=new E;a._lineGraphic=null;a._operationHandle=
null;a._targetGraphic=null;a._vertexGraphics=[];a.activeFillSymbol=new A({type:"simple-fill",style:"solid",color:[150,150,150,.2],outline:{color:[0,0,0,0]}});a.activeLineSymbol=new B({type:"simple-line",color:[12,207,255,1],width:2,style:"dash"});a.activePointSymbol=new v({type:"simple-marker",style:"circle",size:6,color:[12,207,255],outline:{color:[50,50,50],width:1}});a.draw=null;a.graphic=null;a.hoverVertexSymbol=new v({type:"simple-marker",style:"circle",size:8,color:[33,205,255],outline:{color:[0,
12,255],width:1}});a.layer=null;a.pointSymbol=new v({type:"simple-marker",style:"circle",size:6,color:[255,255,255],outline:{color:[50,50,50],width:1}});a.polygonSymbol=new A({type:"simple-fill",color:[150,150,150,.2],outline:{color:[50,50,50],width:2}});a.polylineSymbol=new B({type:"simple-line",color:[130,130,130],width:2});a.selectedVertexSymbol=new v({type:"simple-marker",style:"circle",size:8,color:[255,255,255],outline:{color:[0,12,255],width:1}});a.updatePointSymbol=new v({type:"simple-marker",
size:10,color:[0,200,255,.5],outline:{color:"black",width:1}});a.updatePolygonSymbol=new A({type:"simple-fill",color:[12,207,255,.2],outline:{join:"round",color:[12,207,255],width:2}});a.updatePolylineSymbol=new B({type:"simple-line",color:[12,207,255],width:2});a.vertexSymbol=new v({type:"simple-marker",style:"circle",size:6,color:[33,205,255],outline:{color:[0,12,255],width:1}});a.view=null;return a}x(d,g);d.prototype.initialize=function(){var a=this;this._handles.add([w.whenOnce(this,"view.ready",
function(){a._set("draw",new G({view:a.view}))}),w.when(this,"layer",function(){a._defaultGraphicsLayer&&(a.view&&a.view.map.remove(a._defaultGraphicsLayer),a._defaultGraphicsLayer.destroy(),a._defaultGraphicsLayer=null)}),w.whenNot(this,"layer",function(b){a._defaultGraphicsLayer=new F({listMode:"hide"});a.view&&a.view.map.add(a._defaultGraphicsLayer)}),w.pausable(this,"layer",function(b,c){c&&(a._clearGraphics(c),c.remove(a.graphic));a.reset()})])};d.prototype.destroy=function(){this.reset();this._handles.removeAll();
this._handles=null;this._defaultGraphicsLayer&&(this.view&&this.view.map.remove(this._defaultGraphicsLayer),this._defaultGraphicsLayer.destroy(),this._defaultGraphicsLayer=null);this.draw&&this.draw.destroy();this._set("draw",null);this._set("view",null);this.emit("destroy")};Object.defineProperty(d.prototype,"_layer",{get:function(){return this.layer||this._defaultGraphicsLayer},enumerable:!0,configurable:!0});Object.defineProperty(d.prototype,"state",{get:function(){var a=!!this.get("view.ready"),
b=this._operationHandle;return a&&b?"create"===b.type?"creating":"updating":a?"ready":"disabled"},enumerable:!0,configurable:!0});d.prototype.complete=function(){this._operationHandle&&this._operationHandle.complete();this.draw.reset()};d.prototype.create=function(a,b){var c=this;this._operationHandle&&this._operationHandle.cancel();this._operationHandle=null;var d;switch(a){case "point":d=this._createPointOperation(b);break;case "polygon":d=this._createPolygonOperation(b);break;case "polyline":d=
this._createPolylineOperation(b);break;case "multipoint":d=this._createMultipointOperation(b);break;case "rectangle":d=this._createRectangleOperation(b);break;case "circle":d=this._createCircleOperation(b);break;case "ellipse":d=this._createEllipseOperation(b);break;case "triangle":d=this._createTriangleOperation(b)}if(d)return d.on("complete",function(){d===c._operationHandle&&(c._operationHandle=null,c._emitCreateCompleteEvent(a))}),d.on("cancel",function(){d===c._operationHandle&&(c._operationHandle=
null,c._emitCreateCancelEvent(a))}),this._operationHandle=d,this._emitCreateInitEvent(a),d};d.prototype.reset=function(){this._clearGraphics();this._operationHandle&&this._operationHandle.cancel();this._operationHandle=null;this.graphic&&(this._layer&&this._layer.remove(this.graphic),this._set("graphic",null));this.view.container.style.cursor="default";this.draw.reset();this._emitResetEvent()};d.prototype.update=function(a,b){var c=this;this._operationHandle&&this._operationHandle.cancel();this._operationHandle=
null;if(!this._layer||!a||!a.geometry)return null;var d;switch(a.geometry.type){case "point":d=this._updatePointOperation(a,b);break;case "polyline":case "polygon":d=this._updateOperation(a,b)}if(!d)return null;d.on("complete",function(){d===c._operationHandle&&(c._operationHandle=null,c._emitUpdateCompleteEvent())});d.on("cancel",function(){d===c._operationHandle&&(c._operationHandle=null,c._emitUpdateCancelEvent())});this._operationHandle=d;this._emitUpdateInitEvent();return d};d.prototype.undo=
function(){this._operationHandle&&this._operationHandle.canUndo()&&this._operationHandle.undo()};d.prototype.redo=function(){this._operationHandle&&this._operationHandle.canRedo()&&this._operationHandle.redo()};d.prototype._createPointOperation=function(a){var b=this;a=this.draw.create("point",a);var c=null,d=[a.on("cursor-update",function(a){c=b._displayCrosshairCursor()}),a.on("draw-complete",function(c){b._layer.remove(b.graphic);c=c.coordinates;b._set("graphic",new n(new t.Point({x:c[0],y:c[1],
spatialReference:b.view.spatialReference}),b.pointSymbol));f&&f.complete()})],f=new u({type:"create",complete:function(){b._layer.remove(b.graphic);c&&c.reset();d.forEach(function(b){return b.remove()});b.draw.reset();f.emit("complete")},cancel:function(){b._layer.remove(b.graphic);c&&c.reset();d.forEach(function(b){return b.remove()});b.draw.reset();f.emit("cancel")}});return f};d.prototype._createPolygonOperation=function(a){var b=this,c=this.draw.create("polygon",a),d=new t.Point,f=null,e=null,
k=!1,l=[c.on("vertex-add",function(c){var a=c.vertices;e=c;k&&b._snapLastVertexToAxis(a);b._showPolygonGraphic(a,!1);1===a.length?b._emitCreateStartEvent("polygon"):b._emitCreateEvent("polygon")}),c.on("vertex-remove",function(c){var a=c.vertices;e=c;k&&b._snapLastVertexToAxis(a);b._showPolygonGraphic(a,!1);b._emitCreateEvent("polygon")}),c.on("vertex-update",function(c){var a=c.vertices;e=c;k&&b._snapLastVertexToAxis(a);b._showPolygonGraphic(a,!1);b._emitCreateEvent("polygon")}),c.on("cursor-update",
function(c){var a=c.vertices,h=c.native;e=c;b.view.toMap(h.x,h.y,d);k&&b._snapLastVertexToAxis(a);b._showPolygonGraphic(a,!0)}),c.on("draw-complete",function(c){b._layer.remove(b.graphic);b._set("graphic",new n(q.createPolygon([c.vertices],b.view),b.polygonSymbol));h&&h.complete()}),c.on("undo",function(c){c=c.vertices;var a=e&&"cursor-update"===e.type;c.length?(k&&b._snapLastVertexToAxis(c),b._showPolygonGraphic(c,a)):b._clearGraphics()}),c.on("redo",function(c){c=c.vertices;var a=e&&"cursor-update"===
e.type;k&&b._snapLastVertexToAxis(c);b._showPolygonGraphic(c,a)}),this.view.on("key-down",function(a){var d=c.vertices.slice(0),m=e&&"cursor-update"===e.type;"Control"!==a.key||k?"z"===a.key&&h&&h.canUndo()?(a.stopPropagation(),h.undo()):"r"===a.key&&h&&h.canRedo()?(a.stopPropagation(),h.redo()):"Escape"===a.key&&h&&h.cancel():(k=!0,m&&b._snapLastVertexToAxis(d),b._showPolygonGraphic(d,m))}),this.view.on("key-up",function(a){var h=c.vertices.slice(0),m=e&&"cursor-update"===e.type;"Control"===a.key&&
(k=!1,h.pop(),h.push([d.x,d.y]),b._showPolygonGraphic(h,m))}),this.view.on("pointer-down",function(c){b.view.hitTest(c).then(function(a){a=a.results;a.length&&a[0].graphic&&0===b._vertexGraphics.indexOf(a[0].graphic)&&c.stopPropagation()})}),this.view.on("click",function(a){b.view.hitTest(a).then(function(h){h=h.results;h.length&&h[0].graphic&&0===b._vertexGraphics.indexOf(h[0].graphic)&&2<b._vertexGraphics.length&&(a.stopPropagation(),e&&"cursor-update"===e.type&&c.vertices.pop(),c.complete())})}),
this.view.on("pointer-move",function(a){b.view.hitTest(a).then(function(a){f=b._displayCrosshairCursor()})})],h=new u({type:"create",complete:function(){b._clearGraphics();b._layer.remove(b.graphic);f&&f.reset();l.forEach(function(b){return b.remove()});b.draw.reset();h.emit("complete")},cancel:function(){b._clearGraphics();b._layer.remove(b.graphic);f&&f.reset();l.forEach(function(b){return b.remove()});b.draw.reset();h.emit("cancel")},undo:function(){c&&c.undo();b._emitUndoEvent()},redo:function(){c&&
c.redo();b._emitRedoEvent()},canUndo:function(){return c&&c.canUndo()},canRedo:function(){return c&&c.canRedo()}});return h};d.prototype._createPolylineOperation=function(a){var b=this,c=this.draw.create("polyline",a),d=new t.Point,f=null,e=null,k=!1,l=[c.on("vertex-add",function(a){var c=a.vertices;f=a;k&&b._snapLastVertexToAxis(c);b._showPolylineGraphic(c,!1);1===c.length?b._emitCreateStartEvent("polyline"):b._emitCreateEvent("polyline")}),c.on("vertex-remove",function(a){var c=a.vertices;f=a;k&&
b._snapLastVertexToAxis(c);b._showPolylineGraphic(c,!1);b._emitCreateEvent("polyline")}),c.on("vertex-update",function(a){var c=a.vertices;f=a;k&&b._snapLastVertexToAxis(c);b._showPolylineGraphic(c,!1);b._emitCreateEvent("polyline")}),c.on("cursor-update",function(a){var c=a.vertices,h=a.native;f=a;b.view.toMap(h.x,h.y,d);k&&b._snapLastVertexToAxis(c);b._showPolylineGraphic(c,!0)}),c.on("draw-complete",function(a){b._layer.remove(b.graphic);b._set("graphic",new n(q.createPolyline([a.vertices],b.view),
b.polylineSymbol));h&&h.complete()}),c.on("undo",function(a){a=a.vertices;var c=f&&"cursor-update"===f.type;a.length?(k&&b._snapLastVertexToAxis(a),b._showPolylineGraphic(a,c)):b._clearGraphics()}),c.on("redo",function(a){a=a.vertices;var c=f&&"cursor-update"===f.type;k&&b._snapLastVertexToAxis(a);b._showPolylineGraphic(a,c)}),this.view.on("key-down",function(a){var d=c.vertices.slice(0),e=f&&"cursor-update"===f.type;"Control"!==a.key||k?"z"===a.key&&h&&h.canUndo()?(a.stopPropagation(),h.undo()):
"r"===a.key&&h&&h.canRedo()?(a.stopPropagation(),h.redo()):"Escape"===a.key&&h&&h.cancel():(k=!0,e&&b._snapLastVertexToAxis(d),b._showPolylineGraphic(d,e))}),this.view.on("key-up",function(a){var h=c.vertices.slice(0),e=f&&"cursor-update"===f.type;"Control"===a.key&&(k=!1,h.pop(),h.push([d.x,d.y]),b._showPolylineGraphic(h,e))}),this.view.on("pointer-move",function(a){b.view.hitTest(a).then(function(a){e=b._displayCrosshairCursor()})})],h=new u({type:"create",complete:function(){b._clearGraphics();
b._layer.remove(b.graphic);e&&e.reset();l.forEach(function(b){return b.remove()});b.draw.reset();h.emit("complete")},cancel:function(){b._clearGraphics();b._layer.remove(b.graphic);e&&e.reset();l.forEach(function(b){return b.remove()});b.draw.reset();h.emit("cancel")},undo:function(){c&&c.undo();b._emitUndoEvent()},redo:function(){c&&c.redo();b._emitRedoEvent()},canUndo:function(){return c&&c.canUndo()},canRedo:function(){return c&&c.canRedo()}});return h};d.prototype._createRectangleOperation=function(a){var b=
this,c=this.draw.create("rectangle",a),d=null,f=!1,e=!1,k=[c.on("vertex-add",function(a){a=a.vertices;b._showRectangleGraphic(a,e,f);1===a.length?b._emitCreateStartEvent("rectangle"):b._emitCreateEvent("rectangle")}),c.on("cursor-update",function(a){b._showRectangleGraphic(a.vertices,e,f)}),c.on("draw-complete",function(a){b._layer.remove(b.graphic);a=a.vertices.slice(0);if(1===a.length){e=f=!1;var c=b.view.toScreen(a[0][0],a[0][1],null);a=b.view.toMap(c.x-b._defaultSegmentOffset,c.y+b._defaultSegmentOffset);
c=b.view.toMap(c.x+b._defaultSegmentOffset,c.y-b._defaultSegmentOffset);a=[[a.x,a.y],[c.x,c.y]]}a=f?q.createSquare(a,b.view,e):q.createRectangle(a,b.view,e);b._set("graphic",new n(a,b.polygonSymbol));l&&l.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||f?"Alt"!==a.key||e?"Escape"===a.key&&l&&l.cancel():(e=!0,b._showRectangleGraphic(c.vertices,e,f)):(f=!0,b._showRectangleGraphic(c.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?(f=!1,b._showRectangleGraphic(c.vertices,
e,f)):"Alt"===a.key&&(e=!1,b._showRectangleGraphic(c.vertices,e,f))}),this.view.on("pointer-move",function(a){b.view.hitTest(a).then(function(a){d=b._displayCrosshairCursor()})})],l=new u({type:"create",complete:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("complete")},cancel:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("cancel")},
undo:function(){},redo:function(){},canUndo:function(){return!1},canRedo:function(){return!1}});return l};d.prototype._createMultipointOperation=function(a){var b=this,c=this.draw.create("multipoint",a),d=null,f=[c.on("vertex-add",function(a){a=a.vertices;b._showMultipointGraphic(a);1===a.length?b._emitCreateStartEvent("multipoint"):b._emitCreateEvent("multipoint")}),c.on("vertex-remove",function(a){b._showMultipointGraphic(a.vertices);b._emitCreateEvent("multipoint")}),c.on("vertex-update",function(a){b._showMultipointGraphic(a.vertices);
b._emitCreateEvent("multipoint")}),c.on("cursor-update",function(a){b._showMultipointGraphic(a.vertices)}),c.on("draw-complete",function(a){b._layer.remove(b.graphic);b._set("graphic",new n(q.createMultipoint(a.vertices,b.view),b.pointSymbol));e&&e.complete()}),this.view.on("pointer-move",function(a){b.view.hitTest(a).then(function(a){d=b._displayCrosshairCursor()})}),this.view.on("key-down",function(a){"Escape"===a.key&&e&&e.cancel()})],e=new u({type:"create",complete:function(){b._clearGraphics();
b._layer.remove(b.graphic);d&&d.reset();f.forEach(function(a){return a.remove()});b.draw.reset();e.emit("complete")},cancel:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();f.forEach(function(a){return a.remove()});b.draw.reset();e.emit("cancel")},undo:function(){c&&c.undo();b._emitUndoEvent()},redo:function(){c&&c.undo();b._emitUndoEvent()},canUndo:function(){return!1},canRedo:function(){return!1}});return e};d.prototype._createCircleOperation=function(a){var b=this,c=this.draw.create("circle",
a),d=null,f=!1,e=!1,k=[c.on("vertex-add",function(a){a=a.vertices;b._showCircleGraphic(a,e,f);1===a.length?b._emitCreateStartEvent("circle"):b._emitCreateEvent("circle")}),c.on("cursor-update",function(a){b._showCircleGraphic(a.vertices,e,f)}),c.on("draw-complete",function(a){b._layer.remove(b.graphic);a=a.vertices.slice(0);if(1===a.length){f=!1;e=!0;var d=b.view.toScreen(a[0][0],a[0][1],null),d=new t.ScreenPoint({x:d.x+b._defaultSegmentOffset,y:d.y});a.push(c.getCoordsFromScreenPoint(d))}a=f?q.createEllipse(a,
b.view,e):q.createCircle(a,b.view,e);b._set("graphic",new n(a,b.polygonSymbol));l&&l.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||f?"Alt"!==a.key||e?"Escape"===a.key&&l&&l.cancel():(e=!0,b._showCircleGraphic(c.vertices,e,f)):(f=!0,b._showCircleGraphic(c.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?(f=!1,b._showCircleGraphic(c.vertices,e,f)):"Alt"===a.key&&(e=!1,b._showCircleGraphic(c.vertices,e,f))}),this.view.on("pointer-move",function(a){b.view.hitTest(a).then(function(a){d=
b._displayCrosshairCursor()})})],l=new u({type:"create",complete:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("complete")},cancel:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("cancel")},undo:function(){},redo:function(){},canUndo:function(){return!1},canRedo:function(){return!1}});return l};d.prototype._createEllipseOperation=
function(a){var b=this,c=this.draw.create("ellipse",a),d=null,f=!1,e=!1,k=[c.on("vertex-add",function(a){var c=a.vertices;b._showEllipseGraphic(a.vertices,e,f);1===c.length?b._emitCreateStartEvent("ellipse"):b._emitCreateEvent("ellipse")}),c.on("cursor-update",function(a){b._showEllipseGraphic(a.vertices,e,f)}),c.on("draw-complete",function(a){b._layer.remove(b.graphic);a=a.vertices.slice(0);if(1===a.length){e=f=!0;var d=b.view.toScreen(a[0][0],a[0][1],null),d=new t.ScreenPoint({x:d.x+b._defaultSegmentOffset,
y:d.y});a.push(c.getCoordsFromScreenPoint(d))}a=f?q.createCircle(a,b.view,e):q.createEllipse(a,b.view,e);b._set("graphic",new n(a,b.polygonSymbol));l&&l.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||f?"Alt"!==a.key||e?"Escape"===a.key&&l&&l.cancel():(e=!0,b._showEllipseGraphic(c.vertices,e,f)):(f=!0,b._showEllipseGraphic(c.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?(f=!1,b._showEllipseGraphic(c.vertices,e,f)):"Alt"===a.key&&(e=!1,b._showEllipseGraphic(c.vertices,
e,f))}),this.view.on("pointer-move",function(a){b.view.hitTest(a).then(function(a){d=b._displayCrosshairCursor()})})],l=new u({type:"create",complete:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("complete")},cancel:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("cancel")},undo:function(){},redo:function(){},canUndo:function(){return!1},
canRedo:function(){return!1}});return l};d.prototype._createTriangleOperation=function(a){var b=this,c=this.draw.create("triangle",a),d=null,f=!1,e=!1,k=[c.on("vertex-add",function(a){var c=a.vertices;b._showTriangleGraphic(a.vertices,e,f);1===c.length?b._emitCreateStartEvent("triangle"):b._emitCreateEvent("triangle")}),c.on("cursor-update",function(a){b._showTriangleGraphic(a.vertices,e,f)}),c.on("draw-complete",function(a){b._layer.remove(b.graphic);a=a.vertices.slice(0);if(1===a.length){e=f=!0;
var d=b.view.toScreen(a[0][0],a[0][1],null),d=new t.ScreenPoint({x:d.x+b._defaultSegmentOffset,y:d.y});a.push(c.getCoordsFromScreenPoint(d))}b._set("graphic",new n(q.createTriangle(a,b.view,e,f),b.polygonSymbol));l&&l.complete()}),this.view.on("key-down",function(a){"Control"!==a.key||f?"Alt"!==a.key||e?"Escape"===a.key&&l&&l.cancel():(e=!0,b._showTriangleGraphic(c.vertices,e,f)):(f=!0,b._showTriangleGraphic(c.vertices,e,f))}),this.view.on("key-up",function(a){"Control"===a.key?(f=!1,b._showTriangleGraphic(c.vertices,
e,f)):"Alt"===a.key&&(e=!1,b._showTriangleGraphic(c.vertices,e,f))}),this.view.on("pointer-move",function(a){b.view.hitTest(a).then(function(a){d=b._displayCrosshairCursor()})})],l=new u({type:"create",complete:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("complete")},cancel:function(){b._clearGraphics();b._layer.remove(b.graphic);d&&d.reset();k.forEach(function(a){return a.remove()});b.draw.reset();l.emit("cancel")},
undo:function(){},redo:function(){},canUndo:function(){return!1},canRedo:function(){return!1}});return l};d.prototype._updatePointOperation=function(a,b){var c=this,d=[],f=[],e=null,k=new n(a.geometry,this.updatePointSymbol);this._layer.add(k);this._set("graphic",k.clone());var l=new H({graphics:[k],view:this.view,callbacks:{onGraphicMoveStart:function(a){f=[];d.push({geometry:c.graphic.geometry});c._emitMoveStartEvent(a.dx,a.dy)},onGraphicMove:function(a){c._set("graphic",a.graphic);c._emitMoveEvent(a.dx,
a.dy)},onGraphicMoveStop:function(a){c._set("graphic",a.graphic);c._emitMoveCompleteEvent(a.dx,a.dy)},onGraphicPointerOver:function(a){e=c._displayPointerCursor()},onGraphicPointerOut:function(a){e&&e.reset();e=null}}}),g=[this.view.on("click",function(b){c.view.hitTest(b).then(function(b){b=b.results;b.length&&b[0].graphic&&b[0].graphic===k||(k.geometry!==a.geometry?m&&m.complete():m&&m.cancel())})}),this.view.on("key-down",function(b){"z"===b.key?m&&m.undo():"r"===b.key?m&&m.redo():"Escape"===b.key&&
(c.graphic.geometry!==a.geometry?m&&m.complete():m&&m.cancel())})],m=new u({type:"update",complete:function(){l.destroy();c._layer.remove(k);g.forEach(function(a){return a.remove()});e&&e.reset();d=[];f=[];c.draw.reset();c.graphic.geometry=k.geometry;m.emit("complete")},cancel:function(){l.destroy();c._layer.remove(k);g.forEach(function(a){return a.remove()});e&&e.reset();d=[];f=[];c.draw.reset();c.graphic.geometry=k.geometry;m.emit("cancel")},undo:function(){if(m.canUndo()){var a=d.pop();f.push({geometry:c.graphic.geometry});
c.graphic.geometry=a.geometry;c._emitUndoEvent()}},redo:function(){if(m.canRedo()){var a=f.pop();d.push({geometry:c.graphic.geometry});c.graphic.geometry=a.geometry;c._emitRedoEvent()}},canUndo:function(){return 0<d.length},canRedo:function(){return 0<f.length}});return m};d.prototype._updateOperation=function(a,b){var c=this,d=[],f=[];this._set("graphic",new n(a.geometry,"polygon"===a.geometry.type?this.updatePolygonSymbol:this.updatePolylineSymbol));this._layer.add(this.graphic);var e=new C({graphic:this.graphic,
layer:this._layer,view:this.view,callbacks:{onMoveStart:function(a){f=[];d.push({geometry:c.graphic.geometry});c._emitMoveStartEvent(a.dx,a.dy)},onMove:function(a){c._set("graphic",a.graphic);c._emitMoveEvent(a.dx,a.dy)},onMoveStop:function(a){c._set("graphic",a.graphic);c._emitMoveCompleteEvent(a.dx,a.dy)},onScaleStart:function(a){f=[];d.push({geometry:c.graphic.geometry});c._emitScaleStartEvent(a.xScale,a.yScale)},onScale:function(a){c._set("graphic",a.graphic);c._emitScaleEvent(a.xScale,a.yScale)},
onScaleStop:function(a){c._set("graphic",a.graphic);c._emitScaleCompleteEvent(a.xScale,a.yScale)},onRotateStart:function(a){f=[];d.push({geometry:c.graphic.geometry});c._emitRotateStartEvent(a.angle)},onRotate:function(a){c._set("graphic",a.graphic);c._emitRotateEvent(a.angle)},onRotateStop:function(a){c._set("graphic",a.graphic);c._emitRotateCompleteEvent(a.angle)}}}),k=new D({graphic:null,layer:this._layer,view:this.view,callbacks:{onReshapeStart:function(a){f=[];d.push({geometry:c.graphic.geometry});
c._emitReshapeStartEvent()},onReshape:function(a){c._set("graphic",a.graphic);c._emitReshapeEvent()},onReshapeStop:function(a){c._set("graphic",a.graphic);c._emitReshapeCompleteEvent()},onMoveStart:function(a){f=[];d.push({geometry:c.graphic.geometry});c._emitMoveStartEvent(a.dx,a.dy)},onMove:function(a){c._set("graphic",a.graphic);c._emitMoveEvent(a.dx,a.dy)},onMoveStop:function(a){c._set("graphic",a.graphic);c._emitMoveCompleteEvent(a.dx,a.dy)},onVertexAdd:function(a){c._set("graphic",a.graphic);
f=[];d.push({geometry:a.oldGraphic.geometry});c._emitUpdateEvent()},onVertexRemove:function(a){c._set("graphic",a.graphic);f=[];d.push({geometry:a.oldGraphic.geometry});c._emitUpdateEvent()}}}),g=e,h=[this.view.on("click",function(b){c.view.hitTest(b).then(function(b){b.results.some(function(a){if(a.graphic&&-1<g.graphics.indexOf(a.graphic))return g.graphic=null,g instanceof C?g=k:g instanceof D&&(g=e),g.graphic=c.graphic,!0})||m&&(c.graphic.geometry!==a.geometry?m.complete():m.cancel())})}),this.view.on("key-down",
function(b){"z"===b.key?m&&m.undo():"r"===b.key?m&&m.redo():"Escape"===b.key&&m?c.graphic.geometry!==a.geometry?m.complete():m.cancel():"Control"===b.key&&e&&!b.repeat&&e.set("uniformScaling",!0)}),this.view.on("key-up",function(a){"Control"===a.key&&e&&e.set("uniformScaling",!1)})],m=new u({type:"update",complete:function(){e&&e.destroy();k&&k.destroy();c._layer.remove(c.graphic);c.graphic.symbol=a.symbol;h.forEach(function(a){return a.remove()});d=[];f=[];if("polygon"===a.geometry.type){var b=q.createPolygon(c.graphic.geometry.rings,
c.view);c.graphic.geometry=b}m.emit("complete")},cancel:function(){e&&e.destroy();k&&k.destroy();c._layer.remove(c.graphic);c.graphic.symbol=a.symbol;h.forEach(function(a){return a.remove()});d=[];f=[];m.emit("cancel")},undo:function(){if(m.canUndo()){var a=d.pop();f.push({geometry:c.graphic.geometry});c.graphic.geometry=a.geometry;g.refresh();c._emitUndoEvent()}},redo:function(){if(m.canRedo()){var a=f.pop();d.push({geometry:c.graphic.geometry});c.graphic.geometry=a.geometry;g.refresh();c._emitRedoEvent()}},
canUndo:function(){return 0<d.length},canRedo:function(){return 0<f.length}});return m};d.prototype._showPolygonGraphic=function(a,b){var c=this;this._layer.remove(this.graphic);this._clearGraphics();if(1===a.length){var d=a[0],d=new n(new t.Point(d[0],d[1],this.view.spatialReference),this.activePointSymbol);b||(this._vertexGraphics.push(d),this._layer.add(d));this._set("graphic",d)}else{var f;2===a.length?(d=q.createPolyline([a],this.view),f=this.polylineSymbol):(d=q.createPolygon([a],this.view),
f=this.polygonSymbol,this._targetGraphic=new n(d,this.activeFillSymbol),this._layer.add(this._targetGraphic));this._set("graphic",new n(d,f));if(b){var e=a.map(function(a){return Array.apply([],a)});b=e.pop();b=[e[e.length-1],b];this._lineGraphic=new n(q.createPolyline([e],this.view),this.polylineSymbol);this._layer.add(this._lineGraphic);this._activeLineGraphic=new n(q.createPolyline(b,this.view),this.activeLineSymbol);this._layer.add(this._activeLineGraphic);e.forEach(function(a,b){b=b===e.length-
1?c.activePointSymbol:c.pointSymbol;a=new n({geometry:new t.Point({x:a[0],y:a[1],spatialReference:c.view.spatialReference}),symbol:b});c._vertexGraphics.push(a);c._layer.add(a)})}else this._lineGraphic=new n(q.createPolyline([a],this.view),this.polylineSymbol),this._layer.add(this._lineGraphic),a.forEach(function(b,d){d=d===a.length-1?c.activePointSymbol:c.pointSymbol;b=new n({geometry:new t.Point({x:b[0],y:b[1],spatialReference:c.view.spatialReference}),symbol:d});c._vertexGraphics.push(b);c._layer.add(b)})}};
d.prototype._showPolylineGraphic=function(a,b){var c=this;this._layer.remove(this.graphic);this._clearGraphics();if(1===a.length)b=a[0],this._set("graphic",new n(new t.Point(b[0],b[1],this.view.spatialReference),this.pointSymbol));else if(this._set("graphic",new n(q.createPolyline([a],this.view),this.polylineSymbol)),b){var d=a.map(function(a){return Array.apply([],a)});b=d.pop();b=[d[d.length-1],b];this._lineGraphic=new n(q.createPolyline(d,this.view),this.polylineSymbol);this._layer.add(this._lineGraphic);
this._activeLineGraphic=new n(q.createPolyline(b,this.view),this.activeLineSymbol);this._layer.add(this._activeLineGraphic);d.forEach(function(a,b){b=b===d.length-1?c.activePointSymbol:c.pointSymbol;a=new n({geometry:new t.Point({x:a[0],y:a[1],spatialReference:c.view.spatialReference}),symbol:b});c._vertexGraphics.push(a);c._layer.add(a)})}else this._lineGraphic=new n(q.createPolyline([a],this.view),this.polylineSymbol),this._layer.add(this._lineGraphic),a.forEach(function(b,d){d=d===a.length-1?c.activePointSymbol:
c.pointSymbol;b=new n({geometry:new t.Point({x:b[0],y:b[1],spatialReference:c.view.spatialReference}),symbol:d});c._vertexGraphics.push(b);c._layer.add(b)})};d.prototype._showRectangleGraphic=function(a,b,c){this._layer.remove(this.graphic);this._clearGraphics();1===a.length?(a=a[0],this._set("graphic",new n(new t.Point(a[0],a[1],this.view.spatialReference),this.pointSymbol))):(a=c?q.createSquare(a,this.view,b):q.createRectangle(a,this.view,b),this._toggleCenterGraphic(a),this._set("graphic",new n(a,
this.polygonSymbol)),this._layer.add(this.graphic))};d.prototype._showMultipointGraphic=function(a){this._layer.remove(this.graphic);this._set("graphic",new n(q.createMultipoint(a,this.view),this.pointSymbol));this._layer.add(this.graphic)};d.prototype._showCircleGraphic=function(a,b,c){this._layer.remove(this.graphic);this._clearGraphics();1===a.length?(a=a[0],this._set("graphic",new n(new t.Point(a[0],a[1],this.view.spatialReference),this.pointSymbol))):(a=c?q.createEllipse(a,this.view,b):q.createCircle(a,
this.view,b),this._toggleCenterGraphic(a),this._set("graphic",new n(a,this.polygonSymbol)),this._layer.add(this.graphic))};d.prototype._showEllipseGraphic=function(a,b,c){this._layer.remove(this.graphic);this._clearGraphics();1===a.length?(a=a[0],this._set("graphic",new n(new t.Point(a[0],a[1],this.view.spatialReference),this.pointSymbol))):(a=c?q.createCircle(a,this.view,b):q.createEllipse(a,this.view,b),this._toggleCenterGraphic(a),this._set("graphic",new n(a,this.polygonSymbol)),this._layer.add(this.graphic))};
d.prototype._showTriangleGraphic=function(a,b,c){this._layer.remove(this.graphic);this._clearGraphics();1===a.length?(a=a[0],this._set("graphic",new n(new t.Point(a[0],a[1],this.view.spatialReference),this.pointSymbol))):(a=q.createTriangle(a,this.view,b,c),this._toggleCenterGraphic(a),this._set("graphic",new n(a,this.polygonSymbol)),this._layer.add(this.graphic))};d.prototype._toggleCenterGraphic=function(a){this._layer&&this._layer.remove(this._centerGraphic);this._centerGraphic=null;a&&a.extent&&
a.extent.center&&(this._centerGraphic=new n(a.extent.center,this._centerSymbol),this._layer&&this._layer.add(this._centerGraphic))};d.prototype._clearGraphics=function(a){a=a||this._layer;this._toggleCenterGraphic();a&&(a.remove(this._targetGraphic),a.remove(this._lineGraphic),a.remove(this._activeLineGraphic),a.removeMany(this._vertexGraphics));this._activeLineGraphic=this._lineGraphic=this._targetGraphic=null;this._vertexGraphics=[]};d.prototype._snapLastVertexToAxis=function(a){if(!(2>a.length)){var b=
a.pop(),c=a[a.length-1],b=this.view.toScreen(b[0],b[1],null),c=this.view.toScreen(c[0],c[1],null),d=Math.abs(b.x-c.x),f=Math.abs(b.y-c.y),b=this.view.toMap(d>f?b.x:c.x,d>f?c.y:b.y);a.push([b.x,b.y])}};d.prototype._displayCrosshairCursor=function(){"crosshair"!==this.view.container.style.cursor&&(this.view.container.style.cursor="crosshair");return this._getResetCursorHandle()};d.prototype._displayPointerCursor=function(){"pointer"!==this.view.container.style.cursor&&(this.view.container.style.cursor=
"pointer");return this._getResetCursorHandle()};d.prototype._getResetCursorHandle=function(){var a=this;return new I({reset:function(){"default"!==a.view.container.style.cursor&&(a.view.container.style.cursor="default")}})};d.prototype._emitCreateStartEvent=function(a){this.emit("create-start",new K(a,this.graphic.geometry))};d.prototype._emitCreateEvent=function(a){this.emit("create",new L(a,this.graphic.geometry))};d.prototype._emitCreateCompleteEvent=function(a){this.emit("create-complete",new N(a,
this.graphic.geometry.clone()))};d.prototype._emitCreateCancelEvent=function(a){this.emit("create-cancel",new M(a))};d.prototype._emitCreateInitEvent=function(a){this.emit("create-init",new J(a))};d.prototype._emitUpdateCompleteEvent=function(){this.emit("update-complete",new R(this.graphic.geometry))};d.prototype._emitUpdateEvent=function(){this.emit("update",new P(this.graphic.geometry))};d.prototype._emitUpdateInitEvent=function(){this.emit("update-init",new O(this.graphic.geometry))};d.prototype._emitUpdateCancelEvent=
function(){this.emit("update-cancel",new Q(this.graphic.geometry))};d.prototype._emitResetEvent=function(){this.emit("reset",new S)};d.prototype._emitReshapeStartEvent=function(){this.emit("reshape-start",new ca(this.graphic.geometry))};d.prototype._emitReshapeEvent=function(){this.emit("reshape",new da(this.graphic.geometry))};d.prototype._emitReshapeCompleteEvent=function(){this.emit("reshape-complete",new ea(this.graphic.geometry))};d.prototype._emitMoveStartEvent=function(a,b){this.emit("move-start",
new Z(this.graphic.geometry,a,b))};d.prototype._emitMoveEvent=function(a,b){this.emit("move",new aa(this.graphic.geometry,a,b))};d.prototype._emitMoveCompleteEvent=function(a,b){this.emit("move-complete",new ba(this.graphic.geometry,a,b))};d.prototype._emitScaleStartEvent=function(a,b){this.emit("scale-start",new W(this.graphic.geometry,a,b))};d.prototype._emitScaleEvent=function(a,b){this.emit("scale",new X(this.graphic.geometry,a,b))};d.prototype._emitScaleCompleteEvent=function(a,b){this.emit("scale-complete",
new Y(this.graphic.geometry,a,b))};d.prototype._emitRotateStartEvent=function(a){this.emit("rotate-start",new T(this.graphic.geometry,a))};d.prototype._emitRotateEvent=function(a){this.emit("rotate",new U(this.graphic.geometry,a))};d.prototype._emitRotateCompleteEvent=function(a){this.emit("rotate-complete",new V(this.graphic.geometry,a))};d.prototype._emitUndoEvent=function(){this.emit("undo",new fa(this.graphic.geometry))};d.prototype._emitRedoEvent=function(){this.emit("redo",new ga(this.graphic.geometry))};
r([p.property()],d.prototype,"_defaultGraphicsLayer",void 0);r([p.property({dependsOn:["layer","_defaultGraphicsLayer"]})],d.prototype,"_layer",null);r([p.property()],d.prototype,"_operationHandle",void 0);r([p.property()],d.prototype,"activeFillSymbol",void 0);r([p.property()],d.prototype,"activeLineSymbol",void 0);r([p.property()],d.prototype,"activePointSymbol",void 0);r([p.property({readOnly:!0})],d.prototype,"draw",void 0);r([p.property({readOnly:!0})],d.prototype,"graphic",void 0);r([p.property()],
d.prototype,"hoverVertexSymbol",void 0);r([p.property()],d.prototype,"layer",void 0);r([p.property()],d.prototype,"pointSymbol",void 0);r([p.property()],d.prototype,"polygonSymbol",void 0);r([p.property()],d.prototype,"polylineSymbol",void 0);r([p.property()],d.prototype,"selectedVertexSymbol",void 0);r([p.property({dependsOn:["view.ready","_operationHandle"],readOnly:!0})],d.prototype,"state",null);r([p.property()],d.prototype,"view",void 0);return d=r([p.subclass("esri.widgets.Sketch.SketchViewModel")],
d)}(p.declared(y,z))});