//>>built
(function(a){"object"===typeof module&&"object"===typeof module.exports?(a=a(require,exports),void 0!==a&&(module.exports=a)):"function"===typeof define&&define.amd&&define("require exports tslib ./WidgetBase ./mixins/Projector ../shim/array ./d ../shim/global ./mixins/Themed ./decorators/alwaysRender".split(" "),a)})(function(a,g){function q(e){return function(a){function d(){return null!==a&&a.apply(this,arguments)||this}f.__extends(d,a);d.prototype.render=function(){var a=this,f=Object.keys(this.properties).reduce(function(e,
b){var c=a.properties[b];0===b.indexOf("on")&&(b="__"+b);e[b]=c;return e},{});return l.dom({node:e,props:f,diffType:"dom"})};Object.defineProperty(d,"domNode",{get:function(){return e},enumerable:!0,configurable:!0});return d=f.__decorate([w.alwaysRender()],d)}(r.WidgetBase)}function m(a,g){var e=a.childType,v=a.registryFactory,k={};a.attributes.forEach(function(a){var b=a.toLowerCase();k[b]=a});return function(d){function b(){var c=null!==d&&d.apply(this,arguments)||this;c._properties={};c._children=
[];c._eventProperties={};c._initialised=!1;return c}f.__extends(b,d);b.prototype.connectedCallback=function(){var c=this;if(!this._initialised){var b={},n=a.attributes,d=a.properties,x=a.events;this._properties=f.__assign({},this._properties,this._attributesToProperties(n));f.__spread(n,d).forEach(function(a){var t=c[a],e=a.replace(/^on/,"__");void 0!==t&&(c._properties[a]=t);e!==a&&(b[e]={get:function(){return c._getProperty(a)},set:function(b){return c._setProperty(a,b)}});b[a]={get:function(){return c._getProperty(a)},
set:function(b){return c._setProperty(a,b)}}});x.forEach(function(a){var e=a.replace(/^on/,"").toLowerCase(),d=a.replace(/^on/,"__on");b[d]={get:function(){return c._getEventProperty(a)},set:function(b){return c._setEventProperty(a,b)}};c._eventProperties[a]=void 0;c._properties[a]=function(){for(var b=[],d=0;d<arguments.length;d++)b[d]=arguments[d];d=c._getEventProperty(a);"function"===typeof d&&d.apply(void 0,f.__spread(b));c.dispatchEvent(new CustomEvent(e,{bubbles:!1,detail:b}))}});Object.defineProperties(this,
b);y.from(e===p.TEXT?this.childNodes:this.children).forEach(function(a){e===p.DOJO?(a.addEventListener("dojo-ce-render",function(){return c._render()}),a.addEventListener("dojo-ce-connected",function(){return c._render()}),c._children.push(q(a))):c._children.push(l.dom({node:a,diffType:"dom"}))});this.addEventListener("dojo-ce-connected",function(a){return c._childConnected(a)});var k=this._properties,n=function(a){function b(){return null!==a&&a.apply(this,arguments)||this}f.__extends(b,a);b.prototype.render=
function(){return l.w(g,k,c.__children__())};return b}(r.WidgetBase),d=v(),m=z.registerThemeInjector(this._getTheme(),d);h.default.addEventListener("dojo-theme-set",function(){return m.set(c._getTheme())});this._projector=new (A.ProjectorMixin(n));this._projector.setProperties({registry:d});this._projector.append(this);this._initialised=!0;this.dispatchEvent(new CustomEvent("dojo-ce-connected",{bubbles:!0,detail:this}))}};b.prototype._getTheme=function(){if(h.default&&h.default.dojoce&&h.default.dojoce.theme)return h.default.dojoce.themes[h.default.dojoce.theme]};
b.prototype._childConnected=function(a){var c=this,b=a.detail;b.parentNode!==this||this._children.some(function(a){return a.domNode===b})||(b.addEventListener("dojo-ce-render",function(){return c._render()}),this._children.push(q(b)),this._render())};b.prototype._render=function(){this._projector&&(this._projector.invalidate(),this.dispatchEvent(new CustomEvent("dojo-ce-render",{bubbles:!1,detail:this})))};b.prototype.__properties__=function(){return f.__assign({},this._properties,this._eventProperties)};
b.prototype.__children__=function(){return e===p.DOJO?this._children.filter(function(a){return a.domNode.isWidget}).map(function(a){var b=a.domNode;return l.w(a,f.__assign({},b.__properties__()),f.__spread(b.__children__()))}):this._children};b.prototype.attributeChangedCallback=function(a,b,d){this._setProperty(k[a],d)};b.prototype._setEventProperty=function(a,b){this._eventProperties[a]=b};b.prototype._getEventProperty=function(a){return this._eventProperties[a]};b.prototype._setProperty=function(a,
b){"function"===typeof b&&(b[r.noBind]=!0);this._properties[a]=b;this._render()};b.prototype._getProperty=function(a){return this._properties[a]};b.prototype._attributesToProperties=function(a){var b=this;return a.reduce(function(a,c){var d=c.toLowerCase(),d=b.getAttribute(d);null!==d&&(a[c]=d);return a},{})};Object.defineProperty(b,"observedAttributes",{get:function(){return Object.keys(k)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"isWidget",{get:function(){return!0},enumerable:!0,
configurable:!0});return b}(HTMLElement)}function u(a){var e=a.prototype&&a.prototype.__customElementDescriptor;if(!e)throw Error("Cannot get descriptor for Custom Element, have you added the @customElement decorator to your Widget?");h.default.customElements.define(e.tagName,m(e,a))}Object.defineProperty(g,"__esModule",{value:!0});var f=a("tslib"),r=a("./WidgetBase"),A=a("./mixins/Projector"),y=a("../shim/array"),l=a("./d"),h=a("../shim/global"),z=a("./mixins/Themed"),w=a("./decorators/alwaysRender"),
p;(function(a){a.DOJO="DOJO";a.NODE="NODE";a.TEXT="TEXT"})(p=g.CustomElementChildType||(g.CustomElementChildType={}));g.DomToWidgetWrapper=q;g.create=m;g.register=u;g.default=u});