//>>built
(function(d){"object"===typeof module&&"object"===typeof module.exports?(d=d(require,exports),void 0!==d&&(module.exports=d)):"function"===typeof define&&define.amd&&define("require exports tslib ../shim/Map ../shim/WeakMap ../shim/Symbol ./d ./diff ./RegistryHandler ./NodeHandler ./vdom ./Registry".split(" "),d)})(function(d,h){Object.defineProperty(h,"__esModule",{value:!0});var k=d("tslib"),g=d("../shim/Map"),x=d("../shim/WeakMap"),y=d("../shim/Symbol"),z=d("./d"),A=d("./diff"),n=d("./RegistryHandler"),
B=d("./NodeHandler"),p=d("./vdom"),q=d("./Registry"),m=new g.default,C=A.auto.bind(null);h.noBind=y.default.for("dojoNoBind");d=function(){function b(){var a=this;this._initialProperties=!0;this._changedPropertyKeys=[];this._nodeHandler=new B.default;this._handles=[];this._children=[];this._decoratorCache=new g.default;this._properties={};this._boundRenderFunc=this.render.bind(this);this._boundInvalidate=this.invalidate.bind(this);p.widgetInstanceMap.set(this,{dirty:!0,onAttach:function(){a.onAttach()},
onDetach:function(){a.onDetach();a.destroy()},nodeHandler:this._nodeHandler,registry:function(){return a.registry},coreProperties:{},rendering:!1,inputProperties:{}});this._runAfterConstructors()}b.prototype.meta=function(a){void 0===this._metaMap&&(this._metaMap=new g.default);var c=this._metaMap.get(a);c||(c=new a({invalidate:this._boundInvalidate,nodeHandler:this._nodeHandler,bind:this}),this.own(c),this._metaMap.set(a,c));return c};b.prototype.onAttach=function(){};b.prototype.onDetach=function(){};
Object.defineProperty(b.prototype,"properties",{get:function(){return this._properties},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"changedPropertyKeys",{get:function(){return k.__spread(this._changedPropertyKeys)},enumerable:!0,configurable:!0});b.prototype.__setCoreProperties__=function(a){var c=a.baseRegistry,e=p.widgetInstanceMap.get(this);e.coreProperties.baseRegistry!==c&&(void 0===this._registry&&(this._registry=new n.default,this.own(this._registry),this.own(this._registry.on("invalidate",
this._boundInvalidate))),this._registry.base=c,this.invalidate());e.coreProperties=a};b.prototype.__setProperties__=function(a){var c=this,e=p.widgetInstanceMap.get(this);e.inputProperties=a;a=this._runBeforeProperties(a);var t=this.getDecorator("registeredDiffProperty"),b=[],d=Object.keys(a);if(!1===this._initialProperties||0!==t.length){for(var d=k.__spread(d,Object.keys(this._properties)),h=[],g={},m=!1,l=0;l<d.length;l++){var f=d[l];if(-1===h.indexOf(f)){h.push(f);var n=this._properties[f],q=
this._bindFunctionProperty(a[f],e.coreProperties.bind);if(-1!==t.indexOf(f))for(var m=!0,v=this.getDecorator("diffProperty:"+f),u=0;u<v.length;u++){var r=v[u](n,q);r.changed&&-1===b.indexOf(f)&&b.push(f);f in a&&(g[f]=r.value)}else r=C(n,q),r.changed&&-1===b.indexOf(f)&&b.push(f),f in a&&(g[f]=r.value)}}if(m){var w=[];this.getDecorator("diffReaction").forEach(function(a){var e=a.reaction;a=-1!==b.indexOf(a.propertyName);var t=-1!==w.indexOf(e);a&&!t&&(e.call(c,c._properties,g),w.push(e))})}this._properties=
g;this._changedPropertyKeys=b}else{this._initialProperties=!1;for(l=0;l<d.length;l++)f=d[l],"function"===typeof a[f]?a[f]=this._bindFunctionProperty(a[f],e.coreProperties.bind):b.push(f);this._changedPropertyKeys=b;this._properties=k.__assign({},a)}0<this._changedPropertyKeys.length&&this.invalidate()};Object.defineProperty(b.prototype,"children",{get:function(){return this._children},enumerable:!0,configurable:!0});b.prototype.__setChildren__=function(a){if(0<this._children.length||0<a.length)this._children=
a,this.invalidate()};b.prototype.__render__=function(){p.widgetInstanceMap.get(this).dirty=!1;var a=this._runBeforeRenders()(),a=this.runAfterRenders(a);this._nodeHandler.clear();return a};b.prototype.invalidate=function(){var a=p.widgetInstanceMap.get(this);a.invalidate&&a.invalidate()};b.prototype.render=function(){return z.v("div",{},this.children)};b.prototype.addDecorator=function(a,c){c=Array.isArray(c)?c:[c];if(this.hasOwnProperty("constructor")){var e=m.get(this.constructor);e||(e=new g.default,
m.set(this.constructor,e));var b=e.get(a);b||(b=[],e.set(a,b));b.push.apply(b,k.__spread(c))}else e=this.getDecorator(a),this._decoratorCache.set(a,k.__spread(e,c))};b.prototype._buildDecoratorList=function(a){for(var c=[],b=this.constructor;b;){var d=m.get(b);d&&(d=d.get(a))&&c.unshift.apply(c,k.__spread(d));b=Object.getPrototypeOf(b)}return c};b.prototype.getDecorator=function(a){var b=this._decoratorCache.get(a);if(void 0!==b)return b;b=this._buildDecoratorList(a);this._decoratorCache.set(a,b);
return b};b.prototype._bindFunctionProperty=function(a,b){if("function"===typeof a&&!a[h.noBind]&&!1===q.isWidgetBaseConstructor(a)){void 0===this._bindFunctionPropertyMap&&(this._bindFunctionPropertyMap=new x.default);var e=this._bindFunctionPropertyMap.get(a)||{},c=e.boundFunc,e=e.scope;if(void 0===c||e!==b)c=a.bind(b),this._bindFunctionPropertyMap.set(a,{boundFunc:c,scope:b});return c}return a};Object.defineProperty(b.prototype,"registry",{get:function(){void 0===this._registry&&(this._registry=
new n.default,this.own(this._registry),this.own(this._registry.on("invalidate",this._boundInvalidate)));return this._registry},enumerable:!0,configurable:!0});b.prototype._runBeforeProperties=function(a){var b=this,e=this.getDecorator("beforeProperties");return 0<e.length?e.reduce(function(a,c){return k.__assign({},a,c.call(b,a))},k.__assign({},a)):a};b.prototype._runBeforeRenders=function(){var a=this,b=this.getDecorator("beforeRender");return 0<b.length?b.reduce(function(b,c){c=c.call(a,b,a._properties,
a._children);return c?c:(console.warn("Render function not returned from beforeRender, using previous render"),b)},this._boundRenderFunc):this._boundRenderFunc};b.prototype.runAfterRenders=function(a){var b=this,d=this.getDecorator("afterRender");0<d.length&&(a=d.reduce(function(a,c){return c.call(b,a)},a));void 0!==this._metaMap&&this._metaMap.forEach(function(a){a.afterRender()});return a};b.prototype._runAfterConstructors=function(){var a=this,b=this.getDecorator("afterConstructor");0<b.length&&
b.forEach(function(b){return b.call(a)})};b.prototype.own=function(a){this._handles.push(a)};b.prototype.destroy=function(){for(;0<this._handles.length;){var a=this._handles.pop();a&&a.destroy()}};b._type=q.WIDGET_BASE_TYPE;return b}();h.WidgetBase=d;h.default=d});