// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/Handles ../../../../core/Logger ../../../../core/now ../../../../core/PooledArray ../../../../geometry/support/aaBoundingRect ./deconflictorDebug ../../lib/gl-matrix ../../support/mathUtils ../../support/ResourceController ../../webgl-engine/lib/screenSizePerspectiveUtils ../../webgl-engine/lib/Util ../../webgl-engine/materials/HUDMaterial ../../webgl-engine/materials/internal/MaterialUtil".split(" "),function(D,U,V,
I,J,A,q,p,v,r,E,K,L,F,M,x){function y(b){return!!b&&"selection"===b.type}var N=J.getLogger("esri.views.3d.graphics.Deconflictor"),G=r.vec4d.create(),z=r.vec4d.create(),H=r.vec4d.create(),O=r.vec4d.create(),P=p.create(),Q=p.create(),R=new Set,S=function(){function b(a,c){this.creator=a;this.disposer=c;this.list=[];this.currentIndex=0}b.prototype.alloc=function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];this.currentIndex>=this.list.length&&this.list.push(new this.creator(a));return this.list[this.currentIndex++]};
b.prototype.freeAll=function(){for(var a=this.currentIndex,c=this.disposer,e=this.list;0<=--a;)c(e[a]);this.currentIndex=0};return b}(),B=function(){function b(){this.graphics3DGraphic=null;this.posView=this.yMax=this.yMin=this.xMax=this.xMin=0;this.graphicsOwner=null;this.id=0}b.release=function(a){a.graphics3DGraphic=null;a.graphicsOwner=null};b.copyMetadata=function(a,c){c.graphics3DGraphic=a.graphics3DGraphic;c.graphicsOwner=a.graphicsOwner;c.iconDeconflictionEnabled=a.iconDeconflictionEnabled;
c.labelDeconflictionEnabled=a.labelDeconflictionEnabled;return c};return b}(),d;(function(b){b[b.Idle=0]="Idle";b[b.Collect=1]="Collect";b[b.Process=2]="Process";b[b.SortIcons=3]="SortIcons";b[b.SortLabels=4]="SortLabels";b[b.Deconflict=5]="Deconflict"})(d||(d={}));D=function(){function b(a){var c=this;this.graphicsOwners=[];this.lastRunTimestamp=0;this.nextRunTimestamp=Number.POSITIVE_INFINITY;this.syncBudget=null;this.state=d.Idle;this.collectIndex=0;this.collectGraphics=null;this.collectGraphicsIndex=
0;this.handles=new I;this.graphicInfosToProcess=new q;this.graphicInfoPool=new S(B,B.release);this.nextGraphicInfoId=0;this.visibleObjects={icons:new q,labels:new q};this.accBinsNumX=15;this.accBinsNumY=20;this.accBinsSizeY=this.accBinsSizeX=0;this.accBins=null;this.accNumTests=0;this.iconMarginFactor=-.1;this.view=a;this.handles.add([a.watch("state.camera",function(){c.setDirty({async:!0,forceMaxIntervalRun:!0})})]);this.frameWorker=a.resourceController.registerFrameWorker(function(a){return c.run(a)})}
b.prototype.destroy=function(){this.handles.destroy();this.handles=null;this.graphicInfoPool.freeAll();this.graphicInfoPool=null;this.frameWorker&&(this.frameWorker.remove(),this.frameWorker=null);this.view=null};b.prototype.addGraphicsOwner=function(a){var c=this,e=null;a.layer&&"function"===typeof a.layer.watch&&(e=a.layer.watch("featureReduction",function(e,b){y(e)?(c._setIconVisibilityFlags(a,!1),c.setDirty()):y(b)&&(c._setIconVisibilityFlags(a,void 0),c.setDirty())}));this.graphicsOwners.push({handle:e,
owner:a});this.setDirty()};b.prototype.removeGraphicsOwner=function(a){for(var c=-1,e=0;e<this.graphicsOwners.length;e++)if(this.graphicsOwners[e].owner===a){c=e;break}0<=c&&((a=this.graphicsOwners[c].handle)&&a.remove(),this.graphicsOwners.splice(c,1),this.setDirty())};Object.defineProperty(b.prototype,"isDirty",{get:function(){return this.nextRunTimestamp!==Number.POSITIVE_INFINITY},enumerable:!0,configurable:!0});b.prototype.setDirty=function(a){var c=a?a.async:!0;a=a?a.forceMaxIntervalRun:!1;
this.state!==d.Idle&&(this.state=d.Idle);var e=A();this.nextRunTimestamp=a&&1E3<e-this.lastRunTimestamp?this.lastRunTimestamp=e:e+200;c||this.syncBudget||(this.syncBudget=new K.Budget(A),this.syncBudget.enabled=!1)};b.prototype.setClean=function(){this.graphicInfoPool.freeAll();this.graphicInfosToProcess.clear();this.nextGraphicInfoId=0;this.state=d.Idle;this.lastRunTimestamp=A();this.nextRunTimestamp=Number.POSITIVE_INFINITY;this.syncBudget=null};b.prototype.setInitialIconVisibilityFlag=function(a,
c){a=!y(a?a.featureReduction:null);c.setVisibilityFlag(2,a)};b.prototype.doesIntersectExistingPoly=function(a){var c=a.graphics3DGraphic.graphic.uid;R.clear();for(var e=Math.floor(a.xMin/this.accBinsSizeX);e<=Math.floor(a.xMax/this.accBinsSizeX);e++)if(!(0>e||e>=this.accBinsNumX))for(var b=Math.floor(a.yMin/this.accBinsSizeY);b<=Math.floor(a.yMax/this.accBinsSizeY);b++)if(!(0>b||b>=this.accBinsNumY))for(var m=this.accBins[e][b],d=0;d<m.length;d++){var g=m.data[d];if(g.graphics3DGraphic.graphic.uid!==
c&&(this.accNumTests++,!(g.xMin>a.xMax||g.xMax<a.xMin||g.yMin>a.yMax||g.yMax<a.yMin)))return!0}return!1};b.prototype.initBins=function(a,c){if(null==this.accBins){this.accBins=[];for(var b=0;b<this.accBinsNumX;b++){this.accBins.push([]);for(var d=this.accBins[this.accBins.length-1],m=0;m<this.accBinsNumY;m++)d.push(new q({initialSize:10}))}}for(b=0;b<this.accBinsNumX;b++)for(m=0;m<this.accBinsNumY;m++)this.accBins[b][m].clear();this.accBinsSizeX=a/this.accBinsNumX;this.accBinsSizeY=c/this.accBinsNumY;
this.accNumTests=0};b.prototype.addToBins=function(a){for(var c=Math.floor(a.xMin/this.accBinsSizeX);c<=Math.floor(a.xMax/this.accBinsSizeX);c++)if(!(0>c||c>=this.accBinsNumX))for(var b=Math.floor(a.yMin/this.accBinsSizeY);b<=Math.floor(a.yMax/this.accBinsSizeY);b++)0>b||b>=this.accBinsNumY||this.accBins[c][b].push(a)};b.prototype.run=function(a){if(this.view.ready&&!(a.now()<this.nextRunTimestamp))switch(v.prepare(this.view),this.syncBudget&&(a=this.syncBudget),this.state){case d.Idle:this.collectIndex=
0,this.collectGraphics=null,this.visibleObjects.icons.clear(),this.visibleObjects.labels.clear(),this.graphicInfosToProcess.clear();case d.Collect:this.state=d.Collect;if(!this._collectVisibleObjects(a))break;if(0===this.graphicInfosToProcess.length){this.setClean();break}case d.Process:this.state=d.Process;if(a.done())break;for(;this.graphicInfosToProcess.length&&!a.done();)this._processVisibleObject(this.graphicInfosToProcess.pop());if(0<this.graphicInfosToProcess.length)break;case d.SortIcons:this.state=
d.SortIcons;if(a.done())break;this.visibleObjects.icons.sort(function(a,b){return a.posView-b.posView});case d.SortLabels:this.state=d.SortLabels;if(a.done())break;this.visibleObjects.labels.sort(function(a,b){return a.posView-b.posView});case d.Deconflict:this.state=d.Deconflict,a.done()||(this._deconflictVisibleObjects(this.visibleObjects.icons,!1,a),this.visibleObjects.labels.length&&this._deconflictVisibleObjects(this.visibleObjects.labels,!0,a),v.drawAccelerationStruct(this,this.visibleObjects.icons),
v.drawAccelerationStruct(this,this.visibleObjects.labels),0===this.visibleObjects.icons.length&&0===this.visibleObjects.labels.length&&this.setClean())}};b.prototype._collectVisibleObjects=function(a){for(var b=this.view.state.camera,e=b.fullWidth,b=b.fullHeight;this.collectIndex<this.graphicsOwners.length;++this.collectIndex){var d=this.graphicsOwners[this.collectIndex].owner,m=d.graphics3DGraphics;if(m){var k=d.labelsEnabled,g=y(d.layer?d.layer.featureReduction:null);if(k||g)if(this.collectGraphics||
(this.collectGraphics=d.graphics3DGraphicsKeys,this.collectGraphicsIndex=0),this.collectGraphics){if(this.collectGraphics!==d.graphics3DGraphicsKeys)return this.collectIndex=0,this.collectGraphics=null,!1;for(;this.collectGraphicsIndex<this.collectGraphics.length&&!a.done();++this.collectGraphicsIndex){var p=m[this.collectGraphics[this.collectGraphicsIndex]];if(p&&p.areVisibilityFlagsSet(void 0,2)){var n=this.graphicInfoPool.alloc();n.id=this.nextGraphicInfoId++;n.graphicsOwner=d;n.graphics3DGraphic=
p;n.iconDeconflictionEnabled=g;n.labelDeconflictionEnabled=k;this.graphicInfosToProcess.push(n)}}this.collectGraphicsIndex>=this.collectGraphics.length&&(this.collectGraphics=null)}}}if(this.collectIndex===this.graphicsOwners.length&&!this.collectGraphics){this.collectIndex=0;if(0===this.graphicInfosToProcess.length)return!0;this.initBins(e,b);return!0}this.collectGraphics&&--this.collectIndex;return!1};b.prototype._processVisibleObject=function(a){var b=this.view.state.camera;a.iconDeconflictionEnabled&&
this._collectGraphics(a,b,0);a.labelDeconflictionEnabled&&(a=a.iconDeconflictionEnabled?B.copyMetadata(a,this.graphicInfoPool.alloc()):a,a.id=this.nextGraphicInfoId++,this._collectGraphics(a,b,1))};b.prototype._collectGraphics=function(a,b,d){var c=a.graphics3DGraphic,e=a.graphicsOwner,k=1===d,g=k?this.visibleObjects.labels:this.visibleObjects.icons,r=k?c._labelGraphics:c._graphics,k=k?0:this.iconMarginFactor;if(r.length){for(var n=p.empty(P),q,h,v=0;v<r.length;v++){var l=r[v];if(l&&"object3d"===
l.type){var t=l.stageObject,w=t?t.getNumGeometryRecords():0;if(!(1>w)){var u=t.getGeometryRecord(0),f=u.materials[0];if(f instanceof M)if(1<w)N.warn("Graphic objects with more than 1 geometry record are not supported");else{w=u.geometry.data.getVertexAttr();if(!h){h=t.getCenter();u=u.origin.vec3;x.transformToWorld(h,u,G);x.transformToView(G,u,b.viewMatrix,z);f.applyVerticalOffsetTransformation(z,w[F.VertexAttrConstants.NORMAL].data,t.objectTransformation,b,C);t=w[F.VertexAttrConstants.AUXPOS1].data;
u="screen"!==f.getParams().centerOffsetUnits;x.transformToProjection(z,b.projectionMatrix,u?t:[0,0,0],H);h=x.transformToNDC(H,O);u||(h[0]+=t[0]/b.fullWidth*2,h[1]+=t[1]/b.fullHeight*2);if(-1>h[0]||-1>h[1]||-1>h[2]||1<=h[0]||1<=h[1])break;q=z[2];c.areVisibilityFlagsSet(2,void 0,d)&&(q*=.7)}l=l.getScreenSize(T);L.applyPrecomputedScaleFactorVec2(l,C.factor,l);f=p.offset(f.calculateRelativeScreenBounds(l,C.scaleAlignment,Q),E.lerp(0,b.fullWidth,.5+.5*h[0]),E.lerp(0,b.fullHeight,.5+.5*h[1]));0!==k&&(l=
k*Math.min(p.width(f),p.height(f)),f[0]-=l,f[1]-=l,f[2]+=l,f[3]+=l);p.expand(n,f)}}}}null!=q&&(a.xMin=n[0],a.yMin=n[1],a.xMax=n[2],a.yMax=n[3],a.graphics3DGraphic=c,a.posView=q,a.graphicsOwner=e,g.push(a))}};b.prototype._deconflictVisibleObjects=function(a,b,d){for(var c=b?1:0;0<a.length&&!d.done();){var e=a.pop(),k=e.graphics3DGraphic,g=!(b&&!1===k.areVisibilityFlagsSet(2))&&!this.doesIntersectExistingPoly(e);g&&this.addToBins(e);k.setVisibilityFlag(2,g,c);b&&this.view.labeler.setLabelGraphicVisibility(k,
g);v.drawPoly(e,g?"green":"red")}};b.prototype._setIconVisibilityFlags=function(a,b){var c=a.graphics3DGraphics;a=a.graphics3DGraphicsKeys;if(null!=c&&null!=a)for(var d=0;d<a.length;d++)c[a[d]].setVisibilityFlag(2,b)};return b}();var C={factor:{scale:0,factor:0,minPixelSize:0,paddingPixels:0},scaleAlignment:0,minPixelSizeAlignment:0},T=r.vec2d.create();return D});