// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../Color ../../../../geometry/support/aaBoundingBox ../../../../geometry/support/MeshComponent ../../../../geometry/support/webMercatorUtils ../../../../geometry/support/meshUtils/projection ./ElevationAligners ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolCommonCode ./Graphics3DSymbolLayer ../support/edgeUtils ../support/symbolColorUtils ../../lib/gl-matrix ../../support/debugFlags ../../support/projectionUtils ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/Texture ../../webgl-engine/lib/Util ../../webgl-engine/materials/DefaultMaterial ../../webgl-engine/materials/NativeLineMaterial".split(" "),
function(M,la,U,N,V,W,X,Y,Z,aa,q,ba,ca,da,k,O,ea,G,K,L,fa,ga,ha,ia,P){var h=ha.VertexAttrConstants;M=function(H){function d(){var a=null!==H&&H.apply(this,arguments)||this;a._edgeStageObjects=new Set;a._materials={};a._textures={};return a}U(d,H);d.prototype._prepareResources=function(){O.DRAW_MESH_GEOMETRY_NORMALS&&(this._debugVertexNormalMaterial=new P({color:[1,0,1,1]},"debugVertexNormal"),this._debugFaceNormalMaterial=new P({color:[0,1,1,1]},"debugFAceNormal"));this.resolve()};d.prototype.destroy=
function(){H.prototype.destroy.call(this);this.isFulfilled()||this.reject();for(var a in this._materials)this._context.stage.remove(G.ModelContentType.MATERIAL,this._materials[a].material.id);for(a in this._textures)this._context.stage.remove(G.ModelContentType.TEXTURE,this._textures[a].id);this._materials={};this._textures={}};d.prototype.createGraphics3DGraphic=function(a){var b=a.graphic;if("mesh"!==b.geometry.type)return this._logWarning("unsupported geometry type for fill on mesh-3d symbol: "+
b.geometry.type),null;if(!this._validateGeometry(b.geometry))return null;var c="graphic"+b.uid,e=this.getGraphicElevationContext(b);return this._createAs3DShape(b,a.renderingInfo,e,c,b.uid)};d.prototype.layerPropertyChanged=function(a,b,c){if("opacity"===a){b=this._getLayerOpacity();for(var e in this._materials){c=this._materials[e];c.material.setParameterValues({layerOpacity:b});var g=c.material.getParameterValues();this._setMaterialTransparentParameter(g,c.isComponentTransparent);c.material.setParameterValues({transparent:g.transparent})}if(0<
this._edgeStageObjects.size){var l=this._context.stage.view.getEdgeView(),D=this._getLayerOpacity();this._edgeStageObjects.forEach(function(a){l.updateAllComponentOpacities(a,[D])})}return!0}if("elevationInfo"===a){this._updateElevationContext();for(g in b)if(a=b[g],e=c(a))a=this.getGraphicElevationContext(a.graphic),e.needsElevationUpdates=q.needsElevationUpdates3D(a.mode),e.elevationContext.set(a);return!0}return!1};Object.defineProperty(d.prototype,"numberOfVertices",{get:function(){return 0},
enumerable:!0,configurable:!0});d.prototype._requiresSymbolVertexColors=function(){return this._isPropertyDriven("color")||this._isPropertyDriven("opacity")};d.prototype._colorUid=function(a){a=a.material&&a.material.color;if(!a)return"-";if(a)switch(a.type){case "value":return a.value.toHex();case "image":return a.uid}};d.prototype._materialProperties=function(a,b,c){var e=this._requiresSymbolVertexColors(),g=b.material&&b.material.color;b=this._colorUid(b);a=!!a.vertexAttributes.color;return{hasSymbolVertexColors:e,
hasVertexColors:a,color:g,uid:"vc:"+a+",vct"+c+",svc:"+e+",cmuid:"+b}};d.prototype._setInternalColorValueParameters=function(a,b){b.diffuse=N.toUnitRGB(a.value);b.opacity=a.value.a};d.prototype._getLoadableTextureResource=function(a){return a.data?a.data instanceof HTMLImageElement?a.data.complete?a.data:a.data.src:a.data:a.url};d.prototype._setInternalColorImageParameters=function(a,b,c){var e=this._getLoadableTextureResource(a);if(e){var g=this._textures[a.uid];g||(g=new ga(e,b+"_"+a.uid+"_tex",
{mipmap:!0,wrapClamp:!1,noUnpackFlip:!0}),this._textures[a.uid]=g,this._context.stage.add(G.ModelContentType.TEXTURE,g));c.textureId=g.id}};d.prototype._setInternalMaterialParameters=function(a,b,c){if(a=a.material&&a.material.color)switch(a.type){case "value":this._setInternalColorValueParameters(a,c);break;case "image":this._setInternalColorImageParameters(a,b,c)}};d.prototype._setExternalMaterialParameters=function(a){if(this._isPropertyDriven("color"))a.externalColor=Q;else{var b=this.symbol.material?
N.toUnitRGBA(this.symbol.material.color):Q;a.externalColor=b}if(b=this.symbol.material&&this.symbol.material.colorMixMode)a.colorMixMode=b};d.prototype._hasTransparentVertexColors=function(a){a=a.vertexAttributes.color;if(!a)return!1;for(var b=3;b<a.length;b+=4)if(255!==a[b])return!0;return!1};d.prototype._getOrCreateMaterial=function(a,b){var c=this._hasTransparentVertexColors(a)||!!b.get("material.color.transparent");a=this._materialProperties(a,b,c);var e=this._materials[a.uid];if(e)return e.material;
var e=this._getStageIdHint(),g={specular:R,vertexColors:a.hasVertexColors,symbolColors:a.hasSymbolVertexColors,ambient:R,diffuse:ja,opacity:1,doubleSided:!0,doubleSidedType:"winding-order",cullFace:"none",layerOpacity:this._getLayerOpacity(),slicePlaneEnabled:this._context.slicePlaneEnabled,textureInitTransparent:!0};this._setInternalMaterialParameters(b,e,g);this._setExternalMaterialParameters(g);this._setMaterialTransparentParameter(g,c);b=new ia(g,e+"_"+a.uid+"_mat");this._materials[a.uid]={material:b,
isComponentTransparent:c};this._context.stage.add(G.ModelContentType.MATERIAL,b);return b};d.prototype._setMaterialTransparentParameter=function(a,b){var c=this._isPropertyDriven("opacity");a.transparent=c||b||1>a.layerOpacity||1>a.opacity||a.externalColor&&1>a.externalColor[3]};d.prototype._addDebugNormals=function(a,b,c,e){var g,l,D,d,x=b.length,r=a.spatialReference.isWGS84?20015077/180:1,y=.1*Math.max(a.extent.width*r,a.extent.height*r,a.extent.zmax-a.extent.zmin),B=[],z=[];a=[];for(var r=[],C=
0;C<x;C++)for(var t=b[C],u=t.data.getAttribute(h.POSITION),v=t.data.getAttribute(h.NORMAL),n=t.data.getIndices(h.POSITION),t=t.data.getIndices(h.NORMAL),u=u.data,v=v.data,p=0;p<n.length;p++){for(var A=3*n[p],q=3*t[p],m=0;3>m;m++)B.push(u[A+m]);for(m=0;3>m;m++)B.push(u[A+m]+v[q+m]*y);z.push(z.length);z.push(z.length);if(0===p%3){this._calculateFaceNormal(u,n,p,w);this._getFaceVertices(u,n,p,f,E,F);k.vec3d.add(f,E);k.vec3d.add(f,F);k.vec3d.scale(f,1/3);for(m=0;3>m;m++)a.push(f[m]);for(m=0;3>m;m++)a.push(f[m]+
w[m]*y);r.push(r.length);r.push(r.length)}}x=(g={},g[h.POSITION]={data:new Float64Array(B),size:3},g);g=(l={},l[h.POSITION]=new Uint32Array(z),l);l=new L(x,g,void 0,"line");l=new K(l,"debugVertexNormal");l.singleUse=!0;b.push(l);c.push([this._debugVertexNormalMaterial]);e.push(k.mat4d.create(e[0]));x=(D={},D[h.POSITION]={data:new Float64Array(a),size:3},D);g=(d={},d[h.POSITION]=new Uint32Array(r),d);l=new L(x,g,void 0,"line");l=new K(l,"debugFaceNormal");l.singleUse=!0;b.push(l);c.push([this._debugFaceNormalMaterial]);
e.push(k.mat4d.create(e[0]))};d.prototype._createAs3DShape=function(a,b,c,e,g){var l=this;a=a.geometry;if("mesh"!==a.type)return null;var d=this._createGeometryInfo(a,b,e);if(!d)return null;b=d.geometries;var f=d.materials,k=d.transformations,d=d.objectTransformation;O.DRAW_MESH_GEOMETRY_NORMALS&&this._addDebugNormals(a,b,f,k);var h=new fa({geometries:b,materials:f,transformations:k,castShadow:!0,metadata:{layerUid:this._context.layer.uid,graphicUid:g},idHint:e});h.setObjectTransformation(d);var y=
function(a){var b=l._context.stage.view.getEdgeView();if(b){b.removeObject(a);l._edgeStageObjects.delete(a);var c={opacity:l._getLayerOpacity(),slicePlaneEnabled:l._context.slicePlaneEnabled};if(c=ca.createMaterial(b,l.symbol,c))l._edgeStageObjects.add(a),b.addObject(a,[c],{mergeGeometries:!0})}};y(h);e=function(a,b,c,e,g){a=Z.perObjectElevationAligner(a,b,c,e,g);y(h);return a};g=new aa(this,h,b,null,null,e,c);g.needsElevationUpdates=q.needsElevationUpdates3D(c.mode);c=a.extent.center.clone();c.z=
0;g.elevationContext.centerPointInElevationSR=c;g.alignedTerrainElevation=e(g,g.elevationContext,this._context.elevationProvider,this._context.renderCoordsHelper,this._context.featureExpressionInfoContext);return g};d.prototype._createComponentNormals=function(a,b,c,e){switch(c.shading||"flat"){case "source":return this._createComponentNormalsSource(a,b,c,e);case "flat":return this._createComponentNormalsFlat(a,c,e);case "smooth":return this._createComponentNormalsSmooth(a,c,e)}};d.prototype._createComponentNormalsSource=
function(a,b,c,e){if(!b)return this._createComponentNormalsFlat(a,c,e);c=!1;for(var g=0;g<e.length;g+=3){this._calculateFaceNormal(a,e,g,w);for(var l=0;3>l;l++){var d=3*e[g+l];f[0]=b[d+0];f[1]=b[d+1];f[2]=b[d+2];0>k.vec3d.dot(w,f)&&(b[d+0]=-b[d+0],b[d+1]=-b[d+1],b[d+2]=-b[d+2],c=!0)}}return{normals:b,indices:e,didFlipNormals:c}};d.prototype._createComponentNormalsFlat=function(a,b,c){b=new Float32Array(c.length);for(var e=new Uint32Array(3*c.length),g=0;g<c.length;g+=3)for(var d=this._calculateFaceNormal(a,
c,g,w),f=0;3>f;f++)b[g+f]=d[f],e[g+f]=g/3;return{normals:b,indices:e,didFlipNormals:!1}};d.prototype._createComponentNormalsSmooth=function(a,b,c){b={};for(var e=0;e<c.length;e+=3)for(var g=this._calculateFaceNormal(a,c,e,w),d=0;3>d;d++){var f=c[e+d],h=b[f];h||(h={normal:k.vec3d.create(),count:0},b[f]=h);k.vec3d.add(h.normal,g);h.count++}a=new Float32Array(3*c.length);g=new Uint32Array(3*c.length);for(e=0;e<c.length;e++){f=c[e];h=b[f];1!==h.count&&(k.vec3d.normalize(k.vec3d.scale(h.normal,1/h.count)),
h.count=1);for(d=0;3>d;d++)a[3*e+d]=h.normal[d];g[e]=e}return{normals:a,indices:g,didFlipNormals:!1}};d.prototype._getFaceVertices=function(a,b,c,e,g,d){var f=3*b[c+0],l=3*b[c+1];b=3*b[c+2];e[0]=a[f+0];e[1]=a[f+1];e[2]=a[f+2];g[0]=a[l+0];g[1]=a[l+1];g[2]=a[l+2];d[0]=a[b+0];d[1]=a[b+1];d[2]=a[b+2]};d.prototype._calculateFaceNormal=function(a,b,c,e){this._getFaceVertices(a,b,c,f,E,F);k.vec3d.subtract(E,f);k.vec3d.subtract(F,f);k.vec3d.cross(E,F,f);k.vec3d.normalize(f,e);return e};d.prototype._getOrCreateComponents=
function(a){return a.components?a.components:ka};d.prototype._createPositionBuffer=function(a){var b=a.vertexAttributes.position,c=new Float64Array(b.length);q.reproject(a.vertexAttributes.position,0,a.spatialReference,c,0,this._context.renderSpatialReference,b.length/3);return c};d.prototype._createNormalBuffer=function(a,b){var c=a.vertexAttributes.normal;if(!c)return null;if("local"===this._context.layerView.view.viewingMode)return c;var e=a.vertexAttributes.position,d=new Float32Array(c.length);
return Y.projectNormalToECEF(c,e,b,a.spatialReference,d)};d.prototype._createColorBuffer=function(a){return a.vertexAttributes.color};d.prototype._createSymbolColorBuffer=function(a){if(this._requiresSymbolVertexColors()){a=this._getVertexOpacityAndColor(a);var b=this.symbol.material&&this.symbol.material.colorMixMode||null,c=new Uint8Array(4);da.encodeSymbolColor(a,b,c);return c}return null};d.prototype._createColorIndices=function(a,b){a=new Uint32Array(b.length);for(b=0;b<a.length;b++)a[b]=0;return a};
d.prototype._createBuffers=function(a,b){var c=a.vertexAttributes&&a.vertexAttributes.position;if(!c)return this._logWarning("Mesh geometry must contain position vertex attributes"),null;var e=a.vertexAttributes.normal,d=a.vertexAttributes.uv;if(e&&e.length!==c.length)return this._logWarning("Mesh normal vertex buffer must contain the same number of elements as the position buffer"),null;if(d&&d.length/2!==c.length/3)return this._logWarning("Mesh uv vertex buffer must contain the same number of elements as the position buffer"),
null;c=this._createPositionBuffer(a);e=this._createColorBuffer(a);b=this._createSymbolColorBuffer(b);var f=this._createNormalBuffer(a,c);a=this._transformCenterLocal(a,c,f);return{positionBuffer:c,normalBuffer:f,uvBuffer:d,colorBuffer:e,symbolColorBuffer:b,objectTransformation:a}};d.prototype._transformCenterLocal=function(a,b,c){var e=a.extent.center,d=this._context.renderSpatialReference;I[0]=e.x;I[1]=e.y;I[2]=0;e=k.mat4d.create();ea.computeLinearTransformation(a.spatialReference,I,e,d);k.mat4d.inverse(e,
S);for(a=0;a<b.length;a+=3)f[0]=b[a+0],f[1]=b[a+1],f[2]=b[a+2],k.mat4d.multiplyVec3(S,f),b[a+0]=f[0],b[a+1]=f[1],b[a+2]=f[2];if(c)for(k.mat4d.toMat3(e,J),k.mat3d.transpose(J,J),a=0;a<c.length;a+=3)f[0]=c[a+0],f[1]=c[a+1],f[2]=c[a+2],k.mat3d.multiplyVec3(J,f),c[a+0]=f[0],c[a+1]=f[1],c[a+2]=f[2];return e};d.prototype._validateFaces=function(a,b){a=a.vertexAttributes.position.length/3;if(b=b.faces){for(var c=-1,e=0;e<b.length;e++){var d=b[e];d>c&&(c=d)}if(a<=c)return this._logWarning("Vertex index "+
c+" is out of bounds of the mesh position buffer"),!1}else if(0!==a%3)return this._logWarning("Mesh position buffer length must be a multiple of 9 if no component faces are defined (3 values per vertex * 3 vertices per triangle)"),!1;return!0};d.prototype._getOrCreateFaces=function(a,b){if(b.faces)return b.faces;a=new Uint32Array(a.vertexAttributes.position.length/3);for(b=0;b<a.length;b++)a[b]=b;return a};d.prototype._isOutsideClippingArea=function(a){if(!this._context.clippingExtent)return!1;var b=
a.vertexAttributes&&a.vertexAttributes.position;if(!b)return!1;var c=this._context.elevationProvider.spatialReference,e=b.length/3;a.spatialReference.equals(c)||(b=new Float64Array(b.length),q.reproject(a.vertexAttributes.position,0,a.spatialReference,b,0,c,e));q.computeBoundingBox(b,0,e,T);return q.boundingBoxClipped(T,this._context.clippingExtent)};d.prototype._createGeometryInfo=function(a,b,c){var e,d;if(!X.canProject(a,this._context.layerView.view.spatialReference))return this._logWarning("Geometry spatial reference is not compatible with the view"),
null;if(this._isOutsideClippingArea(a))return null;var f=this._createBuffers(a,b);if(!f)return null;b=f.positionBuffer;for(var q=f.uvBuffer,w=f.colorBuffer,x=f.symbolColorBuffer,r=f.normalBuffer,f=f.objectTransformation,y=[],B=[],z=[],C=!1,t=0,u=this._getOrCreateComponents(a);t<u.length;t++){var v=u[t];if(!this._validateFaces(a,v))return null;var n=this._getOrCreateFaces(a,v);if(0!==n.length){var p=this._createComponentNormals(b,r,v,n);p.didFlipNormals&&(C=!0);var A=(e={},e[h.POSITION]={size:3,data:b},
e[h.NORMAL]={size:3,data:p.normals},e),p=(d={},d[h.POSITION]=n,d[h.NORMAL]=p.indices,d);w&&(A[h.COLOR]={size:4,data:w},p[h.COLOR]=n);x&&(A[h.SYMBOLCOLOR]={size:4,data:x},p[h.SYMBOLCOLOR]=this._createColorIndices(v,n));a.vertexAttributes.uv&&(A[h.UV0]={size:2,data:q},p[h.UV0]=n);n=new L(A,p);n=new K(n,c+"_mesh");n.singleUse=!0;y.push(n);B.push(k.mat4d.identity());z.push([this._getOrCreateMaterial(a,v)])}}C&&this._logWarning("Normals have been automatically flipped to be consistent with the counter clock wise face winding order. It is better to generate mesh geometries that have consistent normals.");
return{geometries:y,transformations:B,materials:z,objectTransformation:f}};return d}(ba);var ja=[1,1,1],Q=[1,1,1,1],R=[0,0,0],I=k.vec3d.create(),f=k.vec3d.create(),E=k.vec3d.create(),F=k.vec3d.create(),w=k.vec3d.create(),S=k.mat4d.create(),J=k.mat3d.create(),T=V.create(),ka=[new W];return M});