// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper dojo/errors/CancelError ../../../../Color ../../../../core/asyncUtils ../../../../core/lang ../../../../core/screenUtils ../../../../geometry/support/aaBoundingBox ../../../../symbols/ObjectSymbol3DLayer ./ElevationAligners ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolCommonCode ./Graphics3DSymbolLayer ./graphicUtils ./objectResourceUtils ./primitiveObjectSymbolUtils ../support/FastSymbolUpdates ../../lib/gl-matrix ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/Util ../../webgl-engine/materials/DefaultMaterial".split(" "),
function(P,Q,F,G,y,H,z,A,m,I,J,B,r,K,k,C,w,t,x,h,L,M,N){var D=[h.ModelContentType.MATERIAL,h.ModelContentType.TEXTURE,h.ModelContentType.GEOMETRY],n=[1,1,1],u=[1,1,1,1],E=[0,0,0];return function(p){function d(){return null!==p&&p.apply(this,arguments)||this}F(d,p);d.prototype._prepareResources=function(){var a=this.symbol,c=this._getStageIdHint();if(!this._isPropertyDriven("size")){var b=k.validateSymbolLayerSize(this.symbol);if(b){this._logWarning(b);this.reject();return}}a.resource&&a.resource.href?
this._prepareModelResources(a.resource.href,c):this._preparePrimitiveResources(a.resource?a.resource.primitive:"sphere",c)};d.prototype._preparePrimitiveResources=function(a,c){if(w.isValidPrimitive(a)){var b=this.symbol;this._geometry=new L(w.primitiveGeometryData(a),c);this._context.stage.add(h.ModelContentType.GEOMETRY,this._geometry);this._resourceBoundingBox=w.primitiveBoundingBox(a);this._resourceSize=m.size(this._resourceBoundingBox);this._symbolSize=k.computeSizeWithResourceSize(this._resourceSize,
b);a=this._getMaterialOpacity();a={specular:[0,0,0],opacity:a,transparent:1>a||this._isPropertyDriven("opacity"),instanced:["transformation"],ambient:n,diffuse:n};var e=this.symbolContainer;if("point-3d"===e.type&&e.verticalOffset){var e=e.verticalOffset,l=e.minWorldLength,d=e.maxWorldLength;a.verticalOffset={screenLength:A.pt2px(e.screenLength),minWorldLength:l||0,maxWorldLength:null!=d?d:Infinity};a.castShadows=!1}this._context.screenSizePerspectiveEnabled&&(a.screenSizePerspective=this._context.sharedResources.screenSizePerspectiveSettings);
this._isPropertyDriven("color")?a.externalColor=u:(b=b.material?y.toUnitRGBA(b.material.color):u,a.externalColor=b);this._fastUpdates=t.initFastSymbolUpdatesState(this._context.renderer,this._fastVisualVariableConvertOptions());this._fastUpdates.enabled?(z.mixin(a,this._fastUpdates.materialParameters),a.instanced.push("featureAttribute")):this._hasPerInstanceColor()&&a.instanced.push("color");a.slicePlaneEnabled=this._context.slicePlaneEnabled;this._material=new N(a,c+"_objectmat");this._context.stage.add(h.ModelContentType.MATERIAL,
this._material);this.resolve()}else this._logWarning("Unknown object symbol primitive: "+a),this.reject()};d.prototype._prepareModelResources=function(a,c){var b=this,e=["transformation"];c={materialParamsMixin:{instanced:e},idHint:c,streamDataSupplier:this._context.streamDataSupplier};this._fastUpdates=t.initFastSymbolUpdatesState(this._context.renderer,this._fastVisualVariableConvertOptions());this._fastUpdates.enabled?(z.mixin(c.materialParamsMixin,this._fastUpdates.materialParameters),e.push("featureAttribute")):
this._hasPerInstanceColor()&&e.push("color");e=this.symbolContainer;if("point-3d"===e.type&&e.verticalOffset){var e=e.verticalOffset,l=e.minWorldLength,d=e.maxWorldLength;c.materialParamsMixin.verticalOffset={screenLength:A.pt2px(e.screenLength),minWorldLength:l||0,maxWorldLength:null!=d?d:Infinity};c.materialParamsMixin.castShadows=!1}this._symbolLoaderPromise=H.safeCast(C.fetch(a,c));this._symbolLoaderPromise.then(function(a){b._symbolLoaderPromise=null;if(!b.isRejected()){var c=b._context,e=a.stageResources,
d=c.stage,l=b._getExternalColorParameters(b.symbol.material),f=b._getMaterialOpacity(),O=b._isPropertyDriven("opacity"),q=e[h.ModelContentType.MATERIAL];a.originalMaterialOpacities=Array(q.length);q.forEach(function(b,e){var d=b.getParameterValues();b.setParameterValues(l);a.originalMaterialOpacities[e]=d.opacity;e=d.opacity*f;b.setParameterValues({opacity:e,transparent:1>e||O||d.transparent});c.screenSizePerspectiveEnabled&&b.setParameterValues({screenSizePerspective:c.sharedResources.screenSizePerspectiveSettings})});
D.forEach(function(a){for(var b=e[a],c=0;b&&c<b.length;c++)d.add(a,b[c])});b._resourceBoundingBox=C.computeBoundingBox(a);b._resourceSize=m.size(b._resourceBoundingBox);b._pivotOffset=a.pivotOffset;b._symbolSize=k.computeSizeWithResourceSize(b._resourceSize,b.symbol);b._i3sModel=a;t.updateFastSymbolUpdatesState(b._fastUpdates,b._context.renderer,b._fastVisualVariableConvertOptions())&&q.forEach(function(a){return a.setParameterValues(b._fastUpdates.materialParameters)});b.resolve()}},function(a){b._symbolLoaderPromise=
null;if(!b.isFulfilled()){if(!(a instanceof G)){var c="ObjectSymbol3DLayer failed to load";a&&a.message&&(c+=" ("+a.message+")");b._logWarning(c)}b.reject()}})};d.prototype._forEachMaterial=function(a){this._i3sModel?this._i3sModel.stageResources[h.ModelContentType.MATERIAL].forEach(a):a(this._material)};d.prototype._getExternalColorParameters=function(a){var c={};this._isPropertyDriven("color")?c.externalColor=u:a&&a.color?c.externalColor=y.toUnitRGBA(a.color):(c.externalColor=u,c.colorMixMode="ignore");
return c};d.prototype.destroy=function(){p.prototype.destroy.call(this);this.isFulfilled()||this.reject();this._symbolLoaderPromise&&this._symbolLoaderPromise.cancel();var a=this._context.stage;if(this._i3sModel){var c=this._i3sModel.stageResources;D.forEach(function(b){for(var e=c[b],d=0;e&&d<e.length;d++)a.remove(b,e[d].id)})}else this._material&&a.remove(h.ModelContentType.MATERIAL,this._material.id),this._geometry&&a.remove(h.ModelContentType.GEOMETRY,this._geometry.id)};d.prototype.createGraphics3DGraphic=
function(a){var c=a.graphic;if(!this._validateGeometry(c.geometry))return null;var b=r.placePointOnGeometry(c.geometry);if(!b)return this._logWarning("unsupported geometry type for icon symbol: "+c.geometry.type),null;var e="graphic"+c.uid,d=this.getGraphicElevationContext(c);return this._createAs3DShape(c,b,a.renderingInfo,d,e,c.uid)};d.prototype.layerPropertyChanged=function(a,c,b){var e=this;if("opacity"===a){var d=this._isPropertyDriven("opacity");if(this._i3sModel){var f=this._getMaterialOpacity();
this._i3sModel.stageResources[h.ModelContentType.MATERIAL].forEach(function(a,b){b=e._i3sModel.originalMaterialOpacities[b]*f;a.setParameterValues({opacity:b,transparent:1>b||d})})}else c=this._getMaterialOpacity(),this._material.setParameterValues({opacity:c,transparent:1>c||d});return!0}if("elevationInfo"===a){this._updateElevationContext();for(var k in c){var g=c[k];if(a=b(g))g=this.getGraphicElevationContext(g.graphic),a.needsElevationUpdates=r.needsElevationUpdates3D(g.mode),a.elevationContext.set(g)}return!0}return!1};
d.prototype.applyRendererDiff=function(a,c,b,e){var d=this,f;for(f in a.diff)switch(f){case "visualVariables":if(t.updateFastSymbolUpdatesState(this._fastUpdates,c,this._fastVisualVariableConvertOptions()))this._forEachMaterial(function(a){return a.setParameterValues(d._fastUpdates.materialParameters)});else return!1;break;default:return!1}return!0};Object.defineProperty(d.prototype,"numberOfVertices",{get:function(){return this._i3sModel?this._i3sModel.numberOfVertices:this._geometry.data.getIndices(M.VertexAttrConstants.POSITION).length},
enumerable:!0,configurable:!0});d.prototype._createAs3DShape=function(a,c,b,e,d,f){var m=this,g=null,l=null,n=this.getFastUpdateAttrValues(a);n&&(g={featureAttribute:n},l=function(a){return t.evaluateModelTransform(m._fastUpdates.materialParameters,n,a)});!this._fastUpdates.enabled&&this._hasPerInstanceColor()&&(g=g||{},g.color=k.mixinColorAndOpacity(b.color,b.opacity));a=this._context.layer.uid;var v=x.mat4d.identity();this._applyObjectRotation(b,v);this._applyObjectRotation(this.symbol,v);this._applyObjectScale(b,
v);this._applyAnchor(v);if(this._i3sModel){b=this._i3sModel.stageResources[h.ModelContentType.GEOMETRY];for(var u=this._i3sModel.materialsByComponent,p=Array(b.length),q=0;q<p.length;q++)p[q]=v;d=r.createStageObjectForPoint.call(this,c,b,u,p,g,e,d,a,f,null,l)}else d=r.createStageObjectForPoint.call(this,c,[this._geometry],[[this._material]],[v],g,e,d,a,f,null,l);if(null===d)return null;if(this._fastUpdates.enabled){var w=t.getMaterialParams(this._fastUpdates.visualVariables,this._fastVisualVariableConvertOptions());
this._forEachMaterial(function(a){return a.setParameterValues(w)})}d.object.setCastShadow(!0);f=new B(this,d.object,null,null,null,J.perObjectElevationAligner,e,B.VisibilityModes.REMOVE_OBJECT);f.alignedTerrainElevation=d.terrainElevation;f.needsElevationUpdates=r.needsElevationUpdates3D(e.mode);r.extendPointGraphicElevationContext(f,c,this._context.elevationProvider);return f};d.prototype._applyObjectScale=function(a,c){this._fastUpdates.enabled&&this._fastUpdates.customTransformation||(a=this._isPropertyDriven("size")&&
a.size?a.size:this._symbolSize,a=k.computeObjectScale(a,this._symbolSize,this._resourceSize,this._context.renderCoordsHelper.unitInMeters),1===a[0]&&1===a[1]&&1===a[2]||x.mat4d.scale(c,a))};d.prototype._applyObjectRotation=function(a,c){if(!(this._fastUpdates.enabled&&this._fastUpdates.customTransformation&&a instanceof I))return k.computeObjectRotation(a.heading,a.tilt,a.roll,c)};d.prototype._computeAnchor=function(){switch(this.symbol.anchor){case "center":return x.vec3d.scale(m.center(this._resourceBoundingBox),
-1);case "top":var a=m.center(this._resourceBoundingBox);return[-a[0],-a[1],-this._resourceBoundingBox[5]];case "bottom":return a=m.center(this._resourceBoundingBox),[-a[0],-a[1],-this._resourceBoundingBox[2]];default:return this._pivotOffset?x.vec3d.scale(this._pivotOffset,-1,Array(3)):E}};d.prototype._applyAnchor=function(a){if(!this._fastUpdates.enabled||!this._fastUpdates.customTransformation){var c=this._computeAnchor();c&&x.mat4d.translate(a,c)}};d.prototype._hasPerInstanceColor=function(){return this._isPropertyDriven("color")||
this._isPropertyDriven("opacity")};d.prototype._fastVisualVariableConvertOptions=function(){var a=this._resourceBoundingBox?m.size(this._resourceBoundingBox):n,c=this._resourceBoundingBox?this._computeAnchor():E,b=this._context.renderCoordsHelper.unitInMeters,d=k.computeObjectScale(this._symbolSize,this._symbolSize,this._resourceSize,b);return{modelSize:a,symbolSize:this._symbolSize||n,unitInMeters:b,transformation:{anchor:c,scale:d,rotation:[this.symbol.tilt||0,this.symbol.roll||0,this.symbol.heading||
0]}}};return d}(K)});