// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../geometry/Point ./Graphics3DObject3DGraphicLayer ./Graphics3DSymbolCommonCode ./Graphics3DSymbolLayer ./graphicUtils ../../lib/gl-matrix ../../support/projectionUtils ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/Util ../../webgl-engine/materials/DefaultMaterial".split(" "),function(z,U,H,I,J,n,K,L,u,M,C,N,D,O,E,P){function Q(k,
d,b,a){k=k.stageObject;for(var e=k.getGeometryRecords(),F=e.length,p="absolute-height"!==d.mode,l=0,f=0;f<F;f++){var u=e[f].geometry,r=[e[f].transformation[12],e[f].transformation[13],e[f].transformation[14]],h=u.data.getVertexAttr(),t=h[R.POSITION].data,S=h.zOffset.data,h=h.mapPos.data,x=h.length/3;T(t.length/3===x*B+2,"unexpected tube geometry");var m=0,y=0;A.spatialReference=b.spatialReference;for(var w=0,c=0;c<x;c++){A.x=h[3*c];A.y=h[3*c+1];A.z=h[3*c+2];var g=n.computeElevation(b,A,d,a,p?G:null);
p&&(w+=G.terrainElevation);var v=B;0!==c&&c!==x-1||v++;for(var z=0;z<v;z++)q[0]=t[m]+r[0],q[1]=t[m+1]+r[1],q[2]=t[m+2]+r[2],a.setAltitude(g+S[y],q),t[m]=q[0]-r[0],t[m+1]=q[1]-r[1],t[m+2]=q[2]-r[2],m+=3,y+=1;u.invalidateBoundingInfo()}k.geometryVertexAttrsUpdated(f);l+=w/x}return l/F}var T=E.assert;z=function(k){function d(){return null!==k&&k.apply(this,arguments)||this}H(d,k);d.prototype._prepareResources=function(){if(!this._isPropertyDriven("size")){var b=L.validateSymbolLayerSize(this._getSymbolSize());
if(b){this._logWarning(b);this.reject();return}}var b=this._getStageIdHint(),a=this._getMaterialOpacityAndColor(),e=u.vec3d.create(a),a=a[3],e={diffuse:e,ambient:e,opacity:a,transparent:1>a||this._isPropertyDriven("opacity"),vertexColors:this._isPropertyDriven("color")||this._isPropertyDriven("opacity"),slicePlaneEnabled:this._context.slicePlaneEnabled};this._material=new P(e,b+"_3dlinemat");this._context.stage.add(C.ModelContentType.MATERIAL,this._material);this.resolve()};d.prototype.destroy=function(){k.prototype.destroy.call(this);
this.isFulfilled()||this.reject();this._material&&(this._context.stage.remove(C.ModelContentType.MATERIAL,this._material.id),this._material=null)};d.prototype.createGraphics3DGraphic=function(b){var a=b.graphic;if("polyline"!==a.geometry.type)return this._logWarning("unsupported geometry type for path symbol: "+a.geometry.type),null;if(!this._validateGeometry(a.geometry))return null;var e="graphic"+a.uid,d=this.getGraphicElevationContext(a);return this._createAs3DShape(a,b.renderingInfo,d,e,a.uid)};
d.prototype.layerPropertyChanged=function(b,a,e){if("opacity"===b)return a=this._getMaterialOpacity(),e=1>a||this._isPropertyDriven("opacity"),this._material.setParameterValues({opacity:a,transparent:e}),!0;if("elevationInfo"===b){this._updateElevationContext();for(var d in a){var p=a[d];if(b=e(p))p=this.getGraphicElevationContext(p.graphic),b.needsElevationUpdates=n.needsElevationUpdates3D(p.mode),b.elevationContext.set(p)}return!0}return!1};Object.defineProperty(d.prototype,"numberOfVertices",{get:function(){return 0},
enumerable:!0,configurable:!0});d.prototype._getPathSize=function(b){b=b.size&&this._isPropertyDriven("size")?n.getSingleSizeDriver(b.size):this._getSymbolSize();return b/=this._context.renderCoordsHelper.unitInMeters};d.prototype._getSymbolSize=function(){return this.symbol.size||1};d.prototype._createAs3DShape=function(b,a,e,d,p){var l=b.geometry,f=l.paths;b=[];var k=[],r=[],h=u.vec3d.create(),t=this._context.renderSpatialReference===M.SphericalECEFSpatialReference,q=Array(6),x=this._getPathSize(a),
l=n.getGeometryVertexData3D(f,l.hasZ,l.spatialReference,this._context.renderSpatialReference,this._context.elevationProvider,this._context.renderCoordsHelper,e);this._logGeometryCreationWarnings(l,f,"paths","PathSymbol3DLayer");if(0<f.length){for(var f=l.geometryData.outlines,m=l.eleVertexData,y=l.vertexData,w=0;w<f.length;++w){var c=f[w];if(!(1>=c.count)){var g=c.index,v=c.count;if(this._context.clippingExtent&&(n.computeBoundingBox(m,g,v,q),n.boundingBoxClipped(q,this._context.clippingExtent)))continue;
n.chooseOrigin(y,g,v,h);n.subtractCoordinates(y,g,v,h);c=new Float64Array(m.buffer,3*g*m.BYTES_PER_ELEMENT,3*v);g=n.flatArrayToArrayOfArrays(y,g,v);g=D.createTubeGeometry(g,.5*x,B,t,h);g.getVertexAttr().mapPos={size:3,data:c,offsetIdx:0,strideIdx:3};this._material.getParams().vertexColors&&(c=this._getVertexOpacityAndColor(a),g=D.addVertexColors(g,c));c=new N(g,d+"path"+w);c.singleUse=!0;b.push(c);k.push([this._material]);c=u.mat4d.identity();u.mat4d.translate(c,h,c);r.push(c)}}if(0<b.length)return a=
new O({geometries:b,materials:k,transformations:r,castShadow:!0,metadata:{layerUid:this._context.layer.uid,graphicUid:p},idHint:d}),a=new J(this,a,b,null,null,Q,e),a.alignedTerrainElevation=l.terrainElevation,a.needsElevationUpdates=n.needsElevationUpdates3D(e.mode),a}return null};return d}(K);var R=E.VertexAttrConstants,q=u.vec3d.create(),A=new I,G={verticalDistanceToGround:0,terrainElevation:0},B=10;return z});