// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper dojo/promise/all ../../../../Color ../../../../core/Accessor ../../../../core/Handles ../../../../core/promiseUtils ../../../../core/screenUtils ../../../../core/accessorSupport/decorators ../../../../layers/support/LabelClass ../../../../symbols/callouts/calloutUtils ./Graphics3DCalloutSymbolLayerFactory ./Graphics3DWebStyleSymbol ./labelPlacement ../../support/debugFlags ../../webgl-engine/Stage ../../webgl-engine/lib/Layer ../../webgl-engine/lib/MaterialCollection ../../webgl-engine/lib/TextTexture ../../webgl-engine/lib/TextTextureAtlas".split(" "),
function(m,u,B,q,C,v,D,E,F,w,p,x,G,H,I,J,K,y,L,z,M,N){Object.defineProperty(u,"__esModule",{value:!0});m=function(m){function b(a){a=m.call(this)||this;a.labelStageLayer=null;a.labels={};a.labelsToAdd={};a.labelsToRemove={};a.labelingContexts=[];a.idHint="__labeler";a.dirty=!1;return a}B(b,m);g=b;b.prototype.setup=function(){var a=this;this.handles||(this.handles=new E,this.handles.add([this.view.watch("state.camera",function(){return a.setDirty()})]));this.labelStageLayer||(this.labelStageLayer=
new L(this.idHint,{isPickable:!1},this.idHint+"_labels"),this.view._stage.add(y.ModelContentType.LAYER,this.labelStageLayer),this.view._stage.addToViewContent([this.labelStageLayer.id]),this.textTextureAtlas=new N(this.idHint+"_atlas",this.view),this.hudMaterialCollection=new z(this.view._stage),this.calloutMaterialCollection=new z(this.view._stage));this.handles.add(this.view.resourceController.registerIdleFrameWorker({needsUpdate:function(){return a.needsIdleUpdate()},idleFrame:function(c){return a.idleUpdate(c)}}))};
b.prototype.dispose=function(){this.handles&&(this.handles.destroy(),this.handles=null);this.labelStageLayer&&(this.view._stage.removeFromViewContent([this.labelStageLayer.id]),this.view._stage.remove(y.ModelContentType.LAYER,this.labelStageLayer.id),this.labelStageLayer=null,this.textTextureAtlas.dispose(),this.textTextureAtlas=null,this.hudMaterialCollection.dispose(),this.hudMaterialCollection=null,this.calloutMaterialCollection.dispose(),this.calloutMaterialCollection=null);this.labelingContexts=
[];this.labels={};this.labelsToAdd={};this.labelsToRemove={}};b.prototype.isActiveLabelingContext=function(a){return a.active&&this.labelsEnabled(a)};b.prototype.activateLabelingContext=function(a){for(var c in a.labels){var d=a.labels[c];this.labels[c]=d;d.graphics3DGraphic.setVisibilityFlag(0,!0,1)}a.active=!0};b.prototype.deactivateLabelingContext=function(a){for(var c in a.labels){var d=a.labels[c];d.graphics3DGraphic.setVisibilityFlag(0,!1,1);d.rendered&&(this.labelsToRemove[c]=a.labels[c]);
delete this.labels[c];delete this.labelsToAdd[c]}a.active=!1};b.prototype.addLabelTextureToAtlas=function(a){for(var c=0,d=0;d<a.graphics3DGraphic._labelGraphics.length;d++){var l=a.graphics3DGraphic._labelGraphics[d];if(l._labelClass){var f=a.textTextures[c];c++;f&&this.textTextureAtlas.addTextTexture(f,l.stageObject)}}a.rendered=!0};b.prototype.removeLabelTextureFromAtlas=function(a){for(var c=0;c<a.graphics3DGraphic._labelGraphics.length;c++)a.textTextures[c]&&this.textTextureAtlas.removeTextTexture(a.textTextures[c],
a.graphics3DGraphic._labelGraphics[c].stageObject);a.rendered=!1};b.prototype.needsIdleUpdate=function(){return this.isDirty};b.prototype.idleUpdate=function(a){if(this.view.ready){for(var c=!!a,d=!1,l=0,f=this.labelingContexts;l<f.length;l++){var e=f[l];if(this.isActiveLabelingContext(e)){if(!this.hasValidLabelClassContext(e)){if(this.hasInvalidLabelClassContext(e)){this.deactivateLabelingContext(e);continue}this.createLabelClassContext(e);if(this.hasPendingLabelClassContext(e)){d=!0;continue}if(!this.hasValidLabelClassContext(e))continue}for(var b in e.labelsToInitialize){if(c&&
a.done())return;var h=e.labelsToInitialize[b];!h.hasGraphics3DResources&&this.createGraphics3DResources(h)&&(this.labels[b]=h,c&&this.view.deconflictor.setDirty());h.hasGraphics3DResources&&!h.hasTextTextureResources&&h.visible&&this.createTextTextureResources(h);(h.visible&&h.hasTextTextureResources||!h.visible&&h.hasGraphics3DResources)&&delete e.labelsToInitialize[b]}}}for(b in this.labelsToRemove)this.removeLabelTextureFromAtlas(this.labelsToRemove[b]),delete this.labelsToRemove[b];for(b in this.labelsToAdd)this.addLabelTextureToAtlas(this.labelsToAdd[b]),
delete this.labelsToAdd[b];d||(this.dirty=!1)}};b.prototype.hasPendingLabelClassContext=function(a){return a.labelClassPromise&&!a.labelClassPromise.isResolved()};b.prototype.hasValidLabelClassContext=function(a){return a.labelClassContexts&&a.labelClassContexts.length};b.prototype.hasInvalidLabelClassContext=function(a){return null===a.labelClassContexts};b.prototype.createLabelClassContext=function(a){if(a.labelClassPromise)return a.labelClassPromise;a.labelClassPromise=a.layer.when(function(){a.scaleVisibility&&
a.scaleVisibility.updateScaleRangeActive();var c=a.graphics3DCore,d=c.layer.labelingInfo&&c.layer.labelingInfo.filter(function(a){return!!a.symbol});if(!d||0===d.length)return null;var b=Array(d.length),d=d.map(function(a,d){var l=a.symbol,e;e=c.getOrCreateGraphics3DSymbol(l);e=e instanceof I?e.graphics3DSymbol:e;var f=null;G.isCalloutSupport(l)&&l.hasVisibleCallout()&&(f=H.make(l,c.symbolCreationContext));b[d]={labelClass:a,graphics3DSymbol:e,graphics3DCalloutSymbolLayer:f,options:a.getOptions()};
return e});return C(d).then(function(){return b})}).then(function(c){c&&(a.labelClassContexts=c)}).catch(function(){a.labelClassContexts=null});return a.labelClassPromise};b.prototype.destroyLabelClassContext=function(a){a.labelClassContexts=[];a.labelClassPromise=null};b.prototype.createLabelText=function(a,c,d,b){if(!x.evaluateWhere(c.where,a.attributes))return null;c=c.getLabelExpression();return c.expression?x.buildLabelText(c.expression,a,b.fields,d):null};b.prototype.createTextSymbolGraphic=
function(a,c,d,b,f){a={text:a,centerOffset:d.centerOffset,translation:d.translation,elevationOffset:d.elevationOffset,screenOffset:d.screenOffset,anchor:d.anchor,needsOffsetAdjustment:d.needsOffsetAdjustment,centerOffsetUnits:d.centerOffsetUnits,verticalOffset:d.verticalOffset,debugDrawBorder:K.LABELS_SHOW_BORDER};g.tmpGraphicCreationContext.graphic=c;g.tmpGraphicCreationContext.renderingInfo=null;g.tmpGraphicCreationContext.layer=b;return f.createGraphics3DGraphic(g.tmpGraphicCreationContext,a,this.hudMaterialCollection,
this.textTextureAtlas)};b.prototype.createLineCalloutGraphic=function(a,c,d,b,f){g.tmpGraphicCreationContext.graphic=a;g.tmpGraphicCreationContext.renderingInfo={symbol:c,needsOffsetAdjustment:b.needsOffsetAdjustment,translation:b.translation,elevationOffset:b.elevationOffset,screenOffset:b.screenOffset,centerOffset:b.centerOffset,centerOffsetUnits:b.centerOffsetUnits,materialCollection:this.calloutMaterialCollection};g.tmpGraphicCreationContext.layer=f;return d.createGraphics3DGraphic(g.tmpGraphicCreationContext)};
b.prototype.createGraphics3DResources=function(a){var c=a.labelingContext,d=!1,b=a.graphics3DGraphic,f=b.graphic,e=c.labelClassContexts,n=c.layer,h=this.labelsEnabled(c);if(e&&0!==e.length&&b._graphics[0]){for(var t=0;t<e.length;t++){var k=e[t],g=k.labelClass,m=this.createLabelText(f,g,k.options,n);if(m){var p=null;k.graphics3DSymbol&&k.graphics3DSymbol.symbol&&"label-3d"===k.graphics3DSymbol.symbol.type&&(p=k.graphics3DSymbol.symbol);var q=k.graphics3DSymbol.childGraphics3DSymbols[0],r=J.get({graphics3DGraphic:b,
labelSymbol:p,labelClass:k.labelClass});if(q&&r.isValid){if(d=this.createTextSymbolGraphic(m,f,r,n,q)){if(d._labelClass=g,b.addLabelGraphic(d,this.labelStageLayer,this.view._stage),c.spatialIndex&&c.spatialIndex.add(b),b.setVisibilityFlag(0,h,1),b.setVisibilityFlag(1,void 0,1),b.setVisibilityFlag(2,!1,1),d=!0,k.graphics3DCalloutSymbolLayer&&r.hasLabelVerticalOffset&&(f=this.createLineCalloutGraphic(f,p,k.graphics3DCalloutSymbolLayer,r,n)))k.calloutSymbolLayerIndex=b._labelGraphics.length,b.addLabelGraphic(f,
this.labelStageLayer,this.view._stage)}else return!1;break}}}c.scaleVisibility&&d&&c.scaleVisibility.updateGraphicLabelScaleVisibility(b);return a.hasGraphics3DResources=!0}};b.prototype.destroyGraphics3DResources=function(a){a.graphics3DGraphic.clearLabelGraphics();a.hasGraphics3DResources=!1};b.prototype.createTextTextureResources=function(a){var c=a.labelingContext,d=a.graphics3DGraphic,b=c.labelClassContexts,c=c.layer,f=d.graphic;if(b&&0!==b.length&&d._graphics[0]){for(d=0;d<b.length;d++){var e=
b[d],n=this.createLabelText(f,e.labelClass,e.options,c)||f.symbol&&f.symbol.text;if(n&&!(1>n.length)){var e=e.graphics3DSymbol.childGraphics3DSymbols[0].symbol,h=e.material?v.toUnitRGBA(e.material.color):A,g=e.halo&&e.halo.color&&0<e.halo.size,k=g?v.toUnitRGBA(e.halo.color):A,g=g?w.pt2px(e.halo.size):0,m=w.pt2px(e.size)||12,n=new M(n,{size:m,color:h,font:{family:e.font&&e.font.family?e.font.family:"sans-serif",weight:e.font&&e.font.weight?e.font.weight:"normal",style:e.font&&e.font.style?e.font.style:
"normal"},halo:{size:g,color:k}},c.id+"_label_"+f.uid);a.textTextures.push(n)}}a.hasTextTextureResources=!0}};b.prototype.destroyTextTextureResources=function(a){a.textTextures=[];a.hasTextTextureResources=!1};b.prototype.addGraphic=function(a,c){var d={hasGraphics3DResources:!1,hasTextTextureResources:!1,visible:!1,rendered:!1,labelingContext:a,graphics3DGraphic:c,textTextures:[]};c=c.graphic.uid;a.labels[c]=d;this.isActiveLabelingContext(a)&&this.hasValidLabelClassContext(a)&&this.createGraphics3DResources(d)?
this.labels[c]=d:a.labelsToInitialize[c]=d;a=a.graphics3DCore.asyncUpdates;this.setDirty(a);this.view.deconflictor.setDirty({async:a})};b.prototype.removeGraphic=function(a,c){c=c.graphic.uid;var d=a.labels[c];d&&(this.labels[c]&&(this.removeLabelTextureFromAtlas(d),delete this.labels[c],delete this.labelsToAdd[c],delete this.labelsToRemove[c]),d.hasTextTextureResources&&this.destroyTextTextureResources(d),d.hasGraphics3DResources&&this.destroyGraphics3DResources(d),delete a.labels[c],delete a.labelsToInitialize[c],
a=a.graphics3DCore.asyncUpdates,this.setDirty(a),this.view.deconflictor.setDirty({async:a}))};b.prototype.labelsEnabled=function(a){return!0===a.layer.labelsVisible&&null!=a.layer.labelingInfo&&0<a.layer.labelingInfo.length};b.prototype.elevationInfoChange=function(a){for(var c=function(c){c.graphics3DSymbol.layerPropertyChanged("elevationInfo",{});if(c.graphics3DCalloutSymbolLayer){var d={},b;for(b in a.labels){var f=a.labels[b].graphics3DGraphic;d[f.graphic.uid]=f}c.graphics3DCalloutSymbolLayer.layerPropertyChanged("elevationInfo",
d,function(a){return a._labelGraphics[c.calloutSymbolLayerIndex]})}},d=0,b=a.labelClassContexts;d<b.length;d++)c(b[d])};b.prototype.visibilityInfoChange=function(a){var c=a.layer.labelsVisible;c&&!a.active&&this.activateLabelingContext(a);!c&&a.active&&this.deactivateLabelingContext(a);a=a.graphics3DCore.asyncUpdates;this.setDirty(a);this.view.deconflictor.setDirty({async:a})};b.prototype.resetLabels=function(a){for(var c in a.labels){var d=a.labels[c];this.labels[c]&&(this.removeLabelTextureFromAtlas(d),
delete this.labels[c],delete this.labelsToAdd[c],delete this.labelsToRemove[c]);d.hasTextTextureResources&&this.destroyTextTextureResources(d);d.hasGraphics3DResources&&this.destroyGraphics3DResources(d);d.visible=!1;d.rendered=!1;a.labelsToInitialize[c]=d}this.destroyLabelClassContext(a);this.labelStageLayer.invalidateSpatialQueryAccelerator();a=a.graphics3DCore.asyncUpdates;this.setDirty(a);this.view.deconflictor.setDirty({async:a})};b.prototype.findLabelingContext=function(a){for(var c=0;c<this.labelingContexts.length;c++)if(this.labelingContexts[c].graphics3DCore===
a)return this.labelingContexts[c];return null};b.prototype.addGraphicsOwner=function(a,c,d){var b=this;if(!this.findLabelingContext(a)){var f={graphics3DCore:a,layer:a.layer,scaleVisibility:c,spatialIndex:d,active:a.layer.labelsVisible,labelClassPromise:null,labelClassContexts:[],labels:{},labelsToInitialize:{}};this.labelingContexts.push(f);this.setDirty();return{addGraphic:function(a){return b.addGraphic(f,a)},removeGraphic:function(a){return b.removeGraphic(f,a)},layerLabelsEnabled:function(){return b.labelsEnabled(f)},
labelingInfoChange:function(a){if(a){for(var c=0;c<a.length;c++){var d=f.labels[a[c]];d&&(b.removeGraphic(f,d.graphics3DGraphic),b.addGraphic(f,d.graphics3DGraphic))}return F.create(function(a){return!0})}b.visibilityInfoChange(f);b.resetLabels(f);return b.createLabelClassContext(f)},elevationInfoChange:function(){b.elevationInfoChange(f)},visibilityInfoChange:function(){b.visibilityInfoChange(f)},clear:function(){b.resetLabels(f)}}}};b.prototype.removeGraphicsOwner=function(a){if(a=this.findLabelingContext(a)){var c=
this.labelingContexts.indexOf(a);this.labelingContexts.splice(c,1);for(var b in a.labels)this.removeGraphic(a,a.labels[b].graphics3DGraphic);this.setDirty()}};b.prototype.setLabelGraphicVisibility=function(a,c){a=a.graphic.uid;var b=this.labels[a];b&&(c&&!b.rendered?(this.labelsToAdd[a]=b,b.hasTextTextureResources||(b.labelingContext.labelsToInitialize[a]=b)):!c&&b.rendered&&(this.labelsToRemove[a]=b),b.visible=c,this.setDirty(b.labelingContext.graphics3DCore.asyncUpdates))};Object.defineProperty(b.prototype,
"labelStageLayerId",{get:function(){return this.labelStageLayer.id},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"isDirty",{get:function(){return this.dirty||this.textTextureAtlas&&this.textTextureAtlas.isDirty},enumerable:!0,configurable:!0});b.prototype.setDirty=function(a){void 0===a&&(a=!0);this.dirty=!0;a||this.idleUpdate()};Object.defineProperty(b.prototype,"updating",{get:function(){return this.labelingContexts.some(function(a){return a.labelClassPromise&&!a.labelClassPromise.isResolved()})},
enumerable:!0,configurable:!0});var g;b.tmpGraphicCreationContext={graphic:null,renderingInfo:null,layer:null};q([p.property({constructOnly:!0})],b.prototype,"view",void 0);q([p.property({type:Boolean,readOnly:!0})],b.prototype,"updating",null);return b=g=q([p.subclass()],b)}(p.declared(D));u.Labeler=m;var A=[0,0,0,1]});