// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/awaiterHelper dojo/errors/CancelError ../../../../request ../../../../core/asyncUtils ../../../../core/Error ../../../../core/has ../../../../core/lang ../../../../core/Logger ../../../../core/promiseUtils ../../../../core/urlUtils ../../../../core/Version ../../../../geometry/support/aaBoundingBox ../../glTF/DefaultLoadingContext ../../glTF/loader ../../lib/gl-matrix ../../support/imageUtils ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/lib/Texture ../../webgl-engine/materials/DefaultMaterial".split(" "),
function(ma,q,na,l,u,E,Y,Z,aa,T,M,ba,n,J,U,ca,da,ea,F,fa,ga,ha,ia,ja,ka){function G(a,b){b.lods&&b.lods.length===a.length&&a.forEach(function(a,c){a.lodMetrics=b.lods[c].metrics});return a}function y(a,b){b=b||{};var f=b.streamDataSupplier;if(f){var c=f.request(a,"json");return n.create(function(a,b){c.then(function(b,c){a(c)},function(a){b(a instanceof E?a:H(a))})},function(){f.cancelRequest(c)})}var e=Y(a);return n.create(function(a,b){e.then(function(b){a(b.data)},function(a){b(a instanceof E?
a:H(a))})},function(){e.cancel()})}function H(a){return new aa("","Request for object resource failed: "+a)}function v(a,b){return u(this,void 0,void 0,function(){var f,c,e,d,p,m,h,z,w,q,K,V,N,u,O,I,n,v,A,y,P,E,B,J,F,G,Q,R,C,D,H,x,L,W;return l(this,function(k){switch(k.label){case 0:return e=[],d=[],p=[],m=[],h=[],z=U.Version.parse(a.version||"1.0","wosr"),la.validate(z),w="meshsymbol_"+a.model.name,q=a.textureDefinitions,[4,X(w,q,b)];case 1:K=k.sent();for(V in K)h.push(K[V].engineTexObj);N=a.model.geometries;
u=a.materialDefinitions;for(I=O=0;I<N.length;I++){var r=n=N[I],g=r.params,l=g.topology;k=!0;g.vertexAttributes||(t.warn("Geometry must specify vertex attributes"),k=!1);switch(g.topology){case "PerAttributeArray":break;case "Indexed":case null:case void 0:l=g.faces;if(!l)t.warn("Indexed geometries must specify faces"),k=!1;else if(g.vertexAttributes){var S=void 0;for(S in g.vertexAttributes)(g=l[S])&&g.values?(null!=g.valueType&&"UInt32"!==g.valueType&&(t.warn("Unsupported indexed geometry indices type '"+
g.valueType+"', only UInt32 is currently supported"),k=!1),null!=g.valuesPerElement&&1!==g.valuesPerElement&&(t.warn("Unsupported indexed geometry values per element '"+g.valuesPerElement+"', only 1 is currently supported"),k=!1)):(t.warn("Indexed geometry does not specify face indices for '"+S+"' attribute"),k=!1)}break;default:t.warn("Unsupported topology '"+l+"'"),k=!1}r.params.material||(t.warn("Geometry requires material"),k=!1);r=r.params.vertexAttributes;g=void 0;for(g in r)r[g].values||(t.warn("Geometries with externally defined attributes are not yet supported"),
k=!1);if(k){k=n.params;f=k.material;c=k.texture;v=n.params.vertexAttributes;A={};for(y in v)P=v[y],E=P.values,A[y]={data:E,size:P.valuesPerElement};p.push([]);B={};if("PerAttributeArray"===n.params.topology){k=J=A.position.data.length/A.position.size;r=new Uint32Array(k);for(g=0;g<k;g++)r[g]=g;F=r;for(G in A)B[G]=F}else for(R in Q=n.params.faces,Q)B[R]=new Uint32Array(Q[R].values);C=c?K[c]:null;D=m[f]?m[f][c]:null;D||(H=f.substring(f.lastIndexOf("/")+1),x=u[H].params,1===x.transparency&&(x.transparency=
0),L={ambient:x.diffuse,diffuse:x.diffuse,specular:[0,0,0],opacity:1-(x.transparency||0),transparent:0<x.transparency,textureId:C?C.engineTexObj.id:void 0,textureInitTransparent:!0,doubleSided:!0,cullFace:"none",flipV:!1,colorMixMode:x.externalColorMixMode||"tint"},T("enable-feature:jkieboom/alpha-channel-usage")&&C&&("transparency"===C.alphaChannelUsage||"maskAndTransparency"===C.alphaChannelUsage)&&(L.transparent=!0),b&&b.materialParamsMixin&&M.mixin(L,b.materialParamsMixin),D=new ka(L,w),m[f]||
(m[f]={}),m[f][c]=D,d.push(D));p[I].push(D);W=new ha(new ia(A,B),w);O+=B.position?B.position.length:0;e.push(W)}}return[2,{stageResources:{textures:h,materials:d,geometries:e},materialsByComponent:p,pivotOffset:a.model.pivotOffset,numberOfVertices:O}]}})})}function X(a,b,f){return u(this,void 0,void 0,function(){var c,e,d,p,m,h,z,w;return l(this,function(l){switch(l.label){case 0:c=[];e=function(d){var e=b[d],h=e.images[0].data;if(!h)return t.warn("Externally referenced texture data is not yet supported"),
"continue";var h=e.encoding+";base64,"+h,l="/textureDefinitions/"+d,m={noUnpackFlip:!0,wrapClamp:!1};T("enable-feature:jkieboom/alpha-channel-usage")&&(m.wrapClamp=!0);d=f&&f.disablePreloadTextures?n.resolve(h):fa.requestImage(h);c.push(d.then(function(b){return{refId:l,engineTexObj:new ja(b,a,m),alphaChannelUsage:"rgba"===e.channels?e.alphaChannelUsage||"transparency":"none"}}))};for(d in b)e(d);return[4,n.all(c)];case 1:p=l.sent();m={};h=0;for(z=p;h<z.length;h++)w=z[h],m[w.refId]=w;return[2,m]}})})}
Object.defineProperty(q,"__esModule",{value:!0});var t=ba.getLogger("esri.views.3d.layers.graphics.objectResourceUtils"),la=new U.Version(1,2,"wosr");q.fetch=function(a,b){void 0===b&&(b={});return u(this,void 0,void 0,function(){var f,c;return l(this,function(e){switch(e.label){case 0:if(!M.endsWith(a,".gltf")&&!M.endsWith(a,".glb"))return[3,2];f=new da.DefaultLoadingContext(b.streamDataSupplier);return[4,ea.load(f,a)];case 1:return[2,e.sent()];case 2:return[4,y(a,b)];case 3:return c=e.sent(),[4,
v(c,b)];case 4:return[2,e.sent()]}})})};q.fetchLod=function(a,b){return u(this,void 0,void 0,function(){var f,c,e,d,p,m=this;return l(this,function(h){switch(h.label){case 0:return f=J.removeFile(a),[4,y(a,b)];case 1:return c=h.sent(),c.lods?[4,n.all(c.lods.map(function(a){return a.href?y(J.makeAbsolute(a.href,f)):c}))]:[3,4];case 2:return e=h.sent(),d=G,[4,Z.map(e,function(a){return u(m,void 0,void 0,function(){return l(this,function(c){switch(c.label){case 0:return[4,v(a,b)];case 1:return[2,c.sent()]}})})})];
case 3:return[2,d.apply(void 0,[h.sent(),c])];case 4:return p=G,[4,v(c,b)];case 5:return[2,p.apply(void 0,[[h.sent()],c])]}})})};q.computeBoundingBox=function(a){a=a.stageResources[ga.ModelContentType.GEOMETRY];for(var b=ca.empty(),f=[0,0,0],c=[0,0,0],e=0;e<a.length;e++){var d=a[e].boundingInfo;F.vec3d.set(d.getBBMin(),f);F.vec3d.set(d.getBBMax(),c);for(d=0;3>d;++d)b[d]=Math.min(b[d],f[d]),b[d+3]=Math.max(b[d+3],c[d])}return b};q.createStageResources=v;q.createTextureResources=X});