// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../core/has ../../../core/promiseUtils ./Container ./webgl/BitBlitRenderer ./webgl/enums ./webgl/Fader ./webgl/WGLPainter ./webgl/shaders/StencilPrograms ../libs/gl-matrix/common ../libs/gl-matrix/mat2d ../libs/gl-matrix/vec2 ../../support/screenshotUtils ../../webgl/BufferObject ../../webgl/context-util ../../webgl/FramebufferObject ../../webgl/programUtils ../../webgl/RenderingContext ../../webgl/VertexArrayObject".split(" "),function(L,
M,B,w,x,C,D,k,E,F,y,G,p,f,z,A,H,q,I,J,K){function u(f){return{state:f.state,pixelRatio:f.pixelRatio,stationary:f.stationary}}return function(n){function c(){var a=null!==n&&n.apply(this,arguments)||this;a._clipData=new Float32Array(8);a._upperLeft=f.create();a._upperRight=f.create();a._lowerLeft=f.create();a._lowerRight=f.create();a._mat2=p.create();a._clipRendererInitialized=!1;a._contextVersion=null;a._labelFader=new E.default(a);return a}B(c,n);Object.defineProperty(c.prototype,"glPainter",{get:function(){return this._painter},
enumerable:!0,configurable:!0});c.prototype.fadeInLabels=function(){this._labelFader.reset();this.requestRender()};c.prototype.createElement=function(){var a=document.createElement("canvas");a.setAttribute("class","esri-display-object");return a};c.prototype.setElement=function(a){this.element=a};c.prototype.useContextVersion=function(a){this._renderingContext||(this._contextVersion=a)};c.prototype.attach=function(a){if(this.attached)return!0;this._resizeCanvas(a);var b=H.createContextOrErrorHTML(this.element,
{alpha:!0,antialias:!1,depth:!0,stencil:!0},this._contextVersion);this._renderingContext=new J(b);this._contextVersion=this._renderingContext.contextVersion;this.attached=!0;this._cachedRenderParams=u(a);this._painter||(this._painter=new F.default,this._painter.initialize(this._renderingContext));return n.prototype.attach.call(this,a)};c.prototype.detach=function(a){n.prototype.detach.call(this,a);this._boundFBO=null;this._clipFBO&&(this._clipFBO.dispose(),this._clipFBO=null);this._labelsFBO1&&(this._labelsFBO1.dispose(),
this._labelsFBO1=null);this._labelsFBO2&&(this._labelsFBO2.dispose(),this._labelsFBO2=null);this._blitRenderer&&(this._blitRenderer.dispose(),this._blitRenderer=null);this._clipVAO&&(this._clipVAO.dispose(),this._clipVBO=this._clipVAO=null);this._painter&&(this._painter.dispose(),this._painter=null);this._clipStencilProgram&&(this._clipStencilProgram.dispose(),this._clipStencilProgram=null);this._renderingContext&&(this._renderingContext.dispose(),this._renderingContext=null);this._cachedRenderParams=
null};c.prototype.renderChildren=function(a){var b=this.children;a.drawPhase=k.WGLDrawPhase.FILL|k.WGLDrawPhase.LINE|k.WGLDrawPhase.MARKER|k.WGLDrawPhase.TEXT;for(var g=b.length,e=0;e<g;e++){var d=b[e];d.attached&&this.renderChild(d,a)}if(w("esri-featurelayer-webgl-labeling")){var c=a.context,f=c.getBoundFramebufferObject();c.bindFramebuffer(this._labelsFBO2);e=a.stationary;c.setClearColor(0,0,0,e?0:1);c.clear(c.gl.COLOR_BUFFER_BIT);if(e)for(a.drawPhase=k.WGLDrawPhase.LABEL_ALPHA,a.labelFBO=this._labelsFBO1,
a.labelStep=this._labelFader.step(),e=0;e<g;e++)d=b[e],d.attached&&this.renderChild(d,a);else this._labelFader.reset();c.bindFramebuffer(f);a.labelFBO=this._labelsFBO2;a.drawPhase=k.WGLDrawPhase.LABEL;for(e=0;e<g;e++)d=b[e],d.attached&&this.renderChild(d,a);a=this._labelsFBO2;this._labelsFBO2=this._labelsFBO1;this._labelsFBO1=a}};c.prototype.beforeRenderChildren=function(a,b){a=b.context;var g=b.state,e=b.pixelRatio;if(b=this._painter){a.enforceState();b.update(g,e);var d=g.width;b=g.height;var c=
g.rotation,d=Math.round(d*e);b=Math.round(b*e);this._boundFBO=a.getBoundFramebufferObject();!w("esri-featurelayer-webgl-labeling")||this._labelsFBO1&&this._labelsFBO1.width===d&&this._labelsFBO1.height===b||(this._labelsFBO1&&(this._labelsFBO1.dispose(),this._labelsFBO2.dispose()),this._labelsFBO1=q.createWithAttachments(a,{target:3553,pixelFormat:6408,internalFormat:6408,dataType:5121,samplingMode:9728,wrapMode:33071,width:d,height:b},{colorTarget:0,depthStencilTarget:0}),a.bindFramebuffer(this._labelsFBO1),
a.setDepthWriteEnabled(!0),a.setStencilWriteMask(255),a.setClearColor(0,0,0,0),a.setClearDepth(1),a.setClearStencil(0),a.clear(a.gl.COLOR_BUFFER_BIT|a.gl.DEPTH_BUFFER_BIT|a.gl.STENCIL_BUFFER_BIT),a.setDepthWriteEnabled(!1),a.bindFramebuffer(this._boundFBO),this._labelsFBO2=q.createWithAttachments(a,{target:3553,pixelFormat:6408,internalFormat:6408,dataType:5121,samplingMode:9728,wrapMode:33071,width:d,height:b},{colorTarget:0,depthStencilTarget:0}));if(g.spatialReference&&(g.spatialReference._isWrappable?
g.spatialReference._isWrappable():g.spatialReference.isWrappable)){var v=G.toRadian(c),l=Math.abs(Math.cos(v)),h=Math.abs(Math.sin(v)),m=Math.round(g.worldScreenWidth);if(Math.round(d*l+b*h)<=m)this._clipFrame=!1;else{this._clipFBO&&this._clipFBO.width===d&&this._clipFBO.height===b||(this._clipFBO=new q(a,{colorTarget:0,depthStencilTarget:3,width:d,height:b}));var k=.5*d,n=.5*b,g=1/d,r=1/b,e=.5*m*e,t=.5*(d*h+b*l),d=this._upperLeft,l=this._upperRight,h=this._lowerLeft,m=this._lowerRight;f.set(d,-e,
-t);f.set(l,e,-t);f.set(h,-e,t);f.set(m,e,t);p.identity(this._mat2);p.translate(this._mat2,this._mat2,[k,n]);0!==c&&p.rotate(this._mat2,this._mat2,v);f.transformMat2d(d,d,this._mat2);f.transformMat2d(l,l,this._mat2);f.transformMat2d(h,h,this._mat2);f.transformMat2d(m,m,this._mat2);c=this._clipData;c.set([2*h[0]*g-1,2*(b-h[1])*r-1,2*m[0]*g-1,2*(b-m[1])*r-1,2*d[0]*g-1,2*(b-d[1])*r-1,2*l[0]*g-1,2*(b-l[1])*r-1]);this._clipRendererInitialized||this._initializeClipRenderer(a);this._clipVBO.setData(c);this._boundFBO=
a.getBoundFramebufferObject();a.bindFramebuffer(this._clipFBO);a.setDepthWriteEnabled(!0);a.setStencilWriteMask(255);a.setClearColor(0,0,0,0);a.setClearDepth(1);a.setClearStencil(0);a.clear(a.gl.COLOR_BUFFER_BIT|a.gl.DEPTH_BUFFER_BIT|a.gl.STENCIL_BUFFER_BIT);a.setDepthWriteEnabled(!1);this._clipFrame=!0}}else this._clipFrame=!1}};c.prototype.afterRenderChildren=function(a,b){a=this._renderingContext;a.logIno();this._clipFrame&&this._clipRendererInitialized&&(a.bindFramebuffer(this._boundFBO),this._boundFBO=
null,a.bindVAO(this._clipVAO),a.bindProgram(this._clipStencilProgram),a.setDepthWriteEnabled(!1),a.setDepthTestEnabled(!1),a.setStencilTestEnabled(!0),a.setBlendingEnabled(!1),a.setColorMask(!1,!1,!1,!1),a.setStencilOp(7680,7680,7681),a.setStencilWriteMask(255),a.setStencilFunction(519,1,255),a.drawElements(4,6,5123,0),a.bindVAO(),a.setColorMask(!0,!0,!0,!0),a.setBlendingEnabled(!0),a.setStencilFunction(514,1,255),this._blitRenderer.render(a,this._clipFBO.colorTexture,9728,1),a.setStencilTestEnabled(!1))};
c.prototype.doRender=function(a){var b=this.element.style;this.visible?(b.display="block",b.opacity=""+this.opacity,this._resizeCanvas(a),n.prototype.doRender.call(this,a),this._cachedRenderParams=u(a)):b.display="none"};c.prototype.takeScreenshot=function(a){if(!this._cachedRenderParams)return x.reject();this._cachedRenderParams.pixelRatio=a.pixelRatio;var b=a.framebufferWidth,c=a.framebufferHeight,e=a.region,d=document.createElement("canvas");d.width=b;d.height=c;var f=z.createEmptyImageData(e.width,
e.height,d),k=this._renderingContext,l=q.create(k,{colorTarget:0,depthStencilTarget:3,width:b,height:c});k.bindFramebuffer(l);k.setViewport(0,0,b,c);var b=this._cachedRenderParams,h=this._renderingContext.gl;this._renderingContext.setClearColor(0,0,0,0);this._renderingContext.setClearDepth(1);this._renderingContext.setClearStencil(0);this._renderingContext.clear(h.COLOR_BUFFER_BIT|h.DEPTH_BUFFER_BIT|h.STENCIL_BUFFER_BIT);b.context=this._renderingContext;b.painter=this._painter;this.beforeRenderChildren(b,
b);if(null!=a.rotation){var h=b.state,m=h.clone();m.viewpoint.rotation=a.rotation;b.state=m;this.renderChildren(b);b.state=h}else this.renderChildren(b);this.afterRenderChildren(b,b);l.readPixels(e.x,c-(e.y+e.height),e.width,e.height,6408,5121,new Uint8Array(f.data.buffer));k.bindFramebuffer();a=z.encodeResult(f,a,d,{flipY:!0,premultipliedAlpha:!0});return x.resolve(a)};c.prototype.prepareChildrenRenderParameters=function(a){if(!this.attached||!this._renderingContext)return null;a=u(a);var b=this._renderingContext,
c=b.gl;b.setDepthWriteEnabled(!0);b.setStencilWriteMask(255);b.setClearColor(0,0,0,0);b.setClearDepth(1);b.setClearStencil(0);b.clear(c.COLOR_BUFFER_BIT|c.DEPTH_BUFFER_BIT|c.STENCIL_BUFFER_BIT);b.setViewport(0,0,this.element.width,this.element.height);b.setDepthWriteEnabled(!1);a.context=b;a.painter=this._painter;return a};c.prototype.attachChild=function(a,b){return a.attach(b)};c.prototype.detachChild=function(a,b){return a.detach(b)};c.prototype.renderChild=function(a,b){return a.processRender(b)};
c.prototype._resizeCanvas=function(a){var b=this.element,c=b.style,e=a.state,d=a.pixelRatio;a=Math.round(e.width*d);d=Math.round(e.height*d);if(b.width!==a||b.height!==d)b.width=a,b.height=d;c.width=e.width+"px";c.height=e.height+"px"};c.prototype._initializeClipRenderer=function(a){if(this._clipRendererInitialized)return!0;this._blitRenderer=new D;var b=y.stencil.attributes,c=I.createProgram(a,y.stencil);if(!c)return!1;var e=A.createVertex(a,35040,32),d=new Uint16Array([0,1,2,2,1,3]),d=A.createIndex(a,
35044,d);a=new K(a,b,{geometry:[{name:"a_pos",count:2,type:5126,offset:0,stride:8,normalized:!1,divisor:0}]},{geometry:e},d);this._clipStencilProgram=c;this._clipVBO=e;this._clipVAO=a;return this._clipRendererInitialized=!0};return c}(C)});