// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
require({cache:{"esri/core/workers/utils":function(){define(["require","exports","dojo/has"],function(m,b,h){function k(a){return a&&"object"===typeof a&&("result"in a||"transferList"in a)}function e(a){return a instanceof ArrayBuffer||a&&a.constructor&&"ArrayBuffer"===a.constructor.name}Object.defineProperty(b,"__esModule",{value:!0});(function(a){a[a.HANDSHAKE=0]="HANDSHAKE";a[a.CONFIGURE=1]="CONFIGURE";a[a.CONFIGURED=2]="CONFIGURED";a[a.OPEN=3]="OPEN";a[a.OPENED=4]="OPENED";a[a.RESPONSE=5]="RESPONSE";
a[a.INVOKE=6]="INVOKE";a[a.CANCEL=7]="CANCEL";a[a.CLOSE=8]="CLOSE";a[a.OPEN_PORT=9]="OPEN_PORT"})(b.MessageType||(b.MessageType={}));var l=0;b.newJobId=function(){return l++};b.isTranferableResult=k;b.toInvokeError=function(a){return a?a.toJSON?JSON.stringify(a):JSON.stringify({name:a.name,message:a.message,details:a.details,stack:a.stack}):null};b.postMessage=function(a,f,c,g){2===arguments.length||void 0===c&&void 0===g?a.postMessage(f):(h("esri-workers-arraybuffer-transfer")||(g?(g=g.filter(function(a){return!e(a)}),
g.length||(g=null)):k(c)&&c.transferList&&(c.transferList=c.transferList.filter(function(a){return!e(a)}),c.transferList.length||(c.transferList=null))),g?(f.data=c,a.postMessage(f,g)):k(c)?(f.data=c.result,c.transferList?a.postMessage(f,c.transferList):a.postMessage(f)):(f.data=c,a.postMessage(f)))};b.receiveMessage=function(a){return a?(a=a.data)?"string"===typeof a?JSON.parse(a):a:null:null}})},"esri/core/workers/request":function(){define(["require","exports","../tsSupport/assignHelper","../Error",
"../global"],function(m,b,h,k,e){Object.defineProperty(b,"__esModule",{value:!0});var l;b.execute=function(a,f){void 0===f&&(f={});var c=f.responseType;c?"json"!==c&&"text"!==c&&"blob"!==c&&"array-buffer"!==c&&(c="text"):c="json";return e.invokeStaticMessage("request",{url:a,options:f}).then(function(g){var e=g.data,b,p,d;if(e&&("json"===c||"text"===c||"blob"===c)&&(b=new Blob([e]),"json"===c||"text"===c)&&(l||(l=new FileReaderSync),p=l.readAsText(b),"json"===c)){try{d=JSON.parse(p||null)}catch(n){throw g=
h({},n,{url:a,requestOptions:f}),new k("request:server",n.message,g);}if(d.error)throw g=h({},d.error,{url:a,requestOptions:f}),new k("request:server",d.error.message,g);}switch(c){case "json":break;case "text":d=p;break;case "blob":d=b;break;default:d=e}return{data:d,requestOptions:f,ssl:g.ssl,url:a}})}})},"esri/core/tsSupport/assignHelper":function(){define([],function(){return Object.assign||function(m){for(var b,h=1,k=arguments.length;h<k;h++){b=arguments[h];for(var e in b)Object.prototype.hasOwnProperty.call(b,
e)&&(m[e]=b[e])}return m}})},"*noref":1}});
define(["require","exports","../Error","../promiseUtils","./utils"],function(m,b,h,k,e){function l(a,d){a["delete"](d)}var a=e.MessageType.CLOSE,f=e.MessageType.CANCEL,c=e.MessageType.INVOKE,g=e.MessageType.RESPONSE,t=e.MessageType.OPEN_PORT,v=function(){function a(a){this._timer=null;this._cancelledJobIds=new Set;this._invokeMessages=[];this._invoke=a;this._timer=null;this._process=this._process.bind(this)}a.prototype.push=function(a){a.type===e.MessageType.CANCEL?this._cancelledJobIds.add(a.jobId):
(this._invokeMessages.push(a),null===this._timer&&(this._timer=setTimeout(this._process,0)))};a.prototype.clear=function(){this._invokeMessages.length=0;this._cancelledJobIds.clear();this._timer=null};a.prototype._process=function(){this._timer=null;for(var a=0,n=this._invokeMessages;a<n.length;a++){var c=n[a];this._cancelledJobIds.has(c.jobId)||this._invoke(c)}this._cancelledJobIds.clear();this._invokeMessages.length=0};return a}();return function(){function b(a,b,c){this._outJobs=new Map;this._inJobs=
new Map;this._queue=new v(this._onInvoke.bind(this));this._onMessage=this._onMessage.bind(this);this._client=b;this._port=a;this._port.addEventListener("message",this._onMessage);this._port.start();this._channel=c}b.connect=function(a){var d=new MessageChannel;a="function"===typeof a?new a:"default"in a&&"function"===typeof a.default?new a.default:a;a.remoteClient=new b(d.port1,a,d);return d.port2};b.prototype.close=function(){this._post({type:a});this._close()};b.prototype.isBusy=function(){return 0<
this._outJobs.size};b.prototype.invoke=function(a,b,g){var d=this;if(!this._port)return k.reject(new h("remote-client:port-closed","Can't invoke(), port is closed"));var n=e.newJobId(),u=function(){l(d._outJobs,n);d._post({type:f,jobId:n})};return k.create(function(e,f){d._outJobs.set(n,{resolve:e,reject:f,cancel:u});d._post({type:c,jobId:n,methodName:a},b,g)},u)};b.prototype.openPort=function(){var a=this,b=e.newJobId(),c=function(){l(a._outJobs,b);a._post({type:f,jobId:b})};return k.create(function(d,
e){a._outJobs.set(b,{resolve:d,reject:e,cancel:c});a._post({type:t,jobId:b})},c)};b.prototype._close=function(){this._channel&&(this._channel=null);this._port.removeEventListener("message",this._onMessage);this._port.close();this._outJobs.forEach(function(a){a.cancel()});this._inJobs.clear();this._outJobs.clear();this._queue.clear();this._port=this._client=null};b.prototype._onMessage=function(d){if(d=e.receiveMessage(d))switch(d.type){case g:this._onResponse(d);break;case c:this._queue.push(d);break;
case f:this._onCancel(d);break;case a:this._close();break;case t:this._onOpenPort(d)}};b.prototype._onCancel=function(a){var b=this._inJobs,d=a.jobId,c=b.get(d);this._queue.push(a);c&&(l(b,d),c.cancel())};b.prototype._onInvoke=function(a){var b=this,c=a.methodName,d=a.jobId;a=a.data;var f=this._inJobs,h=this._client,m=h[c],q;try{if(!m&&c&&-1!==c.indexOf("."))for(var p=c.split("."),r=0;r<p.length-1;r++)h=h[p[r]],m=h[p[r+1]];if("function"!==typeof m)throw new TypeError(c+" is not a function");q=m.call(h,
a,this)}catch(w){this._post({type:g,jobId:d,error:e.toInvokeError(w)});return}k.isThenable(q)?(f.set(d,q),q.then(function(a){f.has(d)&&(l(f,d),b._post({type:g,jobId:d},a))}).catch(function(a){f.has(d)&&(l(f,d),a&&"cancel"===a.dojoType||b._post({type:g,jobId:d,error:e.toInvokeError(a||{message:"Error encountered at method "+c})}))})):this._post({type:g,jobId:d},q)};b.prototype._onOpenPort=function(a){var d=new MessageChannel;new b(d.port1,this._client);this._post({type:g,jobId:a.jobId},d.port2,[d.port2])};
b.prototype._onResponse=function(a){var b=a.jobId,c=a.error;a=a.data;var d=this._outJobs;if(d.has(b)){var e=d.get(b);l(d,b);c?e.reject(h.fromJSON(JSON.parse(c))):e.resolve(a)}};b.prototype._post=function(a,b,c){return e.postMessage(this._port,a,b,c)};return b}()});