// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/Error ../../../../../core/Logger ../../../../../core/MapPool ../../../../../core/promiseUtils ../../../../../core/accessorSupport/decorators ../../../../../geometry/SpatialReference ../../../../../layers/support/LabelClass ../../../../../renderers/support/jsonUtils ../../../engine/webgl/definitions ../../../engine/webgl/rendererInfoUtils ../../../engine/webgl/Utils ../../../engine/webgl/collisions/CollisionGrid ../../../engine/webgl/mesh/factories/matcherUtils ../../../engine/webgl/mesh/factories/MaterialStore ../../../engine/webgl/mesh/factories/WGLMeshFactory ../../../engine/webgl/mesh/templates/WGLTemplateStore ../../../engine/webgl/util/BidiText ./BaseProcessor".split(" "),
function(u,v,z,e,A,B,r,n,f,w,p,x,C,D,E,F,G,H,I,J,K,L){function M(d){var c=d&&d.getSymbols();return d&&("unique-value"===d.type||"class-breaks"===d.type)&&null!==d.backgroundFillSymbol||c.some(function(a){return"simple-fill"===a.type||"picture-fill"===a.type})}function N(d,c){switch(d){case "esriGeometryPoint":return!0;case "esriGeometryPolyline":return!0;case "esriGeometryMultipoint":return!0;case "esriGeometryPolygon":return M(c);default:return O.error(new A("mapview-invalid-type",d+" is not supported")),
!1}}function P(d,c,a){a.has(d)||a.set(d,new Set);d=a.get(d);a=c.length;for(var b=0;b<a;b++){var l=c.charCodeAt(b);d.add(l)}}Object.defineProperty(v,"__esModule",{value:!0});var O=B.getLogger("esri.views.2d.layers.features.processors.SymbolProcessor");u=function(d){function c(){var a=null!==d&&d.apply(this,arguments)||this;a._symbolToMosaicItemMap=new Map;a._visualSetPromises=new Map;a.type="symbol";return a}z(c,d);c.prototype.destroy=function(){this._visualSetPromises.forEach(function(a,b){a.cancel()});
this._visualSetPromises.clear();this._symbolToMosaicItemMap.clear();this.notifyChange("updating")};Object.defineProperty(c.prototype,"supportsTileUpdates",{get:function(){return!0},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"labelingInfo",{get:function(){return this.configuration&&this.configuration.labelingInfo?this.configuration.labelingInfo.map(function(a){return p.fromJSON(a)}):null},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"labelClassInfos",{get:function(){var a=
this;return this.labelingInfo?this.labelingInfo.map(function(b){return{labelOptions:b.getOptions(a.spatialReference),labelExpression:b.getLabelExpression(),labelClass:b}}):null},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"matcher",{get:function(){return G.createMatcher(this.renderer,this.factory.materials,this.factory.templates,w.fromJSON(this.spatialReference),this.service.fields)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"factory",{get:function(){var a=
this;if(!this.configuration)return null;var b=new H.default,c=new J.default(function(b){return a.remoteClient.invoke("tileRenderer.getMaterialItems",b)},this.configuration.devicePixelRatio);return new I.default(this.service.geometryType,this.service.objectIdField,this.service.fields,this.renderer.visualVariables,this.configuration.devicePixelRatio,w.fromJSON(this.spatialReference),b,c,this.labelingInfo)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"queryInfo",{get:function(){var a=
this.configuration,b=a.renderer,c=a.definitionExpression,Q=a.outFields,d=a.gdbVersion,a=a.historicMoment,h=this.service.geometryType,y=this._getReturnCentroid(this.rendererInfo.renderer),g=N(h,this.rendererInfo.renderer),h="esriGeometryPoint"===h||"esriGeometryMultipoint"===h||y?20:0,k=null;(b=b.visualVariables)&&b.some(function(a){if("size"===a.type&&a.field&&!a.normalizationField)return k=[a.field+" DESC"],!0});return{definitionExpression:c,orderByFields:k,outFields:Q,pixelBuffer:h,returnCentroid:y,
returnGeometry:g,gdbVersion:d,historicMoment:a}},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"renderer",{get:function(){return this.configuration?x.fromJSON(this.configuration.renderer):null},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"rendererInfo",{get:function(){return this.configuration?D.createRendererInfo(x.fromJSON(this.configuration.renderer),this.tileStore.spatialReference,{fields:this.service.fields}):null},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,
"updating",{get:function(){return 0<this._visualSetPromises.size},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"fields",{get:function(){return this.service.fields},enumerable:!0,configurable:!0});c.prototype.onTileData=function(a,b){var c=this,d=b.addOrUpdate,R=b.remove,h=b.clear;b=(d&&d.length?this._processFeatures(a,d):n.resolve()).then(function(b){return c.remoteClient.invoke("tileRenderer.onTileData",{tileKey:a.id,data:{addOrUpdate:b&&b.message||null,remove:R,clear:h}},b&&
b.transferList||null)}).catch(function(b){return c._handleError(a,b)});this._visualSetPromises.set(a,b);b.then(function(){return c._cleanPromise(a)},function(){return c._cleanPromise(a)});this.notifyChange("updating");return b};c.prototype.onTileError=function(a,b){var c=this;b=this.remoteClient.invoke("tileRenderer.onTileError",{tileKey:a.id,error:b});this._visualSetPromises.set(a,b);b.then(function(){return c._cleanPromise(a)},function(){return c._cleanPromise(a)});this.notifyChange("updating");
return b};c.prototype.onTileUpdate=function(a){var b=0;for(a=a.removed;b<a.length;b++){var c=a[b],d=this._visualSetPromises;if(!d.has(c))break;d.get(c).cancel();d.delete(c);this.notifyChange("updating")}};c.prototype._cleanPromise=function(a){this._visualSetPromises.delete(a);this.notifyChange("updating")};c.prototype._processFeatures=function(a,b){var c=this;if(!b||!b.length)return n.resolve(null);var d=this.factory;return d.analyze(b,this.matcher,{viewingMode:"",scale:a.scale}).then(function(b){return c._getLabelMosaicItems(a,
b).then(function(l){return c._writeFeatures(a,b,l,d)})})};c.prototype._writeFeatures=function(a,b,c,d){var l=d.createMeshData(b.length);a={viewingMode:"",scale:a.scale};for(var h=0;h<b.length;h++)d.write(l,b[h],a,c,this._symbolToMosaicItemMap);return this._encodeDisplayData(l)};c.prototype._encodeDisplayData=function(a){var b={},c=[];a.encode(b,c);return{message:b,transferList:c}};c.prototype._handleError=function(a,b){if(b&&"cancel"!==b.dojoType)return this.remoteClient.invoke("tileRenderer.onTileError",
{tileKey:a.id,error:b.message})};c.prototype._getReturnCentroid=function(a){function b(b){if(!b)return!1;b=b.type;return"simple-marker"===b||"picture-marker"===b||"text"===b}if("esriGeometryPolygon"===this.service.geometryType&&this.labelingInfo)return!0;if("esriGeometryPolygon"!==this.service.geometryType)return!1;switch(a.type){case "simple":return b(a.symbol);case "unique-value":return b(a.defaultSymbol)||a.uniqueValueInfos.some(function(a){return b(a.symbol)});case "class-breaks":return b(a.defaultSymbol)||
a.classBreakInfos.some(function(a){return b(a.symbol)});default:return!0}};c.prototype._getLabelMosaicItems=function(a,b){var c=r.acquire(),d=this._createLabelFeatures(a.scale,b,c),f=this._symbolToMosaicItemMap,h=r.acquire(),e=[],g=0;c.forEach(function(b,a){if(f.has(a.id)){var c=f.get(a.id).glyphMosaicItems,d=[];b.forEach(function(a){if(c&&c.length<a||!c[a])d[a]=a});0<d.length&&(h.set(g,a),e.push({symbol:a.toJSON(),id:g,glyphIds:d}),g++)}else{h.set(g,a);var k=[];b.forEach(function(a){return k.push(a)});
e.push({symbol:a.toJSON(),id:g,glyphIds:k});g++}});if(0<e.length)return this.remoteClient.invoke("tileRenderer.getMaterialItems",e).then(function(a){for(var b=0;b<a.length;b++){var c=a[b],e=h.get(c.id);if(e)if(E.isTextSymbol(e))if(f.has(e.id)){if(e=f.get(e.id).glyphMosaicItems,c=c.mosaicItem.glyphMosaicItems)for(var g=0;g<c.length;g++)null!=c[g]&&(e[g]=c[g])}else f.set(e.id,c.mosaicItem);else f.set(e.id,c.mosaicItem)}r.release(h);return d});r.release(c);return n.resolve(d)};c.prototype._getLabelClassInfos=
function(a){return this.labelClassInfos.map(function(a,c){return{id:c,labelClassInfo:a}}).filter(function(b){b=b.labelClassInfo;return(!b.labelClass.minScale||b.labelClass.minScale>=a||0===b.labelClass.minScale)&&(!b.labelClass.maxScale||b.labelClass.maxScale<=a||0===b.labelClass.maxScale)})};c.prototype._createLabelFeatures=function(a,b,c){if(!this.labelingInfo||!b||0===b.length)return null;a=this._getLabelClassInfos(a);if(0===a.length)return null;for(var d=r.acquire(),e=a.map(function(a){return a.id}),
f=new F.default(C.COLLISION_EARLY_REJECT_BUCKET_SIZE),l=0;l<b.length;l++){var g=b[l],k=this.service.geometryType,q=0,m=0;if("esriGeometryPoint"===k)k=g.geometry,q=k.x,m=k.y;else if("esriGeometryPolygon"===k)q=g.centroid.x,m=g.centroid.y;else return null;k=g.attributes[this.service.objectIdField];if(!f.checkOverlap(q,m)){q=Array(a.length);for(m=0;m<a.length;m++){var n=a[m].labelClassInfo,t=K.bidiText(this._evaluateLabelExpression(g,n)),p=t[0],t=t[1];P(n.labelClass.symbol,p,c);q[m]={text:p,rtl:t}}d.set(k,
{text:q,labelingInfo:e})}}return d};c.prototype._evaluateLabelExpression=function(a,b){return b.labelClass.symbol&&p.evaluateWhere(b.labelClass.where,a.attributes)&&b.labelExpression.expression?p.buildLabelText(b.labelExpression.expression,a,this.fields,b.labelOptions):""};e([f.property({readOnly:!0})],c.prototype,"supportsTileUpdates",null);e([f.property()],c.prototype,"configuration",void 0);e([f.property({dependsOn:["configuration"]})],c.prototype,"labelingInfo",null);e([f.property({dependsOn:["labelingInfo"]})],
c.prototype,"labelClassInfos",null);e([f.property({dependsOn:["factory"]})],c.prototype,"matcher",null);e([f.property({dependsOn:["configuration","service","fields"]})],c.prototype,"factory",null);e([f.property({constructOnly:!0})],c.prototype,"queryInfo",null);e([f.property({dependsOn:["configuration"]})],c.prototype,"renderer",null);e([f.property({dependsOn:["configuration"]})],c.prototype,"rendererInfo",null);e([f.property({readOnly:!0})],c.prototype,"updating",null);e([f.property({dependsOn:["service"]})],
c.prototype,"fields",null);return c=e([f.subclass()],c)}(f.declared(L.default));v.default=u});