// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../object ./ensureType ./extensions ./metadata ./utils ./decorators/cast".split(" "),function(A,m,q,h,n,k,p,r){function t(c){return u.test(c)?"replace":"merge"}Object.defineProperty(m,"__esModule",{value:!0});var v=Object.prototype.hasOwnProperty,w=/^_([a-zA-Z0-9]+)(Getter|Setter|Reader|Writer|Caster)$/,x={Getter:"get",Setter:"set",Reader:"json.read.reader",Writer:"json.write.writer",Caster:"cast"},y=/^_(set|get)([a-zA-Z0-9]+)Attr$/;m.processPrototype=function(c){for(var z=
c.declaredClass,d=c.properties||{},e=0,g=Object.getOwnPropertyNames(d);e<g.length;e++){var a=g[e],b=d[a],f=typeof b;null==b?k.setPropertyMetadata(c,a,{value:b}):Array.isArray(b)?k.setPropertyMetadata(c,a,{type:[b[0]],value:null}):"object"===f?p.getProperties(b)||b instanceof Date?k.setPropertyMetadata(c,a,{type:b.constructor,value:b}):k.setPropertyMetadata(c,a,b):"boolean"===f?k.setPropertyMetadata(c,a,{type:Boolean,value:b}):"string"===f?k.setPropertyMetadata(c,a,{type:String,value:b}):"number"===
f?k.setPropertyMetadata(c,a,{type:Number,value:b}):"function"===f&&k.setPropertyMetadata(c,a,{type:b,value:null})}e=0;for(g=Object.getOwnPropertyNames(c);e<g.length;e++){var f=g[e],b=c[f],d=a=void 0,l=w.exec(f);if(l)a=l[1],d=x[l[2]];else if(l=y.exec(f))a=l[2][0].toLowerCase()+l[2].substr(1),d=l[1].toLowerCase();a&&d&&(a=k.getPropertyMetadata(c,a),q.setDeepValue(d,b,a))}e=0;for(g=Object.getOwnPropertyNames(k.getPropertiesMetadata(c));e<g.length;e++)if(a=g[e],b=k.getPropertyMetadata(c,a),d=b.type,f=
b.types,void 0===b.value&&v.call(c,a)&&(b.value=c[a]),!b.cast&&d){a=b;if(h.isOneOf(d))d=h.ensureOneOf(d);else{b=0;for(f=d;Array.isArray(f);)f=f[0],b++;d=1===b?h.ensureArray(f):1<b?h.ensureNArray(f,b):h.ensureType(d)}a.cast=d}else!b.cast&&f&&(Array.isArray(f)?b.cast=h.ensureArrayTyped(h.ensureOneOfType(f[0])):b.cast=h.ensureOneOfType(f));n.processPrototypeMetadatas(k.getPropertiesMetadata(c),z);return k.getPropertiesMetadata(c)};var u=/^properties\.[^.]+\.(?:value|type|(?:json\.type|json\.origins\.[^.]\.type))$/;
m.processClass=function(c){for(var h=c.prototype,d=h.declaredClass,e=c._meta.bases,g={},a=e.length-1;0<=a;a--)p.merge(g,k.getMetadata(e[a].prototype),t);var b=g.properties;n.processClassMetadatas(b,d);Object.defineProperty(c,"__accessorMetadata__",{value:{properties:b,autoDestroy:!!g.autoDestroy}});for(var f={},d=function(a){var c=b[a];f[a]={enumerable:!0,configurable:!0,get:function(){return this.__accessor__?this.__accessor__.get(a):c.value},set:function(b){var d=this.__accessor__;if(!d)Object.defineProperty(this,
a,{enumerable:!0,configurable:!0,writable:!0,value:b});else if(!Object.isFrozen(this)){if(d.initialized&&c.readOnly)throw new TypeError("[accessor] cannot assign to read-only property '"+a+"' of "+this.declaredClass);if(2===d.lifecycle&&c.constructOnly)throw new TypeError("[accessor] cannot assign to construct-only property '"+a+"' of "+this.declaredClass);d.set(a,b)}}}},e=0,a=Object.getOwnPropertyNames(b);e<a.length;e++)d(a[e]);Object.defineProperties(c.prototype,f);if(g.parameters)for(c=0,d=Object.getOwnPropertyNames(g.parameters);c<
d.length;c++)e=d[c],a=Object.getOwnPropertyDescriptor(h,e)||{value:h[e]},(a=r.autocastMethod(h,e,a))&&Object.defineProperty(h,e,a);return g}});