// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/Error ../../../../../../core/Logger ../../../../../../symbols/SimpleLineSymbol ../../definitions ../../enums ../../WGLDisplayObject ../MeshData ../VertexVector ./VVFactory ../templates/WGLLabelTemplate ../templates/WGLLineTemplate ../templates/WGLMarkerTemplate ../../util/vvFlagUtils".split(" "),function(x,t,J,z,A,B,l,g,C,D,k,E,F,G,H,p){Object.defineProperty(t,"__esModule",{value:!0});var u=A.getLogger("esri.views.2d.engine.webgl.WGLMeshFactory"),
I={esriGeometryPoint:"above-right above-center above-left center-center center-left center-right below-center below-left below-right".split(" "),esriGeometryPolygon:["always-horizontal"],esriGeometryPolyline:null,esriGeometryMultipoint:null,esriGeometryEnvelope:null};x=function(){function c(a,b,e,d,f,h,c,g,m){var n=this;this._labelsDebugTemplate=null;this._materials=c;this._geometryType=a;this._idField=b;this._pixelRatio=f;this._vvFlags=p.getVVFlags(d);this._vvFactory=new E.default(d,e,h);this._vvBuf=
new ArrayBuffer(16);this._vvBufU32=new Uint32Array(this._vvBuf);this._vvBufF32=new Float32Array(this._vvBuf);this._templateStore=g;m&&(this._validateLabelingInfo(m)?this._labelTemplates=m.map(function(a){return F.default.fromText(n._materials,0,a.symbol,f,a.labelPlacement)}):u.error(new z("mapview-labeling:unsupported-geometry","LabelingInfo failed validation - unable to create labels for layer.")))}Object.defineProperty(c.prototype,"materials",{get:function(){return this._materials},enumerable:!0,
configurable:!0});Object.defineProperty(c.prototype,"templates",{get:function(){return this._templateStore},enumerable:!0,configurable:!0});c.prototype.createMeshData=function(a){var b=Array(5),e=!!p.getMarkerVVFlags(this._vvFlags),d=!!p.getFillVVFlags(this._vvFlags),f=!!p.getLineVVFlags(this._vvFlags,"esriGeometryPolyline"!==this._geometryType),h=!!p.getTextVVFlags(this._vvFlags);b[g.WGLGeometryType.MARKER]=new k.VertexVectors(g.WGLGeometryType.MARKER,e,a);b[g.WGLGeometryType.FILL]=new k.VertexVectors(g.WGLGeometryType.FILL,
d,a);b[g.WGLGeometryType.LINE]=new k.VertexVectors(g.WGLGeometryType.LINE,f,a);b[g.WGLGeometryType.TEXT]=new k.VertexVectors(g.WGLGeometryType.TEXT,h,a);b[g.WGLGeometryType.LABEL]=new k.VertexVectors(g.WGLGeometryType.LABEL,!1,this._labelTemplates&&0<this._labelTemplates.length?a:0);return new D.default([],b,this._materials)};c.prototype.analyze=function(a,b,e){for(var d=0;d<a.length;d++){var f=a[d],h=-1;b&&(h=b.match(f,e));f.groupId=h}return this._templateStore.finalize().then(function(){return a})};
c.prototype.write=function(a,b,e,d,f){var h=this._templateStore.getTemplateGroup(b.groupId),c=b.attributes[this._idField],g=new C(c),m=!!d&&!!this._labelTemplates&&d.has(c);if(h&&(b.geometry||b.centroid)){this._vvFactory.computeVV(this._vvBufF32,b,e);e=g.displayRecords;for(var n=0;n<h.length;n++){var l=h[n],k=a.get(l.geometryType);l.writeMesh(e,k,this._geometryType,c,b,this._pixelRatio,this._vvBufU32)}m&&(h=this._getLabelReference(h),this._writeLabelMesh(g,a,c,b,f,d.get(c),h));a.pushDisplayObject(g)}};
c.prototype._hasBadLabelClass=function(a,b){var e=a.labelPlacement,d=I[b];if(!d)return u.error(new z("mapview-labeling:unsupported-geometry-type","Unable to create labels for WebGL Feature Layer, "+b+" is not supported")),!0;d.some(function(a){return a===e})||(d=d[0],e&&u.warn("Found invalid label placement type "+e+" for "+b+". Defaulting to "+d),a.labelPlacement=d);return!1};c.prototype._validateLabelingInfo=function(a){var b=this;return!a.some(function(a){return b._hasBadLabelClass(a,b._geometryType)})};
c.prototype._getLabelReference=function(a){for(var b=0;b<a.length;b++){var e=a[b];if(e instanceof H.default)return e}return null};c.prototype._writeLabelMesh=function(a,b,e,d,f,c,g){for(var h=a.displayRecords,m=0,n=0,k=-1,p=-1,v=0;v<c.labelingInfo.length;v++){var w=c.labelingInfo[v],r=c.text[v],q=this._labelTemplates[w],u=b.get(q.geometryType),x=f.get(q.symbolId).glyphMosaicItems,t=h.length;q.bindReferenceTemplate(g);var y=q.computeAnchor(this._geometryType,d);0===v&&(k=Math.floor(y[0]/l.COLLISION_BUCKET_SIZE),
p=Math.floor(y[1]/l.COLLISION_BUCKET_SIZE));q.computeGlyphs(x,r)||(r=q.bounds,q.writeMesh(h,u,this._geometryType,e,d,this._pixelRatio,this._vvBufU32),a.anchor=y,a.addMetric(r,t,h.length-t,w),w=r.center,m=Math.max(r.halfWidth+Math.abs(w[0]),m),n=Math.max(r.halfHeight+Math.abs(w[1]),n))}a.metrics.length&&(e=2.5*Math.max(m,n),b=Math.ceil(Math.abs((e-a.anchor[0]%l.COLLISION_BUCKET_SIZE)/l.COLLISION_BUCKET_SIZE)),e=Math.ceil(Math.abs((e-a.anchor[1]%l.COLLISION_BUCKET_SIZE)/l.COLLISION_BUCKET_SIZE)),a.xBucket=
k,a.yBucket=p,a.xOverflow=b,a.yOverflow=e)};c.prototype._debugLabels=function(a,b,c,d,f){d={geometry:{paths:[[[d[0]+f.center[0]-f.width/2,d[1]+f.center[1]+f.height/2],[0,-f.height],[f.width,0],[0,f.height],[-f.width,0]]]},attributes:{}};f=this._getLabelDebugTemplate();b=b.get(f.geometryType);f.writeMesh(a,b,"esriGeometryPolyline",c,d,this._pixelRatio,null)};c.prototype._getLabelDebugTemplate=function(){this._labelsDebugTemplate||(this._labelsDebugTemplate=this._createLabelsDebugTemplate());return this._labelsDebugTemplate};
c.prototype._createLabelsDebugTemplate=function(){var a=new B({style:"solid",width:1,color:[255,0,0,1]});return G.default.fromSimpleLine(this._materials,0,a,null,this._pixelRatio)};return c}();t.default=x});