// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../support/buffer/InterleavedLayout ../lib/GLMaterial ../lib/Material ../lib/RenderSlot ../lib/Util ./internal/bufferWriters ./internal/MaterialUtil ../shaders/ColorPrograms".split(" "),function(m,y,f,q,n,r,g,h,t,e,p){m=function(d){function a(b,a){a=d.call(this,a)||this;a.supportsEdges=!0;a.bufferWriter=new u;a.params=e.copyParameters(b,v);return a}f(a,d);a.prototype.getParams=function(){return this.params};a.prototype.getParameterValues=
function(){return e.copyParameters(this.params)};a.prototype.setColor=function(b){this.params.color=b;this.notifyDirty("matChanged")};a.prototype.getColor=function(){return this.params.color};a.prototype.setTransparent=function(b){this.params.transparent=b;this.notifyDirty("matChanged")};a.prototype.getTransparent=function(){return this.params.transparent};a.prototype.intersect=function(b,a,l,d,f,g,h,k){e.intersectTriangleGeometry(b,a,l,d,f,g,h)};a.prototype.getGLMaterials=function(){return{color:w,
depthShadowMap:void 0,normal:void 0,depth:void 0,highlight:x}};a.prototype.getAllTextureIds=function(){return[]};return a}(r);var w=function(d){function a(b,a,l){b=d.call(this,b,a)||this;b.updateParameters();return b}f(a,d);a.prototype.updateParameters=function(){this.params=this.material.getParameterValues();this.selectProgram()};a.prototype.selectProgram=function(){this.program=this.programRep.getProgram(p.colorPass,{vertexColors:this.params.vertexColors,slice:this.params.slicePlaneEnabled})};a.prototype.beginSlot=
function(a){return a===(1>this.params.color[3]?g.TRANSPARENT_MATERIAL:g.OPAQUE_MATERIAL)};a.prototype.getProgram=function(){return this.program};a.prototype.bind=function(a,c){c=this.program;var b=this.params;a.bindProgram(c);c.setUniform4fv("eColor",b.color);a.setFaceCullingEnabled(!1);b.polygonOffset&&(a.setPolygonOffsetFillEnabled(!0),a.setPolygonOffset(1,1));b.transparent&&(a.setBlendingEnabled(!0),a.setBlendFunctionSeparate(770,771,1,771));a.setDepthTestEnabled(!0)};a.prototype.release=function(a){var b=
this.params;a.setPolygonOffsetFillEnabled(!1);b.transparent&&a.setBlendingEnabled(!1)};a.prototype.bindView=function(a,c){a=this.program;var b=this.params;e.bindView(c.origin,c.view,a);b.slicePlaneEnabled&&e.bindSlicePlane(c.origin,c.slicePlane,a)};a.prototype.bindInstance=function(a,c){this.program.setUniformMatrix4fv("model",c.transformation)};a.prototype.getDrawMode=function(a){return 4};return a}(n),x=function(d){function a(a,c,l){a=d.call(this,a,c)||this;a.updateParameters();return a}f(a,d);
a.prototype.updateParameters=function(){this.params=this.material.getParameterValues();this.selectProgram()};a.prototype.selectProgram=function(){this.program=this.programRep.getProgram(p.colorPass,{vertexColors:this.params.vertexColors,slice:this.params.slicePlaneEnabled})};a.prototype.beginSlot=function(a){return a===g.OPAQUE_MATERIAL};a.prototype.getProgram=function(){return this.program};a.prototype.bind=function(a,c){c=this.program;var b=this.params;a.bindProgram(c);c.setUniform4fv("eColor",
b.color);a.setFaceCullingEnabled(!1);b.polygonOffset&&(a.setPolygonOffsetFillEnabled(!0),a.setPolygonOffset(1,1))};a.prototype.release=function(a){a.setPolygonOffsetFillEnabled(!1)};a.prototype.bindView=function(a,c){a=this.program;var b=this.params;e.bindView(c.origin,c.view,a);b.slicePlaneEnabled&&e.bindSlicePlane(c.origin,c.slicePlane,a)};a.prototype.bindInstance=function(a,c){this.program.setUniformMatrix4fv("model",c.transformation)};a.prototype.getDrawMode=function(a){return 4};return a}(n),
v={color:[1,1,1,1],transparent:!1,vertexColors:!1,polygonOffset:!1,slicePlaneEnabled:!1},k=q.newLayout().vec3f(h.VertexAttrConstants.POSITION).vec4u8(h.VertexAttrConstants.COLOR),u=function(){function d(){this.vertexBufferLayout=k}d.prototype.allocate=function(a){return k.createBuffer(a)};d.prototype.elementCount=function(a){return a.indices[h.VertexAttrConstants.POSITION].length};d.prototype.write=function(a,b,c,d,e){t.writeDefaultAttributes(b,c,k,a.transformation,a.invTranspTransformation,d,e)};
return d}();return m});