// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../geometry/support/aaBoundingRect ../../lib/gl-matrix ../../support/buffer/InterleavedLayout ../lib/ComponentUtils ../lib/GLMaterialTexture ../lib/Material ../lib/RenderPass ../lib/RenderSlot ../lib/screenSizePerspectiveUtils ../lib/Util ./internal/bufferWriters ./internal/MaterialUtil ../shaders/HUDPrograms".split(" "),function(L,ga,C,U,f,V,W,D,X,M,E,H,d,u,k,I){function J(d,a){void 0===a&&(a=N);if(d.textureIsSignedDistanceField){var b=
d.anchorPos;d=d.distanceFieldBoundingBox;var c=a;c[0]=b[0]*(d[2]-d[0])+d[0];c[1]=b[1]*(d[3]-d[1])+d[1]}else f.vec2d.set(d.anchorPos,a);return a}var O={"bottom-left":[0,0],bottom:[.5,0],"bottom-right":[1,0],left:[0,.5],center:[.5,.5],right:[1,.5],"top-left":[0,1],top:[.5,1],"top-right":[1,1]};L=function(l){function a(b,c){c=l.call(this,c)||this;c._textureDirty=!1;c.params=k.copyParameters(b,Y);"string"===typeof c.params.anchorPos&&(c.params.anchorPos=O[c.params.anchorPos]);c.bufferWriter=new Z(c);
return c}C(a,l);a.prototype.dispose=function(){};a.prototype.getParameterValues=function(){return k.copyParameters(this.params)};a.prototype.setParameterValues=function(b){for(var c in b)"textureId"===c&&d.assert(!!this.params.textureId,"Can only change texture of material that already has a texture"),this.params[c]=b[c];this.notifyDirty("matChanged")};a.prototype.getParams=function(){return this.params};a.prototype.intersect=function(b,c,a,e,B,w,aa,h){if(e.isSelection&&e.enableHUDSelection&&!W.isAllHidden(c.componentVisibilities,
b.data.componentOffsets)){var g=b.data;b=this.params;B=c=1;f.mat4d.toMat3(a,F);if(h){B=h(P);c=B[0];B=B[5];h=F;w=h[0];var m=h[1],l=h[2],k=h[3],v=h[4],n=h[5],q=h[6],r=h[7],z=h[8],x=1/Math.sqrt(w*w+m*m+l*l),y=1/Math.sqrt(k*k+v*v+n*n),u=1/Math.sqrt(q*q+r*r+z*z);h[0]=w*x;h[1]=m*x;h[2]=l*x;h[3]=k*y;h[4]=v*y;h[5]=n*y;h[6]=q*u;h[7]=r*u;h[8]=z*u}h=g.getVertexAttr()[d.VertexAttrConstants.POSITION];w=g.getVertexAttr()[d.VertexAttrConstants.SIZE];g=g.getVertexAttr()[d.VertexAttrConstants.NORMAL];d.assert(3<=
h.size);m=e.point;l=e.camera;k=J(b);for(v=0;v<h.data.length/h.size;v++)n=v*h.size,f.vec3d.set3(h.data[n],h.data[n+1],h.data[n+2],t),f.mat4d.multiplyVec3(a,t,t),n=v*w.size,p[0]=w.data[n]*c,p[1]=w.data[n+1]*B,f.mat4d.multiplyVec3(l.viewMatrix,t),n=v*g.size,f.vec3d.set3(g.data[n],g.data[n+1],g.data[n+2],Q),this.applyVerticalOffsetTransformation(t,Q,F,l,R),l.applyProjection(t,A),-1<A[0]&&(n=Math.floor(A[0]),r=Math.floor(A[1]),H.applyPrecomputedScaleFactorVec2(p,R.factor,p),n=n-G-(0<k[0]?p[0]*k[0]:0),
q=n+p[0]+2*G,r=r-G-(0<k[1]?p[1]*k[1]:0),z=r+p[1]+2*G,b.textureIsSignedDistanceField&&(x=b.outlineSize/2,y=b.distanceFieldBoundingBox,n+=p[0]*y[0],r+=p[1]*y[1],q-=p[0]*(1-y[2]),z-=p[1]*(1-y[3]),n-=x,q+=x,r-=x,z+=x),m[0]>n&&m[0]<q&&m[1]>r&&m[1]<z&&(q=e.p0,r=e.p1,f.mat4d.multiplyVec3(f.mat4d.inverse(l.viewMatrix,ba),t,S),A[0]=m[0],A[1]=m[1],l.unprojectPoint(A,t),n=f.vec3d.negate(e.getDirection(),f.vec3d.create()),q=f.vec3d.dist(q,t)/f.vec3d.dist(q,r),aa(q,n,-1,1,!0,S)))}};a.prototype.normalAndViewAngle=
function(b,c,a,e){void 0===e&&(e=K);f.mat3d.multiplyVec3(c,b,e.normal);f.mat4d.multiplyVec3(a.viewInverseTransposeMatrix,e.normal);e.cosAngle=f.vec3d.dot(T,ca);return e};a.prototype.updateScaleInfo=function(b,c,a){c=this.params;c.screenSizePerspective?b.factor=H.precomputeScaleFactor(K.cosAngle,a,c.screenSizePerspective,b.factor):(b.factor.scale=1,b.factor.factor=0,b.factor.minPixelSize=0,b.factor.paddingPixels=0);c.screenSizePerspectiveAlignment?(b.scaleAlignment=H.precomputeScale(K.cosAngle,a,c.screenSizePerspectiveAlignment),
b.minPixelSizeAlignment=c.screenSizePerspectiveAlignment.parameters.minPixelSize):(b.scaleAlignment=b.factor.scale,b.minPixelSizeAlignment=b.factor.minPixelSize)};a.prototype.applyVerticalOffsetTransformation=function(b,c,a,e,d,l){var g=this.params;16===a.length&&(a=f.mat4d.toMat3(a,F));if(!g.verticalOffset||!g.verticalOffset.screenLength)return d&&(g.screenSizePerspective||g.screenSizePerspectiveAlignment)?(e=this.normalAndViewAngle(c,a,e),g=f.vec3d.length(b),this.updateScaleInfo(d,e.cosAngle,g)):
d&&(d.factor.scale=1,d.scaleAlignment=1),l?f.vec3d.set(b,l):b;c=this.normalAndViewAngle(c,a,e);a=f.vec3d.length(b);e=k.verticalOffsetAtDistance(e,a,g.verticalOffset,c.cosAngle,g.screenSizePerspectiveAlignment||g.screenSizePerspective);d&&this.updateScaleInfo(d,c.cosAngle,a);return f.vec3d.add(b,f.vec3d.scale(c.normal,e),l)};a.prototype.getGLMaterials=function(){return{color:da,depthShadowMap:void 0,normal:void 0,depth:void 0,highlight:ea}};a.prototype.getAllTextureIds=function(){return[this.params.textureId]};
a.prototype.setTextureDirty=function(){this._textureDirty=!0};a.prototype.calculateRelativeScreenBounds=function(b,c,a){void 0===a&&(a=U.create());var e=this.params,g=a;void 0===g&&(g=N);f.vec2d.set(e.anchorPos,g);g[0]*=-b[0];g[1]*=-b[1];g[0]+=e.screenOffset[0]*c;g[1]+=e.screenOffset[1]*c;a[2]=a[0]+b[0];a[3]=a[1]+b[1];return a};a.prototype.calculateAnchorPosForRendering=function(b){return J(this.params,b)};a.shouldRenderVisibilityDuringRenderPass=function(b){return b===M.MATERIAL||M.MATERIAL_HIGHLIGHT};
return a}(X);D=function(d){function a(b,c,a){c=d.call(this,b,c,a,b.getParams().textureId)||this;c.params=k.copyParameters(b.getParams());c.selectProgram();c.selectSlot();return c}C(a,d);a.prototype.selectSlot=function(){this.mainSlot=this.params.drawInSecondSlot?E.HUDMATERIAL2:E.HUDMATERIAL1};a.prototype.beginSlot=function(b){return b===this.mainSlot};a.prototype.getProgram=function(){return this.program};a.prototype.updateParameters=function(){this.params=this.material.getParameterValues();this.updateTexture(this.params.textureId);
this.selectProgram();this.selectSlot()};a.prototype.bindRender=function(b,c){var a=this.params,e=this.getProgram();this.bindTexture(b,e);e.setUniform1i("hudVisibilityTexture",1);b.bindTexture(c.hudVisibilityTexture,1);b.setActiveTexture(0);e.setUniform1f("uRenderTransparentlyOccludedHUD","occluded"===c.renderTransparentlyOccludedHUD?1:"notOccluded"===c.renderTransparentlyOccludedHUD?0:.75);c=c.pixelRatio||1;e.setUniform4fv("overrideColor",a.color);e.setUniform1f("pixelRatio",c);a.textureIsSignedDistanceField&&
(e.setUniform4fv("outlineColor",a.outlineColor),e.setUniform1f("outlineSize",a.outlineSize*c));a.vvSizeEnabled&&(e.setUniform3fv("vvSizeMinSize",a.vvSizeMinSize),e.setUniform3fv("vvSizeMaxSize",a.vvSizeMaxSize),e.setUniform3fv("vvSizeOffset",a.vvSizeOffset),e.setUniform3fv("vvSizeFactor",a.vvSizeFactor));a.vvColorEnabled&&(e.setUniform1fv("vvColorValues",a.vvColorValues),e.setUniform4fv("vvColorColors",a.vvColorColors));e.setUniform2fv("texScale",a.texCoordScale);e.setUniform2f("screenOffset",2*a.screenOffset[0]*
c,2*a.screenOffset[1]*c);e.setUniform2fv("anchorPos",J(a));a.polygonOffset&&(b.setPolygonOffsetFillEnabled(!0),b.setPolygonOffset(0,-4));b.setBlendingEnabled(!0);b.setBlendFunction(1,771)};a.prototype.bindProjection=function(b,a){this.material._textureDirty&&(this.renderTexture(b),this.material._textureDirty=!1);var c=a.cameraAboveGround?1:-1,e=this.getProgram(),d=this.params;b.bindProgram(e);e.setUniform1f("cameraGroundRelative",c);e.setUniform1f("polygonOffset",d.shaderPolygonOffset);e.setUniform4fv("viewport",
a.viewport);k.bindVerticalOffset(d.verticalOffset,a,e);e.setUniformMatrix4fv("viewNormal",a.viewInvTransp);d.screenSizePerspective&&(k.bindScreenSizePerspective(d.screenSizePerspective,a,e,"screenSizePerspective"),k.bindScreenSizePerspective(d.screenSizePerspectiveAlignment||d.screenSizePerspective,a,e,"screenSizePerspectiveAlignment"))};a.prototype.releaseRender=function(b){b.setPolygonOffsetFillEnabled(!1);b.setBlendFunction(770,771);b.setBlendingEnabled(!1)};a.prototype.bindView=function(b,a){b=
a.origin;var c=this.getProgram();k.bindView(b,a.view,c);k.bindCamPos(b,a.viewInvTransp,c)};a.prototype.bindInstance=function(b,a){b=this.getProgram();b.setUniformMatrix4fv("model",a.transformation);b.setUniformMatrix4fv("modelNormal",a.transformationNormal)};a.prototype.getDrawMode=function(b){return 4};return a}(D);var da=function(d){function a(b,a,g){b=d.call(this,b,a,g)||this;b.isOcclusionSlot=!1;return b}C(a,d);a.prototype.selectProgram=function(){var b=this.params;this.programOcclusionTestPixel=
this.programRep.getProgram(I.occlusionPass,{verticalOffset:!!b.verticalOffset,screenSizePerspective:!!b.screenSizePerspective,centerOffsetUnitsScreen:"screen"===b.centerOffsetUnits,slice:b.slicePlaneEnabled});this.program=this.programRep.getProgram(I.colorPass,{occlTest:b.occlusionTest,sdf:b.textureIsSignedDistanceField,vvSize:!!b.vvSizeEnabled,vvColor:!!b.vvColorEnabled,verticalOffset:!!b.verticalOffset,screenSizePerspective:!!b.screenSizePerspective,centerOffsetUnitsScreen:"screen"===b.centerOffsetUnits,
debugDrawBorder:!!b.debugDrawBorder})};a.prototype.getDrawMode=function(b){return this.isOcclusionSlot?0:4};a.prototype.release=function(b){b.setDepthFunction(513);this.isOcclusionSlot||this.releaseRender(b)};a.prototype.bind=function(b,a){this.bindProjection(b,a);var c=this.getProgram();b.setDepthTestEnabled(!0);b.setDepthFunction(515);this.isOcclusionSlot?(c.setUniform4f("color",1,1,1,1),c.setUniform1f("pixelRatio",a.pixelRatio||1)):(this.bindRender(b,a),this.bindTexture(b,c))};a.prototype.bindView=
function(b,a){d.prototype.bindView.call(this,b,a);b=this.getProgram();var c=this.params;this.isOcclusionSlot&&c.slicePlaneEnabled&&k.bindSlicePlane(a.origin,a.slicePlane,b)};a.prototype.getProgram=function(){return this.isOcclusionSlot?this.programOcclusionTestPixel:this.program};a.prototype.getPrograms=function(){return[this.programOcclusionTestPixel,this.program]};a.prototype.beginSlot=function(a){if(this.params.occlusionTest)return this.isOcclusionSlot=a===E.OCCLUSION_PIXELS,a===E.OCCLUSION_PIXELS||
a===this.mainSlot;this.isOcclusionSlot=!1;return a===this.mainSlot};return a}(D),ea=function(d){function a(){return null!==d&&d.apply(this,arguments)||this}C(a,d);a.prototype.selectProgram=function(){var a=this.params;this.program=this.programRep.getProgram(I.highlightPass,{occlTest:a.occlusionTest,sdf:a.textureIsSignedDistanceField,vvSize:!!a.vvSizeEnabled,vvColor:!!a.vvColorEnabled,verticalOffset:!!a.verticalOffset,screenSizePerspective:!!a.screenSizePerspective,centerOffsetUnitsScreen:"screen"===
a.centerOffsetUnits,binaryHighlightOcclusion:a.binaryHighlightOcclusion})};a.prototype.bind=function(a,c){this.bindProjection(a,c);this.bindRender(a,c)};a.prototype.release=function(a){this.releaseRender(a)};return a}(D),R={factor:{scale:0,factor:0,minPixelSize:0,paddingPixels:0},scaleAlignment:0,minPixelSizeAlignment:0},N=[0,0],t=f.vec3d.create(),Q=f.vec3d.create(),A=f.vec3d.create(),T=f.vec3d.create(),S=f.vec3d.create(),F=f.mat3d.create(),ba=f.mat4d.create(),K={normal:T,cosAngle:0},P=f.mat4d.create();
f.mat4d.identity(P);var G=1,p=[0,0],ca=[0,0,1],Y={texCoordScale:[1,1],occlusionTest:!0,binaryHighlightOcclusion:!0,drawInSecondSlot:!1,color:[1,1,1,1],outlineColor:[1,1,1,1],outlineSize:0,textureIsSignedDistanceField:!1,distanceFieldBoundingBox:null,vvSizeEnabled:!1,vvSizeMinSize:[1,1,1],vvSizeMaxSize:[100,100,100],vvSizeOffset:[0,0,0],vvSizeFactor:[1,1,1],vvColorEnabled:!1,vvColorValues:[0,0,0,0,0,0,0,0],vvColorColors:[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],screenOffset:[0,
0],verticalOffset:null,screenSizePerspective:null,screenSizePerspectiveAlignment:null,slicePlaneEnabled:!1,anchorPos:O.center,shaderPolygonOffset:1E-5,polygonOffset:!1,textureId:null,centerOffsetUnits:"world",debugDrawBorder:!1},fa=V.newLayout().vec3f(d.VertexAttrConstants.POSITION).vec3f(d.VertexAttrConstants.NORMAL).vec2f(d.VertexAttrConstants.UV0).vec4u8(d.VertexAttrConstants.COLOR).vec2f(d.VertexAttrConstants.SIZE).vec4f(d.VertexAttrConstants.AUXPOS1).vec4f(d.VertexAttrConstants.AUXPOS2),Z=function(){function f(a){this.material=
a;this.vertexBufferLayout=fa}f.prototype.allocate=function(a){return this.vertexBufferLayout.createBuffer(a)};f.prototype.elementCount=function(a){return 6*a.indices[d.VertexAttrConstants.POSITION].length};f.prototype.write=function(a,b,c,g,e){c=this.material.getParameterValues();u.writePosition(b.indices[d.VertexAttrConstants.POSITION],b.vertexAttr[d.VertexAttrConstants.POSITION].data,a.transformation,g.position,e,6);u.writeNormal(b.indices[d.VertexAttrConstants.NORMAL],b.vertexAttr[d.VertexAttrConstants.NORMAL].data,
a.invTranspTransformation,g.normal,e,6);a=b.vertexAttr[d.VertexAttrConstants.UV0].data;var f=void 0,k=void 0,l=void 0,h=void 0;null==a||4>a.length?(k=f=0,l=c.texCoordScale[0],h=c.texCoordScale[1]):(f=a[0],k=a[1],l=a[2],h=a[3]);var l=Math.min(1.99999,l+1),h=Math.min(1.99999,h+1),p=b.indices[d.VertexAttrConstants.POSITION].length,m=g.uv0;c=e;for(a=0;a<p;++a)m.set(c,0,f),m.set(c,1,k),c+=1,m.set(c,0,l),m.set(c,1,k),c+=1,m.set(c,0,l),m.set(c,1,h),c+=1,m.set(c,0,l),m.set(c,1,h),c+=1,m.set(c,0,f),m.set(c,
1,h),c+=1,m.set(c,0,f),m.set(c,1,k),c+=1;u.writeColor(b.indices[d.VertexAttrConstants.COLOR],b.vertexAttr[d.VertexAttrConstants.COLOR].data,4,g.color,e,6);f=b.indices[d.VertexAttrConstants.SIZE];k=b.vertexAttr[d.VertexAttrConstants.SIZE].data;l=f.length;h=g.size;c=e;for(a=0;a<l;++a)for(var p=k[2*f[a]],m=k[2*f[a]+1],t=0;6>t;++t)h.set(c,0,p),h.set(c,1,m),c+=1;b.indices[d.VertexAttrConstants.AUXPOS1]&&b.vertexAttr[d.VertexAttrConstants.AUXPOS1]&&u.writeBufferVec4(b.indices[d.VertexAttrConstants.AUXPOS1],
b.vertexAttr[d.VertexAttrConstants.AUXPOS1].data,g.auxpos1,e,6);b.indices[d.VertexAttrConstants.AUXPOS2]&&b.vertexAttr[d.VertexAttrConstants.AUXPOS2]&&u.writeBufferVec4(b.indices[d.VertexAttrConstants.AUXPOS2],b.vertexAttr[d.VertexAttrConstants.AUXPOS2].data,g.auxpos2,e,6)};return f}();return L});