// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/Logger ../../lib/gl-matrix ../../support/geometryUtils ../../support/buffer/InterleavedLayout ../lib/ComponentUtils ../lib/GLMaterial ../lib/Material ../lib/RenderSlot ../lib/Util ./internal/bufferWriters ./internal/MaterialUtil ../shaders/NativeLinePrograms".split(" "),function(E,W,z,K,b,d,L,M,F,N,G,u,O,r,H){var P=K.getLogger("esri.views.3d.webgl-engine.materials.NativeLineMaterial");E=function(n){function a(e,a){a=
n.call(this,a)||this;a.bufferWriter=new Q;a.canBeMerged=!0;a.params=r.copyParameters(e,R);return a}z(a,n);a.prototype.setColor=function(a){this.params.color=a;this.notifyDirty("matChanged")};a.prototype.getColor=function(){return this.params.color};a.prototype.getParameterValues=function(){return r.copyParameters(this.params)};a.prototype.intersect=function(a,c,m,n,h,f,r,k){if(n.isSelection&&!M.isAllHidden(c.componentVisibilities,a.data.componentOffsets))if(u.isTranslationMatrix(m)){c=a.data.getVertexAttr().position.data;
h=n.camera;f=n.point;b.vec3d.set3(f[0]-2,f[1]+2,0,x[0]);b.vec3d.set3(f[0]+2,f[1]+2,0,x[1]);b.vec3d.set3(f[0]+2,f[1]-2,0,x[2]);b.vec3d.set3(f[0]-2,f[1]-2,0,x[3]);for(k=0;4>k;k++)h.unprojectPoint(x[k],q[k]);d.plane.fromPoints(h.eye,q[0],q[1],A);d.plane.fromPoints(h.eye,q[1],q[2],B);d.plane.fromPoints(h.eye,q[2],q[3],C);d.plane.fromPoints(h.eye,q[3],q[0],D);a=Number.MAX_VALUE;for(k=0;k<c.length-5;k+=3)if(l[0]=c[k]+m[12],l[1]=c[k+1]+m[13],l[2]=c[k+2]+m[14],g[0]=c[k+3]+m[12],g[1]=c[k+4]+m[13],g[2]=c[k+
5]+m[14],!(0>d.plane.distance(A,l)&&0>d.plane.distance(A,g)||0>d.plane.distance(B,l)&&0>d.plane.distance(B,g)||0>d.plane.distance(C,l)&&0>d.plane.distance(C,g)||0>d.plane.distance(D,l)&&0>d.plane.distance(D,g))){h.projectPoint(l,v);h.projectPoint(g,w);if(0>v[2]&&0<w[2]){b.vec3d.subtract(l,g,p);var e=h.frustumPlanes,t=-d.plane.distance(e[4],l),e=t/b.vec3d.dot(p,e[4]);b.vec3d.scale(p,e,p);b.vec3d.add(l,p,l);h.projectPoint(l,v)}else if(0<v[2]&&0>w[2])b.vec3d.subtract(g,l,p),e=h.frustumPlanes,t=-d.plane.distance(e[4],
g),e=t/b.vec3d.dot(p,e[4]),b.vec3d.scale(p,e,p),b.vec3d.add(g,p,g),h.projectPoint(g,w);else if(0>v[2]&&0>w[2])continue;e=u.pointLineSegmentDistanceSquared2D(v,w,f);e<a&&(a=e,b.vec3d.set(l,I),b.vec3d.set(g,J))}m=n.p0;n=n.p1;4>a&&(a=u.lineLineDistanceSquared3D(I,J,m,n,S),c=Number.MAX_VALUE,a.success&&(b.vec3d.subtract(a.pa,m,y),a=b.vec3d.length(y),b.vec3d.scale(y,1/a),c=a/b.vec3d.dist(m,n)),r(c,y))}else P.error("intersection assumes a translation-only matrix")};a.prototype.getGLMaterials=function(){return{color:T,
depthShadowMap:void 0,normal:void 0,depth:void 0,highlight:U}};a.prototype.getAllTextureIds=function(){return[]};return a}(N);var T=function(b){function a(a,c,m){a=b.call(this,a,c)||this;a.updateParameters();return a}z(a,b);a.prototype.updateParameters=function(){this.params=this.material.getParameterValues();this.selectProgram()};a.prototype.selectProgram=function(){this.program=this.programRep.getProgram(H.colorPass,{slice:this.params.slicePlaneEnabled})};a.prototype.beginSlot=function(a){return a===
G.OPAQUE_MATERIAL};a.prototype.getProgram=function(){return this.program};a.prototype.bind=function(a,c){c=this.program;var e=this.params;a.bindProgram(c);c.setUniform4fv("color",e.color);a.setBlendingEnabled(1>e.color[3]);a.setBlendFunctionSeparate(770,771,1,771);a.setDepthTestEnabled(!0)};a.prototype.release=function(a){1>this.params.color[3]&&a.setBlendingEnabled(!1)};a.prototype.bindView=function(a,c){a=this.program;var b=this.params;r.bindView(c.origin,c.view,a);b.slicePlaneEnabled&&r.bindSlicePlane(c.origin,
c.slicePlane,a)};a.prototype.bindInstance=function(a,c){this.program.setUniformMatrix4fv("model",c.transformation)};a.prototype.getDrawMode=function(a){return 1};return a}(F),U=function(b){function a(a,c,d){a=b.call(this,a,c)||this;a.updateParameters();return a}z(a,b);a.prototype.updateParameters=function(){this.params=this.material.getParameterValues();this.selectProgram()};a.prototype.beginSlot=function(a){return a===G.OPAQUE_MATERIAL};a.prototype.getProgram=function(){return this.program};a.prototype.selectProgram=
function(){this.program=this.programRep.getProgram(H.highlightPass,{slice:this.params.slicePlaneEnabled})};a.prototype.bind=function(a,b){a.bindProgram(this.program);a.setDepthTestEnabled(!0)};a.prototype.release=function(a){};a.prototype.bindView=function(a,b){a=this.program;var c=this.params;r.bindView(b.origin,b.view,a);c.slicePlaneEnabled&&r.bindSlicePlane(b.origin,b.slicePlane,a)};a.prototype.bindInstance=function(a,b){this.program.setUniformMatrix4fv("model",b.transformation)};a.prototype.getDrawMode=
function(a){return 1};return a}(F),R={color:[1,1,1,1],slicePlaneEnabled:!1},V=L.newLayout().vec3f(u.VertexAttrConstants.POSITION),t,Q=function(){function b(){this.vertexBufferLayout=V}b.prototype.allocate=function(a){return this.vertexBufferLayout.createBuffer(a)};b.prototype.elementCount=function(a){return a.indices[u.VertexAttrConstants.POSITION].length};b.prototype.write=function(a,b,c,d,l){var h=c=b.vertexAttr[u.VertexAttrConstants.POSITION].data;if(a=a.transformation){if(!t||t.length<c.length)t=
new Float32Array(c.length);for(var h=t,f=0;f<c.length;f+=3){var e=c[f],k=c[f+1],g=c[f+2];h[f]=a[0]*e+a[4]*k+a[8]*g+a[12];h[f+1]=a[1]*e+a[5]*k+a[9]*g+a[13];h[f+2]=a[2]*e+a[6]*k+a[10]*g+a[14]}}O.writeBufferVec3(b.indices[u.VertexAttrConstants.POSITION],h,d.position,l)};return b}(),l=b.vec3d.create(),g=b.vec3d.create(),p=b.vec3d.create(),y=b.vec3d.create(),v=b.vec3d.create(),w=b.vec3d.create(),I=b.vec3d.create(),J=b.vec3d.create(),S={success:!1,dist2:0,pa:b.vec3d.create(),pb:b.vec3d.create()},x=[b.vec3d.create(),
b.vec3d.create(),b.vec3d.create(),b.vec3d.create()],q=[b.vec3d.create(),b.vec3d.create(),b.vec3d.create(),b.vec3d.create()],A=d.plane.create(),B=d.plane.create(),C=d.plane.create(),D=d.plane.create();return E});