// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("../core/kebabDictionary ../core/urlUtils ../core/promiseUtils ../core/screenUtils ../geometry/Polygon ../kernel ../request ../core/lang dojo/dom-construct dojox/gfx/canvas ./Geoprocessor ./support/fileFormat ./support/layoutTemplate ./support/PrintTemplate ./support/printTaskUtils ./Task".split(" "),function(z,x,E,A,F,v,G,m,H,y,I,J,K,L,q,M){function w(a){return a&&(a.path||"image/svg+xml"===a.contentType)}var B={Feet:"ft",Kilometers:"km",Meters:"m",Miles:"mi"},C=z({esriFeet:"Feet",esriKilometers:"Kilometers",
esriMeters:"Meters",esriMiles:"Miles"}),N=z({esriExecutionTypeSynchronous:"sync",esriExecutionTypeAsynchronous:"async"});return M.createSubclass({declaredClass:"esri.tasks.PrintTask",constructor:function(){this._handleExecuteResponse=this._handleExecuteResponse.bind(this)},_vtlExtent:null,_legendLayers:[],_legendLayerNameMap:{},_gpServerUrl:null,_cimVersion:null,_is11xService:!1,_data:null,properties:{mode:{readonly:!0,value:"sync"},_geoprocessor:{dependsOn:["url","updateDelay"],get:function(){return new I(this.url,
{updateDelay:this.updateDelay})}},url:{value:null,type:String},updateDelay:{value:1E3,type:Number}},execute:function(a,e){var d=this.url,l=d.lastIndexOf("/GPServer/");0<l&&(d=d.slice(0,l+9));return E.resolve().then(function(){if(this._gpServerUrl===d)return{data:this._data};this._gpServerUrl=d;return G(d,{query:{f:"json"}})}.bind(this)).then(function(b){this._data=b.data;this._cimVersion=this._data.cimVersion;this._is11xService=!!this._cimVersion;b=this._setPrintParams(a);this._data.executionType&&
(this.mode=N.fromJSON(this._data.executionType));return this._geoprocessor["async"===this.mode?"submitJob":"execute"](b,e).then(this._handleExecuteResponse)}.bind(this))},_createOperationalLayers:function(a,e){var d=[],l,b,k,c,D=a.map.allLayers.filter(function(a){return a.parent&&"group"===a.parent.type&&!a.parent.visible?!1:!0}).items;for(l=0;l<D.length;l++)if(b=D[l],b.loaded&&b.visible)switch(c={id:b.id,title:this._legendLayerNameMap[b.id]||b.title,opacity:b.opacity,minScale:b.minScale||0,maxScale:b.maxScale||
0,url:b.url&&x.normalize(b.url),token:b.token},k=b.declaredClass,k){case "esri.layers.ImageryLayer":var f={bandIds:b.bandIds,compressionQuality:b.compressionQuality,format:b.format,interpolation:b.interpolation};b.mosaicRule&&(f.mosaicRule=b.mosaicRule.toJSON());b.renderingRule&&(f.renderingRule=b.renderingRule.toJSON());d.push(m.mixin(c,f));this._legendLayers&&this._legendLayers.push({id:b.id});break;case "esri.layers.OpenStreetMapLayer":m.mixin(c,{type:"OpenStreetMap"});d.push(c);break;case "esri.layers.GraphicsLayer":m.mixin(c,
this._createFeatureCollectionJSON(b,null,e));d.push(c);this._legendLayers&&this._legendLayers.push({id:b.id});break;case "esri.layers.VectorTileLayer":delete c.url;delete c.token;if(this._is11xService&&b.serviceUrl&&b.styleUrl){var f=v.id&&v.id.findCredential(b.styleUrl),g=v.id&&v.id.findCredential(b.serviceUrl);if(!f&&!g||"2.1.0"!==this._cimVersion){m.mixin(c,{type:"VectorTileLayer",styleUrl:x.normalize(b.styleUrl)});f&&(c.token=f.token);g&&g.token!==c.token&&(c.additionalTokens=[{url:b.serviceUrl,
token:g.token}]);d.push(c);break}}c.type="image";g=e.exportOptions&&e.exportOptions.dpi||96;k=e.exportOptions&&e.exportOptions.width%2===a.width%2;var n=e.exportOptions&&e.exportOptions.height%2===a.height%2,p={format:"png",rotation:0},f=this._vtlExtent||a.extent.clone();"MAP_ONLY"!==e.layout||!e.preserveScale||e.outScale&&e.outScale!==a.scale||96!==g||k&&n||(p.area={x:0,y:0,width:a.width,height:a.height},k||--p.area.width,n||--p.area.height,this._vtlExtent||(g=a.toMap({x:p.area.width,y:p.area.height}),
f.ymin=g.y,f.xmax=g.x,this._vtlExtent=f));c.extent=f.clone()._normalize(!0).toJSON();f=a.whenLayerView(b);f.isResolved()&&f.then(function(b){b=b.takeScreenshot(p,a);b.isResolved()?b.then(function(a){a=x.dataComponents(a.dataUrl);c.imageData=a.data}):console.error("PrintTask: VectorTileLayer.takeScreenshot() returned an unresolved Promise");c.imageData&&d.push(c)});break;case "esri.layers.MapImageLayer":var h={id:b.id,subLayerIds:[]},t=[],r=a.scale,u=function(a){var b=0===r,d=0===a.minScale||r<=a.minScale,
c=0===a.maxScale||r>=a.maxScale;a.visible&&(b||d&&c)&&(a.sublayers?a.sublayers.forEach(u):(b=a.toExportImageJSON().drawingInfo,d=a.toJSON(),d.layerDefinition.drawingInfo=b,t.unshift(d),h.subLayerIds.push(a.id)))};b.sublayers&&b.sublayers.forEach(u);t.length&&(m.mixin(c,{layers:t,visibleLayers:h.subLayerIds}),d.push(c),this._legendLayers.push(h));break;case "esri.layers.KMLLayer":this._is11xService?(c={},b.write(c,{origin:"web-map"}),c.showLabels=e.showLabels,d.push(c)):a.whenLayerView(b).then(function(a){a.allVisibleMapImages.forEach(function(a,
c){c={id:b.id+"_image"+c,type:"image",title:b.id,minScale:b.minScale||0,maxScale:b.maxScale||0,opacity:b.opacity,extent:a.extent.toJSON()};"data:image/png;base64,"===a.href.substr(0,22)?c.imageData=a.href.substr(22):c.url=a.href;d.push(c)});a=a.allVisiblePoints.concat(a.allVisiblePolylines).concat(a.allVisiblePolygons);var c={id:b.id};m.mixin(c,this._createFeatureCollectionJSON(null,a,e));d.push(c)}.bind(this));break;case "esri.layers.WMSLayer":t=[];u=function(a){a.visible&&(a.sublayers?a.sublayers.forEach(u):
a.name&&t.unshift(a.name))};b.sublayers&&b.sublayers.forEach(u);m.mixin(c,{type:"wms",transparentBackground:b.imageTransparency,visibleLayers:t,version:b.version});d.push(c);break;case "esri.layers.WMTSLayer":f=b.activeLayer;m.mixin(c,{type:"wmts",layer:f.id,style:f.styleId,format:f.imageFormat,tileMatrixSet:f.tileMatrixSetId});d.push(c);break;case "esri.layers.WebTileLayer":f=b.urlTemplate.replace(/\$\{/g,"{");m.mixin(c,{type:"WebTiledLayer",urlTemplate:f,credits:b.copyright});b.subDomains&&0<b.subDomains.length&&
(c.subDomains=b.subDomains);d.push(c);break;case "esri.layers.CSVLayer":if(this._is11xService){c={};b.write(c,{origin:"web-map"});d.push(c);break}case "esri.layers.StreamLayer":case "esri.layers.FeatureLayer":g=(f=b.renderer)&&!f.hasVisualVariables()&&!b.featureReduction&&!f.valueExpression&&"esri.layers.CSVLayer"!==k;k="esri.layers.FeatureLayer"===k&&b.source&&b.source.length||"esri.layers.StreamLayer"===k;(this._is11xService||g)&&!k&&f&&("esri.renderer.SimpleRenderer"===f.declaredClass||null==f.field||
"string"===typeof f.field&&b.getField(f.field))?(b.write(c,{origin:"web-map"}),delete c.layerType,delete c.popupInfo,delete c.visibility,c.layerDefinition&&c.layerDefinition.drawingInfo&&c.layerDefinition.drawingInfo.renderer&&(this._convertSvgRenderer(c.layerDefinition.drawingInfo.renderer),f.visualVariables&&f.visualVariables[0]&&f.visualVariables[0].maxSize&&"number"!==typeof f.visualVariables[0].maxSize&&f.visualVariables[0].minSize&&"number"!==typeof f.visualVariables[0].minSize&&(f=f.getSizeRangeAtScale(f.visualVariables[0],
a.scale),c.layerDefinition.drawingInfo.renderer.visualVariables[0].minSize=f.minSize,c.layerDefinition.drawingInfo.renderer.visualVariables[0].maxSize=f.maxSize))):(f=this._getGraphics(a,b),m.mixin(c,this._createFeatureCollectionJSON(b,f,e)));d.push(c);this._legendLayers&&this._legendLayers.push({id:b.id});break;case "esri.layers.MapNotesLayer":var q=[];b.featureCollections.map(function(a){var b=a.source.toArray();a=this._createFeatureCollectionJSON(a,b,e).featureCollection;q=q.concat(a.layers)}.bind(this));
m.mixin(c,{featureCollection:{layers:q}});d.push(c);break;default:d.push(c)}a.graphics&&a.graphics.length&&(c=this._createFeatureCollectionJSON({},a.graphics,e))&&d.push(c);return d},_createFeatureCollectionJSON:function(a,e,d){var l=q.createPolygonLayer(),b=q.createPolylineLayer(),k=q.createPointLayer(),c=q.createMultipointLayer(),m=q.createPointLayer();m.layerDefinition.name="textLayer";delete m.layerDefinition.drawingInfo;a&&("esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===
a.declaredClass?l.layerDefinition.name=b.layerDefinition.name=k.layerDefinition.name=c.layerDefinition.name=this._legendLayerNameMap[a.id]||a.get("arcgisProps.title")||a.title:"esri.layers.GraphicsLayer"===a.declaredClass&&(e=a.graphics.items));var f=a.renderer&&"esri.renderer.SimpleRenderer"===a.renderer.declaredClass;if(a&&a.renderer&&"function"!==typeof a.get("renderer.field")){var g=a.renderer.toJSON();l.layerDefinition.drawingInfo.renderer=g;b.layerDefinition.drawingInfo.renderer=g;k.layerDefinition.drawingInfo.renderer=
g;c.layerDefinition.drawingInfo.renderer=g}else delete l.layerDefinition.drawingInfo,delete b.layerDefinition.drawingInfo,delete k.layerDefinition.drawingInfo,delete c.layerDefinition.drawingInfo;var n=a&&a.fields,g=a&&a.renderer,p=[];g&&"function"!==typeof a.get("renderer.field")&&("class-breaks"===g.type?(n||(n=[{name:g.field,type:"esriFieldTypeDouble"}],g.normalizationField&&n.push({name:g.normalizationField,type:"esriFieldTypeDouble"})),g.field&&p.push(g.field),g.normalizationField&&p.push(g.normalizationField)):
"unique-value"===g.type&&(n||(n=[{name:g.field,type:"esriFieldTypeString"}],g.field2&&n.push({name:g.field2,type:"esriFieldTypeString"}),g.field3&&n.push({name:g.field3,type:"esriFieldTypeString"})),g.field&&p.push(g.field),g.field2&&p.push(g.field2),g.field3&&p.push(g.field3)));n&&(l.layerDefinition.fields=n,b.layerDefinition.fields=n,k.layerDefinition.fields=n,c.layerDefinition.fields=n);for(var n=e&&e.length,h,t=0;t<n;t++){var r=e[t]||e.getItemAt(t);if(!1!==r.visible&&r.geometry&&(h=r.toJSON(),
h.hasOwnProperty("popupTemplate")&&delete h.popupTemplate,h.geometry&&h.geometry.z&&delete h.geometry.z,!h.symbol||!h.symbol.outline||"esriCLS"!==h.symbol.outline.type||this._is11xService)){h.symbol&&h.symbol.outline&&h.symbol.outline.color&&h.symbol.outline.color[3]&&!this._is11xService&&(h.symbol.outline.color[3]=255);if(a&&a.renderer&&!h.symbol&&("function"===typeof a.renderer.field||a.renderer.compiledFunc||a.renderer.hasVisualVariables()||a.renderer)){var g=a.renderer,u=g.getSymbol(r);if(!u)continue;
h.symbol=u.toJSON();g.hasVisualVariables()&&q.applyVisualVariables(h.symbol,{renderer:g,graphic:r,symbol:u})}h.symbol&&(h.symbol.angle||delete h.symbol.angle,w(h.symbol)?h.symbol=this._convertSvgToPictureMarkerSymbolJson(h.symbol):h.symbol.text&&delete h.attributes);if(!d||!d.forceFeatureAttributes)if(a&&a.renderer&&"simple"===a.renderer.type)delete h.attributes;else if(p.length){var v={};p.forEach(function(a){h.attributes&&h.attributes.hasOwnProperty(a)&&(v[a]=h.attributes[a])});h.attributes=v}"polygon"===
r.geometry.type?l.featureSet.features.push(h):"polyline"===r.geometry.type?b.featureSet.features.push(h):"point"===r.geometry.type?h.symbol&&h.symbol.text?m.featureSet.features.push(h):k.featureSet.features.push(h):"multipoint"===r.geometry.type?c.featureSet.features.push(h):"extent"===r.geometry.type&&(h.geometry=F.fromExtent(r.geometry).toJSON(),l.featureSet.features.push(h))}}a=[l,b,c,k,m].filter(function(a){return 0<a.featureSet.features.length});a.forEach(function(a){var b=a.featureSet.features.every(function(a){return a.symbol});
!b&&!f||d&&d.forceFeatureAttributes||a.featureSet.features.forEach(function(a){delete a.attributes});b&&delete a.layerDefinition.drawingInfo;a.layerDefinition.drawingInfo&&a.layerDefinition.drawingInfo.renderer&&this._convertSvgRenderer(a.layerDefinition.drawingInfo.renderer)},this);return a.length?{featureCollection:{layers:a}}:null},_convertSvgToPictureMarkerSymbolJson:function(a){this._canvasParent||(this._canvasParent=H.create("div"),this._canvasSurface=y.createSurface(this._canvasParent,200,
200));var e;e="image/svg+xml"===a.contentType?this._canvasSurface.createObject(y.Image,{src:"data:image/svg+xml;base64,"+a.imageData,width:A.pt2px(a.width),height:A.pt2px(a.height),x:0,y:0}):this._canvasSurface.createObject(y.Path,a.path).setFill(a.color).setStroke(a.outline);"pendingRender"in this._canvasSurface&&this._canvasSurface._render(!0);var d=this._canvasSurface.rawNode.getContext("2d");e=e.getBoundingBox();var l=Math.ceil(e.width+e.x),b=Math.ceil(e.height+e.y),k=d.getImageData(e.x,e.y,l,
b);d.canvas.width=l;d.canvas.height=b;d.putImageData(k,0,0);return{type:"esriPMS",imageData:d.canvas.toDataURL("image/png").substr(22),angle:a.angle,contentType:"image/png",height:a.size?a.size:b-e.y,width:a.size?a.size:l-e.x,xoffset:a.xoffset,yoffset:a.yoffset}},_convertSvgRenderer:function(a){var e=a.type;if("simple"===e&&w(a.symbol))a.symbol=this._convertSvgToPictureMarkerSymbolJson(a.symbol);else if("unique-value"===e||"class-breaks"===e)w(a.defaultSymbol)&&(a.defaultSymbol=this._convertSvgToPictureMarkerSymbolJson(a.defaultSymbol)),
(a=a["unique-value"===e?"uniqueValueInfos":"classBreakInfos"])&&a.forEach(function(a){w(a.symbol)&&(a.symbol=this._convertSvgToPictureMarkerSymbolJson(a.symbol))},this)},_getGraphics:function(a,e){var d;a.whenLayerView(e).then(function(a){return a.queryGraphics&&a.queryGraphics()||a.featuresView.graphics}).then(function(a){d=a&&a.features||a});return d},_getPrintDefinition:function(a,e){var d=a.view,l=d.map,b=d.spatialReference,k={operationalLayers:this._createOperationalLayers(d,e)};a=this._vtlExtent||
a.extent||d.extent;b&&b.isWrappable&&(a=a.clone()._normalize(!0),b=a.spatialReference);k.mapOptions={extent:a&&a.toJSON(),spatialReference:b&&b.toJSON(),showAttribution:e.attributionVisible};this._vtlExtent=null;d.rotation&&(k.mapOptions.rotation=-d.rotation);e.preserveScale&&(k.mapOptions.scale=e.outScale||d.scale);l.timeExtent&&(k.mapOptions.time=[l.timeExtent.startTime.getTime(),l.timeExtent.endTime.getTime()]);return k},_handleExecuteResponse:function(a){return"sync"===this.mode?a.results&&a.results[0]&&
a.results[0].value:this._geoprocessor.getResultData(a.jobId,"Output_File").then(function(a){return a.value})},_setPrintParams:function(a){var e=a.template||new L;null==e.showLabels&&(e.showLabels=!0);var d=e.exportOptions,l;if(d){l={dpi:d.dpi};var b=K.toJSON(e.layout);if("map_only"===b.toLowerCase()||""===b)l.outputSize=[d.width,d.height]}var d=e.layoutOptions,k;if(d){var c,q;if("Miles"===d.scalebarUnit||"Kilometers"===d.scalebarUnit)c="Kilometers",q="Miles";else if("Meters"===d.scalebarUnit||"Feet"===
d.scalebarUnit)c="Meters",q="Feet";k={titleText:d.titleText,authorText:d.authorText,copyrightText:d.copyrightText,customTextElements:d.customTextElements,scaleBarOptions:{metricUnit:C.toJSON(c),metricLabel:B[c],nonMetricUnit:C.toJSON(q),nonMetricLabel:B[q]}}}c=null;d&&d.legendLayers&&(c=d.legendLayers.map(function(a){this._legendLayerNameMap[a.layerId]=a.title;var b={id:a.layerId};a.subLayerIds&&(b.subLayerIds=a.subLayerIds);return b},this));d=this._getPrintDefinition(a,e);if(d.operationalLayers){var f,
g=/[\u4E00-\u9FFF\u0E00-\u0E7F\u0900-\u097F\u3040-\u309F\u30A0-\u30FF\u31F0-\u31FF]/,n=/[\u0600-\u06FF]/,p=function(a){var b=a.text,c=(a=a.font)&&a.family&&a.family.toLowerCase();b&&a&&("arial"===c||"arial unicode ms"===c)&&(a.family=g.test(b)?"Arial Unicode MS":"Arial","normal"!==a.style&&n.test(b)&&(a.family="Arial Unicode MS"))};d.operationalLayers.forEach(function(a){a.featureCollection&&a.featureCollection.layers&&a.featureCollection.layers.forEach(function(a){a.layerDefinition&&a.layerDefinition.drawingInfo&&
a.layerDefinition.drawingInfo.renderer&&a.layerDefinition.drawingInfo.renderer.symbol&&(f=a.layerDefinition.drawingInfo.renderer,"esriTS"===f.symbol.type&&p(f.symbol));a.featureSet&&a.featureSet.features&&a.featureSet.features.forEach(function(a){a.symbol&&"esriTS"===a.symbol.type&&p(a.symbol)})})})}a.outSpatialReference&&(d.mapOptions.spatialReference=a.outSpatialReference.toJSON());m.mixin(d,{exportOptions:l,layoutOptions:k});m.mixin(d.layoutOptions,{legendOptions:{operationalLayers:null!=c?c:this._legendLayers}});
this._legendLayers.length=0;e={Web_Map_as_JSON:JSON.stringify(d),Format:J.toJSON(e.format),Layout_Template:b};a.extraParameters&&m.mixin(e,a.extraParameters);return e}})});