// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.31/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/_DataDrillingSupport","dojo/_base/declare dojo/aspect dojo/on esri/dijit/geoenrichment/when dojo/dom-class dojo/dom-construct dojo/dom-style dojo/query ./SimpleInfographicViewModes ../../grid/coreUtils/GridDataUtil ./dataDrilling/DataDrillingLibrary ../utils/InfographicJsonUtil esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/TooltipUtil esri/dijit/geoenrichment/utils/WaitingUtil ../../sections/SectionTypes ../../sections/sectionUtils/SectionJsonUtil ../../supportClasses/ViewModes ./DataDrillingBackgroundUtil ./DataDrillingExportUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(t,D,m,l,E,n,z,A,w,F,x,B,u,q,C,p,y,G,H,I,J,K,v,r){r=r.geoenrichment.dijit.ReportPlayer.Infographics;var h={w:700,h:600,minW:400,minH:500};t=t(null,{_drillingSections:null,_drillingSectionsButtons:null,postCreate:function(){var a=this;this.inherited(arguments);m(this.backToMainViewButton,"click",function(){a._setViewMode(w.VIEW_MAIN,!0)});q.isMobileDevice()&&this.own(m(window,"resize, orientationchange",function(){a._setViewMode(w.VIEW_MAIN,!1)}));p.hide([this.exportButton,this.printButton]);
this.viewModel.dynamicReportInfo&&(v.canExportDataDrilling(this)&&(y.setTooltipToNode(this.exportButton,r.exportInfographic),p.show(this.exportButton),m(this.exportButton,"click",function(){v.exportDataDrilling(a)})),v.canPrintDataDrilling(this)&&(y.setTooltipToNode(this.printButton,r.printInfographic),p.show(this.printButton),m(this.printButton,"click",function(){v.printDataDrilling(a)})))},_getCountryID:function(){return this.viewModel.dynamicReportInfo.infographicOptions.countryID},_addDataDrillingHandlers:function(a,
d){var c=this;this.onShowWaiting(l(x.init({variableProvider:this.viewModel.dynamicReportInfo.templateVariableProvider,countryID:this.viewModel.dynamicReportInfo.countryID}),function(){var f=F.getFieldInfo(d.getFirstCell()),b=B.getDataDrilling(c._currentInfographicJson,f.templateName),e=b&&b.sectionJson?b:null,g=(b=b&&b.isStandard&&x.getDrillingOptions(c._getCountryID(),b.standardId||f))&&b[0];if(e||g)a.getTables().forEach(function(a){a.getFieldCells().forEach(function(a){y.setTooltipToNode(a.domNode,
null)})}),c._setUpDataDrillingButton(a,function(a){a=c._setViewMode(w.VIEW_DATA_DRILLING,!0,a,e&&e.sectionJson);e?c._renderCustomSectionJson({customDDPanelInfo:e,fieldInfo:f,animationPromise:a}):c._loadStandardDataDrillingView({fieldInfo:f,optionName:g.name,calcState:null,sectionVisualState:null,animationPromise:a})})}))},_setUpDataDrillingButton:function(a,d){function c(){var b=n.create("div",{"class":"simpleInfographic_drillDataButton"},a.domNode);n.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonIcon esriGESpaceAfterBig"},
b);var d=n.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonLabel",innerHTML:r.drillForMoreData},b),c=[];a.getTables().forEach(function(a){c.push(a.domNode)});var e=p.uniteNodeBoxes(c,a.domNode);z.set(b,{left:e.x+"px",top:e.y+"px",width:e.w+"px",height:e.h+"px",lineHeight:e.h+"px"});var k=b.clientWidth;k>e.w&&z.set(b,"left",e.x-(k-e.w)/2+"px");d.style.maxWidth=k-50+"px";d.style.whiteSpace="normal";f._drillingSectionsButtons.push({destroy:function(){n.destroy(b)}});return b}var f=
this,b;if(q.isMobileDevice()){var e=function(a){b.style.opacity=a?1:0;g=a;k&&k.remove()},g=!1,k;C.addNoDragClickHandler(a.domNode,function(){g||(b=b||c(),e(!0),setTimeout(function(){k=C.addNoDragClickHandler(b,function(){e(!1);d(b)});m.once(document.body,"touchend",function(){e(!1)})}))},{detectLongPress:!0,longPressTimeout:750,ignoreReleaseIfLongPressHappened:!0,longPressCallback:function(){b=b||c();e(!0);d(b);setTimeout(function(){e(!1)})}})}else a.own(m.once(this.domNode,"mouseover",function(){b=
b||c();m(b,"click",function(){d(b)})}))},_dataDrillingState:null,_loadStandardDataDrillingView:function(a){var d=a.fieldInfo,c=a.optionName,f=a.calcState,b=a.sectionVisualState,e=a.animationPromise,g=this;this._dataDrillingState={fieldInfo:d,optionName:c,calcState:f,sectionVisualState:b};this._destroyDrillingSections();this._showDDProgress(!0);return l(function(){var a=g._getDataDrillingPanelDimensions(),b=B.getDataDrilling(g._currentInfographicJson,d.templateName),e=x.getDrillingOptionInfo(g._getCountryID(),
b.standardId||d,c,a.w,a.h,f),a=e.enrichInfos;return l(a&&a.length&&g.viewModel.enrichFieldData(a),function(){return e})}(),function(a){return l(g._renderStandardOptionInfo({drillingDataOptionInfo:a,fieldInfo:d,animationPromise:e,optionName:c,calcState:f,sectionVisualState:b}),function(){g._showDDProgress(!1)})})},_renderStandardOptionInfo:function(a){var d=a.drillingDataOptionInfo,c=a.fieldInfo,f=a.animationPromise,b=a.optionName,e=a.sectionVisualState,g=this,k;this._destroyDrillingSections();var h=
this._getDataDrillingPanelSectionParams();h.json={type:H.DETAILS,stack:[d.tableJson]};h.calculationStatesGroup=d.calculationStatesGroup;h.onCalculationStateChanged=function(a){g._loadStandardDataDrillingView({fieldInfo:c,optionName:b,calcState:a,sectionVisualState:k.getVisualState(),animationPromise:null})};return l(f,function(){return u.delay(function(){k=g._createDataDrillingSection(h);k.fitContentNicely();k.domNode.style.opacity="0.01";return l(k.getContentFullPromise(),function(){return u.delay(function(){k.setVisualState(e);
k.domNode.style.opacity="";k.notifyShown()},100)})})})},_renderCustomSectionJson:function(a){var d=a.customDDPanelInfo,c=a.animationPromise,f=a.sectionVisualState,b=this;this._destroyDrillingSections();this._dataDrillingState=null;var e,g=this._getDataDrillingPanelSectionParams(d.sectionJson);g.json=d.sectionJson;this._showDDProgress(!0);return l(c,function(){return u.delay(function(){e=b._createDataDrillingSection(g,!0);e.fitContentNicely();e.domNode.style.opacity="0.01";return l(e.getContentFullPromise(),
function(){return u.delay(function(){e.setVisualState(f);e.domNode.style.opacity="";e.notifyShown();b._showDDProgress(!1)})})})})},_getDataDrillingPanelSectionParams:function(a){var d={"class":"infographicContainer_dataDrillingSection"};d.initialWidth=this._getDataDrillingPanelDimensions(a).w;d.initialHeight=this._getDataDrillingPanelDimensions(a).h;d.viewModel=this.viewModel;d.theme=this.theme;d.parentWidget=this;d.isDataDrillingView=!0;d.currentFeatureIndex=this.currentFeatureIndex||0;d.initialViewMode=
J.PREVIEW_VALUES;n.empty(this.dynamicSettingsToolbarRoot);d.dynamicSettingsToolbarRoot=this.dynamicSettingsToolbarRoot;return d},_createDataDrillingSection:function(a,d){var c=this._getDataDrillingPanelDimensions(d&&a.json);a=this.viewModel.layoutBuilder.createElement("section",a,this.drilledDataViewDivScaler);this._drillingSections.push(a);E[A(".sectionDynamicSettings_settingsButton",this.dataDrillingViewDiv)[0]?"add":"remove"](this.dataDrillingViewDiv,"hasChartSettingsButton");this._setUpDDPanelBackgroundColor();
c.scale&&(a.notifyPanelScaleChanged(c.scale),this._applyScaleToDataDrillingToolbarButtons(c.buttonScale||c.scale),D.after(a,"onDynamicSettingsButtonsCreated",function(){this._applyScaleToDataDrillingToolbarButtons(c.buttonScale||c.scale)}.bind(this)));return a},_applyScaleToDataDrillingToolbarButtons:function(a){var d=1/a;a=[];var c=A(".sectionDynamicSettings_buttonBar",this.dynamicSettingsToolbarRoot)[0];if(c)for(var f=0;f<c.children.length;f++)a.push(c.children[f]);a.push(this.exportButton);a.push(this.printButton);
a.push(this.backToMainViewButton);a.forEach(function(a,c){a.style.transformOrigin=this.viewModel.showDataDrillingInsidePanel?"100% 0":"100% 100%";a.style.transform="scale("+d+")";a.style["webkit-transform"]="scale("+d+")";0<c&&(c=(this.viewModel.showDataDrillingInsidePanel?5:26)*d,c+=32*(d-1),a.style.marginLeft=c+"px")},this)},_setUpDDPanelBackgroundColor:function(){var a=this.viewModel.getDocumentDefaultStyles(this.theme),a=a.backgroundImage&&a.backgroundImage.data;this.viewModel.showDataDrillingInsidePanel&&
!a||K.setUpDDPanelBackgroundColor({viewModel:this.viewModel,theme:this.theme,infographicJson:this._currentInfographicJson,node:this.dataDrillingViewDiv})},_getDataDrillingPanelDimensions:function(a){if(this.viewModel.showDataDrillingInsidePanel){a=1/this._panelScale;var d=this.width/a,c=this.height/a,f=h.minW>d,b=h.minH>c;this.dataDrillingViewDiv.style.overflowX=f?"auto":"hidden";this.dataDrillingViewDiv.style.overflowY=b?"auto":"hidden";return{scale:a,buttonScale:1/a,w:Math.max(d,h.minW)-(b?p.getScrollbarSize().w/
a:0),h:Math.max(c,h.minH)-(f?p.getScrollbarSize().h/a:0)}}d=document.body.clientWidth-(q.isLandscape()?80:40);c=document.body.clientHeight-80;if(a&&1<a.stack.length)return b=I.calcSectionJsonBox(a),f=a.style&&a.style.width||Math.max(b.w,h.w),b=a.style&&a.style.height||Math.max(b.h,h.h),a=Math.min(1,d/f,c/b),q.isMobileDevice()?{w:f,h:b,scale:a,yOffset:10,animateFromCenter:!0}:{w:f,h:b,scale:a,yOffset:c-30>b?0:15};a=Math.max(.7,Math.min(1,d/h.minW,c/h.minH));return q.isMobileDevice()?{w:d/a,h:c/a,scale:a,
yOffset:10,animateFromCenter:!0}:{w:Math.min(d/a,h.w),h:Math.min(c/a,h.h),scale:a,yOffset:c-30>h.h?0:15}},_showDDProgress:function(a){G[a?"showProgress":"removeProgress"](this.viewModel.showDataDrillingInsidePanel?this.domNode:this.dataDrillingViewDiv);this.topToolbar&&(this.topToolbar.style.opacity=a?"0.001":"")},_getDataDrillingState:function(){return this._dataDrillingState},_setDataDrillingState:function(a){a&&this._loadStandardDataDrillingView({fieldInfo:a.fieldInfo,optionName:a.optionName,calcState:a.calcState,
sectionVisualState:a.sectionVisualState,animationPromise:null})},_panelScale:1,notifyPanelScaleChanged:function(a){this._panelScale=a;this.domNode.style.fontSize=13/(a||1)+"px"},_destroyDrillingSections:function(){this._drillingSections=this._drillingSections||[];this._drillingSections.forEach(function(a){a.destroy()});this._drillingSections.length=0;this.domNode&&n.empty(this.drilledDataViewDivScaler)},_destroyDrillingSectionsButtons:function(){this._drillingSectionsButtons=this._drillingSectionsButtons||
[];this._drillingSectionsButtons.forEach(function(a){a.destroy()});this._drillingSectionsButtons.length=0}});t.DATA_DRILLING_BOX_ZOOM=h;return t});