// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/assignHelper ../../../../core/Error ../../../../core/has ../../../../core/promiseUtils ../../../../geometry/support/jsonUtils ../../featureConversionUtils ../../data/DefaultSpatialIndex ../../data/projectionSupport ../../data/QueryEngine ../../../support/fieldUtils ../../../../tasks/support/Query".split(" "),function(B,C,M,D,z,E,w,t,x,F,u,G,v,y){function H(c){return t.isPoint(c)?null!=c.z:!!c.hasZ}function I(c){return t.isPoint(c)?
null!=c.m:!!c.hasM}function J(c,a){if(E("csp-restrictions"))return function(){return D({},c)};a="this."+a+" \x3d null;";for(var m in c)a+="this."+m+" \x3d "+JSON.stringify(c[m])+";";var b=new Function(a);return function(){return new b}}Object.defineProperty(C,"__esModule",{value:!0});var K={hasAttachments:!1,capabilities:"query, editing, create, delete, update",useStandardizedQueries:!0,supportsCoordinatesQuantization:!0,advancedQueryCapabilities:{supportsQueryAttachments:!1,supportsStatistics:!0,
supportsReturningGeometryCentroid:!0,supportsQueryWithDistance:!0,supportsDistinct:!0,supportsReturningQueryExtent:!0,supportsReturningGeometryProperties:!1,supportsHavingClause:!0,supportsOrderBy:!0,supportsPagination:!0,supportsQueryWithResultType:!1,supportsSqlExpression:!0}},L=function(){return function(){this.description=this.code=null}}(),r=function(){return function(c){this.error=new L;this.objectId=this.globalId=null;this.success=!1;this.uniqueId=null;this.error.description=c}}(),A=function(){return function(c){this.globalId=
null;this.success=!0;this.objectId=this.uniqueId=c}}();B=function(){function c(){this._nextObjectId=this._queryEngine=null;this._fieldsMap=new Map}c.prototype.load=function(a){var c=this,b=a.features,d=this._inferLayerProperties(b,a.fields),f=a.fields||[],e=null!=a.hasM?a.hasM:d.hasM,g=null!=a.hasZ?a.hasZ:d.hasZ,p=a.objectIdField||d.objectIdField,l=a.spatialReference||d.spatialReference;a=a.geometryType||d.geometryType;if(!l)return w.reject(new z("feature-layer:missing-property","spatialReference not set and couldn't be inferred from the provided features"));
if(!a)return w.reject(new z("feature-layer:missing-property","geometryType not set and couldn't be inferred from the provided features"));if(!p)return w.reject(new z("feature-layer:missing-property","objectIdField not set and couldn't be found in the provided fields"));if(p&&!d.objectIdField){var k=null;f.some(function(a){return a.name===p?(k=a,!0):!1})?(k.type="esriFieldTypeOID",k.editable=!1,k.nullable=!1):f.unshift({alias:p,name:p,type:"esriFieldTypeOID",editable:!1,nullable:!1})}var h={featureErrors:[],
layerDefinition:D({},K,{extent:null,geometryType:a,objectIdField:p,fields:f,hasZ:!!g,hasM:!!e})};this._queryEngine=new G.default({fields:f,geometryType:a,hasM:e,hasZ:g,objectIdField:p,spatialReference:l,spatialIndex:new F.default({geometryType:a,hasM:e,hasZ:g})});d={};this._requiredFieldNames=[];for(e=0;e<f.length;e++)g=f[e],"esriFieldTypeOID"!==g.type&&"esriFieldTypeGlobalID"!==g.type&&(a=v.getFieldDefaultValue(g),g.nullable||void 0!==a?d[g.name]=a:this._requiredFieldNames.push(g.name)),this._fieldsMap.set(g.name.trim(),
g),this._fieldsMap.set(g.name.trim().toLowerCase(),g);this._createDefaultAttributes=J(d,p);if(b&&b.length)return this._nextObjectId=1+b.reduce(function(a,b){b=b.attributes&&b.attributes[p];return null==b||isNaN(b)||!isFinite(b)?a:Math.max(a,b)},0),u.checkProjectionSupport(b,l).then(function(){return c._loadInitialFeatures(h,b)});this._nextObjectId=1;return w.resolve(h)};c.prototype.applyEdits=function(a){var c=this,b=this._queryEngine.spatialReference;return u.checkProjectionSupport(a.adds,b).then(function(){return u.checkProjectionSupport(a.updates,
b)}).then(function(){return c._applyEdits(a)})};c.prototype.queryFeatures=function(a){return this._queryEngine.executeQuery(y.fromJSON(a))};c.prototype.queryFeatureCount=function(a){return this._queryEngine.executeQueryForCount(y.fromJSON(a))};c.prototype.queryObjectIds=function(a){return this._queryEngine.executeQueryForIds(y.fromJSON(a))};c.prototype.queryExtent=function(a){return this._queryEngine.executeQueryForExtent(y.fromJSON(a))};c.prototype._inferLayerProperties=function(a,c){for(var b=void 0,
d=void 0,f=null,e=null,g=null,m=0;m<a.length;m++){var l=a[m].geometry;if(l&&(f||(f=t.getJsonType(l)),e||(e=l.spatialReference),null==b&&(b=H(l)),null==d&&(d=I(l)),f&&e&&null!=b&&null!=d))break}if(c&&c.length){var k=null;c.some(function(a){k=a;return"esriFieldTypeOID"===a.type||a.name&&"objectid"===a.name.toLowerCase()})&&(g=k.name)}return{geometryType:f,spatialReference:e,objectIdField:g,hasM:d,hasZ:b}};c.prototype._loadInitialFeatures=function(a,c){for(var b=this._queryEngine,d=b.geometryType,f=
b.hasM,e=b.hasZ,g=b.objectIdField,m=b.spatialReference,b=b.spatialIndex,l=[],k=0;k<c.length;k++){var h=c[k];if(h.geometry&&d!==t.getJsonType(h.geometry))a.featureErrors.push(new r("Incorrect geometry type."));else{var n=this._createDefaultAttributes(),q=this._mixAttributes(n,h.attributes,!1);q?a.featureErrors.push(q):(h.attributes=n,h.geometry&&(h.geometry=u.project(h.geometry,h.geometry.spatialReference,m)),l.push(h))}}b.addMany(x.convertFromFeatures([],l,d,e,f,g));a.layerDefinition.extent=this._queryEngine.fullExtent;
return a};c.prototype._applyEdits=function(a){var c=this._queryEngine.spatialIndex,b=a.adds,d=a.updates;a=a.deletes;var f={addResults:[],deleteResults:[],updateResults:[]};b&&b.length&&this._applyAddEdits(f,b);d&&d.length&&this._applyUpdateEdits(f,d);if(a&&a.length){for(b=0;b<a.length;b++)f.deleteResults.push(new A(a[b]));c.removeManyById(a)}return{fullExtent:this._queryEngine.fullExtent,featureEditResults:f}};c.prototype._applyAddEdits=function(a,c){a=a.addResults;for(var b=this._queryEngine,d=b.geometryType,
f=b.hasM,e=b.hasZ,g=b.objectIdField,m=b.spatialReference,b=b.spatialIndex,l=[],k=0;k<c.length;k++){var h=c[k];if(h.geometry&&d!==t.getJsonType(h.geometry))a.push(new r("Incorrect geometry type."));else{var n=this._createDefaultAttributes(),q=this._mixAttributes(n,h.attributes,!0);q?a.push(q):(h.attributes=n,h.geometry&&(h.geometry=u.project(h.geometry,h.geometry.spatialReference,m)),l.push(h),a.push(new A(h.attributes[g])))}}b.addMany(x.convertFromFeatures([],l,d,e,f,g))};c.prototype._applyUpdateEdits=
function(a,c){a=a.updateResults;for(var b=this._queryEngine,d=b.geometryType,f=b.hasM,e=b.hasZ,g=b.objectIdField,m=b.spatialReference,b=b.spatialIndex,l=0;l<c.length;l++){var k=c[l],h=k.attributes,n=k.geometry,k=h&&h[g];if(null==k)a.push(new r("Identifier field "+g+" missing"));else if(b.hasFeature(k)){var q=x.convertToFeature(b.getFeature(k),d,e,f);if(n)if(d!==t.getJsonType(n)){a.push(new r("Incorrect geometry type."));continue}else q.geometry=u.project(n,n.spatialReference,m);if(h&&(h=this._mixAttributes(q.attributes,
h,!1))){a.push(h);continue}b.add(x.convertFromFeature(q,d,e,f,g));a.push(new A(k))}else a.push(new r("Feature with object id "+k+" missing"))}};c.prototype._mixAttributes=function(a,c,b){for(var d in c){var f=c[d],e=this._fieldsMap.get(d);if(!e){if((e=this._fieldsMap.get(d.toLowerCase()))&&e.editable){var g=v.validateFieldValue(e,f);if(g)return new r(v.validationErrorToString(g,e,f));a[e.name]=c[d]}}else if(e.editable){if(g=v.validateFieldValue(e,f))return new r(v.validationErrorToString(g,e,f));
a[e.name]=c[d]}}d=0;for(f=this._requiredFieldNames;d<f.length;d++)if(e=f[d],void 0===a[e])return new r("missing required field "+e);d=this._queryEngine.objectIdField;b?a[d]=this._nextObjectId++:a[d]||(a[d]=c&&null!=c[d]?c[d]:this._nextObjectId++);return null};return c}();C.default=B});