// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../Viewpoint ../../../core/Accessor ../../../core/accessorSupport/decorators ../../../geometry/Point ../viewpointUtils ./ZoomBox ./actions/Pan ./actions/Pinch ./actions/Rotate".split(" "),function(A,B,p,e,q,r,c,t,f,u,v,w,x){var l=new q({targetGeometry:new t}),m=[0,0];return function(n){function a(b){b=n.call(this)||this;b._endTimer=null;b.animationManager=null;return b}p(a,n);a.prototype.initialize=
function(){this.pan=new v({navigation:this});this.rotate=new x({navigation:this});this.pinch=new w({navigation:this});this.zoomBox=new u({view:this.view,navigation:this})};a.prototype.destroy=function(){this.zoomBox.destroy();this.animationManager=this.zoomBox=null};a.prototype.begin=function(){this._set("interacting",!0)};a.prototype.end=function(){var b=this;this._endTimer&&(clearTimeout(this._endTimer),this._endTimer=0);this._endTimer=setTimeout(function(){b._set("interacting",!1)},0)};a.prototype.zoom=
function(b,d){void 0===d&&(d=this._getDefaultAnchor());this.stop();this.begin();if(this.view.constraints.snapToZoom&&this.view.constraints.effectiveLODs)return 1>b?this.zoomIn(d):this.zoomOut(d);this.setViewpoint(d,b,0,[0,0])};a.prototype.zoomIn=function(b){void 0===b&&(b=this._getDefaultAnchor());var d=this.view,a=d.scale,c=d.constraints.snapToNextScale(a);return d.goTo(this._scaleAndRotateViewpoint(l,b,c/a,0))};a.prototype.zoomOut=function(b){void 0===b&&(b=this._getDefaultAnchor());var d=this.view,
a=d.scale,c=d.constraints.snapToPreviousScale(a);return d.goTo(this._scaleAndRotateViewpoint(l,b,c/a,0))};a.prototype.setViewpoint=function(b,d,a,c){this.begin();this.view.state.viewpoint=this._scaleRotateTranslateViewpoint(this.view.viewpoint,b,d,a,c);this.end()};a.prototype.animateViewpoint=function(b,d,a){return this.view.goTo(this._scaleAndRotateViewpoint(l,b,d,a))};a.prototype.continousRotateClockwise=function(){var a=this.get("view.viewpoint");this.animationManager.animateContinous(a,function(a){f.rotateBy(a,
a,-1)})};a.prototype.continousRotateCounterclockwise=function(){var a=this.get("view.viewpoint");this.animationManager.animateContinous(a,function(a){f.rotateBy(a,a,1)})};a.prototype.resetRotation=function(){this.view.rotation=0};a.prototype.continousPanLeft=function(){var a=this.get("view.viewpoint");this.animationManager.animateContinous(a,function(a){f.translateBy(a,a,[-10,0])})};a.prototype.continousPanRight=function(){var a=this.get("view.viewpoint");this.animationManager.animateContinous(a,
function(a){f.translateBy(a,a,[10,0])})};a.prototype.continousPanUp=function(){var a=this.get("view.viewpoint");this.animationManager.animateContinous(a,function(a){f.translateBy(a,a,[0,10])})};a.prototype.continousPanDown=function(){var a=this.get("view.viewpoint");this.animationManager.animateContinous(a,function(a){f.translateBy(a,a,[0,-10])})};a.prototype.stop=function(){this.pan.stopMomentumNavigation();this.animationManager.stop();this.end();this._endTimer&&(clearTimeout(this._endTimer),this._endTimer=
0)};a.prototype._getDefaultAnchor=function(){var a=this.view.size;m[0]=.5*a[0];m[1]=.5*a[1];return m};a.prototype._scaleAndRotateViewpoint=function(a,d,c,e){var b=this.view,z=b.size,y=b.padding,h=b.constraints,g=b.viewpoint,k=b.scale*c,b=h.canZoomInTo(k),h=h.canZoomOutTo(k);return 1>c&&!b||1<c&&!h?g:f.padAndScaleAndRotateBy(a,g,c,e,d,z,y)};a.prototype._scaleRotateTranslateViewpoint=function(a,d,c,e,l){var b=this.view,m=b.size,h=b.padding,g=b.constraints,k=b.viewpoint,n=b.scale*c,b=g.canZoomInTo(n),
g=g.canZoomOutTo(n);if(1>c&&!b||1<c&&!g)c=1;f.translateBy(k,k,l);return f.padAndScaleAndRotateBy(a,k,c,e,d,m,h)};e([c.property()],a.prototype,"animationManager",void 0);e([c.property({type:Boolean,readOnly:!0})],a.prototype,"interacting",void 0);e([c.property()],a.prototype,"pan",void 0);e([c.property()],a.prototype,"pinch",void 0);e([c.property()],a.prototype,"rotate",void 0);e([c.property()],a.prototype,"view",void 0);e([c.property()],a.prototype,"zoomBox",void 0);return a=e([c.subclass("esri.views.2d.navigation.MapViewNavigation")],
a)}(c.declared(r))});