// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../lib/gl-matrix ../../support/debugFlags ./Camera ./ComponentUtils ./DefaultVertexBufferLayouts ./glUtil3D ./HighlightUtils ./Renderer ./RenderPass ./SliceHelper ./Util ../lighting/Lightsources ../materials/internal/TexOnlyGLMaterial ../../../webgl/FramebufferObject ../../../webgl/Texture ../../../webgl/Util".split(" "),function(r,I,m,t,w,u,x,y,z,A,q,B,C,D,E,F,G,H){r=function(){function c(a,b,f,d,c,e){var g=this;this._renderTargets={};this._clearColor=m.vec4d.createFrom(0,
0,0,0);this._id2origin={};this._uniqueIdx=0;this._rctx=a;this._canvas=b;this._programRep=f;this._modelDirtySet=e;this._modelDirtySet.onMaterialChanged=function(a){return g.materialChanged(a)};this._renderer=new A(f,d,c,this._rctx,!0);this._sliceHelper=new B;this._renderer.onHasHighlightsChanged=function(a){if(g.onHasHighlightsChanged)g.onHasHighlightsChanged(a)};this._renderer.setLighting({lights:[new D.AmbientLight(m.vec3d.createFrom(1,1,1))],groundLightingFactor:1,globalFactor:0})}c.prototype.dispose=
function(){for(var a in this._renderTargets)this._renderTargets[a].dispose();this._renderTargets=null;this._renderer.dispose();this._renderer=null};c.prototype.createRenderTarget=function(a){return this.createRenderTargetInternal(a,!0)};c.prototype.createHighlightRenderTarget=function(a){return this.createRenderTargetInternal(a,!1)};c.prototype.disposeRenderTarget=function(a){var b=this._renderTargets[a];b&&b.dispose();delete this._renderTargets[a]};c.prototype.getRenderTargetTexture=function(a){return(a=
this._renderTargets[a])?a.colorTexture:null};c.prototype.addRenderGeometries=function(a){var b=this;a.forEach(function(a){null==a.origin&&(a.origin=b.getOrigin(a.center,a.bsRadius));a.idx=b._uniqueIdx++});this._renderer.modify(a,[]);if(this.onContentChanged)this.onContentChanged()};c.prototype.removeRenderGeometries=function(a){this._renderer.modify([],a);if(this.onContentChanged)this.onContentChanged()};c.prototype.updateRenderGeometries=function(a,b){a=a.map(function(a){return{renderGeometry:a,
updateType:b}});this._renderer.modify([],[],a);if(this.onContentChanged)this.onContentChanged()};c.prototype.updateRenderOrder=function(a){if(0<a.size&&(this._renderer.modifyRenderOrder(a),this.onContentChanged))this.onContentChanged()};c.prototype.setBackgroundColor=function(a){this._clearColor=a;if(this.onContentChanged)this.onContentChanged()};c.prototype.addRenderGeometryHighlight=function(a,b){var f=a.instanceParameters,d=z.generateHighlightId();f.componentHighlights=u.addHighlight(f.componentHighlights,
null,b,d);this.updateRenderGeometries([a],32);return d};c.prototype.removeRenderGeometryHighlight=function(a,b){var f=a.instanceParameters;f.componentHighlights=u.removeHighlight(f.componentHighlights,b);this.updateRenderGeometries([a],32)};c.prototype.isEmpty=function(){return this._renderer.isEmpty()&&!t.OVERLAY_DRAW_TEST_TEXTURE};c.prototype.processDirtyMaterials=function(){var a=this._modelDirtySet.getDirtyMaterials();a&&this._renderer.modify([],[],[],a);this._modelDirtySet.clearDirtyMaterials()};
Object.defineProperty(c.prototype,"hasHighlights",{get:function(){return this._renderer.hasHighlights},enumerable:!0,configurable:!0});c.prototype.draw=function(a,b){return this.drawPass(q.MATERIAL,a,b)};c.prototype.drawHighlights=function(a,b){return this.drawPass(q.MATERIAL_HIGHLIGHT,a,b)};c.prototype.drawPass=function(a,b,f){if(this.isEmpty()||a===q.MATERIAL_HIGHLIGHT&&!this.hasHighlights)return!1;this.processDirtyMaterials();if(!f.views.some(function(a){return a.extent[0]!==a.extent[2]&&a.extent[1]!==
a.extent[3]}))return!1;b=this._renderTargets[b];if(!b)return!1;var d=this._rctx,c=d.gl,e=f.width,g=f.height;if(b.width!==e||b.height!==g)b.resize(e,g),b.colorTexture.setSamplingMode(9729);var h=l.camera;l.fbo=b;l.pixelRatio=f.pixelRatio||1;h.near=1;h.far=1E4;d.bindFramebuffer(b);d.setDepthTestEnabled(!1);d.setBlendFunctionSeparate(770,771,1,771);d.setClearColor.apply(d,this._clearColor);d.clear(c.COLOR_BUFFER_BIT);for(c=0;c<f.views.length;c++){var k=f.views[c];h.viewport=k.viewport;m.mat4d.ortho(0,
k.extent[2]-k.extent[0],0,k.extent[3]-k.extent[1],h.near,h.far,h.projectionMatrix);m.mat4d.identity(h.viewMatrix);m.mat4d.translate(h.viewMatrix,[-k.extent[0],-k.extent[1],0]);h.setGLViewport(this._rctx);t.OVERLAY_DRAW_TEST_TEXTURE&&this._drawTestTexture(e,g,v[f.index%v.length]);this._renderer.renderGeometryPass(a,l,null,null,this._sliceHelper)}d.setDepthTestEnabled(!0);d.setBlendFunctionSeparate(770,771,1,771);d.bindFramebuffer(null);d.setViewport(0,0,this._canvas.width,this._canvas.height);b.colorTexture.descriptor.hasMipmap&&
b.colorTexture.generateMipmap();return!0};c.prototype._drawTestTexture=function(a,b,f){var c=this._rctx,l=c.gl;if(!this._testPatternMat){for(var e=new Uint8Array(a*b*4),g=0,h=0;h<b;h++)for(var k=0;k<a;k++){var n=Math.floor(k/10),p=Math.floor(h/10);2>n||2>p||10*n>a-20||10*p>b-20?(e[g++]=255,e[g++]=255,e[g++]=255,e[g++]=255):(e[g++]=255,e[g++]=255,e[g++]=255,n&1&&p&1?e[g++]=k&1^h&1?0:255:e[g++]=n&1^p&1?0:128)}a=new G(c,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:a,height:b},
e);this._testPatternMat=new E(this._programRep,a,[1,1,1,1],!0,l.ALWAYS);this._testPatternBindParams={proj:m.mat4d.identity(),view:m.mat4d.identity(),nearFar:[-1,1],origin:[0,0,0],viewInvTransp:null,viewport:null,lightingData:null,fovY:0};this._quadVAO=y.createQuadVAO(c,x.Pos3Tex)}this._testPatternMat.setColor([f[0],f[1],f[2],1]);this._testPatternMat.bind(c,this._testPatternBindParams);this._testPatternMat.bindView(c,this._testPatternBindParams);c.bindVAO(this._quadVAO);c.drawArrays(5,0,H.vertexCount(this._quadVAO,
"geometry"));this._testPatternMat.release(c)};c.prototype.getOrigin=function(a,b){var c=0;b=10*b/1E4;1<b&&(c=Math.ceil(C.logWithBase(b,2)));b=1E4*Math.pow(2,c);var d=Math.round(a[0]/b),l=Math.round(a[1]/b);a=Math.round(a[2]/b);var c=c+"_"+d+"_"+l+"_"+a,e=this._id2origin[c];null==e&&(e={vec3:m.vec3d.createFrom(d*b,l*b,a*b),id:c},this._id2origin[c]=e);return e};c.prototype.materialChanged=function(a){if(this.onContentChanged)this.onContentChanged()};c.prototype.createRenderTargetInternal=function(a,
c){for(var b=a,d=0;this._renderTargets[b];)b=a+"_"+ ++d;this._renderTargets[b]=F.createWithAttachments(this._rctx,{target:3553,pixelFormat:6408,dataType:5121,wrapMode:33071,samplingMode:9987,hasMipmap:c,maxAnisotropy:8,width:0,height:0},{colorTarget:0,depthStencilTarget:0});return b};return c}();var v=[[1,.5,.5],[.5,.5,1],[.5,1,.5]],l={fbo:null,camera:new w,pixelRatio:1};return r});