// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/iteratorUtils ../../lib/gl-matrix ../../support/buffer/glUtil ./ComponentUtils ./DefaultVertexAttributeLocations ./Float32ArrayList ./FxaaRenderPass ./HighlightTextureHelper ./InstanceBufferData ./IntervalUtilities ./LinearDepthTextureHelper ./NormalTextureHelper ./RenderContext ./RenderPass ./RenderPluginManager ./RenderSlot ./SmaaRenderPass ./StencilRenderingHelper ./Util ./edgeRendering/EdgeView ../lighting/SceneLighting ../materials/HUDMaterial ../../../webgl/BufferObject ../../../webgl/Profiling ../../../webgl/Texture ../../../webgl/Util ../../../webgl/VertexArrayObject".split(" "),
function(Y,sa,U,A,N,Z,S,aa,da,ea,fa,ba,ga,ha,ia,B,ja,w,ka,la,D,ma,na,oa,O,pa,ca,E,P){function T(e){return e.instanceParameters.hidden?[]:Z.generateVisibleIndexRanges(e.instanceParameters.componentVisibilities,e.componentOffsets)}function V(e,a,b){var c=e.origin.vec3;D.setMatrixTranslation3(L,-c[0],-c[1],-c[2]);A.mat4d.multiply(L,e.transformation,a);A.mat4d.inverse(a,b);A.mat4d.transpose(b)}function I(e,a,b){for(var c in e){var d=e[c];a(c,d);d.origin2data.forEach(function(a,c){b(c,a)})}}function W(e){return!1===
e.preinterleaved?D.getFirstObjectValue(e.indices).length:e.indexCount}var M=A.mat4d.identity();Y=function(){function e(a,b,c,d,h){this._lighting=new na.SceneLighting;this._mat2DataMerged={};this._mat2DataInstanced={};this._mat2DataPreinterleaved={};this._renderOrder=[];this._renderContext=new ia;this._isRendering=!1;this._highlights=[];this._threshold=1535;this._needsRender=!0;this._fallbackDepthStencilTexture=null;this._stats=new qa;this._edgeView=null;this.ssaoEnabled=this._edgeViewLoaded=!1;this.renderOptions=
{antialiasing:"smaa",earlyOcclusionPixelDraw:!1};this._programRep=a;this._materialRep=b;this._orderedRendering=h;this._rctx=d;this._fxaaPass=new da(d);this._smaaPass=new ka(d);this._renderContext.rctx=d;this._renderContext.lightingData=this._lighting.getOld();d.setDepthTestEnabled(!0);d.setFaceCullingEnabled(!0);d.setBlendingEnabled(!1);d.setBlendFunctionSeparate(770,771,1,771);this._bindParameters={view:null,proj:null,viewInvTransp:null,fovY:0,nearFar:null,lightingData:null,viewport:null,framebufferTex:null,
shadowMappingEnabled:!1,ssaoEnabled:!1,origin:null,pixelRatio:null,slicePlane:null};this._linearDepthTextureHelper=new ga(d);this._normalTextureHelper=new ha(d);this._highlightTextureHelper=new ea(d);this._stencilRenderingHelper=new la(d);this._renderPlugins=new ja.RenderPluginManager({rctx:d,gl:d.gl,programRep:a,textureRep:c,materialRep:b});this._initializeFramebufferTexture()}e.prototype._initializeFramebufferTexture=function(){var a=this._rctx.gl,a=this._rctx.contextAttributes.alpha?a.RGBA:a.RGB,
b=new ca(this._rctx,{target:3553,pixelFormat:a,dataType:5121,samplingMode:9728,wrapMode:33071,width:4,height:4});this._framebuffer={format:a,texture:b}};e.prototype.dispose=function(){var a=this,b=function(b){a._releaseMaterials(b)},c=function(a,b){if(b.type===t.Preinterleaved)for(var c in b.instances)b.instances[c].vao.dispose(!0);else b.vao.dispose(!0)};I(this._mat2DataMerged,b,c);I(this._mat2DataInstanced,b,c);I(this._mat2DataPreinterleaved,b,c);this._mat2DataPreinterleaved=this._mat2DataInstanced=
this._mat2DataMerged=null;this._framebuffer.texture.dispose();this._framebuffer.texture=null;this._linearDepthTextureHelper.enabled=!1;this._normalTextureHelper.enabled=!1;this._stencilRenderingHelper.enabled=!1;this._fallbackDepthStencilTexture&&(this._fallbackDepthStencilTexture.dispose(),this._fallbackDepthStencilTexture=null);this._highlightTextureHelper&&(this._highlightTextureHelper.dispose(),this._highlightTextureHelper=null)};Object.defineProperty(e.prototype,"isLoadingResources",{get:function(){return"smaa"===
this.renderOptions.antialiasing&&this._smaaPass.isLoadingResources},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"edgeView",{get:function(){var a=this;this._edgeViewLoaded||(this._edgeViewLoaded=!0,this._edgeView=new ma.EdgeView(this._rctx,this._programRep,{setNeedsRender:function(){a._needsRender=!0}}),this._edgeView.initialize());return this._edgeView},enumerable:!0,configurable:!0});e.prototype.setLighting=function(a){this._lighting.set(a)};Object.defineProperty(e.prototype,
"renderPlugins",{get:function(){return this._renderPlugins},enumerable:!0,configurable:!0});e.prototype.resetNeedsRender=function(){this._needsRender=!1;this._renderPlugins.resetNeedsRender()};e.prototype.needsRender=function(){return this._needsRender||this._renderPlugins.needsRender()};e.prototype.getCombinedStats=function(){var a=this;this._stats.VBOallocatedSize=0;this._stats.VBOoptimalSize=0;this._stats.VBOusedSize=0;var b=function(){},c=function(b,c){if(c.type===t.Preinterleaved)for(var d in c.instances)b=
c.instances[d].vao.size,a._stats.VBOallocatedSize+=b/4,a._stats.VBOusedSize+=b/4,a._stats.VBOoptimalSize+=b/4;else a._stats.VBOallocatedSize+=c.buffer.getArray().length,a._stats.VBOusedSize+=c.buffer.getSize(),a._stats.VBOoptimalSize+=c.optimalCount};I(this._mat2DataMerged,b,c);I(this._mat2DataInstanced,b,c);I(this._mat2DataPreinterleaved,b,c);this._stats.VBOallocatedSize*=.00390625;this._stats.VBOusedSize*=.00390625;this._stats.VBOoptimalSize*=.00390625;return this._stats};e.prototype.getFramebufferTexture=
function(a){switch(a){case "linearDepth":return this._linearDepthTextureHelper.framebuffer.colorTexture;case "normals":return this._normalTextureHelper.framebuffer.colorTexture}return null};e.prototype._addHighlight=function(a){var b=this._getInstance(a);if(null===b)console.error("No instance found for RenderGeometry {name: '"+a.name+"', uniqueName: '"+a.uniqueName+"'}");else if(this._highlights.push(b),this._orderedRendering&&this._sortHighlightsByRenderOrder(),this._needsRender=!0,this.onHasHighlightsChanged)this.onHasHighlightsChanged(this.hasHighlights)};
e.prototype._removeHighlight=function(a){var b=this._highlights.length;this._highlights=this._highlights.filter(function(b){return b.uniqueName!==a.uniqueName});if(b!==this._highlights.length){if(this.onHasHighlightsChanged)this.onHasHighlightsChanged(this.hasHighlights);this._needsRender=!0}};Object.defineProperty(e.prototype,"hasHighlights",{get:function(){return 0<this._highlights.length},enumerable:!0,configurable:!0});e.prototype._renderHUDVisibility=function(a){var b=this,c=oa.shouldRenderVisibilityDuringRenderPass(a.pass),
d=a.offscreenRenderingHelper&&a.offscreenRenderingHelper.enabled,h=!1;c&&d&&a.offscreenRenderingHelper.renderHUDVisibility(function(){h=b._renderInternalSlot(w.OCCLUSION_PIXELS,a)});return h};e.prototype.renderGeometrySlotsPt1=function(a){this._renderPlugins.render(w.INTERNAL_MATERIAL,a);this._renderInternalSlot(w.STENCIL_MATERIAL,a);this._renderPlugins.render(w.OPAQUE_TERRAIN,a);this._renderInternalSlot(w.OPAQUE_MATERIAL,a);this._renderPlugins.render(w.OPAQUE_EXTERNAL,a);a.ssaoHelper&&a.ssaoHelper.bindAll(this._programRep);
this._renderPlugins.render(w.POSTPROCESSING_ATMOSPHERE_OPAQUE,this._renderContext);this._renderInternalSlot(w.TRANSPARENT_MATERIAL,a);this.renderOptions.earlyOcclusionPixelDraw&&(this._renderHUDVisibility(a),this._renderInternalSlot(w.LINE_CALLOUTS,this._renderContext));this._renderPlugins.render(w.TRANSPARENT_EXTERNAL,a);a.ssaoHelper&&a.ssaoHelper.bindAll(this._programRep)};e.prototype.renderTransparentTerrain=function(a){return this._renderPlugins.render(w.TRANSPARENT_TERRAIN,a)};e.prototype.renderGeometrySlots=
function(a){this.renderGeometrySlotsPt1(a);this.renderTransparentTerrain(a)};e.prototype.renderHUD=function(a){this._bindParameters.renderTransparentlyOccludedHUD=a;this._renderInternalSlot(w.LINE_CALLOUTS_HUD_DEPTH,this._renderContext);this._renderInternalSlot(w.HUDMATERIAL1,this._renderContext);this._renderInternalSlot(w.HUDMATERIAL2,this._renderContext)};e.prototype._renderHighlights=function(a,b){if(b&&b.enabled&&(this.hasHighlights||this._renderPlugins.needsHighlight())){var c=null;b.profilingCallback&&
(c=pa.startMeasurement(this._renderContext.rctx));var d=a.fbo;this._highlightTextureHelper.prepareHighlightPass(a.camera);this.renderGeometryPass(B.MATERIAL_HIGHLIGHT,a,null,null,this._renderContext.sliceHelper);this._rctx.clear(this._rctx.gl.DEPTH_BUFFER_BIT);this.renderHUD("both");this._highlightTextureHelper.finish(d);b.render(a,this._highlightTextureHelper.framebuffer);null!==c&&b.profilingCallback&&c.stop(function(a){b.profilingCallback&&b.profilingCallback(a)})}};e.prototype._needsRenderOccluded=
function(a){for(var b in this._mat2DataInstanced){var c=this._mat2DataInstanced[b][0];if(c&&c.renderOccluded&&c.beginSlot(a)&&c.isVisible())return!0}return!1};e.prototype._renderOccluded=function(a,b,c){if(b&&c&&c.enabled){var d=this._needsRenderOccluded(w.OPAQUE_MATERIAL)||this._needsRenderOccluded(w.TRANSPARENT_MATERIAL);if(b.enabled=d)d=this._renderContext,b.setupFBOs(a),b.prepareColorPass(),d.pass=B.MATERIAL,d.renderOccludedOnly=!0,this._renderInternalSlot(w.OPAQUE_MATERIAL,d),this._renderInternalSlot(w.TRANSPARENT_MATERIAL,
d),d.renderOccludedOnly=!1,b.finish(c.framebuffer),b.apply()}};e.prototype._renderUnordered=function(a,b,c){var d=this,h=this._rctx;this._isRendering=!0;this._stats.reset();var f=a.camera,n=a.fbo,k=a.pixelRatio;this._updateGlobalUniforms(f.projectionMatrix);this._renderContext.pass=B.MATERIAL;this._renderContext.camera=f;this._renderContext.pixelRatio=k;this._renderContext.shadowMap=b;this._renderContext.sliceHelper=c.slice;this._renderContext.ssaoHelper=c.ssao;this._renderContext.offscreenRenderingHelper=
c.offscreenRendering;this._renderContext.stencilRenderingHelper=this._stencilRenderingHelper;this._renderContext.depth=this._linearDepthTextureHelper.framebuffer;this._renderContext.normals=this._normalTextureHelper.framebuffer;this._renderContext.highlight=this._highlightTextureHelper.framebuffer;this._renderContext.options=this.renderOptions;c.offscreenRendering.enabled=!0;c.offscreenRendering.initializeFrame(f,n);this._renderPlugins.render(w.BACKGROUND,this._renderContext);this.renderGeometrySlotsPt1(this._renderContext);
this._edgeView&&this.edgeView.shouldRender()&&c.offscreenRendering.renderSeparateAndComposite(function(){d._edgeView.render(d._bindParameters)},void 0,"alpha");k=b=!1;this.renderOptions.earlyOcclusionPixelDraw||(b=this._renderHUDVisibility(this._renderContext),this._renderInternalSlot(w.LINE_CALLOUTS,this._renderContext));(k=this.renderTransparentTerrain(this._renderContext))&&b&&(c.offscreenRendering.compositeTransparentTerrainOntoHUDVisibility(),c.offscreenRendering.renderToTargets(function(){return d.renderHUD("occluded")},
c.offscreenRendering.mainColor,c.offscreenRendering.tmpDepth,void 0,!0));k&&c.offscreenRendering.compositeTransparentTerrainOntoMain();c.offscreenRendering.renderToTargets(function(){d._renderPlugins.render(w.POSTPROCESSING_ATMOSPHERE_TRANSPARENT,d._renderContext);d._renderPlugins.render(w.POSTPROCESSING_EXTERNAL,d._renderContext);d._renderOccluded(f,c.renderOccluded,c.offscreenRendering)},c.offscreenRendering.mainColor,c.offscreenRendering.mainDepth);b=this.renderOptions.antialiasing;"smaa"===b&&
this._smaaPass.loadResources(function(){d._needsRender=!0});"smaa"===b&&this._smaaPass.enable()?(this._fxaaPass.disable(),this._smaaPass.render({colorTexture:c.offscreenRendering.colorTexture},n)):"fxaa"===b&&this._fxaaPass.enable()?(this._smaaPass.disable(),this._fxaaPass.render({colorTexture:c.offscreenRendering.colorTexture},n)):(c.offscreenRendering.composite(),this._fxaaPass.disable(),this._smaaPass.disable());h.bindFramebuffer(n);this._renderContext.framebufferTex=c.offscreenRendering.colorTexture;
this.renderHUD("notOccluded");this._renderHighlights(a,c.highlight);this._isRendering=!1};e.prototype._renderGeometryPassOrderedHighlight=function(a){this._renderInternalHighlights()};e.prototype._renderGeometryPassOrderedMaterial=function(a){for(var b=null,c=0;c<this._renderOrder.length;c++){var d=this._renderOrder[c][1];if(d.instanced){var h=d.instanced||d.merged,f=h[a.pass];f&&f.isVisible()&&(this._renderInternalInstanced(h,f,this._bindParameters,Infinity),b=null)}d.merged&&(h=d.merged,(f=h[a.pass])&&
f.isVisible()&&(d=f.getProgram(),d!==b&&(d.setUniformMatrix4fv("model",M),d.hasUniform("modelNormal")&&d.setUniformMatrix4fv("modelNormal",M)),b=d,this._renderInternalMerged(h,f,this._bindParameters,Infinity)))}};e.prototype._renderGeometryPassOrdered=function(a){var b=a.camera;this._bindParameters.view=b.viewMatrix;this._bindParameters.proj=b.projectionMatrix;this._bindParameters.viewInvTransp=b.viewInverseTransposeMatrix;K[0]=b.near;K[1]=b.far;this._bindParameters.nearFar=K;this._bindParameters.lightingData=
a.lightingData;this._bindParameters.viewport=b.fullViewport;this._bindParameters.framebufferTex=this._framebuffer.texture;this._bindParameters.pixelRatio=a.pixelRatio;this._bindParameters.slicePlane=a.sliceHelper&&a.sliceHelper.plane;a.isHighlightPass?this._renderGeometryPassOrderedHighlight(a):this._renderGeometryPassOrderedMaterial(a)};e.prototype._renderOrdered=function(a,b){this._stats.reset();this.renderGeometryPass(a,b)};e.prototype.prepareRender=function(a){this._renderPlugins.prepareRender(a);
this._renderContext.rctx.setDepthFunction(513)};e.prototype.render=function(a,b){this._orderedRendering?this._renderOrdered(B.MATERIAL,a):this._renderUnordered(a,b.shadowMap,b)};e.prototype.renderAuxiliaryBuffers=function(a,b){var c=b.ssao,d=b.slice;b=b.shadowMap;var h=this.ssaoEnabled||this._renderPlugins.needsLinearDepth(),f=a.camera,n=a.fbo;if(this._linearDepthTextureHelper.enabled=h)this._linearDepthTextureHelper.setupFBOs(f),this._linearDepthTextureHelper.prepareDepthPass(),this.renderGeometryPass(B.MATERIAL_DEPTH,
a,b,c,d),this._linearDepthTextureHelper.finish(n);if(this._normalTextureHelper.enabled=this.ssaoEnabled)this._normalTextureHelper.setupFBOs(f),this._normalTextureHelper.prepareNormalPass(),this.renderGeometryPass(B.MATERIAL_NORMAL,a,b,c,d),this._normalTextureHelper.finish(n),c.computeSSAO(f,n,this._linearDepthTextureHelper.framebuffer,this._normalTextureHelper.framebuffer);c.bindAll(this._programRep)};e.prototype.renderGeometryPass=function(a,b,c,d,h){this._isRendering=!0;var f=b.camera;b=b.pixelRatio;
this._updateGlobalUniforms(f.projectionMatrix);this._renderContext.pass=a;this._renderContext.camera=f;this._renderContext.pixelRatio=b;this._renderContext.shadowMap=c;this._renderContext.ssaoHelper=d;this._renderContext.depth=this._linearDepthTextureHelper.framebuffer;this._renderContext.normals=this._normalTextureHelper.framebuffer;this._renderContext.sliceHelper=h;this._orderedRendering?this._renderGeometryPassOrdered(this._renderContext):this._renderGeometryPassUnordered(this._renderContext);
this._isRendering=!1};e.prototype._renderGeometryPassUnordered=function(a){this.renderGeometrySlots(a)};e.prototype._renderInternalHighlights=function(a){void 0===a&&(a=null);for(var b=!1,c=0;c<this._highlights.length;++c){var d=this._highlights[c],h=d.matData[B.MATERIAL_HIGHLIGHT];h&&(null===a||h.beginSlot(a))&&h.isVisible()&&(b=this._renderInternalHighlight(d,this._bindParameters,B.MATERIAL_HIGHLIGHT)||b)}return b};e.prototype._renderInternalSlotOccluded=function(a,b){var c=!1,d;for(d in this._mat2DataInstanced){var h=
this._mat2DataInstanced[d],f=h[b.pass];f&&f.renderOccluded&&f.beginSlot(a)&&f.isVisible()&&(c=this._renderInternalInstanced(h,f,this._bindParameters,a)||c)}return c};e.prototype._renderInternalSlotMaterial=function(a,b){var c=!1,d;for(d in this._mat2DataInstanced){var h=this._mat2DataInstanced[d],f=h[b.pass];f&&f.beginSlot(a)&&f.isVisible()&&(c=this._renderInternalInstanced(h,f,this._bindParameters,a)||c)}for(var h=this._programRep.getProgramsUsingUniform("model"),f=this._programRep.getProgramsUsingUniform("modelNormal"),
n=0;n<h.length;n++){var k=h[n];k.setUniformMatrix4fv("model",M);-1<f.indexOf(k)&&k.setUniformMatrix4fv("modelNormal",M)}for(d in this._mat2DataMerged)h=this._mat2DataMerged[d],(f=h[b.pass])&&f.beginSlot(a)&&f.isVisible()&&(c=this._renderInternalMerged(h,f,this._bindParameters,a)||c);for(d in this._mat2DataPreinterleaved)h=this._mat2DataPreinterleaved[d],(f=h[b.pass])&&f.beginSlot(a)&&f.isVisible()&&(c=this._renderInternalPreinterleaved(h,f,this._bindParameters,a)||c);a===w.STENCIL_MATERIAL&&this._stencilRenderingHelper.finish();
return c};e.prototype._renderInternalSlotHighlights=function(a,b){return this._renderInternalHighlights(a)};e.prototype._renderInternalSlot=function(a,b){this._bindParameters.view=b.camera.viewMatrix;this._bindParameters.proj=b.camera.projectionMatrix;this._bindParameters.viewInvTransp=b.camera.viewInverseTransposeMatrix;this._bindParameters.cameraAboveGround=b.camera.aboveGround;this._bindParameters.fovY=b.camera.fovY;K[0]=b.camera.near;K[1]=b.camera.far;var c=this._renderContext.offscreenRenderingHelper;
this._bindParameters.nearFar=K;this._bindParameters.lightingData=b.lightingData;this._bindParameters.viewport=b.camera.fullViewport;this._bindParameters.framebufferTex=c?c.colorTexture:null;this._bindParameters.shadowMap=b.shadowMap;this._bindParameters.shadowMappingEnabled=!!b.shadowMap&&b.shadowMap.enabled;this._bindParameters.ssaoEnabled=!!b.ssaoHelper&&b.ssaoHelper.enabled;this._bindParameters.pixelRatio=b.pixelRatio;this._bindParameters.slicePlane=b.sliceHelper&&b.sliceHelper.plane;this._bindParameters.hudVisibilityTexture=
c?c.hudVisibilityTexture:null;return b.isHighlightPass?this._renderInternalSlotHighlights(a,b):b.renderOccludedOnly?this._renderInternalSlotOccluded(a,b):this._renderInternalSlotMaterial(a,b)};e.prototype._renderInternalInstanced=function(a,b,c,d){var h=this,f=this._rctx,n=f.gl,k=!1,l=b.getDrawMode(f),g=f.capabilities.instancing,e=!1;a.origin2data.forEach(function(a){c.origin=a.origin;d===w.STENCIL_MATERIAL&&(h._stencilRenderingHelper.enabled=!0,h._stencilRenderingHelper.prepareStencilWritePass());
var m=!1;if(b.instanced)for(var p in a.perGeometryDataInfo){var u=a.perGeometryDataInfo[p];k||(b.bind(f,c),k=!0);f.bindVAO(u.vao);var G=b.getProgram();E.assertCompatibleVertexAttributeLocations(u.vao,G);m||(b.bindView(f,c),m=!0);var G=u.to-u.from,t=u.refCount;l===n.TRIANGLES&&(h._stats.trianglesRendered+=t*G/3);g.drawArraysInstanced(l,u.from,G,t);e=!0;h._stats.drawCallsAngleInstanced++;h._stats.instancesDrawnAngle+=t}else for(u in p=a.instances,p)G=p[u],t=G.displayedIndexRange,t&&0===t.length||(k||
(b.bind(f,c),k=!0),m||(f.bindVAO(a.vao),b.bindView(f,c),m=!0),b.bindInstance(f,G),h._stats.drawCallsInstanced++,l===n.TRIANGLES&&(h._stats.trianglesRendered+=(G.to-G.from)/3),t?h._drawArraysFaceRange(t,G.from,l):f.drawArrays(l,G.from,G.to-G.from),e=!0)});f.bindVAO(null);k&&b.release(f,c);return e};e.prototype._renderInternalHighlight=function(a,b,c){var d=this._rctx,h=d.gl;c=a.matData[c];var f=c.getDrawMode(d),n=a.instance,k=n.highlightedIndexRange,e=this._renderContext.offscreenRenderingHelper,e=
(e?e.depthTexture:null)||this._getFallbackDepthTexture(),g=c.getProgram(),p=d.capabilities.instancing;b.origin=a.originData.origin;var m=!1;if(c.instanced&&a.type===t.Instanced)for(a=a.instancedVAO,c.bind(d,b),d.bindVAO(a),E.assertCompatibleVertexAttributeLocations(a,g),c.bindView(d,b),a=0;a<k.length;a++){var q=k[a],m=q.range?q.range[0]+n.from:n.from,q=q.range?q.range[1]-q.range[0]+1:n.to-n.from;d.bindTexture(e,5);g.setUniform1i("depthTex",5);g.setUniform4f("highlightViewportPixelSz",0,0,1/this._bindParameters.viewport[2],
1/this._bindParameters.viewport[3]);p.drawArraysInstanced(f,m,q,1);f===h.TRIANGLES&&(this._stats.trianglesRendered+=1*q/3);this._stats.drawCallsHighlight++;m=!0}else if(a.type===t.Instanced&&c.instanced)console.error("_renderInternalHighlight: incompatible instance type");else{c.bind(d,b);c.bindView(d,b);p=null;switch(a.type){case t.Merged:q=a.originData;d.bindVAO(q.vao);g.setUniformMatrix4fv("model",M);break;case t.Instanced:q=a.originData;d.bindVAO(q.vao);c.bindInstance(d,n);break;case t.Preinterleaved:q=
a.originData,a=q.instances[a.uniqueName].vao,d.bindVAO(a),c.bindInstance(d,n),p=a.indexBuffer&&a.indexBuffer.indexType}for(a=0;a<k.length;a++){q=k[a];m=q.range?q.range[0]+n.from:n.from;q=q.range?q.range[1]-q.range[0]+1:n.to-n.from;d.bindTexture(e,5);c.getProgram().setUniform1i("depthTex",5);g.setUniform4f("highlightViewportPixelSz",0,0,1/this._bindParameters.viewport[2],1/this._bindParameters.viewport[3]);if(p){var r=E.getBytesPerElement(p);d.drawElements(f,q,p,m*r)}else d.drawArrays(f,m,q);f===h.TRIANGLES&&
(this._stats.trianglesRendered+=q/3);this._stats.drawCallsHighlight++;m=!0}}d.bindVAO(null);c.release(d,b);return m};e.prototype._drawArraysFaceRange=function(a,b,c){for(var d=this._rctx,h=0;h<a.length;h++){var f=a[h];d.drawArrays(c,f[0]+b,f[1]-f[0]+1)}this._stats.drawCallsFragmented+=a.length-1};e.prototype._drawElementsFaceRange=function(a,b,c,d){for(var h=this._rctx,f=E.getBytesPerElement(d),e=0;e<a.length;e++){var k=a[e];h.drawElements(c,k[1]-k[0]+1,d,(k[0]+b)*f)}this._stats.drawCallsFragmented+=
a.length-1};e.prototype._renderInternalMerged=function(a,b,c,d){var h=this,f=this._rctx,e=f.gl,k=!1,l=!1;a.origin2data.forEach(function(a){c.origin=a.origin;d===w.STENCIL_MATERIAL&&(h._stencilRenderingHelper.enabled=!0,h._stencilRenderingHelper.prepareStencilWritePass());if(!a.displayedIndexRange||0!==a.displayedIndexRange.length){l||(b.bind(f,c),l=!0);var g=b.getProgram();f.bindVAO(a.vao);E.assertCompatibleVertexAttributeLocations(a.vao,g);b.bindView(f,c);h._stats.drawCallsMerged++;g=b.getDrawMode(f);
g===e.TRIANGLES&&(h._stats.trianglesRendered+=a.vao.vertexBuffers.geometry.size/3);a.displayedIndexRange?h._drawArraysFaceRange(a.displayedIndexRange,0,g):f.drawArrays(g,0,E.vertexCount(a.vao,"geometry"));k=!0}});l&&b.release(f,c);return k};e.prototype._renderInternalPreinterleaved=function(a,b,c,d){var h=this,f=this._rctx,e=f.gl,k=!1,l=!1,g=b.getDrawMode(f);a.origin2data.forEach(function(a){c.origin=a.origin;var n=!1;d===w.STENCIL_MATERIAL&&(h._stencilRenderingHelper.enabled=!0,h._stencilRenderingHelper.prepareStencilWritePass());
for(var p in a.instances){var r=a.instances[p],u=r.instance,t=r.vao,r=u.displayedIndexRange;if(!r||0!==r.length){l||(b.bind(f,c),l=!0);var A=b.getProgram();E.assertCompatibleVertexAttributeLocations(t,A);f.bindVAO(t);n||(b.bindView(f,c),n=!0);b.bindInstance(f,u);h._stats.drawCallsPreinterleaved++;g===e.TRIANGLES&&(h._stats.trianglesRendered+=(u.to-u.from)/3);t=t.indexBuffer&&t.indexBuffer.indexType;r?t?h._drawElementsFaceRange(r,u.from,g,t):h._drawArraysFaceRange(r,u.from,g):t?(r=E.getBytesPerElement(t),
f.drawElements(g,u.to-u.from,t,u.from*r)):f.drawArrays(g,u.from,u.to-u.from);k=!0}}});f.bindVAO(null);l&&b.release(f,c);return k};e.prototype._updateGlobalUniforms=function(a){for(var b=this._programRep.getProgramsUsingUniform("proj"),c=0;c<b.length;c++)b[c].setUniformMatrix4fv("proj",a);if(this._lighting){b=this._programRep.getProgramsUsingUniform("lightingMainDirection");for(c=0;c<b.length;c++)this._lighting.setUniforms(b[c]);b=this._programRep.getProgramsUsingUniform("lightDirection");for(c=0;c<
b.length;c++)this._lighting.setUniforms(b[c])}};e.prototype.print=function(){var a=Object.keys(this._mat2DataMerged).length,b=Object.keys(this._mat2DataInstanced).length,c=Object.keys(this._mat2DataPreinterleaved).length;console.log("number of materials (merged/instanced/preinterleaved): "+a+"/"+b+"/"+c);var d=0;I(this._mat2DataMerged,function(){},function(a,b){d+=Object.keys(b.instances).length});var h=0;I(this._mat2DataInstanced,function(){},function(a,b){h+=Object.keys(b.instances).length});var f=
0;I(this._mat2DataPreinterleaved,function(){},function(a,b){f+=Object.keys(b.instances).length});console.log("number of instances (merged/instanced/preinterleaved): "+d+"/"+h+"/"+f)};e.prototype.isEmpty=function(){for(var a in this._mat2DataInstanced){var b=this._mat2DataInstanced[a];if(!U.everyMap(b.origin2data,function(a){return D.objectEmpty(a.instances)}))return!1}for(a in this._mat2DataMerged)if(b=this._mat2DataMerged[a],!U.everyMap(b.origin2data,function(a){return D.objectEmpty(a.instances)}))return!1;
for(a in this._mat2DataPreinterleaved)if(b=this._mat2DataPreinterleaved[a],!U.everyMap(b.origin2data,function(a){return D.objectEmpty(a.instances)}))return!1;return!0};e.prototype.modify=function(a,b,c,d){this._isRendering&&console.warn("Renderer.modify called while rendering");var h=[],f=[],e=[];this._classifyRenderGeometry(a,h,f,e);a=[];var k=[],l=[];this._classifyRenderGeometry(b,a,k,l);var g={};c&&this._performUpdates(c,g);c=[];this._modifyMerged(h,a,c,g);this._modifyInstanced(f,k,c);this._modifyPreinterleaved(e,
l,c);this._updateMergedFaceranges(g);this._releaseMaterials(c);h=this._highlights.length;if(b&&0<b.length&&0<h&&(this._highlights=this._highlights.filter(function(a){return!b.some(function(b){return b.uniqueName===a.uniqueName})}),h!==this._highlights.length&&this.onHasHighlightsChanged))this.onHasHighlightsChanged(this.hasHighlights);this._updateHighlightVAOs();d&&this._modifyMaterials(d);this._needsRender=!0};e.prototype._classifyRenderGeometry=function(a,b,c,d){for(var h=0;h<a.length;h++){var f=
a[h];if(1<=W(f.data))switch(this._getType(f)){case t.Merged:b.push(f);break;case t.Instanced:c.push(f);break;case t.Preinterleaved:d.push(f)}}};e.prototype._performUpdates=function(a,b){for(var c=0;c<a.length;c++){var d=a[c],h=d.updateType,d=d.renderGeometry,f=this._getType(d)===t.Merged;if(1<=W(d.data)){h&2&&this._updateFaceranges(d,b);if(h&32){var e=this._getInstance(d);e&&this._updateHighlightFaceranges(d,e.instance)}h&4||f&&h&16?this._updateVertexAttributes(d,!f):!f&&h&16&&this._updateInstanceTransformation(d)}}};
e.prototype._updateFaceranges=function(a,b){var c=a.material.id,d=a.origin.id,h=this._getType(a),f;if(h===t.Preinterleaved){var e=this._getOriginData(h,c,d);f=e.instances[a.uniqueName].instance}else e=this._getOriginData(h,c,d),(f=e.instances[a.uniqueName])&&h===t.Merged&&(b[this._modifiedMergedFacerangesKey(c,d)]=e);f&&(f.displayedIndexRange=T(a),this._updateHighlightFaceranges(a,f))};e.prototype._updateHighlightFaceranges=function(a,b){if(b){var c=b.highlightedIndexRange,d;d=a.instanceParameters.hidden?
null:Z.generateHighlightedIndexRanges(a.instanceParameters.componentVisibilities,a.instanceParameters.componentHighlights,a.componentOffsets);(b.highlightedIndexRange=d)&&!c?this._addHighlight(a):!d&&c&&this._removeHighlight(a)}};e.prototype._updateMergedFaceranges=function(a){for(var b in a){var c=a[b];c.displayedIndexRange=[];var d=c.instances,h=!0,f;for(f in d){var e=d[f];e.displayedIndexRange?(c.displayedIndexRange.push.apply(c.displayedIndexRange,ba.offsetIntervals(e.displayedIndexRange,e.from)),
h=!1):c.displayedIndexRange.push([e.from,e.to-1])}c.displayedIndexRange=h?null:ba.mergeIntervals(c.displayedIndexRange)}};e.prototype._updateVertexAttributes=function(a,b){var c=a.material,d=c.bufferWriter,h=c.id,f=a.origin.id,c=d.vertexBufferLayout.stride/4,e=this._getType(a);if(e===t.Preinterleaved)console.error("Updating Preinterleaved geometry not supported");else{var e=this._getOriginData(e,h,f),h=e.instances[a.uniqueName],f=e.buffer.getArray(),e=e.vao,k,l;b||(V(a,Q,R),k=Q,l=R);d.write({transformation:k,
invTranspTransformation:l},a.data,a.instanceParameters,d.vertexBufferLayout.createView(f.buffer),h.from);D.assert(h.from+d.elementCount(a.data)===h.to,"material VBO layout has changed");e.vertexBuffers.geometry.setSubData(f,h.from*c*4,h.from*c*4,h.to*c*4)}};e.prototype._updateInstanceTransformation=function(a){var b=this._getType(a),c=a.material.id,d=a.origin.id;b===t.Preinterleaved?(b=this._getOriginData(b,c,d),d=b.instances[a.uniqueName].instance,V(a,d.transformation,d.transformationNormal)):(b=
this._getOriginData(b,c,d),d=b.instances[a.uniqueName],b=b.perGeometryDataInfo[a.data.id],c=b.instanceBufferData,V(a,d.transformation,d.transformationNormal),c&&(a=c.getSlot(a.idx),c.fill(a,0,d.transformation),c.fill(a,16,d.transformationNormal),a=4*c.getOffset(a),d=E.getStride(b.vao.layout.instance),b.vao.vertexBuffers.instance.setSubData(c.getArray(),a,a,a+d)))};e.prototype._modifyMerged=function(a,b,c,d){a=this._compMatToDelta(a,b,t.Merged);b=this._mat2DataMerged;for(var h in a){var f=a[h],e;for(e in f){var k=
f[e],l=k.optimalCount,g=k.sparseCount,p=k.material,m=p.bufferWriter.vertexBufferLayout,q=m.stride/4,r=b[h];null==r&&(D.assert(0<l),r=this._initializeMatData(p),b[h]=r,this._orderedRendering&&this._insertIntoRenderOrder(r,p.renderPriority,"merged"));var u=r.origin2data.get(e);null==u&&(D.assert(0<l),u=this._createMergedData(m,l,k.origin),r.origin2data.set(e,u));if(0===l)u.vao.dispose(!0),u.vao=null,r.origin2data.delete(e),0===r.origin2data.size&&(c.push(h),delete b[h],this._orderedRendering&&this._removeFromRenderOrder(r,
"merged"));else{var w=(m=l<k.sparseCount/2)?l:g,l=ra,g=u.buffer.getSize(),r=u.buffer.getArray(),w=u.buffer.resize(w);m||w?this._rebuildMerged(u,k.toRemove,q,r,l):0<k.toRemove.length?(this._removeMergedByErasing(u,k.toRemove,q,l),0<k.toAdd.length&&(l.end=g)):(l.begin=g,l.end=g);m=L;D.setMatrixTranslation3(m,-k.origin[0],-k.origin[1],-k.origin[2]);this._appendMerged(u,p,k.toAdd,q,m,l);k=u.vao.vertexBuffers.geometry;k.byteSize!==u.buffer.getArray().buffer.byteLength?k.setData(u.buffer.getArray()):(m=
l.begin,p=l.end,m<p&&(q=u.buffer.getArray(),m*=4,k.setSubData(q,m,m,4*p)));if(l.updatedDisplayedIndexRange||u.displayedIndexRange)d[this._modifiedMergedFacerangesKey(h,e)]=u}}}};e.prototype._createMergedData=function(a,b,c){return{type:t.Merged,instances:{},vao:new P(this._rctx,S.Default3D,{geometry:N.glLayout(a)},{geometry:O.createVertex(this._rctx,35044)}),buffer:new aa(b),optimalCount:0,origin:c}};e.prototype._rebuildMerged=function(a,b,c,d,h){for(var f=0;f<b.length;++f){var e=a.instances[b[f].uniqueName];
a.optimalCount-=(e.to-e.from)*c;delete a.instances[b[f].uniqueName]}b=0;f=a.buffer.getArray();h.begin=0;h.end=0;var k=-1,l=-1,g=0,p;for(p in a.instances){var e=a.instances[p],m=e.from*c,q=e.to*c,r=q-m;k!==l&&l!==m?(f.set(d.subarray(k,l),g),g+=l-k,k=m):-1===k&&(k=m);l=q;e.from=b/c;b+=r;e.to=b/c}k!==l&&f.set(d.subarray(k,l),g);h.end=b};e.prototype._removeMergedByErasing=function(a,b,c,d){if(0!==b.length){d.begin=Infinity;d.end=-Infinity;for(var e=-1,f=-1,n=0;n<b.length;n++){var k=b[n].uniqueName,l=
a.instances[k].from*c,g=a.instances[k].to*c;e!==f&&f!==l?(a.buffer.erase(e,f),e=l):-1===e&&(e=l);f=g;delete a.instances[k];a.optimalCount-=g-l;l<d.begin&&(d.begin=l);g>d.end&&(d.end=g)}e!==f&&a.buffer.erase(e,f)}};e.prototype._appendMerged=function(a,b,c,d,e,f){f.updatedDisplayedIndexRange=!1;b=b.bufferWriter;for(var h=0;h<c.length;h++){var k=c[h],l=k.data;A.mat4d.multiply(e,k.transformation,Q);A.mat4d.inverse(Q,R);A.mat4d.transpose(R);var g=f.end;b.write({transformation:Q,invTranspTransformation:R},
l,k.instanceParameters,b.vertexBufferLayout.createView(a.buffer.getArray().buffer),f.end/d);var l=b.elementCount(l)*d,p=g+l;D.assert(null==a.instances[k.uniqueName]);var m=T(k),g=new X(k.name,g/d,p/d,m,void 0,void 0,k.idx);a.instances[k.uniqueName]=g;this._updateHighlightFaceranges(k,g);m&&(f.updatedDisplayedIndexRange=!0);a.optimalCount+=l;f.end+=l}};e.prototype._modifyInstanced=function(a,b,c){var d=this._rctx,e=t.Instanced;a=this._compMatToDelta(a,b,e);b=this._mat2DataInstanced;for(var f in a){var n=
a[f],k;for(k in n){var l=n[k];if(0===l.optimalCount)l=b[f],l.origin2data.get(k).vao.dispose(!0),l.origin2data.delete(k),0===l.origin2data.size&&(c.push(f),delete b[f],this._orderedRendering&&this._removeFromRenderOrder(l,"instanced"));else{var g=l.material,p=g.bufferWriter,m=b[f];if(null==m){var q=g.renderPriority,m=this._initializeMatData(g);b[f]=m;this._orderedRendering&&this._insertIntoRenderOrder(m,q,"instanced")}var q=p.vertexBufferLayout,r=m[B.MATERIAL].instanced?p.instanceBufferLayout:void 0,
u=r&&r.fields.get("instanceColor"),w=r&&r.fields.get("instanceFeatureAttribute"),H=q.stride/4,g=m.origin2data.get(k);null==g&&(g={type:e,instances:{},vao:new P(d,S.Default3D,{geometry:N.glLayout(q)},{geometry:O.createVertex(d,35044)}),buffer:new aa(l.optimalCount),optimalCount:0,perGeometryDataInfo:{},origin:l.origin},m.origin2data.set(k,g));var m=g.buffer.getSize(),E=g.buffer.getArray(),C=l.optimalCount<l.sparseCount/2,y=g.buffer.resize(C?l.optimalCount:l.sparseCount),z;for(z in l.perGeometryDelta){var v=
g.perGeometryDataInfo[z];if(v&&v.instanceBufferData){var x=l.perGeometryDelta[z].removeCount;0<x&&v.instanceBufferData.prepareFree(x)}}var F=l.toRemove;if(C||y){for(C=0;C<F.length;++C){y=F[C];delete g.instances[y.uniqueName];z=y.data.id;var J=v=g.perGeometryDataInfo[z];0===--J.refCount&&null==l.dataId2refCount[z]?(g.optimalCount-=(J.to-J.from)*H,delete g.perGeometryDataInfo[z]):v.instanceBufferData&&v.instanceBufferData.free(y.idx)}var m=0,C=g.buffer.getArray(),y={},I;for(I in g.perGeometryDataInfo)J=
g.perGeometryDataInfo[I],D.assert(null==y[J.from]),y[J.from]=J;for(var K in y)J=y[K],x=J.from*H,v=J.to*H,C.set(E.subarray(x,v),m),J.from=m/H,m+=v-x,J.to=m/H;for(var M in g.instances)x=g.instances[M],x.from=g.perGeometryDataInfo[x.dataId].from,x.to=g.perGeometryDataInfo[x.dataId].to}else for(C=0;C<F.length;++C)y=F[C],delete g.instances[y.uniqueName],z=y.data.id,v=g.perGeometryDataInfo[z],0===--v.refCount&&null==l.dataId2refCount[z]?(x=v.from*H,v=v.to*H,g.buffer.erase(x,v),g.optimalCount-=v-x,delete g.perGeometryDataInfo[z]):
v.instanceBufferData&&v.instanceBufferData.free(y.idx);D.setMatrixTranslation3(L,-l.origin[0],-l.origin[1],-l.origin[2]);for(z in l.perGeometryDelta)(v=g.perGeometryDataInfo[z])&&v.instanceBufferData&&(C=l.perGeometryDelta[z].addCount,0<C&&v.instanceBufferData.prepareAllocate(C));E=l.toAdd;for(C=0;C<E.length;++C)if(y=E[C],x=y.data,z=x.id,v=g.perGeometryDataInfo[z],null==v?(p.write({},x,void 0,p.vertexBufferLayout.createView(g.buffer.getArray().buffer),m/H),F=p.elementCount(x)*H,x=m/H,m+=F,v=m/H,g.optimalCount+=
F,v={refCount:1,from:x,to:v,vao:null,instanceBufferData:null},r&&(x=r.stride/4,v.vao=new P(d,S.Default3D,{geometry:N.glLayout(q),instance:N.glLayout(r,{divisor:1})},{geometry:g.vao.vertexBuffers.geometry,instance:O.createVertex(d,35044)}),v.instanceBufferData=new fa(x,l.perGeometryDelta[z].addCount)),g.perGeometryDataInfo[z]=v):++v.refCount,D.assert(v.from*H<=g.buffer.getSize()&&v.to*H<=g.buffer.getSize()),x=A.mat4d.create(),A.mat4d.multiply(L,y.transformation,x),F=T(y),x=new X(y.name,v.from,v.to,
F,x,y.instanceParameters,y.idx,z),g.instances[y.uniqueName]=x,this._updateHighlightFaceranges(y,x),v=v.instanceBufferData)F=v.allocate(y.idx),v.fill(F,0,x.transformation),v.fill(F,16,x.transformationNormal),u&&v.fill(F,u.offset/4,y.instanceParameters.color),w&&v.fill(F,w.offset/4,y.instanceParameters.featureAttribute);D.assert(g.optimalCount===l.optimalCount);p=new Float32Array(g.buffer.getArray().buffer,0,g.buffer.getSize());g.vao.vertexBuffers.geometry.setData(p);for(z in g.perGeometryDataInfo)if(q=
g.perGeometryDataInfo[z],q.vao&&(p=q.vao.vertexBuffers.instance))r=l.perGeometryDelta[z],0<r.addCount+r.removeCount&&(q=q.instanceBufferData.compact(),p.setData(q))}}}};e.prototype._modifyPreinterleaved=function(a,b,c){for(var d=this._rctx,e=t.Preinterleaved,f=this._mat2DataPreinterleaved,n=0;n<a.length;n++){var k=a[n],l=k.material,g=l.bufferWriter,p=l.id,m=k.origin.id,q=k.origin.vec3,r=f[p];null==r&&(r=this._initializeMatData(l),f[p]=r);p=r.origin2data.get(m);null==p&&(p={type:e,origin:q,count:0,
instances:{}},r.origin2data.set(m,p));D.setMatrixTranslation3(L,-q[0],-q[1],-q[2]);r=A.mat4d.create();A.mat4d.multiply(L,k.transformation,r);q=T(k);m=k.data;m.preinterleaved?null==m.vertexData?D.assert(!1,"Trying to re-add preinterleaved geometry data which is no longer available."):(r=new X(k.name,0,m.indexCount,q,r,k.instanceParameters,k.idx,m.id),q=m.indexData?O.createIndex(d,35044,m.indexData):null,g=new P(d,S.Default3D,{geometry:N.glLayout(g.vertexBufferLayout)},{geometry:O.createVertex(d,35044)},
q),g.vertexBuffers.geometry.setData(m.vertexData),m.indexData=null,m.vertexData=null,p.count+=1,p.instances[k.uniqueName]={instance:r,vao:g},this._updateHighlightFaceranges(k,r)):D.assert(!1,"Non-interleaved render geometry processed as pre-interleaved")}for(a=0;a<b.length;a++)k=b[a],q=k.origin,l=k.material,p=l.id,m=q.id,k=k.uniqueName,r=f[p],d=r.origin2data.get(m),d.instances[k].vao.dispose(),delete d.instances[k],--d.count,0===d.count&&r.origin2data.delete(m),0===r.origin2data.size&&(c.push(p),
delete f[p])};e.prototype._compMatToDelta=function(a,b,c){var d={};this._updateMatToDelta(a,!0,c,d);this._updateMatToDelta(b,!1,c,d);return d};e.prototype._updateMatToDelta=function(a,b,c,d){c=c===t.Instanced;for(var e=0;e<a.length;e++){var f=a[e],n=f.origin,k=f.material,l=k.bufferWriter,g=k.id,p=c?this._mat2DataInstanced[g]:this._mat2DataMerged[g],p=p&&p.origin2data.get(n.id),m=d[g];null==m&&(m={},d[g]=m);g=m[n.id];if(null==g){g={optimalCount:null==p?0:p.optimalCount,sparseCount:null==p?0:p.buffer.getSize(),
material:k,toAdd:[],toRemove:[],perGeometryDelta:null,origin:n.vec3};if(c){k={};if(void 0!==p)for(var q in p.perGeometryDataInfo)k[q]=p.perGeometryDataInfo[q].refCount;g.dataId2refCount=k;g.perGeometryDelta={}}m[n.id]=g}n=l.vertexBufferLayout.stride/4;l=l.elementCount(f.data)*n;c?(n=f.data.id,k=g.perGeometryDelta[n],k||(k={addCount:0,removeCount:0},g.perGeometryDelta[n]=k),b?(k.addCount++,null==g.dataId2refCount[n]&&(g.dataId2refCount[n]=0),1===++g.dataId2refCount[n]&&(g.optimalCount+=l,g.sparseCount+=
l),g.toAdd.push(f)):(k.removeCount++,0===--g.dataId2refCount[n]&&(delete g.dataId2refCount[n],g.optimalCount-=l),g.toRemove.push(f))):b?(g.optimalCount+=l,g.sparseCount+=l,g.toAdd.push(f)):(g.optimalCount-=l,g.toRemove.push(f))}};e.prototype._getType=function(a){if(a.data.preinterleaved)return t.Preinterleaved;var b=!1,c=W(a.data),b=(b=(b=b||!1===a.material.canBeMerged)||a.material.instanced)||!0===a.material.renderOccluded;a.singleUse||(b=b||c>this._threshold);return b?t.Instanced:t.Merged};e.prototype._getTargetMat2Data=
function(a){switch(a){case t.Merged:return this._mat2DataMerged;case t.Instanced:return this._mat2DataInstanced;case t.Preinterleaved:return this._mat2DataPreinterleaved}};e.prototype._getOriginData=function(a,b,c){return this._getTargetMat2Data(a)[b].origin2data.get(c)};e.prototype._modifiedMergedFacerangesKey=function(a,b){return a+"_"+b};e.prototype._insertIntoRenderOrder=function(a,b,c){for(var d=a[B.MATERIAL].materialId,e=this._renderOrder.length,f=0;f<e&&this._renderOrder[f][0]>=b;){var n=this._renderOrder[f][1];
if(n.id===d){D.assert(!n[c],"matData for type already exists");n[c]=a;return}f++}d={id:d,instanced:null,merged:null};d[c]=a;this._renderOrder.splice(f,0,[b,d])};e.prototype._removeFromRenderOrder=function(a,b){var c=a[B.MATERIAL].materialId;for(a=0;this._renderOrder[a][1].id!==c;)a++;c=this._renderOrder[a][1];c[b]=null;c.instanced||c.merged||this._renderOrder.splice(a,1)};e.prototype._sortHighlightsByRenderOrder=function(){this._highlights.sort(function(a,b){a=a.matData[B.MATERIAL].renderPriority;
b=b.matData[B.MATERIAL].renderPriority;return a>b?-1:b>a?1:0})};e.prototype._updateRenderOrder=function(a,b){for(var c=b.length,d=0;d<c&&b[d][1].id!==a;)d++;if(d<c){a=b[d][1];a=(a.merged||a.instanced)[B.MATERIAL].renderPriority;var e=b[d][0];if(a!==b[d][0])for(b[d][0]=a,e=a>e?-1:1,d+=e;-1<d&&d<c&&e*b[d][0]>e*a;){var f=b[d];b[d]=b[d-e];b[d-e]=f;d+=e}}};e.prototype._modifyMaterials=function(a){var b=this;a.forEach(function(a){b._materialRep.updateMaterialParameters(a)})};e.prototype.modifyRenderOrder=
function(a){var b=this;this._orderedRendering&&(a.forEach(function(a){b._updateRenderOrder(a,b._renderOrder)}),this._sortHighlightsByRenderOrder(),this._needsRender=!0)};e.prototype._initializeMatData=function(a){var b={origin2data:new Map};b[B.MATERIAL]=this._materialRep.aquire(a);b[B.MATERIAL_DEPTH_SHADOWMAP]=this._materialRep.aquireDepthShadowMap(a);b[B.MATERIAL_NORMAL]=this._materialRep.aquireNormal(a);b[B.MATERIAL_DEPTH]=this._materialRep.aquireDepth(a);b[B.MATERIAL_HIGHLIGHT]=this._materialRep.aquireHighlight(a);
return b};e.prototype._releaseMaterials=function(a){if(Array.isArray(a))for(var b=0;b<a.length;b++)this._materialRep.release(a[b]),this._materialRep.releaseDepthShadowMap(a[b]),this._materialRep.releaseNormal(a[b]),this._materialRep.releaseDepth(a[b]),this._materialRep.releaseHighlight(a[b]);else this._materialRep.release(a),this._materialRep.releaseDepthShadowMap(a),this._materialRep.releaseNormal(a),this._materialRep.releaseDepth(a),this._materialRep.releaseHighlight(a)};e.prototype._getInstance=
function(a){var b=a.uniqueName,c=a.material.id,d=this._getType(a),c=this._getTargetMat2Data(d)[c];if(!c)return null;a=c.origin2data.get(a.origin.id);if(!a)return null;var e;return(e=a.type===t.Preinterleaved?a.instances[b].instance:a.instances[b])?{type:d,uniqueName:b,instance:e,matData:c,originData:a,instancedVAO:null,instancedVAOBaseInstance:null}:null};e.prototype._createBaseInstanceVAO=function(a){var b=this._rctx,c=a.instance,d=a.originData;if(a.type===t.Instanced&&d.perGeometryDataInfo){var d=
d.perGeometryDataInfo[c.dataId],e=d.instanceBufferData;e&&(d=d.vao,c=e.getSlot(c.idx),a.instancedVAOBaseInstance!==c&&(e=E.setBaseInstanceOffset(d.layout,c),a.instancedVAO=new P(b,d.locations,e,d.vertexBuffers,d.indexBuffer),a.instancedVAOBaseInstance=c))}};e.prototype._updateHighlightVAOs=function(){for(var a=0;a<this._highlights.length;++a)this._createBaseInstanceVAO(this._highlights[a])};e.prototype._getFallbackDepthTexture=function(){this._fallbackDepthStencilTexture||(this._fallbackDepthStencilTexture=
new ca(this._rctx,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:1,height:1},new Uint8Array([255,255,255,255])));return this._fallbackDepthStencilTexture};return e}();var qa=function(){function e(){this.reset()}e.prototype.reset=function(){this.VBOusedSize=this.VBOoptimalSize=this.VBOallocatedSize=this.instancesDrawnAngle=this.drawCallsHighlight=this.drawCallsFragmented=this.drawCallsPreinterleaved=this.drawCallsMerged=this.drawCallsAngleInstanced=this.drawCallsInstanced=this.trianglesRendered=
0};return e}(),X=function(){return function(e,a,b,c,d,h,f,n){this.name=e;this.from=a;this.to=b;this.displayedIndexRange=c;this.transformation=d;this.instanceParameters=h;this.idx=f;this.dataId=n;null!=d&&(this.transformationNormal=A.mat4d.create(),A.mat4d.set(d,this.transformationNormal),A.mat4d.inverse(this.transformationNormal,this.transformationNormal),A.mat4d.transpose(this.transformationNormal,this.transformationNormal))}}(),t;(function(e){e[e.Merged=0]="Merged";e[e.Instanced=1]="Instanced";
e[e.Preinterleaved=2]="Preinterleaved"})(t||(t={}));var ra={updatedDisplayedIndexRange:!1,begin:0,end:0},K=A.vec2d.create(),L=A.mat4d.identity(),Q=A.mat4d.create(),R=A.mat4d.create();return Y});