// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/has ../../lib/gl-matrix ./Object3D ./PerformanceTimer".split(" "),function(t,x,y,a,w,z){var u=a.vec3d.create(),v=a.vec3d.create(),l=a.vec3d.create();t=function(){function c(b){this.minResult=new q;this.maxResult=new q;this._normalDir=null;this._transform=a.mat4d.create();this._transformInverse=new f({value:this._transform},a.mat4d.inverse,a.mat4d.create);this._transformInverseTranspose=new f(this._transformInverse,a.mat4d.transpose,a.mat4d.create);this._transformTranspose=
new f({value:this._transform},a.mat4d.transpose,a.mat4d.create);this._transformInverseRotation=new f({value:this._transform},a.mat4d.toInverseMat3,a.mat3d.create);this.enableTerrain=this.enableHUDSelection=!0;this.enableInvisibleTerrain=!1;this.enableBackfacesTerrain=!0;this.performanceInfo={queryDuration:0,numObjectsTested:0};this.viewingMode=b||"global"}c.prototype.init=function(b,c,d,g,e,r,k,h){var m=this;c&&d&&a.vec3d.subtract(d,c,l);this.minResult.init(c,d);this.maxResult.init(c,d);this._numObjectsTested=
0;this.point=g;this.camera=e;this.isSelection=k;this.p0=c;this.p1=d;this.hudResults=[];null==r&&(r=1E-5);this.tolerance=r;if(b)for(c=function(b){m.intersectObject(b,h)},d=0;d<b.length;d++)if(g=b[d],e=g.getSpatialQueryAccelerator?g.getSpatialQueryAccelerator():void 0)e.forEachAlongRay(this.p0,l,c),k&&e.forEachDegenerateObject(c);else for(e=0,g=g.getObjects();e<g.length;e++)c(g[e])};Object.defineProperty(c.prototype,"transformInverse",{get:function(){return this._transformInverse.value},enumerable:!0,
configurable:!0});Object.defineProperty(c.prototype,"transformInverseTranspose",{get:function(){return this._transformInverseTranspose.value},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"transformInverseRotation",{get:function(){return this._transformInverseRotation.value},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"transformTranspose",{get:function(){return this._transformTranspose.value},enumerable:!0,configurable:!0});c.prototype.getDirection=function(){this._normalDir||
(this._normalDir=a.vec3d.create(),a.vec3d.normalize(l,this._normalDir));return this._normalDir};c.prototype.intersectObject=function(b,c){var d=this;this._numObjectsTested++;for(var g=b.id,e=b.getGeometryRecords(),m=b.objectTransformation,k,h=0;h<e.length;h++){var p=e[h],f=p.geometry,n=p.materials,l=p.instanceParameters;l.hidden||(k=f.id,a.mat4d.set(m,this._transform),a.mat4d.multiply(this._transform,p.getShaderTransformation()),this._transformInverse.invalidate(),this._transformInverseTranspose.invalidate(),
this._transformTranspose.invalidate(),this._transformInverseRotation.invalidate(),a.mat4d.multiplyVec3(this.transformInverse,this.p0,u),a.mat4d.multiplyVec3(this.transformInverse,this.p1,v),n[0].intersect(f,l,this._transform,this,u,v,function(a,e,m,f,h,l){0<=a&&(null==c||c(d.p0,d.p1,a))&&(h?(h=new q,h.init(d.p0,d.p1),h.set(b,g,a,e,f,l,k,m),d.hudResults.push(h)):((null==d.minResult.priority||f>=d.minResult.priority)&&(null==d.minResult.dist||a<d.minResult.dist)&&d.minResult.set(b,g,a,e,f,null,k,m),
(null==d.maxResult.priority||f>=d.maxResult.priority)&&(null==d.maxResult.dist||a>d.maxResult.dist)&&d.maxResult.set(b,g,a,e,f,null,k,m)))},p.customTransformation),this.minResult.geometryId===k&&a.mat4d.set(this._transform,this.minResult.transformation),this.maxResult.geometryId===k&&a.mat4d.set(this._transform,this.maxResult.transformation))}};c.DEFAULT_TOLERANCE=1E-5;return c}();var q=function(){function c(b,c){this.transformation=a.mat4d.identity();this.normal=a.vec3d.create();this.init(b,c)}c.prototype.getIntersectionPoint=
function(b){if(null==this.dist)return!1;a.vec3d.lerp(this.p0,this.p1,this.dist,b);return!0};c.prototype.getTransformedNormal=function(b){a.vec3d.set(this.normal,n);n[3]=0;a.mat4d.multiplyVec4(this.transformation,n);a.vec3d.set(n,b);a.vec3d.normalize(b);return b};c.prototype.set=function(b,c,d,g,e,f,k,h){b instanceof w&&(b={type:"stage",obj:b});this.dist=d;a.vec3d.set(g,this.normal);this.target=b;this.name=c;this.priority=e;this.center=f?a.vec3d.create(f):null;this.geometryId=k;this.triangleNr=h};
c.prototype.copyFrom=function(b){this.p0=b.p0;this.p1=b.p1;this.dist=b.dist;this.target=b.target;this.name=b.name;this.priority=b.priority;this.center=b.center?a.vec3d.create(b.center):null;this.geometryId=b.geometryId;this.triangleNr=b.triangleNr;this.intersector=b.intersector;a.vec3d.set(b.normal,this.normal)};c.prototype.setIntersector=function(b){this.intersector=b};c.prototype.init=function(b,a){this.priority=this.name=this.target=this.dist=void 0;this.triangleNr=this.geometryId=this.center=
null;this.intersector="Stage";this.p0=b;this.p1=a};return c}(),f=function(){function a(a,c,d){this.original=a;this.update=c;this.dirty=!0;this.transform=d()}a.prototype.invalidate=function(){this.dirty=!0};Object.defineProperty(a.prototype,"value",{get:function(){this.dirty&&(this.update(this.original.value,this.transform),this.dirty=!1);return this.transform},enumerable:!0,configurable:!0});return a}(),n=a.vec4d.create();return t});