// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../lib/gl-matrix ../../support/mathUtils ./Camera ./DefaultVertexAttributeLocations ./DefaultVertexBufferLayouts ./glUtil3D ./Util ../shaders/MiscPrograms ../../../webgl/BufferObject ../../../webgl/FramebufferObject ../../../webgl/Texture ../../../webgl/Util ../../../webgl/VertexArrayObject".split(" "),function(Q,D,a,ga,ha,ia,ja,ka,m,la,ma,na,oa,R,pa){function q(b,f){a.vec3d.set3(b[f],b[f+3],b[f+6],S);return S}var qa=function(){return function(){this.camera=new ha;this.lightMat=
a.mat4d.create()}}();Q=function(){function e(a,b){this.doShadowMapMipmapsWork=!1;this.textureRes=4096;this.numCascades=1;this.maxNumCascades=2;this.cascadeDistances=[0,0,0,0,0];this.cascades=[];this.programRep=a;this.rctx=b;this.emptyTexture=ka.createEmptyTexture(b);for(a=0;4>a;++a)this.cascades.push(new qa)}e.prototype.dispose=function(){this.emptyTexture.dispose();this.emptyTexture=null};Object.defineProperty(e.prototype,"textureResolution",{get:function(){return this.textureRes},set:function(a){this.textureRes=
a},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"maxCascades",{get:function(){return this.maxNumCascades},set:function(a){this.maxNumCascades=ga.clamp(Math.floor(a),1,4)},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"enabled",{get:function(){return!!this.depthTexture},set:function(a){a?this.enable():this.disable()},enumerable:!0,configurable:!0});e.prototype.getDepthTexture=function(){return this.depthTexture};e.prototype.getCascades=function(){for(var a=
0;a<this.numCascades;++a)P[a]=this.cascades[a];P.length=this.numCascades;return P};e.prototype.prepare=function(f,t,G,l){m.assert(this.enabled);a.mat4d.multiply(f.projectionMatrix,f.viewMatrix,T);var c=l.near,n=l.far;2>c&&(c=2);2>n&&(n=2);c>=n&&(c=2,n=4);this.numCascades=Math.min(1+Math.floor(m.logWithBase(n/c,4)),this.maxNumCascades);G=Math.pow(n/c,1/this.numCascades);for(l=0;l<this.numCascades+1;++l)this.cascadeDistances[l]=c*Math.pow(G,l);a.mat4d.inverse(T,U);a.mat4d.lookAt([0,0,0],[-t[0],-t[1],
-t[2]],[0,1,0],V);G=f.viewMatrix;f=f.projectionMatrix;for(l=0;l<this.numCascades;++l){var e=this.cascades[l],n=-this.cascadeDistances[l],c=-this.cascadeDistances[l+1],n=(f[10]*n+f[14])/Math.abs(f[11]*n+f[15]),c=(f[10]*c+f[14])/Math.abs(f[11]*c+f[15]);m.assert(n<c);for(var d=0;8>d;++d){a.vec4d.set4(0===d%4||3===d%4?-1:1,0===d%4||1===d%4?-1:1,4>d?n:c,1,W);a.mat4d.multiplyVec4(U,W,r[d]);for(var g=0;3>g;++g)r[d][g]/=r[d][3]}a.vec3d.negate(r[0],X);a.mat4d.translate(V,X,Y);e.camera.viewMatrix=Y;for(d=0;8>
d;++d)a.mat4d.multiplyVec3(e.camera.viewMatrix,r[d]);a.vec3d.set(r[0],z);a.vec3d.set(r[0],A);for(d=1;8>d;++d)for(g=0;3>g;++g)z[g]=Math.min(z[g],r[d][g]),A[g]=Math.max(A[g],r[d][g]);z[2]-=200;A[2]+=200;e.camera.near=-A[2];e.camera.far=-z[2];c=1/r[0][3];n=1/r[4][3];m.assert(c<n);var g=c+Math.sqrt(c*n),d=Math.sin(Math.acos(G[2]*t[0]+G[6]*t[1]+G[10]*t[2])),g=g/d,c=r,K=g,E=d,d=Z,u=aa,k=ra,x=ba,g=ca;a.vec2d.set2(0,0,w);for(var h=0;4>h;++h)a.vec2d.add(w,c[h],w);a.vec2d.scale(w,.25);a.vec2d.set2(0,0,L);for(h=
4;8>h;++h)a.vec2d.add(L,c[h],L);a.vec2d.scale(L,.25);a.vec2d.lerp(c[4],c[5],.5,F[0]);a.vec2d.lerp(c[5],c[6],.5,F[1]);a.vec2d.lerp(c[6],c[7],.5,F[2]);a.vec2d.lerp(c[7],c[4],.5,F[3]);for(var B=0,y=a.vec2d.dist2(F[0],w),h=1;4>h;++h){var H=a.vec2d.dist2(F[h],w);H<y&&(y=H,B=h)}a.vec2d.subtract(F[B],c[B+4],p);h=p[0];p[0]=-p[1];p[1]=h;a.vec2d.subtract(L,w,da);a.vec2d.lerp(p,da,E);a.vec2d.normalize(p);B=E=void 0;E=B=a.vec2d.dot(a.vec2d.subtract(c[0],w,C),p);for(h=1;8>h;++h)y=a.vec2d.dot(a.vec2d.subtract(c[h],
w,C),p),y<E?E=y:y>B&&(B=y);a.vec2d.set(w,d);a.vec2d.scale(p,E-K,C);a.vec2d.add(d,C,d);for(var H=-1,D=1,h=K=y=0;8>h;++h){a.vec2d.subtract(c[h],d,N);a.vec2d.normalize(N);var M=p[0]*N[1]-p[1]*N[0];0<M?M>H&&(H=M,y=h):M<D&&(D=M,K=h)}m.verify(0<H,"leftArea");m.verify(0>D,"rightArea");a.vec2d.scale(p,E,I);a.vec2d.add(I,w,I);a.vec2d.scale(p,B,J);a.vec2d.add(J,w,J);O[0]=-p[1];O[1]=p[0];u=m.rayRay2D(d,c[K],J,a.vec2d.add(J,O,C),1,u);k=m.rayRay2D(d,c[y],J,C,1,k);x=m.rayRay2D(d,c[y],I,a.vec2d.add(I,O,C),1,x);
c=m.rayRay2D(d,c[K],I,C,1,g);m.verify(u,"rayRay");m.verify(k,"rayRay");m.verify(x,"rayRay");m.verify(c,"rayRay");k=Z;c=aa;d=ba;x=ca;g=e.camera.projectionMatrix;a.vec2d.scale(a.vec2d.subtract(d,x,v),.5);b[0]=v[0];b[1]=v[1];b[2]=0;b[3]=v[1];b[4]=-v[0];b[5]=0;b[6]=v[0]*v[0]+v[1]*v[1];b[7]=v[0]*v[1]-v[1]*v[0];b[8]=1;b[6]=-a.vec2d.dot(q(b,0),k);b[7]=-a.vec2d.dot(q(b,1),k);k=a.vec2d.dot(q(b,0),d)+b[6];u=a.vec2d.dot(q(b,1),d)+b[7];h=a.vec2d.dot(q(b,0),x)+b[6];x=a.vec2d.dot(q(b,1),x)+b[7];k=-(k+h)/(u+x);
b[0]+=b[1]*k;b[3]+=b[4]*k;b[6]+=b[7]*k;k=1/(a.vec2d.dot(q(b,0),d)+b[6]);u=1/(a.vec2d.dot(q(b,1),d)+b[7]);b[0]*=k;b[3]*=k;b[6]*=k;b[1]*=u;b[4]*=u;b[7]*=u;b[2]=b[1];b[5]=b[4];b[8]=b[7];b[7]+=1;k=a.vec2d.dot(q(b,1),c)+b[7];u=a.vec2d.dot(q(b,2),c)+b[8];h=a.vec2d.dot(q(b,1),d)+b[7];x=a.vec2d.dot(q(b,2),d)+b[8];k=-.5*(k/u+h/x);b[1]+=b[2]*k;b[4]+=b[5]*k;b[7]+=b[8]*k;k=a.vec2d.dot(q(b,1),c)+b[7];u=a.vec2d.dot(q(b,2),c)+b[8];h=-u/k;b[1]*=h;b[4]*=h;b[7]*=h;g[0]=b[0];g[1]=b[1];g[2]=0;g[3]=b[2];g[4]=b[3];g[5]=
b[4];g[6]=0;g[7]=b[5];g[8]=0;g[9]=0;g[10]=1;g[11]=0;g[12]=b[6];g[13]=b[7];g[14]=0;g[15]=b[8];e.camera.projectionMatrix[10]=2/(z[2]-A[2]);e.camera.projectionMatrix[14]=-(z[2]+A[2])/(z[2]-A[2]);a.mat4d.multiply(e.camera.projectionMatrix,e.camera.viewMatrix,e.lightMat);c=this.textureRes/2;e.camera.viewport[0]=0===l%2?0:c;e.camera.viewport[1]=0===Math.floor(l/2)?0:c;e.camera.viewport[2]=c;e.camera.viewport[3]=c}this.lastOrigin=null;this.cascadeDistances[this.numCascades]=100*n;t=this.rctx;l=t.gl;t.bindFramebuffer(this.fbo);
t.bindTexture(null,7);t.setClearColor(1,1,1,1);t.clear(l.COLOR_BUFFER_BIT|l.DEPTH_BUFFER_BIT);t.setBlendingEnabled(!1)};e.prototype.finish=function(a){m.assert(this.enabled);this.rctx.bindFramebuffer(a);this.doShadowMapMipmapsWork&&this.depthTexture.generateMipmap()};e.prototype.bind=function(a){var b=this.rctx,f=this.enabled;b.bindTexture(f?this.depthTexture:this.emptyTexture,7);b.bindProgram(a);a.setUniform1i("depthTex",7);a.setUniform1f("depthHalfPixelSz",f?.5/this.textureRes:-1);a.setUniform1i("shadowMapNum",
this.numCascades);a.setUniform4f("shadowMapDistance",this.cascadeDistances[0],this.cascadeDistances[1],this.cascadeDistances[2],this.cascadeDistances[3])};e.prototype.bindAll=function(a){a=a.getProgramsUsingUniform("shadowMapDistance");for(var b=0;b<a.length;b++)this.bind(a[b])};e.prototype.bindView=function(b,e){if(this.enabled){var f=this.lastOrigin;if(!f||f[0]!==e[0]||f[1]!==e[1]||f[2]!==e[2])for(this.lastOrigin=this.lastOrigin||a.vec3d.create(),a.vec3d.set(e,this.lastOrigin),f=0;f<this.numCascades;++f){a.mat4d.translate(this.cascades[f].lightMat,
e,ea);for(var l=0;16>l;++l)fa[16*f+l]=ea[l]}b.setUniformMatrix4fv("shadowMapMatrix",fa)}};e.prototype.drawDebugQuad=function(a){m.assert(this.enabled);var b=this.rctx,e=b.gl;if(!this.debugQuadVAO){var f=new Float32Array([0,0,0,0,256,0,1,0,0,256,0,1,256,256,1,1]);this.debugQuadVAO=new pa(b,ia.Default3D,{geometry:ja.Pos2Tex},{geometry:ma.createVertex(b,e.STATIC_DRAW,f)})}var f=this.programRep.getProgram(la.showDepth),c=this.debugQuadVAO;b.setDepthTestEnabled(!1);b.bindProgram(f);f.setUniformMatrix4fv("proj",
a);f.setUniform1i("depthTex",0);b.bindTexture(this.depthTexture,0);b.bindVAO(c);R.assertCompatibleVertexAttributeLocations(c,f);b.drawArrays(e.TRIANGLE_STRIP,0,R.vertexCount(c,"geometry"));b.setDepthTestEnabled(!0)};e.prototype.enable=function(){if(!this.enabled){var a=this.rctx.gl;this.depthTexture=new oa(this.rctx,{target:a.TEXTURE_2D,pixelFormat:a.RGBA,dataType:a.UNSIGNED_BYTE,wrapMode:a.CLAMP_TO_EDGE,samplingMode:a.NEAREST,flipped:!0,width:this.textureRes,height:this.textureRes});this.fbo=na.createWithAttachments(this.rctx,
this.depthTexture,{colorTarget:0,depthStencilTarget:1,width:this.textureRes,height:this.textureRes})}};e.prototype.disable=function(){this.enabled&&this.fbo&&(this.fbo.dispose(),this.depthTexture=this.fbo=null)};return e}();var Y=a.mat4d.create(),T=a.mat4d.create(),U=a.mat4d.create(),W=a.vec4d.create(),r=[];for(D=0;8>D;++D)r.push(a.vec4d.create());var z=a.vec3d.create(),A=a.vec3d.create(),Z=a.vec2d.create(),aa=a.vec2d.create(),ra=a.vec2d.create(),ba=a.vec2d.create(),ca=a.vec2d.create(),V=a.mat4d.create(),
X=a.vec3d.create(),P=[],ea=a.mat4d.create(),fa=new Float32Array(64),w=a.vec2d.create(),L=a.vec2d.create(),F=[a.vec2d.create(),a.vec2d.create(),a.vec2d.create(),a.vec2d.create()],p=a.vec2d.create(),da=a.vec2d.create(),C=a.vec2d.create(),N=a.vec2d.create(),I=a.vec2d.create(),J=a.vec2d.create(),O=a.vec2d.create(),S=a.vec3d.create(),v=a.vec2d.create(),b=a.mat3d.create();return Q});