// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/arrayUtils ../../support/mathUtils ./ModelContentType ./Texture ../../../webgl/Texture".split(" "),function(t,u,n,p,m,q,r){var f={budget:null,repackingEnabled:!0};return function(){function d(a,c){this.dirty=!1;this.elementsToAdd={};this.elementsToRemove={};this.elementsToRender={};this.elements={};this.stageObjects={};this.id=q.idGen.gen(a);this.stage=c._stage;this.controller=c.resourceController;this.canvas=this.create2DCanvas();this.ctx=this.canvas.getContext("2d");
this.stage.add(m.TEXTURE,this);a=this.computeAtlasResolution(c.width,c.height);this.createAtlasRegion(a);this.update2DCanvasSize()}d.prototype.setUnloadFunc=function(a){this.unloadFunc=a};d.prototype.unload=function(){null!=this.unloadFunc&&(this.unloadFunc(this.id),this.unloadFunc=null)};d.prototype.deferredLoading=function(){return!1};d.prototype.getWidth=function(){return this.atlas.size.width};d.prototype.getHeight=function(){return this.atlas.size.height};d.prototype.initializeThroughRender=
function(a,c){c.wrapMode=33071;c.samplingMode=9987;c.flipped=!0;c.preMultiplyAlpha=!0;c.hasMipmap=!0;return this.glTexture=new r(a,c,this.canvas)};d.prototype.dispose=function(){this.elementsToRender=this.elementsToRemove=this.elementsToAdd=this.elements=null;this.glTexture&&(this.glTexture=null,this.stage.remove(m.TEXTURE,this.id))};d.prototype.create2DCanvas=function(){var a=document.createElement("canvas");a.setAttribute("id","canvas2d");a.setAttribute("style","display:none");a.setAttribute("width",
(512).toString());a.setAttribute("height",(512).toString());return a};d.prototype.update2DCanvasSize=function(){this.canvas.setAttribute("width",this.atlas.size.width.toString());this.canvas.setAttribute("height",this.atlas.size.height.toString())};d.prototype.generateTextId=function(a){return JSON.stringify(a.getParams())+"_"+a.getText()};d.prototype.createAtlasRegion=function(a){void 0===a&&(a=512);this.atlas={size:{width:a,height:a},cursor:{x:0,y:0},lineHeight:0}};d.prototype.computeAtlasResolution=
function(a,c){a=Math.max(a,c);a=p.nextHighestPowerOfTwo(a+256);return a=Math.min(a,4096)};d.prototype.resizeAtlas=function(a,c){c=c||a;var b=this.atlas;b.size.width=a;b.size.height=c;this.glTexture&&this.glTexture.resize(a,c);this.update2DCanvasSize()};d.prototype.resetAtlasCursor=function(){var a=this.atlas;a.cursor.x=0;a.cursor.y=0;a.lineHeight=0};d.prototype.getAtlasUsage=function(){var a=this.atlas;return(a.cursor.x+a.cursor.y*a.size.width)/(a.size.width*a.size.height)};d.prototype.getExpectedAtlasUsage=
function(){var a=Object.keys(this.elementsToRemove).length,c=Object.keys(this.elementsToAdd).length,b=Object.keys(this.elements).length;return this.getAtlasUsage()/b*(b+c-a)};d.prototype.addAtlasElement=function(a,c,b,d,g){var e=this.atlas;a.placement.offset.x=e.cursor.x;a.placement.offset.y=e.cursor.y;a.placement.size.width=c;a.placement.size.height=b;a.placement.uvMinMax=[a.placement.offset.x/e.size.width,1-(a.placement.offset.y+b)/e.size.height,(a.placement.offset.x+c)/e.size.width,1-a.placement.offset.y/
e.size.height];e.cursor.x+=d;e.lineHeight=Math.max(e.lineHeight,g)};d.prototype.removeAtlasElement=function(a){if(a&&this.elements[a.textId]){var c=a.placement.offset,b=a.placement.size;this.ctx.clearRect(c.x,c.y,b.width,b.height);delete this.elements[a.textId]}};d.prototype.addStageObject=function(a,c){this.stageObjects[a]||(this.stageObjects[a]=[]);-1===this.stageObjects[a].indexOf(c)&&this.stageObjects[a].push(c)};d.prototype.removeStageObject=function(a,c){this.stageObjects[a]&&n.removeUnordered(this.stageObjects[a],
c)&&(c.geometries[0].data.vertexAttributes.size.data=new Float32Array([0,0]),c.geometryVertexAttrsUpdated(0))};d.prototype.processAdditionRequest=function(a,c){var b=this.atlas,d=a.textId,g=a.textTexture.renderedWidth,e=a.textTexture.renderedHeight,k=g+2,h=e+2+2;c=c.repackingEnabled;if(b.cursor.x+k<b.size.width&&b.cursor.y+h<b.size.height)this.addAtlasElement(a,g,e,k,h),this.elements[d]=a,this.elementsToRender[d]=a,delete this.elementsToAdd[d];else if(b.cursor.y+h+b.lineHeight<b.size.height)b.cursor.x=
2,b.cursor.y+=b.lineHeight,b.lineHeight=0,this.addAtlasElement(a,g,e,k,h),this.elements[d]=a,this.elementsToRender[d]=a,delete this.elementsToAdd[d];else{a=this.getExpectedAtlasUsage();(d=.85<a&&4096>b.size.width)&&this.resizeAtlas(2*b.size.width,2*b.size.height);for(var f in this.elementsToRemove)0===this.stageObjects[f].length&&this.removeAtlasElement(this.elementsToRemove[f]),delete this.elementsToRemove[f];if(!c||!d&&.95<a&&4096===b.size.width)return 0;for(var l in this.elements)b=this.elements[l],
b.rendered=!1,this.elementsToAdd[l]=b,delete this.elements[l];this.resetAtlasCursor();this.elementsToRender={};return 1}return 0};d.prototype.processRenderingRequest=function(a){var c=a.textId;this.ctx.clearRect(a.placement.offset.x,a.placement.offset.y,a.placement.size.width,a.placement.size.height);a.textTexture.renderText(a.placement.size.width,a.placement.size.height,this.ctx,a.placement.offset.x,a.placement.offset.y);for(var b=0,c=this.stageObjects[c];b<c.length;b++){var d=c[b];d.geometries[0].data.vertexAttributes.uv0.data=
new Float32Array(a.placement.uvMinMax);d.geometries[0].data.vertexAttributes.size.data=new Float32Array([a.placement.size.width,a.placement.size.height]);d.geometryVertexAttrsUpdated(0)}a.rendered=!0};d.prototype.run=function(a){if(this.dirty&&this.glTexture){var c=a.budget,b;for(b in this.elementsToAdd)if(this.elements[b]&&this.elements[b].rendered){for(var d=0,g=this.stageObjects[b];d<g.length;d++){var e=g[d],f=e.geometries[0].data.vertexAttributes;f.uv0.data=new Float32Array(this.elements[b].placement.uvMinMax);
f.size.data=new Float32Array([this.elements[b].placement.size.width,this.elements[b].placement.size.height]);e.geometryVertexAttrsUpdated(0)}delete this.elementsToAdd[b]}else if(1===this.processAdditionRequest(this.elementsToAdd[b],a)){a.budget=null;a.repackingEnabled=!1;this.run(a);return}a=!1;for(b in this.elementsToRender){if(c&&!c.remaining()){a&&this.glTexture.setData(this.canvas);return}this.processRenderingRequest(this.elementsToRender[b]);delete this.elementsToRender[b];a=!0}a&&this.glTexture.setData(this.canvas);
this.dirty=!1;this.frameWorker.remove();this.frameWorker=null}};d.prototype.makeRunContext=function(a){void 0===a&&(a=null);f.budget=a;f.repackingEnabled=!0;return f};d.prototype.addTextTexture=function(a,c){var b=this.generateTextId(a);this.elementsToAdd[b]||(this.elementsToAdd[b]={textId:b,placement:{offset:{x:0,y:0},size:{width:0,height:0},uvMinMax:[]},textTexture:a,rendered:!1});this.addStageObject(b,c);delete this.elementsToRemove[b];this.setDirty()};d.prototype.removeTextTexture=function(a,
c){a=this.generateTextId(a);this.elementsToRemove[a]=this.elements[a];this.removeStageObject(a,c);delete this.elementsToAdd[a]};Object.defineProperty(d.prototype,"textureId",{get:function(){return this.id},enumerable:!0,configurable:!0});Object.defineProperty(d.prototype,"isDirty",{get:function(){return this.dirty},enumerable:!0,configurable:!0});d.prototype.setDirty=function(){var a=this;this.dirty||(this.dirty=!0,this.frameWorker=this.controller.registerFrameWorker(function(c){return a.run(a.makeRunContext(c))}))};
return d}()});