// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","../../lib/gl-matrix","../../support/geometryUtils","../../support/mathUtils"],function(S,c,e,r,q){function C(a,b){if(!a)throw a=Error("dummy"),a.stack&&console.log(a.stack),new D(b);}function E(a,b,d){e.mat4d.multiply(b,a,y);e.mat4d.inverse(y);for(a=0;8>a;++a)e.mat4d.multiplyVec4(y,K[a],f),e.vec3d.set3(f[0]/f[3],f[1]/f[3],f[2]/f[3],d[a])}function F(a,b){r.plane.fromPoints(a[4],a[0],a[3],b[0]);r.plane.fromPoints(a[1],a[5],a[6],b[1]);r.plane.fromPoints(a[4],a[5],a[1],b[2]);
r.plane.fromPoints(a[3],a[2],a[6],b[3]);r.plane.fromPoints(a[0],a[1],a[2],b[4]);r.plane.fromPoints(a[5],a[4],a[7],b[5])}function G(a){for(var b in a)return b}function H(a,b){a[12]=b[0];a[13]=b[1];a[14]=b[2]}function I(a,b){void 0===b&&(b=0);for(var d=0,g=0;4>g;g++)d+=a[b+g]*L[g];return d}function M(a){return a-Math.floor(a)}Object.defineProperty(c,"__esModule",{value:!0});var y=e.mat4d.create(),K=[e.vec4d.createFrom(-1,-1,-1,1),e.vec4d.createFrom(1,-1,-1,1),e.vec4d.createFrom(1,1,-1,1),e.vec4d.createFrom(-1,
1,-1,1),e.vec4d.createFrom(-1,-1,1,1),e.vec4d.createFrom(1,-1,1,1),e.vec4d.createFrom(1,1,1,1),e.vec4d.createFrom(-1,1,1,1)],f=e.vec4d.create(),N=[e.vec3d.create(),e.vec3d.create(),e.vec3d.create(),e.vec3d.create(),e.vec3d.create(),e.vec3d.create(),e.vec3d.create(),e.vec3d.create()],O=e.vec3d.create(),n=e.vec3d.create(),h=e.vec3d.create(),k=e.vec3d.create(),v=e.vec3d.create(),w=e.vec3d.create(),z=e.vec3d.create(),A=e.vec3d.create(),t=e.vec3d.create(),m=e.vec3d.create(),u=e.vec3d.create(),x=e.vec3d.create(),
P=e.vec3d.createFrom(0,0,0),D=function(){function a(a){this.message=a}a.prototype.toString=function(){return"AssertException: "+this.message};return a}();c.AssertException=D;c.VertexAttrConstants={POSITION:"position",NORMAL:"normal",NORMALCOMPRESSED:"normalCompressed",UV0:"uv0",AUXPOS1:"auxpos1",AUXPOS2:"auxpos2",COLOR:"color",SYMBOLCOLOR:"symbolColor",SIZE:"size",REGION:"region",COMPONENTINDEX:"componentIndex"};c.assert=C;c.verify=function(a,b){a||(console.log("Verify failed: "+b),console.log(Error("dummy").stack))};
c.encodeInt16=function(a){return q.clamp(Math.round(32767*a),-32767,32767)};c.encodeNormal=function(a,b){var d=Math.abs(a[0]),g=Math.abs(a[1]),l=1/(d+g+Math.abs(a[2])),e=Math.min(a[2]*l,0);b[0]=(0>a[0]?-1:1)*(d*l-e);b[1]=(0>a[1]?-1:1)*(g*l-e)};c.fallbackIfUndefined=function(a,b){return void 0===a?b:a};c.hex2rgb=function(a){a=Math.floor(a);return[(a>>16&255)/255,(a>>8&255)/255,(a&255)/255]};c.rgb2hex=function(a){var b=q.clamp(Math.round(255*a[0]),0,255),d=q.clamp(Math.round(255*a[1]),0,255);a=q.clamp(Math.round(255*
a[2]),0,255);return"0x"+((b<<16)+(d<<8)+a).toString(16)};c.dec2hex=function(a){a=a.toString(16);return"00000000".substr(0,8-a.length)+a};c.raySphere=function(a,b,d,g,l){d=d||P;var c=e.vec3d.subtract(a,d,O);d=e.vec3d.dot(b,b);var p=2*e.vec3d.dot(b,c);g=e.vec3d.dot(c,c)-g*g;g=p*p-4*d*g;if(0>g)return!1;c=Math.sqrt(g);g=(-p-c)/(2*d);d=(-p+c)/(2*d);if(0>g||d<g&&0<d)g=d;return 0<g?(l&&e.vec3d.add(a,e.vec3d.scale(b,g,x),l),!0):!1};c.rayTriangle3D=function(a,b,d,g,l,c,p,f,h){void 0===h&&(h=e.vec3d.create());
var k=g[p]-d[c],B=g[p+1]-d[c+1],m=g[p+2]-d[c+2];g=l[f]-d[c];p=l[f+1]-d[c+1];l=l[f+2]-d[c+2];var n=b[1]*l-p*b[2],J=b[2]*g-l*b[0],q=b[0]*p-g*b[1];f=k*n+B*J+m*q;if(-1E-5<f&&1E-5>f)return!1;f=1/f;var r=a[0]-d[c],t=a[1]-d[c+1];a=a[2]-d[c+2];h[1]=f*(r*n+t*J+a*q);if(0>h[1]||1<h[1])return!1;d=t*m-B*a;a=a*k-m*r;k=r*B-k*t;h[2]=f*(b[0]*d+b[1]*a+b[2]*k);if(0>h[2]||1<h[1]+h[2])return!1;h[0]=f*(g*d+p*a+l*k);return!0};c.rayBoxTest=function(a,b,d,g){var e,c=(d[0]-a[0])/b[0],f=(g[0]-a[0])/b[0];c>f&&(e=c,c=f,f=e);
var h=(d[1]-a[1])/b[1],k=(g[1]-a[1])/b[1];h>k&&(e=h,h=k,k=e);if(c>k||h>f)return!1;h>c&&(c=h);k<f&&(f=k);d=(d[2]-a[2])/b[2];a=(g[2]-a[2])/b[2];d>a&&(e=d,d=a,a=e);if(c>a||d>f)return!1;a<f&&(f=a);return 0>f?!1:!0};c.rayRay2D=function(a,b,d,g,c,f){void 0===f&&(f=e.vec2d.create());var l=(g[c]-d[c])*(b[0]-a[0])-(g[0]-d[0])*(b[c]-a[c]);if(0===l)return!1;d=((g[0]-d[0])*(a[c]-d[c])-(g[c]-d[c])*(a[0]-d[0]))/l;f[0]=a[0]+d*(b[0]-a[0]);f[1]=a[c]+d*(b[c]-a[c]);return!0};c.matrixToFrustumPoints=E;c.matrixToFrustumPlanes=
function(a,b,d,c){void 0===c&&(c=d,d=N);E(a,b,d);F(d,c)};c.frustumPointsToPlanes=F;c.project=function(a,b,d,c,l){l||(l=a);f[0]=a[0];f[1]=a[1];f[2]=a[2];f[3]=1;e.mat4d.multiplyVec4(b,f);2<l.length&&(l[2]=-f[2]);e.mat4d.multiplyVec4(d,f);C(0!==f[3]);l[0]=f[0]/f[3];l[1]=f[1]/f[3];l[2]=f[2]/f[3];l[0]=(.5*l[0]+.5)*c[2]+c[0];l[1]=(.5*l[1]+.5)*c[3]+c[1]};c.getFirstObjectKey=G;c.getFirstObjectValue=function(a){return a[G(a)]};c.objectEmpty=function(a){for(var b in a)return!1;return!0};c.logWithBase=function(a,
b){return Math.log(a)/Math.log(b)};c.setMatrixTranslation=H;c.setMatrixTranslation3=function(a,b,d,c){a[12]=b;a[13]=d;a[14]=c};c.getMatrixTranslation=function(a,b){void 0===b&&(b=e.vec3d.create());b[0]=a[12];b[1]=a[13];b[2]=a[14];return b};c.createTranslationMatrix=function(a,b){a=e.mat4d.identity(a);H(a,b);return a};c.isTranslationMatrix=function(a){return 1===a[0]&&0===a[1]&&0===a[2]&&0===a[3]&&0===a[4]&&1===a[5]&&0===a[6]&&0===a[7]&&0===a[8]&&0===a[9]&&1===a[10]&&0===a[11]&&1===a[15]};c.fovx2fovy=
function(a,b,d){return 2*Math.atan(d*Math.tan(.5*a)/b)};c.fovy2fovx=function(a,b,d){return 2*Math.atan(b*Math.tan(.5*a)/d)};c.fovx2fovd=function(a,b,d){return 2*Math.atan(Math.sqrt(b*b+d*d)*Math.tan(.5*a)/b)};c.fovy2fovd=function(a,b,d){return 2*Math.atan(Math.sqrt(b*b+d*d)*Math.tan(.5*a)/d)};c.fovd2fovx=function(a,b,d){return 2*Math.atan(b*Math.tan(.5*a)/Math.sqrt(b*b+d*d))};c.fovd2fovy=function(a,b,d){return 2*Math.atan(d*Math.tan(.5*a)/Math.sqrt(b*b+d*d))};c.lineLineDistanceSquared3D=function(a,
b,d,c,f){n[0]=a[0]-d[0];n[1]=a[1]-d[1];n[2]=a[2]-d[2];h[0]=c[0]-d[0];h[1]=c[1]-d[1];h[2]=c[2]-d[2];if(1E-4>Math.abs(h[0])&&1E-4>Math.abs(h[1])&&1E-4>Math.abs(h[2]))return f.success=!1,f;k[0]=b[0]-a[0];k[1]=b[1]-a[1];k[2]=b[2]-a[2];if(1E-4>Math.abs(k[0])&&1E-4>Math.abs(k[1])&&1E-4>Math.abs(k[2]))return f.success=!1,f;b=n[0]*h[0]+n[1]*h[1]+n[2]*h[2];c=h[0]*k[0]+h[1]*k[1]+h[2]*k[2];var g=n[0]*k[0]+n[1]*k[1]+n[2]*k[2],l=h[0]*h[0]+h[1]*h[1]+h[2]*h[2],m=(k[0]*k[0]+k[1]*k[1]+k[2]*k[2])*l-c*c;if(1E-4>Math.abs(m))return f.success=
!1,f;g=q.clamp((b*c-g*l)/m,0,1);b=q.clamp((b+c*g)/l,0,1);v[0]=a[0]+g*k[0];v[1]=a[1]+g*k[1];v[2]=a[2]+g*k[2];w[0]=d[0]+b*h[0];w[1]=d[1]+b*h[1];w[2]=d[2]+b*h[2];a=e.vec3d.dist2(v,w);f.success=!0;f.dist2=a;f.pa=v;f.pb=w;return f};c.pointLineSegmentDistanceSquared2D=function(a,b,d){m[0]=b[0]-a[0];m[1]=b[1]-a[1];m[2]=0;u[0]=d[0]-a[0];u[1]=d[1]-a[1];u[2]=0;x[0]=d[0];x[1]=d[1];x[2]=0;b=e.vec2d.dot(u,m);d=e.vec2d.dot(m,m);b=q.clamp(b/d,0,1);t[0]=m[0]*b;t[1]=m[1]*b;z[0]=a[0]+t[0];z[1]=a[1]+t[1];e.vec2d.subtract(x,
z,A);a=e.vec2d.dot(A,A);b=e.vec2d.dot(u,u);d=e.vec2d.dot(m,m);var c=e.vec2d.dot(t,t);if(c>b||c>d)a=Number.MAX_VALUE;return a};c.packFloatRGBA=function(a,b,d){void 0===d&&(d=0);a=q.clamp(a,0,Q);for(var c=0;4>c;c++)b[d+c]=Math.floor(256*M(a*R[c]))};c.unpackFloatRGBA=I;var R=[1,256,65536,16777216],L=[1/256,1/65536,1/16777216,1/4294967296],Q=I(new Uint8ClampedArray([255,255,255,255]));c.inverseProjectionInfo=function(a,b,d,c,f){0===a[11]?(c[0]=2/(b*a[0]),c[1]=2/(d*a[5]),c[2]=(1+a[12])/a[0],c[3]=(1+a[13])/
a[5],e.vec2d.set2(0,1,f)):(c[0]=-2/(b*a[0]),c[1]=-2/(d*a[5]),c[2]=(1-a[8])/a[0],c[3]=(1-a[9])/a[5],e.vec2d.set2(1,0,f))}});