// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/tsSupport/assignHelper @dojo/framework/shim/array @dojo/framework/shim/Map ../../../../../geometry ../../../../../request ../../../../../core/Error ../../../../../core/Logger ../../../../../core/promiseUtils ../../../../../core/throttle ../../../../../core/accessorSupport/decorators ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/data/DefaultSpatialIndex ../../../../../layers/graphics/data/QueryEngine ../../../../../tasks/operations/query ../../../../../tasks/support/Query ./BaseController ./support/DispatchQueue".split(" "),
function(q,r,x,h,y,z,t,u,A,k,B,g,C,d,v,D,E,F,l,G,H){function w(d){for(var b=0,a=0;a<d.length;a++)b=(b<<5)-b+d.charCodeAt(a),b|=0;return b}Object.defineProperty(r,"__esModule",{value:!0});var m=B.getLogger("esri.views.2d.layers.features.controllers.StreamController");q=function(n){function b(){var a=null!==n&&n.apply(this,arguments)||this;a.errorString=null;a._started=!1;a._idCounter=0;a._tileDispatchMap=new t.default;a._updateIntervalId=0;a._reconnectWebSocketT=C.throttle(a._reconnectWebSocket,5E3,
a);a._featureIds=[];return a}x(b,n);b.prototype.initialize=function(){var a=this;this.handles.add(this.watch("processor",this._switchProcessor.bind(this)));["connectionStatus","errorString"].forEach(function(c){a.watch(c,function(b){return a.remoteClient.invoke("setProperty",{propertyName:c,value:b})})});this._updateIntervalId=setInterval(function(){return a._checkForUpdates()},64)};b.prototype.destroy=function(){clearInterval(this._updateIntervalId);this._destroyWebSocket();this._tileDispatchMap.forEach(function(a){return a.destroy()});
this.queryEngine&&(this.queryEngine.destroy(),this._set("queryEngine",null));this._tempQueryEngine&&this._tempQueryEngine.destroy()};Object.defineProperty(b.prototype,"updating",{get:function(){return!this._started||this._tempQueryEngine&&!!this._tempQueryEngine.spatialIndex.numFeatures||this._anyUpdatesQueued()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"connectionStatus",{get:function(){if(!this._websocket)return"disconnected";switch(this._websocket.readyState){case 0:case 1:return"connected";
case 2:case 3:return"disconnected"}},enumerable:!0,configurable:!0});b.prototype.onEdits=function(a){};b.prototype.redraw=function(){};b.prototype.refresh=function(){};b.prototype.setViewState=function(a){};b.prototype.queryFeatures=function(a){return this.queryEngine.executeQuery(l.fromJSON(a))};b.prototype.queryFeatureCount=function(a){return this.queryEngine.executeQueryForCount(l.fromJSON(a))};b.prototype.queryObjectIds=function(a){return this.queryEngine.executeQueryForIds(l.fromJSON(a))};b.prototype.queryExtent=
function(a){return this.queryEngine.executeQueryForExtent(l.fromJSON(a))};b.prototype.queryLatestObservations=function(a){return this.queryEngine.executeQueryForLatestObservations(l.fromJSON(a))};b.prototype.onTileUpdate=function(a){var c=this,b=a.added;this._started&&(a.removed.forEach(function(a){return c._handleTileRemove(a)}),b.forEach(function(a){return c._handleTileAdd(a)}))};b.prototype.enableEvent=function(a){"data-received"===a.name&&(this._shouldPushDataReceived=a.value)};b.prototype._start=
function(){var a=this;this._started||this._queryBuddies().then(function(){a._startWebSocket();a.tileStore.tiles.forEach(function(c){return a._handleTileAdd(c)});a._started=!0;a._updateActiveTiles(a.queryEngine)})};b.prototype._getService=function(){var a=y({},this.service.content,{f:"json"});return A(this.service.source,{query:a,responseType:"json"}).then(function(a){return a.data})};b.prototype._startWebSocket=function(){var a=this;this._getService().then(function(c){return a._createWebSocket(c)}).then(function(c){return a._setFilter(c)}).catch(function(a){return m.error(k("stream-socket",
"Encountered an error while creating listening stream",a))})};b.prototype._destroyWebSocket=function(){this._websocket&&(this._websocket.onmessage=null,this._websocket.onerror=null,this._websocket.onopen=null,this._websocket.onclose=null,this._websocket.close(),this.notifyChange("connectionStatus"))};b.prototype._createWebSocket=function(a){var c=this;return g.create(function(b){for(var e=a.streamUrls.filter(function(a){return"ws"===a.transport})[0],I=e.token,d=null,h=null,p=0,e=e.urls;p<e.length;p++){var k=
e[p];-1!==k.indexOf("wss")?d=k:h=k}var g=new WebSocket((d||h)+"/subscribe?token\x3d"+I+"\x26outSR\x3d"+c.spatialReference.wkid);g.onopen=function(){c.notifyChange("connectionStatus");b(g)};g.onmessage=c._handleWebSocketMessage.bind(c);g.onclose=c._handleWebSocketClose.bind(c);c._destroyWebSocket();c._websocket=g})};b.prototype._setFilter=function(a){var c=this,b={},f=this.processor.queryInfo.outFields;this.configuration.filter.geometry&&(b.geometry=JSON.stringify(this.configuration.filter.geometry));
this.configuration.filter.where&&(b.where=this.configuration.filter.where);.75<=f.length/this.service.fields.length&&(b.outFields=f.join(","));b.geometry||b.where||b.outFields||g.resolve();return g.create(function(e,f){var d=a.onmessage;a.onmessage=function(b){b=JSON.parse(b.data);b.filter&&(a.onmessage=d,b.error?(c.set("errorString","Could not set filter - "+b.error),f(k("stream-socket-filter",c.errorString,{activeFilter:b.filter}))):e())};a.send(JSON.stringify({filter:b}))})};b.prototype._reconnectWebSocket=
function(a){this.set("errorString","Lost websocket connection - "+a+", attempting to reconnect");m.error(k("stream-socket",this.errorString));this._startWebSocket()};b.prototype._handleWebSocketClose=function(a){a=a.code;this.notifyChange("connectionStatus");if(1001===a||4E3<=a){var c=this._getErrorMessage(a);this.set("errorString","Encountered a service error "+a+" - "+c+", terminating websocket connection");m.error(k("stream-socket",this.errorString))}else 1E3!==a&&this._reconnectWebSocketT(a)};
b.prototype._getErrorMessage=function(a){switch(a){case 1001:return"Service is going away";case 4400:return"Invalid URL parameters. Check filter properties.";case 4401:case 4403:return"Not authorized";case 4404:return"Service not found";default:return"Encountered error code "+a}};b.prototype._handleWebSocketMessage=function(a){try{var c=JSON.parse(a.data);this._shouldPushDataReceived&&this.remoteClient.invoke("emitEvent",{name:"data-received",event:c});this._normalizeFeatureId(c);this._enrichFeature(c);
if(c.geometry||c.centroid){var b=v.convertFromFeature(c,this.service.geometryType,!1,!1,this.service.objectIdField);this._featureIds.push(b.attributes[this.service.objectIdField]);this._tempQueryEngine.spatialIndex.add(b)}else m.error(k("stream-socket","Found malformed feature"))}catch(f){m.error(k("stream-socket","Encountered an error when parsing socket message",f))}};b.prototype._handleTileAdd=function(a){if(this._tileDispatchMap.has(a.id)){var c=this._tileDispatchMap.get(a.id);c.up()}else c=new H.default,
this._tileDispatchMap.set(a.id,c);this._queryTileFeatures(a,!0,this.queryEngine)};b.prototype._handleTileRemove=function(a){this._tileDispatchMap.get(a.id).destroy();this._tileDispatchMap.delete(a.id)};b.prototype._checkForUpdates=function(){if(this._started){var a=this._getFeaturesToAdd(),c=this._getFeaturesToRemove(),b=a.spatialIndex.getAllFeatures();c.spatialIndex.addMany(b);this.processor.supportsTileUpdates?(this._updateActiveTiles(a,c),a.spatialIndex.transferAll(this.queryEngine.spatialIndex)):
(a.spatialIndex.transferAll(this.queryEngine.spatialIndex),this._repushActiveTiles(a,c));c.destroy()}};b.prototype._anyUpdatesQueued=function(){return z.from(this._tileDispatchMap).some(function(a){return a[1].hasAction()})};b.prototype._updateActiveTiles=function(a,c){for(var b=0,f=this.tileStore.tiles;b<f.length;b++)this._queryTileFeatures(f[b],!1,a,c)};b.prototype._repushActiveTiles=function(a,c){a=0;for(c=this.tileStore.tiles;a<c.length;a++)this._queryTileFeatures(c[a],!0,this.queryEngine)};b.prototype._getFeaturesToAdd=
function(){return this._tempQueryEngine};b.prototype._getFeaturesToRemove=function(){var a=this.configuration.purgeOptions,c=a.displayCount,a=a.age,b=this._createQueryEngine();this._purgeByDisplayCount(c,b);this._purgeByAge(a,b);return b};b.prototype._purgeByDisplayCount=function(a,c){if(null!=a){var b=this.queryEngine.spatialIndex.numFeatures;b>a&&(a=this._featureIds.splice(0,b-a),this.queryEngine.spatialIndex.transferIds(c.spatialIndex,a))}};b.prototype._purgeByAge=function(a,b){if(null==a)return g.resolve();
a*=6E4;var c=Date.now()-a,f=this.service.timeInfo.startTimeField;this.queryEngine.spatialIndex.transferIf(b.spatialIndex,function(a){return a.attributes[f]<c})};b.prototype._queryTileFeatures=function(a,b,e,f){var c=this,d=this.processor.queryInfo,d={returnCentroid:d.returnCentroid,returnGeometry:d.returnGeometry,pixelBuffer:d.pixelBuffer},g=this._tileDispatchMap.get(a.id),h=e&&e.executeTileQuery(a,d).features,k=f&&f.executeTileQueryForIds(a,d);g.enqueue(function(){return c.processor.onTileData(a,
{addOrUpdate:h,remove:k,clear:b})})};b.prototype._queryBuddies=function(){var a=this,b=this.service.buddyLayers,e=b.keepLatestArchive,b=this._queryBuddy(b.relatedFeatures),e=this._queryBuddy(e);return g.all([b,e]).then(function(b){return a._addBuddyFeatures(b[0],b[1])})};b.prototype._queryBuddy=function(a){if(!a)return g.resolve();var b=this._createQuery(this.processor.queryInfo);return F.executeQuery(a.source,b).then(function(a){return a.data})};b.prototype._addBuddyFeatures=function(a,b){a&&this._setEnrichmentData(a);
b&&this._addFeatures(b)};b.prototype._setEnrichmentData=function(a){a=a.features;for(var b=new t.default,e=this.service.buddyLayers.relatedFeatures.joinField,f=0;f<a.length;f++){var d=a[f];e===this.service.objectIdField&&"string"===typeof e&&(d.attributes[e]=w(d.attributes[e]));b.set(d.attributes[e],d)}this._enrichmentData=b};b.prototype._enrichFeature=function(a){if(!this._enrichmentData)return a;var b=a.attributes[this.service.buddyLayers.relatedFeatures.joinField];if(this._enrichmentData.has(b)){var e=
this._enrichmentData.get(b),b=e.attributes,e=e.geometry,d;for(d in b)a.attributes[d]=b[d];e&&(a.geometry=e)}return a};b.prototype._normalizeFeatureId=function(a){var b;b="__OBJECTID"===this.service.objectIdField?this._idCounter++:"string"===typeof a.attributes[this.service.objectIdField]?w(a.attributes[this.service.objectIdField]):a.attributes[this.service.objectIdField];a.attributes[this.service.objectIdField]=b};b.prototype._addFeatures=function(a){a.objectIdFieldName=this.service.objectIdField;
for(var b=0,d=a.features;b<d.length;b++){var f=d[b];this._normalizeFeatureId(f);this._enrichFeature(f)}a=v.convertFromFeatureSet(a).features;this.queryEngine.spatialIndex.addMany(a)};b.prototype._createQuery=function(a){var b=new l,d=a.historicMoment,f=a.outFields;b.historicMoment=null!=d?new Date(d):null;b.outFields=.75<=f.length/this.service.fields.length?["*"]:f;b.returnExceededLimitFeatures=!0;b.returnGeometry=!0;b.gdbVersion=a.gdbVersion;b.returnCentroid=a.returnCentroid;b.orderByFields=a.orderByFields;
b.outSpatialReference=u.SpatialReference.fromJSON(this.spatialReference);b.where=this.configuration.filter.where||"1\x3d1";this.configuration.filter.geometry&&(b.geometry=u.Extent.fromJSON(this.configuration.filter.geometry));return b};b.prototype._createQueryEngine=function(){var a=this.processor.queryInfo,b=a.historicMoment;return new E.default({definitionExpression:a.definitionExpression,fields:this.service.fields,geometryType:this.service.geometryType,objectIdField:this.service.objectIdField,
hasM:!1,hasZ:!1,spatialReference:this.spatialReference,cacheSpatialQueries:!0,gdbVersion:a.gdbVersion,historicMoment:null!=b&&new Date(b),spatialIndex:new D.default({geometryType:this.service.geometryType,hasM:!1,hasZ:!1}),timeInfo:this.service.timeInfo})};b.prototype._resetTempStore=function(){this._tempQueryEngine&&this._tempQueryEngine.destroy();this._tempQueryEngine=this._createQueryEngine()};b.prototype._switchProcessor=function(a,b){this.queryEngine&&this.queryEngine.destroy();this._set("queryEngine",
this._createQueryEngine());this._resetTempStore();this._start();this.notifyChange("updating")};h([d.property()],b.prototype,"service",void 0);h([d.property()],b.prototype,"configuration",void 0);h([d.property({readOnly:!0})],b.prototype,"queryEngine",void 0);h([d.property()],b.prototype,"updating",null);h([d.property()],b.prototype,"connectionStatus",null);h([d.property()],b.prototype,"errorString",void 0);return b=h([d.subclass()],b)}(d.declared(G.default));r.default=q});