// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/arrayUtils ../../core/Evented ../../core/lang ../../core/ObjectPool ../../core/accessorSupport/decorators ./FieldConfig ./InputField".split(" "),function(v,w,m,c,n,k,p,q,r,d,t,u){return function(l){function b(a){a=l.call(this)||this;a._fieldPool=new r(u);a._featureClone=null;a.fieldConfig=null;a.strict=!1;return a}m(b,l);Object.defineProperty(b.prototype,"feature",{get:function(){return this._get("feature")},
set:function(a){this._featureClone=a?a.clone():null;this._set("feature",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"inputFields",{get:function(){var a=this,b=this._fieldPool,d=this._featureClone,g=this.layer,c=this._get("inputFields");c&&c.forEach(function(a){return b.release(a)});if("ready"!==this.state)return[];var e=this.get("layer.fields")||[],c=this.fieldConfig||[];return(0!==c.length?c.map(function(c){var f=k.find(e,function(a){return a.name===c.name}),h=b.acquire();
h.set({field:f,config:c,feature:d,layer:g,value:a.getValue(f.name)});return h}):e.map(function(c){var f=b.acquire();f.field=c;f.layer=g;f.feature=d;f.value=a.getValue(c.name);return f})).filter(function(a){return a.visible})},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"layer",{get:function(){return this.get("feature.layer")},set:function(a){a?this._override("layer",a):this._clearOverride("layer")},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"state",{get:function(){return this.get("layer.loaded")&&
this.feature?"ready":"disabled"},enumerable:!0,configurable:!0});b.prototype.getValue=function(a){var b=this._featureClone;return b&&b.get("attributes."+a)};b.prototype.setValue=function(a,b){var c=this,g=this._featureClone,d=this.strict;if(g&&g.attributes){var e=k.find(this.inputFields,function(b){return b.name===a});if(e&&g.attributes[a]!==b){e.value=b;if(this.get("layer.typeIdField")===e.name){var h=new Set;this.layer.types.forEach(function(a){return Object.keys(a.domains).forEach(function(a){return h.add(a)})});
h&&h.forEach(function(a){var b=k.find(c.inputFields,function(b){return b.name===a});b&&b.notifyChange("domain")})}if(!d||e.valid)g.attributes[a]=b,this._emitChangeEvent(e)}}};b.prototype.getValues=function(){var a=this._featureClone;return a&&q.clone(a.attributes)||null};b.prototype.submit=function(){var a=this.inputFields.filter(function(a){return a.valid}).map(function(a){return a.name}),b=this.inputFields.filter(function(a){return!a.valid}).map(function(a){return a.name}),c=this.getValues();this.emit("submit",
{valid:a,invalid:b,values:c})};b.prototype._emitChangeEvent=function(a){this.emit("value-change",{layer:this.layer,feature:this.feature,fieldName:a.name,value:a.value,valid:a.valid})};c([d.property()],b.prototype,"feature",null);c([d.property({type:[t]})],b.prototype,"fieldConfig",void 0);c([d.property({readOnly:!0,dependsOn:["feature","fieldConfig","layer.fields","layer.loaded"]})],b.prototype,"inputFields",null);c([d.property({dependsOn:["feature.layer"]})],b.prototype,"layer",null);c([d.property({dependsOn:["layer.loaded",
"feature"]})],b.prototype,"state",null);c([d.property()],b.prototype,"strict",void 0);c([d.property()],b.prototype,"getValues",null);c([d.property()],b.prototype,"submit",null);return b=c([d.subclass("esri.widgets.FeatureForm.FeatureFormViewModel")],b)}(d.declared(n,p))});