// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/awaiterHelper ../../../../core/tsSupport/generatorHelper ../../../../core/tsSupport/assignHelper ../../../../core/lang ../../../../core/promiseUtils ../../../../core/urlUtils ../../../../core/Version ./BinaryStreamReader ./fillDefaults ./pathUtils ../../lib/gl-matrix ../../support/buffer/BufferView ../../support/buffer/bufferViewUtil".split(" "),function(v,w,h,m,L,x,y,C,z,D,A,E,l,q,B){function F(d){return h(this,void 0,void 0,function(){return m(this,
function(c){return[2,y.create(function(b,a){var c=new Blob([d]),f=new FileReader;f.onload=function(){b(JSON.parse(f.result))};f.onerror=function(b){a(b)};f.readAsText(c)})]})})}function G(d,c){return h(this,void 0,void 0,function(){return m(this,function(b){return[2,y.create(function(a,b){var e=new Blob([d],{type:c}),k=URL.createObjectURL(e),g=new Image;g.addEventListener("load",function(){URL.revokeObjectURL(k);a(g)});g.addEventListener("error",function(a){URL.revokeObjectURL(k);b(a)});g.src=k})]})})}
Object.defineProperty(w,"__esModule",{value:!0});var p;v=function(){function d(c,b,a,e,f){this.context=c;this.errorContext=b;this.uri=a;this.json=e;this.glbBuffer=f;this.bufferCache=new Map;this.textureCache=new Map;this.materialCache=new Map;this.nodeParentMap=new Map;this.nodeTransformCache=new Map;this.baseUri=E.splitURI(this.uri).dirPart;this.checkVersionSupported();this.checkRequiredExtensionsSupported();b.errorUnsupportedIf(null==e.scene,"A scene must be defined.");b.errorUnsupportedIf(null==
e.scenes,"Scenes must be defined.");b.errorUnsupportedIf(null==e.meshes,"Meshes must be defined");b.errorUnsupportedIf(null==e.nodes,"Nodes must be defined.");this.computeNodeParents()}d.load=function(c,b,a){return h(this,void 0,void 0,function(){var e,f,k;return m(this,function(g){switch(g.label){case 0:return x.endsWith(a,".gltf")?[4,c.loadJson(a)]:[3,2];case 1:return e=g.sent(),[2,new d(c,b,a,e)];case 2:return x.endsWith(a,".glb")?[4,c.loadBinary(a)]:[3,5];case 3:return f=g.sent(),[4,d.parseGLB(b,
f)];case 4:return k=g.sent(),[2,new d(c,b,a,k.json,k.binaryData)];case 5:b.error('URI needs to end in ".gltf" or ".glb"'),g.label=6;case 6:return[2]}})})};d.parseGLB=function(c,b){return h(this,void 0,void 0,function(){var a,e,f,k,g,d,h,r,l;return m(this,function(n){switch(n.label){case 0:a=new D.BinaryStreamReader(b),c.assert(12<=a.remainingBytes(),"GLB binary data is insufficiently large."),e=a.readUint32(),f=a.readUint32(),k=a.readUint32(),c.assert(1179937895===e,"Magic first 4 bytes do not fit to expected GLB value."),
c.assert(b.byteLength>=k,"GLB binary data is smalller than header specifies."),c.errorUnsupportedIf(2!==f,"Only GLB container version 2 is supported."),g=0,n.label=1;case 1:if(!(8<=a.remainingBytes()))return[3,5];r=a.readUint32();l=a.readUint32();if(0!==g)return[3,3];c.assert(1313821514===l,"First GLB chunck must be JSON.");c.assert(0<=r,"No JSON data found.");return[4,F(a.readUint8Array(r))];case 2:return d=n.sent(),[3,4];case 3:1===g?(c.errorUnsupportedIf(5130562!==l,"Second GLB chunck expected to be BIN."),
h=a.readUint8Array(r)):c.warnUnsupported("More than 2 GLB chunks detected. Skipping."),n.label=4;case 4:return g+=1,[3,1];case 5:return d||c.error("No GLB JSON chunk detected."),[2,{json:d,binaryData:h}]}})})};d.prototype.getBuffer=function(c){return h(this,void 0,void 0,function(){var b,a,e,f;return m(this,function(d){switch(d.label){case 0:return b=this.json.buffers[c],a=this.errorContext,null==b.uri?(a.assert(null!=this.glbBuffer,"GLB buffer not present"),[2,this.glbBuffer]):(e=this.bufferCache.get(c))?
[3,2]:[4,this.context.loadBinary(this.resolveUri(b.uri))];case 1:f=d.sent(),e=new Uint8Array(f),this.bufferCache.set(c,e),a.assert(e.byteLength===b.byteLength,"Buffer byte lengths should match."),d.label=2;case 2:return[2,e]}})})};d.prototype.getAccessor=function(c){return h(this,void 0,void 0,function(){var b,a,e,f,d,g,n,h;return m(this,function(k){switch(k.label){case 0:return b=this.json.accessors[c],a=this.errorContext,a.errorUnsupportedIf(null==b.bufferView,"An accessor bufferView is required."),
a.errorUnsupportedIf(b.type in["MAT2","MAT3","MAT4"],"AttributeType "+b.type+" is not supported"),e=this.json.bufferViews[b.bufferView],[4,this.getBuffer(e.buffer)];case 1:return f=k.sent(),d=H[b.type],g=I[b.componentType],n=d*g,h=e.byteStride||n,[2,{raw:f.buffer,byteStride:h,byteOffset:f.byteOffset+(e.byteOffset||0)+(b.byteOffset||0),entryCount:b.count,isDenselyPacked:h===n,componentCount:d,componentByteSize:g,componentType:b.componentType,min:b.min,max:b.max}]}})})};d.prototype.getIndexData=function(c){return h(this,
void 0,void 0,function(){var b,a;return m(this,function(e){switch(e.label){case 0:if(null==c.indices)return[2,null];b=this.errorContext;return[4,this.getAccessor(c.indices)];case 1:a=e.sent();b.errorUnsupportedIf(5121===a.componentType,"uint8 indices are not supported.");if(a.isDenselyPacked)switch(a.componentType){case 5123:return[2,new Uint16Array(a.raw,a.byteOffset,a.entryCount)];case 5125:return[2,new Uint32Array(a.raw,a.byteOffset,a.entryCount)]}else switch(a.componentType){case 5123:return[2,
B.makeDenseSingle(new q.BufferViewUint16(a.raw,a.byteOffset,a.byteOffset+a.byteStride,a.byteStride*a.entryCount))];case 5125:return[2,B.makeDenseSingle(new q.BufferViewUint32(a.raw,a.byteOffset,a.byteOffset+a.byteStride,a.byteStride*a.entryCount))]}return[2]}})})};d.prototype.getPositionData=function(c){return h(this,void 0,void 0,function(){var b,a;return m(this,function(e){switch(e.label){case 0:return b=this.errorContext,b.errorUnsupportedIf(null==c.attributes.POSITION,"POSITION vertex data is required."),
[4,this.getAccessor(c.attributes.POSITION)];case 1:return a=e.sent(),b.errorUnsupportedIf(5126!==a.componentType,"[POSITION attribute] Expected type FLOAT, found "+t[a.componentType]),b.errorUnsupportedIf(3!==a.componentCount,"POSITION attribute must have 3 components."),[2,new q.BufferViewVec3f(a.raw,a.byteOffset,a.byteStride,a.byteOffset+a.byteStride*a.entryCount)]}})})};d.prototype.getNormalData=function(c){return h(this,void 0,void 0,function(){var b,a;return m(this,function(e){switch(e.label){case 0:return b=
this.errorContext,b.errorUnsupportedIf(null==c.attributes.NORMAL,"NORMAL vertex data is required."),[4,this.getAccessor(c.attributes.NORMAL)];case 1:return a=e.sent(),b.errorUnsupportedIf(5126!==a.componentType,"[NORMAL attribute] Expected type FLOAT, found "+t[a.componentType]),b.errorUnsupportedIf(3!==a.componentCount,"NORMAL attribute must have 3 components."),[2,new q.BufferViewVec3f(a.raw,a.byteOffset,a.byteStride,a.byteOffset+a.byteStride*a.entryCount)]}})})};d.prototype.getTextureCoordinates=
function(c){return h(this,void 0,void 0,function(){var b,a;return m(this,function(e){switch(e.label){case 0:return b=this.errorContext,b.errorUnsupportedIf(null==c.attributes.TEXCOORD_0,"TEXCOORD_0 vertex data is required."),[4,this.getAccessor(c.attributes.TEXCOORD_0)];case 1:return a=e.sent(),b.errorUnsupportedIf(5126!==a.componentType,"[TEXCOORD_0 attribute] Expected type FLOAT, found "+t[a.componentType]),b.errorUnsupportedIf(2!==a.componentCount,"TEXCOORD_0 attribute must have 2 components."),
[2,new q.BufferViewVec2f(a.raw,a.byteOffset,a.byteStride,a.byteOffset+a.byteStride*a.entryCount)]}})})};d.prototype.getVertexColors=function(c){return h(this,void 0,void 0,function(){var b,a;return m(this,function(e){switch(e.label){case 0:return b=this.errorContext,b.errorUnsupportedIf(null==c.attributes.COLOR_0,"COLOR_0 vertex data is required."),[4,this.getAccessor(c.attributes.COLOR_0)];case 1:a=e.sent();b.errorUnsupportedIf(4!==a.componentCount,"COLOR_0 attribute must have 4 components.");if(5126===
a.componentType)return[2,new q.BufferViewVec4f(a.raw,a.byteOffset,a.byteStride,a.byteOffset+a.byteStride*a.entryCount)];if(5121===a.componentType)return[2,new q.BufferViewVec4u8(a.raw,a.byteOffset,a.byteStride,a.byteOffset+a.byteStride*a.entryCount)];b.errorUnsupported("[COLOR_0 attribute] Unsupported component type: "+t[a.componentType]);return[2]}})})};d.prototype.getMaterial=function(c){return h(this,void 0,void 0,function(){var b,a,e,d,k,g;return m(this,function(f){switch(f.label){case 0:b=this.errorContext;
if(a=this.materialCache.get(c.material))return[3,3];e=A.material(this.json.materials[c.material]);d=e.pbrMetallicRoughness;k=!!c.attributes.COLOR_0;g=void 0;if(!d.baseColorTexture)return[3,2];b.errorUnsupportedIf(0!==(d.baseColorTexture.texCoord||0),"Only TEXCOORD_0 is supported");return[4,this.getTexture(d.baseColorTexture.index)];case 1:g=f.sent(),f.label=2;case 2:a={alphaMode:e.alphaMode,color:d.baseColorFactor,doubleSided:!!e.doubleSided,colorTexture:g,name:e.name,vertexColors:k},f.label=3;case 3:return[2,
a]}})})};d.prototype.getTexture=function(c){return h(this,void 0,void 0,function(){var b,a,e,d,k,g,h,l;return m(this,function(f){switch(f.label){case 0:b=this.errorContext;a=this.json.textures[c];e=A.textureSampler(a.sampler);b.errorUnsupportedIf(null==a.source,"source must be defined for a texture");d=this.json.images[a.source];if(k=this.textureCache.get(c))return[3,6];g=void 0;return d.uri?[4,this.context.loadImage(this.resolveUri(d.uri))]:[3,2];case 1:return g=f.sent(),[3,5];case 2:return b.errorUnsupportedIf(null==
d.bufferView,"Image bufferView must be defined."),b.errorUnsupportedIf(null==d.mimeType,"Image mimeType must be defined."),h=this.json.bufferViews[d.bufferView],[4,this.getBuffer(h.buffer)];case 3:return l=f.sent(),b.errorUnsupportedIf(null!=h.byteStride,"byteStride not supported for image buffer"),[4,G(new Uint8Array(l.buffer,l.byteOffset+(h.byteOffset||0),h.byteLength),d.mimeType)];case 4:g=f.sent(),f.label=5;case 5:k={data:g,wrapS:e.wrapS,wrapT:e.wrapT,minFilter:e.minFilter,name:d.name},this.textureCache.set(c,
k),f.label=6;case 6:return[2,k]}})})};d.prototype.getNodeTransform=function(c){if(void 0===c)return J;var b=this.nodeTransformCache.get(c);if(!b){var b=this.getNodeTransform(this.getNodeParent(c)),a=this.json.nodes[c];if(a.matrix)b=l.mat4d.multiply(b,a.matrix,l.mat4d.create());else if(a.translation||a.rotation||a.scale)b=l.mat4d.create(b),a.translation&&l.mat4d.translate(b,a.translation,b),a.rotation&&(l.quat4d.toAngleAxis(a.rotation,u),l.mat4d.rotate(b,u[3],u,b)),a.scale&&l.mat4d.scale(b,a.scale,
b);this.nodeTransformCache.set(c,b)}return b};d.prototype.resolveUri=function(c){return C.isDataProtocol(c)?c:this.baseUri+c};d.prototype.getNodeParent=function(c){return this.nodeParentMap.get(c)};d.prototype.checkVersionSupported=function(){z.Version.parse(this.json.asset.version,"glTF").validate(K)};d.prototype.checkRequiredExtensionsSupported=function(){var c=this.json,b=this.errorContext;c.extensionsRequired&&0!==c.extensionsRequired.length&&b.errorUnsupportedIf(!0,"Extensions: "+c.extensionsRequired.join(", "))};
d.prototype.computeNodeParents=function(){var c=this;this.json.nodes.forEach(function(b,a){b.children&&b.children.forEach(function(b){c.nodeParentMap.set(b,a)})})};return d}();w.Resource=v;var K=new z.Version(2,0,"glTF"),J=l.mat4d.rotateX(l.mat4d.identity(),Math.PI/2),u=l.quat4d.create(),H={SCALAR:1,VEC2:2,VEC3:3,VEC4:4},I=(p={},p[5120]=1,p[5121]=1,p[5122]=2,p[5123]=2,p[5126]=4,p[5125]=4,p),t={5120:"BYTE",5121:"UNSIGNED_BYTE",5122:"SHORT",5123:"UNSIGNED_SHORT",5125:"UNSIGNED_INT",5126:"FLOAT"}});