// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../lib/gl-matrix ./primitiveIntersectionUtils ../../support/earthUtils ../../support/mathUtils".split(" "),function(M,e,a,k,q,y){function z(b,c,d,h,f){void 0===f&&(f=!1);var e=l;k.createRay(c,d,e,f);return k.intersectSphere(b,e,h)?a.vec3d.dist2(b.center,e.origin)<b.radius*b.radius&&(c=A(b,e.origin),e=-t(e.origin,h,m)-c,0<e)?(c=B,a.mat4d.identity(c),a.mat4d.rotate(c,-e,m),a.vec3d.subtract(h,b.center),a.mat4d.multiplyVec3(c,h,h),a.vec3d.add(h,b.center),!1):!0:(r(b,e,h),!1)}
function A(b,c){var d=m;a.vec3d.subtract(c,b.center,d);c=Math.abs(a.vec3d.length(d)-b.radius);return Math.acos(b.radius/(c+b.radius))}function u(b,a,d,e){var c=l;k.createRay(a,d,c,!0);return k.intersectSphere(b,c,e)}function t(b,c,d){a.vec3d.cross(b,c,d);b=a.vec3d.dot(b,c)/(a.vec3d.length(b)*a.vec3d.length(c));return-y.acos(b)}function C(b,c,d,e){var f=B;a.mat4d.identity(f);a.mat4d.rotate(f,e,d);a.vec3d.subtract(b.eye,c);a.mat4d.multiplyVec3(f,b.eye,b.eye);a.vec3d.add(b.eye,c);a.vec3d.subtract(b.center,
c);a.mat4d.multiplyVec3(f,b.center,b.center);a.vec3d.add(b.center,c);a.mat4d.multiplyVec3(f,b.up,b.up);b.markViewDirty()}function r(b,c,d){var e=m,f=D,g=K;a.vec3d.subtract(c.origin,b.center,f);a.vec3d.cross(f,c.direction,e);a.vec3d.cross(e,f,d);a.vec3d.scale(d,1/a.vec3d.length(d)*b.radius);b=-y.asin(b.radius/a.vec3d.length(c.origin));a.mat4d.identity(g);a.mat4d.rotate(g,b,e);a.mat4d.multiplyVec3(g,d)}function E(b,c,d,e){v.radius=b;a.vec3d.set3(0,0,0,v.center);a.vec3d.set(c,l.origin);a.vec3d.set(d,
l.direction);return r(v,l,e)}function F(b,c){a.vec3d.set3(0,0,0,c);for(var d=0;d<b.length;d++)a.vec3d.add(c,b[d]);a.vec3d.scale(c,1/b.length)}function G(b,c,d){return Math.sin(b/a.vec3d.length(c))*(d+q.earthRadius)}Object.defineProperty(e,"__esModule",{value:!0});e.Earth={center:a.vec3d.create(),radius:q.earthRadius};e.normalizeCoordinate=function(b,a,d){d[0]=a[0]/b.fullWidth;d[1]=a[1]/b.fullHeight;return d};e.sphereOrSilhouettePointFromScreenPoint=z;e.computeHorizonSphereCapAngle=A;e.intersectSphereFromScreenPoint=
u;e.rotationAndAxisFromPoints=t;e.rotationFromPointsAroundAxis=function(b,c,d){var e=m,f=D,g=L;a.vec3d.set(b,f);a.vec3d.set(c,g);b=a.vec3d.dot(f,d);c=a.vec3d.dot(g,d);a.vec3d.scale(d,b,e);a.vec3d.subtract(f,e);a.vec3d.normalize(f);a.vec3d.scale(d,c,e);a.vec3d.subtract(g,e);a.vec3d.normalize(g);b=a.vec3d.dot(f,g);a.vec3d.cross(d,f,e);d=a.vec3d.dot(g,e);return Math.atan2(d,b)};e.setPlane=function(b,c,d){a.vec3d.set(c,d.normal);d.d=-a.vec3d.dot(c,b)};e.setPlaneD=function(b,c){c.d=-a.vec3d.dot(c.normal,
b)};e.normalizeRotationDelta=function(b){for(;b>Math.PI;)b-=2*Math.PI;for(;b<-Math.PI;)b+=2*Math.PI;return b};e.applyRotation=C;e.closestPointOnSphereSilhouette=r;e.closestPointOnCenteredSphereSilhouette=E;e.intersectPlaneFromScreenPoint=function(b,a,d,e){var c=l;k.createRay(a,d,c);return k.intersectPlane(b,c,e)};e.centerOnManifoldSilhouetteFallback=function(b,c,d,e,f){b.intersectManifold(c,d,e,f)||"global"!==b.type||(E(e+q.earthRadius,c,d,w),a.vec3d.add(c,a.vec3d.scale(d,a.vec3d.dist(c,w),w),f))};
e.applyZoomToPoint=function(b,c,d,e){var f=n;d=1-d;a.vec3d.subtract(c,b.eye,f);var g=a.vec3d.length(f),h=g*(1-d);0<=d&&h<e&&(h=e,d=-(h-g)/g);1E-6>Math.abs(g-h)||(a.vec3d.scale(f,d),a.vec3d.add(b.eye,f),a.vec3d.lerp(b.center,c,d))};e.applyZoomOnSphere=function(b,c,d){a.vec2d.set2(c.padding[3]+c.width/2,c.padding[2]+c.height/2,H);u(b,c,H,c.center);a.vec3d.subtract(c.center,c.eye,n);b=a.vec3d.length(n);1E-6>Math.abs(b-b*d)||(a.vec3d.scale(n,d),a.vec3d.subtract(c.center,n,c.eye),c.markViewDirty())};var H=
a.vec2d.create();e.navPointToScreenPoint=function(b,c,d){a.vec2d.set2(c.x,b.fullHeight-c.y,d)};e.centroidOnSphere=function(b,c,d){F(c,d);a.vec3d.normalize(d);a.vec3d.scale(d,b)};e.centroid=F;e.onSurfaceTiltToEyeTiltGlobal=G;e.offSurfaceTiltToEyeTiltGlobal=function(a,c,d){return G(Math.PI/2,c,d)+(a-Math.PI/2)};var p;(function(a){a[a.Vertical=0]="Vertical";a[a.Horizontal=1]="Horizontal"})(p=e.PanMode||(e.PanMode={}));e.VerticalPanTresholds={Elevation:3E4,Angle:8/180*Math.PI};e.pickPointAndInitSphere=
function(b,c,d,h){var f=a.vec3d.create(),g={center:a.vec3d.create(),radius:0},k=!0;b.pickPointInScreen(d,f)?g.radius=a.vec3d.length(f):(g.radius=c.aboveGround?Math.max(a.vec3d.length(c.center),.9*e.Earth.radius):a.vec3d.length(c.eye)-c.relativeElevation,h?z(g,c,d,f):k=u(g,c,d,f));return{sphere:g,scenePickPoint:k?f:null}};e.decidePanMode=function(b,c,d){var h=a.vec3d.length(b.eye);if(Math.abs(h-e.Earth.radius)>e.VerticalPanTresholds.Elevation)return p.Horizontal;if(b.aboveGround===c.radius>h)return p.Vertical;
a.vec3d.normalize(a.vec3d.subtract(b.eye,d,I));return Math.abs(.5*Math.PI-Math.acos(a.vec3d.dot(d,I)/a.vec3d.length(d)))<e.VerticalPanTresholds.Angle?p.Vertical:p.Horizontal};var I=a.vec3d.create();e.applyPanPlanar=function(b,c,d){a.vec3d.subtract(d,c,x);a.vec3d.subtract(b.eye,x);a.vec3d.subtract(b.center,x);b.markViewDirty()};var x=a.vec3d.create();e.applyPanSpherical=function(a,c,d,e){d=t(d,e,J);C(c,a.center,J,d)};var J=a.vec3d.create(),K=a.mat4d.create(),B=a.mat4d.create(),n=a.vec3d.create(),m=
a.vec3d.create(),D=a.vec3d.create(),L=a.vec3d.create(),w=a.vec3d.create(),l={origin:a.vec3d.create(),direction:a.vec3d.create()},v={center:a.vec3d.create(),radius:0}});