// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/runtimeUtils ../../camera/constraintUtils ../../lib/gl-matrix ../Constraints ./InteractiveController ../utils/navigationUtils ../utils/viewUtils ../../../3d/support/earthUtils ../../support/cameraUtils ../../support/cameraUtilsInternal ../../support/mathUtils ../../webgl-engine/lib/Camera ../../../navigation/gamepadUtils".split(" "),function(C,D,L,E,t,d,u,M,h,F,G,N,O,q,P,w){Object.defineProperty(D,"__esModule",{value:!0});
C=function(x){function e(b,a){var c=x.call(this)||this;c.view=b;c.device=a;c.transformation={translation:[0,0,0],heading:0,tilt:0};c.constraintOptions={selection:15,interactionType:0,interactionStartCamera:new P,interactionFactor:0,interactionDirection:null,tiltMode:1};return c}L(e,x);e.prototype.handleEvent=function(b){var a=w.extractTransformation(b,this.view.navigation.gamepad,this.transformation);("end"===b.action||w.isZeroTransformation(a))&&this.finishController()};e.prototype.onControllerStart=
function(b){this.filteredSurfaceElevation=this.view.pointsOfInterest.cameraOnSurface.location.z;x.prototype.onControllerStart.call(this,b)};e.prototype.updateFilteredSurfaceElevation=function(b){this.filteredSurfaceElevation+=1*(this.view.pointsOfInterest.cameraOnSurface.location.z-this.filteredSurfaceElevation)*b};e.prototype.stepController=function(b,a){this.updateFilteredSurfaceElevation(b);this.currentCamera.copyViewFrom(a);this.updateCameraCenter();this.constraintOptions.interactionStartCamera.copyFrom(this.currentCamera);
this.calculateControlTransformation(b,this.currentCamera,v);this.applyPan(v.pan);this.applyRotate(v.rotate);this.applyZoom(v.zoom);this.applyAscend(v.ascend);this.constraintOptions.interactionType=0;this.constraintOptions.selection=8;t.applyAll(this.view,this.currentCamera,this.constraintOptions);x.prototype.stepController.call(this,b,a)};e.prototype.applyRotate=function(b){if(b.enabled){var a=this.currentCamera,c=a.center,g=a.up,k=a.eye;d.vec3d.subtract(c,k);d.mat4d.multiplyVec3(b.matrix,c);d.vec3d.add(c,
k);d.mat4d.multiplyVec3(b.matrix,g);a.markViewDirty();this.constraintOptions.interactionType=3;this.constraintOptions.selection=7;t.applyAll(this.view,a,this.constraintOptions)}};e.prototype.applyPan=function(b){if(b.enabled){var a=this.currentCamera,c=a.center,g=a.up;d.mat4d.multiplyVec3(b.matrix,a.eye);d.mat4d.multiplyVec3(b.matrix,c);this.view.state.isGlobal&&d.mat4d.multiplyVec3(b.matrix,g);a.markViewDirty();this.constraintOptions.interactionType=4;this.constraintOptions.selection=15;t.applyAll(this.view,
a,this.constraintOptions)}};e.prototype.applyZoom=function(b){if(b){var a=this.currentCamera,c=a.viewForward;d.vec3d.add(a.eye,d.vec3d.scale(c,b,y));this.currentCamera.markViewDirty();this.constraintOptions.interactionDirection=d.vec3d.negate(d.vec3d.set(c,H));this.constraintOptions.interactionType=1;this.constraintOptions.selection=7;t.applyAll(this.view,this.currentCamera,this.constraintOptions);this.constraintOptions.interactionDirection=null}};e.prototype.applyAscend=function(b){if(b){var a=this.currentCamera,
c=a.center,a=a.eye;this.view.renderCoordsHelper.worldUpAtPosition(a,z);this.constraintOptions.interactionDirection=d.vec3d.set(z,H);if(this.view.state.isGlobal){var g=d.vec3d.length(a);b=(g+b)/g;d.vec3d.scale(a,b);d.vec3d.scale(c,b)}else b=d.vec3d.scale(z,b,l),d.vec3d.add(a,b),d.vec3d.add(c,b);this.currentCamera.markViewDirty();this.updateCameraCenter();this.constraintOptions.interactionType=5;this.constraintOptions.selection=8;t.applyAll(this.view,this.currentCamera,this.constraintOptions)&&this.updateCameraCenter();
this.constraintOptions.selection=7;t.applyAll(this.view,this.currentCamera,this.constraintOptions);this.constraintOptions.interactionDirection=null}};e.prototype.calculateControlTransformation=function(b,a,c){c.zoom=0;c.ascend=0;c.pan.enabled=!1;d.mat4d.identity(c.pan.matrix);c.rotate.enabled=!1;d.mat4d.identity(c.rotate.matrix);b=this.computeVelocities(b);switch(this.view.viewingMode){case "local":this.calculateControlTransformationLocal(b,a,c);break;case "global":this.calculateControlTransformationGlobal(b,
a,c);break;default:E.neverReached(this.view.viewingMode)}};e.prototype.updateCameraCenter=function(){var b=this.currentCamera;h.centerOnManifoldSilhouetteFallback(this.view.renderCoordsHelper,b.eye,b.viewForward,this.view.pointsOfInterest.centerOnSurfaceFrequent.estimatedSurfaceAltitude,b.center);this.currentCamera.markViewDirty()};e.prototype.calculateControlTransformationLocal=function(b,a,c){var g=a.viewRight,k=a.viewForward,f=this.transformation,e=this.view.navigation.gamepad;d.vec3d.set3(k[0],
k[1],0,p);d.vec3d.normalize(p);k=f.translation[0]*b.pan;0!==k&&(d.vec3d.scale(g,k,I),d.mat4d.translate(c.pan.matrix,I),c.pan.enabled=!0);d.vec3d.set3(0,0,0,y);switch(e.mode){case "pan":e=-f.translation[1]*b.pan;0!==e&&(d.vec3d.scale(p,e,y),d.mat4d.translate(c.pan.matrix,y),c.pan.enabled=!0);break;case "zoom":c.zoom=-f.translation[1]*b.zoom;break;default:E.neverReached(e.mode)}c.ascend=f.translation[2]*b.ascend;e=-f.heading*b.rotate;0!==e&&(d.mat4d.rotate(c.rotate.matrix,e,this.view.renderCoordsHelper.worldUpAtPosition(a.eye,
z)),c.rotate.enabled=!0);b=f.tilt*b.rotate;a=F.viewAngle(this.view.renderCoordsHelper,a.center,a.eye);if(a=q.clamp(a+b,u.TiltDefault.min,u.TiltDefault.max)-a)d.mat4d.rotate(c.rotate.matrix,a,g),c.rotate.enabled=!0};e.prototype.calculateControlTransformationGlobal=function(b,a,c){var g=a.eye,e=a.viewRight,f=this.transformation,m=this.view.navigation.gamepad;d.vec3d.cross(e,g,p);d.vec3d.normalize(p);d.vec3d.negate(p);var n=f.translation[0]*b.pan;0!==n&&(d.mat4d.rotate(c.pan.matrix,n,p),c.pan.enabled=
!0);switch(m.mode){case "pan":m=f.translation[1]*b.pan;0!==m&&(d.mat4d.rotate(c.pan.matrix,m,e),c.pan.enabled=!0);break;case "zoom":c.zoom=-f.translation[1]*b.zoom}m=this.view.pointsOfInterest.centerOnSurfaceFrequent.estimatedSurfaceAltitude;c.ascend=f.translation[2]*b.ascend;n=-f.heading*b.rotate;0!==n&&(d.mat4d.rotate(c.rotate.matrix,n,g),c.rotate.enabled=!0);b=this.clampTiltDeltaGlobalToValidRange(f.tilt*b.rotate,a.eye,a.viewForward,m);0!==b&&(d.mat4d.rotate(c.rotate.matrix,b,e),c.rotate.enabled=
!0)};e.prototype.clampTiltDeltaGlobalToValidRange=function(b,a,c,g){var e=h.onSurfaceTiltToEyeTiltGlobal(u.TiltDefault.min,a,g),f=0,m=0;this.view.renderCoordsHelper.intersectManifold(a,c,g,l)?(c=F.viewAngle(this.view.renderCoordsHelper,l,a),f=h.onSurfaceTiltToEyeTiltGlobal(c,a,g),m=h.onSurfaceTiltToEyeTiltGlobal(u.TiltDefault.max,a,g)):(h.closestPointOnCenteredSphereSilhouette(g+G.earthRadius,a,c,l),c=q.acos(-d.vec3d.dot(c,d.vec3d.normalize(l))),f=h.offSurfaceTiltToEyeTiltGlobal(c,a,g),m=h.offSurfaceTiltToEyeTiltGlobal(u.TiltDefault.max,
a,g));return q.clamp(f+b,e,m)-f};e.prototype.pointEquivalentAboveSurface=function(b,a,c){var e=this.view.renderCoordsHelper,k=e.getAltitude(b);a+=Math.abs(k-a);d.vec3d.set(b,c);e.setAltitude(a,c);return a};e.prototype.clampedDistanceToSurface=function(b,a){var c=this.view.renderCoordsHelper,e=this.view.state.camera,k=N.headingTiltToDirectionUp(this.view,a,0,J,Q).direction;h.centerOnManifoldSilhouetteFallback(c,a,k,b,r);k=d.vec3d.dist(a,r);h.centerOnManifoldSilhouetteFallback(c,a,d.vec3d.direction(e.center,
a,r),b,A);b=d.vec3d.dist(a,A);return Math.min(k,b)};e.prototype.computeHeadingRotateRadius=function(b){var a=this.view,c=a.renderCoordsHelper,e=a.state,a=e.camera,e=e.isGlobal;h.centerOnManifoldSilhouetteFallback(c,a.eye,a.viewForward,this.filteredSurfaceElevation,l);if(e)return a=d.vec3d.subtract(b,l,r),c=d.vec3d.length(a),d.vec3d.scale(a,1/c,a),b=d.vec3d.normalize(b,A),b=q.acos(d.vec3d.dot(b,a)),c*Math.sin(Math.min(R,b));d.vec3d.set(b,r);c.setAltitude(this.filteredSurfaceElevation,r);return d.vec3d.dist(l,
r)};e.prototype.minimumAscendVelocity=function(){return this.view.state.constraints.collision.enabled?0:S};e.prototype.computeVelocities=function(b){var a=this.filteredSurfaceElevation,c=a+G.earthRadius,d=this.view.state,e=d.camera,f=d.isGlobal,m=this.pointEquivalentAboveSurface(e.eye,a,B),n=this.clampedDistanceToSurface(a,B),h=e.width/2,l=K*e.width,d=K*e.width,e=n*Math.tan(.5*e.fovX)/h,p=e/c,c=e/this.computeHeadingRotateRadius(B),f=(f?p:e)*l*b,a=m-a,a=Math.max(this.minimumAscendVelocity()*b,Math.pow(2,
l*b/h)*a-a),n=Math.pow(2,l*b/h)*n-n;b*=q.clamp(c*d,T,U);return{pan:f,ascend:a,zoom:n,rotate:b}};e.activatesFor=function(b,a){b=w.extractTransformation(a,b.navigation.gamepad,V);return!("end"===a.action||w.isZeroTransformation(b))};return e}(M.InteractiveController);D.GamepadController=C;var V={translation:[0,0,0],heading:0,tilt:0},J=80,R=q.deg2rad(J),K=.75,S=5,T=q.deg2rad(30),U=q.deg2rad(80),p=d.vec3d.create(),z=d.vec3d.create(),I=d.vec3d.create(),y=d.vec3d.create(),l=d.vec3d.create(),r=d.vec3d.create(),
A=d.vec3d.create(),B=d.vec3d.create(),v={zoom:0,ascend:0,pan:{enabled:!1,matrix:d.mat4d.create()},rotate:{enabled:!1,matrix:d.mat4d.create()}},H=d.vec3d.create(),Q=O.createDirectionUp()});