// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/assignHelper ../../../../core/promiseUtils ../../../../geometry/Extent ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/spatialReferenceUtils ../../../../layers/support/TileInfo ../../viewStateUtils ../../engine/Bitmap ../../tiling/TileInfoView ../../tiling/TileKey".split(" "),function(z,A,r,m,p,t,u,v,n,w,x,y){var b=t.create(),h=[0,0],q=new y(0,0,0,0),l={container:null,fetchSource:null,requestUpdate:null,imageMaxWidth:2048,
imageMaxHeight:2048,imageRotationSupported:!1,imageNormalizationSupported:!1,hidpi:!1};return function(){function e(a){this._imagePromise=null;this.hidpi=l.hidpi;this.imageMaxWidth=l.imageMaxWidth;this.imageMaxHeight=l.imageMaxHeight;this.imageRotationSupported=l.imageRotationSupported;this.imageNormalizationSupported=l.imageNormalizationSupported;a=r({},l,a);this.container=a.container;this.disposeSource=a.disposeSource;this.fetchSource=a.fetchSource;this.requestUpdate=a.requestUpdate;this.imageMaxWidth=
a.imageMaxWidth;this.imageMaxHeight=a.imageMaxHeight;this.imageRotationSupported=a.imageRotationSupported;this.imageNormalizationSupported=a.imageNormalizationSupported;this.hidpi=a.hidpi}e.prototype.destroy=function(){};Object.defineProperty(e.prototype,"updating",{get:function(){return null!==this._imagePromise},enumerable:!0,configurable:!0});e.prototype.update=function(a){var c=this,d=a.state,f=u.getInfo(d.spatialReference),g=this.hidpi?a.pixelRatio:1;this._imagePromise&&(this._imagePromise.cancel(),
this._imagePromise=null);if(a.stationary){this.imageRotationSupported?(h[0]=d.width,h[1]=d.height):n.getOuterSize(h,d);a=f&&(d.extent.xmin<f.valid[0]||d.extent.xmax>f.valid[1]);a=!this.imageNormalizationSupported&&a;f=this.imageRotationSupported?d.rotation:0;if(Math.floor(h[0]*g)>this.imageMaxWidth||Math.floor(h[1]*g)>this.imageMaxHeight||a){var b=Math.min(this.imageMaxWidth,this.imageMaxHeight);a&&(b=Math.min(d.worldScreenWidth,b));this._imagePromise=this._tiledExport(d,b,f,g)}else this._imagePromise=
this._singleExport(d,h,f,g);this._imagePromise.then(function(a){c._imagePromise=null;var d=c.container.children.slice();c.container.removeAllChildren();a.forEach(c.container.addChild,c.container);c.disposeSource&&d.forEach(function(a){c.disposeSource(a.source)},c)}).catch(function(a){c._imagePromise=null;if("cancel"!==a.dojoType)throw a;})}};e.prototype.updateExports=function(a,c){for(var d=0,f=this.container.children;d<f.length;d++){var g=f[d];if(!g.visible||!g.attached)break;a(g,c)?console.error("ExportStrategy.updateExports doesn't support promise yet"):
g.requestRender()}};e.prototype._export=function(a,c,d,f,g){var b=this;return m.resolve().then(function(){return b.fetchSource(a,Math.floor(c*g),Math.floor(d*g),{rotation:f,pixelRatio:g})}).then(function(b){var k=new w(b);k.x=b.x=a.xmin;k.y=b.y=a.ymax;k.resolution=b.resolution=a.width/c;b.rotation=f;b.pixelRatio=g;k.width=c;k.height=d;return k})};e.prototype._singleExport=function(a,c,d,f){n.getBBox(b,a.center,a.resolution,c);a=new p(b[0],b[1],b[2],b[3],a.spatialReference);return this._export(a,c[0],
c[1],d,f).then(function(a){return[a]})};e.prototype._tiledExport=function(a,c,d,f){var g=this,e=v.create({size:c,spatialReference:a.spatialReference,scales:[a.scale]}),h=new x(e),e=h.getTileCoverage(a);if(!e)return null;var k=[];e.forEach(function(e,l,m,n){q.set(e,l,m,n);h.getTileBounds(b,q);e=new p(b[0],b[1],b[2],b[3],a.spatialReference);k.push(g._export(e,c,c,d,f))});return m.all(k)};return e}()});