// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("dojo/date/locale ../../Color ../../core/lang ../../core/numberUtils ../../core/unitUtils dojo/i18n!dojo/cldr/nls/gregorian".split(" "),function(p,q,c,l,g,u){function v(b){return b&&b.map(function(a){return new q(a)})}function t(b,a,d){var f="";0===a?f=m.lt+" ":a===d&&(f=m.gt+" ");return f+b}var h={},m={lte:"\x3c\x3d",gte:"\x3e\x3d",lt:"\x3c",gt:"\x3e",pct:"%",ld:"\u2013"},w={millisecond:0,second:1,minute:2,hour:3,day:4,month:5,year:6},x={millisecond:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},
second:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},minute:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},hour:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},day:{selector:"date",dateOptions:{formatLength:"long"}},month:{selector:"date",dateOptions:{formatLength:"long"}},year:{selector:"date",dateOptions:{selector:"year"}}},y={formatLength:"short",fullYear:!0},z={formatLength:"short"};c.mixin(h,{meterIn:{inches:g.convertUnit(1,
"meters","inches"),feet:g.convertUnit(1,"meters","feet"),"us-feet":g.convertUnit(1,"meters","us-feet"),yards:g.convertUnit(1,"meters","yards"),miles:g.convertUnit(1,"meters","miles"),"nautical-miles":g.convertUnit(1,"meters","nautical-miles"),millimeters:g.convertUnit(1,"meters","millimeters"),centimeters:g.convertUnit(1,"meters","centimeters"),decimeters:g.convertUnit(1,"meters","decimeters"),meters:g.convertUnit(1,"meters","meters"),kilometers:g.convertUnit(1,"meters","kilometers"),"decimal-degrees":1/
g.lengthToDegrees(1,"meters")},timelineDateFormatOptions:{selector:"date",dateOptions:{formatLength:"short",fullYear:!0}},formatDate:function(b,a){var d=[];null==b||b instanceof Date||(b=new Date(b));a=a||{};a=c.mixin({},a);var f=a.selector?a.selector.toLowerCase():null,e=!f||-1<f.indexOf("time"),f=!f||-1<f.indexOf("date");e&&(a.timeOptions=a.timeOptions||z,a.timeOptions&&(a.timeOptions=c.mixin({},a.timeOptions),a.timeOptions.selector=a.timeOptions.selector||"time",d.push(a.timeOptions)));f&&(a.dateOptions=
a.dateOptions||y,a.dateOptions&&(a.dateOptions=c.mixin({},a.dateOptions),a.dateOptions.selector=a.dateOptions.selector||"date",d.push(a.dateOptions)));d&&d.length?(d=d.map(function(a){return p.format(b,a)}),a=1==d.length?d[0]:u["dateTimeFormat-medium"].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(a,b){return d[b]})):a=p.format(b);return a},createColorStops:function(b){var a=b.values,d=b.colors,f=b.labelIndexes,e=b.isDate,k=b.dateFormatOptions;b=[];return b=a.map(function(b,r){var n=null;if(!f||
-1<f.indexOf(r)){var c;(c=e?h.formatDate(b,k):l.format(b))&&(n=t(c,r,a.length-1))}return{value:b,color:d[r],label:n}})},updateColorStops:function(b){var a=b.stops,d=b.changes,f=b.isDate,e=b.dateFormatOptions,k=[],n,c=a.map(function(a){return a.value});d.forEach(function(a){k.push(a.index);c[a.index]=a.value});n=l.round(c,{indexes:k});a.forEach(function(b,d){b.value=c[d];if(null!=b.label){var k,g=null;(k=f?h.formatDate(n[d],e):l.format(n[d]))&&(g=t(k,d,a.length-1));b.label=g}})},createClassBreakLabel:function(b){var a=
b.minValue,d=b.maxValue,f=b.isFirstBreak?"":m.gt+" ";b="percent-of-total"===b.normalizationType?m.pct:"";a=null==a?"":l.format(a);d=null==d?"":l.format(d);return f+a+b+" "+m.ld+" "+d+b},setLabelsForClassBreaks:function(b){var a=b.classBreakInfos,d=b.classificationMethod,f=b.normalizationType,e=[];a&&a.length&&("standard-deviation"===d?console.log("setLabelsForClassBreaks: cannot set labels for class breaks generated using 'standard-deviation' method."):b.round?(e.push(a[0].minValue),a.forEach(function(a){e.push(a.maxValue)}),
e=l.round(e),a.forEach(function(a,b){a.label=h.createClassBreakLabel({minValue:0===b?e[0]:e[b],maxValue:e[b+1],isFirstBreak:0===b,normalizationType:f})})):a.forEach(function(a,b){a.label=h.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===b,normalizationType:f})}))},updateClassBreak:function(b){var a=b.classBreaks,d=b.normalizationType,f=b.change,e=f.index,f=f.value,k=-1,c=-1,g=a.length;"standard-deviation"===b.classificationMethod?console.log("updateClassBreak: cannot update labels for class breaks generated using 'standard-deviation' method."):
(0===e?k=e:e===g?c=e-1:(c=e-1,k=e),-1<k&&k<g&&(b=a[k],b.minValue=f,b.label=h.createClassBreakLabel({minValue:b.minValue,maxValue:b.maxValue,isFirstBreak:0===k,normalizationType:d})),-1<c&&c<g&&(b=a[c],b.maxValue=f,b.label=h.createClassBreakLabel({minValue:b.minValue,maxValue:b.maxValue,isFirstBreak:0===c,normalizationType:d})))},calculateDateFormatInterval:function(b){var a,d,f=b.length,e,c,g,h,l,m,p=Infinity,q;b=b.map(function(a){return new Date(a)});for(a=0;a<f-1;a++){e=b[a];g=[];l=Infinity;m="";
for(d=a+1;d<f;d++)c=b[d],c=e.getFullYear()!==c.getFullYear()&&"year"||e.getMonth()!==c.getMonth()&&"month"||e.getDate()!==c.getDate()&&"day"||e.getHours()!==c.getHours()&&"hour"||e.getMinutes()!==c.getMinutes()&&"minute"||e.getSeconds()!==c.getSeconds()&&"second"||"millisecond",h=w[c],h<l&&(l=h,m=c),g.push(c);l<p&&(p=l,q=m)}return q},createUniqueValueLabel:function(b){var a=b.value,d=b.fieldInfo,c=b.domain;b=b.dateFormatInterval;var e=String(a);(c=c&&c.codedValues?c.getName(a):null)?e=c:"number"===
typeof a&&(e=d&&"date"===d.type?h.formatDate(a,b&&x[b]):l.format(a));return e},cloneColorVariable:function(b){var a;b&&(a=c.mixin({},b),a.colors=v(a.colors),a.stops=a.stops&&a.stops.map(function(a){a=c.mixin({},a);a.color&&(a.color=new q(a.color));return a}),a.legendOptions&&(a.legendOptions=c.mixin({},a.legendOptions)));return a},cloneOpacityVariable:function(b){var a;if(b){a=c.mixin({},b);if(b=a.opacityValues)a.opacityValues=b.slice(0);if(b=a.stops)a.stops=b.map(function(a){return c.mixin({},a)});
if(b=a.legendOptions)a.legendOptions=c.mixin({},b)}return a},cloneSizeVariable:function(b){var a;b&&(a=c.mixin({},b),a.stops&&(a.stops=a.stops.map(function(a){return c.mixin({},a)})),(b=a.minSize)&&"object"===typeof b&&(a.minSize=h.cloneSizeVariable(b)),(b=a.maxSize)&&"object"===typeof b&&(a.maxSize=h.cloneSizeVariable(b)),b=a.legendOptions)&&(a.legendOptions=c.mixin({},b),b=b.customValues)&&(a.legendOptions.customValues=b.slice(0));return a}});return h});