// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../geometry ../../../../geometry/support/spatialReferenceUtils ../../../../geometry/support/webMercatorUtils ../DisplayObject ./gfxUtils".split(" "),function(y,z,q,v,w,n,x,f){var r=new Set,g=[];return function(l){function b(){var a=null!==l&&l.apply(this,arguments)||this;a._prevStateId=null;a.visible=!0;return a}q(b,l);Object.defineProperty(b.prototype,"graphic",{get:function(){return this._graphic},set:function(a){this._geometry=
(this._graphic=a)&&a.geometry||null;this._projected=null;this.requestRender()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"geometry",{get:function(){return this._geometry},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"isPolygonMarkerSymbol",{get:function(){var a=this.renderingInfo.symbol.type,c=this.geometry;return c&&"polygon"===c.type&&("simple-marker"===a||"picture-marker"===a||"text"===a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"renderingInfo",{get:function(){return this._renderingInfo},set:function(a){this._renderingInfo=a;this.requestRender()},enumerable:!0,configurable:!0});b.prototype.detach=function(){this._revokeShapeUrl();this._removeShape();this._drawInfo=this._projected=null};b.prototype.doRender=function(a){var c=this,d=a.surface,p=a.state,b=a.projector,e=this._prevStateId!==p.id;if(this.renderRequested||e)if(e&&a.stationary&&(this._prevStateId=p.id),this.visible)if(e=this._projectGeometry(this.geometry,a.state.spatialReference),
a=this._getScreenOffsets([],a.state),f.isShapeInvalid(this.renderingInfo.symbol,this._shape)&&this._removeShape(),a.length){var k=this._shape,g=e.type,m=this._shapePromise;m&&!m.isFulfilled()&&m.cancel();if(!k||this._showRedraw(a,p))m="point"===g?f.drawPoint(b,d,e,k,this.renderingInfo,p.rotation,a).then(function(a){f.stylePoint(a,c.renderingInfo);return a}):"multipoint"===g?f.drawMarkers(b,d,e,k,this.renderingInfo,p.rotation,a,this).then(function(a){f.styleMarkers(a,c.renderingInfo);return a}):f.drawShape(b,
d,e,k,a).then(function(a){f.styleShape(a,c.renderingInfo);return a});this._shapePromise=m.then(function(a){c._shape=a;a.getNode().gfxObject=c;return a})}else this._removeShape();else this._removeShape()};b.prototype._getScreenOffsets=function(a,c){var d=c.clippedExtent,b=this._projected.outExtent,h=c.spatialReference;a.length=0;if(!b)return a;if(h.isWrappable){var h=w.getInfo(h),e=b.cache._partwise,d=d._getParts(h);g.length=0;if(e&&e.length)for(b=0;b<e.length;b++)g.push.apply(g,e[b]._getParts(h));
else g.push.apply(g,b._getParts(h));c=c.worldScreenWidth;a.length=0;r.clear();b=g.length;for(h=0;h<b;h++)for(var k=g[h],e=k.extent,k=k.frameIds,f=k.length,m=d.length,l=0;l<m;l++){var n=d[l];if(n.extent.intersects(e))for(var q=f,t=0;t<q;t++){var u=(n.frameIds[0]-k[t])*c;r.has(u)||(a.push(u),r.add(u))}}a.sort()}else d.intersects(b)&&a.push(0);return a};b.prototype._projectGeometry=function(a,c){var b=this._projected;a=this.isPolygonMarkerSymbol?a.centroid:a;if(b&&b.inGeometry===a&&b.outSpatialReference===
c)return b.outGeometry;a&&a.spatialReference.equals(c)?this._projected={inGeometry:a,outGeometry:a,outSpatialReference:c,outExtent:this._getExtent(a)}:n.canProject(a,c)?this._projected={inGeometry:a,outGeometry:n.project(a,c),outSpatialReference:c,outExtent:this._getExtent(a)}:this._projected={inGeometry:a,outGeometry:null,outSpatialReference:c,outExtent:null};return this._projected.outGeometry};b.prototype._getExtent=function(a){var b=a.extent;if(!b){var d=b=void 0;"esri.geometry.Point"===a.declaredClass?
(b=a.x,d=a.y):"esri.geometry.Multipoint"===a.declaredClass&&(b=a.points[0][0],d=a.points[0][1]);b=new v.Extent(b,d,b,d,a.spatialReference)}return b};b.prototype._removeShape=function(){var a=this._shape;a&&(a.removeShape(),a.getNode().gfxObject=null,a.destroy());this._shape=this._drawInfo=null};b.prototype._revokeShapeUrl=function(){var a=this._shape;a&&(a=a.shape)&&"image"===a.type&&f.revokeBlobUrl(a.src)};b.prototype._showRedraw=function(a,b){return!0};return b}(x)});