// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/assignHelper @dojo/framework/shim/array @dojo/framework/shim/Map ../../../../Color ../../../../request ../../../../core/promiseUtils ../../../../core/screenUtils ../../../../core/urlUtils ../../../../geometry/Polygon ../../../../symbols/SimpleMarkerSymbol ../../../../symbols/support/gfxUtils ../../libs/gl-matrix/mat2d ../../libs/gl-matrix/mat2dExtras".split(" "),function(Z,m,I,R,S,T,U,u,v,G,V,n,w,x,C){function D(c,a){if(!a)return null;a.toRgba?(c[0]=
a.r,c[1]=a.g,c[2]=a.b,c[3]=a.a):(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3]);return c}function E(c,a,b){null!=b&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=b);return c}function J(c,a,b){var e=a[0]/a[1];c[0]=c[1]=1;isNaN(b)||(1<e?(c[0]=b/a[0],c[1]=b/e/a[1]):(c[1]=b/a[1],c[0]=b*e/a[0]));return c}function K(c,a,b,e,h,k,f){var d=h.symbol;b=c.toScreenPoint(W,b,f[0]);c=[b.x,b.y];var m=b.x,r=b.y;f=h.heading;b=h.size&&h.size[0];var g,l;x.identity(q);"number"===typeof b&&(g=isFinite(b)&&b);g=(b=g&&isFinite(g)&&!isNaN(g))?
v.pt2px(g):NaN;k&&C.rotategAt(q,q,k,c);f&&C.rotategAt(q,q,f,c);k=v.pt2px(d.xoffset);f=v.pt2px(d.yoffset);var p;if(0!==k||0!==f)p=[k,-f];var A=null;0!==d.angle&&(A=x.create(),C.rotategAt(A,A,d.angle,c));var H;if("simple-marker"===d.type){k=d.style;f=Math.round;g=b?g:v.pt2px(d.size);l=l=void 0;switch(k){case n.STYLE_SQUARE:case n.STYLE_CROSS:case n.STYLE_X:case n.STYLE_DIAMOND:l=isNaN(g)?16:.5*g;l=F(a,e,L(k,m,r,f(m-l),f(m+l),f(r-l),f(r+l)));break;case n.STYLE_PATH:l=d=F(a,e,d.path);d=d.getBoundingBox();
g=J(x.create(),[d.width,d.height],g);1===g[0]&&1===g[3]||C.scaleAt(q,q,g,c);H=[-(d.x+.5*d.width)+m,-(d.y+.5*d.height)+r];break;default:l=isNaN(g)?16:.5*g,l=M(a,e,{cx:m,cy:r,r:l})}l=u.resolve(l)}else if("picture-marker"===d.type){var B=null,z=null;c=v.pt2px(d.width);l=v.pt2px(d.height);b?(z=g,B=c/l*z):(B=c,z=l);p&&(null!=p[0]&&(p[0]=p[0]/c*B),null!=p[1]&&(p[1]=p[1]/l*z));var t=d.url,d=void 0,d=G.isDataProtocol(t)?u.resolve(t):G.isBlobProtocol(t)?u.resolve(URL.createObjectURL(t)):y.has(t)?u.resolve(y.get(t)):
U(t,{responseType:"blob"}).then(function(a){if(y.has(t))return y.get(t);a=URL.createObjectURL(a.data);y.set(t,a);return a}).catch(function(a){if("cancel"!==a.dojoType)return t;u.reject(a)});l=d.then(function(b){b=N(a,e,{x:m-.5*B,y:r-.5*z,width:B,height:z,src:b});var c=b.getNode();c&&(null!=h.opacity?c.setAttribute("opacity",h.opacity.toString()):c.setAttribute("opacity","1"));return b})}else if("text"===d.type){if(c=d.font&&d.font.clone())c.size=b?g:v.pt2px(c.size);l=O(a,e,{type:"text",text:d.text,
x:m,y:r,align:w.getSVGAlign(d),decoration:d.decoration||c&&c.decoration,rotated:d.rotated,kerning:d.kerning});c&&l.setFont(c);g=l.getNode();c=w.getSVGBaseline(d);d=w.getSVGBaselineShift(d);g&&(g.setAttribute("dominant-baseline",c),d&&g.setAttribute("baseline-shift",d));l=u.resolve(l)}return l.then(function(a){p&&x.translate(q,q,p);A&&x.multiply(q,q,A);H&&x.translate(q,q,H);a.setTransform(q);return a})}function N(c,a,b){return a?a.setShape(b):c.createImage(b)}function M(c,a,b){return a?a.setShape(b):
c.createCircle(b)}function F(c,a,b){b=Array.isArray(b)?b.join(" "):b;return a?a.setShape(b):c.createPath(b)}function O(c,a,b){return a?a.setShape(b):c.createText(b)}function P(c,a){a=a&&a.shape&&a.shape.type;var b=c&&c.type;c=c&&c.style;b&&(c=X[b]||c);Y[c]&&(c="path");return!(!a||!c||a===c)}function L(c,a,b,e,h,k,f,d){switch(c){case n.STYLE_SQUARE:return["M",e+","+k,h+","+k,h+","+f,e+","+f,"Z"];case n.STYLE_CROSS:return["M",a+","+k,a+","+f,"M",e+","+b,h+","+b];case n.STYLE_X:return["M",e+","+k,h+
","+f,"M",e+","+f,h+","+k];case n.STYLE_DIAMOND:return["M",a+","+k,h+","+b,a+","+f,e+","+b,"Z"];case n.STYLE_TARGET:return["M",e+","+k,h+","+k,h+","+f,e+","+f,e+","+k,"M",e-d+","+b,e+","+b,"M",a+","+(k-d),a+","+k,"M",h+d+","+b,h+","+b,"M",a+","+(f+d),a+","+f]}}function Q(c,a){var b=a.symbol;if("picture-marker"!==b.type){var e=w.getFill(b);if("simple-marker"===b.type){var h=b.style,k=(b=w.getStroke(b))&&b.color,h=h===n.STYLE_X||h===n.STYLE_CROSS,f=a.opacity;(a=a.color||D([0,0,0,0],h?k:e))&&null!=f&&
(a=E([0,0,0,0],a,f));a&&(h?a!==k&&(b=I({},b),b.color=a):a!==e&&(e=a));c.setFill(e).setStroke(b)}else"text"===b.type&&(f=a.opacity,(a=a.color||D([0,0,0,0],e))&&null!=f&&(a=E([0,0,0,0],a,f)),a&&a!==e&&(e=a),c.setFill(e))}}Object.defineProperty(m,"__esModule",{value:!0});var y=new S.default;m.getScalingVector=J;var W={x:0,y:0},q=x.create();m.drawPoint=K;m.drawMarkers=function(c,a,b,e,h,k,f,d){var m=h.symbol,r=b.points,g=e||a.createGroup();a=[0];g.children[0]&&P(m,g.children[0])&&g.clear();m=0;b=[];e=
r.length;for(var l=0;l<e;l++)for(var p=r[l],q=f.length,n=0;n<q;n++)a[0]=f[n],b.push(K(c,g,{x:p[0],y:p[1]},g.children[m++],h,k,a));return u.all(b).then(function(a){a.forEach(function(a){a.getNode().gfxObject=d;g.add(a)});var b=g.children.length;if(r.length*f.length<b)for(a=r.length*f.length,--b;b>=a;b--)g.children[b].removeShape();return g})};m.drawShape=function(c,a,b,e,h){var k=[];"extent"===b.type&&(b=V.fromExtent(b));if("polyline"===b.type||"polygon"===b.type){for(var f=h.length,d=0;d<f;d++)k=
k.concat(c.toScreenPath(b,h[d]));e=F(a,e,k)}return u.resolve(e)};m.drawRect=function(c,a,b){return a?a.setShape(b):c.createRect(b)};m.drawImage=N;m.drawCircle=M;m.drawPath=F;m.drawText=O;var X={"picture-marker":"image","picture-fill":"path","simple-fill":"path","simple-line":"path",text:"text"},Y={square:1,cross:1,x:1,diamond:1,target:1};m.isShapeInvalid=P;m.smsToPath=L;m.stylePoint=Q;m.styleMarkers=function(c,a){for(var b=c.children.length,e=0;e<b;e++)Q(c.children[e],a)};m.styleShape=function(c,
a){var b=a.symbol,e=a.size,h=a.color,k=a.opacity,f=a.outlineSize;a=w.getStroke(b);var d=w.getFill(b),m=!1,n;"simple-line"===b.type?(m=!0,n="none"!==b.style):n=b.outline&&"none"!==b.outline.style;var g,l,p;if(null!=e||null!=f)if(e=e&&isFinite(e[0])&&e[0],f=m?null:f,null!=e||null!=f)p=v.pt2px(f||e);e="picture-fill"===b.type;!h&&null==k||e||(m?(g=h||a&&a.color&&D([0,0,0,0],a.color))&&null!=k&&(g=E(g,g,k)):d&&(l=h||D([0,0,0,0],d))&&null!=k&&(l=E(l,l,k)));!n||null==p&&!g?c.setStroke(a):c.setStroke(I({},
a,null!=p?{width:p}:null,g&&{color:g}));b=h&&new T(h)||b.color;d&&"pattern"===d.type&&b&&!e?w.getPatternUrlWithColor(d.src,b.toCss(!0)).then(function(a){d.src=a;c.setFill(d)}):c.setFill(l||d);c.rawNode.setAttribute("vector-effect","non-scaling-stroke")};m.revokeBlobUrl=function(c){if(c&&G.isBlobProtocol(c)){for(var a=0,b=R.from(y);a<b.length;a++){var e=b[a],h=e[0];if(e[1]===c){y.delete(h);break}}URL.revokeObjectURL(c)}}});