// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports dojo/Deferred dojo/promise/all ../../request ../../core/has ../../core/LRUCache ../../core/promiseUtils ../../core/requireUtils ../../core/workers ../2d/tiling/TileKey ./GeometryUtils ./GlyphMosaic ./GlyphSource ./SpriteMosaic ./SpriteSource ./TileIndex ./VectorTileDisplayObject module".split(" "),function(r,F,t,n,u,G,v,e,w,x,y,p,z,A,B,C,k,D,E){var l=new v(10),h=new Map;return function(){function b(a,c,f,d,b){void 0===d&&(d=!1);this.devicePixelRatio=f;this.allowUpdates=d;this._tileIndex=
this._connection=this._glyphMosaic=this._spriteMosaic=null;this._updateQueue=new Map;this._ongoingRequests=new Map;this._vectorTileLayer=a;this._styleRepository=a.styleRepository;this._requestUpdate=c}b.prototype.destroy=function(){this.stop();this._vectorTileLayer=this._requestUpdate=this._styleRepository=null;this._spriteMosaic&&(this._spriteMosaic.dispose(),this._spriteMosaic=null);this._glyphMosaic&&(this._glyphMosaic.dispose(),this._glyphMosaic=null)};Object.defineProperty(b.prototype,"initialized",
{get:function(){return this._broadcastPromise&&this._broadcastPromise.isFulfilled()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"spriteMosaic",{get:function(){return this._spriteMosaic},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"glyphMosaic",{get:function(){return this._glyphMosaic},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"ongoingRequestCount",{get:function(){return this._ongoingRequests.size},enumerable:!0,configurable:!0});
b.prototype.start=function(){var a=this;this.stop();var c=this._styleRepository,f=new C(c.sprite,this.devicePixelRatio);f.devicePixelRatio=this.devicePixelRatio;var d=f.load().then(function(){a._spriteMosaic=new B(1024,1024,250);a._spriteMosaic.setSpriteSource(f)}),b=new A(c.glyphs);this._glyphMosaic=new z(1024,1024,b);var g=this._fetchTileMap(this._vectorTileLayer.tileIndexUrl),e=x.open(w.getAbsMid("./WorkerTileHandler",r,E),{client:this}).then(function(c){a._connection=c}),q=new t(function(a){d.isFulfilled()||
d.cancel();g.isFulfilled()||g.cancel();e.isFulfilled()||e.cancel()});n([d,g,e]).then(function(d){n(a._connection.broadcast("setLayers",c.styleJSON)).then(function(){q.resolve()})});return this._broadcastPromise=q.promise};b.prototype.stop=function(){this._broadcastPromise&&!this._broadcastPromise.isFulfilled()&&this._broadcastPromise.cancel();this._updateQueue.forEach(function(a){return a.cancel()});this._ongoingRequests.forEach(function(a){return a.cancel()});this._connection&&(this._connection.close(),
this._connection=null)};b.prototype.updateTile=function(a,c){var b=this;if(!this.allowUpdates)return e.resolve(null);if(!this._broadcastPromise.isFulfilled()||!this._connection)return e.reject(Error("no connection"));c=Math.round(p.degToByte(c.state.rotation));if(a.rotation===c)return e.resolve(null);var d,m=a.key;this._updateQueue.has(m.id)&&(d=this._updateQueue.get(m.id),d.cancel());a.rotation=c;d=this._connection.invoke("update",{key:a.id,rotation:c},null,{client:a.client}).then(function(c){a.updateSymbolData(c);
return c}).always(function(){b._updateQueue["delete"](m.id)});this._updateQueue.set(a.id,d);return d};b.prototype.getVectorTile=function(a,c,b,d){var f=this;void 0===d&&(d=0);var e=new y(a,c,b,0);return this.getRefKey(e).then(function(a){var c=new D(e,a,f._vectorTileLayer.tileInfo,f._styleRepository,0);if(a)return f.getTileData(c.key,0).then(function(a){c.setData(a.tileData,a.client);return c});c.setData(null,null);return c})};b.prototype.getTileData=function(a,c){var b=this;return this._broadcastPromise.isFulfilled()&&
this._connection?this.getRefKey(a).then(function(d){if(!d)return e.resolve(null);var f=Math.round(p.degToByte(c));return b._getTileData(b._connection,a,d,f).then(function(a){return a&&a.tileData?a:e.reject("No data")})}):e.reject(Error("no connection"))};b.prototype.getRefKey=function(a){return this._tileIndex?this._tileIndex.dataKey(a):e.resolve(a)};b.prototype.getSprites=function(a){return this._spriteMosaic.getSpriteItems(a)};b.prototype.getGlyphs=function(a){return this._glyphMosaic.getGlyphItems(a.tileID,
a.font,a.codePoints)};b.prototype.getStyleRepository=function(){return this._styleRepository};b.prototype.getTileIndex=function(){return this._tileIndex};b.prototype._getTileData=function(a,c,b,d){var f=this,g={client:null};if(a=this._ongoingRequests.get(c.id))return a;a=this._vectorTileLayer.getTileUrl(b.level,b.row,b.col);a=this._connection.invoke("getTile",{key:c.id,refKey:b.id,url:a,rotation:d,cacheTile:this.allowUpdates},null,g).then(function(a){f._ongoingRequests.delete(c.id);return{tileData:a,
client:g.client}}).catch(function(a){f._ongoingRequests.delete(c.id);f._connection.invoke("destructTileData",c.id,null,g);return e.reject(a)});this._ongoingRequests.set(c.id,a);return a};b.prototype._fetchTileMap=function(a){var c=this;if(this._vectorTileLayer.capabilities.operations.supportsTileMap&&this._vectorTileLayer.tilemapCache)return this._tileIndex=new k(this._vectorTileLayer.tilemapCache),e.resolve();if(!a)return e.resolve();if(l.has(a))return this._tileIndex=l.use(a),e.resolve();if(h.has(a))return h.get(a).then(function(a){c._tileIndex=
new k(a.data)});var b=u(a,{responseType:"json"});b.then(function(b){c._tileIndex=new k(b.data);h["delete"](a);l.insert(a,c._tileIndex)});h.set(a,b);return b};return b}()});