// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/extendsHelper ../../core/ObjectPool ../../core/libs/gl-matrix/mat4 ../../core/libs/gl-matrix/vec2 ../../geometry/support/spatialReferenceUtils ../2d/engine/DisplayObject ../2d/tiling/enums ../2d/tiling/TileKey ./RenderBucket ../webgl/BufferObject".split(" "),function(B,C,t,u,v,w,x,y,m,z,p,d){var A="fillVertexBuffer fillDDVertexBuffer fillIndexBuffer outlineVertexBuffer outlineDDVertexBuffer outlineIndexBuffer lineVertexBuffer lineDDVertexBuffer lineIndexBuffer iconVertexBuffer iconDDVertexBuffer iconIndexBuffer textVertexBuffer textDDVertexBuffer textIndexBuffer circleVertexBuffer circleIndexBuffer".split(" ");
return function(q){function f(){for(var a,c=[],b=0;b<arguments.length;b++)c[b]=arguments[b];b=q.call(this)||this;b._renderBuckets=[];b._vectorTileData=null;b._symbolUpdateData=null;b.status=m.TileStatus.INITIALIZED;b.coords=[0,0];b.bounds=[0,0,0,0];b.tileTransform={transform:Float32Array[16],displayCoord:Float32Array[2]};b.stencilData={mask:0,reference:0};b.status=m.TileStatus.INITIALIZED;b.tileTransform.transform=v.create();b.tileTransform.displayCoord=w.create();0<c.length&&(a=b.acquire).call.apply(a,
[b].concat(c));return b}t(f,q);f.prototype.reset=function(){z.pool.release(this.key);this.refKey=this.key=null;this.coords[0]=0;this.coords[1]=0;this.bounds[0]=0;this.bounds[1]=0;this.bounds[2]=0;this.height=this.width=this.bounds[3]=0;this.resolution=null;this.rotation=0;this.id=this.client=this.styleLayers=this._vectorTileData=null;this.tileTransform.transform.fill(0);this.tileTransform.displayCoord.fill(0);this.stencilData.mask=0;this.stencilData.reference=0;this._renderBuckets.length=0;this._symbolUpdateData=
null;this.status=m.TileStatus.INITIALIZED};f.prototype.acquire=function(a,c,b,h,e){this.key=a;this.refKey=c;c=b.lodAt(a.level);c=null!==c?c.resolution:0;var g=b.size[0]*c,n=b.origin,k=a.col*g,l=a.row*g,d=b.spatialReference,f=0;d&&(d._isWrappable?d._isWrappable():d.isWrappable)&&(d=x.getInfo(d),f=d.valid[1]-d.valid[0]);k=n.x+k+a.world*f;n=n.y-l;this.coords[0]=k;this.coords[1]=n;this.bounds[0]=k;this.bounds[1]=n;this.bounds[2]=k+g;this.bounds[3]=n-g;this.widthInPixels=b.size[1];this.coordRange=4096;
this.resolution=c;this.rotation=e;this.styleLayers=h;this.id=a.id};f.prototype.setData=function(a,c){this._vectorTileData=a;this.client=c;a&&a.bufferDataInfo||(this.status=m.TileStatus.NO_DATA)};f.prototype.updateSymbolData=function(a){a&&(this._symbolUpdateData=a,this.requestRender())};f.prototype.dispose=function(){for(var a="fillVertexArrayObject fillDDVertexArrayObject outlineVertexArrayObject lineVertexArrayObject lineDDVertexArrayObject iconVertexArrayObject iconDDVertexArrayObject textVertexArrayObject textDDVertexArrayObject circleVertexArrayObject fillVertexBuffer fillDDVertexBuffer fillIndexBuffer outlineVertexBuffer outlineDDVertexBuffer outlineIndexBuffer lineVertexBuffer lineDDVertexBuffer lineIndexBuffer iconVertexBuffer iconDDVertexBuffer iconIndexBuffer textVertexBuffer textDDVertexBuffer textIndexBuffer circleVertexBuffer circleIndexBuffer texture".split(" "),
c=0;c<a.length;++c){var b=a[c];this[b]&&(this[b].dispose(),this[b]=null)}this._renderBuckets.length=0;this.status=m.TileStatus.INITIALIZED};f.prototype.getCpuMemoryUsage=function(){return null!=this._vectorTileData&&this._vectorTileData.bufferData?this._vectorTileData.bufferData.reduce(function(a,c){return a+c.byteLength},0)+this._vectorTileData.bufferDataInfo.byteLength+this._vectorTileData.bucketDataInfo.byteLength:0};f.prototype.getGpuMemoryUsage=function(){var a=this,c=A.reduce(function(b,c){return a[c]?
b+a[c].size:b},0);this.texture&&(c+=this.texture.descriptor.width*this.texture.descriptor.height*4);return c};f.prototype.attach=function(a){if(this.status!==m.TileStatus.INITIALIZED)return!0;this._createRenderBuckets();this._createBufferObjects(a);this._vectorTileData=null;this.status=m.TileStatus.READY;return!0};f.prototype._createRenderBuckets=function(){if(0===this._renderBuckets.length)for(var a=new Uint32Array(this._vectorTileData.bucketDataInfo),c=a.length,b=0;b<c;){var h=a[b];switch(a[b+1]){case 0:var e=
new p.BackgroundRenderBucket;e.layerID=h;this._renderBuckets.push(e);b+=2;break;case 1:e=new p.FillRenderBucket;e.layerID=h;e.triangleElementStart=a[b+2];e.triangleElementCount=a[b+3];e.outlineElementStart=a[b+4];e.outlineElementCount=a[b+5];this._renderBuckets.push(e);b+=6;break;case 2:e=new p.LineRenderBucket;e.layerID=h;e.triangleElementStart=a[b+2];e.triangleElementCount=a[b+3];this._renderBuckets.push(e);b+=4;break;case 3:e=new p.SymbolRenderBucket;e.layerID=h;e.isSDF=0!==a[b+2];var g=b+3,h=
a[g];g++;if(0<h)for(var n=void 0,k=void 0,d=void 0,f=0;f<h;f++)n=a[g],k=a[g+1],d=a[g+2],e.markerPerPageElementsMap.set(n,[k,d]),g+=3;var m=a[g];g++;if(0<m)for(d=k=n=void 0,f=0;f<m;f++)n=a[g],k=a[g+1],d=a[g+2],e.glyphPerPageElementsMap.set(n,[k,d]),g+=3;this._renderBuckets.push(e);b+=5+3*h+3*m;break;case 4:e=new p.CircleRenderBucket;e.layerID=h;e.triangleElementStart=a[b+2];e.triangleElementCount=a[b+3];this._renderBuckets.push(e);b+=4;break;default:console.error("Bad bucket type!"),b+=2}}};f._createBufferToObject=
function(){var a=[];a[1]={create:d.createVertex,var:"fillVertexBuffer"};a[2]={create:d.createVertex,var:"fillDDVertexBuffer"};a[3]={create:d.createIndex,var:"fillIndexBuffer"};a[4]={create:d.createVertex,var:"outlineVertexBuffer"};a[5]={create:d.createVertex,var:"outlineDDVertexBuffer"};a[6]={create:d.createIndex,var:"outlineIndexBuffer"};a[7]={create:d.createVertex,var:"lineVertexBuffer"};a[9]={create:d.createIndex,var:"lineIndexBuffer"};a[10]={create:d.createVertex,var:"iconVertexBuffer"};a[11]=
{create:d.createVertex,var:"iconDDVertexBuffer"};a[12]={create:d.createIndex,var:"iconIndexBuffer"};a[13]={create:d.createVertex,var:"textVertexBuffer"};a[14]={create:d.createVertex,var:"textDDVertexBuffer"};a[15]={create:d.createIndex,var:"textIndexBuffer"};a[16]={create:d.createVertex,var:"circleVertexBuffer"};a[17]={create:d.createIndex,var:"circleIndexBuffer"};return a};f.prototype._createBufferObjects=function(a){a=a.context;for(var c=new Uint32Array(this._vectorTileData.bufferDataInfo),b=c.length,
h=0,e=0;e<b;e+=2,h++){var g=c[e];if(!(0>=c[e+1]||0===this._vectorTileData.bufferData[h].byteLength)){var d=f.bufferToObject[g];d?this[d.var]?this[d.var].setData(this._vectorTileData.bufferData[h]):this[d.var]=d.create(a,35044,this._vectorTileData.bufferData[h]):console.error("Bad buffer type "+g)}}};f.prototype.detach=function(a){this.client&&this.status!==m.TileStatus.INVALID&&this.status!==m.TileStatus.INITIALIZED&&this.client.invoke("destructTileData",this.id);this.dispose();q.prototype.detach.call(this,
a)};f.prototype.doRender=function(a){if(this.visible&&this.status===m.TileStatus.READY){var c=a.context,b=a.renderer;if(c&&b){var d=a.drawphase;this._symbolUpdateData&&this._updateSymbolData(a);c.setStencilFunction(514,this.stencilData.reference,this.stencilData.mask);var e=this.styleLayers,g=void 0!==a.layerOpacity?a.layerOpacity:1;if(0!==g){var f=this._renderBuckets.length;if(0===d)for(var k=f-1;0<=k;k--){var l=this._renderBuckets[k];1!==l.type&&0!==l.type||!l.hasData()||b.renderBucket(c,l,a.displayLevel,
a.requiredLevel,d,this,e.layers[l.layerID],g)}else for(k=0;k<f;k++)l=this._renderBuckets[k],l.hasData()&&b.renderBucket(c,l,a.displayLevel,a.requiredLevel,d,this,e.layers[l.layerID],g)}}}};f.prototype._updateSymbolData=function(a){if(!this._symbolUpdateData.bucketDataInfo)return!0;var c=new Uint32Array(this._symbolUpdateData.bucketDataInfo),b=c.length;if(0===b)return this._symbolUpdateData=null,!0;if(this.status!==m.TileStatus.READY)return this.requestRender(),!1;a=a.context;for(var h=new Uint32Array(this._symbolUpdateData.bufferDataInfo),
e=h.length,g=0,f=0;f<e;f+=2,g++)switch(h[f]){case 10:this.iconVertexBuffer&&(this.iconVertexBuffer.dispose(),this.iconVertexBuffer=null);this.iconVertexBuffer=d.createVertex(a,35044,this._symbolUpdateData.bufferData[g]);break;case 11:this.iconDDVertexBuffer&&(this.iconDDVertexBuffer.dispose(),this.iconDDVertexBuffer=null);this.iconDDVertexBuffer=d.createVertex(a,35044,this._symbolUpdateData.bufferData[g]);break;case 12:this.iconIndexBuffer&&(this.iconIndexBuffer.dispose(),this.iconIndexBuffer=null);
this.iconIndexBuffer=d.createIndex(a,35044,this._symbolUpdateData.bufferData[g]);break;case 13:this.textVertexBuffer&&(this.textVertexBuffer.dispose(),this.textVertexBuffer=null);this.textVertexBuffer=d.createVertex(a,35044,this._symbolUpdateData.bufferData[g]);break;case 14:this.textDDVertexBuffer&&(this.textDDVertexBuffer.dispose(),this.textDDVertexBuffer=null);this.textDDVertexBuffer=d.createVertex(a,35044,this._symbolUpdateData.bufferData[g]);break;case 15:this.textIndexBuffer&&(this.textIndexBuffer.dispose(),
this.textIndexBuffer=null),this.textIndexBuffer=d.createIndex(a,35044,this._symbolUpdateData.bufferData[g])}a=this._renderBuckets.length;for(h=0;h<a;h++)this._renderBuckets[h]instanceof p.SymbolRenderBucket&&(e=this._renderBuckets[h],e.markerPerPageElementsMap.clear(),e.glyphPerPageElementsMap.clear());for(a=0;a<b;){e=c[a];g=-1;f=this._renderBuckets.length;for(h=0;h<f;h++)if(this._renderBuckets[h].layerID===e){g=h;break}h=this._renderBuckets[g];h||(h=new p.SymbolRenderBucket,h.layerID=e,h.isSDF=0!==
c[a+2],this._renderBuckets.push(h));var k=a+3,e=c[k];k++;if(0<e)for(var l=f=g=void 0,r=0;r<e;r++)g=c[k],f=c[k+1],l=c[k+2],h.markerPerPageElementsMap.set(g,[f,l]),k+=3;var q=c[k];k++;if(0<q)for(l=f=g=void 0,r=0;r<q;r++)g=c[k],f=c[k+1],l=c[k+2],h.glyphPerPageElementsMap.set(g,[f,l]),k+=3;a+=5+3*e+3*q}this.iconVertexArrayObject&&(this.iconVertexArrayObject.dispose(),this.iconVertexArrayObject=null);this.iconDDVertexArrayObject&&(this.iconDDVertexArrayObject.dispose(),this.iconDDVertexArrayObject=null);
this.textVertexArrayObject&&(this.textVertexArrayObject.dispose(),this.textVertexArrayObject=null);this.textDDVertexArrayObject&&(this.textDDVertexArrayObject.dispose(),this.textDDVertexArrayObject=null);this._symbolUpdateData=null;return!0};f.pool=new u(f);f.bufferToObject=f._createBufferToObject();return f}(y)});