// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","../../lib/gl-matrix","../../webgl-engine/lib/Selector","../../webgl-engine/lib/SelectorUtils"],function(r,v,e,m,w){function n(f,a,d,c,b){d?e.vec3d.set(a.eye,c):e.vec3d.unproject(e.vec3d.createFrom(f[0],f[1],0),a.viewMatrix,a.projectionMatrix,a.fullViewport,c);e.vec3d.unproject(e.vec3d.createFrom(f[0],f[1],1),a.viewMatrix,a.projectionMatrix,a.fullViewport,b)}Object.defineProperty(v,"__esModule",{value:!0});r=function(){function f(a,d,c){this.viewingMode=a;this.layerProvider=
d;this.viewPropertyProvider=c;this.tmpR0=e.vec3d.create();this.tmpR1=e.vec3d.create();this.tmpScreenPoint=e.vec2d.create();this.tmpScreenPointHud=e.vec2d.create();this.tmpPointHud=e.vec3d.create();this.tmpSelector=new m(this.viewingMode);this.externalIntersectionHandlers=new Set;this.intersectionTolerance=m.DEFAULT_TOLERANCE;this.validateHUDSelector=new m(this.viewingMode);this.validateHUDSelector.enableHUDSelection=!1}f.prototype.getPickRay=function(a,d,c){void 0===d&&(d=e.vec3d.create());void 0===
c&&(c=e.vec3d.create());var b=this.viewPropertyProvider.camera();n(a,b,!1,d,c)};f.prototype.pickPointInScreen=function(a,d,c){var b=this.viewPropertyProvider.camera();n(a,b,!1,this.tmpR0,this.tmpR1);return this.pickPointFromSegment(this.tmpR0,this.tmpR1,d,c)};f.prototype.pickPointFromSegment=function(a,d,c,b){b=this.computeIntersection(a,d,null,null,!1,b||this.tmpSelector);c=b?(a=b.minResult)?a.getIntersectionPoint(c):!1:!1;return c};f.prototype.pickFreePointInScreen=function(a,d){var c=this.viewPropertyProvider.camera();
n(a,c,!1,this.tmpR0,this.tmpR1);this.pickFreePointFromSegment(this.tmpR0,this.tmpR1,d)};f.prototype.pickFreePointFromSegment=function(a,d,c){e.vec3d.set(a,this.tmpR0);e.vec3d.set(d,this.tmpR1);e.vec3d.subtract(this.tmpR1,this.tmpR0);e.vec3d.normalize(this.tmpR1);var b=this.viewPropertyProvider.extent();a=Math.max(b.xmax-b.xmin,b.ymax-b.ymin,8*Math.max(b.xmax-b.xmin,b.ymax-b.ymin));var g=this.viewPropertyProvider.camera();d=Math.max(0,b.xmin-g.eye[0],g.eye[0]-b.xmax);b=Math.max(0,b.ymin-g.eye[1],g.eye[1]-
b.ymax);g=a/Math.max(1,Math.pow(Math.max(0,Math.log(a/(Math.abs(g.relativeElevation)+Number.MIN_VALUE))),2));g=Math.max(g,Math.min(Math.sqrt(d*d+b*b),a));e.vec3d.scale(this.tmpR1,g);e.vec3d.add(this.tmpR0,this.tmpR1,c)};f.prototype.pickSelectorInScreen=function(a,d,c,b){void 0===b&&(b=!1);var e=this.viewPropertyProvider.camera();n(a,e,!1,this.tmpR0,this.tmpR1);return this.computeIntersection(this.tmpR0,this.tmpR1,a,c,b,d)};f.prototype.setTolerance=function(a){void 0===a&&(a=m.DEFAULT_TOLERANCE);this.intersectionTolerance=
a};f.prototype.addIntersectionHandler=function(a){this.externalIntersectionHandlers.add(a)};f.prototype.removeIntersectionHandler=function(a){this.externalIntersectionHandlers.delete(a)};f.prototype.computeIntersection=function(a,d,c,b,f,h){var g=this,p=this.viewPropertyProvider.camera();c||(c=this.tmpScreenPoint,p.projectPoint(d,c));var t=this.layerProvider.getPickableLayers();b&&(t=t.filter(function(a){return b.has(a.id)}));var q=this.viewPropertyProvider.slicePlane(),q=q?w.sliceFilterPredicate(q):
null;h=h||new m(this.viewingMode);h.init(t,a,d,c,p,this.intersectionTolerance,f,q);this.externalIntersectionHandlers.forEach(function(b){b.intersect(h,a,d,c)});if(h.hudResults.length){var l=h.hudResults;l.sort(function(a,b){return b.dist-a.dist});var l=l[l.length-1],k=this.tmpScreenPointHud;p.projectPoint(l.center,k);k[0]=Math.round(k[0]);k[1]=Math.round(k[1]);var u=this.tmpPointHud;n(k,p,!1,a,u);var r=e.vec3d.dist(l.center,a)/e.vec3d.dist(a,u)*.99;this.validateHUDSelector.init(t,a,u,k,p,this.intersectionTolerance,
f,q);this.externalIntersectionHandlers.forEach(function(b){b.intersect(g.validateHUDSelector,a,u,k)});f=this.validateHUDSelector.minResult;(null==f.dist||r<=f.dist)&&h.minResult.copyFrom(l)}return h};return f}();v.SceneIntersectionHelper=r});