// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../core/tsSupport/decorateHelper dojo/errors/CancelError dojo/promise/all ../../../request ../../../core/arrayUtils ../../../core/arrayUtils ../../../core/Handles ../../../core/Logger ../../../core/promiseUtils ../../../core/requireUtils ../../../core/screenUtils ../../../core/watchUtils ../../../core/workers ../../../core/accessorSupport/decorators ../../../geometry/support/aaBoundingBox ../../../geometry/support/scaleUtils ../../../symbols/support/unitConversionUtils ./LayerView3D ./PointCloudWorker ./i3s/I3SUtil ./i3s/IdleQueue ./i3s/LoDUtil ./i3s/PagedNodeIndex ./i3s/PointCloudRendererUtil ./i3s/PointRenderer ./support/layerViewUpdatingProperties ../lib/gl-matrix ../support/geometryUtils ../support/orientedBoundingBox ../support/projectionUtils ../webgl-engine/lib/RenderSlot module".split(" "),
function(A,X,B,h,C,t,u,D,m,E,F,n,G,H,f,I,g,J,K,L,M,N,v,O,p,P,l,w,Q,q,x,R,S,T,U){var y=F.getLogger("esri.views.3d.layers.PointCloudLayerView3D"),V=x.plane.create();return function(r){function b(){var a=null!==r&&r.apply(this,arguments)||this;a.maximumPointCount=4E6;a.slicePlaneEnabled=!1;a._renderer=null;a._rendererAdded=!1;a._renderedNodes=new Set;a._updateViewNeeded=!0;a._lodFactor=1;a._worker=new N;a._workerThread=null;a._maxLoggedBoxWarnings=5;a._pageMultiplier=1;a._handles=new E;a._indexQueue=
[];a._workQueue=[];a._idleQueue=new O.IdleQueue;a._indexPagesLoading=new Map;a._loadingNodes=new Map;a._layerIsVisible=!1;a._totalWork=0;a._index=null;a._loadingInitNodePage=!1;a._nodeIdArray=[];return a}B(b,r);Object.defineProperty(b.prototype,"pointScale",{get:function(){var a=l.getSplatSizeAlgorithm(this.layer.renderer);return a&&null!=a.scaleFactor?a.scaleFactor:1},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"useRealWorldSymbolSizes",{get:function(){var a=l.getFixedSizeAlgorithm(this.layer.renderer);
return a&&null!=a.useRealWorldSymbolSizes?a.useRealWorldSymbolSizes:!1},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"pointSize",{get:function(){var a=l.getFixedSizeAlgorithm(this.layer.renderer);return a&&null!=a.size?a.size:0},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"inverseDensity",{get:function(){return this.layer.renderer?96/this.layer.renderer.pointsPerInch:5},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"_clippingBox",{get:function(){var a=
J.create();return S.extentToBoundingBox(this.view.clippingArea,a,this.view.renderSpatialReference)?a:null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"_elevationOffset",{get:function(){var a=this.layer.elevationInfo;if(a&&"absolute-height"===a.mode){var c=K.getMetersPerVerticalUnitForSR(this.layer.spatialReference),b=L.getMetersPerUnit(a.unit);return(a.offset||0)*b/c}return 0},enumerable:!0,configurable:!0});b.prototype.initialize=function(){var a=this;v.checkPointCloudLayerValid(this.layer);
v.checkPointCloudLayerCompatibleWithView(this.layer,this.view);this._initRenderer();var c=this._initNodePages(),b={idleBegin:function(){return a._idleBegin()},idleEnd:function(){return a._idleEnd()}};I.open(G.getAbsMid("./PointCloudWorker",A,U),{client:this}).then(function(c){a.destroyed?c.close():a._workerThread=c});this._memCache=this.view.resourceController.getMemCache(this.layer.uid);this._handles.add(f.init(this,"_clippingBox",function(){return a._setUpdateViewNeeded()}));this._handles.add(f.init(this,
"_elevationOffset",function(){return a._elevationOffsetChanged()}));this._handles.add(f.init(this.layer,"renderer",function(){return a._rendererChanged()}));this._handles.add(f.init(this,"clippingArea",function(){a._setUpdateViewNeeded()}));this._handles.add(this.view.state.watch("camera",function(){a._setUpdateViewNeeded()}));this.view.resourceController.memoryEvents.on("quality-changed",function(){return a._setUpdateViewNeeded()});this.addResolvingPromise(c);this.when(function(){a._handles.add(a.view.resourceController.registerFrameWorker(function(c){return a._process(c)}));
a._handles.add(a.view.resourceController.registerIdleFrameWorker(b));a._handles.add(f.init(a,"suspended",function(c){c?a._clearNodeState():a._setUpdateViewNeeded()}))})};b.prototype._setUpdateViewNeeded=function(){this._updateViewNeeded=!0;this._updateLoading()};b.prototype.destroy=function(){this._cancelNodeLoading();this._workerThread&&(this._workerThread.close(),this._workerThread=null);this._handles.destroy();this._destroyRenderer();this._memCache.destroy();this._memCache=null};b.prototype._initRenderer=
function(){var a=this;this._renderer=new w;this._renderer.layerUid=this.layer.uid;this._handles.add(f.init(this,"_clippingBox",function(c){a._renderer.clippingBox=c}));this._handles.add(f.init(this,"_clippingBox",function(c){a._renderer.clippingBox=c}));this._handles.add(f.init(this,"suspended",function(c){return a._setPointsVisible(!c)}));this._handles.add(f.init(this,"pointScale",function(c){a._renderer.scaleFactor=c}));this._renderer.minSizePx=Math.sqrt(2);this._handles.add(f.init(this,"useRealWorldSymbolSizes",
function(c){a._renderer.useRealWorldSymbolSizes=c}));this._handles.add(f.init(this,"pointSize",function(c){var b=H.pt2px(c);a._renderer.size=c;a._renderer.sizePx=b}));this._handles.add(f.init(this,"slicePlaneEnabled",function(c){a._renderer.slicePlaneEnabled=c}));this._handles.add(f.init(this,["inverseDensity","maximumPointCount"],function(){a._setUpdateViewNeeded()}));this._handles.add(f.init(this.view,"qualitySettings.sceneService.pointCloud.lodFactor",function(c){a._lodFactor=c;a._setUpdateViewNeeded()}))};
b.prototype._destroyRenderer=function(){this._setPointsVisible(!1)};b.prototype._setPointsVisible=function(a){a&&!this._rendererAdded?(this.view._stage.addRenderPlugin([T.OPAQUE_EXTERNAL],this._renderer),this._rendererAdded=!0):!a&&this._rendererAdded&&(this.view._stage.removeRenderPlugin(this._renderer),this._rendererAdded=!1)};b.prototype._rendererChanged=function(){this._clearNodeState();this._memCache.clear();this._renderer.useFixedSizes=l.rendererUsesFixedSizes(this.layer.renderer);this._setUpdateViewNeeded()};
b.prototype._elevationOffsetChanged=function(){this._clearNodeState();this._memCache.clear();this._initNodePages()};b.prototype.displayNodes=function(a){this._workQueue=p.nodeDiff(m.keysOfSet(this._renderedNodes),a,this._index);p.sortFrontToBack(this._workQueue,this.view.state.camera.viewForward,this._index);p.splitWorkEntries(this._workQueue,8,this._index);this._updateQueues();this._totalWork=this._computeWork();this._updateLoading();this._layerIsVisible=0<a.length||this._loadingInitNodePage;this.notifyChange("suspended")};
b.prototype.cancelLoading=function(){this._cancelNodeLoading();this._cancelIndexLoading()};b.prototype._cancelNodeLoading=function(){var a=[];this._loadingNodes.forEach(function(c){return a.push(c)});this._loadingNodes.clear();for(var c=0;c<a.length;c++)a[c].cancel();this._workQueue=[];this._idleQueue.cancelAll();this._totalWork=this._computeWork();this._updateLoading()};b.prototype._updateQueues=function(){var a=this,c=new Set;this._workQueue.forEach(function(a){a.load.forEach(function(a){c.add(a)})});
var b=[],d=new Map;this._loadingNodes.forEach(function(a,k){c.has(k)?d.set(k,a):b.push(a)});this._loadingNodes=d;for(var e=0;e<b.length;e++)b[e].cancel();this._workQueue=this._workQueue.filter(function(c){var b=0;for(c=c.load;b<c.length;b++)if(a._loadingNodes.has(c[b]))return!1;return!0});this._totalWork=this._computeWork();this._updateLoading()};b.prototype._cancelIndexLoading=function(){this._indexQueue=[];this._indexPagesLoading.forEach(function(a){return a.cancel()});this._indexPagesLoading.clear();
this._totalWork=this._computeWork();this._updateLoading()};b.prototype._clearNodeState=function(){var a=this;this._renderedNodes.forEach(function(c){return a._removeFromRenderer(c)});this._cancelNodeLoading()};b.prototype._idleBegin=function(){this._setUpdateViewNeeded()};b.prototype._idleEnd=function(){this._setUpdateViewNeeded()};b.prototype._process=function(a){if(this.suspended)this._updateViewNeeded&&(this._updateViewNeeded=!1,a=this._isRootNodeVisible(),a!==this._layerIsVisible&&(this._layerIsVisible=
a,this.notifyChange("suspended")));else{for(this._updateViewNeeded&&!a.done()&&this._updateWorkQueues();0<this._indexQueue.length&&!a.done();)this._processIndexQueue();for(this._processWorkQueue(a);0<this._idleQueue.length()&&!a.done();)this._idleQueue.process()}};b.prototype._processIndexQueue=function(){var a=this,c=this._indexQueue.shift();this._indexPagesLoading.set(c,this._loadNodePage(c));this._indexPagesLoading.get(c).then(function(b){a._index.addPage(c,b,a._elevationOffset);a._setUpdateViewNeeded()}).always(function(){a._indexPagesLoading.delete(c)})};
b.prototype._processWorkQueue=function(a){for(;!a.done();){var c=this._scheduleWorkEntry();if(!c)break;this._processWorkEntry(c)}};b.prototype._scheduleWorkEntry=function(){var a=this;if(8<=this._loadingNodes.size)return null;for(var c=0;c<this._workQueue.length;++c){var b=this._workQueue[c];if(!D.find(b.remove,function(c){return!a._renderedNodes.has(c)})){for(;0<c;--c)this._workQueue[c]=this._workQueue[c-1];this._workQueue.shift();return b}}return null};b.prototype._processWorkEntry=function(a){var c=
this;if(0===a.load.length)for(var b=0;b<a.remove.length;b++)this._removeFromRenderer(a.remove[b]);else t(a.load.map(function(a){var b=c._memCache.pop(a.toString());b?c._loadingNodes.set(a,n.resolve(b)):c._loadingNodes.has(a)||c._loadingNodes.set(a,c.loadNode(a));return c._loadingNodes.get(a)})).then(function(b){for(var d=0;d<a.load.length;d++)if(b[d]){var k=c._setupRendererData(a.load[d],b[d]);c._addToRenderer(k)}for(d=0;d<a.remove.length;d++)c._removeFromRenderer(a.remove[d])}).always(function(){for(var b=
0;b<a.load.length;b++)c._loadingNodes.delete(a.load[b]);c._updateLoading()}),this._updateLoading()};b.prototype._computeWork=function(){for(var a=0,c=0;c<this._workQueue.length;c++)a+=this._workQueue[c].load.length;a+=this._loadingNodes.size;a+=(this._indexQueue.length+this._indexPagesLoading.size)*this._index.pageSize;a+=this._loadingInitNodePage?100:0;return a+=this._updateViewNeeded?100:0};Object.defineProperty(b.prototype,"updatingPercentageValue",{get:function(){var a=this._computeWork();return 100*
Math.min(this._totalWork,a)/this._totalWork},enumerable:!0,configurable:!0});b.prototype._updateLoading=function(){this.notifyChange("updating");this.notifyChange("updatingPercentageValue")};b.prototype.canResume=function(){return this.inherited(arguments)&&this._layerIsVisible};b.prototype.isUpdating=function(){return 0<this._computeWork()};b.prototype._initNodePages=function(){var a=this,c=this.layer.store.index;this._index=new P(this.layer.spatialReference,this.view.renderCoordsHelper.spatialReference,
c.nodesPerPage||c.nodePerIndexBlock);this._cancelIndexLoading();this._traverseVisible=this._index.createVisibilityTraverse();this._layerIsVisible=this._loadingInitNodePage=!0;this.notifyChange("suspended");this._updateLoading();this._pageMultiplier=null!=c.nodesPerPage?1:c.nodePerIndexBlock;return this._loadNodePage(0).then(function(c){a._index.addPage(0,c,a._elevationOffset);a._loadingInitNodePage=!1;a._setUpdateViewNeeded()})};b.prototype._loadNodePage=function(a){var c=this;return this._requestJSON(this.baseUrl+
"/nodepages/"+a*this._pageMultiplier).then(function(b){return b.data.nodes.map(function(b,k){return{resourceId:null!=b.resourceId?b.resourceId:a*c._index.pageSize+k,obb:b.obb,firstChild:b.firstChild,childCount:b.childCount,vertexCount:null!=b.vertexCount?b.vertexCount:b.pointCount,lodThreshold:null!=b.lodThreshold?b.lodThreshold:b.effectiveArea}})})};b.prototype._updateWorkQueues=function(){for(var a=this.inverseDensity/this._lodFactor*this._getLodMemoryFactor(),c=this.maximumPointCount*this._lodFactor*
this._getLodMemoryFactor(),b=this._computeNodesForMinimumDensity(a),d=this._computePointCount(b),e=Math.sqrt(d/(.75*c));d>c;)a*=e,b=this._computeNodesForMinimumDensity(a),d=this._computePointCount(b),e=Math.sqrt(2);this.displayNodes(b);this._updateViewNeeded=!1;this._updateLoading()};b.prototype._computePointCount=function(a){for(var c=0,b=0;b<a.length;b++){var d=this._index.getNode(a[b]);d&&(c+=d.vertexCount)}return c};b.prototype._getLodMemoryFactor=function(){return this.view.resourceController.memoryFactor};
b.prototype._isRootNodeVisible=function(){var a=!1;this._traverseVisible({frustumPlanes:this.view.state.camera.frustumPlanes,clippingBox:this._clippingBox},{predicate:function(c,b,d){a=d;return!1},pageMiss:function(a,b){}});return a};b.prototype._computeNodesForMinimumDensity=function(a){var c=this,b=this.view.state.camera,d=b.frustumPlanes,e=this._clippingBox,z=b.viewForward,W=q.vec3d.dot(z,b.eye),f=x.plane.fromNormalAndOffset(z,-W,V),g=b.perPixelRatio,h=a*a,l=this._nodeIdArray;l.length=0;this._traverseVisible({frustumPlanes:d,
clippingBox:e},{predicate:function(a,b,d){if(!d)return!1;if(0===b.childCount)return l.push(a),!1;d=c._index.getRenderObb(a);return c._computeAveragePixelArea(d,b.lodThreshold,b.vertexCount,f,g)<=h?(l.push(a),!1):!0},pageMiss:function(a,b){l.push(a);0>c._indexQueue.indexOf(b)&&c._indexQueue.push(b)}});return l};b.prototype._computeAveragePixelArea=function(a,c,b,d,e){a=Math.max(1E-7,R.minimumDistancePlane(a,d));return c/(a*a)/(4*e*e)/b};b.prototype.loadNode=function(a){var c=this,b=this._index.getNode(a),
d=l.getRendererInfo(this.layer),e=[];return this._idleQueue.push().then(function(){var a=b.resourceId,k=c.loadGeometry(a),f=c.loadAttribute(a,d.primaryAttribute),a=c.loadAttribute(a,d.modulationAttribute);e=[k,f,a];return t(e)}).then(function(b){var e=b[0],k=b[1],f=b[2];b=[e];k&&b.push(k);f&&b.push(f);e={geometryBuffer:e,primaryAttribute:k,modulationAttribute:f,schema:c.layer.store.defaultGeometrySchema,rendererInfo:d,obb:c._index.getRenderObb(a),elevationOffset:c._elevationOffset,inSR:c.layer.spatialReference.toJSON(),
outSR:c.view.renderCoordsHelper.spatialReference.toJSON()};return c._workerThread?c._workerThread.invoke("process",e,b):n.resolve(c._worker.transform(e))}).catch(function(a){if(a instanceof C)for(var b=0,c=e;b<c.length;b++)c[b].cancel();else console.error(a);return n.reject(a)})};b.prototype.loadGeometry=function(a){return this._requestBinary(this.baseUrl+"/nodes/"+a+"/geometries/0").then(function(a){return a.data})};b.prototype.loadAttribute=function(a,b){return b&&b.storageInfo?this._requestBinary(this.baseUrl+
"/nodes/"+a+"/attributes/"+b.storageInfo.key).then(function(a){return a.data}):n.resolve(null)};b.prototype._requestJSON=function(a){return u(a,{query:{f:"json"},responseType:"json"})};b.prototype._requestBinary=function(a){return u(a,{responseType:"array-buffer"})};b.prototype._removeFromRenderer=function(a){if(this._renderedNodes.has(a)){var b=this._renderer.removeNode(a);this._renderedNodes.delete(a);this._memCache.put(b.id.toString(),b,5*b.coordinates.length+128)}};b.prototype._addToRenderer=
function(a){this._renderedNodes.has(a.id)||(this._renderedNodes.add(a.id),this._renderer.addNode(a))};b.prototype._setupRendererData=function(a,b){var c=this._index.getNode(a),d=Math.sqrt(c.lodThreshold/c.vertexCount),e=this._index.getRenderObb(a);if(w.isInstanceOfNode(b))return b.splatSize=d,b.obb=e,b.origin=q.vec3.create(b.obb.center),b;if(b.obb.halfSize[0]>e.halfSize[0]||b.obb.halfSize[1]>e.halfSize[1]||b.obb.halfSize[2]>e.halfSize[2])0<this._maxLoggedBoxWarnings&&(y.warn("Node",a,"reported bounding box too small, got",
e,"but points cover",b.obb),0===--this._maxLoggedBoxWarnings&&y.warn("  Too many bounding box errors, stopping reporting for this layer.")),this._index.setRenderObb(a,b.obb);return{id:a,coordinates:b.points,origin:q.vec3.create(e.center),rgb:new Uint8Array(b.rgb),splatSize:d,obb:e,isLeaf:0===c.childCount}};b.prototype.getUsedMemory=function(){var a=this;return m.keysOfSet(this._renderedNodes).reduce(function(b,f){return b+15*a._index.getNode(f).vertexCount+128},0)};b.prototype.getUnloadedMemory=function(){var a=
this,b=this._renderedNodes.size;if(4>b)return 0;for(var f=m.keysOfSet(this._renderedNodes).reduce(function(b,c){return b+a._index.getNode(c).vertexCount}),d=this._loadingNodes.size,e=0;e<this._workQueue.length;e++)d+=this._workQueue[e].load.length,d-=this._workQueue[e].remove.length;return 0>d?0:d*f/b*15+128*d};b.prototype.getStats=function(){var a=this;return{"Rendered Nodes":this._renderedNodes.size,"Rendered Points":m.keysOfSet(this._renderedNodes).reduce(function(b,f){return b+a._index.getNode(f).vertexCount},
0),"Loading Nodes":this._loadingNodes.size,"Index Queue":this._indexQueue.length,"Work Queue":this._workQueue.length,"Idle Queue":this._idleQueue.length()}};h([g.property()],b.prototype,"layer",void 0);h([g.property({readOnly:!0,aliasOf:"layer.parsedUrl.path"})],b.prototype,"baseUrl",void 0);h([g.property({readOnly:!0,dependsOn:["layer.renderer"]})],b.prototype,"pointScale",null);h([g.property({readOnly:!0,dependsOn:["layer.renderer"]})],b.prototype,"useRealWorldSymbolSizes",null);h([g.property({readOnly:!0,
dependsOn:["layer.renderer"]})],b.prototype,"pointSize",null);h([g.property({readOnly:!0,dependsOn:["layer.renderer"]})],b.prototype,"inverseDensity",null);h([g.property()],b.prototype,"maximumPointCount",void 0);h([g.property({readOnly:!0,dependsOn:["view.clippingArea"]})],b.prototype,"_clippingBox",null);h([g.property({readOnly:!0,dependsOn:["layer.elevationInfo"]})],b.prototype,"_elevationOffset",null);h([g.property({type:Boolean})],b.prototype,"slicePlaneEnabled",void 0);h([g.property(Q.updatingPercentage)],
b.prototype,"updatingPercentage",void 0);h([g.property({readOnly:!0})],b.prototype,"updatingPercentageValue",null);return b=h([g.subclass("esri.views.3d.layers.PointCloudLayerView3D")],b)}(g.declared(M))});