// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../Graphic ../../../core/Handles ../../../core/has ../../../core/Logger ../../../core/PooledArray ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators ../../../core/libs/rbush/PooledRBush ../../../geometry/support/aaBoundingBox ../../../geometry/support/aaBoundingRect ../../../geometry/support/contains ../../../layers/graphics/dehydratedFeatures ../../../layers/graphics/controllers/I3SOnDemandController ../../../renderers/support/renderingInfoUtils ./LayerView3D ./graphics/Graphics3DFeatureLikeLayerView ./graphics/Graphics3DVerticalScale ./i3s/I3SQueryEngine ./i3s/I3SUtil ./support/layerViewUpdatingProperties ../lib/gl-matrix ../support/EventedArray ../support/orientedBoundingBox ../support/projectionUtils".split(" "),
function(v,fa,K,h,L,M,N,O,P,t,I,g,Q,u,J,R,C,S,T,U,V,W,X,w,Y,Z,aa,ba,D){var E=O.getLogger("esri.views.3d.layers.SceneLayerGraphicsView3D");v=function(v){function b(a){a=v.call(this)||this;a._nodesAddedToStage={};a._handles=new M;a.overlayUpdating=!1;a.supportsDraping=!0;a._queryEngine=null;a._memCache=null;a._usedMemory=0;a.loadedGraphics=new aa;a.supportsHeightUnitConversion=!0;a._coordinatesOutsideExtentErrors=0;a._maxCoordinatesOutsideExtentErrors=20;a._definitionExpressionErrors=0;a._maxDefinitionExpressionErrors=
20;return a}K(b,v);b.prototype.initialize=function(){var a=this;w.checkSpatialReferences(this.layer,this.view.spatialReference,this.view.viewingMode);this._handles.add([I.init(this.layer,"rangeInfos",function(d){return a._rangeInfosChanged(d)}),this.layer.watch("renderer",function(d,e){return a._rendererChange(d,e)}),this.layer.watch("objectIdFilter",function(){return a._objectIdFilterChange()}),this.watch("_controller.parsedDefinitionExpression",function(){return a._definitionExpressionChange()})]);
this.graphics3d=new V({owner:this,layer:this.layer,asyncGraphicsUpdates:!0,frustumVisibilityEnabled:!1,elevationAlignmentEnabled:!0,elevationFeatureExpressionEnabled:!1,suspendResumeExtentMode:"data",dataExtent:this.layer.fullExtent,updateClippingExtent:function(d){return a._updateClippingExtent(d)},queryGraphicUIDsInExtent:function(d,e,c){return a._queryGraphicUIDsInExtent(d,e,c)}});this.supportsHeightUnitConversion&&(this._verticalScale=new W({sourceSpatialReference:this.layer.spatialReference,
destSpatialReference:this.view.spatialReference}));this.addResolvingPromise(this.graphics3d.setup());this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this._memCache=this.view.resourceController.getMemCache(this.layer.uid);this._controller=new S({layerView:this});this.when(function(){a._handles.add(a.graphics3d.graphicsCore.watch("maxNumberOfFeatures",function(d){a._controller.featureTarget=d}));a._handles.add(I.init(a,"suspended",function(d){d&&a._removeAllNodeData()}))})};b.prototype.destroy=
function(){this.graphics3d&&(this.graphics3d.destroy(),this.graphics3d=null);this._controller&&(this._controller.destroy(),this._controller=null);this._memCache.destroy();this._nodesAddedToStage=this._elevationUpdateNodes=this._memCache=null;this._usedMemory=0;this._handles&&(this._handles.destroy(),this._handles=null)};Object.defineProperty(b.prototype,"displayLimitExceeded",{get:function(){return this.suspended?!1:!!this._controller&&!this._controller.leafsReached},enumerable:!0,configurable:!0});
b.prototype.whenGraphicAttributes=function(a,d){var e=this;return w.whenGraphicAttributes(this.layer,[a],this._getObjectIdField(),d,function(){var c=e._findGraphicNodeAndIndex(a);return{node:c.node,indices:[c.index]}},{ignoreUnavailableFields:!0,populateObjectId:!0}).then(function(a){return a[0]})};b.prototype.getGraphicFromGraphicUid=function(a){if(!this.loadedGraphics)return t.reject();var d=C.hydrateGraphic(this.loadedGraphics.find(function(c){return c.uid===a}),this.layer),e=this._getObjectIdField();
if(!d||!d.attributes||!d.attributes[e])return t.reject();d.layer=this.layer;d.sourceLayer=this.layer;return t.resolve(d)};b.prototype.whenGraphicBounds=function(a,d){return this.graphics3d.graphicsCore.whenGraphicBounds(a,d)};b.prototype.canResume=function(){return this.inherited(arguments)&&(!this._controller||this._controller.rootNodeVisible)};b.prototype.isUpdating=function(){return this.overlayUpdating||this._controller&&this._controller.updating||!this.graphics3d.destroyed&&this.graphics3d.updating};
b.prototype.getRenderingInfo=function(a){if((a=T.getRenderingInfo(a,{renderer:this.layer.renderer}))&&a.color){var d=a.color;d[0]/=255;d[1]/=255;d[2]/=255}return a};Object.defineProperty(b.prototype,"symbolUpdateType",{get:function(){return this.graphics3d.graphicsCore.symbolUpdateType},enumerable:!0,configurable:!0});b.prototype._findGraphicNodeAndIndex=function(a){a=a.attributes[this.layer.objectIdField];for(var d=0,e=Object.keys(this._nodesAddedToStage);d<e.length;d++){var c=e[d],b=this._findGraphicIndex(this._nodesAddedToStage[c].bundle,
a);if(0<=b)return{node:this._controller.nodeIndex[c],index:b}}return null};b.prototype._forAllFeatures=function(a,d){for(var b=0,c=Object.keys(this._nodesAddedToStage);b<c.length;b++){for(var f=c[b],n=this._nodesAddedToStage[f].bundle,k=0;k<n.length;k++)for(var q=n[k].graphics,m=0;m<q.length;m++){var l=q[m],p=n[k].featureIds[m];l.visible&&a(p,k,l)}null!=d&&d({nodeId:f})}};b.prototype._getGraphicIndices=function(a,d){a=this._nodesAddedToStage[a];for(var b=this._getObjectIdField(),c=[],f=0;f<d.length;f++){var n=
this._findGraphicIndex(a.bundle,d[f].attributes[b]);0<=n&&c.push(n)}return c};b.prototype._findGraphicIndex=function(a,d){for(var b=0;b<a.length;b++)for(var c=0,f=a[b].featureIds;c<f.length;c++)if(f[c]===d)return b;return-1};b.prototype._queryGraphicUIDsInExtent=function(a,d,b){if(this._controller){var c=this._controller.crsIndex;D.boundingRectToBoundingRect(a,d,z,c);var f=ca;u.fromRect(f,z);f[2]=-Infinity;f[5]=Infinity;null==this._elevationUpdateNodes&&(this._elevationUpdateNodes=new P({initialSize:10}));
var e=this._elevationUpdateNodes;e.clear();this._controller.updateElevationChanged(f,c,e);for(c=0;c<e.length;c++){var k=this._nodesAddedToStage[e.data[c].id];if(null!=k){if(!k.spatialIndex&&k.bundle.length>=da){for(var q=new Q.PooledRBush(9,N("csp-restrictions")?function(a){return{minX:a.extent[0],minY:a.extent[1],maxX:a.extent[2],maxY:a.extent[3]}}:[".extent[0]",".extent[1]",".extent[2]",".extent[3]"]),m=H.length=0,l=k.bundle;m<l.length;m++){for(var p=l[m],g=J.empty(),h=0,t=p.graphics;h<t.length;h++)f=
t[h],C.expandAABR(f.geometry,g);p.extent=g;H.push(p)}q.load(H);k.spatialIndex=q}if(k.spatialIndex)f=z,D.boundingRectToBoundingRect(a,d,z,this.view.spatialReference),x.minX=f[0],x.minY=f[1],x.maxX=f[2],x.maxY=f[3],k.spatialIndex.search(x,function(a){var c=0;for(a=a.graphics;c<a.length;c++)b(a[c].uid)});else for(q=0,k=k.bundle;q<k.length;q++)for(p=k[q],m=0,p=p.graphics;m<p.length;m++)f=p[m],b(f.uid)}}}};b.prototype.highlight=function(a,d){return this.graphics3d.highlight(a,d,this.layer.objectIdField)};
b.prototype.addNodeData=function(a,d){var b=d.allGeometryData,c=d.attributeDataInfo,f=this._controller.crsIndex;d=this.view.spatialReference;var n=[0,0,0],k=this._getObjectIdField();a.memory=4096;null==this._nodesAddedToStage[a.id]&&(this._nodesAddedToStage[a.id]={bundle:[],attributeData:c?c.attributeData:null,loadedAttributes:c?c.loadedAttributes:null});var q=[];this._nodesAddedToStage[a.id].bundle=q;if(c=this.layer.fullExtent)c=this.layer.fullExtent.clone(),c.xmin-=.5,c.ymin-=.5,c.xmax+=.5,c.ymax+=
.5,c.hasZ&&(c.zmin-=.5,c.zmax+=.5),c.hasM&&(c.mmin-=.5,c.mmax+=.5);for(var m=c,c=[],l=[],h=0;h<b.length;h++){var g=b[h],v=g.featureDataPosition,u=v.length,x=g.geometries||[ea[u]],y=g.featureIds;m&&!R.extentContainsCoords3D(m,v)&&(this._coordinatesOutsideExtentErrors<this._maxCoordinatesOutsideExtentErrors&&E.error("Service Error: Coordinates outside of layer extent"),this._coordinatesOutsideExtentErrors+1===this._maxCoordinatesOutsideExtentErrors&&E.error("Maximum number of errors reached. Further errors are ignored."),
this._coordinatesOutsideExtentErrors++);for(var F=0;F<x.length;F++){var A=x[F];if("points"===A.params.type){var w=[],B=y[F<y.length?F:0],z={};null!=B&&(z[k]=B);B=void 0;"Embedded"===A.type&&(B=A.params.vertexAttributes.position);for(A=0;A<B.length;A+=u){for(var r=0;r<u;r++)n[r]=v[r]+B[A+r];D.bufferToBuffer(n,f,0,G,d,0,1);r=C.makeDehydratedPoint(G[0],G[1],G[2],d);3>u&&(r.z=void 0);w.push({uid:L.generateUID(),geometry:r,attributes:z,visible:!0});a.obb||l.push(r.x,r.y,r.z?r.z:0)}a.memory+=16*B.length;
c.push.apply(c,w);q.push({featureIds:g.featureIds,graphics:w})}}}a.numFeatures=c.length;b=this._nodesAddedToStage[a.id];this._setBundleAttributes(b.bundle,b.loadedAttributes,b.attributeData);0<l.length&&(f=this.view.renderSpatialReference,n=this._controller.crsVertex,D.bufferToBuffer(l,d,0,l,f,0,l.length/3),a.obb=ba.compute({data:l,size:3,offsetIdx:0,strideIdx:3}),D.vectorToVector(a.obb.center,f,a.obb.center,n),this._controller.updateVisibility(a.id));if(!this._controller.isGeometryVisible(a))return this._memCache.put(a.id,
this._nodesAddedToStage[a.id],a.memory),delete this._nodesAddedToStage[a.id],t.resolve();this._verticalScale&&this._verticalScale.adjust(c);this._usedMemory+=a.memory;this.loadedGraphics.addMany(c);this._filterNode(b);return t.resolve()};b.prototype.isNodeLoaded=function(a){return null!=this._nodesAddedToStage[a.id]};b.prototype._removeAllNodeData=function(){var a=this;Object.keys(this._nodesAddedToStage).forEach(function(d){var b=a._nodesAddedToStage[d];b&&a._memCache.put(d,b,a._controller.nodeIndex[d].memory)});
this._nodesAddedToStage={};this._usedMemory=0;this.loadedGraphics.clear()};b.prototype.removeNodeData=function(a){var b=this,e=[];a.forEach(function(a){var c=b._removeNodeStageData(a,e);c&&b._memCache.put(a.id,c,a.memory)});this.loadedGraphics.removeUnorderedMany(e)};b.prototype._removeNodeStageData=function(a,b){var d=this._nodesAddedToStage[a.id];if(!d)return null;for(var c=0,f=d.bundle;c<f.length;c++)b.push.apply(b,f[c].graphics);delete this._nodesAddedToStage[a.id];this._usedMemory-=a.memory;
return d};b.prototype.loadCachedNodeData=function(a,b){return t.resolve(this._memCache.pop(a.id))};b.prototype.addCachedNodeData=function(a,b,e){for(var c=[],d=0,n=b.bundle;d<n.length;d++)c.push.apply(c,n[d].graphics);this._nodesAddedToStage[a.id]=b;this.setAttributeData(a,e.loadedAttributes,e.attributeData);this._usedMemory+=a.memory;this.loadedGraphics.addMany(c);this._filterNode(b);return t.resolve()};b.prototype.getLoadedNodeIDs=function(){return Object.keys(this._nodesAddedToStage)};b.prototype.getLoadedAttributes=
function(a){if(a=this._nodesAddedToStage[a.id])return a.loadedAttributes};b.prototype.getAttributeData=function(a){if(a=this._nodesAddedToStage[a.id])return a.attributeData};b.prototype.setAttributeData=function(a,b,e){if(a=this._nodesAddedToStage[a.id])a.loadedAttributes=b,a.attributeData=e,this._setBundleAttributes(a.bundle,b,e),this._filterNode(a),this.graphics3d.graphicsCore.labelsEnabled&&(b=a.bundle.map(function(a){return a.graphics.length&&a.graphics[0].uid}),this.graphics3d.graphicsCore.updateLabelingInfo(b))};
b.prototype._setBundleAttributes=function(a,b,e){for(var c=0;c<a.length;c++)for(var d=0,n=a[c].graphics;d<n.length;d++){var k=n[d];k.attributes||(k.attributes={});if(b)for(var g=0,h=b;g<h.length;g++){var l=h[g].name;e[l]&&(k.attributes[l]=w.getCachedAttributeValue(e[l],c))}}};b.prototype._updateClippingExtent=function(a){this._controller&&this._controller.updateClippingArea(a);return!1};b.prototype._getObjectIdField=function(){return this.layer.objectIdField||"OBJECTID"};b.prototype._rendererChange=
function(a,b){var d=a?a.requiredFields:[],c=b?b.requiredFields:[];d.length===c.length&&d.every(function(a,b){return d[b]===c[b]})||this._reloadAllNodes()};b.prototype._rangeInfosChanged=function(a){null!=a&&0<a.length&&E.warn("Unsupported property: rangeInfos are currently only serialized to and from web scenes but do not affect rendering.")};b.prototype._objectIdFilterChange=function(){var a=this;Object.keys(this._nodesAddedToStage).forEach(function(b){return a._filterNode(a._nodesAddedToStage[b])})};
b.prototype._reloadAllNodes=function(){this._removeAllNodeData();this._controller&&this._controller.restartNodeLoading()};b.prototype._definitionExpressionChange=function(){this._definitionExpressionErrors=0};b.prototype._evaluateClause=function(a,b){try{return!!a.calculateValue(b)}catch(e){return this._definitionExpressionErrors<this._maxDefinitionExpressionErrors&&E.error("Error while evaluating definitionExpression: "+e),this._definitionExpressionErrors++,this._definitionExpressionErrors===this._maxDefinitionExpressionErrors&&
E.error("Further errors are ignored"),!1}};b.prototype._filterNode=function(a){var b=this._getObjectIdField(),e=null;if(this.layer.objectIdFilter)var c=this.layer.objectIdFilter.ids,f="include"===this.layer.objectIdFilter.method,e=function(a){return 0<=c.indexOf(a)===f};var g=this._controller.parsedDefinitionExpression,k=0;for(a=a.bundle;k<a.length;k++)for(var h=0,m=a[k].graphics;h<m.length;h++){var l=m[h],p=l.visible;e&&!e(l.attributes[b])?l.visible=!1:l.visible=g?this._evaluateClause(g,l):!0;p!==
l.visible&&(y.graphic=l,y.property="visible",y.oldValue=p,y.newValue=l.visible,this.layer.graphicChanged(y))}};b.prototype.queryExtent=function(a){return this._ensureQueryEngine().queryExtent(a)};b.prototype.queryFeatureCount=function(a){return this._ensureQueryEngine().queryFeatureCount(a)};b.prototype.queryFeatures=function(a){return this._ensureQueryEngine().queryFeatures(a)};b.prototype.queryObjectIds=function(a){return this._ensureQueryEngine().queryObjectIds(a)};b.prototype._ensureQueryEngine=
function(){this._queryEngine||(this._queryEngine=this._createQueryEngine());return this._queryEngine};b.prototype._createQueryEngine=function(){var a=this,b={id:0,index:0,graphic:null},e=this;return new X(this.layer,{forAll:function(c,d){a._forAllFeatures(function(a,d,f){b.id=a;b.index=d;b.graphic=f;c(b)},d)},createGraphic:function(a){return C.hydrateGraphic(a.graphic,e.layer)},requestFields:function(b,d,e){return w.whenGraphicAttributes(a.layer,d,a._getObjectIdField(),e,function(){var c=a._getGraphicIndices(b.nodeId,
d);return{node:a._controller.nodeIndex[b.nodeId],indices:c}},{ignoreUnavailableFields:!1})},createExtentBuilder:function(){var b=u.empty(),d=a.layer.spatialReference;return{add:function(a){return C.expandAABB(a.graphic.geometry,b)},getExtent:function(){return u.toExtent(b,d)}}}},{enableObjectId:!0,enableOutFields:!!this.layer.objectIdField})};b.prototype.getUsedMemory=function(){var a=this._usedMemory;this._controller&&(a+=512*Object.keys(this._controller.nodeIndex).length);return a};b.prototype.getUnloadedMemory=
function(){return this._controller?this._controller.getUnloadedMemoryEstimate():0};b.prototype.getStats=function(){var a=this.inherited(arguments)||{};a.index=this._controller?Object.keys(this._controller.nodeIndex).length:0;a.nodes=Object.keys(this._nodesAddedToStage).length;a.features=this.loadedGraphics.length;this._controller&&this._controller.updateStats(a);return a};h([g.property()],b.prototype,"graphics3d",void 0);h([g.property()],b.prototype,"drawingOrder",void 0);h([g.property({aliasOf:"graphics3d.graphicsCore.hasDraped"})],
b.prototype,"hasDraped",void 0);h([g.property({type:Boolean})],b.prototype,"overlayUpdating",void 0);h([g.property({type:Boolean})],b.prototype,"supportsDraping",void 0);h([g.property()],b.prototype,"loadedGraphics",void 0);h([g.property()],b.prototype,"layer",void 0);h([g.property()],b.prototype,"_controller",void 0);h([g.property({dependsOn:["_controller.updating","graphics3d.updating","overlayUpdating"]})],b.prototype,"updating",void 0);h([g.property({dependsOn:["_controller.rootNodeVisible"]})],
b.prototype,"suspended",void 0);h([g.property(Y.updatingPercentage)],b.prototype,"updatingPercentage",void 0);h([g.property({aliasOf:"_controller.updatingPercentage"})],b.prototype,"updatingPercentageValue",void 0);h([g.property({dependsOn:["suspended","_controller.leafsReached"]})],b.prototype,"displayLimitExceeded",null);return b=h([g.subclass("esri.views.3d.layers.SceneLayerGraphicsView3D")],b)}(g.declared(U));var ea={2:{type:"Embedded",params:{type:"points",vertexAttributes:{position:[0,0]}}},
3:{type:"Embedded",params:{type:"points",vertexAttributes:{position:[0,0,0]}}}},da=100,z=J.create(),ca=u.create(u.POSITIVE_INFINITY),x={minX:0,minY:0,maxX:0,maxY:0},G=Z.vec3d.create(),H=[],y={graphic:null,property:null,oldValue:null,newValue:null};return v});