// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper dojo/on ../../../Graphic ../../../core/Accessor ../../../core/Handles ../../../core/Logger ../../../core/accessorSupport/decorators ../../../geometry/Point ../../../geometry/support/aaBoundingRect ../../../symbols/SimpleMarkerSymbol ../lib/gl-matrix ../state/utils/viewUtils ../support/debugFlags ../support/debugFlags ../support/earthUtils ../support/mathUtils ../support/projectionUtils ../webgl-engine/lib/Selector".split(" "),
function(T,U,C,t,D,E,F,G,H,r,I,l,J,g,K,L,M,N,q,u,O){var P=[[-.1,-2,3.9,2],[-.1,-3.9,3.9,.1],[-2,-3.9,2,.1],[-3.9,-3.9,.1,.1],[-3.9,-2,.1,2],[-3.9,-.1,.1,3.9],[-2,-.1,2,3.9],[-.1,-.1,3.9,3.9]],Q=H.getLogger("esri.views.3d.OverlayManager"),v,y=function(w){function f(){var a=null!==w&&w.apply(this,arguments)||this;a._handles=new G;a._overlaySR=null;a._renderSR=null;a._overlaySREqualsRenderSR=!0;a._connectedLayers={};a._scale=0;a._dirty=!1;a._isSpherical=!1;a._latestOriginId=0;a.opacity=0;return a}C(f,
w);Object.defineProperty(f.prototype,"hasHighlights",{get:function(){return this._renderer.hasHighlights},enumerable:!0,configurable:!0});f.prototype.initialize=function(){var a=this;this._stage=this.view._stage;this._renderer=this._stage.getDrapedTextureRenderer();this._renderer.onHasHighlightsChanged=function(){return a.onHasHighlightsChanged()};this._renderer.onContentChanged=function(){return a.setOverlayDirty()};this._renderer.forceUpdate=function(b){return a.updateOverlays(b)};this.groundSelector=
new O(this.view.viewingMode);this.groundSelector.enableBackfacesTerrain=!0;this.groundSelector.enableInvisibleTerrain=!0;this.groundSelector.enableHUDSelection=!1;this._handles.add(this.view.watch(["pointsOfInterest.renderPointOfView","pointsOfInterest.centerOnSurfaceFrequent.location"],function(){return a.setOverlayDirty()}));this._handles.add(this.view.on("resize",function(){return a.setOverlayDirty()}))};f.prototype.destroy=function(){for(var a in this._connectedLayers)this.unregisterLayerView(this._connectedLayers[a].layerView);
this._disposeOverlays();this._handles&&(this._handles.destroy(),this._handles=null)};f.prototype.onHasHighlightsChanged=function(){this.setOverlayDirty();this.notifyChange("hasHighlights")};f.prototype.hasOverlays=function(){return!!this._overlays};f.prototype.setSpatialReference=function(a,b){(this._overlaySR=a)?(this._renderSR=this.view.renderSpatialReference,this._overlaySREqualsRenderSR=this._overlaySR.equals(this._renderSR),this._longitudeCyclical=(this._isSpherical=b)?a.isWebMercator?new q.Cyclical(-2.0037508342788905E7,
2.0037508342788905E7):new q.Cyclical(-180,180):null):(this._disposeOverlays(),this._longitudeCyclical=null)};f.prototype.registerLayerView=function(a){var b=this,c=a.layer.uid;if(this._connectedLayers[c])Q.warn("[OverlayManager#registerLayerView]: Layer "+c+" is already connected");else{var e=D(a,"draped-data-change",function(){return b.setOverlayDirty()});this._connectedLayers[c]={eventHandles:[e],layerView:a};a.setDrapingExtent&&this._overlays&&[this._overlays.inner,this._overlays.outer].forEach(function(c,
e){a.setDrapingExtent(e,c.extent,b._overlaySR,c.resolution,c.renderLocalOrigin)});this.setOverlayDirty();this._setLayerViewOverlayUpdating(a,this._dirty)}};f.prototype.unregisterLayerView=function(a){for(var b in this._connectedLayers){var c=this._connectedLayers[b];if(c.layerView===a){if(c.eventHandles)for(var e=0;e<c.eventHandles.length;e++)c.eventHandles[e].remove();delete this._connectedLayers[b];this.setOverlayDirty();a.destroyed||(a.overlayUpdating=!1)}}};f.prototype.setOverlayDirty=function(){this._dirty||
(this._setOverlayUpdating(!0),this._dirty=!0)};f.prototype._setLayerViewOverlayUpdating=function(a,b){if(!b||!a.suspended&&a.hasDraped)a.overlayUpdating=b};f.prototype._setOverlayUpdating=function(a){for(var b in this._connectedLayers)this._setLayerViewOverlayUpdating(this._connectedLayers[b].layerView,a);if(b=this.view.graphicsView)b.overlayUpdating=a};f.prototype.updateOverlays=function(a){void 0===a&&(a=this.view.state.camera);if(this._overlaySR){var b;b=Math.max(a.fullWidth,a.fullHeight);b=q.nextHighestPowerOfTwo(b+
256);b=Math.min(b,2048);this._computeOverlayExtents(a,b,x);this._overlays||this._initOverlays();this._updateOverlay(this._overlays.inner,0,x.inner,b);this._updateOverlay(this._overlays.outer,1,x.outer,b);this.opacity=1;this._setOverlayUpdating(!1);this._drawOverlays();this.terrainSurface._updateTileOverlayParams();this._dirty=!1}};f.prototype._updateOverlay=function(a,b,c,e){var d;a:{d=a.extent;for(var f=L.TESTS_DISABLE_UPDATE_THROTTLE_THRESHOLDS?0:y.EXTENTS_DIFFER_THRESHOLD*Math.max(c[2]-c[0],c[3]-
c[1],d[2]-d[0],d[3]-d[1]),m=0;4>m;m++)if(Math.abs(d[m]-c[m])>f){d=!0;break a}d=!1}if(d||e!==a.resolution){l.set(a.extent,c);a.resolution=e;a.renderLocalOrigin={id:"OV_"+this._latestOriginId++,vec3:l.center(a.extent,g.vec3d.create())};for(var k in this._connectedLayers)d=this._connectedLayers[k].layerView,d.setDrapingExtent&&d.setDrapingExtent(b,c,this._overlaySR,e,a.renderLocalOrigin)}};f.prototype.overlaysNeedUpdate=function(){return this._dirty&&!!this._overlaySR};f.prototype.updateOpacity=function(a){var b=
1;if(this._overlays){var c=this._scale;3.5*a<c&&(b=Math.sqrt(q.clamp((a-c/10)/(c/3.5-c/10),0,1)))}return b};f.prototype.setOverlayParamsOfTile=function(a,b,c){var e=this._overlays.inner,d=this._overlays.outer;a=l.intersection(a.extent,a.parentSurface.extent,z);this._rectInsideRect(a,e.extent)?(this._setTileOverlayData(a,e,b.overlays[0]),this._invalidateTileOverlayData(b.overlays[1])):this._rectanglesOverlap(a,e.extent)?(this._setTileOverlayData(a,e,b.overlays[0]),this._setTileOverlayData(a,d,b.overlays[1])):
(this._rectanglesOverlap(a,d.extent)?this._setTileOverlayData(a,d,b.overlays[0]):this._invalidateTileOverlayData(b.overlays[0]),this._invalidateTileOverlayData(b.overlays[1]));b.overlayOpacity=void 0!==c?c:1};f.prototype._setTileOverlayData=function(a,b,c){var e=b.extent;c.texScale[0]=(a[2]-a[0])/(e[2]-e[0]);c.texScale[1]=(a[3]-a[1])/(e[3]-e[1]);var d=a[0];if(this._longitudeCyclical){var d=this._longitudeCyclical.minimalMonotonic(e[0],d),f=this._longitudeCyclical.minimalMonotonic(e[0],a[2]);d>f&&
(d=f-(a[2]-a[0]))}c.texOffset[0]=(d-e[0])/(e[2]-e[0]);c.texOffset[1]=(a[1]-e[1])/(e[3]-e[1]);c.renderTargetId=b.valid?b.renderTargetId:null;c.highlightRenderTargetId=b.highlightValid?b.highlightRenderTargetId:null};f.prototype._invalidateTileOverlayData=function(a){a.renderTargetId=null;a.highlightRenderTargetId=null};f.prototype.overlayPixelSizeInMapUnits=function(a){var b;this._overlays&&(b=this._pointIsInExtent(a,this._overlays.inner.extent)?this._overlays.inner:this._overlays.outer);return b?
(b.extent[2]-b.extent[0])/b.resolution:0};f.prototype._createEmptyOverlay=function(a){var b=this._renderer.createRenderTarget("overlay"+a);a=this._renderer.createHighlightRenderTarget("overlayHighlight"+a);return{extent:l.create(),resolution:0,renderTargetId:b,valid:!1,highlightRenderTargetId:a,highlightValid:!1,renderLocalOrigin:{id:"O",vec3:[0,0,0]}}};f.prototype._initOverlays=function(){this._overlays={inner:this._createEmptyOverlay(0),outer:this._createEmptyOverlay(1)}};f.prototype._disposeOverlays=
function(){this._overlays&&(this._renderer.disposeRenderTarget(this._overlays.inner.renderTargetId),this._renderer.disposeRenderTarget(this._overlays.inner.highlightRenderTargetId),this._renderer.disposeRenderTarget(this._overlays.outer.renderTargetId),this._renderer.disposeRenderTarget(this._overlays.outer.highlightRenderTargetId),this._overlays=null)};f.prototype._intersectGroundFromView=function(a,b,c,e){var d=g.vec3d.createFrom(b*a.fullWidth,c*a.fullHeight,1);g.vec3d.unproject(d,a.viewMatrix,
a.projectionMatrix,a.fullViewport,d);b=g.vec3d.createFrom(b*a.fullWidth,c*a.fullHeight,0);g.vec3d.unproject(b,a.viewMatrix,a.projectionMatrix,a.fullViewport,b);this.groundSelector.init([],b,d,null,a,null,!1);this.view.basemapTerrain.intersect(this.groundSelector,b,d);return this.groundSelector.minResult.getIntersectionPoint(e)};f.prototype._findHorizonBasedPointOfInterest=function(a,b,c){var e=.5;if("global"===this.view.viewingMode){e=g.vec3d.create(a.eye);g.vec3d.normalize(e);g.vec3d.negate(e);b=
g.vec3d.length(b);b=Math.asin(b/g.vec3d.length(a.eye));var d=Math.acos(g.vec3d.dot(a.viewForward,e)),e=q.clamp((b-(d-.5*a.fovY))/a.fovY,0,1);b=q.clamp((-b-(d-.5*a.fovY))/a.fovY,0,1);e=1===e&&0===b?.5:b+.55*(e-b)}else e=g.mat4d.multiplyVec4(a.projectionMatrix,g.vec4d.createFrom(0,Math.tan(.5*Math.PI-Math.acos(-a.viewForward[2])),1,0))[1],e=q.clamp(.5+.5*e,0,1),e=1===e||0===e?.5:0<a.eye[2]?.55*e:1-.55*(1-e);return this._intersectGroundFromView(a,.5,e,c)?!0:!1};f.prototype._computeOverlayExtents=function(a,
b,c){var e=this.terrainSurface.extent,d=g.vec3d.create(),f=this.view.pointsOfInterest.centerOnSurfaceFrequent.renderLocation;this._findHorizonBasedPointOfInterest(a,this.view.pointsOfInterest.centerOnSurfaceFrequent.renderLocation,d)||g.vec3d.set(f,d);this._scale=this.view.renderCoordsHelper.getAltitude(a.eye);var m=g.vec3d.dist(a.eye,d),f=K.viewAngle(this.view.renderCoordsHelper,f,a.eye),f=Math.PI/2-Math.abs(f-Math.PI/2);if(M.OVERLAY_SHOW_CENTER){var k=new J({color:[255,0,0],outline:{color:[255,
255,255],width:2}}),h=new I;u.vectorToPoint(d,this._renderSR,h,this._overlaySR);k=new E({geometry:h,symbol:k});void 0!==v&&this.view.graphics.remove(v);this.view.graphics.add(k);v=k}this._overlaySREqualsRenderSR||u.vectorToVector(d,this._renderSR,d,this._overlaySR);b=.5*b*a.perPixelRatio*m*2;h=!1;m=Infinity;this._isSpherical&&(this._overlaySR.isWebMercator?(b/=Math.cos(u.webMercator.y2lat(d[1])),m=this.terrainSurface.extent[3],m*=.999):(h=!0,b/=N.metersPerDegree,m=90),b>=m&&(b=m,d[1]=0,this._overlaySR.isWebMercator&&
(d[0]=0)));k=1;h&&(k=1/Math.max(.2,Math.cos(Math.abs(q.deg2rad(d[1])))),180<b*k&&(k=180/b));var n=b*k,h=c.inner;h[0]=d[0]-n;h[1]=d[1]-b;h[2]=d[0]+n;h[3]=d[1]+b;this._isSpherical&&this._shiftExtentToFitBounds(h,Infinity,m);c=c.outer;l.set(c,h);6*n>e[2]-e[0]?l.set(c,e):f<=.25*Math.PI?(c[0]-=n,c[1]-=b,c[2]+=n,c[3]+=b):(u.vectorToVector(a.eye,this._renderSR,A,this._overlaySR),g.vec2d.subtract(d,A,p),a=-Math.atan2(p[1],p[0])+.125*Math.PI,0>a&&(a+=2*Math.PI),g.vec4d.scale(P[Math.floor(a/(.25*Math.PI))],
2*b,p),p[0]*=k,p[2]*=k,g.vec4d.add(c,p,c));this._isSpherical&&(c[0]=this._longitudeCyclical.clamp(c[0]),c[2]=this._longitudeCyclical.clamp(c[2]),c[1]=Math.max(c[1],-m),c[3]=Math.min(c[3],m));!this._isSpherical&&e&&(a=l.intersection(h,e,z),e=l.intersection(c,e,R),l.contains(a,e)&&(c[2]=c[0],c[3]=c[1]))};f.prototype._drawOverlays=function(){var a=this._overlays.inner.extent[2]-this._overlays.inner.extent[0];this._drawOverlay(this._overlays.inner,0,a);this._drawOverlay(this._overlays.outer,1,a)};f.prototype._drawOverlay=
function(a,b,c){var e=this._renderer,d=a.extent,f=a.resolution,m=this._longitudeCyclical?d[2]>this._longitudeCyclical.max:!1,k=this._longitudeCyclical?d[0]<this._longitudeCyclical.min:!1;if(m||k){n.views=S;var k=void 0,k=m?this._longitudeCyclical.max-d[0]:this._longitudeCyclical.min-d[0],k=Math.round(k/(d[2]-d[0])*f),h=n.views[0];g.vec4d.set4(0,0,k,f,h.viewport);g.vec4d.set4(d[0],d[1],this._longitudeCyclical.max,d[3],h.extent);m||(h.extent[0]+=this._longitudeCyclical.range);h=n.views[1];g.vec4d.set4(k,
0,f-k,f,h.viewport);g.vec4d.set4(this._longitudeCyclical.min,d[1],d[2],d[3],h.extent);m&&(h.extent[2]-=this._longitudeCyclical.range)}else n.views=B,l.set(n.views[0].extent,d),g.vec4d.set4(0,0,f,f,n.views[0].viewport);n.width=f;n.height=f;n.pixelRatio=c/(d[2]-d[0]);n.index=b;a.valid=e.draw(a.renderTargetId,n);a.highlightValid=e.drawHighlights(a.highlightRenderTargetId,n)};f.prototype._rectanglesOverlap=function(a,b){return this._longitudeCyclical?(this._longitudeCyclical.contains(b[0],b[2],a[0])||
this._longitudeCyclical.contains(b[0],b[2],a[2])||this._longitudeCyclical.contains(a[0],a[2],b[0]))&&!(a[1]>b[3]||a[3]<b[1]):l.intersects(a,b)};f.prototype._rectInsideRect=function(a,b){return this._longitudeCyclical?this._longitudeCyclical.contains(b[0],b[2],a[0])&&this._longitudeCyclical.contains(b[0],b[2],a[2])&&a[1]>b[1]&&a[3]<b[3]:l.contains(b,a)};f.prototype._pointIsInExtent=function(a,b){if(this._longitudeCyclical)return this._longitudeCyclical.contains(b[0],b[2],a.x)&&a.y>=b[1]&&a.y<=b[3];
var c=a.x;a=a.y;return c>b[0]&&c<b[2]&&a>b[1]&&a<b[3]};f.prototype._shiftExtentToFitBounds=function(a,b,c){var e=0,d=0;a[0]<-b?e=a[0]+b:a[2]>b&&(e=b-a[2]);a[1]<-c?d=a[1]+c:a[3]>c&&(d=c-a[3]);l.offset(a,e,d)};f.EXTENTS_DIFFER_THRESHOLD=1E-5;t([r.property()],f.prototype,"view",void 0);t([r.property()],f.prototype,"terrainSurface",void 0);t([r.property({type:Boolean})],f.prototype,"hasHighlights",null);return f=t([r.subclass("esri.views.3d.terrain.OverlayManager")],f)}(r.declared(F)),n={width:0,height:0,
pixelRatio:0,views:null,index:0},B=[{viewport:l.create(),extent:l.create()}],S=[B[0],{viewport:l.create(),extent:l.create()}],p=g.vec4d.create(),A=g.vec3d.create(),x={inner:l.create(),outer:l.create()},z=l.create(),R=l.create();return y});