// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/extendsHelper ../../../Color ../../../core/ObjectPool ../../../core/PooledArray ../../../core/promiseUtils ../../../geometry/support/aaBoundingBox ../lib/gl-matrix ../support/imageUtils ./ResourceCounter ./TerrainConst ./TileGeometryFactory ./TileRenderData ./TileRenderer ./tileUtils ../webgl-engine/lib/DefaultVertexAttributeLocations ../webgl-engine/lib/DefaultVertexBufferLayouts ../webgl-engine/lib/glUtil3D ../webgl-engine/lib/RenderPass ../webgl-engine/lib/RenderSlot ../webgl-engine/lib/screenSizePerspectiveUtils ../webgl-engine/lib/tracer ../webgl-engine/lib/Util ../webgl-engine/materials/internal/MaterialUtil ../webgl-engine/shaders/TerrainRendererPrograms ../../webgl/BufferObject ../../webgl/Util ../../webgl/VertexArrayObject".split(" "),
function(I,pa,qa,U,J,B,C,D,k,V,W,K,X,Y,Z,w,aa,ba,ca,m,L,da,E,ea,x,n,M,N,fa){function O(b){return function(a,c){a=a.screenDepth;c=c.screenDepth;return a<c?-b:a>c?b:0}}function ga(b){var a=O(b);return function(c,e){return 0===c.tiles.length?-b:0===e.tiles.length?b:a(c.tiles.data[0],e.tiles.data[0])}}var ha=ea.assert,ia=k.mat4d.identity(),P=L.OPAQUE_TERRAIN,Q=L.TRANSPARENT_TERRAIN,R=k.vec3d.create(),F=k.vec2d.create(),G=D.create(),z=k.vec4d.create(),A=k.vec4d.create(),S=k.vec4d.create(),ja=function(){return function(){this.extent=
k.vec4d.create();this.maxLevel=this.minLevel=0;this.callback=null}}();I=function(){function b(a,c){this.initialized=!1;this.rctx=null;this.renderDataPool=new J(Y.TileRenderData);this.perOriginTileData=new B({initialSize:10,allocator:function(){return{root:null,origin:null,tiles:new B({initialSize:300})}}});this.perOriginTileDataDirty=!0;this.tileIterator=new w.IteratorPreorder;this.highestVisibleLODTile=null;this.visible=!0;this.debugScreenSizePerspective=!1;this.wireframe=x.copyParameters(ka);this._opaque=
!0;this._skirtScale=1;this._cullBackFaces=this._disableRendering=this._drawBorders=!1;this._renderOrder=1;this._velvetOverground=!0;this._hasOverlays=!1;this.castShadows=!0;this.receiveShadows=!1;this.backgroundPromise=this.tileRenderer=this.emptyTex=null;this.tileBackgroundInitialized=!1;this.stencilEnabledLayerExtents=[];this.numOriginsRendered=this.numTilesCulled=this.numTilesRendered=this.numTrianglesRendered=0;this.resourceCounter=new W;this.loaded=this.clippingExtent=null;this._loaded=!1;this.needsRender=
!0;this.needsHighlight=this.didRender=!1;this.visibleScaleRangeQueries=new B({initialSize:10});this.visibleScaleRangeQueriesInvPtr=0;this.visibleScaleRangeQueryQueue=new B({initialSize:30});this.visibleScaleRangeQueryPool=new J(ja,!1);this.manifold=a;this.tileSize=c||256}b.prototype.destroy=function(a){this.uninstall(a);this.backgroundPromise&&(this.backgroundPromise.cancel(),this.backgroundPromise=null)};b.prototype.install=function(a){a.addRenderPlugin([P,Q],this);this.drapedRenderer=a.getDrapedTextureRenderer()};
b.prototype.uninstall=function(a){a.removeRenderPlugin(this)};Object.defineProperty(b.prototype,"disableRendering",{set:function(a){this._disableRendering=!!a;this.setNeedsRender()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"opaque",{set:function(a){this._opaque=a;this.setNeedsRender()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"skirtScale",{set:function(a){this._skirtScale=a;this.setNeedsRender()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"drawBorders",{set:function(a){this._drawBorders!==a&&(this._drawBorders=a,this._updatePrograms())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"cullBackFaces",{set:function(a){this._cullBackFaces=a;this.setNeedsRender()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"renderOrder",{set:function(a){this._renderOrder=a;this.setNeedsRender()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"velvetOverground",{set:function(a){this._velvetOverground!==
a&&(this._velvetOverground=a,this._updatePrograms())},enumerable:!0,configurable:!0});b.prototype.setRootTiles=function(a){this.rootTiles=a;this.setNeedsRender()};b.prototype.setNeedsHighlight=function(a){this.needsHighlight=a;this.setNeedsRender()};b.prototype.setStencilEnabledLayerExtents=function(a){this.stencilEnabledLayerExtents=a;this.setNeedsRender()};b.prototype.setTileSize=function(a){this.tileSize=a;this.tileRenderer&&(this.tileRenderer.tileSize=a);this.setNeedsRender()};b.prototype.loadTile=
function(a){ha(null===a.renderData);a.renderData=this.renderDataPool.acquire();a.renderData.init();var c=this.getLocalOriginOfTile(a);a.createGeometry(a.renderData.updateGeometryState(a),c,"debug"===this.wireframe.mode);a.renderData.localOrigin=c;this._updateTileGeometryBuffers(a);this.tileBackgroundInitialized&&this.tileRenderer.updateTileTexture(a)};b.prototype.queryVisibleLevelRange=function(a,c,e,d){var f=this.visibleScaleRangeQueryPool.acquire();k.vec4d.set(a,f.extent);f.minLevel=c?c:-Number.MAX_VALUE;
f.maxLevel=null!=e?e:Number.MAX_VALUE;f.callback=d;this.visibleScaleRangeQueryQueue.push(f);this.setNeedsRender()};b.prototype.updateTileTexture=function(a){this.tileRenderer&&this.tileBackgroundInitialized&&this.tileRenderer.updateTileTexture(a)};b.prototype.updateTileGeometry=function(a){a.renderData.updateGeometryState(a);for(var c=a.renderData.geometryState,e=a.layerInfo[K.LayerClass.ELEVATION],d=0;d<e.length;d++)e[d].pendingUpdates&=~K.TileUpdateTypes.UPDATE_GEOMETRY;return c.needsUpdate?(a.renderData.vao&&
this._releaseTileGeometry(a),a.createGeometry(c,a.renderData.localOrigin,"debug"===this.wireframe.mode),this._updateTileGeometryBuffers(a),!0):!1};b.prototype.unloadTile=function(a){this._releaseTileGeometry(a);a.renderData.texture&&a.renderData.texture.dispose();this.renderDataPool.release(a.renderData);a.renderData=null;a.updateMemoryUsed()};b.prototype.getLocalOriginOfTile=function(a){if(10<=a.lij[0]){for(;7<a.lij[0];)a=a.parent;return a.centerAtSeaLevel}if("spherical"===this.manifold)return R;
for(;a.parent;)a=a.parent;return a.centerAtSeaLevel};b.prototype.setVisibility=function(a){this.visible=a;this.setNeedsRender()};b.prototype.getStats=function(){return{numTilesRendered:this.numTilesRendered,numTilesCulled:this.numTilesCulled,numTrianglesRendered:this.numTrianglesRendered,numOriginsRendered:this.numOriginsRendered}};b.prototype.getWireframeEnabled=function(){return"shader"===this.wireframe.mode};b.prototype.setDebugScreenSizePerspective=function(a){a!==this.debugScreenSizePerspective&&
(this.debugScreenSizePerspective=a,this._updatePrograms())};b.prototype.setWireframe=function(a){var c=this;if(!1===a||!0===a)a={mode:a?"shader":"none"};var e=this.wireframe;if(void 0!==a.mode&&e.mode!==a.mode){var d="debug"===e.mode,f="debug"===a.mode;e.mode=a.mode;this._updatePrograms();d!==f&&this.rootTiles&&w.traverseTilesPreorder(this.rootTiles,function(a){a.renderData&&(a.renderData.vao&&c._releaseTileGeometry(a),a.createGeometry(a.renderData.updateGeometryState(a),a.renderData.localOrigin,
f),c._updateTileGeometryBuffers(a))})}for(var b in a)e.hasOwnProperty(b)&&(e[b]=a[b]),this.setNeedsRender();e.resolution&&(e.resolution=Math.min(e.resolution,this.tileSize),e.resolution=1<<Math.round(Math.log(e.resolution)/Math.LN2))};b.prototype.setNeedsRender=function(){this.needsRender=!0;this.didRender=!1;this.perOriginTileDataDirty=!0};b.prototype.resetNeedsRender=function(){this.didRender&&(this.needsRender=0!==this.visibleScaleRangeQueryQueue.length,this.didRender=!1)};b.prototype.isOpaque=
function(){var a=this.wireframe,a="shader"===a.mode&&(1>a.wireOpacity||1>a.surfaceOpacity);return this._opaque&&!a};b.prototype.updateTileBackground=function(a){this.backgroundPromise&&this.backgroundPromise.cancel();this.backgroundPromise="string"===typeof a?V.requestImage(a).catch(function(){return null}):null!=a?C.resolve(U.toUnitRGBA(a)):C.resolve(null);this._renderTileBackground()};b.prototype.initializeRenderContext=function(a){var c=this,e=this.rctx=a.rctx;a=this.programRep=a.programRep;var d=
function(a){C.when(a).then(function(){c.initialized=!0;c.setNeedsRender()}).catch(d)};d(this._renderTileBackground());this.programs={color:null,normal:null,depth:null,depthShadowMap:null,highlight:null};this._updatePrograms();this.tileRenderer=new Z(e,this.tileSize,a,this.resourceCounter,this.setNeedsRender.bind(this));this._renderTileBackground();this.emptyTex=ca.createEmptyTexture(e)};b.prototype.uninitializeRenderContext=function(a){null!=this.emptyTex&&(this.emptyTex.dispose(),this.emptyTex=null);
this.tileRenderer&&(this.tileRenderer.dispose(),this.tileRenderer=null)};b.prototype.render=function(a){var c=a.rctx,e=c.gl;if(!this.initialized||this._disableRendering||!this.visible||!this.rootTiles||!this.tileBackgroundInitialized)return!1;var d=this.isOpaque()?P:Q;if(a.slot!==d)return!1;E.trace("# BEGIN RENDER TERRAIN");d=a.pass;c.setFaceCullingEnabled(this._cullBackFaces);var f=1===a.lightingData.helper.globalFactor;d===m.MATERIAL?this._renderMaterialPass(a,this._updatePerOriginTileData()):d===
m.MATERIAL_DEPTH_SHADOWMAP&&this.castShadows&&f?this._renderDepthPass(a,this.programs.depthShadowMap,this._updatePerOriginTileData()):d===m.MATERIAL_DEPTH?this._renderDepthPass(a,this.programs.depth,this._updatePerOriginTileData()):d===m.MATERIAL_NORMAL?this._renderNormalPass(a,this._updatePerOriginTileData()):d===m.MATERIAL_HIGHLIGHT&&this.needsHighlight&&(this._renderHighlightPass(a,this._updatePerOriginTileData()),c.clear(e.DEPTH_BUFFER_BIT));this._cullBackFaces&&c.setFaceCullingEnabled(!1);E.trace("# END RENDER TERRAIN");
return!0};b.prototype.intersect=function(a,c,e,d){if(this.rootTiles&&(!a.isSelection||this.isOpaque())&&a.enableTerrain){var f=la,b=ma;k.vec3d.subtract(e,c,f);k.vec3d.set3(1/f[0],1/f[1],1/f[2],b);var g=a.minResult,p=a.maxResult,T=this.clippingExtent,r=this.tileIterator;r.reset(this.rootTiles);d=function(){var d=r.next();if(null===d.renderData)return"continue";if(a.enableInvisibleTerrain){if(!d.visible&&T&&!d.intersectsExtent(T))return"continue"}else if(!d.visible)return"continue";var h=d.renderData.geometryInfo,
l=d.renderData.localOrigin,t=na;k.vec3d.subtract(c,l,t);var q=-v._skirtScale*h.skirtLength;if(0!==q){var y=d.tileUp;D.offset(h.boundingBox,q*y[0],q*y[1],q*y[2],G);D.expandWithBuffer(G,h.boundingBox,0,2)}if(!x.intersectAabbInvDir(0!==q?G:h.boundingBox,t,b,a.tolerance))return"continue";var y=function(c,e,b){if(0<=c&&(a.enableBackfacesTerrain||0>k.vec3d.dot(e,f))){b=void 0;if(void 0===g.dist||c<g.dist)b=w.tile2str(d),g.set(void 0,b,c,e,void 0),g.setIntersector("TerrainRenderer");if(void 0===p.dist||
c>p.dist)b=w.tile2str(d),p.set(void 0,b,c,e,void 0),p.setIntersector("TerrainRenderer")}},m=oa;k.vec3d.subtract(e,l,m);var l=h.indices,n={data:h.vertexAttributes,size:3,offsetIdx:0,strideIdx:5},h=h.numWithoutSkirtIndices/3;x.intersectTriangles(t,m,0,h,l,n,null,y);0!==q&&w.intersectSkirts(t,m,h,l.length/3,l,n,null,"spherical"===v.manifold?function(a){return k.vec3d.scale(a,q/k.vec3d.length(a))}:function(a){return k.vec3d.set3(0,0,q,a)},y)};for(var v=this;!r.done;)d()}};b.prototype._renderTileBackground=
function(){var a=this;if(this.rctx&&this.backgroundPromise&&this.tileRenderer)return this.backgroundPromise.then(function(c){a.tileRenderer&&(a.tileBackgroundInitialized=!0,a.tileRenderer.setBackground(c),a.rootTiles&&w.traverseTilesPreorder(a.rootTiles,function(c){a.tileRenderer.updateTileTexture(c)}))})};b.prototype._updatePrograms=function(){var a="spherical"===this.manifold,c=a?"global":"local",e="shader"===this.wireframe.mode,d=this.programRep;this.programs.color=d.getProgram(n.colorPass,{viewingMode:c,
mode:e||this._drawBorders?"wireframe":"normal",spherical:a,overlay:this._hasOverlays,atmosphere:a&&this._velvetOverground,wireframeTexture:e,tileBorders:this._drawBorders,receiveShadows:this.receiveShadows,screenSizePerspective:this.debugScreenSizePerspective});this.programs.normal=d.getProgram(n.normalPass,{viewingMode:c,spherical:a,alphaZero:!0});this.programs.depth=d.getProgram(n.depthPass,{viewingMode:c,spherical:a,shadowMap:!1});this.programs.depthShadowMap=d.getProgram(n.depthPass,{viewingMode:c,
spherical:a,shadowMap:!0});this.programs.highlight=d.getProgram(n.highlightPass,{viewingMode:c,spherical:a});this.setNeedsRender()};b.prototype._renderMaterialPass=function(a,c){var e=this,d=a.shadowMap&&a.shadowMap.enabled,b=a.rctx;this.receiveShadows!==d&&(this.receiveShadows=d,this._updatePrograms());d=!this.drapedRenderer.isEmpty();d!==this._hasOverlays&&(this._hasOverlays=d,this._updatePrograms());d=a.camera;b.setDepthTestEnabled(!0);var h=this.wireframe,g=this.programs.color;b.bindProgram(g);
if("shader"===h.mode||this._drawBorders)g.setUniform1f("wireframe.width",this.wireframe.width),g.setUniform1f("wireframe.falloff",Math.min(h.width,h.falloff)),g.setUniform1f("wireframe.wireOpacity",h.wireOpacity),g.setUniform1f("wireframe.surfaceOpacity",h.surfaceOpacity),g.setUniform4fv("wireframe.color",h.color);a.shadowMap&&a.shadowMap.bind(g);a.ssaoHelper&&a.ssaoHelper.setUniforms(g);g.setUniform1i("tex",0);g.setUniform1i("overlay0Tex",1);g.setUniform1i("overlay1Tex",2);g.setUniformMatrix4fv("viewNormal",
d.viewInverseTransposeMatrix);g.setUniformMatrix4fv("proj",d.projectionMatrix);a.lightingData.helper.setUniforms(g,!0);b=d.viewMatrix;k.vec3d.set3(b[12],b[13],b[14],H);k.vec3d.normalize(H);g.setUniform3fv("viewDirection",H);this.numOriginsRendered=this.numTrianglesRendered=this.numTilesCulled=this.numTilesRendered=0;this._prepareScaleRangeQueries();this.isOpaque()?this._renderTiles(a,g,c):a.offscreenRenderingHelper.renderToTargets(function(){return e._renderTiles(a,g,c)},a.offscreenRenderingHelper.tmpColor,
a.offscreenRenderingHelper.mainDepth,[0,0,0,0]);this._processScaleRangeQueries();0<this.numTilesRendered&&!this._loaded&&(this._loaded=!0,this.loaded&&this.loaded())};b.prototype._renderDepthPass=function(a,c,e){var d=a.rctx,b=a.camera;d.bindProgram(c);d.setBlendingEnabled(!1);d.setDepthTestEnabled(!0);c.setUniformMatrix4fv("model",ia);c.setUniformMatrix4fv("viewNormal",b.viewInverseTransposeMatrix);F[0]=b.near;F[1]=b.far;c.setUniform2fv("nearFar",F);this._renderTilesAuxiliary(a,c,e,!1)};b.prototype._renderNormalPass=
function(a,c){var b=a.rctx,d=a.camera,f=this.programs.normal;b.bindProgram(f);b.setBlendingEnabled(!1);b.setDepthTestEnabled(!0);f.setUniformMatrix4fv("viewNormal",d.viewInverseTransposeMatrix);this._renderTilesAuxiliary(a,f,c,!1)};b.prototype._renderHighlightPass=function(a,c){var b=a.rctx,d=this.programs.highlight;b.bindProgram(d);b.setBlendingEnabled(!1);b.setDepthTestEnabled(!0);var f=a.offscreenRenderingHelper;b.bindTexture(f.depthTexture,3);d.setUniform1i("depthTex",3);d.setUniform4f("highlightViewportPixelSz",
0,0,1/f.width,1/f.height);this._renderTilesAuxiliary(a,d,c,!0)};b.prototype._updatePerOriginTileData=function(){var a=this.perOriginTileData;if(!this.perOriginTileDataDirty)return a;this.highestVisibleLODTile=null;this._renderCollectOrigins();if(0!==this._renderOrder){for(var c=O(this._renderOrder),b=0;b<a.length;b++)this._sortFrontToBack(a.data[b].tiles,c);c=ga(this._renderOrder);this._sortFrontToBack(a,c)}this.perOriginTileDataDirty=!1;return a};b.prototype._renderCollectOrigins=function(){var a=
this.perOriginTileData,c=this.rootTiles,b="spherical"===this.manifold;a.clear();for(var d=0;d<c.length;d++){var f=c[d],h=a.pushNew();h.root=f;h.origin=b?R:f.centerAtSeaLevel;h.tiles.clear();this._renderCollectOriginsForRoot(h)}return!0};b.prototype._renderCollectOriginsForRoot=function(a){var c=this.tileIterator,b=this.perOriginTileData;for(c.resetOne(a.root);!c.done;){var d=c.next(),f=d.renderData;if(f&&!d.visible)this.numTilesCulled++,c.skipSubtree();else{var h=b.back();if(7===d.lij[0]){if(h===
a||0!==h.tiles.length)h=b.pushNew(),h.tiles.clear();h.root=d;h.origin=d.centerAtSeaLevel}if(f){10<=d.lij[0]?b.back().tiles.push(d):a.tiles.push(d);if(!this.highestVisibleLODTile||d.vlevel>this.highestVisibleLODTile.vlevel)this.highestVisibleLODTile=d;c.skipSubtree()}}}};b.prototype._sortFrontToBack=function(a,c){a.sort(c)};b.prototype._scaleQueriesForTile=function(a){var c=a.extent;a=a.lij[0];for(var b=0;b<this.visibleScaleRangeQueriesInvPtr;){var d=this.visibleScaleRangeQueries.data[b],f=d.extent;
a>=d.minLevel&&a<=d.maxLevel&&f[0]<=c[2]&&f[2]>=c[0]&&f[1]<=c[3]&&f[3]>=c[1]?(this.visibleScaleRangeQueries.swapElements(b,this.visibleScaleRangeQueriesInvPtr-1),this.visibleScaleRangeQueriesInvPtr--):b++}};b.prototype._updateStencilReadStateForTile=function(a,c){if(a.stencilRenderingHelper&&a.stencilRenderingHelper.enabled){for(var b=this.stencilEnabledLayerExtents,d=!1,f=0;f<b.length;f++)if(c.intersectsExtent(b[f])){d=!0;break}d?a.stencilRenderingHelper.enableStencilRead():a.stencilRenderingHelper.disableStencilRead()}};
b.prototype._renderTilesAuxiliary=function(a,c,b,d){var f=a.rctx,e=f.gl,g=a.camera,k=g.viewMatrix;c.setUniformMatrix4fv("proj",g.projectionMatrix);c.setUniform1f("skirtScale",this._skirtScale);d&&(c.setUniform1i("overlay0Tex",1),c.setUniform1i("overlay1Tex",2));for(g=0;g<b.length;g++){var m=b.data[g];c.setUniform3fv("origin",m.origin);x.bindView(m.origin,k,c);for(var r=0;r<m.tiles.length;r++){var v=m.tiles.data[r],u=v.renderData;d&&(this._bindOverlayTextures(c,u.overlays,!0),c.setUniform1f("overlayOpacity",
u.overlayOpacity));this._updateStencilReadStateForTile(a,v);f.bindVAO(u.vao);N.assertCompatibleVertexAttributeLocations(u.vao,c);f.drawElements(e.TRIANGLES,0!==this._skirtScale?u.vao.indexBuffer.size:u.geometryInfo.numWithoutSkirtIndices,u.vao.indexBuffer.indexType,0)}}f.bindVAO(null);a.stencilRenderingHelper&&a.stencilRenderingHelper.disableStencilRead()};b.prototype._renderTiles=function(a,c,b){var d=a.rctx,f=d.gl,e=a.camera,g=e.viewMatrix;if(this.debugScreenSizePerspective&&this.pointsOfInterest){var p=
da.getSettings("spherical"===this.manifold?"global":"local");p.update({distance:this.pointsOfInterest.centerOnSurfaceFrequent.distance,fovY:e.fovY});x.bindScreenSizePerspective(p,a,c,"screenSizePerspective")}c.setUniform1f("skirtScale",this._skirtScale);for(e=0;e<b.length;e++)if(p=b.data[e],c.setUniform3fv("origin",p.origin),x.bindView(p.origin,g,c),a.shadowMap&&a.shadowMap.bindView(c,p.origin),this.numOriginsRendered++,p=p.tiles,0!==p.length){var m="debug"===this.wireframe.mode?f.LINES:f.TRIANGLES,
r=this.highestVisibleLODTile,v=void 0,u=void 0;r?(v=r.vlevel,u=this.tileSize/this.wireframe.resolution):(v=16,u=this.tileSize/64);for(r=0;r<p.length;r++){var n=p.data[r],l=n.renderData;this._updateStencilReadStateForTile(a,n);E.trace("# RENDER TILE "+w.tile2str(n)+", screenDepth:"+n.screenDepth);var t=l.geometryInfo.uvOffsetAndScale,q=l.texOffsetAndScale;k.vec4d.set4(t[0]*q[2]+q[0],t[1]*q[3]+q[1],t[2]*q[2],t[3]*q[3],S);c.setUniform4fv("texOffsetAndScale",S);d.bindTexture(l.textureReference||l.texture,
0);c.setUniform1f("opacity",l.opacity);this._bindOverlayTextures(c,l.overlays,!1);c.setUniform1f("overlayOpacity",l.overlayOpacity);("shader"===this.wireframe.mode||this._drawBorders)&&c.setUniform1f("wireframe.subdivision",u*(1<<v-n.vlevel));t=0!==this._skirtScale?l.vao.indexBuffer.size:l.geometryInfo.numWithoutSkirtIndices;d.bindVAO(l.vao);N.assertCompatibleVertexAttributeLocations(l.vao,c);d.drawElements(m,t,l.vao.indexBuffer.indexType,0);n.renderOrder=this.numTilesRendered;this.numTilesRendered++;
this.numTrianglesRendered+=t/3;this._scaleQueriesForTile(n)}}d.bindVAO(null);a.stencilRenderingHelper&&a.stencilRenderingHelper.disableStencilRead()};b.prototype._bindOverlayTextures=function(a,b,e){for(var c=0;2>c;c++){var f=2*c,h=b[c],g=e?h.highlightRenderTargetId:h.renderTargetId;g?(g=this.drapedRenderer.getRenderTargetTexture(g),z[f]=h.texOffset[0],z[f+1]=h.texOffset[1],A[f]=h.texScale[0],A[f+1]=h.texScale[1],this.rctx.bindTexture(g,1+c)):(z[f]=0,z[f+1]=0,A[f]=0,A[f+1]=0,this.rctx.bindTexture(this.emptyTex,
1+c))}a.setUniform4fv("overlayTexOffset",z);a.setUniform4fv("overlayTexScale",A)};b.prototype._updateTileGeometryBuffers=function(a){var c=this.rctx,b=c.gl;a=a.renderData;var d=a.geometryInfo.indices;a.vao=new fa(c,aa.Default3D,{geometry:ba.Pos3Tex},{geometry:M.createVertex(c,b.STATIC_DRAW,a.geometryInfo.vertexAttributes)},M.createIndex(c,b.STATIC_DRAW,d));this.setNeedsRender()};b.prototype._releaseTileGeometry=function(a){a=a.renderData;a.vao.dispose(!0);a.vao=null;X.releaseGeometry(a.geometryInfo);
this.setNeedsRender()};b.prototype._prepareScaleRangeQueries=function(){for(var a=this.visibleScaleRangeQueries,b=this.visibleScaleRangeQueryQueue;a.length<a.data.length&&0<b.length;){var e=b.pop();a.push(e)}this.visibleScaleRangeQueriesInvPtr=a.length};b.prototype._processScaleRangeQueries=function(){for(var a=this.visibleScaleRangeQueries,b=this.visibleScaleRangeQueryPool,e=0;e<a.length;e++){var d=a.data[e];b.release(d);d.callback(e>=this.visibleScaleRangeQueriesInvPtr);d.callback=null}a.clear()};
return b}();var ka={mode:"none",width:1.5,falloff:1.5,wireOpacity:1,surfaceOpacity:0,color:[1,1,1,0],resolution:64},H=k.vec3d.create(),la=k.vec3d.create(),ma=k.vec3d.create(),na=k.vec3d.create(),oa=k.vec3d.create();return I});