// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/arrayUtils ../../../geometry/support/aaBoundingRect ../lib/gl-matrix ../support/mathUtils ../support/buffer/typedArrayUtil ./ElevationData ./ElevationTileAgent ./MapTileAgent ./TerrainConst ./terrainUtils ./TileAgent ./TilePerLayerInfo ./tileUtils ../../vectorTiles/VectorTileDisplayObject ../../webgl/Texture".split(" "),function(J,K,u,v,f,q,E,A,w,x,g,B,F,C,y,G,H){function z(e){e instanceof w?w.Pool.release(e):e instanceof x&&x.Pool.release(e)}var D=B.weakAssert,
t=f.vec3d.create(),h=f.vec4d.create(),r=f.vec4d.create(),I=f.vec3d.create(),l=F.AGENT_DONE;return function(){function e(a){this.lij=[0,0,0];this.extent=v.create();this.elevationBounds=f.vec2d.create();this.children=[null,null,null,null];this.layerInfo=Array(g.LayerClass.COUNT);this.extentWGS84Rad=v.create();this.centerAtSeaLevel=f.vec3d.create();this.center=f.vec3d.create();this.tileUp=I;this.intersectsClippingArea=this.isWithinClippingArea=!0;this.clippingArea=null;this._memoryUsed=this.radius=this.edgeLen2=
this.edgeLen=this.renderOrder=this.screenDepth=this._maxTesselation=0;this.numSubdivisionsAtLevel=a}Object.defineProperty(e.prototype,"memoryUsed",{get:function(){return this._memoryUsed},enumerable:!0,configurable:!0});e.prototype.init=function(a,b,c,d){this.lij[0]=a[0];this.lij[1]=a[1];this.lij[2]=a[2];d.getExtent(a[0],a[1],a[2],this.extent,this.extentWGS84Rad);this.intersectsClippingArea=this.isWithinClippingArea=!0;this.clippingArea=null;this.radius=this.edgeLen2=this.edgeLen=0;this.vlevel=a?
a[0]:0;b&&b.elevationBounds?f.vec2d.set(b.elevationBounds,this.elevationBounds):f.vec2d.set2(0,0,this.elevationBounds);this.pendingUpdates=0;this.renderData=null;this.screenDepth=0;this.visible=!1;this.parent=b;this.parentSurface=c;for(a=0;4>a;a++)this.children[a]=null;for(a=0;a<g.LayerClass.COUNT;a++)if(c){b=c.numLayers(a);var k=void 0;this.layerInfo[a]?(k=this.layerInfo[a],k.length=b):(k=Array(b),this.layerInfo[a]=k);for(var e=0;e<b;e++)k[e]=C.makeEmptyLayerInfo(a,k[e]),a===g.LayerClass.ELEVATION&&
this.findElevationBoundsForLayer(e,-1)}else this.layerInfo[a]=null;this.computeElevationBounds();this._maxTesselation=Math.min(d.pixelSize[0],g.MAX_TILE_TESSELATION)};e.prototype.dispose=function(){for(var a=0;a<g.LayerClass.COUNT;a++)for(var b=0,c=this.layerInfo[a];b<c.length;b++)c[b].dispose();this.updateMemoryUsed()};e.prototype.updateMemoryUsed=function(){for(var a=this.parentSurface.tilingScheme.pixelSize,a=a[0]*a[1]*4,b=this._memoryUsed=0,c=this.layerInfo[g.LayerClass.MAP];b<c.length;b++){var d=
c[b],d=d.data;d instanceof H?this._memoryUsed+=1.3*d.descriptor.width*d.descriptor.height*4:d instanceof HTMLImageElement?this._memoryUsed+=a:d instanceof G&&(this._memoryUsed+=d.getGpuMemoryUsage()+d.getCpuMemoryUsage())}b=0;for(c=this.layerInfo[g.LayerClass.ELEVATION];b<c.length;b++)d=c[b],this._memoryUsed+=d.data?a:0;this.renderData&&(this._memoryUsed+=this.renderData.estimateGeometryMemoryUsage(),a=this.renderData.texture?this.renderData.texture.descriptor:null)&&(this._memoryUsed+=1.3*a.width*
a.height*4)};e.prototype.updateScreenDepth=function(a){f.vec3d.set(this.center,r);r[3]=1;f.mat4d.multiplyVec4(a,r,r);this.screenDepth=r[2]/r[3]};e.prototype.shouldSplit=function(a,b){var c=this.lij[0];f.vec3d.subtract(this.center,b,t);var d=f.vec3d.length2(t),k=a[4];if(d<this.edgeLen2&&c<k)return g.TileUpdateTypes.SPLIT;var e=a[1],d=2*Math.sqrt(d),n=this.edgeLen/(a[0]*d);return n<e?this.vlevel!==this.lij[0]?(this.vlevel=this.lij[0],g.TileUpdateTypes.VSPLITMERGE):g.TileUpdateTypes.NONE:c>=k?(a=c+Math.ceil(-q.log2(e/
n)),a!==this.vlevel?(this.vlevel=a,g.TileUpdateTypes.VSPLITMERGE):g.TileUpdateTypes.NONE):6<c&&(f.vec3d.scale(this.tileUp,f.vec3d.dot(this.tileUp,t),h),f.vec3d.subtract(h,t),c=f.vec3d.length2(h),c>this.radius*this.radius&&(f.vec3d.scale(h,this.radius/Math.sqrt(c)),f.vec3d.add(h,this.center),f.vec3d.subtract(b,h,h),b=this.elevationBounds[1]-this.elevationBounds[0],Math.min(1,(Math.abs(f.vec3d.dot(h,this.tileUp))+.5*b+this.curvatureHeight)/f.vec3d.length(h))*(this.edgeLen/(a[2]*d))<.1/a[5]*a[3]))?g.TileUpdateTypes.NONE:
g.TileUpdateTypes.SPLIT};e.prototype.decodeElevationData=function(a){var b;if(E.isArrayBuffer(a))try{b=A.createFromLERC(this.lij,this.extent,a,g.noDataValueOpt)}catch(c){console.warn("Error decoding raw data: %s",c.message)}else b=A.createFromFetchTileResult(this.lij,this.extent,a);return b};e.prototype.getWGS84Extent=function(){var a=this.extentWGS84Rad;return v.fromValues(q.rad2deg(a[0]),q.rad2deg(a[1]),q.rad2deg(a[2]),q.rad2deg(a[3]))};e.prototype.load=function(a){for(var b=0;b<g.LayerClass.COUNT;b++)this.layerInfo[b]&&
this._createOrUpdateAgents(0,b);a.loadTile(this)};e.prototype.unload=function(a){this.renderData&&a.unloadTile(this);for(a=0;a<g.LayerClass.COUNT;a++)for(var b=this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.loadingAgent&&d.loadingAgent!==l&&(d.loadingAgent.dispose(),z(d.loadingAgent),d.loadingAgent=null);d.pendingUpdates=0}this.pendingUpdates&=~g.TileUpdateTypes.UPDATE_GEOMETRY;this.pendingUpdates&=~g.TileUpdateTypes.UPDATE_TEXTURE};e.prototype.updateClippingStatus=function(a){if(u.equals(a,this.clippingArea))return!1;
var b=this.intersectsClippingArea,c=this.isWithinClippingArea;a?(this.intersectsClippingArea=this.intersectsExtent(a),this.isWithinClippingArea=this.isWithinExtent(a)):this.isWithinClippingArea=this.intersectsClippingArea=!0;this.clippingArea=a;a=c&&this.isWithinClippingArea;b=!c&&!b&&!this.isWithinClippingArea&&!this.intersectsClippingArea;!this.renderData||a||b||this.updateGeometry();return!0};e.prototype.updateVisibility=function(a){a=this.isVisible(a)&&this.intersectsClippingArea;if(a!==this.visible){this.visible=
a;for(var b=this.layerInfo[0],c=0;c<b.length;c++){var d=b[c];d.loadingAgent&&d.loadingAgent!==l&&d.loadingAgent.setSuspension(!a)}}return a};e.prototype.getLayerInfo=function(a,b){return this.layerInfo[b][a]};e.prototype.hasLayerData=function(a,b){return(a=this.layerInfo[b][a])&&a.data&&!a.dataInvalidated};e.prototype.hasDataAvailable=function(a,b,c){return(b=this.layerInfo[c][b].tilemap)?"unavailable"!==b.getAvailability(a.lij[1],a.lij[2]):!0};e.prototype.requestLayerData=function(a,b,c){g.TILE_LOADING_DEBUGLOG&&
console.log("tile %s layer %d/%d requested by tile %s",this.lij.toString(),b,a,c.tile.lij.toString());var d=this.layerInfo[b][a];if(-1<d.waitingAgents.indexOf(c))return console.warn("agent already requested this piece of map data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),c.tile.lij.toString(),b,a),!0;d.waitingAgents.push(c);if(d.data&&!d.dataInvalidated)return console.warn("agent requested existing data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),c.tile.lij.toString(),
b,a),setTimeout(c.dataArrived.bind(c,this),0),!0;if(d.pendingUpdates&g.TileUpdateTypes.DECODE_ELEVATION||d.requestPromise)return!0;var k=this.parentSurface.requestTileData(this,a,b);if(!k||k.isFulfilled())return!1;a=function(){d.requestPromise===k&&(d.requestPromise=null)};d.requestPromise=k;k.then(a,a);return!0};e.prototype.descendants=function(a){a||(a=[]);for(var b=0;4>b;b++){var c=this.children[b];c&&(c.descendants(a),a.unshift(this.children[b]))}return a};e.prototype.hasLij=function(a){return this.lij[0]===
a[0]&&this.lij[1]===a[1]&&this.lij[2]===a[2]};e.prototype.findByLij=function(a){if(this.hasLij(a))return this;for(var b=0;4>b;b++){var c=this.children[b];if(c&&(c=c.findByLij(a)))return c}return null};e.prototype.unrequestLayerData=function(a,b,c){g.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d canceled by tile %s",this.lij.toString(),b,a,c.tile.lij.toString());var d=this.layerInfo[b][a],k=d.waitingAgents;c=null!=u.removeUnordered(k,c);D(c,"agent has not requested this piece of map data");
1>k.length&&(k=d.requestPromise,c=!1,b===g.LayerClass.MAP&&(c=this.parentSurface.layerViewByIndex(a,g.LayerClass.MAP),c=B.isVectorTileLayerView(c)),c||D(k||d.rawData,"no pending operations on layerInfo that agents were waiting for"),k&&!k.isFulfilled()&&(k.cancel(),d.requestPromise=null),g.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d request/loading canceled",this.lij.toString(),b,a),this.updateMemoryUsed())};e.prototype.dataArrived=function(a,b,c){a=this.layerInfo[b][a];a.data=c;a.dataInvalidated=
!1;for(c=0;c<a.waitingAgents.length;c++)a.waitingAgents[c].dataArrived(this);a.waitingAgents.length=0;this.updateMemoryUsed()};e.prototype.dataMissing=function(a,b,c){c.notInTilemap||console.error("Tile %s layer %d/%d error",this.lij.toString(),b,a);a=this.layerInfo[b][a];a.dataMissing=!0;for(b=0;b<a.waitingAgents.length;b++)a.waitingAgents[b].dataMissing(this);a.waitingAgents.length=0;this.updateMemoryUsed()};e.prototype.updateTexture=function(a){void 0===a&&(a=!1);this.renderData&&(a?this.parentSurface.renderer.updateTileTexture(this):
(this.pendingUpdates|=g.TileUpdateTypes.UPDATE_TEXTURE,this.parentSurface.setPendingUpdates()))};e.prototype.invalidateLayerData=function(a,b){this.layerInfo[b][a].invalidateSourceData();this.restartAgents(b)};e.prototype.computeElevationBounds=function(){f.vec2d.set2(Number.MAX_VALUE,-Number.MAX_VALUE,this.elevationBounds);for(var a=this.layerInfo[g.LayerClass.ELEVATION],b=!1,c=0;c<a.length;c++){var d=a[c];d.elevationBounds&&(this.elevationBounds[0]=Math.min(this.elevationBounds[0],d.elevationBounds[0]),
this.elevationBounds[1]=Math.max(this.elevationBounds[1],d.elevationBounds[1]),b=!0)}b||f.vec2d.set2(0,0,this.elevationBounds);this.updateRadiusAndCenter()};e.prototype.updateRadiusAndCenter=function(){f.vec3d.scale(this.tileUp,.5*(this.elevationBounds[0]+this.elevationBounds[1]),h);f.vec3d.add(this.centerAtSeaLevel,h,this.center)};e.prototype.findElevationBoundsForLayer=function(a,b){var c=this.layerInfo[g.LayerClass.ELEVATION][a];if(!c.elevationBounds||c.elevationBounds[2]<b)if(b=this.parentSurface.layerViewByIndex(a,
g.LayerClass.ELEVATION),y.fallsWithinLayer(this,b.layer,!1)){b=!1;if(c.data){var d=c.data;f.vec2d.set(d.bounds,h);h[2]=this.lij[0];b=!0}else{for(var k=this.parent,e=0,n=null,d=c.data;k&&(!d||e<g.ELEVATION_DESIRED_RESOLUTION_LEVEL);){e=this.vlevel-k.lij[0];n=d||n;d=k.layerInfo[g.LayerClass.ELEVATION][a].data;if(!d&&n&&e>=g.ELEVATION_DESIRED_RESOLUTION_LEVEL)break;k=k.parent}if(d=d||n)d.computeMinMaxValue(this.lij[0],this.lij[1],this.lij[2],h),Infinity!==h[0]&&(h[2]=d.level,b=!0)}b&&(c.elevationBounds?
f.vec3d.set(h,c.elevationBounds):c.elevationBounds=[h[0],h[1],h[2]])}};e.prototype.updateGeometry=function(){this.pendingUpdates|=g.TileUpdateTypes.UPDATE_GEOMETRY;this.parentSurface.setPendingUpdates()};e.prototype.modifyLayers=function(a,b,c){for(var d=this.layerInfo[c],e=0;e<d.length;e++){var f=d[e];f.loadingAgent&&f.loadingAgent!==l&&(f.loadingAgent.dispose(),z(f.loadingAgent),f.loadingAgent=null);f.waitingAgents.length=0}if(c===g.LayerClass.MAP)for(e=0;e<d.length;++e)void 0===a[e]&&d[e].dispose();
a=b.length;f=Array(a);for(e=0;e<a;e++){var h=b[e];f[e]=-1<h?d[h]:C.makeEmptyLayerInfo(c)}this.layerInfo[c]=f;this.updateMemoryUsed()};e.prototype.restartAgents=function(a){if(this.renderData)if(this._createOrUpdateAgents(0,a),a===g.LayerClass.ELEVATION){this.updateGeometry();a=this.layerInfo[a];for(var b=0;b<a.length;b++)a[b].pendingUpdates|=g.TileUpdateTypes.UPDATE_GEOMETRY;this.parentSurface.setPendingUpdates()}else this.updateTexture(!0)};e.prototype.updateAgents=function(a){if(this.renderData){for(var b=
this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.loadingAgent===l&&(d.loadingAgent=null)}this._createOrUpdateAgents(0,a)}};e.prototype.removeLayerAgent=function(a,b){a=this.layerInfo[b][a];a.loadingAgent&&a.loadingAgent!==l&&a.loadingAgent.dispose();a.loadingAgent=null};e.prototype.agentDone=function(a,b){var c=this.layerInfo[b],d=c[a];d.loadingAgent=l;d.data||d.upsampleFromTile||a<c.length-1&&this._createOrUpdateAgents(a+1,b)};e.prototype._createOrUpdateAgents=function(a,b){for(var c=b===g.LayerClass.ELEVATION?
!1:!this.visible,d=this.layerInfo[b];a<d.length;++a){var e=d[a],f=!1,h=this.parentSurface.layerViewByIndex(a,b);if(e.loadingAgent)e.loadingAgent!==l&&(f=e.loadingAgent.update());else if(y.fallsWithinLayer(this,h.layer,!1)){var m;m=b===g.LayerClass.ELEVATION?w.Pool.acquire():x.Pool.acquire();(f=m.init(this,a,b,c))?e.loadingAgent=m:(m.dispose(),z(m),e.loadingAgent=l)}if(f&&h.isOpaque)break}};e.prototype.geometryState=function(a){var b,c=this._getElevationInfo(a?a.samplerData:null),d=this.lij[0];c.samplerData?
(b=this.vlevel-d,b=Math.max(d-c.maxTileLevel,g.ELEVATION_DESIRED_RESOLUTION_LEVEL-b),d=this._maxTesselation,b=q.clamp((d>>b)+1,2,d+1)):b=8>d?this.numSubdivisionsAtLevel[d]+1:2;d=this.clippingArea;if(!this.intersectsClippingArea||this.isWithinClippingArea)d=null;a?(a.needsUpdate=!1,a.numVertsPerRow!==b&&(a.numVertsPerRow=b,a.needsUpdate=!0),c.changed&&(a.samplerData=c.samplerData,a.needsUpdate=!0),u.equals(a.clippingArea,d)||(a.clippingArea=d,a.needsUpdate=!0)):a={numVertsPerRow:b,samplerData:c.samplerData,
needsUpdate:!0,clippingArea:d};return a};e.prototype._getElevationInfo=function(a){for(var b=this.layerInfo[g.LayerClass.ELEVATION],c=b.length,d=Array(c),e=0,f=0,h=!1,m=0;m<c;m++){var l=b[m];if(l.upsampleFromTile){var l=l.upsampleFromTile.tile,p=l.layerInfo[g.LayerClass.ELEVATION][m].data;a&&a[e]===p.samplerData||(h=!0);d[e++]=p.samplerData;f=Math.max(f,l.lij[0])}else l.data&&(p=this.parentSurface.layerViewByIndex(m,g.LayerClass.ELEVATION),y.fallsWithinLayer(this,p.layer,!1)&&(p=l.data,a&&a[e]===
p.samplerData||(h=!0),d[e++]=p.samplerData,f=this.lij[0]))}a&&a.length!==e&&(h=!0);0<e?d.length=e:d=null;return{changed:h,samplerData:d,maxTileLevel:f}};e.prototype.isWithinExtent=function(a){var b=this.extent;return b[0]>=a[0]&&a[2]>=b[2]&&b[1]>=a[1]&&a[3]>=b[3]};e.prototype.intersectsExtent=function(a){var b=this.extent;return b[2]>=a[0]&&a[2]>=b[0]&&b[3]>=a[1]&&a[3]>=b[1]};return e}()});