// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
require({cache:{"esri/renderers/support/heatmapUtils":function(){define(["require","exports","../../core/global","../../views/3d/support/mathUtils"],function(k,c,m,a){function n(h,d,b,l,g){h=new Uint32Array(h*h);d="buffer"in d?d:new Float64Array(d);b="buffer"in b?new Uint32Array(b.buffer):new Uint32Array((new Uint8Array(b)).buffer);g=b.length/(g-l);for(var e=0;e<d.length;e++)h[e]=b[a.clamp(Math.floor((d[e]-l)*g),0,b.length-1)];return h.buffer}function q(a){for(var d=Math.round(4.5*a),b=a*a,l=new Float64Array(2*
d+1),g=0;g<=l.length;g++)l[g]=Math.exp(-Math.pow(g-d,2)/(2*b))/Math.sqrt(2*Math.PI)*(a/2);return l}function e(a,d){return"function"===typeof a?a:a?"string"===typeof d?function(b){return-1*+b[a]}:function(b){return+b[a]+d}:function(b){return 1}}Object.defineProperty(c,"__esModule",{value:!0});c.generateGradient=function(){if(!("document"in m))return function(a){return null};var a=document.createElement("canvas"),d=a.getContext("2d");a.height=512;a.width=1;return function(b){var l=d.createLinearGradient(0,
0,0,a.height),g=0;for(b=b.colorStops;g<b.length;g++){var e=b[g],c=e.color;l.addColorStop(e.ratio,"rgba("+c[0]+", "+c[1]+", "+c[2]+", "+c[3]+")")}d.fillStyle=l;d.fillRect(0,0,1,a.height);return d.getImageData(0,0,1,a.height).data}}();c.calculateHeatmapIntensityInfo=function(a,d,b,l){var g=d.blurRadius,c=d.fieldOffset,h=d.field;d=new Float64Array(b*l);for(var n=q(g),g=Math.round(4.5*g),k=Number.NEGATIVE_INFINITY,m,c=e(h,c),h=0;h<a.length;h++){var f=a[h],p=f.geometry,u=p.x-g,w=p.y-g,A=Math.max(0,u);
m=Math.max(0,w);for(var B=Math.min(l,p.y+g),p=Math.min(b,p.x+g),f=+c(f.attributes),r=m;r<B;r++)for(var C=n[r-w],t=A;t<p;t++)m=d[r*b+t]+=C*n[t-u]*f,m>k&&(k=m)}return{matrix:d.buffer,max:k}};c.drawHeatmap=function(a,d,b,l,g,e){var c=a.getContext("2d");c.clearRect(0,0,d,d);var h=c.getImageData(0,0,d,d);b&&l&&h.data.set(new Uint8ClampedArray(n(d,b,l,g,e)));c.putImageData(h,0,0);return a};c.createHeatmapImageData=n;c.createKernel=q;c.createValueFunction=e})},"esri/views/2d/layers/features/tileRenderers/BaseTileRenderer":function(){define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/Accessor ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators ../../../tiling/enums".split(" "),
function(k,c,m,a,n,q,e,h){Object.defineProperty(c,"__esModule",{value:!0});k=function(d){function b(a){a=d.call(this)||this;a.tiles=new Map;a.layer=null;return a}m(b,d);b.prototype.destroy=function(){this.tiles.clear();this.layer=this.layerView=this.tileInfoView=this.highlightOptions=this.configuration=this.tiles=null};Object.defineProperty(b.prototype,"updating",{get:function(){return this.isUpdating()},enumerable:!0,configurable:!0});b.prototype.acquireTile=function(a){var b=this,d=this.createTile(a);
d.once("attach",function(){return b.notifyChange("updating")});this.tiles.set(a.id,d);return d};b.prototype.forEachTile=function(a){this.tiles.forEach(a)};b.prototype.releaseTile=function(a){this.tiles.delete(a.key.id);this.disposeTile(a)};b.prototype.isUpdating=function(){var a=!0;this.tiles.forEach(function(b){a=a&&b.status!==h.TileStatus.INITIALIZED});return!a};b.prototype.requestUpdate=function(){this.layerView.requestUpdate()};a([e.property()],b.prototype,"configuration",void 0);a([e.property()],
b.prototype,"highlightOptions",void 0);a([e.property()],b.prototype,"layer",void 0);a([e.property()],b.prototype,"layerView",void 0);a([e.property()],b.prototype,"tileInfoView",void 0);a([e.property()],b.prototype,"updating",null);return b=a([e.subclass()],b)}(e.declared(n,q));c.default=k})},"esri/views/2d/layers/features/tileRenderers/support/HeatmapSource":function(){define("require exports ../../../../../../core/tsSupport/extendsHelper ../../../../../../core/tsSupport/decorateHelper ../../../../../../core/ObjectFactory ../../../../../../core/ObjectPool ../../../../../../renderers/support/heatmapUtils ../../../../engine/BitmapSource".split(" "),
function(k,c,m,a,n,q,e,h){Object.defineProperty(c,"__esModule",{value:!0});var d=new n.default(function(){var a=document.createElement("canvas");a.width=a.height=512;return a},function(a){a.width=a.height=512});k=function(a){function b(){var b=a.call(this,d.acquire())||this;b._invalidated=!0;b._gradient=null;return b}m(b,a);Object.defineProperty(b.prototype,"gradient",{get:function(){return this._gradient},set:function(a){this._gradient=a;this.invalidate()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"intensities",{get:function(){return this._intensities},set:function(a){this._intensities=a;this.invalidate()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"minPixelIntensity",{get:function(){return this._minPixelIntensity},set:function(a){this._minPixelIntensity=a;this.invalidate()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"maxPixelIntensity",{get:function(){return this._maxPixelIntensity},set:function(a){this._maxPixelIntensity=a;this.invalidate()},
enumerable:!0,configurable:!0});b.prototype.acquire=function(){this.data=d.acquire()};b.prototype.release=function(){d.release(this.data);this.gradient=this.intensities=this.data=null};b.prototype.draw=function(b,d,c,h,m,n,f,p,u){this._invalidated&&(this._invalidated=!1,e.drawHeatmap(this.data,512,this._intensities,this._gradient,this._minPixelIntensity,this._maxPixelIntensity));a.prototype.draw.call(this,b,d,c,h,m,n,f,p,u)};b.prototype.invalidate=function(){this._invalidated=!0;this.emit("update",
this)};b.pool=new q(b,!0);return b}(h.default);c.default=k})},"esri/core/ObjectFactory":function(){define(["require","exports"],function(k,c){Object.defineProperty(c,"__esModule",{value:!0});k=function(){function c(a,c,k,e){void 0===k&&(k=1);void 0===e&&(e=0);this.acquireFunction=a;this.releaseFunction=c;this.growthSize=k;this._pool=Array(e);this._set=new Set;this._initialSize=e;for(a=0;a<e;a++)this._pool[a]=this.acquireFunction();this.growthSize=Math.max(k,1)}c.prototype.acquire=function(){var a;
if(0===this._pool.length){a=this.growthSize;for(var c=0;c<a;c++)this._pool[c]=this.acquireFunction()}(a=this._pool.shift())&&a.acquire&&"function"===typeof a.acquire&&a.acquire();this._set.delete(a);return a};c.prototype.release=function(a){a&&!this._set.has(a)&&(this.releaseFunction?this.releaseFunction(a):a&&a.release&&"function"===typeof a.release&&a.release(),this._pool.push(a),this._set.add(a))};c.prototype.prune=function(){if(!(this._pool.length<=this._initialSize))for(var a;this._initialSize>
this._pool.length;)a=this._pool.shift(),this._set.delete(a),a.dispose&&"function"===typeof a.dispose&&a.dispose()};return c}();c.default=k})},"*noref":1}});
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../renderers ../../../../../core/Accessor ../../../../../core/promiseUtils ../../../../../core/accessorSupport/decorators ../../../../../renderers/support/diffUtils ../../../../../renderers/support/heatmapUtils ../../../engine/BitmapContainer ../../../engine/BitmapTile ../../../engine/Canvas2DContainer ./BaseTileRenderer ./support/HeatmapSource ../../../tiling/enums".split(" "),function(k,
c,m,a,n,q,e,h,d,b,l,g,x,y,v,z){Object.defineProperty(c,"__esModule",{value:!0});k=function(c){function f(a){a=c.call(this)||this;a._canvas=new x;a._bitmaps=new l;a._canvas.addChild(a._bitmaps);return a}m(f,c);Object.defineProperty(f.prototype,"gradient",{get:function(){return b.generateGradient(this.configuration.renderer)},enumerable:!0,configurable:!0});f.prototype.createTile=function(a){var b=g.default.pool.acquire();b.key.set(a);this.tileInfoView.getTileCoords(b,a);b.resolution=this.tileInfoView.getTileResolution(a);
b.height=b.width=512;return b};f.prototype.applyConfiguration=function(a){this.configuration=a;a=a.renderer;var b=a.minPixelIntensity,p=a.maxPixelIntensity,c=this.gradient;this.tiles.forEach(function(a){if(a=a.source)a.minPixelIntensity=b,a.maxPixelIntensity=p,a.gradient=c})};f.prototype.clear=function(){this.tiles.forEach(function(a){if(a=a.source)a.intensities=null})};f.prototype.getProcessorConfiguration=function(){var a=this.layer;return{type:"heatmap",renderer:a.renderer.toJSON(),definitionExpression:a.definitionExpression,
outFields:a.outFields,gdbVersion:a.gdbVersion,historicMoment:a.historicMoment&&a.historicMoment.getTime()}};f.prototype.hitTest=function(a,b){return e.resolve([])};f.prototype.highlight=function(a){return{remove:function(){}}};f.prototype.install=function(a){a.addChild(this._canvas)};f.prototype.uninstall=function(a){a.removeChild(this._canvas)};f.prototype.needsProcessorReconfiguration=function(a){var b=this.configuration;return this.wouldClear(a)||b.definitionExpression!==a.definitionExpression};
f.prototype.wouldClear=function(a){var b=this.configuration;if(!b||b.outFields.join()!==a.outFields.join())return!0;b=this.configuration&&n.fromJSON(this.configuration.renderer)||null;a=a&&n.fromJSON(a.renderer)||null;a=d.diff(b,a);if(!a)return!1;switch(a.type){case "complete":return!0;case "partial":for(var c in a.diff)if("colorStops"!==c&&"minPixelIntensity"!==c&&"maxPixelIntensity"!==c)return!0}return!1};f.prototype.disposeTile=function(a){a.source&&v.default.pool.release(a.source);this._bitmaps.removeChild(a);
g.default.pool.release(a)};f.prototype.supportsRenderer=function(a){return a&&"heatmap"===a.type};f.prototype.onTileData=function(a){var b=this.tiles.get(a.tileKey);if(b){a=a.intensityInfo;var c=this.configuration.renderer,d=c.minPixelIntensity,c=c.maxPixelIntensity;if(b.source)b.source.minPixelIntensity=d,b.source.maxPixelIntensity=c,b.source.gradient=this.gradient,b.source.intensities=a&&a.matrix||null;else{var e=v.default.pool.acquire();e.intensities=a&&a.matrix||null;e.minPixelIntensity=d;e.maxPixelIntensity=
c;e.gradient=this.gradient;b.source=e;b.source.x=b.x;b.source.y=b.y;b.status=z.TileStatus.READY;this._bitmaps.addChild(b);this.requestUpdate()}}};f.prototype.onTileError=function(a){console.error(a)};a([h.property({readOnly:!0,dependsOn:["configuration"]})],f.prototype,"gradient",null);return f=a([h.subclass()],f)}(h.declared(q,y.default));c.default=k});