// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/extendsHelper ../../../../../core/Logger ../Utils ./vvFlagUtils".split(" "),function(h,l,r,p,t,q){Object.defineProperty(l,"__esModule",{value:!0});var u=p.getLogger("esri/views/2d/engine/webgl/util/Matcher");h=function(){function e(){this._defaultResult=null}e.fromSimpleRenderer=function(b,a,f){var d=b.getSymbols(),c=q.getVVFlags(b.visualVariables);b=new e;d.length&&(a=f.createTemplateGroup(d[0],null,a,c),b.setDefault(a));return b};e.prototype.size=
function(){return 1};e.prototype.getDefault=function(){return this._defaultResult};e.prototype.setDefault=function(b){this._defaultResult=b};e.prototype.match=function(b,a){return this.getDefault()};return e}();l.default=h;p=function(e){function b(a,f,d,c){var b=e.call(this)||this;b._intervals=[];b._isMaxInclusive=f;d?b._getValue=t.createArcadeFunction(d):a&&a.length?"function"===typeof a?(b._field=null,b._getValue=a):(b._field=a,b._normalizationInfo=c,b._getValue=b._getValueFromField.bind(b)):b._field=
null;return b}r(b,e);b.fromCBRenderer=function(a,f,d,c,e){var k=a.isMaxInclusive,n=a.valueExpression,g=a.normalizationField,m=a.normalizationTotal,h=a.normalizationType,l=q.getVVFlags(a.visualVariables);c=new b(a.field,k,n?{valueExpression:n,spatialReference:c,layer:{fields:e}}:null,{normalizationField:g,normalizationTotal:m,normalizationType:h});e=a.backgroundFillSymbol;k=0;for(n=a.classBreakInfos;k<n.length;k++)g=n[k],m=d.createTemplateGroup(g.symbol,e,f,l),c.add({min:g.minValue,max:g.maxValue},
m);if(a=a.defaultSymbol)f=d.createTemplateGroup(a,e,f,l),c.setDefault(f);return c};b.prototype.add=function(a,b){this._intervals.push({interval:a,result:b});this._intervals.sort(function(a,b){return a.interval.min-b.interval.min})};b.prototype.size=function(){return e.prototype.size.call(this)+this._intervals.length};b.prototype.match=function(a,b){if(!this._getValue)return this.getDefault();a=this._getValue(a,b);if(!a&&(null===a||void 0===a||isNaN(a)))return this.getDefault();for(b=0;b<this._intervals.length;b++){var d=
this._intervals[b],c=d.interval,d=d.result,f=this._isMaxInclusive?a<=c.max:a<c.max;if(a>=c.min&&f)return d}return this.getDefault()};b.prototype._needsNormalization=function(){var a=this._normalizationInfo;return a&&(a.normalizationField||a.normalizationTotal||a.normalizationType)};b.prototype._getValueFromField=function(a){var b=a.attributes[this._field];if(!this._needsNormalization())return b;var d=this._normalizationInfo,c=d.normalizationField,e=d.normalizationTotal,d=d.normalizationType;a=!!c&&
a.attributes[c];if(d)switch(d){case "field":return(a||void 0)&&b/a;case "log":return Math.log(b)*Math.LOG10E;case "percent-of-total":return b/e*100;default:u.error("Found unknown normalization type: "+d)}else u.error("Normalization is required, but no type was set!")};return b}(h);l.IntervalMatcher=p;h=function(e){function b(a,b,d){var c=e.call(this)||this;c._resultsMap=new Map;d?c._getValue=t.createArcadeFunction(d):a&&a.length?"function"===typeof a[0]?(c._fields=null,c._getValue=a[0]):(c._fields=
a,c._seperator=b||"",c._getValue=c._getValueFromFields.bind(c)):c._fields=null;return c}r(b,e);b.fromUVRenderer=function(a,e,d,c,k){var f=a.uniqueValueInfos,h=q.getVVFlags(a.visualVariables),g=[a.field];a.field2&&g.push(a.field2);a.field3&&g.push(a.field3);var m=a.valueExpression,l=a.backgroundFillSymbol;c=new b(g,a.fieldDelimiter,m?{valueExpression:m,spatialReference:c,layer:{fields:k}}:null);for(k=0;k<f.length;k++)g=f[k],m=d.createTemplateGroup(g.symbol,l,e,h),c.add(g.value,m);a.defaultSymbol&&
(a=d.createTemplateGroup(a.defaultSymbol,l,e,h),c.setDefault(a));return c};b.prototype.add=function(a,b){this._resultsMap.set(a.toString(),b)};b.prototype.size=function(){return e.prototype.size.call(this)+this._resultsMap.size};b.prototype.match=function(a,b){if(!this._getValue)return this.getDefault();a=this._getValue(a,b);if(!a&&(null===a||void 0===a))return this.getDefault();a=a.toString();return this._resultsMap.has(a)?this._resultsMap.get(a):this.getDefault()};b.prototype._getValueFromFields=
function(a){for(var b=[],d=0,c=this._fields;d<c.length;d++)b.push(a.attributes[c[d]]);return b.join(this._seperator)};return b}(h);l.MapMatcher=h});