// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/assignHelper ../../../../core/has ../../../../core/Logger ../../../../core/promiseUtils ../../lib/gl-matrix ../lib/DrapedRenderer ../lib/GLMaterialRep ../lib/GLTextureRep ../lib/ProgramRepository ../lib/tracer ../lighting/Lightsources ./Model ./Viewport ../../../support/screenshotUtils ../../../webgl/context-util ../../../webgl/FramebufferObject ../../../webgl/RenderingContext".split(" "),function(n,J,q,r,t,u,k,v,w,x,y,m,z,A,B,l,C,D,E){var F=t.getLogger("esri.views.3d.webgl-engine.parts.View");
n=function(){function b(a,e,b,c){var d=this;this._backgroundColor=k.vec4d.createFrom(1,1,1,1);this._lightDirection=k.vec3d.createFrom(0,1,0);this._didRender=!1;this._idleSuspend=this._needsRender=!0;this._shouldRender=!1;this._supersampleScreenshots=!0;this._screenshotQueue=[];this._container=a;this._stage=e;this._initializeContext(c);this._programRepository=new y(this._rctx);this._programRepository.globalOptions.viewingMode=c.viewingMode;this._textureRep=new x(e.getAll(A.ContentType.TEXTURE),this._programRepository,
function(){return d._viewport.getCamera().viewport},this._rctx);this._materialRep=new w(this._textureRep,this._programRepository);this._viewport=new B(this._stage,this._programRepository,this._materialRep,this._textureRep,this._rctx);this._initializeViewportCamera();this._drapedRenderer=new v(this._rctx,this._canvas,this._programRepository,this._materialRep,this._textureRep,b);this._initializeFrameTask()}Object.defineProperty(b.prototype,"isLoadingResources",{get:function(){return this._viewport.isLoadingResources},
enumerable:!0,configurable:!0});b.prototype._initializeFrameTask=function(){var a=this;this._frameTask={preRender:function(){m.begin();a._stage.processDirty();a.needsRender()?(a._shouldRender=!0,a._viewport.getCamera().setGLViewport(a._rctx),a._rctx.setClearColor.apply(a._rctx,a._backgroundColor),a._rctx.clear(16640)):a._shouldRender=!1},render:function(){a._shouldRender&&(a._didRender=!0,p.lightDirection=a._lightDirection,a._viewport.render(p))},postRender:function(){m.end()},update:function(){a.resetNeedsRender();
a._performScreenshots()}}};b.prototype._initializeViewportCamera=function(){var a=this._container.getBoundingClientRect(),e=this._viewport.getCamera();e.viewport[2]=a.width;e.viewport[3]=a.height;this._viewport.setCamera(e)};b.prototype._initializeContext=function(a){this._canvas=a.canvas;this._canvas||(this._canvas=document.createElement("canvas"));this._canvas.setAttribute("style","width: 100%; height:100%; display:block;");var e=C.createContextOrErrorHTML(this._canvas,{alpha:a.alpha||!1,premultipliedAlpha:!0,
antialias:!1,depth:!0,stencil:null==a.stencil?!0:a.stencil},a.renderContext);this._gl=m.instrumentContext(e);this._rctx=new E(this._gl,{disabledExtensions:a.deactivatedWebGLExtensions||{}});!a.alpha&&this._rctx.contextAttributes.alpha&&F.error("WebGL context has alpha channel even though no alpha channel was requested");!this._rctx.contextAttributes.alpha&&11<=r("safari")&&(this._container.style.backgroundColor="black");this._container.appendChild(this._canvas);null!=a.supersampleScreenshots&&(this._supersampleScreenshots=
a.supersampleScreenshots)};b.prototype.dispose=function(){this._viewport.dispose();this._viewport=null;this._drapedRenderer.dispose();this._drapedRenderer=null;this._programRepository.dispose();this._programRepository=null;this._container.contains(this._canvas)&&this._container.removeChild(this._canvas);this._frameTask=this._gl=this._canvas=this._container=null};b.prototype.getCombinedStats=function(){return this._viewport.getCombinedStats()};b.prototype.setNeedsRender=function(){this._didRender=
!1;this._needsRender=!0};b.prototype.resetNeedsRender=function(){this._didRender&&(this._didRender=this._needsRender=!1);this._viewport.resetNeedsRender();this._textureRep.resetNeedsRender()};b.prototype.needsRender=function(){return this._needsRender||!this._idleSuspend||this._viewport.needsRender()||this._textureRep.needsRender()};b.prototype.getFrameTask=function(){return this._frameTask};b.prototype.setLighting=function(a){k.vec3d.set3(0,0,0,this._lightDirection);for(var e=0,b=a.lights;e<b.length;e++){var c=
b[e];if(c instanceof z.MainLight){k.vec3d.negate(c.direction,this._lightDirection);break}}this._viewport.setLighting(a);this._needsRender=!0};b.prototype.getEdgeView=function(){return this._viewport.getEdgeView()};b.prototype.getMainLightDirection=function(){return this._lightDirection};b.prototype.getViewParams=function(a){var e={};if(!a||a.backgroundColor)e.backgroundColor=this._backgroundColor;return e};b.prototype.setViewParams=function(a){this._needsRender=!0;a.backgroundColor&&(this._backgroundColor=
a.backgroundColor)};b.prototype.setRenderParams=function(a){this._needsRender=!0;void 0!==a.idleSuspend&&(this._idleSuspend=!!a.idleSuspend);this._viewport.setRenderParams(a)};b.prototype.getRenderParams=function(){var a=this._viewport.getRenderParams();a.anisotropicFiltering=this._textureRep.getMaxAnisotropy();a.idleSuspend=this._idleSuspend;return a};b.prototype.getIdleSuspend=function(){return this._idleSuspend};Object.defineProperty(b.prototype,"renderingContext",{get:function(){return this._rctx},
enumerable:!0,configurable:!0});b.prototype.has=function(a){return"s3tc"===a?!!this._rctx.capabilities.compressedTextureS3TC:"shaderTextureLOD"===a?!!this._rctx.capabilities.shaderTextureLOD:!1};b.prototype.modify=function(a,e,b,c){this._viewport.modify(a,e,b,c)};b.prototype.setCamera=function(a){this._viewport.setCamera(a)};b.prototype.getCamera=function(){return this._viewport.getCamera()};b.prototype.getCanvas=function(){return this._canvas};b.prototype.getDrapedTextureRenderer=function(){return this._drapedRenderer};
b.prototype.takeScreenshot=function(a){var e=this,b=u.createResolver(function(){e._screenshotQueue=e._screenshotQueue.filter(function(a){return a.resolver!==b})});this._screenshotQueue.push({settings:a,resolver:b});this._needsRender=!0;return b.promise};b.prototype.getFramebufferTexture=function(a){return this._viewport.getFramebufferTexture(a)};Object.defineProperty(b.prototype,"renderPlugins",{get:function(){return this._viewport.renderPlugins},enumerable:!0,configurable:!0});b.prototype._screenshotSuperSampleSettings=
function(a){if(!this._supersampleScreenshots)return a;var b=a.framebufferWidth,d=a.framebufferHeight,c=a.region,f=Math.min(G,H/Math.max(b,d));return f<I?a:q({},a,{framebufferWidth:Math.round(b*f),framebufferHeight:Math.round(d*f),pixelRatio:a.pixelRatio*f,resample:{region:{x:Math.round(c.x*f),y:Math.round(c.y*f),width:Math.round(c.width*f),height:Math.round(c.height*f)},width:b,height:d}})};b.prototype._readbackScreenshot=function(a){var b=a.framebufferWidth,d=a.framebufferHeight,c=a.region;if(a=
a.resample){var f=l.createEmptyImageData(b,d,this._ensureScreenshotEncodeCanvas());this._gl.readPixels(0,0,b,d,6408,5121,new Uint8Array(f.data.buffer));b=l.createEmptyImageData(c.width,c.height,this._ensureScreenshotEncodeCanvas());return l.resampleHermite(f,b,!0,a.region.x,d-(a.region.y+a.region.height),a.region.width,a.region.height)}f=l.createEmptyImageData(c.width,c.height,this._ensureScreenshotEncodeCanvas());this._gl.readPixels(c.x,d-(c.y+c.height),c.width,c.height,6408,5121,new Uint8Array(f.data.buffer));
return f};b.prototype._renderScreenshot=function(a){var b=null,d=this._viewport.getCamera();a=this._screenshotSuperSampleSettings(a);var c=a.framebufferWidth,f=a.framebufferHeight,h=!1;if(c!==d.fullWidth||f!==d.fullHeight){var g=d.copy();g.fullWidth=c;g.fullHeight=f;b=d.fovX-g.fovX;h=d.fovY-g.fovY;0>b&&b<h?g.fovX=d.fovX:0>h&&h<b&&(g.fovY=d.fovY);this._drapedRenderer.forceUpdate&&this._drapedRenderer.forceUpdate(g);h=!0;b=new D(this._rctx,{width:g.fullWidth,height:g.fullHeight,colorTarget:0,depthStencilTarget:3});
this._rctx.bindFramebuffer(b);g.setGLViewport(this._rctx);this._rctx.setClearColor.apply(this._rctx,this._backgroundColor);this._rctx.clear(16640);this._viewport.render({lightDirection:this._lightDirection,fbo:b,camera:g,pixelRatio:a.pixelRatio})}a=this._readbackScreenshot(a);b&&b.dispose();this._rctx.bindFramebuffer(null);h&&this._drapedRenderer.forceUpdate&&this._drapedRenderer.forceUpdate(d);return a};b.prototype._performScreenshots=function(){if(0!==this._screenshotQueue.length){for(var a=0,b=
this._screenshotQueue;a<b.length;a++){var d=b[a],c=d.settings;if(this._gl){var f=this._ensureScreenshotEncodeCanvas(),h=this._renderScreenshot(c),c=l.encodeResult(h,c,f,{flipY:!0,premultipliedAlpha:!0});d.resolver(c)}else d.resolver.reject()}this._screenshotQueue=[]}};b.prototype._ensureScreenshotEncodeCanvas=function(){this._screenshotEncodeCanvas||(this._screenshotEncodeCanvas=document.createElement("canvas"));return this._screenshotEncodeCanvas};return b}();var p={lightDirection:k.vec3d.create(),
camera:null,fbo:null,pixelRatio:1},H=2048,I=1.5,G=8;return n});