// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/TimeProfiler ../../lib/gl-matrix ../../support/debugFlags ../lib/depthRange ../lib/depthRangeUtils ../lib/HighlightHelper ../lib/OffscreenRenderingHelper ../lib/Renderer ../lib/RenderOccludedHelper ../lib/RenderPass ../lib/ShadowMap ../lib/SliceHelper ../lib/SSAOHelper ../lib/Util".split(" "),function(z,A,k,h,l,m,n,p,q,r,t,u,v,w,x,f){var y=f.assert;return function(){function b(a,d,b,c,e){this._drawSSAOMapDebugQuad=this._drawShadowMapDebugQuad=!1;this._needsRender=
!0;this._content=new Map;this._stage=a;this._rctx=e;this._renderer=new r(d,b,c,this._rctx,!1);this._programRep=d;this._helpers={shadowMap:new v(d,this._rctx),ssao:new x(d,this._rctx,this.setNeedsRender.bind(this)),highlight:new p(d,this._rctx),renderOccluded:new t(d,this._rctx),slice:new w,offscreenRendering:new q(d,this._rctx)}}Object.defineProperty(b.prototype,"isLoadingResources",{get:function(){return this._renderer.isLoadingResources},enumerable:!0,configurable:!0});b.prototype.getCombinedStats=
function(){return this._renderer.getCombinedStats()};b.prototype.dispose=function(){this._renderer.dispose();this._helpers.shadowMap.enabled=!1;this._helpers.shadowMap.dispose();this._helpers.ssao.enabled=!1;this._helpers.ssao.dispose();this._helpers.highlight.enabled=!1;this._helpers.renderOccluded.enabled=!1;this._helpers.offscreenRendering.enabled=!1};b.prototype.setLighting=function(a){this._renderer.setLighting(a)};b.prototype.setRenderParams=function(a){void 0!==a.shadowMapResolution&&!1===
this._helpers.shadowMap.enabled&&(this._helpers.shadowMap.textureResolution=a.shadowMapResolution);void 0!==a.shadowMap&&(this._helpers.shadowMap.enabled=a.shadowMap);void 0!==a.shadowMapMaxCascades&&(this._helpers.shadowMap.maxCascades=a.shadowMapMaxCascades);this._helpers.highlight.enabled=!0;void 0!==a.ssao&&(this._helpers.ssao.enabled=a.ssao);void 0!==a.ssaoAttenuation&&(this._helpers.ssao.attenuation=a.ssaoAttenuation);void 0!==a.ssaoRadius&&(this._helpers.ssao.radius=a.ssaoRadius);void 0!==
a.ssaoFilterRadius&&console.error("The property ssaoFilterRadius is no longer supported as a render parameter.");void 0!==a.ssaoSamples&&(this._helpers.ssao.samples=a.ssaoSamples);void 0!==a.drawShadowMapDebugQuad&&(this._drawShadowMapDebugQuad=a.drawShadowMapDebugQuad);void 0!==a.drawSSAODebugQuad&&(this._drawSSAOMapDebugQuad=a.drawSSAODebugQuad);this._renderer.ssaoEnabled=this._helpers.ssao.enabled;void 0!==a.offscreenRendering&&(this._helpers.offscreenRendering.enabled=a.offscreenRendering);a.background&&
(this._helpers.offscreenRendering.background=a.background);void 0!==a.antialiasingEnabled&&(this._renderer.renderOptions.antialiasing=a.antialiasingEnabled?"smaa":"none");void 0!==a.earlyOcclusionPixelDraw&&(this._renderer.renderOptions.earlyOcclusionPixelDraw=a.earlyOcclusionPixelDraw);void 0!==a.defaultHighlightOptions&&this._helpers.highlight.setDefaultOptions(a.defaultHighlightOptions);void 0!==a.slicePlane&&(this._helpers.slice.plane=a.slicePlane);this._needsRender=!0};b.prototype.getRenderParams=
function(){var a={};a.shadowMap=this._helpers.shadowMap.enabled;a.shadowMapResolution=this._helpers.shadowMap.textureResolution;a.shadowMapMaxCascades=this._helpers.shadowMap.maxCascades;this._helpers.ssao.isSupported&&(a.ssao=this._helpers.ssao.enabled,a.ssaoAttenuation=this._helpers.ssao.attenuation,a.ssaoRadius=this._helpers.ssao.radius,a.ssaoFilterRadius=this._helpers.ssao.filterRadius,a.ssaoSamples=this._helpers.ssao.samples);return a};b.prototype.getFramebufferTexture=function(a){switch(a){case "color":return this._helpers.offscreenRendering.colorTexture;
case "hudVisibility":return this._helpers.offscreenRendering.hudVisibilityTexture;case "shadowMap":return this._helpers.shadowMap.getDepthTexture()}return this._renderer.getFramebufferTexture(a)};b.prototype.modify=function(a,d,b,c){this._renderer.modify(a,d,b,c);for(c=0;c<d.length;++c)this._content.delete(d[c].uniqueName);for(c=0;c<a.length;++c)this._content.set(a[c].uniqueName,a[c]);for(c=0;c<b.length;++c)y(this._content.get(b[c].renderGeometry.uniqueName)===b[c].renderGeometry)};b.prototype.getContent=
function(){return this._content};b.prototype.getProjectionMatrix=function(a,d,b,c,e){d=f.fovx2fovy(d,a[2],a[3]);h.mat4d.perspective(180*d/Math.PI,a[2]/a[3],b,c,e)};Object.defineProperty(b.prototype,"renderPlugins",{get:function(){return this._renderer.renderPlugins},enumerable:!0,configurable:!0});b.prototype.resetNeedsRender=function(){this._needsRender=!1;this._renderer.resetNeedsRender()};b.prototype.needsRender=function(){return this._needsRender||this._renderer.needsRender()};b.prototype.setNeedsRender=
function(){this._needsRender=!0};b.prototype.render=function(a){var d=a.camera,b=a.fbo,c=a.lightDirection,e=d.viewport;this._renderer.prepareRender(d);if(this._helpers.shadowMap.enabled){l.ENABLE_PROFILE_DEPTH_RANGE&&k.begin("depthRange");var g=this.computeDepthRange(d);l.ENABLE_PROFILE_DEPTH_RANGE&&k.end("depthRange");this._helpers.shadowMap.prepare(d,c,this._content,g);c=this._helpers.shadowMap.getCascades();for(g=0;g<c.length;++g){var f=c[g];f.camera.setGLViewport(this._rctx);a.camera=f.camera;
this._renderer.renderGeometryPass(u.MATERIAL_DEPTH_SHADOWMAP,a,null,null,this._helpers.slice)}a.camera=d;this._helpers.shadowMap.finish(b);d.setGLViewport(this._rctx)}this._helpers.shadowMap.bindAll(this._programRep);this._renderer.renderAuxiliaryBuffers(a,this._helpers);this._renderer.render(a,this._helpers);this._drawShadowMapDebugQuad&&this._helpers.shadowMap.enabled&&(a=h.mat4d.ortho(e[0],e[2],e[1],e[3],-1,1),this._helpers.shadowMap.drawDebugQuad(a));this._drawSSAOMapDebugQuad&&this._helpers.ssao.enabled&&
(a=h.mat4d.ortho(e[0],e[2],e[1],e[3],-1,1),this._helpers.ssao.drawQuad(a))};b.prototype.getEdgeView=function(){return this._renderer.edgeView};b.prototype.computeDepthRange=function(a){var b=n.depthRangeFromScene(a,this._content,this._stage.getLayers());m.union(b,this.renderPlugins.queryDepthRange(a));b.near=Math.max(a.near,b.near);b.far=Math.min(a.far,b.far);return b};return b}()});