// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.31/esri/copyright.txt for details.
//>>built
define("esri/sniff",["dojo/_base/sniff","dojo/global","./kernel"],function(a,b,e){var f=a("ff"),h=a("ie"),p=void 0===h&&7<=a("trident"),q=a("edge"),l=a("webkit"),k=a("opera"),n=a("chrome"),r=a("safari"),c=navigator.userAgent,g;(g=c.match(/(iPhone|iPad|CPU)\s+OS\s+(\d+\_\d+)/i))&&a.add("esri-iphone",parseFloat(g[2].replace("_",".")));(g=c.match(/Android\s+(\d+(\.\d+)*)/i))&&a.add("esri-android",parseFloat(g[1]));(g=c.match(/Fennec\/(\d+\.\d+)/i))&&a.add("esri-fennec",parseFloat(g[1]));0<=c.indexOf("BlackBerry")&&
0<=c.indexOf("WebKit")&&a.add("esri-blackberry",1);a.add("esri-touch",a("esri-iphone")||a("esri-android")||a("esri-blackberry")||6<=a("esri-fennec")||(f||l)&&(document.createTouch||"ontouchstart"in b||b.TouchEvent&&0<navigator.maxTouchPoints)?!0:!1);(g=c.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry|Opera Mini|IEMobile/i))&&a.add("esri-mobile",!!g);a.add("esri-pointer",!f&&(navigator.pointerEnabled||navigator.msPointerEnabled||!!window.PointerEvent));e._getDOMAccessor=function(a){var d="";f?d=
"Moz":l?d="Webkit":h?d="ms":k&&(d="O");return d+a.charAt(0).toUpperCase()+a.substr(1)};a.add("esri-phonegap",!!b.cordova);a.add("esri-cors",a("esri-phonegap")||b.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest);a.add("esri-file-upload",b.FormData&&b.FileList?!0:!1);a.add("esri-script-sandbox",function(){return"MessageChannel"in b&&"HTMLIFrameElement"in b&&"sandbox"in HTMLIFrameElement.prototype});a.add("esri-secure-context",function(){if("isSecureContext"in b)return b.isSecureContext;if(b.location&&
b.location.origin)return 0===b.location.origin.indexOf("https:")});a.add("esri-wasm","WebAssembly"in b);a.add("esri-workers",b.Worker?!0:!1);a.add("esri-featurelayer-webgl",!1);if(c=a("esri-featurelayer-webgl")){var m=a("esri-mobile");g=m?1:2;m=m?1:3;"object"===typeof c?(c.maxDrillLevel=null==c.maxDrillLevel?g:c.maxDrillLevel,c.maxRecordCountFactor=null==c.maxRecordCountFactor?m:c.maxRecordCountFactor,c.enablePBFQuery=null==c.enablePBFQuery?!0:c.enablePBFQuery):a.add("esri-featurelayer-webgl",{maxDrillLevel:g,
maxRecordCountFactor:m,enablePBFQuery:!0},null,!0)}a.add("esri-featurelayer-webgl-labeling",!1);a.add("esri-pbf",!h||10<=h);a.add("esri-featurelayer-pbf",!0);a.add("esri-transforms",p||q||9<=h||3.5<=f||4<=n||3.1<=r||10.5<=k||3.2<=a("esri-iphone")||2.1<=a("esri-android"));a.add("esri-transitions",p||q||10<=h||4<=f||4<=n||3.1<=r||10.5<=k||3.2<=a("esri-iphone")||2.1<=a("esri-android"));a.add("esri-transforms3d",p||q||10<=f||12<=n||4<=r||3.2<=a("esri-iphone")||3<=a("esri-android"));a.add("esri-url-encodes-apostrophe",
function(){if(!b.document)return!1;var a=b.document.createElement("a");a.href="?'";return-1<a.href.indexOf("?%27")});3>a("esri-android")&&(a.add("esri-transforms",!1,!1,!0),a.add("esri-transitions",!1,!1,!0),a.add("esri-transforms3d",!1,!1,!0));a.add("esri-will-change",a("esri-transforms")&&(52<=n||11.1<=r));e._css=function(b){var d=a("esri-transforms3d");void 0!==b&&null!==b?d=b:d&&(n||r&&!a("esri-iphone"))&&(d=!1);var c=d?"translate3d(":"translate(",e=d?n?",-1px)":",0px)":")",g=d?"scale3d(":"scale(",
m=d?",1)":")",p=d?"rotate3d(0,0,1,":"rotate(",q=d?"matrix3d(":"matrix(",t=d?",0,0,":",",u=d?",0,0,0,0,1,0,":",",v=d?",0,1)":")";return{names:{transition:l&&"-webkit-transition"||f&&"MozTransition"||k&&"OTransition"||h&&"msTransition"||"transition",transform:l&&"-webkit-transform"||f&&"MozTransform"||k&&"OTransform"||h&&"msTransform"||"transform",transformName:l&&"-webkit-transform"||f&&"-moz-transform"||k&&"-o-transform"||h&&"-ms-transform"||"transform",origin:l&&"-webkit-transform-origin"||f&&"MozTransformOrigin"||
k&&"OTransformOrigin"||h&&"msTransformOrigin"||"transformOrigin",endEvent:l&&"webkitTransitionEnd"||f&&"transitionend"||k&&"oTransitionEnd"||h&&"MSTransitionEnd"||"transitionend"},translate:function(a,b){return c+a+"px,"+b+"px"+e},scale:function(a){return g+a+","+a+m},rotate:function(a){return p+a+"deg)"},matrix:function(a){return q+a.xx+","+a.xy+t+a.yx+","+a.yy+u+a.dx.toFixed(10)+(f&&59>=f?"px,":",")+a.dy.toFixed(10)+(f&&59>=f?"px":"")+v},getScaleFromMatrix:function(a){if(!a)return 1;a=a.toLowerCase();
var b=-1<a.indexOf("matrix3d")?"matrix3d(":"matrix(";return Number(a.substring(b.length,a.indexOf(",")))}}};a("extend-esri")&&(e.isiPhone=a("esri-iphone"),e.isAndroid=a("esri-android"),e.isFennec=a("esri-fennec"),e.isBlackBerry=a("esri-blackberry"),e.isTouchEnabled=a("esri-touch"),e.isPointerEnabled=a("esri-pointer"),e._hasCors=a("esri-cors"),e._hasFileUpload=a("esri-file-upload"),e._hasTransforms=a("esri-transforms"),e._hasTransitions=a("esri-transitions"),e._has3DTransforms=a("esri-transforms3d"));
return a});