// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ./tsSupport/assignHelper dojo/io-query dojo/_base/url ../config ./Error ./global ./lang ./Logger".split(" "),function(ca,e,P,l,m,Q,R,S,w,T){function g(a){var b={path:null,query:null},c=new m(a),d=a.indexOf("?");null===c.query?b.path=a:(b.path=a.substring(0,d),b.query=l.queryToObject(c.query));c.fragment&&(b.hash=c.fragment,null===c.query&&(b.path=b.path.substring(0,b.path.length-(c.fragment.length+1))));return b}function x(a){var b=a.indexOf("?");-1!==b?(r.path=a.slice(0,b),
r.query=a.slice(b+1)):(r.path=a,r.query=null);return r}function D(a){a=x(a).path;a&&"/"===a[a.length-1]||(a+="/");a=y(a,!0);return a=a.toLowerCase()}function t(a){var b=n.proxyRules;a=D(a);for(var c=0;c<b.length;c++)if(0===a.indexOf(b[c].urlPrefix))return b[c]}function E(a){a=p(a);var b=a.indexOf("/sharing");return 0<b?a.substring(0,b):a.replace(/\/+$/,"")}function z(a,b,c){void 0===c&&(c=!1);a=A(a);b=A(b);return c||a.scheme===b.scheme?a.host.toLowerCase()===b.host.toLowerCase()&&a.port===b.port:
!1}function q(a,b,c){void 0===b&&(b=e.appBaseUrl);if(f(a))return c&&c.preserveProtocolRelative?a:"http"===e.appUrl.scheme&&e.appUrl.authority===F(a).slice(2)?"http:"+a:"https:"+a;if(u(a))return a;c=G;if("/"===a[0]){var d=b.indexOf("//"),d=b.indexOf("/",d+2);b=-1===d?b:b.slice(0,d)}return c(b,a)}function H(a,b,c){void 0===b&&(b=e.appBaseUrl);if(!k(a))return a;var d=p(a),h=d.toLowerCase();b=p(b).toLowerCase().replace(/\/+$/,"");if((c=c?p(c).toLowerCase().replace(/\/+$/,""):null)&&0!==b.indexOf(c))return a;
for(var I=function(a,b,c){c=a.indexOf(b,c);return-1===c?a.length:c},f=I(h,"/",h.indexOf("//")+2),g=-1;h.slice(0,f+1)===b.slice(0,f)+"/";){g=f+1;if(f===h.length)break;f=I(h,"/",f+1)}if(-1===g||c&&g<c.length)return a;a=d.slice(g);d=b.slice(g-1).replace(/[^/]+/g,"").length;if(0<d)for(h=0;h<d;h++)a="../"+a;else a="./"+a;return a}function p(a){a=a.trim();a=q(a);if(/^https?:\/\//i.test(a)){var b=x(a);a=b.path.replace(/\/{2,}/g,"/");a=a.replace("/","//");b.query&&(a+="?"+b.query)}a=a.replace(/^(https?:\/\/)(arcgis\.com)/i,
"$1www.$2");return a=U(a)}function G(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];if(a&&a.length){b=[];if(k(a[0])){var c=a[0],d=c.indexOf("//");b.push(c.slice(0,d+1));V.test(a[0])&&(b[0]+="/");a[0]=c.slice(d+2)}else"/"===a[0][0]&&b.push("");a=a.reduce(function(a,b){return b?a.concat(b.split("/")):a},[]);for(c=0;c<a.length;c++)d=a[c],".."===d&&0<b.length?b.pop():!d||"."===d&&0!==b.length||b.push(d);return b.join("/")}}function F(a){if(J(a)||K(a))return null;var b=a.indexOf("://");if(-1===
b&&f(a))b=2;else if(-1!==b)b+=3;else return null;b=a.indexOf("/",b);return-1===b?a:a.slice(0,b)}function k(a){return f(a)||u(a)}function J(a){return"blob:"===a.slice(0,5)}function K(a){return"data:"===a.slice(0,5)}function L(a){return(a=a.match(W))?{mediaType:a[1],isBase64:!!a[2],data:a[3]}:null}function f(a){return a&&"/"===a[0]&&"/"===a[1]}function u(a){return M.test(a)}function X(a){return N.test(a)||"http"===e.appUrl.scheme&&f(a)}function B(a){return f(a)?"https:"+a:a.replace(N,"https:")}function C(){return"https"===
e.appUrl.scheme}function y(a,b){void 0===b&&(b=!1);if(f(a))return a.slice(2);a=a.replace(M,"");b&&1<a.length&&"/"===a[0]&&"/"===a[1]&&(a=a.slice(2));return a}function U(a){var b=n.httpsDomains;if(!X(a))return a;var c=a.indexOf("/",7),d;d=-1===c?a:a.slice(0,c);d=d.toLowerCase().slice(7);if(Y.test(d))if(w.endsWith(d,":80"))d=d.slice(0,-3),a=a.replace(":80","");else return a;if("http"===e.appUrl.scheme&&d===e.appUrl.authority&&!Z.test(a))return a;if(C()&&d===e.appUrl.authority||b&&b.some(function(a){return d===
a||w.endsWith(d,"."+a)})||C()&&!t(a))a=B(a);return a}function v(a,b,c){if(!(b&&c&&a&&k(a)))return a;var d=a.indexOf("//"),e=a.indexOf("/",d+2),f=a.indexOf(":",d+2),e=Math.min(0>e?a.length:e,0>f?a.length:f);if(a.slice(d+2,e).toLowerCase()!==b.toLowerCase())return a;b=a.slice(0,d+2);a=a.slice(e);return""+b+c+a}function A(a){if("string"===typeof a)return new m(q(a));a.scheme||(a.scheme=e.appUrl.scheme);return a}Object.defineProperty(e,"__esModule",{value:!0});var aa=T.getLogger("esri.core.urlUtils"),
n=Q.request,M=/^\s*[a-z][a-z0-9-+.]*:(?![0-9])/i,N=/^\s*http:/i,O=/^\s*https:/i,V=/^\s*file:/i,Y=/:\d+$/,Z=/^https?:\/\/[^/]+\.arcgis.com\/sharing(\/|$)/i;e.appUrl=new m(S.location);e.trustedServersUrlCache={};e.appBaseUrl=function(){var a=e.appUrl.path,a=a.substring(0,a.lastIndexOf(a.split("/")[a.split("/").length-1]));return""+(e.appUrl.scheme+"://"+e.appUrl.host+(null!=e.appUrl.port?":"+e.appUrl.port:""))+a}();e.urlToObject=g;e.getProxyUrl=function(a){void 0===a&&(a=!1);var b,c=n.proxyUrl;if("string"===
typeof a){if(b=a,b=O.test(b)||"https"===e.appUrl.scheme&&f(b),a=t(a))c=a.proxyUrl}else b=!!a;if(!c)throw aa.warn("esri/config: esriConfig.request.proxyUrl is not set."),new R("urlutils:proxy-not-set","esri/config: esriConfig.request.proxyUrl is not set.");b&&C()&&(c=B(c));return g(c)};e.addProxy=function(a){var b=t(a),c,d;b&&(d=x(b.proxyUrl),c=d.path,d=d.query?l.queryToObject(d.query):null);c&&(b=g(a),a=c+"?"+b.path,(c=l.objectToQuery(P({},d,b.query)))&&(a=a+"?"+c));return a};var r={path:"",query:""};
e.addProxyRule=function(a){a={proxyUrl:a.proxyUrl,urlPrefix:D(a.urlPrefix)};for(var b=n.proxyRules,c=a.urlPrefix,d=b.length,e=0;e<b.length;e++){var f=b[e].urlPrefix;if(0===c.indexOf(f)){if(c.length===f.length)return-1;d=e;break}0===f.indexOf(c)&&(d=e+1)}b.splice(d,0,a);return d};e.getProxyRule=t;e.hasSamePortal=function(a,b){a=E(a);b=E(b);return y(a)===y(b)};e.getInterceptor=function(a){var b=function(b){return null==b||b instanceof RegExp&&b.test(a)||"string"===typeof b&&w.startsWith(a,b)},c=n.interceptors;
if(c)for(var d=0;d<c.length;d++){var e=c[d];if(Array.isArray(e.urls)){if(e.urls.some(b))return e}else if(b(e.urls))return e}return null};e.hasSameOrigin=z;e.isTrustedServer=function(a){if("string"===typeof a)if(k(a))a=A(a);else return!0;for(var b=n.trustedServers||[],c=0;c<b.length;c++){var d;d=b[c];e.trustedServersUrlCache[d]||(u(d)||f(d)?e.trustedServersUrlCache[d]=[new m(q(d))]:e.trustedServersUrlCache[d]=[new m("http://"+d),new m("https://"+d)]);d=e.trustedServersUrlCache[d];for(var g=0;g<d.length;g++)if(z(a,
d[g]))return!0}return!1};e.makeAbsolute=q;e.makeRelative=H;e.normalize=p;e.join=G;e.getOrigin=F;e.isAbsolute=k;e.isBlobProtocol=J;e.isDataProtocol=K;e.dataToArrayBuffer=function(a){a=L(a);if(!a||!a.isBase64)return null;a=atob(a.data);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b.buffer};var W=/^data:(.*?)(;base64)?,(.*)$/;e.dataComponents=L;e.makeData=function(a){return a.isBase64?"data:"+a.mediaType+";base64,"+a.data:"data:"+a.mediaType+","+a.data};e.isProtocolRelative=
f;e.hasProtocol=u;e.toHTTP=function(a){return f(a)?"http:"+a:a.replace(O,"http:")};e.toHTTPS=B;e.removeFile=function(a){var b=0;if(k(a)){var c=a.indexOf("//");-1!==c&&(b=c+2)}c=a.lastIndexOf("/");return c<b?a:a.slice(0,c+1)};e.removeTrailingSlash=function(a){return a.replace(/\/+$/,"")};e.changeDomain=v;e.read=function(a,b){var c=b&&b.url&&b.url.path;a&&c&&(a=q(a,c,{preserveProtocolRelative:!0}));(b=b&&b.portal)&&!b.isPortal&&b.urlKey&&b.customBaseUrl?(c=b.urlKey+"."+b.customBaseUrl,b=z(e.appUrl,
e.appUrl.scheme+"://"+c)?v(a,b.portalHostname,c):v(a,c,b.portalHostname)):b=a;return b};e.write=function(a,b){if(!a)return a;!k(a)&&b&&b.blockedRelativeUrls&&b.blockedRelativeUrls.push(a);var c=q(a);if(b){var d=b.verifyItemRelativeUrls&&b.verifyItemRelativeUrls.rootPath||b.url&&b.url.path;d&&(c=H(c,d,d),c!==a&&b.verifyItemRelativeUrls&&b.verifyItemRelativeUrls.writtenUrls.push(c))}a=c;c=(b=b&&b.portal)&&!b.isPortal&&b.urlKey&&b.customBaseUrl?v(a,b.urlKey+"."+b.customBaseUrl,b.portalHostname):a;return c};
e.writeOperationalLayerUrl=function(a,b){a&&f(a)&&(a="https:"+a);b.url=a?p(a):a};e.isSVG=function(a){return ba.test(a)};e.removeQueryParameters=function(a,b){a=g(a);var c=Object.keys(a.query||{});0<c.length&&b&&b.warn("removeQueryParameters()","Url query parameters are not supported, the following parameters have been removed: "+c.join(", ")+".");return a.path};e.addQueryParameter=function(a,b,c){a=g(a);var d=a.query||{};d[b]=c;return a.path+"?"+l.objectToQuery(d)};e.addQueryParameters=function(a,
b){a=g(a);var c=a.query||{},d;for(d in b)c[d]=b[d];return(b=l.objectToQuery(c))?a.path+"?"+b:a.path};e.removeQueryParameter=function(a,b){var c=g(a),d=c.path,c=c.query;if(!c)return a;delete c[b];return(a=l.objectToQuery(c))?d+"?"+a:d};var ba=/(^data:image\/svg|\.svg$)/i});