// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../core/tsSupport/assignHelper ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/date/locale ../moment ../core/accessorSupport/decorators ../layers/support/domains ../layers/support/fieldUtils ./Widget ./FeatureForm/FeatureFormViewModel ./support/widget".split(" "),function(x,y,k,r,h,n,l,g,t,u,v,w,d){var p={datePattern:"M/d/y",timePattern:"h:mm:ss a"};return function(q){function c(a){a=q.call(this)||this;a._featureChanged=!1;a._activeDateEdit=null;
a.feature=null;a.fieldConfig=null;a.layer=null;a.strict=null;a.viewModel=new w;a._handleFormKeyDown=a._handleFormKeyDown.bind(a);a._handleInputBlur=a._handleInputBlur.bind(a);a._handleNumberInputMouseDown=a._handleNumberInputMouseDown.bind(a);a._handleInputKeyDown=a._handleInputKeyDown.bind(a);a._handleOptionChange=a._handleOptionChange.bind(a);a._handleSubmit=a._handleSubmit.bind(a);a._afterScrollerCreateOrUpdate=a._afterScrollerCreateOrUpdate.bind(a);return a}r(c,q);c.prototype.postInitialize=function(){var a=
this;this.own(this.watch("feature",function(){return a._featureChanged=!0}))};c.prototype.getValues=function(){return null};c.prototype.submit=function(){return null};c.prototype.render=function(){var a=this.viewModel.state;return d.tsx("div",{class:this.classes("esri-feature-form","esri-widget")},"ready"===a?this.renderForm():null)};c.prototype.renderForm=function(){return d.tsx("form",{class:"esri-feature-form__form",novalidate:!0,onsubmit:this._handleSubmit,onkeydown:this._handleFormKeyDown},this.renderFields())};
c.prototype.renderFields=function(){var a=this,b=this.viewModel,e=b.layer;return b.inputFields.map(function(b){return d.tsx("label",{key:e.id+"-"+b.name,class:"esri-feature-form__label"},[b.label,"unsupported"!==b.type?a.renderInputField(b):a.renderUnsupportedField(b),a.renderAuxiliaryText(b)])})};c.prototype.renderInputField=function(a){var b=a.domain,e=a.editable,c=a.type,f=this.viewModel.getValue(a.name),e=!e,m=this.getCommonInputProps(a);return b&&"coded-value"===b.type&&!e?this.renderSelectInputField(f,
b.codedValues.map(function(a){return{value:a.code,name:a.name}}),m):"text"===c&&"text-area"===a.editorType||"rich-text"===a.editorType?d.tsx("textarea",k({},m)):"date"===c?this.renderDateInputField(f,m):d.tsx("input",k({type:"text"===c?"text":"number"},m))};c.prototype.renderDateInputField=function(a,b){var e=this._formatDate(0),c=e.date,e=e.time,f=this.id+"-"+b.key,m=f+"-date",f=f+"-time",g=b["data-field"];return d.tsx("div",{key:b.key+"-date",class:"esri-feature-form__date-input-container"},d.tsx("div",
{class:"esri-feature-form__date-input-part"},d.tsx("input",k({"aria-label":g.label,"aria-describedby":m,type:"text"},b,{"data-date-part":"date",class:this.classes(b.class,"esri-feature-form__input--date"),value:this._formatDate(a).date})),d.tsx("div",{class:"esri-feature-form__date-format-hint",id:m},c)),d.tsx("div",{class:"esri-feature-form__date-input-part"},d.tsx("input",k({"aria-describedby":f,"aria-label":g.label,type:"text"},b,{"data-date-part":"time",class:this.classes(b.class,"esri-feature-form__input--time"),
value:this._formatDate(a).time})),d.tsx("div",{class:"esri-feature-form__date-format-hint",id:f},e)))};c.prototype.renderUnsupportedField=function(a){a=this.viewModel.getValue(a.name);return d.tsx("input",{class:this.classes("esri-input","esri-feature-form__input","esri-feature-form__input--disabled"),disabled:!0,type:"text",value:""+a})};c.prototype.renderSelectInputField=function(a,b,e){var c=!1;b=b.map(function(b){b.value===a&&(c=!0);return d.tsx("option",{value:""+b.value,key:b.name},b.name)});
null==a||""===a||c||b.unshift(d.tsx("option",{value:""+a,key:"outlier-option"},a));var f=e["data-field"];f.required||null!=f.value||b.unshift(d.tsx("option",{value:"",key:"empty-option"}));return d.tsx("select",k({},e,{class:this.classes(e.class,"esri-select"),onchange:this._handleOptionChange}),b)};c.prototype.renderAuxiliaryText=function(a){if(!a.valid)return d.tsx("div",{key:"error-message"},d.tsx("span",{class:this.classes("esri-feature-form__input-icon--invalid","esri-icon-notice-triangle")}),
d.tsx("div",{class:"esri-feature-form__field-error-message"},a.errorMessage));if(a.valid&&a.description)return d.tsx("div",{key:"description"},a.description)};c.prototype.getCommonInputProps=function(a){var b=a.editable,e=a.name,c=a.required,f=a.maxLength,d=a.hint,g=a.type,h=a.valid,l=this.viewModel.getValue(e),b=!b;return k({afterCreate:this._afterScrollerCreateOrUpdate,afterUpdate:this._afterScrollerCreateOrUpdate,"aria-invalid":h?"false":"true",class:this.classes("esri-input","esri-feature-form__input",
b?"esri-feature-form__input--disabled":null,h?null:"esri-feature-form__input--invalid"),key:e,maxlength:-1<f?""+f:""},this._getNumberFieldConstraints(a),{disabled:b,value:null==l?"":""+l,"data-field":a,onblur:this._handleInputBlur,onkeydown:this._handleInputKeyDown,onmousedown:"number"===g?this._handleNumberInputMouseDown:null,required:c,title:d})};c.prototype._handleNumberInputMouseDown=function(a){a=a.target;a.disabled||a.focus();this.scheduleRender()};c.prototype._getNumberFieldConstraints=function(a){return(a=
t.getDomainRange(a.domain)||u.getFieldRange(a.field))&&a.max!==Number.MAX_VALUE&&a.min!==Number.MIN_VALUE?a:{min:null,max:null}};c.prototype._afterScrollerCreateOrUpdate=function(a){var b=a["data-field"];this._featureChanged&&b.editable&&(a.focus(),this._featureChanged=!1)};c.prototype._handleInputBlur=function(a){var b,e=a.target,c=e["data-field"],f=(a=a.relatedTarget)&&a["data-field"];if("date"===c.type){var d=e.getAttribute("data-date-part");this._activeDateEdit=k({},this._activeDateEdit,(b={},
b[d]={value:e.value,input:e},b))}f&&"date"===c.type&&"date"===f.type&&c.field===f.field?""!==e.value&&""===a.value&&(d=a.getAttribute("data-date-part"),a.value=this._formatDate(Date.now())[d]):(this._activeDateEdit?(e=this._activeDateEdit,b=e.date,e=e.time,a=this._getDateEditValue(c,"date"),c=this._getDateEditValue(c,"time"),f=""===a||""===c,b&&(b=b.input,b.value=f?"":a,this._updateFieldValue(b)),e&&(b=e.input,b.value=f?"":c,this._updateFieldValue(b)),this._activeDateEdit=null):this._updateFieldValue(e),
this.scheduleRender())};c.prototype._getDateEditValue=function(a,b){var e=this._activeDateEdit[b];if(e)return""===e.value?"":(e=this._parseDate(e.value,b))?this._formatDate(e.getTime())[b]:this._formatDate(a.value)[b]};c.prototype._handleInputKeyDown=function(a){var b=a.key,e=a.altKey,c=a.ctrlKey,f=a.metaKey;if("Enter"!==b){var d=a.target["data-field"].field.type,g="single"===d||"double"===d;"integer"!==d&&"small-integer"!==d&&!g||e||c||f||1!==b.length||(e=Number(b),c=["-","+"],f=["e","."],g=g?c.concat(f):
c,isNaN(e)&&-1===g.indexOf(b)&&a.preventDefault())}else this._updateFieldValue(a.target),this.scheduleRender()};c.prototype._updateFieldValue=function(a){this.viewModel.setValue(a["data-field"].name,this._parseValue(a))};c.prototype._parseValue=function(a){var b=a["data-field"],c=a.value,d=b.type;if(!b.required&&""===c)return null;if("number"===d)return parseFloat(c);if("date"===d){if(!c)return null;a=a.getAttribute("data-date-part");d=Number(c);if(!isNaN(d))return d;c=this._parseDate(c,a);if(!c)return null;
var c=l(c),f=b.domain,g=l(),d=g;f&&"range"===f.type&&(f=l(f.maxValue),g.isAfter(f)||(d=f));b=this.viewModel.getValue(b.name);b=l(null!=b?b:d);"date"===a?(c.hour(b.hour()),c.minutes(b.minutes()),c.seconds(b.seconds())):(c.date(b.date()),c.month(b.month()),c.year(b.year()));return c.valueOf()}return c};c.prototype._handleOptionChange=function(a){this._updateFieldValue(a.target);this.scheduleRender()};c.prototype._handleSubmit=function(a){a.preventDefault()};c.prototype._handleFormKeyDown=function(a){"Enter"===
a.key&&this.viewModel.submit()};c.prototype._formatDate=function(a){if(null==a)return{date:"",time:""};a=new Date(a);return{date:n.format(a,k({selector:"date"},p)),time:n.format(a,k({selector:"time"},p))}};c.prototype._parseDate=function(a,b){return null==a||""===a?null:n.parse(a,k({selector:b},p))};h([g.aliasOf("viewModel.feature")],c.prototype,"feature",void 0);h([g.aliasOf("viewModel.fieldConfig")],c.prototype,"fieldConfig",void 0);h([g.aliasOf("viewModel.layer")],c.prototype,"layer",void 0);h([g.aliasOf("viewModel.strict")],
c.prototype,"strict",void 0);h([g.property(),d.renderable(["viewModel.inputFields","viewModel.state"]),d.vmEvent(["value-change","submit"])],c.prototype,"viewModel",void 0);h([g.aliasOf("viewModel.getValues")],c.prototype,"getValues",null);h([g.aliasOf("viewModel.submit")],c.prototype,"submit",null);return c=h([g.subclass("esri.widgets.Form")],c)}(g.declared(v))});