// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
require({cache:{"esri/widgets/LayerList/LayerListViewModel":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/Collection ../../core/Evented ../../core/Handles ../../core/watchUtils ../../core/accessorSupport/decorators ./ListItem ./support/layerListUtils".split(" "),function(r,m,q,e,p,f,u,l,g,k,n,h){var t=f.ofType(n);return function(b){function c(a){a=b.call(this)||this;a._handles=new l;a.listItemCreatedFunction=
null;a.operationalItems=new t;a.view=null;return a}q(c,b);c.prototype.initialize=function(){var a=this;this._handles.add(g.init(this,"view",function(){return a._viewHandles()}),"view")};c.prototype.destroy=function(){this._handles.destroy();this.view=this._handles=null;this.operationalItems.removeAll()};Object.defineProperty(c.prototype,"state",{get:function(){var a=this.get("view");return this.get("view.ready")?"ready":a?"loading":"disabled"},enumerable:!0,configurable:!0});c.prototype.triggerAction=
function(a,d){a&&this.emit("trigger-action",{action:a,item:d})};c.prototype._createLayerViewHandles=function(a){var d=this,c=this._handles;c.remove("layer-views");this._compileList();a&&c.add(a.on("change",function(){return d._compileList()}),"layer-views")};c.prototype._createMapLayerHandles=function(a){var d=this,c=this._handles;c.remove("map-layers");this._compileList();a&&c.add(a.on("change",function(){return d._compileList()}),"map-layers")};c.prototype._watchItemProperties=function(a){var d=
this;this._handles.add([a.children.on("change",function(){d._modifyListItemChildren(a.children)})],"children-change-"+a.uid)};c.prototype._modifyListItemChildren=function(a){var d=this;a.forEach(function(a){return d._modifyListItem(a)})};c.prototype._modifyListItem=function(a){"function"===typeof this.listItemCreatedFunction&&this.listItemCreatedFunction.call(null,{item:a});this._modifyListItemChildren(a.children)};c.prototype._createListItem=function(a){a=new n({layer:a,view:this.view});this._watchItemProperties(a);
return a};c.prototype._removeAllItems=function(){var a=this._handles,d=this.operationalItems;d.forEach(function(d){a.remove("children-change-"+d.uid)});d.removeAll()};c.prototype._getViewableLayers=function(a){if(a)return a.filter(function(a){return"hide"!==h.findLayerListMode(a)})};c.prototype._watchLayersListMode=function(a){var d=this,c=this._handles;c.remove("layer-list-mode");a&&a.forEach(function(a){c.add(g.watch(a,"listMode",function(){return d._compileList()}),"layer-list-mode")})};c.prototype._compileList=
function(){var a=this.get("view.map.layers");this._watchLayersListMode(a);(a=this._getViewableLayers(a))&&a.length?(this._createNewItems(a),this._modifyOrRemoveItems(a),this._sortItems(a)):this._removeAllItems()};c.prototype._createNewItems=function(a){var d=this,c=this.operationalItems;a.forEach(function(a){c.find(function(d){return d.layer===a})||c.add(d._createListItem(a))})};c.prototype._modifyOrRemoveItems=function(a){var d=this,c=this._handles,b=this.operationalItems;b.forEach(function(w){w&&
(a.find(function(a){return w.layer===a})?d._modifyListItem(w):(c.remove("children-change-"+w.uid),b.remove(w)))})};c.prototype._sortItems=function(a){this.operationalItems.sort(function(d,c){d=a.indexOf(d.layer);c=a.indexOf(c.layer);return d>c?-1:d<c?1:0})};c.prototype._viewHandles=function(){var a=this,d=this._handles,c=this.view;d.remove(["map-layers","layer-views","view-layers"]);this._compileList();c&&d.add([g.init(this,"view.map.layers",function(d){return a._createMapLayerHandles(d)}),g.init(this,
"view.layerViews",function(d){return a._createLayerViewHandles(d)}),g.init(this,"listItemCreatedFunction",function(){return a._compileList()})],"view-layers")};e([k.property()],c.prototype,"listItemCreatedFunction",void 0);e([k.property({type:t})],c.prototype,"operationalItems",void 0);e([k.property({dependsOn:["view.ready"],readOnly:!0})],c.prototype,"state",null);e([k.property()],c.prototype,"view",void 0);e([k.property()],c.prototype,"triggerAction",null);return c=e([k.subclass("esri.widgets.LayerList.LayerListViewModel")],
c)}(k.declared(p,u))})},"esri/widgets/LayerList/ListItem":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/Collection ../../core/Handles ../../core/Identifiable ../../core/watchUtils ../../core/accessorSupport/decorators ../../layers/support/Sublayer ../../support/actions/ActionBase ../../support/actions/ActionButton ../../support/actions/ActionSlider ../../support/actions/ActionToggle ./ListItemPanel ./support/layerListUtils".split(" "),
function(r,m,q,e,p,f,u,l,g,k,n,h,t,b,c,a,d){r=f.ofType({key:"type",defaultKeyValue:"button",base:h,typeMap:{button:t,toggle:c,slider:b}});var z=f.ofType(r);return function(c){function b(a){a=c.call(this)||this;a._handles=new u;a._layerViewPromise=null;a.actionsSections=new z;a.actionsOpen=!1;a.children=new (f.ofType(h));a.error=null;a.layer=null;a.layerView=null;a.open=!1;a.panel=null;a.parent=null;a.view=null;a.visible=null;return a}q(b,c);h=b;b.prototype.initialize=function(){var a=this;this._handles.add([g.init(this,
"layer",function(d){return a._watchLayerProperties(d)}),g.init(this,"view",function(d){return a._updateChildren(d)}),g.init(this,"panel",function(d){return a._setListItemOnPanel(d)}),g.init(this,["layer","view"],function(){return a._getLayerView()})])};b.prototype.destroy=function(){this._layerViewPromise&&this._layerViewPromise.cancel();this._layerViewPromise=null;this._handles.destroy();this.view=this._handles=null};b.prototype.castPanel=function(d){this.get("panel.open")&&!d.hasOwnProperty("open")&&
(d.open=!0);return d?new a(d):null};Object.defineProperty(b.prototype,"title",{get:function(){var a=this.get("layer.layer");return(!a||a&&this.get("layer.layer.loaded"))&&this.get("layer.title")||""},set:function(a){void 0===a?this._clearOverride("title"):this._override("title",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"updating",{get:function(){var a=this.layerView;return a?a.updating:this._isLayerUpdating(this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,
"visibleAtCurrentScale",{get:function(){return!d.isLayerOutsideScaleRange(this.layer,this.get("view.scale"))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"visibilityMode",{get:function(){return d.findLayerVisibilityMode(this.layer)||"independent"},enumerable:!0,configurable:!0});b.prototype.clone=function(){return new h({actionsSections:this.actionsSections.clone(),actionsOpen:this.actionsOpen,children:this.children.clone(),layer:this.layer,open:this.open,panel:this.panel,title:this.title,
view:this.view,visible:this.visible})};b.prototype._setListItemOnPanel=function(a){a&&(a.listItem=this)};b.prototype._updateChildren=function(a){var d=this.children;d&&d.forEach(function(d){return d.view=a})};b.prototype._addChildren=function(a){var c=this;this.children.removeAll();if(a){var b=[];a.forEach(function(a){d.canDisplayLayer(a)&&(a=new h({layer:a,parent:c,view:c.view}),b.unshift(a))});this.children.addMany(b)}};b.prototype._watchSublayerChanges=function(a){var d=this;a&&this._handles.add(a.on("change",
function(){d._addChildren(a)}),"layer")};b.prototype._initializeChildLayers=function(a){this._addChildren(a);this._watchSublayerChanges(a)};b.prototype._watchLayerProperties=function(a){var c=this;if(this._handles&&(this._handles.remove("layer"),a)){var b=d.getNormalizedChildLayerProperty(a);b&&this._handles.add(g.init(a,b,function(){a.hasOwnProperty(b)&&c._initializeChildLayers(a[b])}),"layer")}};b.prototype._getLayerView=function(){var a=this,d=this.layer,c=this.view;if(d&&c){var b=this._layerViewPromise=
c.whenLayerView(d);b.then(function(d){b===a._layerViewPromise&&(a._layerViewPromise=null,a._set("layerView",d))}).catch(function(d){b===a._layerViewPromise&&(a._layerViewPromise=null)})}};b.prototype._isLayerUpdating=function(a){return a instanceof n?!1:a&&"loading"===a.loadStatus};var h;e([k.property({type:z})],b.prototype,"actionsSections",void 0);e([k.property()],b.prototype,"actionsOpen",void 0);e([k.property({type:f})],b.prototype,"children",void 0);e([k.aliasOf("layer.loadError")],b.prototype,
"error",void 0);e([k.property()],b.prototype,"layer",void 0);e([k.property({readOnly:!0})],b.prototype,"layerView",void 0);e([k.property()],b.prototype,"open",void 0);e([k.property({type:a})],b.prototype,"panel",void 0);e([k.cast("panel")],b.prototype,"castPanel",null);e([k.property()],b.prototype,"parent",void 0);e([k.property({dependsOn:["layer.layer.loaded","layer.title"]})],b.prototype,"title",null);e([k.property({dependsOn:["layer.loadStatus","layerView.updating"],readOnly:!0})],b.prototype,
"updating",null);e([k.property({value:null})],b.prototype,"view",void 0);e([k.aliasOf("layer.visible")],b.prototype,"visible",void 0);e([k.property({dependsOn:["layer.minScale","layer.maxScale","view.scale"],readOnly:!0})],b.prototype,"visibleAtCurrentScale",null);e([k.property({dependsOn:["layer.visibilityMode"],readOnly:!0})],b.prototype,"visibilityMode",null);return b=h=e([k.subclass("esri.widgets.LayerList.ListItem")],b)}(k.declared(p,l))})},"esri/support/actions/ActionSlider":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ./ActionBase".split(" "),
function(r,m,q,e,p,f){return function(f){function l(e){e=f.call(this)||this;e.displayValueEnabled=!1;e.max=1;e.min=0;e.step=.1;e.type="slider";e.value=null;return e}q(l,f);g=l;l.prototype.clone=function(){return new g({active:this.active,className:this.className,disabled:this.disabled,id:this.id,indicator:this.indicator,title:this.title,visible:this.visible,displayValueEnabled:this.displayValueEnabled,max:this.max,min:this.min,step:this.step,value:this.value})};var g;e([p.property()],l.prototype,
"displayValueEnabled",void 0);e([p.property()],l.prototype,"max",void 0);e([p.property()],l.prototype,"min",void 0);e([p.property()],l.prototype,"step",void 0);e([p.property()],l.prototype,"value",void 0);return l=g=e([p.subclass("esri.support.Action.ActionSlider")],l)}(p.declared(f))})},"esri/widgets/LayerList/ListItemPanel":function(){define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Handles ../../core/Identifiable ../../core/requireUtils ../../core/watchUtils ../../core/accessorSupport/decorators ../Widget ../support/widget".split(" "),
function(r,m,q,e,p,f,u,l,g,k,n){return function(h){function f(b){b=h.call(this)||this;b._legend=null;b._handles=new p;b.content=null;b.image=null;b.listItem=null;b.open=!1;b.visible=!0;return b}q(f,h);f.prototype.postInitialize=function(){var b=this;this.own([l.init(this,"content",function(c){return b._createLegend(c)})])};f.prototype.destroy=function(){var b=this._legend;b&&b.destroy();this._legend=null};Object.defineProperty(f.prototype,"className",{get:function(){var b=this.image,c=this._getFirstWidget();
return this._get("className")||!b&&c?c.iconClass:""},set:function(b){void 0===b?this._clearOverride("className"):this._override("className",b)},enumerable:!0,configurable:!0});Object.defineProperty(f.prototype,"title",{get:function(){var b=this._getFirstWidget();return this._get("title")||b?b.label:""},set:function(b){void 0===b?this._clearOverride("title"):this._override("title",b)},enumerable:!0,configurable:!0});f.prototype.render=function(){return n.tsx("div",{class:"esri-layer-list-panel"},this._renderContents())};
f.prototype._renderContent=function(b,c){c=this._legend;var a=this.listItem;return b?"legend"===b?a&&a.view&&a.layer&&c?n.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--legend"),key:c},c.render()):null:"string"===typeof b?n.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--string"),key:b,innerHTML:b}):n.isWidget(b)?n.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--widget"),
key:b},b.render()):b instanceof HTMLElement?n.tsx("div",{class:this.classes("esri-layer-list-panel__content","esri-layer-list-panel__content--html-element"),key:b,bind:b,afterCreate:this._attachToNode}):null:null};f.prototype._renderContents=function(){var b=this,c=this.content;return Array.isArray(c)?c.map(function(a,d){return b._renderContent(a,d)}):this._renderContent(c,0)};f.prototype._getLegendOptions=function(b){if(b){var c=b.layer;b=b.view;if(c&&b)return{view:b,layerInfos:[{layer:c,title:""}]}}};
f.prototype._createLegend=function(b){var c=this;this._hasLegend(b)&&!this._legend&&u.when(r,"../Legend").then(function(a){var d=c._handles,b=new a(c._getLegendOptions(c.listItem));c._legend=b;c.notifyChange("className");c.notifyChange("title");a=l.init(c,["listItem.view","listItem.layer"],function(){return c._updateLegend(b)});d.add(a,"legends");c.scheduleRender()})};f.prototype._hasLegend=function(b){return"legend"===b?!0:Array.isArray(b)?b.some(function(c){return"legend"===c}):!1};f.prototype._attachToNode=
function(b){b.appendChild(this)};f.prototype._updateLegend=function(b){var c=this.listItem;if(c){var a=c.layer;b.view=c.view;b.layerInfos=[{layer:a,title:null}];this.scheduleRender()}};f.prototype._getWidget=function(b){return"legend"===b?this._legend:n.isWidget(b)?b:null};f.prototype._getFirstWidget=function(){var b=this,c=this.content;if(Array.isArray(c)){var a=null;c.some(function(d){(d=b._getWidget(d))&&(a=d);return!!d});return a}return this._getWidget(c)};e([g.property({dependsOn:["content",
"image"]})],f.prototype,"className",null);e([g.property(),n.renderable()],f.prototype,"content",void 0);e([g.property()],f.prototype,"image",void 0);e([g.property()],f.prototype,"listItem",void 0);e([g.property({dependsOn:["content"]})],f.prototype,"title",null);e([g.property(),n.renderable()],f.prototype,"open",void 0);e([g.property()],f.prototype,"visible",void 0);return f=e([g.subclass("esri.widgets.LayerList.ListItemPanel")],f)}(g.declared(k,f))})},"esri/widgets/LayerList/support/layerListUtils":function(){define(["require",
"exports"],function(r,m){function q(f){if(f)return f.hasOwnProperty("listMode")?f.listMode:void 0}function e(f){if(f)return f.hasOwnProperty("minScale")?f.minScale:void 0}function p(f){if(f)return f.hasOwnProperty("maxScale")?f.maxScale:void 0}Object.defineProperty(m,"__esModule",{value:!0});m.findLayerListMode=q;m.findLayerMinScale=e;m.findLayerMaxScale=p;m.findLayerVisibilityMode=function(f){if(f)return f.get("layer.capabilities")?f.get("layer.capabilities.exportMap.supportsSublayerVisibility")?
"independent":"inherited":f.hasOwnProperty("visibilityMode")?f.visibilityMode:void 0};m.getNormalizedChildLayerProperty=function(f){if(f&&"hide-children"!==f.listMode&&"wmts"!==f.type)return"group"===f.type?"layers":"sublayers"};m.canDisplayLayer=function(f){return"hide"!==q(f)};m.isLayerOutsideScaleRange=function(f,m){if(!f||isNaN(m))return!1;var l=e(f);f=p(f);l=!isNaN(l)&&0<l&&m>=l;m=!isNaN(f)&&0<f&&m<=f;return l||m}})},"*now":function(r){r(['dojo/i18n!*preload*esri/widgets/nls/LayerList*["ar","ca","cs","da","de","el","en-gb","en-us","es-es","fi-fi","fr-fr","he-il","hu","it-it","ja-jp","ko-kr","nl-nl","nb","pl","pt-br","pt-pt","ru","sk","sl","sv","th","tr","zh-tw","zh-cn","ROOT"]'])},
"*noref":1}});
define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper dojo/i18n!../nls/common dojo/i18n!./LayerList/nls/LayerList ../core/Handles ../core/watchUtils ../core/accessorSupport/decorators ./Widget ./LayerList/LayerListViewModel ./support/widget".split(" "),function(r,m,q,e,p,f,u,l,g,k,n,h){function t(b){var c=b.children;b.actionsOpen&&(b.actionsOpen=!1);c.forEach(function(a){return t(a)})}return function(b){function c(){var a=b.call(this)||this;a._handles=new u;
a.iconClass="esri-icon-layers";a.statusIndicatorsVisible=!0;a.label=f.widgetLabel;a.listItemCreatedFunction=null;a.operationalItems=null;a.view=null;a.viewModel=new n;return a}q(c,b);c.prototype.postInitialize=function(){var a=this,d=this.operationalItems;this.own(l.on(this,"operationalItems","change",function(){return a._itemsChanged(d)}))};c.prototype.destroy=function(){this._handles.destroy();this._handles=null};c.prototype.triggerAction=function(a,d){};c.prototype.render=function(){var a=this,
d,c=this._getItems(),b=this.get("viewModel.state"),c=0===c.length?h.tsx("div",{class:"esri-layer-list__no-items"},f.noItemsToDisplay):h.tsx("ul",{class:this.classes("esri-layer-list__list","esri-layer-list__list--root","esri-layer-list__list--independent")},c.map(function(d,c){return a._renderItem(d,null)})),b=(d={},d["esri-hidden"]="loading"===b,d["esri-disabled"]="disabled"===b,d);return h.tsx("div",{class:this.classes("esri-layer-list esri-widget esri-widget--panel",b)},c)};c.prototype._getItems=
function(){var a=this;return this.operationalItems.toArray().filter(function(d){return a.errorsVisible||!d.error})};c.prototype._renderItem=function(a,d){var c=this,b,e,g,k,l=this.id+"_"+a.uid,m=l+"_actions",n=l+"__list",l=l+"__title",q=!!a.children.length,r=!!a.error,u=r?f.layerError:"",t=a.visibilityMode,x=a.children&&a.children.toArray(),A=(b={},b["esri-layer-list__list--exclusive"]="exclusive"===t,b["esri-layer-list__list--inherited"]="inherited"===t,b["esri-layer-list__list--independent"]="inherited"!==
t&&"exclusive"!==t,b);b=(e={},e["esri-layer-list__item--has-children"]=q,e["esri-layer-list__item--error"]=!!u,e["esri-layer-list__item--updating"]=a.updating&&!d&&this.statusIndicatorsVisible,e["esri-layer-list__item--invisible-at-scale"]=!a.visibleAtCurrentScale,e);var y=this._countActions(a.actionsSections),v=a.panel;e=v&&v.open?v.render():null;var v=v&&v.visible?this._renderPanelButton(v):null,B=(g={},g["esri-layer-list__item-actions-menu-item--active"]=a.actionsOpen,g);g=a.actionsOpen?p.close:
p.open;g=y?h.tsx("div",{key:"esri-layer-list__actions-menu-toggle","data-item":a,bind:this,onclick:this._toggleActionsOpen,onkeydown:this._toggleActionsOpen,class:this.classes("esri-layer-list__item-actions-menu-item",B),tabindex:"0",role:"button","aria-controls":m,"aria-label":g,title:g},h.tsx("span",{"aria-hidden":"true",class:"esri-icon-handle-horizontal"})):null;g=y||v?h.tsx("div",{key:"esri-layer-list__actions-menu",class:"esri-layer-list__item-actions-menu"},v,g):null;m=y?this._renderActionsSections(a,
a.actionsSections,m):null;t=q?h.tsx("ul",{key:"esri-layer-list__list-items",id:n,class:this.classes("esri-layer-list__list",A),"aria-expanded":a.open?"true":"false",role:"exclusive"===t?"radiogroup":"group",hidden:a.open?null:!0},x.map(function(d,b){return c._renderItem(d,a)})):null;x=(k={},k["esri-layer-list__child-toggle--open"]=a.open,k);k=a.open?p.collapse:p.expand;n=q?h.tsx("span",{onclick:this._toggleChildrenClick,onkeydown:this._toggleChildrenClick,"data-item":a,key:"esri-layer-list__toggle-children",
class:this.classes("esri-layer-list__child-toggle",x),tabindex:"0",role:"button","aria-controls":n,"aria-label":k,title:k},h.tsx("span",{"aria-hidden":"true",class:this.classes("esri-layer-list__child-toggle-icon--closed","esri-icon-right-triangle-arrow")}),h.tsx("span",{"aria-hidden":"true",class:this.classes("esri-layer-list__child-toggle-icon--opened","esri-icon-down-arrow")}),h.tsx("span",{"aria-hidden":"true",class:this.classes("esri-layer-list__child-toggle-icon--closed-rtl","esri-icon-left-triangle-arrow")})):
null;d=this._createLabelNode(a,d,l);r=r?h.tsx("div",{key:"esri-layer-list__error",class:"esri-layer-list__item-error-message",role:"alert"},h.tsx("span",{"aria-hidden":"true",class:"esri-icon-notice-triangle"}),h.tsx("span",null,u)):null;return h.tsx("li",{key:a,class:this.classes("esri-layer-list__item",b),"aria-labelledby":l},h.tsx("div",{key:"esri-layer-list__list-item-container",class:"esri-layer-list__item-container"},n,d,g),r,m,e,t)};c.prototype._createLabelNode=function(a,d,c){var b;d=d&&d.visibilityMode;
var e=(b={},b["esri-icon-radio-checked"]="exclusive"===d&&a.visible,b["esri-icon-radio-unchecked"]="exclusive"===d&&!a.visible,b["esri-icon-visible"]="exclusive"!==d&&a.visible,b["esri-icon-non-visible"]="exclusive"!==d&&!a.visible,b);b="exclusive"===d?"radio":"checkbox";var g=a.title||f.untitledLayer,k=a.visibleAtCurrentScale?g:g+" ("+f.layerInvisibleAtScale+")",g=h.tsx("span",{id:c,title:k,"aria-label":k,class:"esri-layer-list__item-title"},g);return"inherited"===d?h.tsx("div",{key:a,class:"esri-layer-list__item-label"},
g):h.tsx("div",{key:a,onclick:this._labelClick,onkeydown:this._labelClick,"data-item":a,"data-parent-visibility":d,tabindex:"0","aria-checked":a.visible?"true":"false",role:b,"aria-labelledby":c,class:"esri-layer-list__item-label"},h.tsx("span",{class:"esri-layer-list__item-toggle"},h.tsx("span",{class:this.classes("esri-layer-list__item-toggle-icon",e),"aria-hidden":"true"})),g)};c.prototype._renderPanelButton=function(a){var d,b,c=a.className,e=a.open,f=a.title,c=a.image||c?c:"esri-icon-default-action",
g=this._getIconImageStyles(a),e=(d={},d["esri-layer-list__item-actions-menu-item--active"]=e,d);d=(b={},b["esri-layer-list__item-action-image"]=!!g["background-image"],b);c&&(d[c]=!!c);return h.tsx("div",{key:a,bind:this,"data-panel":a,onclick:this._triggerPanel,onkeydown:this._triggerPanel,class:this.classes("esri-layer-list__item-actions-menu-item",e),role:"button",tabindex:"0",title:f,"aria-label":f},h.tsx("span",{class:this.classes(d),styles:g}))};c.prototype._watchActionSectionChanges=function(a,
d){var b=this,c="action-section"+d;this._handles.add(a.on("change",this.scheduleRender.bind(this)),c);a.forEach(function(a){return b._renderOnActionChanges(a,d)})};c.prototype._renderOnActionChanges=function(a,d){var b=this;d="actions"+d;"toggle"===a.type?this._handles.add([l.init(a,"className image id title visible value".split(" "),function(){return b.scheduleRender()})],d):"slider"===a.type?this._handles.add([l.init(a,"className id title visible value displayValueEnabled max min step".split(" "),
function(){return b.scheduleRender()})],d):this._handles.add([l.init(a,["className","image","id","title","visible"],function(){return b.scheduleRender()})],d)};c.prototype._renderOnItemChanges=function(a){var d=this,b=a.uid,c="items"+b;this._handles.add([l.init(a,"actionsOpen visible open updating title visibleAtCurrentScale error visibilityMode panel panel.title panel.content panel.className".split(" "),function(){return d.scheduleRender()}),a.actionsSections.on("change",function(){return d.scheduleRender()}),
a.children.on("change",function(){return d.scheduleRender()})],c);a.children.forEach(function(a){return d._renderOnItemChanges(a)});a.actionsSections.forEach(function(a){return d._watchActionSectionChanges(a,b)})};c.prototype._itemsChanged=function(a){var b=this;this._handles.removeAll();a.forEach(function(a){return b._renderOnItemChanges(a)});this.scheduleRender()};c.prototype._renderActionsSections=function(a,b,c){var d=this;b=b.toArray().map(function(b){return h.tsx("ul",{key:b,class:"esri-layer-list__item-actions-list"},
d._renderActionSection(a,b))});return h.tsx("div",{role:"group","aria-expanded":a.actionsOpen?"true":"false",key:"esri-layer-list__actions-section",id:c,class:"esri-layer-list__item-actions",hidden:a.actionsOpen?null:!0},b)};c.prototype._renderActionSection=function(a,b){var c=this;return(b&&b.toArray()).map(function(b){return c._renderAction(a,b)})};c.prototype._renderAction=function(a,b){var c,d,e=this._getIconImageStyles(b),f=b.active,g=b.className,k=b.disabled,l=b.title,g="button"!==b.type||b.image||
g?g:"esri-icon-default-action",k=(c={},c["esri-layer-list__item-action"]="toggle"!==b.type,c["esri-layer-list__action-toggle"]="toggle"===b.type,c["esri-layer-list__action-toggle--on"]="toggle"===b.type&&b.value,c["esri-disabled-element"]=k,c);c=(d={},d["esri-layer-list__item-action-image"]=!f&&!!e["background-image"],d["esri-icon-loading-indicator"]=f,d["esri-rotating"]=f,d);g&&(c[g]=!0);return h.tsx("li",{bind:this,"data-item":a,"data-action":b,key:b,onclick:this._triggerAction,onkeydown:this._triggerAction,
classes:k,tabindex:"0",role:"button",title:l,"aria-label":l},h.tsx("span",{"aria-hidden":"true",class:this.classes("esri-layer-list__item-action-icon",c),styles:e}),h.tsx("span",{class:"esri-layer-list__item-action-title"},l))};c.prototype._countActions=function(a){return a.reduce(function(a,b){return a+b.length},0)};c.prototype._getIconImageStyles=function(a){a=a.declaredClass=a.image;return{"background-image":a?'url("'+a+'")':null}};c.prototype._toggleActionsOpen=function(a){a=a.currentTarget["data-item"];
var b=!a.actionsOpen;b&&this.operationalItems.forEach(function(a){return t(a)});a.actionsOpen=b};c.prototype._triggerPanel=function(a){if(a=a.currentTarget["data-panel"])a.open=!a.open};c.prototype._triggerAction=function(a){var b=a.currentTarget;a=b["data-action"];b=b["data-item"];"toggle"===a.type&&(a.value=!a.value);this.triggerAction(a,b)};c.prototype._labelClick=function(a){var b=a.currentTarget;a=b.getAttribute("data-parent-visibility");b=b["data-item"];"exclusive"===a&&b.visible||(b.visible=
!b.visible)};c.prototype._toggleChildrenClick=function(a){a=a.currentTarget["data-item"];a.open=!a.open};e([g.property()],c.prototype,"iconClass",void 0);e([g.property(),h.renderable()],c.prototype,"statusIndicatorsVisible",void 0);e([g.property(),h.renderable()],c.prototype,"errorsVisible",void 0);e([g.property()],c.prototype,"label",void 0);e([g.aliasOf("viewModel.listItemCreatedFunction"),h.renderable()],c.prototype,"listItemCreatedFunction",void 0);e([g.aliasOf("viewModel.operationalItems"),h.renderable()],
c.prototype,"operationalItems",void 0);e([g.aliasOf("viewModel.view"),h.renderable()],c.prototype,"view",void 0);e([h.vmEvent("trigger-action"),g.property({type:n}),h.renderable("viewModel.state")],c.prototype,"viewModel",void 0);e([g.aliasOf("viewModel.triggerAction")],c.prototype,"triggerAction",null);e([h.accessibleHandler()],c.prototype,"_toggleActionsOpen",null);e([h.accessibleHandler()],c.prototype,"_triggerPanel",null);e([h.accessibleHandler()],c.prototype,"_triggerAction",null);e([h.accessibleHandler()],
c.prototype,"_labelClick",null);e([h.accessibleHandler()],c.prototype,"_toggleChildrenClick",null);return c=e([g.subclass("esri.widgets.LayerList")],c)}(g.declared(k))});