// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/awaiterHelper ../../../core/tsSupport/generatorHelper ../../../core/tsSupport/assignHelper ../../../core/arrayUtils ./DefaultErrorContext ./internal/Resource ../support/buffer/BufferView ../support/buffer/bufferViewUtil ../support/buffer/glUtil ../support/buffer/math ../webgl-engine/lib/Geometry ../webgl-engine/lib/PreinterleavedGeometryData ../webgl-engine/lib/Texture ../webgl-engine/materials/DefaultMaterial".split(" "),function(P,h,k,w,Q,q,F,G,l,
A,H,x,I,J,K,B){function L(d,a){return k(this,void 0,void 0,function(){var b,c,m,g,l,e,n,r;return w(this,function(t){switch(t.label){case 0:b=d.json,c=0,t.label=1;case 1:if(!(c<b.nodes.length))return[3,6];m=b.nodes[c];g=d.getNodeTransform(c);u.warnUnsupportedIf(null!=m.weights,"Morph targets are not supported.");if(null==m.mesh)return[3,5];l=b.meshes[m.mesh];e=0;n=l.primitives;t.label=2;case 2:if(!(e<n.length))return[3,5];r=n[e];return[4,a(r,g)];case 3:t.sent(),t.label=4;case 4:return e++,[3,2];case 5:return c++,
[3,1];case 6:return[2]}})})}function M(d,a){if(d.materials.has(a))return d.materials.get(a);var b;if(null!=a.colorTexture&&(b=d.textures.get(a.colorTexture),!b)){var c=a.colorTexture;b=new K(c.data,c.name,{wrapClamp:33071===c.wrapS||33071===c.wrapT,mipmap:N.some(function(b){return b===c.minFilter}),preMultiplyAlpha:!0,noUnpackFlip:!0});d.textures.set(a.colorTexture,b)}b=new B({transparent:"OPAQUE"!==a.alphaMode,diffuse:[a.color[0],a.color[1],a.color[2]],ambient:[a.color[0],a.color[1],a.color[2]],
opacity:a.color[3],doubleSided:a.doubleSided,doubleSidedType:"winding-order",vertexColors:a.vertexColors,castShadows:!0,receiveSSAO:!0,textureId:b?b.id:void 0},a.name||"");d.materials.set(a,b);return b}Object.defineProperty(h,"__esModule",{value:!0});h.load=function(d,a){return k(this,void 0,void 0,function(){var b,c,m,g,h=this;return w(this,function(e){switch(e.label){case 0:return[4,G.Resource.load(d,u,a)];case 1:return b=e.sent(),c={textures:new Map,materials:new Map,geometries:[],materialsByComponent:[],
numberOfVertices:0},m=0,[4,L(b,function(a,d){return k(h,void 0,void 0,function(){var e,g,h,k,n,q,y,p,r,C,D,E,z,v;return w(this,function(f){switch(f.label){case 0:return e="gltf_"+m++,g=a.mode||4,4!==g?(u.warnUnsupported("Unsupported primitive mode ("+O[g]+"). Skipping primitive."),[2]):a.attributes.NORMAL?[4,b.getMaterial(a)]:(u.warnUnsupported("Vertex normals are required. Skipping primitive."),[2]);case 1:return h=f.sent(),k=M(c,h),n=B.getVertexBufferLayout(k.getParams()),[4,b.getIndexData(a)];
case 2:return q=f.sent(),[4,b.getPositionData(a)];case 3:return y=f.sent(),p=n.createBuffer(y.count),x.vec3.transformMat4(p.position,y,d),(r=p.getField("normal",l.BufferViewVec3f))?[4,b.getNormalData(a)]:[3,5];case 4:C=f.sent(),x.vec3.transformMat4(r,C,d),f.label=5;case 5:return(D=p.getField("uv0",l.BufferViewVec2f))?[4,b.getTextureCoordinates(a)]:[3,7];case 6:E=f.sent(),A.unrolledCopyVec2(D,E),f.label=7;case 7:return(z=p.getField("color",l.BufferViewVec4u8))?[4,b.getVertexColors(a)]:[3,9];case 8:v=
f.sent(),v instanceof l.BufferViewVec4f?x.vec4.scale(z,v,255):A.unrolledCopyVec4(z,v),f.label=9;case 9:return c.numberOfVertices+=p.count,c.materialsByComponent.push([k]),c.geometries.push(new I(new J(new Float32Array(p.buffer),H.glLayout(n),void 0,void 0,q,!1),e)),[2]}})})})];case 2:return e.sent(),g={stageResources:{textures:q.fromMapValues(c.textures),materials:q.fromMapValues(c.materials),geometries:c.geometries},materialsByComponent:c.materialsByComponent,numberOfVertices:c.numberOfVertices,
pivotOffset:void 0},[2,g]}})})};var u=new F.DefaultErrorContext,N=[9987,9985],O="POINTS LINES LINE_LOOP LINE_STRIP TRIANGLES TRIANGLE_STRIP TRIANGLE_FAN".split(" ")});