// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("../core/declare ../core/lang ../core/kebabDictionary ../core/Error ../core/Logger ../core/accessorSupport/ensureType ../support/arcadeUtils ../symbols/Symbol ../symbols/PolygonSymbol3D ../symbols/support/jsonUtils ../symbols/support/typeUtils ./Renderer ./support/LegendOptions ./support/ClassBreakInfo".split(" "),function(r,m,g,t,u,p,k,v,w,f,l,x,n,h){var y=u.getLogger("esri.renderers.ClassBreaksRenderer");n=n.LegendOptions;h=h.ClassBreakInfo;g=g({esriNormalizeByLog:"log",esriNormalizeByPercentOfTotal:"percent-of-total",
esriNormalizeByField:"field"});var z=p.ensureType(h),q=r(x,{declaredClass:"esri.renderers.ClassBreaksRenderer",properties:{backgroundFillSymbol:{types:{base:v,key:"type",typeMap:{"simple-fill":l.types.typeMap["simple-fill"],"picture-fill":l.types.typeMap["picture-fill"],"polygon-3d":l.types.typeMap["polygon-3d"]}},value:null,json:{origins:{"web-scene":{read:f.read,write:{target:{backgroundFillSymbol:{type:w}},writer:f.writeTarget}}},read:f.read,write:f.writeTarget}},classBreakInfos:{type:[h],json:{read:function(a,
b,c){if(Array.isArray(a)){var d=b.minValue;return a.map(function(a){var b=new h;b.read(a,c);null==b.minValue&&(b.minValue=d);null==b.maxValue&&(b.maxValue=b.minValue);d=b.maxValue;return b})}},write:function(a,b,c,d){a=a.map(function(a){return a.write({},d)});this._areClassBreaksConsecutive()&&a.forEach(function(a){delete a.classMinValue});b[c]=a}}},minValue:{type:Number,readOnly:!0,dependsOn:["classBreakInfos"],get:function(){return this.classBreakInfos[0]&&this.classBreakInfos[0].minValue||0},json:{read:!1,
write:{overridePolicy:function(){return 0!==this.classBreakInfos.length&&this._areClassBreaksConsecutive()?{enabled:!0}:{enabled:!1}}}}},defaultLabel:{type:String,value:null,json:{write:!0}},defaultSymbol:{types:l.rendererTypes,value:null,json:{origins:{"web-scene":{read:f.read,write:{target:{defaultSymbol:{types:l.rendererTypes3D}},writer:f.writeTarget}}},read:f.read,write:f.writeTarget}},valueExpression:{type:String,value:null,json:{write:!0}},valueExpressionTitle:{type:String,value:null,json:{write:!0}},
compiledFunc:{dependsOn:["valueExpression"],get:function(){return k.createFunction(this.valueExpression)}},legendOptions:{type:n,value:null,json:{write:!0}},field:{value:null,cast:function(a){return null==a?a:"function"===typeof a?a:p.ensureString(a)},json:{type:String,write:function(a,b,c,d){"string"===typeof a?b[c]=a:d&&d.messages?d.messages.push(new t("property:unsupported","ClassBreaksRenderer.field set to a function cannot be written to JSON")):y.error(".field: cannot write field to JSON since it's not a string value")}}},
isMaxInclusive:!0,normalizationField:{type:String,value:null,json:{write:!0}},normalizationTotal:{type:Number,value:null,json:{write:!0}},normalizationType:{type:g.apiValues,value:null,dependsOn:["normalizationField","normalizationTotal"],get:function(){var a=this._get("normalizationType"),b=!!this.normalizationField,c=null!=this.normalizationTotal;if(b||c)a=b&&"field"||c&&"percent-of-total",b&&c&&console.warn("warning: both normalizationField and normalizationTotal are set!");else if("field"===a||
"percent-of-total"===a)a=null;return a},json:{type:g.jsonValues,read:g.read,write:g.write}},requiredFields:{dependsOn:["field","normalizationField","valueExpression"]},type:{type:["class-breaks"],value:"class-breaks",json:{type:["classBreaks"]}}},constructor:function(){this.classBreakInfos=[]},addClassBreakInfo:function(a,b,c){a="number"===typeof a?new h({minValue:a,maxValue:b,symbol:c}):z(m.clone(a));this.classBreakInfos.push(a);1===this.classBreakInfos.length&&this.notifyChange("minValue")},removeClassBreakInfo:function(a,
b){var c,d,e=this.classBreakInfos.length;for(d=0;d<e;d++)if(c=[this.classBreakInfos[d].minValue,this.classBreakInfos[d].maxValue],c[0]==a&&c[1]==b){this.classBreakInfos.splice(d,1);break}},getBreakIndex:function(a,b){var c=this.field,d=this.classBreakInfos,e=a.attributes,f=d.length,g=this.isMaxInclusive;if(this.valueExpression)a=k.executeFunction(this.compiledFunc,k.createExecContext(a,k.getViewInfo(b)));else if("function"===typeof c)a=c(a);else if(a=parseFloat(e[c]),b=this.normalizationType)if(c=
parseFloat(this.normalizationTotal),e=parseFloat(e[this.normalizationField]),"log"===b)a=Math.log(a)*Math.LOG10E;else if("percent-of-total"===b&&!isNaN(c))a=a/c*100;else if("field"===b&&!isNaN(e)){if(isNaN(a)||isNaN(e))return-1;a/=e}if(null!=a&&!isNaN(a)&&"number"===typeof a)for(e=0;e<f;e++)if(b=[d[e].minValue,d[e].maxValue],b[0]<=a&&(g?a<=b[1]:a<b[1]))return e;return-1},getClassBreakInfo:function(a,b){a=this.getBreakIndex(a,b);return-1!==a?this.classBreakInfos[a]:null},getSymbol:function(a,b){a=
this.getBreakIndex(a,b);return-1<a?this.classBreakInfos[a].symbol:this.defaultSymbol},getSymbols:function(){var a=[];this.classBreakInfos.forEach(function(b){b.symbol&&a.push(b.symbol)});this.defaultSymbol&&a.push(this.defaultSymbol);return a},clone:function(){return new q({field:this.field,backgroundFillSymbol:this.backgroundFillSymbol&&this.backgroundFillSymbol.clone(),defaultLabel:this.defaultLabel,defaultSymbol:this.defaultSymbol&&this.defaultSymbol.clone(),valueExpression:this.valueExpression,
valueExpressionTitle:this.valueExpressionTitle,classBreakInfos:m.clone(this.classBreakInfos),isMaxInclusive:this.isMaxInclusive,normalizationField:this.normalizationField,normalizationTotal:this.normalizationTotal,normalizationType:this.normalizationType,visualVariables:m.clone(this.visualVariables),legendOptions:m.clone(this.legendOptions),authoringInfo:this.authoringInfo&&this.authoringInfo.clone()})},collectRequiredFields:function(a){this.inherited(arguments);[this.field,this.normalizationField].forEach(function(b){b&&
(a[b]=!0)});this.valueExpression&&k.extractFieldNames(this.valueExpression).forEach(function(b){a[b]=!0})},_areClassBreaksConsecutive:function(){for(var a=this.classBreakInfos,b=1;b<a.length;b++)if(a[b-1].maxValue!==a[b].minValue)return!1;return!0}});return q});