// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/assignHelper @dojo/framework/shim/Map ../../../../../core/Logger ../../../../../core/libs/gl-matrix/mat2d ../../../../../core/libs/gl-matrix/vec2 ../definitions ./CollisionBucket ../util/iterator ../../../tiling/TileKey ../../../../3d/support/mathUtils ../../../../vectorTiles/GeometryUtils".split(" "),function(v,C,K,D,F,w,z,x,G,E,p,r,H){Object.defineProperty(C,"__esModule",{value:!0});var I=F.getLogger("esri/views/2d/engine/webgl/collisions/CollisionEngine"),
A=x.TILE_SIZE/x.COLLISION_BUCKET_SIZE;v=function(){function c(a){this._layers=new D.default;this._collisionBuckets=new D.default;this._v3Buf1=z.create();this._v3Buf2=z.create();this._mat2dBuf=w.create();this._tileInfo=a}c.prototype.registerLayer=function(a,b){if(a&&!this._layers.has(a.uid)){var d=this._createInfo(b,a.labelingInfo);this._layers.set(a.uid,d);this._collisionBuckets.forEach(function(a){return a.onRegisterLayer(d.index)})}};c.prototype.unregisterLayer=function(a){var b=this;if(a&&this._layers.has(a.uid)){var d=
this._layers.get(a.uid);this._deleteInfo(d);this._layers.delete(a.uid);this._collisionBuckets.forEach(function(a,f){var g=a.getTile(d.index);g&&(g.dirty=!1,a.onUnregisterLayer(d.index),a.canDelete()&&b._collisionBuckets.delete(f))})}};c.prototype.addTile=function(a,b){var d=b.key.id;this._layers.has(a)&&(this._collisionBuckets.has(d)||this._collisionBuckets.set(d,new G.default(this._layers.size)),this._collisionBuckets.get(d).getTile(this._getIndex(a)).reference=b)};c.prototype.removeTile=function(a,
b){this._layers.has(a)&&this._collisionBuckets.has(b)&&(this._collisionBuckets.get(b).getTile(this._getIndex(a)).reference=null)};c.prototype.run=function(a,b){var d=[],h=p.pool.acquire(0,0,0,0);E.forEachIter(this._collisionBuckets.keys(),function(a){h.set(a);h.level===b&&d.push(a)});p.pool.release(h);for(var d=p.sort(d),f=a.state.rotation,g=this._checkRotation(f),e=0,k=d;e<k.length;e++){var n=k[e];this._computeNeighbors(n)}for(var k=0,c=d;k<c.length;k++)for(n=c[k],g=g||this._collisionBuckets.get(n).isDirty,
e=0;e<this._layers.size;e++){var m=this._getCollisionInfo(e);this._resetCollisionBucket(m,n,a,g)}a=0;for(g=d;a<g.length;a++)for(n=g[a],e=0;e<this._layers.size;e++)k=this._getCollisionInfo(e).zoomRanges,this._runCollisionBucket(e,n,b,!!f,k);f=0;for(e=d;f<e.length;f++)n=e[f],this._cleanCollisionBucket(n)};c.prototype._computeNeighbors=function(a){var b=this._collisionBuckets.get(a);a=p.from(a);b.neighbors=[this._getNeighboringBucket(a,-1,-1),this._getNeighboringBucket(a,0,-1),this._getNeighboringBucket(a,
1,-1),this._getNeighboringBucket(a,-1,0),b,this._getNeighboringBucket(a,1,0),this._getNeighboringBucket(a,-1,1),this._getNeighboringBucket(a,0,1),this._getNeighboringBucket(a,1,1)]};c.prototype._getNeighboringBucket=function(a,b,d){a=p.getId(a.level,a.row+d,a.col+b,a.world);return this._collisionBuckets.has(a)?this._collisionBuckets.get(a):null};c.prototype._checkRotation=function(a){if(!this._lastRotation)return this._lastRotation=a,!1;var b=a!==this._lastRotation;this._lastRotation=a;return b};
c.prototype._collectCollisionInfos=function(){var a=[];E.forEachIter(this._layers.values(),function(b){return a.push(b)});return a};c.prototype._createInfo=function(a,b){for(var d=this,h=this._collectCollisionInfos().sort(function(a,b){return a.order-b.order}),f=!1,g=-1,e=0;e<h.length;e++){var c=h[e];!f&&c.order>a&&(g=c.index,f=!0);f&&c.index++}f||(g=h.length);b=b.map(function(a){return d._convertLabelClass(a)});return{index:g,order:a,zoomRanges:b}};c.prototype._convertLabelClass=function(a){var b=
!!a.maxScale,d=!!a.minScale&&this._tileInfo.scaleToZoom(a.minScale)||0;a=b&&this._tileInfo.scaleToZoom(a.maxScale)||255;return{minZoom:Math.floor(10*d),maxZoom:Math.floor(10*a)}};c.prototype._deleteInfo=function(a){var b=a.index;a=this._collectCollisionInfos().sort(function(a,b){return a.index-b.index});for(b+=1;b<a.length;b++)a[b].index--};c.prototype._resetCollisionBucket=function(a,b,d,c){a=this._collisionBuckets.get(b).getTile(a.index);if(!a)return!1;a=a.reference;if(!a||!a.hasData)return!1;b=
this._v3Buf1;var f=this._mat2dBuf;d=d.state;d.toScreen(b,a.coords);a.tileTransform.screenCoord[0]=b[0];a.tileTransform.screenCoord[1]=b[1];w.identity(f);w.rotate(f,f,d.rotation*H.C_DEG_TO_RAD);a.tileTransform.screenTransform.set(f);c&&(a.isDirty=!0);if(!a.isDirty)return!1;c=0;for(d=a.displayObjects;c<d.length;c++)for(a=0,b=d[c].metrics;a<b.length;a++)b[a].maxZoom=0;return!0};c.prototype._runCollisionBucket=function(a,b,d,c,f){b=this._collisionBuckets.get(b);var g=b.getTile(a);if(g){var e=g.reference;
if(e&&e.isDirty)for(var k=0;k<e.displayObjects.length;k++)for(var h=e.displayObjects[k],B=h.id,m=0;m<h.metrics.length;m++){var l=h.metrics[m],y=f[l.index],J=this._computeLabelVisibility(a,k,m,B,b,g,h,h.anchor,l,d,e,c,y);l.minZoom=J;l.maxZoom=y.maxZoom;e.setVisibilityRange(B,m,l.minZoom,l.maxZoom)}}};c.prototype._cleanCollisionBucket=function(a){this._collisionBuckets.get(a).clean()};c.prototype._computeLabelVisibility=function(a,b,d,c,f,g,e,k,n,B,m,l,y){b=y.minZoom;d=m.tileTransform.screenTransform;
d=l?z.transformMat2d(this._v3Buf1,k,d):k;g=n.bounds.center;var h=m.tileTransform.screenCoord;k=d[0]+g[0]+h[0];d=d[1]+g[1]+h[1];g=e.xBucket;var t=e.yBucket,h=e.xOverflow,q=e.yOverflow;e=g-h;g=g+h+1;h=t+q+1;for(t-=q;t<h;t++)for(q=e;q<g;q++)if(!(q<-A||t<-A||q>A||t>A))for(var p=0;p<=a;p++){var w=a===p,u=this._getRelativeSubBucket(p,f,m,q,t);if(u)for(var x=u.neighborTile,r=0,u=u.bucket;r<u.length;r++){var v=u[r];w&&v.id===c||(b=Math.max(this._compareLabelToDisplayObject(c,n,k,d,v,B,x,l,y),b))}}return b};
c.prototype._getRelativeSubBucket=function(a,b,d,c,f){var g=r.sign(Math.floor(c/4)),e=r.sign(Math.floor(f/4));return(a=this._getNeighboringTile(a,b,d,g,e))&&a.index?{bucket:a.index[f-4*e][c-4*g],neighborTile:a.reference}:null};c.prototype._getNeighboringTile=function(a,b,d,c,f){return(a=(b=b.neighbors[3*(1+f)+(1+c)])&&b.getTile(a))&&a.reference&&a.reference.hasData?a:null};c.prototype._compareLabelToDisplayObject=function(a,b,d,c,f,g,e,k,n){a=n.minZoom;n=10*(g+x.COLLISION_MAX_ZOOM_DELTA);var h=e.tileTransform.screenTransform;
k=k?z.transformMat2d(this._v3Buf2,f.anchor,h):f.anchor;h=0;for(f=f.metrics;h<f.length;h++){var m=f[h];if(m.maxZoom&&!(m.minZoom>n||a>=m.maxZoom)){var l=m.bounds.center,p=e.tileTransform.screenCoord,l=this._updateMinZoom(d,c,b.bounds,k[0]+l[0]+p[0],k[1]+l[1]+p[1],m.bounds),l=Math.min(Math.max(Math.ceil(10*(l+g)),0),255);if(!(m.minZoom>=l)){if(255<=l){a=255;break}a=Math.max(a,l)}}}return a};c.prototype._updateMinZoom=function(a,b,d,c,f,g){return r.log2(Math.min((g.width+d.width)/2/Math.abs(c-a),(g.height+
d.height)/2/Math.abs(f-b)))};c.prototype.onLabelsRendered=function(){this._collisionBuckets.forEach(function(a){a.onLabelsRendered()})};c.prototype._getIndex=function(a){return this._layers.get(a).index};c.prototype._getCollisionInfo=function(a){for(var b=0,d=this._collectCollisionInfos();b<d.length;b++){var c=d[b];if(c.index===a)return c}I.error("Tried to get a LayerCollisionInfo for an index that doesn't exist!");return null};return c}();C.default=v});