// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","../../../../core/has","./FreeList","./Utils"],function(u,v,w,q,r){function x(e){e=e.getStrides();var a={},b;for(b in e)a[t[b]]=e[b];return a}Object.defineProperty(v,"__esModule",{value:!0});var t=["FILL","LINE","MARKER","TEXT","LABEL"];u=function(){function e(a,b,h,f){this._strides=a;this._displayList=b;this._freeListsAndStorage={};this._dirtyMap=null;this._dirtyMap=h;for(var d in a){this._freeListsAndStorage[d]={vtxFreeList:f?new q.FreeList(f):null,idxFreeList:f?new q.FreeList(f):
null,vertexBuffers:{},indexBuffer:f?new Uint32Array(f):null};for(var l in a[d])this._freeListsAndStorage[d].vertexBuffers[l]={data:f?r.allocateTypedArrayBuffer(f,a[d][l]):null,stride:a[d][l]}}}e.fromTileData=function(a,b){var h=x(a),f=[0,0,0,0,0],d=[0,0,0,0,0],l=[];a.tileDisplayData.displayObjectRegistry.forEach(function(a){l.push(a)});for(var k=0;k<l.length;k++)for(var g=0,n=l[k].displayRecords;g<n.length;g++){var c=n[g];f[c.geometryType]=Math.max(f[c.geometryType],c.vertexFrom+c.vertexCount);d[c.geometryType]=
Math.max(d[c.geometryType],c.indexFrom+c.indexCount)}b=new e(h,a.tileDisplayData.displayList,b,null);for(h=0;h<a.tileBufferData.geometries.length;++h){var k=f[h],n=d[h],c=a.tileBufferData.geometries[h],g=b._storageFor(t[h]),m=a.tileBufferData.geometries[h].indexBuffer;g.indexBuffer=m;g.idxFreeList=new q.FreeList(m.length);g.idxFreeList.allocate(n);var n=void 0,p;for(p in c.vertexBuffer)c=a.tileBufferData.geometries[h].vertexBuffer[p],g.vertexBuffers[p].data=c.data,g.vertexBuffers[p].stride=c.stride,
m=r.strideToPackingFactor(c.stride),c=c.data.length*m/c.stride,n||(n=c);g.vtxFreeList=new q.FreeList(n);g.vtxFreeList.allocate(k)}return b};e.prototype.delete=function(a){var b=t[a.geometryType];this._freeVertices(b,a.vertexFrom,a.vertexCount);this._freeIndices(b,a.indexFrom,a.indexCount);this._displayList.removeFromList(a);a.vertexFrom=void 0;a.indexFrom=void 0};e.prototype.setMeshData=function(a,b,h,f){var d=t[a.geometryType];a.meshData=null;var l=void 0,k=void 0;void 0===a.vertexFrom?(k=b.vertexCount,
l=this._allocateVertices(d,k)):b.vertexCount>a.vertexCount?(this._freeVertices(d,a.vertexFrom,a.vertexCount),k=b.vertexCount,l=this._allocateVertices(d,k)):b.vertexCount===a.vertexCount?(l=a.vertexFrom,k=a.vertexCount):(this._freeVertices(d,a.vertexFrom+b.vertexCount,a.vertexCount-b.vertexCount),l=a.vertexFrom,k=b.vertexCount);var g=!0,e=void 0,c=void 0,m=void 0;void 0===a.indexFrom?(m=b.indexCount,c=this._allocateIndices(d,m)):b.indexCount>a.indexCount?(e=this._displayList.removeFromList(a),this._freeIndices(d,
a.indexFrom,a.indexCount),m=b.indexCount,c=this._allocateIndices(d,m)):b.indexCount===a.indexCount?(g=!1,c=a.indexFrom,m=a.indexCount):(e=this._displayList.removeFromList(a),this._freeIndices(d,a.indexFrom+b.indexCount,a.indexCount-b.indexCount),c=a.indexFrom,m=b.indexCount);if(-1!==l&&-1!==c){d=this._storageFor(d);r.copyMeshData(l,c,d.vertexBuffers,d.indexBuffer,b,h,f);a.vertexFrom=l;a.indexFrom=c;a.vertexCount=b.vertexCount;a.indexCount=b.indexCount;if(this._dirtyMap){this._dirtyMap.markDirtyIndices(a.geometryType,
a.indexFrom,a.indexCount);for(var p in h)this._dirtyMap.markDirtyVertices(a.geometryType,p,a.vertexFrom,a.vertexCount)}g&&this._displayList.addToList(a,e);return!0}-1!==l&&this._freeVertices(d,l,k);-1!==c&&this._freeIndices(d,c,m);a.setMeshDataFromBuffers(b,h,f);a.vertexFrom=void 0;a.vertexCount=0;a.indexFrom=void 0;a.indexCount=0;return!1};e.prototype._allocateVertices=function(a,b){a=this._storageFor(a);b=a.vtxFreeList.allocate(b);return-1===b||.5<a.vtxFreeList.fragmentation?-1:b};e.prototype._freeVertices=
function(a,b,h){var f=this._storageFor(a);f.vtxFreeList.free(b,h);if(w("esri-feature-tiles-debug"))for(var d in f.vertexBuffers)for(var e=f.vertexBuffers[d].data,k=this._stridesFor(a,d),g=r.strideToPackingFactor(k),n=b*k/g,k=h*k/g,g=n;g<n+k;++g)e[g]=0};e.prototype._freeIndices=function(a,b,e){a=this._storageFor(a);a.idxFreeList.free(b,e);if(w("esri-feature-tiles-debug")){a=a.indexBuffer;for(var f=b;f<b+e;++f)a[f]=0}};e.prototype._allocateIndices=function(a,b){a=this._storageFor(a);b=a.idxFreeList.allocate(b);
return-1===b||.5<a.idxFreeList.fragmentation?-1:b};e.prototype._storageFor=function(a){return this._freeListsAndStorage[a]};e.prototype._stridesFor=function(a,b){return this._strides[a][b]};return e}();v.default=u});