// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../arcade/Dictionary ../../../../arcade/Feature ../../../../core/Error ../../../../core/Logger ../../../../core/screenUtils ../../../../support/arcadeUtils ./color ./enums ./SymbolProperties".split(" "),function(q,a,M,N,w,O,x,y,z,c,P){function f(b){for(var a={},g=0;g<b.length;g++){var l=b[g];a[l.name]=l.strideInBytes}return a}function A(b){switch(b){case c.WGLGeometryType.MARKER:return Q;case c.WGLGeometryType.FILL:return R;case c.WGLGeometryType.LINE:return S;case c.WGLGeometryType.TEXT:return T;
case c.WGLGeometryType.LABEL:return U}return null}function G(b){switch(b%4){case 0:case 2:return 4;case 1:case 3:return 1}}function k(b){switch(b){case "esriSMS":return"simple-marker";case "esriPMS":return"picture-marker";case "esriSLS":return"simple-line";case "esriPLS":return"picture-line";case "esriSFS":return"simple-fill";case "esriPFS":return"picture-fill";case "esriTS":return"text"}return b}function H(b){if(b=k(b.type)){switch(b){case "simple-marker":case "picture-marker":return!0;case "CIMPointSymbol":return!0}return!1}}
function I(b){if(b=k(b.type)){switch(b){case "simple-fill":case "picture-fill":return!0;case "CIMPolygonSymbol":return!0}return!1}}function J(b){if(b=k(b.type)){switch(b){case "simple-line":case "picture-line":return!0;case "CIMLineSymbol":return!0}return!1}}function K(b){if(b=k(b.type)){switch(b){case "text":return!0;case "CIMTextSymbol":return!0}return!1}}function u(b){return b&&b.length||0}function L(b){return"string"===typeof b}Object.defineProperty(a,"__esModule",{value:!0});var p,v=O.getLogger("esri.views.2d.engine.webgl.Utils");
a.C_HITTEST_SEARCH_SIZE=4;a.C_VBO_GEOMETRY="geometry";a.C_VBO_PERINSTANCE="per_instance";a.C_VBO_PERINSTANCE_VV="per_instance_vv";a.C_VBO_VISIBILITY="visibility";a.C_VBO_VISIBILITY_RANGE="visibilityRange";a.C_ICON_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:24,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_ICON_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:40,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_ICON_HEATMAP=[{name:a.C_VBO_GEOMETRY,strideInBytes:28,
divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_FILL_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:24,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_FILL_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:32,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_LINE_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:32,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_LINE_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:44,
divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_TEXT_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:20,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_TEXT_VERTEX_DEF_VV=[{name:a.C_VBO_GEOMETRY,strideInBytes:36,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0}];a.C_LABEL_VERTEX_DEF=[{name:a.C_VBO_GEOMETRY,strideInBytes:20,divisor:0},{name:a.C_VBO_VISIBILITY,strideInBytes:1,divisor:0},{name:a.C_VBO_VISIBILITY_RANGE,strideInBytes:2,divisor:0}];
a.C_ICON_STRIDE_SPEC=f(a.C_ICON_VERTEX_DEF);a.C_ICON_STRIDE_SPEC_VV=f(a.C_ICON_VERTEX_DEF_VV);a.C_ICON_STRIDE_SPEC_HEATMAP=f(a.C_ICON_HEATMAP);a.C_FILL_STRIDE_SPEC=f(a.C_FILL_VERTEX_DEF);a.C_FILL_STRIDE_SPEC_VV=f(a.C_FILL_VERTEX_DEF_VV);a.C_LINE_STRIDE_SPEC=f(a.C_LINE_VERTEX_DEF);a.C_LINE_STRIDE_SPEC_VV=f(a.C_LINE_VERTEX_DEF_VV);a.C_TEXT_STRIDE_SPEC=f(a.C_TEXT_VERTEX_DEF);a.C_TEXT_STRIDE_SPEC_VV=f(a.C_TEXT_VERTEX_DEF_VV);a.C_LABEL_STRIDE_SPEC=f(a.C_LABEL_VERTEX_DEF);a.getStrides=function(b,d,g){void 0===
g&&(g=!1);switch(b){case c.WGLGeometryType.MARKER:return d?a.C_ICON_STRIDE_SPEC_VV:g?a.C_ICON_STRIDE_SPEC_HEATMAP:a.C_ICON_STRIDE_SPEC;case c.WGLGeometryType.FILL:return d?a.C_FILL_STRIDE_SPEC_VV:a.C_FILL_STRIDE_SPEC;case c.WGLGeometryType.LINE:return d?a.C_LINE_STRIDE_SPEC_VV:a.C_LINE_STRIDE_SPEC;case c.WGLGeometryType.TEXT:return d?a.C_TEXT_STRIDE_SPEC_VV:a.C_TEXT_STRIDE_SPEC;case c.WGLGeometryType.LABEL:return a.C_LABEL_STRIDE_SPEC}return null};var Q=[a.C_VBO_GEOMETRY,a.C_VBO_VISIBILITY],R=[a.C_VBO_GEOMETRY,
a.C_VBO_VISIBILITY],S=[a.C_VBO_GEOMETRY,a.C_VBO_VISIBILITY],T=[a.C_VBO_GEOMETRY,a.C_VBO_VISIBILITY],U=[a.C_VBO_GEOMETRY,a.C_VBO_VISIBILITY,a.C_VBO_VISIBILITY_RANGE];a.getNamedBuffers=A;a.strideToPackingFactor=G;a.allocateTypedArrayBuffer=function(b,a){switch(a%4){case 0:case 2:return new Uint32Array(Math.floor(b*a/4));case 1:case 3:return new Uint8Array(b*a)}};a.allocateTypedArrayBufferwithData=function(b,a){switch(a%4){case 0:case 2:return new Uint32Array(b);case 1:case 3:return new Uint8Array(b)}};
a.getSymbolGeometryType=function(b){return H(b)?c.WGLGeometryType.MARKER:J(b)?c.WGLGeometryType.LINE:I(b)?c.WGLGeometryType.FILL:K(b)?c.WGLGeometryType.TEXT:c.WGLGeometryType.UNKNOWN};a.normalizeSymbolType=k;a.isMarkerSymbol=H;a.isFillSymbol=I;a.isLineSymbol=J;a.isPictureSymbol=function(b){if(b=k(b.type))switch(b){case "picture-marker":case "picture-line":case "picture-fill":return!0}return!1};a.isTextSymbol=K;a.getTextProperties=function(b){return P.TextProperties.pool.acquire(b.color?z.copyAndPremultiply(b.color):
[255,255,255,255],b.haloColor?z.copyAndPremultiply(b.haloColor):[255,255,255,255],x.pt2px(b.haloSize),x.pt2px(b.font.size),b.angle*Math.PI/180,b.xoffset/b.font.size,b.yoffset/b.font.size,"left"===b.horizontalAlignment?0:"right"===b.horizontalAlignment?1:.5,"top"===b.verticalAlignment?0:"bottom"===b.verticalAlignment?1:.5)};a.isSameUniformValue=function(b,a){return!1};a.isSameMaterialInfo=function(a,d){if(a.materialKey!==d.materialKey||u(a.texBindingInfo)!==u(d.texBindingInfo)||u(a.materialParams)!==
u(d.materialParams))return!1;for(var b=a.texBindingInfo.length,l=0;l<b;++l){var c=a.texBindingInfo[l],e=d.texBindingInfo[l];if(c.unit!==e.unit||c.pageId!==e.pageId||c.semantic!==e.semantic)return!1}a=a.materialParams.length;for(l=0;l<a;)return!1;return!0};a.serializeString=function(a,d,g){for(var b=0,c=a.length,e=0;e<c;++e)d&&(d[g+b]=a.charCodeAt(e)),++b;d&&(d[g+b]=0);++b;return b};a.deserializeString=function(a,d,c){var b=0;a.s="";for(var g=!0;g;){var e=d[c+b];++b;0!==e?a.s+=String.fromCharCode(e):
g=!1}return b};a.isDefined=function(a){return null!==a&&void 0!==a};a.isNumber=function(a){return"number"===typeof a};a.isString=L;a.isStringOrNull=function(a){return null==a||L(a)};a.lerp=function(a,d,c){return a+(d-a)*c};q=function(){function a(){this._arr=[];this._push=this._push.bind(this)}a.prototype._push=function(a,b){this._arr.push(b)};a.prototype.getKeys=function(a){this._arr.length=0;a&&a.forEach(this._push);return this._arr};return a}();a.KeysGetter=q;q=function(){function a(){this._arr=
[];this._push=this._push.bind(this)}a.prototype._push=function(a,b){this._arr.push(a)};a.prototype.getValues=function(a){this._arr.length=0;a&&a.forEach(this._push);return this._arr};return a}();a.ValuesGetter=q;a.getCapType=function(a){switch(a){case "butt":return c.CapType.BUTT;case "round":return c.CapType.ROUND;case "square":return c.CapType.SQUARE;default:return v.error(new w("mapview-invalid-type","Cap type "+a+" is not a valid option. Defaulting to round")),c.CapType.ROUND}};a.getJoinType=
function(a){switch(a){case "miter":return c.JoinType.MITER;case "bevel":return c.JoinType.BEVEL;case "round":return c.JoinType.ROUND;default:return v.error(new w("mapview-invalid-type","Join type "+a+" is not a valid option. Defaulting to round")),c.JoinType.ROUND}};a.getVVType=function(a){switch(a){case "opacity":return c.VVType.OPACITY;case "color":return c.VVType.COLOR;case "rotation":return c.VVType.ROTATION;case "size":return c.VVType.SIZE;default:return v.error("Cannot interpret unknown vv: "+
a),null}};a.createArcadeFunction=function(a,c){var b=a.spatialReference,d=a.layer,n=y.createFunction(a.valueExpression),e=new N,m=new M({viewingMode:null,scale:null}),B={},F={vars:{$feature:e,$view:null},spatialReference:b};return function(a,b){e.repurposeFromGraphicLikeObject(a.geometry,a.attributes,d);b?(F.vars.$view=m,m.attributes.viewingMode=b.viewingMode,m.attributes.scale=b.scale):F.vars.$view=B;a=y.executeFunction(n,F);return c?c(a):a}};a.copyMeshData=function(a,c,g,l,n,e,m){for(var b in e)for(var d=
e[b].stride,f=G(d),r=e[b].data,V=g[b].data,k=d*n.vertexCount/f,h=d*a/f,f=d*n.vertexFrom/f,d=0;d<k;++d)V[d+h]=r[d+f];g=n.indexCount;for(d=0;d<g;++d)l[d+c]=m[d+n.indexFrom]-n.vertexFrom+a};a.C_VBO_INFO=(p={},p[a.C_VBO_GEOMETRY]=35044,p[a.C_VBO_VISIBILITY]=35044,p[a.C_VBO_VISIBILITY_RANGE]=35048,p);a.createGeometryData=function(a,c){for(var b=[],d=0;5>d;++d){for(var f={},e=0,m=A(d);e<m.length;e++){var B=m[e];f[B]={data:c(d,B)}}b.push({data:a(d),buffers:f})}return b};a.resampleHermite=function(a,c,g,
f,n,e,m){void 0===m&&(m=!0);var b=c/n;g/=e;for(var d=Math.ceil(b/2),l=Math.ceil(g/2),r=0;r<e;r++)for(var k=0;k<n;k++){for(var p=4*(k+(m?e-r-1:r)*n),h=0,q=0,u=0,v=0,w=0,x=0,y=0,z=(r+.5)*g,C=Math.floor(r*g);C<(r+1)*g;C++)for(var D=Math.abs(z-(C+.5))/l,A=(k+.5)*b,D=D*D,E=Math.floor(k*b);E<(k+1)*b;E++){var t=Math.abs(A-(E+.5))/d,h=Math.sqrt(D+t*t);-1<=h&&1>=h&&(h=2*h*h*h-3*h*h+1,0<h&&(t=4*(E+C*c),y+=h*a[t+3],u+=h,255>a[t+3]&&(h=h*a[t+3]/250),v+=h*a[t],w+=h*a[t+1],x+=h*a[t+2],q+=h))}f[p]=v/q;f[p+1]=w/
q;f[p+2]=x/q;f[p+3]=y/u}}});