// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","../../../../core/Logger","./MeshData","./Utils"],function(t,u,q,n,m){var r=q.getLogger("esri/views/2d/engine/webgl/WGLDisplayRecord");return function(){function b(a,c,h){this.id=a;this.geometryType=c;this._materialInfo=h;this.meshData=null;this.indexCount=this.indexFrom=this.vertexCount=this.vertexFrom=this.zOrder=this.symbolLevel=0}Object.defineProperty(b.prototype,"sortKey",{get:function(){void 0===this._sortKey&&this._computeSortKey();return this._sortKey},enumerable:!0,
configurable:!0});Object.defineProperty(b.prototype,"materialInfo",{get:function(){return"number"===typeof this._materialInfo?(r.warn("Tried to read materialInfo, but found an index! Was materialInfo deserialized correctly?"),null):this._materialInfo},set:function(a){this._materialInfo=a},enumerable:!0,configurable:!0});b.prototype.copy=function(){var a=new b(this.id,this.geometryType,this._materialInfo);a.vertexFrom=this.vertexFrom;a.vertexCount=this.vertexCount;a.indexFrom=this.indexFrom;a.indexCount=
this.indexCount;a.zOrder=this.zOrder;a.symbolLevel=this.symbolLevel;a.meshData=this.meshData;return a};b.prototype.setMeshDataFromBuffers=function(a,c,h){var g=new n,b;for(b in c){for(var e=c[b].stride,k=c[b].data,f=[],p=m.strideToPackingFactor(e),d=0;d<e*a.vertexCount/p;++d)f[d]=k[d+e*a.vertexFrom/p];g.vertexData.set(b,f)}for(d=g.indexData.length=0;d<a.indexCount;++d)g.indexData[d]=h[d+a.indexFrom]-a.vertexFrom;g.vertexCount=a.vertexCount;this.meshData=g};b.prototype.readMeshDataFromBuffers=function(a,
c){this.meshData?this.meshData.clear():this.meshData=new n;for(var b in a){for(var g=a[b].stride,l=a[b].data,e=[],k=m.strideToPackingFactor(g),f=0;f<g*this.vertexCount/k;++f)e[f]=l[f+g*this.vertexFrom/k];this.meshData.vertexData.set(b,e)}for(f=this.meshData.indexData.length=0;f<this.indexCount;++f)this.meshData.indexData[f]=c[f+this.indexFrom]-this.vertexFrom;this.meshData.vertexCount=this.vertexCount};b.prototype.writeMeshDataToBuffers=function(a,c,b,g){for(var l in c)for(var e=c[l].stride,k=this.meshData.vertexData.get(l),
f=c[l].data,h=m.strideToPackingFactor(e),d=0;d<e*this.meshData.vertexCount/h;++d)f[d+e*a/h]=k[d];for(d=0;d<this.meshData.indexData.length;++d)g[d+b]=this.meshData.indexData[d]+a;this.vertexFrom=a;this.vertexCount=this.meshData.vertexCount;this.indexFrom=b;this.indexCount=this.meshData.indexData.length};b.writeAllMeshDataToBuffers=function(a,b,h){for(var c=0,l=0,e=0;e<a.length;e++){var k=a[e];k.writeMeshDataToBuffers(c,b,l,h);c+=k.vertexCount;l+=k.indexCount}};b.prototype._computeSortKey=function(){this._sortKey=
(this.symbolLevel&31)<<12|(this.zOrder&127)<<4|this.geometryType&7};b.prototype.serialize=function(a){a.push(this.geometryType);a.push(this._materialInfo);a.push(this.symbolLevel);a.push(this.zOrder);a.push(this.vertexFrom);a.push(this.vertexCount);a.push(this.indexFrom);a.push(this.indexCount);return a};b.deserialize=function(a,c){var h=a.readInt32(),g=c.store&&c.store.get(a.readInt32())||a.readInt32();c=new b(c.id,h,g);c.symbolLevel=a.readInt32();c.zOrder=a.readInt32();c.vertexFrom=a.readInt32();
c.vertexCount=a.readInt32();c.indexFrom=a.readInt32();c.indexCount=a.readInt32();return c};return b}()});