// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/assignHelper ../../../../core/tsSupport/extendsHelper ../../../../core/promiseUtils ../../../../core/promiseUtils ../../../../core/libs/gl-matrix/mat4 ../../../../core/libs/gl-matrix/vec3 ../../../../geometry/Point ../Container ../StageGL ./enums ./GeometryUtils ./TextureManager ./Utils ./WGLPainter ./WGLRendererInfo".split(" "),function(q,r,u,v,w,x,l,n,y,z,A,p,B,C,t,D,E){Object.defineProperty(r,"__esModule",{value:!0});q=function(m){function c(a){var b=
m.call(this)||this;b._rendererInfo=new E;b._stage=new A;b._container=null;b._tileCoordinateScale=n.create();b._orientationVec=n.fromValues(0,0,1);b._displayScale=n.create();b._defaultTransform=l.create();b._pointToCallbacks=new Map;b._highlightIDs=new Set;b._invisibleFeatures=new Set;b._displayWidth=0;b._displayHeight=0;b._highlightOptionsUpToDate=!1;b.layer=null;b.textureManager=new C;b.highlightOptions=a.highlightOptions;b.tileInfoView=a.tileInfoView;b._stage.useContextVersion("webgl");b.layer=
a.layer;b._layerView=a.layerView;return b}v(c,m);c.prototype.fadeInLabels=function(){this._stage.fadeInLabels()};c.prototype.dispose=function(){this.textureManager&&(this.textureManager.dispose(),this.textureManager=null);this.removeAllChildren();for(var a=0,b=this.children;a<b.length;a++)b[a].dispose()};c.prototype.disposeWebGLResources=function(){for(var a=0,b=this.children;a<b.length;a++)b[a].clear()};c.prototype.displayWidth=function(){return this._displayWidth};Object.defineProperty(c.prototype,
"displayHeight",{get:function(){return this._displayHeight},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"highlightOptions",{get:function(){return this._highlightOptions},set:function(a){this._highlightOptions=a;this._highlightOptionsUpToDate=!1},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"visualVariablesInfo",{get:function(){return this._visualVariablesInfo},set:function(a){this._visualVariablesInfo=a;this.requestRender()},enumerable:!0,configurable:!0});
c.prototype.install=function(a){a.addChild(this._stage);this._stage.addChild(this);this._container=a};c.prototype.uninstall=function(a){a.removeChild(this._stage);this._stage.removeChild(this);this.dispose();this._container=null};c.prototype.hitTest=function(a,b){var e=this,d=[a,b];return w.create(function(a,b){e._pointToCallbacks.set(d,{resolve:a,reject:b});e.requestRender()},function(){e._pointToCallbacks.has(d)&&e._pointToCallbacks.delete(d)})};c.prototype.highlight=function(a){var b=this;b.addHighlight(a);
return{remove:function(){b.removeHighlight(a)}}};c.prototype.setHighlight=function(a){this._highlightIDs.clear();this.addHighlight(a)};c.prototype.setVisibility=function(a,b){a||(a=[]);b||(b=[]);for(var e=this._invisibleFeatures,d=0,c=a;d<c.length;d++){var f=c[d];e.has(f)&&e.delete(f)}d=0;for(c=b;d<c.length;d++)e.add(c[d]);e=0;for(d=this.children;e<d.length;e++)c=d[e],c.data&&c.setVisibility(a,b)};c.prototype.setVisibilityRange=function(a,b,e,c){for(var d=0,f=this.children;d<f.length;d++){var g=f[d];
g.data&&g.data.tileDisplayData.displayObjectRegistry.has(a)&&g.setVisibilityRange(a,b,e,c)}};c.prototype.addHighlight=function(a){for(var b=0;b<a.length;b++)this._highlightIDs.add(a[b]);this._buildHLList()};c.prototype.removeHighlight=function(a){for(var b=0;b<a.length;b++)this._highlightIDs.delete(a[b]);this._buildHLList()};c.prototype.getMaterialItems=function(a){if(a&&0!==a.length){for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push(this.textureManager.rasterizeItem(d.symbol,d.glyphIds))}return x.all(b).then(function(a){return a.map(function(a,
b){return{id:b,mosaicItem:a}})})}};c.prototype.onTileData=function(a,b){a.setData(b,!(!this.layer.labelingInfo||!this.layer.labelingInfo.length),this.layer.labelsVisible);a.resetVisibility(this._invisibleFeatures);a.buildHLList(this._highlightIDs);this.contains(a)||this.addChild(a);this.fadeInLabels();this.requestRender();this._layerView&&this._layerView.view.labelManager.requestUpdate()};c.prototype.onTileError=function(a){a.clear();a.buildHLList(this._highlightIDs);this.contains(a)||this.addChild(a);
this.requestRender()};c.prototype.addChild=function(a){var b=m.prototype.addChild.call(this,a);this.layer.labelingInfo&&this._layerView&&this._layerView.view.labelManager.addTile(this.layer.uid,a);this._buildHLList();return b};c.prototype.removeChild=function(a){var b=m.prototype.removeChild.call(this,a);this.layer.labelingInfo&&this._layerView&&this._layerView.view.labelManager.removeTile(this.layer.uid,a.key.id);this._buildHLList();return b};c.prototype.prepareChildrenRenderParameters=function(a){this._rendererInfo.updateVisualVariables(this._visualVariablesInfo.vvRanges,
a.state);var b=this.tileInfoView.getClosestInfoForScale(a.state.scale).level,c=this.tileInfoView.tileInfo.scaleToZoom(a.state.scale);return u({},a,{rendererInfo:this._rendererInfo,requiredLevel:b,displayLevel:c})};c.prototype.renderChildren=function(a){var b=this,c=a.painter;c.bindTextureManager(this.textureManager);this._rendererInfo.updateVisualVariables(this._visualVariablesInfo.vvRanges,a.state);this.sortChildren(function(a,b){return 0!==a.key.level-b.key.level?a.key.level-b.key.level:0!==a.key.row-
b.key.row?a.key.row-b.key.row:a.key.col-b.key.col});var d=D.default.toWGLDrawPhases(a.drawPhase);if(0<d.length&&d[0]===p.WGLDrawPhase.LABEL||d[0]===p.WGLDrawPhase.LABEL_ALPHA){var h=this.layer;if(!(h.labelsVisible&&h.labelingInfo&&0<h.labelingInfo.length))return;this._updateTilesTransform(a.state,a.requiredLevel);c.update(a.state,a.pixelRatio)}c.draw(a,this.children,d,this._painterOptions);0<this._highlightIDs.size&&c.highlight(a,this.children);0!==this._pointToCallbacks.size&&(this._pointToCallbacks.forEach(function(c,
d){c.resolve(b._hitTest(a,d[0],d[1]))}),this._pointToCallbacks.clear())};c.prototype.attachChild=function(a,b){return a.attach(b)};c.prototype.detachChild=function(a,b){a.detach(b)};c.prototype.renderChild=function(a,b){a.doRender(b)};c.prototype.beforeRenderChildren=function(a,b){this._updateTilesTransform(a.state,this.tileInfoView.getClosestInfoForScale(a.state.scale).level);this._updateHighlightOptions();this._stage.opacity=this._container.opacity};c.prototype._hitTest=function(a,b,c){var d=a.painter,
e=a.requiredLevel,f=[0,0];a.state.toMap(f,[b,c]);b=a.state.clone();c=b.viewpoint.clone();c.targetGeometry=new y(f[0],f[1],a.state.spatialReference);b.viewpoint=c;b.size=[t.C_HITTEST_SEARCH_SIZE,t.C_HITTEST_SEARCH_SIZE];this._updateTilesTransform(b,e);d.update(b,a.pixelRatio);return d.hitTest({context:a.context,drawPhase:p.WGLDrawPhase.HITTEST,painter:d,pixelRatio:a.pixelRatio,displayLevel:a.displayLevel,rendererInfo:this._rendererInfo,requiredLevel:e,state:b,stationary:a.stationary},this.children)};
c.prototype._updateTilesTransform=function(a,b){var c=1/a.width,d=1/a.height,h=[0,0];this._calculateRelativeViewProjMat(this.tileInfoView.tileInfo.lods[b].resolution,a.resolution,a.rotation,this.tileInfoView.tileInfo.size[0],a.width,a.height,this._defaultTransform);for(var f=0,g=this.children;f<g.length;f++){var k=g[f];a.toScreen(h,k.coords);h[1]=a.height-h[1];k.tileTransform.displayCoord[0]=2*h[0]*c-1;k.tileTransform.displayCoord[1]=2*h[1]*d-1;k.key.level===b?k.tileTransform.transform.set(this._defaultTransform):
this._calculateRelativeViewProjMat(this.tileInfoView.tileInfo.lods[k.key.level].resolution,a.resolution,a.rotation,this.tileInfoView.tileInfo.size[0],a.width,a.height,k.tileTransform.transform)}};c.prototype._calculateRelativeViewProjMat=function(a,b,c,d,h,f,g){a/=b;this._tileCoordinateScale.set([a,a,1]);if(h!==this._displayWidth||f!==this._displayHeight)this._displayScale.set([2/h,-2/f,1]),this._displayWidth=h,this._displayHeight=f;l.identity(g);l.scale(g,g,this._tileCoordinateScale);l.rotate(g,
g,-c*B.C_DEG_TO_RAD,this._orientationVec);l.scale(g,g,this._displayScale);l.transpose(g,g)};c.prototype._updateHighlightOptions=function(){if(!this._highlightOptionsUpToDate&&this.parent){var a=this.parent.glPainter,b=this._highlightOptions;if(a){var c=b.color.toRgba();c[0]/=255;c[1]/=255;c[2]/=255;var d=c.slice();c[3]*=b.fillOpacity;d[3]*=b.haloOpacity;a.setHighlightOptions({fillColor:c,outlineColor:d,outlineWidth:2,outerHaloWidth:.3,innerHaloWidth:.3,outlinePosition:0})}}};c.prototype._buildHLList=
function(){for(var a=0,b=this.children;a<b.length;a++)b[a].buildHLList(this._highlightIDs);this.requestRender()};return c}(z);r.default=q});