// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ../../../../core/libs/gl-matrix/mat2d ../../../../core/libs/gl-matrix/mat4 ../../../../core/libs/gl-matrix/vec2 ../DisplayObject ./definitions ./DirtyMap ./DisplayRecordStore ./enums ./number ./TileData ./Utils ./WGLBuffers ./WGLDisplayList ../../tiling/enums ../../tiling/TileKey".split(" "),function(H,I,x,y,z,u,A,r,v,w,n,B,C,q,D,E,l,F){function G(l,a){return l.sortKey-a.sortKey}return function(t){function a(b,k){var c=t.call(this)||
this;c.status=l.TileStatus.INITIALIZED;c._data=null;c.hlDisplayList=null;c._displayList=null;c._wglBuffers=null;c._dirtyMap=new v.default;c.coords=[0,0];c.bounds=[0,0,0,0];c.tileTransform={transform:Float32Array[16],screenTransform:Float32Array[16],displayCoord:Float32Array[2],screenCoord:Float32Array[2]};c._labelIndex=null;c.tileTransform.screenTransform=y.create();c.tileTransform.transform=z.create();c.tileTransform.displayCoord=u.create();c.tileTransform.screenCoord=u.create();c.key=F.pool.acquire(b);
c.coords[0]=k[0];c.coords[1]=k[3];c.bounds=k;return c}x(a,t);Object.defineProperty(a.prototype,"iconGeometry",{get:function(){return this.getGeometry(n.WGLGeometryType.MARKER)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"textGeometry",{get:function(){return this.getGeometry(n.WGLGeometryType.TEXT)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"fillGeometry",{get:function(){return this.getGeometry(n.WGLGeometryType.FILL)},enumerable:!0,configurable:!0});
Object.defineProperty(a.prototype,"lineGeometry",{get:function(){return this.getGeometry(n.WGLGeometryType.LINE)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"labelGeometry",{get:function(){return this.getGeometry(n.WGLGeometryType.LABEL)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"displayObjects",{get:function(){return this._data.tileDisplayData.displayObjects},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"canDisplay",{get:function(){return!!this.attached},
enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"isDirty",{get:function(){return this.status===l.TileStatus.MODIFIED},set:function(b){this.hasData&&(b&&this.status===l.TileStatus.READY?this.setStatus(l.TileStatus.MODIFIED):b||this.status!==l.TileStatus.MODIFIED||this.setStatus(l.TileStatus.READY),this.requestRender())},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"hasData",{get:function(){return!!this._data},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,
"labelIndex",{get:function(){return this._labelIndex},enumerable:!0,configurable:!0});a.prototype.getGeometry=function(b){return this._wglBuffers&&this._wglBuffers.has(b)?this._wglBuffers.get(b):null};a.prototype.getDisplayList=function(b){switch(b){case n.WGLDrawPhase.HIGHLIGHT:return this.hlDisplayList;default:return this._data&&this._displayList}};Object.defineProperty(a.prototype,"data",{get:function(){return this._data},enumerable:!0,configurable:!0});a.prototype.setData=function(b,k,c){var a=
b.addOrUpdate&&C.decode(b.addOrUpdate),e=b.remove;!b.clear&&this.hasData||b.addOrUpdate?!b.clear&&this.hasData||!b.addOrUpdate?this.hasData&&this._doPatchData({addOrUpdate:a,remove:e},k,c):(this._dirtyMap=new v.default,this._dispRecStore=w.default.fromTileData(a,this._dirtyMap),this._data=a,this._readyTileIfNoLabels(k,c),this._dirtyMap.markAllDirty(),this._displayList||(this._displayList=a.tileDisplayData.displayList.clone())):(this.clear(),this.setStatus(l.TileStatus.NO_DATA))};a.prototype.commitChanges=
function(b){this._data&&(this.status===l.TileStatus.READY||this.status===l.TileStatus.MODIFIED&&!this._wglBuffers)&&(this._wglBuffers||(this._wglBuffers=new D.default(b.context)),this._displayList=this._data.tileDisplayData.displayList.clone(),this._wglBuffers.upload(this._data.tileBufferData,this._dirtyMap),this._dirtyMap.markAllClean())};a.prototype.resetVisibility=function(b){var k=this,c=[],a=Array(1);b.forEach(function(b){a[0]=b;k.setVisibility(c,a)})};a.prototype.setVisibility=function(b,k){for(var c=
this._data.tileBufferData.geometries.map(function(b){return{vertexFrom:void 0,vertexTo:void 0,geometry:b}}),a=0;a<b.length;a++){var e=this._data.tileDisplayData.displayObjectRegistry.get(b[a]);if(e)for(var f=0,h=e.displayRecords;f<h.length;f++){var d=h[f],g=c[d.geometryType];if(e=g.geometry.vertexBuffer[q.C_VBO_VISIBILITY]){g.vertexFrom=null==g.vertexFrom?d.vertexFrom:Math.min(g.vertexFrom,d.vertexFrom);g.vertexTo=null==g.vertexTo?d.vertexFrom+d.vertexCount:Math.max(g.vertexTo,d.vertexFrom+d.vertexCount);
for(var g=d.vertexFrom,d=d.vertexCount,m=0;m<d;++m)e.data[g+m]=255}}}for(b=0;b<k.length;b++)if(e=this._data.tileDisplayData.displayObjectRegistry.get(k[b]))for(a=0,f=e.displayRecords;a<f.length;a++)if(d=f[a],g=c[d.geometryType],e=g.geometry.vertexBuffer[q.C_VBO_VISIBILITY])for(g.vertexFrom=null==g.vertexFrom?d.vertexFrom:Math.min(g.vertexFrom,d.vertexFrom),g.vertexTo=null==g.vertexTo?d.vertexFrom+d.vertexCount:Math.max(g.vertexTo,d.vertexFrom+d.vertexCount),g=d.vertexFrom,d=d.vertexCount,m=0;m<d;++m)e.data[g+
m]=0;k=!1;for(e=0;e<c.length;++e)g=c[e],null!=g.vertexFrom&&null!=g.vertexTo&&(this._dirtyMap.markDirtyVertices(e,q.C_VBO_VISIBILITY,g.vertexFrom,g.vertexTo?g.vertexTo-g.vertexFrom:0),k=!0);k&&this.requestRender()};a.prototype.setVisibilityRange=function(b,a,c,p){c=B.i8888to32(c,p,c,p);var k=p=void 0,f=this._data.tileBufferData.geometries[n.WGLGeometryType.LABEL].vertexBuffer[q.C_VBO_VISIBILITY_RANGE];b=this._data.tileDisplayData.displayObjectRegistry.get(b);a=b.metrics[a];var h=a.range.from;for(a=
h+a.range.count;h<a;++h){var d=b.displayRecords[h];if(d.geometryType===n.WGLGeometryType.LABEL){p=null==p?d.vertexFrom:Math.min(p,d.vertexFrom);for(var k=null==k?d.vertexFrom+d.vertexCount:Math.max(k,d.vertexFrom+d.vertexCount),g=d.vertexFrom*f.stride/4,d=d.vertexCount*f.stride/4,m=0;m<d;++m)f.data[g+m]=c}}this._dirtyMap.markDirtyVertices(n.WGLGeometryType.LABEL,q.C_VBO_VISIBILITY_RANGE,p,k?k-p:0)};a.prototype.setStatus=function(b){this.status=b;if(b===l.TileStatus.READY||b===l.TileStatus.NO_DATA)this.attached=
!0};a.prototype.clear=function(){this.attached=!1;this._dispRecStore=this._displayList=this._data=null;this.setStatus(l.TileStatus.INITIALIZED);this._wglBuffers&&(this._wglBuffers.dispose(),this._wglBuffers=null);this.hlDisplayList&&(this.hlDisplayList=null)};a.prototype.dispose=function(){this.clear()};a.prototype.attach=function(b){return this.canDisplay};a.prototype.detach=function(b){t.prototype.detach.call(this,b)};a.prototype.doRender=function(b){var a=this;this.attached&&this.hasData&&(this.commitChanges(b),
b.context.setStencilFunction(514,this.stencilRef,255),b.painter.getBrushes(b.drawPhase).forEach(function(c){return c.draw(b,a)}))};a.prototype.buildHLList=function(b){var a=this;this.hlDisplayList=new E;b.forEach(function(b){a._addToHLDisplayList(a.hlDisplayList,b)})};a.prototype._addToHLDisplayList=function(b,a){if(this._data){var c=this._data.tileDisplayData.displayObjectRegistry.get(a);if(c){a=[];for(var k=0,c=c.displayRecords;k<c.length;k++){var e=c[k].copy();e.meshData=null;e.symbolLevel=0;e.zOrder=
0;a.push(e)}a.sort(G);b.addToList(a)}}};a.prototype._readyTileIfNoLabels=function(b,a){b?(this.setStatus(a?l.TileStatus.MODIFIED:l.TileStatus.READY),this._rebuildLabelIndex()):this.setStatus(l.TileStatus.READY)};a.prototype._doPatchData=function(b,a,c){this._patchData(b)||(this._dirtyMap.markAllDirty(),this._data.reshuffle(),this._dispRecStore=w.default.fromTileData(this._data,this._dirtyMap));this._readyTileIfNoLabels(a,c);this.requestRender()};a.prototype._rebuildLabelIndex=function(){this._labelIndex=
this._initLabelIndex();for(var b=0,a=this.displayObjects;b<a.length;b++)this._insertIntoLabelIndex(a[b])};a.prototype._insertIntoLabelIndex=function(b){var a=b.anchor;-1!==b.xBucket&&a&&this.labelIndex[b.yBucket][b.xBucket].push(b)};a.prototype._initLabelIndex=function(){for(var b=[],a=0;a<r.TILE_SIZE/r.COLLISION_BUCKET_SIZE;a++){b.push([]);for(var c=0;c<r.TILE_SIZE/r.COLLISION_BUCKET_SIZE;c++)b[a].push([])}return b};a.prototype._patchData=function(a){for(var b=!0,c=0,l=a.remove||[];c<l.length;c++){var e=
l[c],f=this._data.tileDisplayData.displayObjectRegistry.get(e);if(f){this._data.tileDisplayData.displayList.removeFromList(f.displayRecords);for(var h=0,d=f.displayRecords;h<d.length;h++)this._dispRecStore.delete(d[h]);this._data.tileDisplayData.displayObjectRegistry.delete(e);f=this._data.tileDisplayData.displayObjects.indexOf(f);this._data.tileDisplayData.displayObjects.splice(f,1)}}c=0;for(l=a.addOrUpdate&&a.addOrUpdate.tileDisplayData&&a.addOrUpdate.tileDisplayData.displayObjects||[];c<l.length;c++){e=
l[c];if(f=this._data.tileDisplayData.displayObjectRegistry.get(e.id)){h=f.displayRecords;f.set(e);f.displayRecords=h;for(var g=f.displayRecords.length,h=0;h<g;++h){var d=f.displayRecords[h],m=e.displayRecords[h];if(h>=e.displayRecords.length||d.geometryType!==m.geometryType||d.symbolLevel!==m.symbolLevel||d.zOrder!==m.zOrder||d.materialInfo.materialKey!==m.materialInfo.materialKey)this._dispRecStore.delete(f.displayRecords[h]),h<e.displayRecords.length&&(f.displayRecords[h]=void 0)}f.displayRecords.length=
e.displayRecords.length;f.anchor=e.anchor;f.metrics=e.metrics}else f=e.copy(),f.displayRecords=[],this._data.tileDisplayData.displayObjectRegistry.set(e.id,f),this._data.tileDisplayData.displayObjects.push(f);g=e.displayRecords.length;for(h=0;h<g;++h){m=e.displayRecords[h];(d=f.displayRecords[h])?(d.meshData=m.meshData,d.materialInfo=m.materialInfo):(d=m.copy(),d.vertexFrom=void 0,d.indexFrom=void 0,f.displayRecords[h]=d);var n=a.addOrUpdate.tileBufferData.geometries[m.geometryType],b=this._dispRecStore.setMeshData(d,
m,n.vertexBuffer,n.indexBuffer)&&b}}return b};return a}(A)});