// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","../../lib/gl-matrix","../../support/mathUtils"],function(u,v,c,q){Object.defineProperty(v,"__esModule",{value:!0});var r=q.angle,t=q.lerp,y=q.slerp,g=c.vec3d.create(),k=c.vec3d.create(),h=c.vec3d.create(),d=c.vec3d.create(),l=c.vec3d.create(),n=c.vec3d.create(),m=c.vec3d.createFrom(0,0,1),w=c.vec3d.createFrom(0,1,0),p=c.vec3d.createFrom(1,0,0),x=c.mat3d.create();u=function(){function f(a){void 0===a&&(a="global");this.viewingMode=a;this.center=c.vec3d.create();this.distance=
this.yaw=this.pitch=0;this.lookAtDirection=c.vec3d.create(w)}f.prototype.pixelsPerPanAtZoom=function(a){return this.size/2/(this._zoomToPanScale*a)};f.prototype.zoomAtPixelsPerPan=function(a){return this.size/2/(this._zoomToPanScale*a)};f.prototype.pixelsPerRotateAtZoom=function(a){return this.size/2/Math.max(Math.cos(Math.abs(this.pitch)),.5)};f.prototype.compareTo=function(a,b){b||(b={pan:0,rotate:0,sourceZoom:0,targetZoom:0});if("global"===this.viewingMode){var e=c.vec3d.length(this.center),d=
c.vec3d.length(a.center),e=(e+d)/2;b.pan=r(this.center,a.center)*e}else b.pan=c.vec3d.dist(this.center,a.center);e=Math.abs(a.yaw-this.yaw);e>=Math.PI&&(e=2*Math.PI-e);b.rotate=Math.max(e,Math.abs(a.pitch-this.pitch));b.sourceZoom=this.distance;b.targetZoom=a.distance;return b};f.prototype.interpolate=function(a,b,e){"global"===this.viewingMode?y(a.center,b.center,e.pan,this.center):c.vec3d.lerp(a.center,b.center,e.pan,this.center);this.distance=t(a.distance,b.distance,e.zoom);this.pitch=t(a.pitch,
b.pitch,e.rotate);a=a.yaw;b=b.yaw;Math.abs(b-a)>=Math.PI&&(a+=2*(a<b?1:-1)*Math.PI);this.yaw=t(a,b,e.rotate)};f.prototype.copyFrom=function(a){c.vec3d.set(a.center,this.center);this.pitch=a.pitch;this.yaw=a.yaw;this.distance=a.distance;c.vec3d.set(a.lookAtDirection,this.lookAtDirection);this.size=a.size;this.copyFromCommon(a);this.viewingMode=a.viewingMode};f.prototype.copyFromRenderCamera=function(a){var b=this._lookAtOrientation(a.center,x);c.vec3d.set(a.center,this.center);c.mat3d.multiplyVec3(b,
c.vec3d.subtract(a.center,a.eye,d));c.mat3d.multiplyVec3(b,a.up,l);this.distance=c.vec3d.length(d);d[0]/=this.distance;d[1]/=this.distance;d[2]/=this.distance;this.pitch=this._eyeUpToPitch(d,l);this.yaw=this._eyeUpToYaw(d,l);this.size=Math.sqrt(a.width*a.width+a.height*a.height);this.copyFromCommon(a)};f.prototype.copyFromCommon=function(a){this.fov=a.fov;this._zoomToPanScale=Math.atan(.5*this.fov)};f.prototype.copyToRenderCamera=function(a){var b=this._lookAtOrientation(this.center,x);c.mat3d.transpose(b);
this._axisAngleVec3(p,this.pitch-Math.PI/2,w,d);this._axisAngleVec3(m,this.yaw,d);this._axisAngleVec3(p,this.pitch-Math.PI/2,m,l);this._axisAngleVec3(m,this.yaw,l);c.vec3d.scale(d,this.distance);c.mat3d.multiplyVec3(b,d);c.mat3d.multiplyVec3(b,l);a.center=this.center;a.eye=c.vec3d.subtract(this.center,d,d);a.up=l};f.prototype._axisAngleVec3=function(a,b,e,d){void 0===d&&(d=e);var f=Math.cos(b);b=Math.sin(b);c.vec3d.scale(e,f,g);c.vec3d.scale(c.vec3d.cross(a,e,k),b);c.vec3d.scale(a,(1-f)*c.vec3d.dot(a,
e),h);return c.vec3d.add(c.vec3d.add(g,k,d),h,d)};f.prototype._lookAtOrientation=function(a,b){this._upAtLookAt(a,h);c.vec3d.normalize(c.vec3d.cross(this.lookAtDirection,h,g));0===g[0]&&0===g[1]&&0===g[2]&&c.vec3d.set(p,g);c.vec3d.normalize(c.vec3d.cross(h,g,k));b||(b=c.mat3d.create());b[0]=g[0];b[1]=k[0];b[2]=h[0];b[3]=g[1];b[4]=k[1];b[5]=h[1];b[6]=g[2];b[7]=k[2];b[8]=h[2];return b};f.prototype._upAtLookAt=function(a,b){return"local"===this.viewingMode?c.vec3d.set(m,b):c.vec3d.normalize(a,b)};f.prototype._eyeUpToPitch=
function(a,b){return Math.PI-r(m,a)};f.prototype._eyeUpToYaw=function(a,b){.5>Math.abs(b[2])?(c.vec3d.set(b,n),0<a[2]&&c.vec3d.scale(n,-1)):c.vec3d.set(a,n);return r(p,c.vec3d.normalize(c.vec3d.cross(n,m,k)),m)};return f}();v.default=u});