// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/extendsHelper ./internals/Mat3 ./internals/Mat4 ./internals/Single ./internals/Vec2 ./internals/Vec3 ./internals/Vec4".split(" "),function(p,g,h,q,e,k,l,m,n){Object.defineProperty(g,"__esModule",{value:!0});p=function(b){function a(f,a,d){void 0===a&&(a=0);f=b.call(this,Float32Array,f,a,d)||this;f.elementType="f32";return f}h(a,b);a.ElementType="f32";return a}(k.BufferViewSingle);g.BufferViewFloat=p;p=function(b){function a(f,a,d,e){void 0===a&&(a=
0);f=b.call(this,Float32Array,f,a,d,e)||this;f.elementType="f32";return f}h(a,b);a.ElementType="f32";return a}(l.BufferViewVec2Impl);g.BufferViewVec2f=p;p=function(b){function a(f,a,d,e){void 0===a&&(a=0);f=b.call(this,Float32Array,f,a,d,e)||this;f.elementType="f32";return f}h(a,b);a.ElementType="f32";return a}(m.BufferViewVec3Impl);g.BufferViewVec3f=p;p=function(b){function a(f,a,d,e){void 0===a&&(a=0);f=b.call(this,Float32Array,f,a,d,e)||this;f.elementType="f32";return f}h(a,b);a.ElementType="f32";
return a}(n.BufferViewVec4Impl);g.BufferViewVec4f=p;q=function(b){function a(f,a,d){void 0===a&&(a=0);f=b.call(this,Float32Array,f,a,d)||this;f.elementType="f32";return f}h(a,b);a.ElementType="f32";return a}(q.BufferViewMat3);g.BufferViewMat3f=q;e=function(b){function a(f,a,d){void 0===a&&(a=0);f=b.call(this,Float32Array,f,a,d)||this;f.elementType="f32";return f}h(a,b);a.ElementType="f32";return a}(e.BufferViewMat4);g.BufferViewMat4f=e;e=function(b){function a(f,a,d){void 0===a&&(a=0);f=b.call(this,
Float64Array,f,a,d)||this;f.elementType="f64";return f}h(a,b);a.ElementType="f64";return a}(k.BufferViewSingle);g.BufferViewFloat64=e;e=function(b){function a(f,a,d){void 0===a&&(a=0);f=b.call(this,Float64Array,f,a,d)||this;f.elementType="f64";return f}h(a,b);a.ElementType="f64";return a}(l.BufferViewVec2Impl);g.BufferViewVec2f64=e;e=function(b){function a(f,a,d){void 0===a&&(a=0);f=b.call(this,Float64Array,f,a,d)||this;f.elementType="f64";return f}h(a,b);a.ElementType="f64";return a}(m.BufferViewVec3Impl);
g.BufferViewVec3f64=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Float64Array,a,c,d)||this;a.elementType="f64";return a}h(a,b);a.ElementType="f64";return a}(n.BufferViewVec4Impl);g.BufferViewVec4f64=e;e=function(b){function a(a,c,d,e){void 0===c&&(c=0);a=b.call(this,Uint8Array,a,c,d,e)||this;a.elementType="u8";return a}h(a,b);a.ElementType="u8";return a}(k.BufferViewSingle);g.BufferViewUint8=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Uint8Array,a,c,d)||
this;a.elementType="u8";return a}h(a,b);a.ElementType="u8";return a}(l.BufferViewVec2Impl);g.BufferViewVec2u8=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Uint8Array,a,c,d)||this;a.elementType="u8";return a}h(a,b);a.ElementType="u8";return a}(m.BufferViewVec3Impl);g.BufferViewVec3u8=e;e=function(b){function a(a,c,d,e){void 0===c&&(c=0);a=b.call(this,Uint8Array,a,c,d,e)||this;a.elementType="u8";return a}h(a,b);a.ElementType="u8";return a}(n.BufferViewVec4Impl);g.BufferViewVec4u8=
e;e=function(b){function a(a,c,d,e){void 0===c&&(c=0);a=b.call(this,Uint16Array,a,c,d,e)||this;a.elementType="u16";return a}h(a,b);a.ElementType="u16";return a}(k.BufferViewSingle);g.BufferViewUint16=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Uint16Array,a,c,d)||this;a.elementType="u16";return a}h(a,b);a.ElementType="u16";return a}(l.BufferViewVec2Impl);g.BufferViewVec2u16=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Uint16Array,a,c,d)||this;a.elementType=
"u16";return a}h(a,b);a.ElementType="u16";return a}(m.BufferViewVec3Impl);g.BufferViewVec3u16=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Uint16Array,a,c,d)||this;a.elementType="u16";return a}h(a,b);a.ElementType="u16";return a}(n.BufferViewVec4Impl);g.BufferViewVec4u16=e;e=function(b){function a(a,c,d,e){void 0===c&&(c=0);a=b.call(this,Uint32Array,a,c,d,e)||this;a.elementType="u32";return a}h(a,b);a.ElementType="u32";return a}(k.BufferViewSingle);g.BufferViewUint32=e;e=function(b){function a(a,
c,d){void 0===c&&(c=0);a=b.call(this,Uint32Array,a,c,d)||this;a.elementType="u32";return a}h(a,b);a.ElementType="u32";return a}(l.BufferViewVec2Impl);g.BufferViewVec2u32=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Uint32Array,a,c,d)||this;a.elementType="u32";return a}h(a,b);a.ElementType="u32";return a}(m.BufferViewVec3Impl);g.BufferViewVec3u32=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Uint32Array,a,c,d)||this;a.elementType="u32";return a}h(a,b);a.ElementType=
"u32";return a}(n.BufferViewVec4Impl);g.BufferViewVec4u32=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int8Array,a,c,d)||this;a.elementType="i8";return a}h(a,b);a.ElementType="i8";return a}(k.BufferViewSingle);g.BufferViewInt8=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int8Array,a,c,d)||this;a.elementType="i8";return a}h(a,b);a.ElementType="i8";return a}(l.BufferViewVec2Impl);g.BufferViewVec2i8=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,
Int8Array,a,c,d)||this;a.elementType="i8";return a}h(a,b);a.ElementType="i8";return a}(m.BufferViewVec3Impl);g.BufferViewVec3i8=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int8Array,a,c,d)||this;a.elementType="i8";return a}h(a,b);a.ElementType="i8";return a}(n.BufferViewVec4Impl);g.BufferViewVec4i8=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int16Array,a,c,d)||this;a.elementType="i16";return a}h(a,b);a.ElementType="i16";return a}(k.BufferViewSingle);g.BufferViewInt16=
e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int16Array,a,c,d)||this;a.elementType="i16";return a}h(a,b);a.ElementType="i16";return a}(l.BufferViewVec2Impl);g.BufferViewVec2i16=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int16Array,a,c,d)||this;a.elementType="i16";return a}h(a,b);a.ElementType="i16";return a}(m.BufferViewVec3Impl);g.BufferViewVec3i16=e;e=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int16Array,a,c,d)||this;a.elementType="i16";
return a}h(a,b);a.ElementType="i16";return a}(n.BufferViewVec4Impl);g.BufferViewVec4i16=e;k=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int32Array,a,c,d)||this;a.elementType="i32";return a}h(a,b);a.ElementType="i32";return a}(k.BufferViewSingle);g.BufferViewInt32=k;l=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int32Array,a,c,d)||this;a.elementType="i32";return a}h(a,b);a.ElementType="i32";return a}(l.BufferViewVec2Impl);g.BufferViewVec2i32=l;m=function(b){function a(a,
c,d){void 0===c&&(c=0);a=b.call(this,Int32Array,a,c,d)||this;a.elementType="i32";return a}h(a,b);a.ElementType="i32";return a}(m.BufferViewVec3Impl);g.BufferViewVec3i32=m;n=function(b){function a(a,c,d){void 0===c&&(c=0);a=b.call(this,Int32Array,a,c,d)||this;a.elementType="i32";return a}h(a,b);a.ElementType="i32";return a}(n.BufferViewVec4Impl);g.BufferViewVec4i32=n});