// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper dojo/i18n!../../../nls/common dojo/i18n!../../Legend/nls/Legend dojox/gfx ../../../core/lang ../../../core/screenUtils ../../../core/accessorSupport/decorators ../../Widget ./common ../support/styleUtils ../../support/colorUtils ../../support/widget".split(" "),function(V,W,P,t,Q,A,C,R,B,w,S,T,z,U,d){var y;(function(d){d.Auto="auto";d.Stack="stack";d.SideBySide="side-by-side"})(y||(y={}));var E=
function(d){return{width:B.pt2px(d.width),height:B.pt2px(d.height)}};return function(D){function k(a){a=D.call(this)||this;a._hasIndicators=!1;a._selectedSectionName=null;a._sectionNames=[];a._sectionMap=new Map;a.activeLayerInfos=null;a.layout=y.Stack;a.type="card";a.view=null;return a}P(k,D);k.prototype.render=function(){var a=this,f;this._sectionNames.length=0;this._hasIndicators=this.layout===y.Auto&&768>=this.view.container.clientWidth||this.layout===y.Stack;var e=this.activeLayerInfos,b=e&&
e.toArray().map(function(b){return a._renderLegendForLayer(b)}).filter(function(a){return!!a});this._hasIndicators?this._selectedSectionName&&-1!==this._sectionNames.indexOf(this._selectedSectionName)||(this._selectedSectionName=this._sectionNames&&this._sectionNames[0]):this._selectedSectionName=null;var h=this._sectionNames.length,e=this._sectionNames.map(function(b,c){var e;c=R.substitute({index:c+1,total:h},Q.pagination.pageText);return d.tsx("div",{key:b,"aria-label":c,title:c,tabIndex:0,onclick:a._selectSection,
onkeydown:a._selectSection,bind:a,class:a.classes("esri-legend--card__carousel-indicator",(e={},e["esri-legend--card__carousel-indicator--activated"]=a._selectedSectionName===b,e)),"data-section-name":b})}),e=this._hasIndicators?d.tsx("div",{class:"esri-legend--card__carousel-indicator-container",key:"carousel-navigation"},e):null,b=this._hasIndicators?this._sectionMap.get(this._selectedSectionName):b&&b.length?b:null,c=(f={},f["esri-legend--stacked"]=this._hasIndicators,f);return d.tsx("div",{class:this.classes("esri-legend--card esri-widget",
c)},e,b?b:d.tsx("div",{class:"esri-legend--card__message"},A.noLegend))};k.prototype._selectSection=function(a){if(a=a.target.getAttribute("data-section-name"))this._selectedSectionName=a};k.prototype._renderLegendForLayer=function(a){var f=this,e;if(!a.ready)return null;var b="esri-legend--card__"+a.layer.uid+"-version-"+a.version;if(a.children.length)return e=a.children.map(function(a){return f._renderLegendForLayer(a)}).toArray(),this._sectionNames.push(b),d.tsx("div",{key:a.layer.uid,class:this.classes("esri-legend--card__service",
"esri-legend--card__group-layer")},d.tsx("div",{class:"esri-legend--card__service-caption-container"},a.title),e);if((b=a.legendElements)&&!b.length)return null;var h=b.some(function(a){return"relationship-ramp"===a.type}),b=b.map(function(b){return f._renderLegendForElement(b,a.layer,h)}).filter(function(a){return!!a});if(!b.length)return null;var c=(e={},e["esri-legend--card__group-layer-child"]=!!a.parent,e);return d.tsx("div",{key:a.layer.uid,class:this.classes("esri-legend--card__service",c)},
d.tsx("div",{class:"esri-legend--card__service-caption-container"},d.tsx("div",{class:"esri-legend--card__service-caption-text"},a.title)),d.tsx("div",{class:"esri-legend--card__service-content"},b))};k.prototype._renderLegendForElement=function(a,f,e){var b=this;void 0===e&&(e=!1);var h,c="color-ramp"===a.type,l="opacity-ramp"===a.type,u="size-ramp"===a.type,p=a.title,q=null;"string"===typeof p?q=p:p&&(q=z.getTitle(p,c||l),q=p.title?p.title+" ("+q+")":q);p="esri-legend--card__"+f.uid+"-type-"+a.type;
q=this._hasIndicators?d.tsx("div",null,d.tsx("h3",{class:this.classes("esri-widget__heading","esri-legend--card__carousel-title")},f.title),d.tsx("h4",{class:this.classes("esri-widget__heading","esri-legend--card__layer-caption")},q)):q?d.tsx("h4",{class:this.classes("esri-widget__heading","esri-legend--card__layer-caption")},q):null;c=null;"symbol-table"===a.type?(u=a.infos.map(function(c){return b._renderLegendForElementInfo(c,f,a.legendType)}).filter(function(a){return!!a}),u.length&&(c=u[0].properties.classes&&
u[0].properties.classes["esri-legend--card__symbol-row"],e=(h={},h["esri-legend--card__label-container"]=!c&&!e,h["esri-legend--card__relationship-label-container"]=e,h),c=d.tsx("div",{key:p,class:"esri-legend--card__section"},q,d.tsx("div",{class:this.classes(e)},u)))):"color-ramp"===a.type||"opacity-ramp"===a.type||"heatmap-ramp"===a.type?c=d.tsx("div",{key:p,class:"esri-legend--card__section"},q,this._renderLegendForRamp(a)):u?c=d.tsx("div",{key:p,class:"esri-legend--card__section"},q,this._renderSizeRamps(a.infos)):
"relationship-ramp"===a.type&&(c=d.tsx("div",{key:p,class:this.classes("esri-legend--card__section","esri-legend--card__relationship-section")},q,T.renderRelationshipRamp(a,this.id)));if(!c)return null;this._sectionNames.push(p);this._sectionMap.set(p,c);return c};k.prototype._renderLegendForElementInfo=function(a,f,e){var b,h,c;if(a.type)return this._renderLegendForElement(a,f);e=z.isImageryStretchedLegend(f,e);if(a.symbol&&a.preview){if(-1===a.symbol.type.indexOf("simple-fill")){if(!a.label)return d.tsx("div",
{bind:a.preview,afterCreate:z.attachToNode});f=(b={},b["esri-legend--card__symbol-cell"]=this._hasIndicators,b);return d.tsx("div",{class:this.classes("esri-legend--card__layer-row",(h={},h["esri-legend--card__symbol-row"]=this._hasIndicators,h))},d.tsx("div",{class:this.classes(f),bind:a.preview,afterCreate:z.attachToNode}),d.tsx("div",{class:this.classes("esri-legend--card__image-label",(c={},c["esri-legend--card__label-cell"]=this._hasIndicators,c))},z.getTitle(a.label,!1)||""))}c=h=b=255;f=0;
var l=e=255,u=255,p=0,q=a.symbol.color&&a.symbol.color.a,k=a.symbol.outline&&a.symbol.outline.color.a;q&&(b=a.symbol.color.r,h=a.symbol.color.g,c=a.symbol.color.b,f=a.symbol.color.a);k&&(e=a.symbol.outline.color.r,l=a.symbol.outline.color.g,u=a.symbol.outline.color.b,p=a.symbol.outline.color.a);var t=U.isBright(a.symbol.color),g=t?"rgba(255, 255, 255, .6)":"rgba(0, 0, 0, .6)";return d.tsx("div",{class:"esri-legend--card__layer-row"},d.tsx("div",{key:a.label,class:"esri-legend--card__label-element",
styles:{background:q?"rgba("+b+", "+h+", "+c+", "+f+")":"none",color:t?"black":"white",textShadow:"-1px -1px 0 "+g+",\n                                              1px -1px 0 "+g+",\n                                              -1px 1px 0 "+g+",\n                                              1px 1px 0 "+g,border:k?"1px solid rgba("+e+", "+l+", "+u+", "+p+")":"none"}}," ",a.label," "))}if(a.src)return b=this._renderImage(a,f,e),d.tsx("div",{class:"esri-legend--card__layer-row"},b,d.tsx("div",{class:"esri-legend--card__image-label"},
a.label||""))};k.prototype._renderImage=function(a,f,e){var b,h=a.label,c=a.src,l=a.opacity;e=(b={},b["esri-legend--card__imagery-layer-image--stretched"]=e,b["esri-legend--card__symbol"]=!e,b);f={opacity:""+(null!=l?l:f.opacity)};return d.tsx("img",{alt:h,src:c,border:0,width:a.width,height:a.height,class:this.classes(e),styles:f})};k.prototype._renderSizeRamps=function(a){var f,e=document.createElement("div"),b,h=a[a.length-1].symbol.color,c,l,u=a[0].label,p=a[a.length-1].label,q=a[0].symbol.style&&
"circle"===a[0].symbol.style;try{if(this._hasIndicators)if(l=100,q){var k=B.pt2px(a[0].symbol.size),t=B.pt2px(a[a.length-1].symbol.size),g=k/2,r=t/2;c=2*g+2;var w=l-g-r,y=Math.sqrt(Math.pow(w,2)-Math.pow(g-r,2)),v=g*y/w,F=g+v,G=g+Math.sqrt(Math.pow(g,2)-Math.pow(v,2)),x=r*v/g,H=g+x,I=l-(r-Math.sqrt(Math.pow(r,2)-Math.pow(x,2))),v=g-v,x=g-x;b=C.createSurface(e,c,l);b.createCircle({cx:g,cy:g,r:g}).setFill(h).setStroke({color:"#ddd",width:1});b.createCircle({cx:g,cy:l-r,r:r}).setFill(h).setStroke({color:"#ddd",
width:1});b.createLine({x1:F,y1:G,x2:H,y2:I}).setStroke({color:"#ddd",width:1});b.createLine({x1:v,y1:G,x2:x,y2:I}).setStroke({color:"#ddd",width:1})}else{var A=E(a[0].symbol),J=A.width,K=A.height,D=E(a[a.length-1].symbol),L=D.width,M=D.height,m=Math.max(J,K),n=Math.max(L,M);c=m;b=C.createSurface(e,c,l);b.createRect({x:0,y:0,height:m,width:m}).setStroke({color:"#ddd",width:1});b.createRect({x:m/2-n/2,y:l-n,height:n,width:n}).setStroke({color:"#ddd",width:1});b.createImage({src:a[0].symbol.url,height:m,
width:m});b.createImage({src:a[a.length-1].symbol.url,height:n,width:n,y:l-n,x:m/2-n/2});b.createLine({x1:0,y1:m,x2:m/2-n/2,y2:l-n}).setStroke({color:"#ddd",width:1});b.createLine({x1:c,y1:m,x2:m/2+n/2,y2:l-n}).setStroke({color:"#ddd",width:1})}else{c=180;if(q)k=B.pt2px(a[0].symbol.size),t=B.pt2px(a[a.length-1].symbol.size),g=k/2,r=t/2,l=2*g,w=c-g-r,y=Math.sqrt(Math.pow(w,2)-Math.pow(g-r,2)),v=g*y/w,G=g-v,F=c-(g+Math.sqrt(Math.pow(g,2)-Math.pow(v,2))),x=r*v/g,I=g-x,H=r-Math.sqrt(Math.pow(r,2)-Math.pow(x,
2)),v=g+v,x=g+x,b=C.createSurface(e,c,l),b.createCircle({cx:c-g,cy:g,r:g}).setFill(h).setStroke({color:"#ddd",width:1}),b.createCircle({cx:r,cy:g,r:r}).setFill(h).setStroke({color:"#ddd",width:1}),b.createLine({x1:F,y1:G,x2:H,y2:I}).setStroke({color:"#ddd",width:1}),b.createLine({x1:F,y1:v,x2:H,y2:x}).setStroke({color:"#ddd",width:1});else{var N=E(a[0].symbol),J=N.width,K=N.height,O=E(a[a.length-1].symbol),L=O.width,M=O.height,m=Math.max(J,K),n=Math.max(L,M);b=C.createSurface(e,c,m);b.createRect({x:0,
y:m/2-n/2,height:n,width:n}).setStroke({color:"#ddd",width:1});b.createRect({x:c-m,y:0,height:m,width:m}).setStroke({color:"#ddd",width:1});b.createImage({src:a[a.length-1].symbol.url,height:n,width:n,y:m/2-n/2});b.createImage({src:a[0].symbol.url,height:m,width:m,x:c-m});b.createLine({x1:n,y1:m/2-n/2,x2:c-m,y2:0}).setStroke({color:"#ddd",width:1});b.createLine({x1:n,y1:m/2+n/2,x2:c-m,y2:m}).setStroke({color:"#ddd",width:1})}h=u;u=p;p=h}}catch(X){b.clear(),b.destroy()}return b?d.tsx("div",{class:this.classes("esri-legend--card__layer-row",
(f={},f["esri-legend--card__size-ramp-row"]=this._hasIndicators,f))},d.tsx("div",{class:"esri-legend--card__ramp-label"},u),d.tsx("div",{class:"esri-legend--card__size-ramp-container"},d.tsx("div",{bind:e,afterCreate:z.attachToNode})),d.tsx("div",{class:"esri-legend--card__ramp-label"},p)):null};k.prototype._renderLegendForRamp=function(a){var f=a.infos,e="heatmap-ramp"===a.type,b=f.length-1,h=2<b&&!e?25*b:100,c=h+20;a=document.createElement("div");a.style.width=c+"px";var l=C.createSurface(a,c,25),
k=f.slice(0).reverse();try{k.forEach(function(a,c){a.offset=e?a.ratio:c/b}),e||l.createPath("M0 12.5 L10 0 L10 25 Z").setFill(k[0].color).setStroke(null),l.createRect({x:10,y:0,width:h,height:25}).setFill({type:"linear",x1:10,y1:0,x2:h+10,y2:0,colors:k}).setStroke(null),e||l.createPath("M"+(h+10)+" 0 L"+c+" 12.5 L"+(h+10)+" 25 Z").setFill(k[k.length-1].color).setStroke(null)}catch(p){l.clear(),l.destroy()}if(!l)return null;h=k.filter(function(a,b){return!!a.label&&0!==b&&b!==k.length-1}).map(function(a){return d.tsx("div",
{class:"esri-legend--card__interval-separators-container"},d.tsx("div",{class:"esri-legend--card__interval-separator"},"|"),d.tsx("div",{class:"esri-legend--card__ramp-label"},a.label))});c=f[f.length-1].label;f=f[0].label;return d.tsx("div",{class:"esri-legend--card__layer-row"},d.tsx("div",{class:"esri-legend--card__ramp-label"},e?A[c]:c),d.tsx("div",{class:"esri-legend--card__symbol-container"},d.tsx("div",{bind:a,afterCreate:z.attachToNode}),h),d.tsx("div",{class:"esri-legend--card__ramp-label"},
e?A[f]:f))};t([d.renderable(),w.property()],k.prototype,"activeLayerInfos",void 0);t([w.property()],k.prototype,"layout",void 0);t([w.property({readOnly:!0})],k.prototype,"type",void 0);t([w.property()],k.prototype,"view",void 0);t([d.accessibleHandler()],k.prototype,"_selectSection",null);return k=t([w.subclass("esri.widgets.Legend.styles.Card")],k)}(w.declared(S))});