// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper dojo/i18n!../../Legend/nls/Legend dojox/gfx ../../../core/accessorSupport/decorators ../../Widget ./common ../support/styleUtils ../../support/widget".split(" "),function(z,A,v,r,t,w,q,x,y,n,g){return function(u){function e(a){a=u.call(this)||this;a.activeLayerInfos=null;a.type="classic";return a}v(e,u);e.prototype.render=function(){var a=this,d=this.activeLayerInfos,b=this.classes("esri-legend esri-widget--panel",
"esri-widget"),d=d&&d.toArray().map(function(c){return a._renderLegendForLayer(c)}).filter(function(a){return!!a});return g.tsx("div",{class:b},d&&d.length?d:g.tsx("div",{class:"esri-legend__message"},t.noLegend))};e.prototype._renderLegendForLayer=function(a){var d=this,b;if(!a.ready)return null;var c=!!a.children.length,k="esri-legend__"+a.layer.uid+"-version-"+a.version,f=a.title?g.tsx("h3",{class:this.classes("esri-widget__heading","esri-legend__service-label")},a.title):null;if(c)return b=a.children.map(function(a){return d._renderLegendForLayer(a)}).toArray(),
g.tsx("div",{key:k,class:this.classes("esri-legend__service","esri-legend__group-layer")},f,b);if((c=a.legendElements)&&!c.length)return null;c=c.map(function(b){return d._renderLegendForElement(b,a.layer)}).filter(function(a){return!!a});if(!c.length)return null;var h=(b={},b["esri-legend__group-layer-child"]=!!a.parent,b);return g.tsx("div",{key:k,class:this.classes("esri-legend__service",h)},f,g.tsx("div",{class:"esri-legend__layer"},c))};e.prototype._renderLegendForElement=function(a,d,b){var c=
this,k,f="color-ramp"===a.type,h="opacity-ramp"===a.type,e="size-ramp"===a.type,p=null;if("symbol-table"===a.type||e){var l=a.infos.map(function(b){return c._renderLegendForElementInfo(b,d,e,a.legendType)}).filter(function(a){return!!a});l.length&&(p=g.tsx("div",{class:"esri-legend__layer-body"},l))}else"color-ramp"===a.type||"opacity-ramp"===a.type||"heatmap-ramp"===a.type?p=this._renderLegendForRamp(a):"relationship-ramp"===a.type&&(p=y.renderRelationshipRamp(a,this.id));if(!p)return null;var l=
a.title,m=null;"string"===typeof l?m=l:l&&(m=n.getTitle(l,f||h),m=n.isRendererTitle(l,f||h)&&l.title?l.title+" ("+m+")":m);f=b?"esri-legend__layer-child-table":"esri-legend__layer-table";h=m?g.tsx("div",{class:"esri-legend__layer-caption"},m):null;b=(k={},k["esri-legend__layer-table--size-ramp"]=e||!b,k);return g.tsx("div",{class:this.classes(f,b)},h,p)};e.prototype._renderLegendForRamp=function(a){var d=a.infos,b="opacity-ramp"===a.type,c="heatmap-ramp"===a.type,k=d.length-1,f=null;2<k&&!c?f=25*
k:f=c?75:50;var h=document.createElement("div");h.className="esri-legend__color-ramp "+(b?"esri-legend__opacity-ramp":"");h.style.height=f+"px";b=w.createSurface(h,"100%",f);try{if(c||d.forEach(function(a,b){a.offset=b/k}),b.createRect({x:0,y:0,width:"100%",height:f}).setFill({type:"linear",x1:0,y1:0,x2:0,y2:f,colors:d}).setStroke(null),"color-ramp"===a.type||"opacity-ramp"===a.type){var e=a.overlayColor;e&&0<e.a&&b.createRect({x:0,y:0,width:"100%",height:f}).setFill(e).setStroke(null)}}catch(p){b.clear(),
b.destroy()}if(!b)return null;a=d.filter(function(a){return!!a.label}).map(function(a){return g.tsx("div",{class:"esri-legend__ramp-label"},c?t[a.label]:a.label)});f={height:f+"px"};return g.tsx("div",{class:"esri-legend__layer-row"},g.tsx("div",{class:"esri-legend__layer-cell esri-legend__layer-cell--symbols",styles:{width:"24px"}},g.tsx("div",{class:"esri-legend__ramps",bind:h,afterCreate:n.attachToNode})),g.tsx("div",{class:"esri-legend__layer-cell esri-legend__layer-cell--info"},g.tsx("div",{class:"esri-legend__ramp-labels",
styles:f},a)))};e.prototype._renderLegendForElementInfo=function(a,d,b,c){var e,f;if(a.type)return this._renderLegendForElement(a,d,!0);var h=null;c=n.isImageryStretchedLegend(d,c);a.symbol&&a.preview?h=g.tsx("div",{class:"esri-legend__symbol",bind:a.preview,afterCreate:n.attachToNode}):a.src&&(h=this._renderImage(a,d,c));if(!h)return null;d=(e={},e["esri-legend__imagery-layer-info--stretched"]=c,e);b=(f={},f["esri-legend__imagery-layer-info--stretched"]=c,f["esri-legend__size-ramp"]=!c&&b,f);return g.tsx("div",
{class:"esri-legend__layer-row"},g.tsx("div",{class:this.classes("esri-legend__layer-cell esri-legend__layer-cell--symbols",b)},h),g.tsx("div",{class:this.classes("esri-legend__layer-cell esri-legend__layer-cell--info",d)},n.getTitle(a.label,!1)||""))};e.prototype._renderImage=function(a,d,b){var c,e=a.label,f=a.src,h=a.opacity;b=(c={},c["esri-legend__imagery-layer-image--stretched"]=b,c["esri-legend__symbol"]=!b,c);d={opacity:""+(null!=h?h:d.opacity)};return g.tsx("img",{alt:e,src:f,border:0,width:a.width,
height:a.height,class:this.classes(b),styles:d})};r([g.renderable(),q.property()],e.prototype,"activeLayerInfos",void 0);r([q.property({readOnly:!0})],e.prototype,"type",void 0);return e=r([q.subclass("esri.widgets.Legend.styles.Classic")],e)}(q.declared(x))});