// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","../../core/tsSupport/assignHelper"],function(L,q,M){function x(a,b){var e=a||{},g=e.format,d=e.quality,e=e.rotation,f=b.padding||E,c;c=b.width-f.left-f.right;b=b.height-f.top-f.bottom;var n=0,f=0,h=c,l=b;if(a&&a.area){var n=Math.floor(a.area.x)||0,f=Math.floor(a.area.y)||0,k=null!=a.area.width?Math.floor(a.area.width):null,p=null!=a.area.height?Math.floor(a.area.height):null,h=h-n,l=l-f;null!=k&&null!=p?(h=Math.min(h,k),l=Math.min(l,p)):null==k&&null!=p?(k=Math.min(h,
k),l*=k/h,h=k):null!=k&&null==p&&(k=Math.min(l,p),h*=k/l,l=k)}a&&null!=a.width&&null!=a.height&&(k=a.width/a.height,p=h/l,p!==k&&(p<k?h=Math.floor(l*k):l=Math.floor(h/k)));n=Math.floor(Math.max(n,0));f=Math.floor(Math.max(f,0));c={x:n,y:f,width:Math.floor(Math.min(h,c-n)),height:Math.floor(Math.min(l,b-f))};b=c.width/c.height;f=h/l;f!==b&&(f>b?(b=Math.floor(c.width/f),c={x:c.x,y:Math.floor(c.y+(c.height-b)/2),width:c.width,height:b}):(b=Math.floor(c.height*f),c={x:Math.floor(c.x+(c.width-b)/2),y:c.y,
width:b,height:c.height}));b=F(a,c);a=b.width;b=b.height;a:switch(g){case "png":case "jpg":case "jpeg":break a;default:g=I}f=J[g];d=null!=d?d:f;return{format:g,quality:0>d?0:100<d?100:d,area:c,width:a,height:b,rotation:e}}function y(a,b){return a.toDataURL(K[b.format],b.quality/100)}function z(a,b,e){e||(t||(t=document.createElement("canvas"),t.width=1,t.height=1),e=t);return e.getContext("2d").createImageData(a,b)}function F(a,b){if(!a)return b;var e=a.width;a=a.height;if(null!=e&&null!=a)return{width:Math.floor(e),
height:Math.floor(a)};if(null==e&&null==a)return b;b=b.width/b.height;return null==a?{width:Math.floor(e),height:Math.floor(e/b)}:{width:Math.floor(a*b),height:Math.floor(a)}}Object.defineProperty(q,"__esModule",{value:!0});q.completeUserSettings=x;q.toRenderSettings=function(a,b){a=x(a,b);var e=a.area,g=a.width/e.width,d=b.padding,f=d.left+d.right,c=d.top+d.bottom;return{framebufferWidth:Math.floor((b.width-f)*g+f),framebufferHeight:Math.floor((b.height-c)*g+c),region:{x:Math.floor(e.x*g)+d.left,
y:Math.floor(e.y*g)+d.top,width:a.width,height:a.height},format:a.format,quality:a.quality,rotation:a.rotation,pixelRatio:g}};q.encodeResult=function(a,b,e,g){if(g.premultipliedAlpha)for(var d=a.data,f=d.length,c=0;c<f;c+=4){var n=d[c+3];0<n&&(n/=255,d[c+0]/=n,d[c+1]/=n,d[c+2]/=n)}e.width=a.width;e.height=a.height;d=e.getContext("2d");d.putImageData(a,0,0);g.flipY&&(d.save(),d.globalCompositeOperation="copy",d.scale(1,-1),d.translate(0,-d.canvas.height),d.drawImage(d.canvas,0,0),d.restore());a=d.getImageData(0,
0,a.width,a.height);b=y(e,b);e.width=0;e.height=0;return{dataUrl:b,data:a}};q.toDataUrl=y;q.createEmptyImageData=function(a,b,e){if(!a||!b)throw Error("Cannot construct image data without dimensions");if(r)try{return new ImageData(a,b)}catch(g){r=!1}return z(a,b,e)};q.wrapImageData=function(a,b,e,g){if(!b||!e)throw Error("Cannot construct image data without dimensions");if(r)try{return new ImageData(a,b,e)}catch(d){r=!1}b=z(b,e,g);b.data.set(a,0);return b};q.resampleHermite=function(a,b,e,g,d,f,c,
n){void 0===g&&(g=0);void 0===d&&(d=0);void 0===f&&(f=a.width-g);void 0===c&&(c=a.height-d);void 0===n&&(n=!1);var h=a.data,l=b.width,k=b.height,p=b.data;f/=l;c/=k;var q=Math.ceil(f/2),t=Math.ceil(c/2);a=a.width;for(var u=0;u<k;u++)for(var v=0;v<l;v++){for(var r=4*(v+(n?k-u-1:u)*l),A=0,G=0,x=0,y=0,z=0,H=0,E=(u+.5)*c,B=Math.floor(u*c);B<(u+1)*c;B++)for(var C=Math.abs(E-(B+.5))/t,F=(v+.5)*f,C=C*C,D=Math.floor(v*f);D<(v+1)*f;D++){var m=Math.abs(F-(D+.5))/q,m=Math.sqrt(C+m*m);if(!(1<=m)){var m=2*m*m*
m-3*m*m+1,w=4*(g+D+(d+B)*a),H=H+m*h[w+3],G=G+m;!e&&255>h[w+3]&&(m=m*h[w+3]/255);x+=m*h[w];y+=m*h[w+1];z+=m*h[w+2];A+=m}}p[r]=x/A;p[r+1]=y/A;p[r+2]=z/A;p[r+3]=H/G}return b};var t=null,r=!0,K={png:"image/png",jpg:"image/jpeg",jpeg:"image/jpeg"},I="jpg",J={png:100,jpg:98,jpeg:98},E={top:0,right:0,bottom:0,left:0}});