// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define(["require","exports","@dojo/framework/shim/Set","../../core/object","./domains"],function(F,b,z,q,h){function r(a,c,b){if(a)for(var e=0;e<a.length;e++){var f=a[e],g=q.getDeepValue(f,c);(g=g&&"function"!==typeof g&&t(g,b))&&q.setDeepValue(f,g.name,c)}}function t(a,c){if("string"!==typeof a)return null;if(null!=c){a=a.toLowerCase();for(var b=0;b<c.length;b++){var d=c[b];if(d&&d.name.toLowerCase()===a)return d}}return null}function u(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}function A(a){return null===
a||u(a)}function v(a){return"number"===typeof a&&isFinite(a)&&Math.floor(a)===a}function B(a){return null===a||v(a)}function w(a){return null!=a&&"string"===typeof a}function C(a){return null===a||w(a)}function D(a){return!0}function k(a,c){var b;switch(a.type){case "date":case "integer":case "long":case "small-integer":case "esriFieldTypeDate":case "esriFieldTypeInteger":case "esriFieldTypeLong":case "esriFieldTypeSmallInteger":b=a.nullable?B:v;break;case "double":case "single":case "esriFieldTypeSingle":case "esriFieldTypeDouble":b=
a.nullable?A:u;break;case "string":case "esriFieldTypeString":b=a.nullable?C:w;break;default:b=D}return 1===arguments.length?b:b(c)}function l(a){return null!=a&&E.has(a.type)}function x(a,c){return a.nullable&&null===c?null:l(a)&&!y(a.type,c)?m.OUT_OF_RANGE:k(a,c)?a.domain?h.validateDomainValue(a.domain,c):null:n.INVALID_TYPE}function y(a,c){return(a=p(a))?c>=a.min&&c<=a.max:!1}function p(a){switch(a){case "esriFieldTypeSmallInteger":case "small-integer":return{min:-32768,max:32767};case "esriFieldTypeInteger":case "integer":return{min:-2147483648,
max:2147483647};case "esriFieldTypeSingle":case "single":return{min:-3.4E38,max:1.2E38};case "esriFieldTypeDouble":case "double":return{min:-Number.MAX_VALUE,max:Number.MAX_VALUE}}}Object.defineProperty(b,"__esModule",{value:!0});b.fixRendererFields=function(a,c){if(null!=a&&null!=c){var e=0;for(a=Array.isArray(a)?a:[a];e<a.length;e++){var d=a[e];r(b.rendererFields,d,c);if(d.visualVariables)for(var f=0,d=d.visualVariables;f<d.length;f++)r(b.visualVariableFields,d[f],c)}}};b.getField=t;b.getFieldDefaultValue=
function(a){var c=a.defaultValue;if(void 0!==c&&k(a,c))return c;if(a.nullable)return null};b.isValueMatchingFieldType=k;b.rendererFields="field field2 field3 normalizationField rotationInfo.field proportionalSymbolInfo.field proportionalSymbolInfo.normalizationField colorInfo.field colorInfo.normalizationField".split(" ");b.visualVariableFields=["field","normalizationField"];b.numericTypes=["integer","small-integer","single","double"];var E=new z.default(b.numericTypes.concat(["esriFieldTypeInteger",
"esriFieldTypeSmallInteger","esriFieldTypeSingle","esriFieldTypeDouble"]));b.isNumericField=l;b.isStringField=function(a){return null!=a&&("string"===a.type||"esriFieldTypeString"===a.type)};b.isDateField=function(a){return null!=a&&("date"===a.type||"esriFieldTypeDate"===a.type)};b.isValidFieldValue=function(a,c){return null===x(a,c)};var m;(m=b.NumericRangeValidationError||(b.NumericRangeValidationError={})).OUT_OF_RANGE="numeric-range-validation-error::out-of-range";var n;(n=b.TypeValidationError||
(b.TypeValidationError={})).INVALID_TYPE="type-validation-error::invalid-type";b.validateFieldValue=x;b.isNumberInRange=y;b.getFieldRange=function(a){var c=h.getDomainRange(a.domain);if(c)return c;if(l(a))return p(a.type)};b.validationErrorToString=function(a,c,b){switch(a){case h.DomainValidationError.INVALID_CODED_VALUE:return"Value "+b+" is not in the coded domain - field: "+c.name+", domain: "+JSON.stringify(c.domain);case h.DomainValidationError.VALUE_OUT_OF_RANGE:return"Value "+b+" is out of the range of valid values - field: "+
c.name+", domain: "+JSON.stringify(c.domain);case n.INVALID_TYPE:return"Value "+b+" is not a valid value for the field type - field: "+c.name+", type: "+c.type+", nullable: "+c.nullable;case m.OUT_OF_RANGE:return a=p(c.type),"Value "+b+" is out of range for the number type - field: "+c.name+", type: "+c.type+", value range is "+a.min+" to "+a.max}}});