// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/assignHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper dojo/io-query ../../request ../../core/Accessor ../../core/Error ../../core/Handles ../../core/Logger ../../core/LRUMap ../../core/PooledArray ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators ./Tilemap".split(" "),function(D,E,r,t,e,u,v,w,m,x,y,z,A,g,B,f,h){var C=y.getLogger("esri.layers.support.TilemapCache");return function(q){function b(a){a=
q.call(this)||this;a._handles=new x;a._pendingTilemapRequests={};a._availableLevels={};a.levels=5;a.cacheByteSize=2097152;a.request=v;return a}t(b,q);k=b;b.prototype.initialize=function(){var a=this;this._tilemapCache=new z(this.cacheByteSize,{sizeOfFunction:function(a){return a.byteSize}});this._handles.add([this.watch(["layer.parsedUrl","layer.tileServers?"],function(){return a._initializeTilemapDefinition()}),B.init(this,"layer.tileInfo.lods",function(d){return a._initializeAvailableLevels(d)},
!0)]);this._initializeTilemapDefinition()};b.prototype.destroy=function(){this._handles&&(this._handles.destroy(),this._handles=null)};b.prototype.castLevels=function(a){return 2>=a?(C.error("Minimum levels for Tilemap is 3, but got ",a),3):a};Object.defineProperty(b.prototype,"size",{get:function(){return 1<<this.levels},enumerable:!0,configurable:!0});b.prototype.getTilemap=function(a,d,b){return this._tilemapFromCache(a,d,b,this._tmpTilemapDefinition)};b.prototype.fetchTilemap=function(a,d,b,c){var l=
this;if(!this._availableLevels[a])return g.reject(new m("tilemap-cache:level-unavailable","Level "+a+" is unavailable in the service"));var f=this._tmpTilemapDefinition;if(a=this._tilemapFromCache(a,d,b,f))return g.resolve(a);var n=h.tilemapDefinitionId(f),e=this._pendingTilemapRequests[n];e||(e=h.Tilemap.fromDefinition(f,c).then(function(a){l._tilemapCache.set(n,a);delete l._pendingTilemapRequests[n];return a}).catch(function(a){delete l._pendingTilemapRequests[n];return g.reject(a)}),this._pendingTilemapRequests[n]=
e);return g.create(function(a,d){e.then(a,d)})};b.prototype.getAvailability=function(a,d,b){return this._availableLevels[a]?(a=this.getTilemap(a,d,b))?a.getAvailability(d,b):"unknown":"unavailable"};b.prototype.getAvailabilityUpsample=function(a,d,b,c){c.level=a;c.row=d;c.col=b;a=this.layer.tileInfo;for(a.updateTileInfo(c);;)if(d=this.getAvailability(c.level,c.row,c.col),"unavailable"===d){if(!a.upsampleTile(c))return"unavailable"}else return d};b.prototype.fetchAvailability=function(a,d,b,c){return this._availableLevels[a]?
this.fetchTilemap(a,d,b,c).always(function(c){return c instanceof h.Tilemap?(c=c.getAvailability(d,b),"unavailable"===c?g.reject(new m("tile-map:tile-unavailable","Tile is not available",{level:a,row:d,col:b})):c):c&&"cancel"===c.dojoType?g.reject(c):"unknown"}):g.reject(new m("tilemap-cache:level-unavailable","Level "+a+" is unavailable in the service"))};b.prototype.fetchAvailabilityUpsample=function(a,d,b,c,e){var f=this;c.level=a;c.row=d;c.col=b;var l=this.layer.tileInfo;l.updateTileInfo(c);var h=
this.fetchAvailability(a,d,b,e).catch(function(a){return a&&"cancel"===a.dojoType?g.reject(a):l.upsampleTile(c)?f.fetchAvailabilityUpsample(c.level,c.row,c.col,c):g.reject(a)}),p={id:c.id,level:a,row:d,col:b};a=function(a){var b=m.fetchAvailability(p.level,p.row,p.col,e);k._prefetches.push(b);h.always(function(){return b.cancel()});b.always(function(){return k._prefetches.removeUnordered(b)})};var m=this;for(d=0;k._prefetches.length<k._maxPrefetch&&l.upsampleTile(p);++d)a(d);return h};b.prototype._initializeTilemapDefinition=
function(){if(this.layer.parsedUrl){var a=this.layer.parsedUrl,b=a.query;b&&b.token||!this.layer.token||(b=r({},b,{token:this.layer.token}));this._tilemapCache.clear();this._tmpTilemapDefinition={service:{url:a.path,query:b?u.objectToQuery(b):null,tileServers:this.layer.tileServers,request:this.request,type:this.layer.type},width:this.size,height:this.size,level:0,row:0,col:0}}};b.prototype._tilemapFromCache=function(a,b,e,c){a=this._getTilemapDefinition(a,b,e,c);a=h.tilemapDefinitionId(a);return this._tilemapCache.get(a)};
b.prototype._getTilemapDefinition=function(a,b,e,c){c.level=a;c.row=b-b%this.size;c.col=e-e%this.size;return c};b.prototype._initializeAvailableLevels=function(a){var b=this;this._availableLevels={};a&&a.forEach(function(a){return b._availableLevels[a.level]=!0})};var k;b._maxPrefetch=4;b._prefetches=new A({initialSize:k._maxPrefetch});e([f.property({constructOnly:!0,type:Number})],b.prototype,"levels",void 0);e([f.cast("levels")],b.prototype,"castLevels",null);e([f.property({readOnly:!0,dependsOn:["levels"],
type:Number})],b.prototype,"size",null);e([f.property({constructOnly:!0,type:Number})],b.prototype,"cacheByteSize",void 0);e([f.property({constructOnly:!0})],b.prototype,"layer",void 0);e([f.property({constructOnly:!0})],b.prototype,"request",void 0);return b=k=e([f.subclass("esri.layers.support.TilemapCache")],b)}(f.declared(w))});