//>>built
(function(d){"object"===typeof module&&"object"===typeof module.exports?(d=d(require,exports),void 0!==d&&(module.exports=d)):"function"===typeof define&&define.amd&&define("require exports tslib ../../../shim/global ../../../shim/WeakMap ../../async/Task ../../has ../../Observable ../../util ../Headers ../Response ../SubscriptionPool ../TimeoutError ../util".split(" "),d)})(function(d,l){function k(c){c=f.get(c);if(c.used)return m.default.reject(new TypeError("Body already read"));c.used=!0;return c.task}
function x(){}function F(c,a){c.addEventListener("error",function(c){a(new TypeError(c.error||"Network request failed"))})}Object.defineProperty(l,"__esModule",{value:!0});var z=d("tslib"),K=d("../../../shim/global"),L=d("../../../shim/WeakMap"),m=d("../../async/Task"),e=d("../../has"),A=d("../../Observable"),M=d("../../util"),G=d("../Headers"),g=d("../Response"),B=d("../SubscriptionPool"),N=d("../TimeoutError"),O=d("../util"),f=new L.default,n=function(c){function a(a){var b=c.call(this)||this,d=
b.headers=new G.default,h=a.getAllResponseHeaders();if(h)for(var h=h.split(/\r\n/g),y=0;y<h.length;y++){var f=h[y].match(/^(.*?): (.*)$/);f&&d.append(f[1],f[2])}b.status=a.status;b.ok=200<=b.status&&300>b.status;b.statusText=a.statusText||"OK";return b}z.__extends(a,c);Object.defineProperty(a.prototype,"bodyUsed",{get:function(){return f.get(this).used},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"nativeResponse",{get:function(){return f.get(this).nativeResponse},enumerable:!0,
configurable:!0});Object.defineProperty(a.prototype,"requestOptions",{get:function(){return f.get(this).requestOptions},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"url",{get:function(){return f.get(this).url},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"download",{get:function(){return f.get(this).downloadObservable},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"data",{get:function(){return f.get(this).dataObservable},enumerable:!0,
configurable:!0});a.prototype.arrayBuffer=function(){return m.default.reject(Error("ArrayBuffer not supported"))};a.prototype.blob=function(){return m.default.reject(Error("Blob not supported"))};a.prototype.formData=function(){return m.default.reject(Error("FormData not supported"))};a.prototype.text=function(){return k(this).then(function(a){return String(a.responseText)})};a.prototype.xml=function(){var a=this;return this.text().then(function(b){var c=new DOMParser,d=a.headers.get("content-type");
return c.parseFromString(b,d?d.split(";")[0]:"text/html")})};return a}(g.default);l.XhrResponse=n;e.default("blob")&&(n.prototype.blob=function(){return k(this).then(function(c){return c.response})},n.prototype.text=function(){return this.blob().then(g.getTextFromBlob)},e.default("arraybuffer")&&(n.prototype.arrayBuffer=function(){return this.blob().then(g.getArrayBufferFromBlob)}));e.default("formdata")&&(n.prototype.formData=function(){return this.text().then(function(c){var a=new FormData;c.trim().split("\x26").forEach(function(c){if(c){var b=
c.split("\x3d");c=(b.shift()||"").replace(/\+/," ");b=b.join("\x3d").replace(/\+/," ");a.append(decodeURIComponent(c),decodeURIComponent(b))}});return a})});l.default=function(c,a){function d(){h=!0;b&&(b.abort(),b.onreadystatechange=x)}void 0===a&&(a={});var b=new XMLHttpRequest,l=O.generateRequestUrl(c,a);a=Object.create(a);a.method||(a.method="GET");c=a.credentials;c=void 0===c?"same-origin":c;"include"===c?b.withCredentials=!0:"omit"===c&&(b.withCredentials=!1);var h=!1,p,r,g,t=new m.default(function(c,
e){r=e;a.signal&&(g=function(){var a;try{a=new DOMException("Aborted","AbortError")}catch(P){a=Error("Aborted"),a.name="AbortError"}e(a)},a.signal.addEventListener("abort",g));b.onreadystatechange=function(){if(!h&&2===b.readyState){var e=new n(b),g=new B.default,k=new B.default,C=new m.default(function(a,c){r=c;b.onprogress=function(a){h||g.next(a.loaded)};b.onreadystatechange=function(){h||4!==b.readyState||(b.onreadystatechange=x,p&&p.destroy(),k.next(b.response),k.complete(),a(b))};F(b,c)},d);
f.set(e,{task:C,used:!1,nativeResponse:b,requestOptions:a,url:l,downloadObservable:new A.default(function(a){return g.add(a)}),dataObservable:new A.default(function(a){return k.add(a)})});c(e)}};F(b,e)},d);b.open(a.method,l,!a.blockMainThread,a.user,a.password);e.default("filereader")&&e.default("blob")&&(b.responseType="blob");a.timeout&&0<a.timeout&&Infinity!==a.timeout&&(p=M.createTimer(function(){r&&r(new N.default("The XMLHttpRequest request timed out"));d()},a.timeout));var k=c=!1,u=a.includeRequestedWithHeader,
u=void 0===u?!0:u,v=a.includeUploadProgress,v=void 0===v?!0:v;if(a.headers){var D=new G.default(a.headers),k=D.has("x-requested-with");c=D.has("content-type");try{for(var w=z.__values(D),q=w.next();!q.done;q=w.next()){var H=z.__read(q.value,2);b.setRequestHeader(H[0],H[1])}}catch(C){E={error:C}}finally{try{q&&!q.done&&(I=w.return)&&I.call(w)}finally{if(E)throw E.error;}}}!k&&u&&b.setRequestHeader("X-Requested-With","XMLHttpRequest");!c&&e.default("formdata")&&a.body instanceof K.default.FormData&&
b.setRequestHeader("Content-Type","application/x-www-form-urlencoded");t.finally(function(){0!==t.state&&(b.onreadystatechange=x,p&&p.destroy());a.signal&&a.signal.removeEventListener("abort",g)});if(v){var J=new B.default;t.upload=new A.default(function(a){return J.add(a)});(e.default("host-browser")||e.default("web-worker-xhr-upload"))&&b.upload.addEventListener("progress",function(a){J.next(a.loaded)})}b.send(a.body||null);return t;var E,I}});