// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/array dojo/Deferred dojo/_base/url dojo/cookie dojo/io-query dojo/regexp ../kernel ../config ../core/global ../core/has ../core/lang ../core/object ./ServerInfo ../core/urlUtils ../core/deferredUtils ../core/Accessor ../request ../core/Error ../core/Evented ./OAuthCredential ./OAuthInfo".split(" "),function(A,l,O,r,D,P,Q,m,R,G,H,w,y,E,v,I,S,x,q,J,K,L){var B={},M=function(a){var b=(new r(a.owningSystemUrl)).host;a=(new r(a.server)).host;var c=/.+\.arcgis\.com$/i;
return c.test(b)&&c.test(a)},F=function(a,b){return!!(M(a)&&b&&l.some(b,function(b){return b.test(a.server)}))},p;A=A(J,{declaredClass:"esri.identity.IdentityManagerBase",constructor:function(){this._portalConfig=G.esriGeowConfig;this.serverInfos=[];this.oAuthInfos=[];this.credentials=[];this._soReqs=[];this._xoReqs=[];this._portals=[];this._getOAuthHash();window.addEventListener("pageshow",function(a){this._pageShowHandler(a)}.bind(this))},defaultOAuthInfo:null,defaultTokenValidity:60,tokenValidity:null,
signInPage:null,useSignInPage:!0,normalizeWebTierAuth:!1,_busy:null,_rejectOnPersistedPageShow:!1,_oAuthHash:null,_gwTokenUrl:"/sharing/generateToken",_agsRest:"/rest/services",_agsPortal:/\/sharing(\/|$)/i,_agsAdmin:/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i,_adminSvcs:/\/admin\/services(\/|$)/i,_agolSuffix:".arcgis.com",_gwDomains:[{regex:/https?:\/\/www\.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/dev\.arcgis\.com/i,tokenServiceUrl:"https://dev.arcgis.com/sharing/generateToken"},
{regex:/https?:\/\/.*dev[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://devext.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*qa[^.]*\.arcgis\.com/i,tokenServiceUrl:"https://qaext.arcgis.com/sharing/generateToken"},{regex:/https?:\/\/.*.arcgis\.com/i,tokenServiceUrl:"https://www.arcgis.com/sharing/generateToken"}],_legacyFed:[],_regexSDirUrl:/http.+\/rest\/services\/?/ig,_regexServerType:/(\/(MapServer|GeocodeServer|GPServer|GeometryServer|ImageServer|NAServer|FeatureServer|GeoDataServer|GlobeServer|MobileServer|GeoenrichmentServer|VectorTileServer|SceneServer)).*/ig,
_gwUser:/http.+\/users\/([^\/]+)\/?.*/i,_gwItem:/http.+\/items\/([^\/]+)\/?.*/i,_gwGroup:/http.+\/groups\/([^\/]+)\/?.*/i,_errorCodes:[499,498,403,401],_rePortalTokenSvc:/\/sharing(\/rest)?\/generatetoken/i,_publicUrls:[/\/arcgis\/tokens/i,/\/sharing(\/rest)?\/generatetoken/i,/\/rest\/info/i],_createDefaultOAuthInfo:!0,_hasTestedIfAppIsOnPortal:!1,registerServers:function(a){var b=this.serverInfos;b?(a=l.filter(a,function(a){return!this.findServerInfo(a.server)},this),this.serverInfos=b.concat(a)):
this.serverInfos=a;l.forEach(a,function(a){a.owningSystemUrl&&this._portals.push(a.owningSystemUrl);a.hasPortal&&this._portals.push(a.server)},this)},registerOAuthInfos:function(a){var b=this.oAuthInfos;b?(a=l.filter(a,function(a){return!this.findOAuthInfo(a.portalUrl)},this),this.oAuthInfos=b.concat(a)):this.oAuthInfos=a},registerToken:function(a){a=w.mixin({},a);var b=this._sanitizeUrl(a.server),c=this.findServerInfo(b),d=this._isServerRsrc(b),e=!0,f;c||(c=new E,c.server=this._getServerInstanceRoot(b),
d?c.hasServer=!0:(c.tokenServiceUrl=this._getTokenSvcUrl(b),c.hasPortal=!0),this.registerServers([c]));(f=this._findCredential(b))?(delete a.server,w.mixin(f,a),e=!1):(f=new p({userId:a.userId,server:c.server,token:a.token,expires:a.expires,ssl:a.ssl,scope:d?"server":"portal"}),f.resources=[b],this.credentials.push(f));f.emitTokenChange(!1);e||f.refreshServerTokens()},toJSON:function(){return w.fixJson({serverInfos:l.map(this.serverInfos,function(a){return a.toJSON()}),oAuthInfos:l.map(this.oAuthInfos,
function(a){return a.toJSON()}),credentials:l.map(this.credentials,function(a){return a.toJSON()})})},initialize:function(a){if(a){"string"===typeof a&&(a=JSON.parse(a));var b=a.serverInfos,c=a.oAuthInfos;a=a.credentials;if(b){var d=[];l.forEach(b,function(a){a.server&&a.tokenServiceUrl&&d.push(a.declaredClass?a:new E(a))});d.length&&this.registerServers(d)}if(c){var e=[];l.forEach(c,function(a){a.appId&&e.push(a.declaredClass?a:new L(a))});e.length&&this.registerOAuthInfos(e)}a&&l.forEach(a,function(a){a.server&&
a.token&&a.expires&&a.expires>(new Date).getTime()&&(a=a.declaredClass?a:new p(a),a.emitTokenChange(),this.credentials.push(a))},this)}},findServerInfo:function(a){var b;a=this._sanitizeUrl(a);l.some(this.serverInfos,function(c){this._hasSameServerInstance(c.server,a)&&(b=c);return!!b},this);return b},findOAuthInfo:function(a){var b;a=this._sanitizeUrl(a);l.some(this.oAuthInfos,function(c){this._hasSameServerInstance(c.portalUrl,a)&&(b=c);return!!b},this);return b},findCredential:function(a,b){var c,
d;a=this._sanitizeUrl(a);d=this._isServerRsrc(a)?"server":"portal";b?l.some(this.credentials,function(e){this._hasSameServerInstance(e.server,a)&&b===e.userId&&e.scope===d&&(c=e);return!!c},this):l.some(this.credentials,function(b){this._hasSameServerInstance(b.server,a)&&-1!==this._getIdenticalSvcIdx(a,b)&&b.scope===d&&(c=b);return!!c},this);return c},getCredential:function(a,b){var c,d,e=!0;null!=b&&("object"===typeof b?(c=!!b.token,d=b.error,e=!1!==b.prompt):c=b);a=this._sanitizeUrl(a);var f=I.makeDeferredCancellingPending(),
k=this._isAdminResource(a),g=c&&this._doPortalSignIn(a)?this._getEsriAuthCookie():null;if((c=c?this.findCredential(a):null)&&d&&498===d.code)c.destroy(),g&&g.token===b.token&&D("esri_auth",null,{expires:-1,path:"/",domain:document.domain});else if(g||c)return a=new q("identity-manager:not-authorized","You are currently signed in as: '"+(g&&g.email||c&&c.userId)+"'. You do not have access to this resource: "+a,{error:d}),f.reject(a),f.promise;if(d=this._findCredential(a,b))return f.resolve(d),f.promise;
d=this.findServerInfo(a);if(d)!d.hasServer&&this._isServerRsrc(a)&&(d._restInfoPms=this._getTokenSvcUrl(a),d.hasServer=!0);else{g=this._getTokenSvcUrl(a);if(!g)return a=new q("identity-manager:unknown-resource","Unknown resource - could not find token service endpoint."),f.reject(a),f.promise;d=new E;d.server=this._getServerInstanceRoot(a);"string"===typeof g?(d.tokenServiceUrl=g,d.hasPortal=!0):(d._restInfoPms=g,d.hasServer=!0);this.registerServers([d])}e&&d.hasPortal&&void 0===d._selfReq&&!this._findOAuthInfo(a)&&
(d._selfReq={owningTenant:b&&b.owningTenant,selfDfd:this._getPortalSelf(d.tokenServiceUrl.replace(this._rePortalTokenSvc,"/sharing/rest/portals/self"),a)});return this._enqueue(a,d,b,f,k)},getResourceName:function(a){return this._isRESTService(a)?a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"")||"":this._gwUser.test(a)&&a.replace(this._gwUser,"$1")||this._gwItem.test(a)&&a.replace(this._gwItem,"$1")||this._gwGroup.test(a)&&a.replace(this._gwGroup,"$1")||""},generateToken:function(a,
b,c){var d,e,f,k,g,l,h=this._rePortalTokenSvc.test(a.tokenServiceUrl),t=new r(window.location.href.toLowerCase()),N=this._getEsriAuthCookie(),C,z=!b;k=a.shortLivedTokenValidity;var n;b&&(n=m.id.tokenValidity||k||m.id.defaultTokenValidity,n>k&&0<k&&(n=k));c&&(d=c.isAdmin,e=c.serverUrl,f=c.token,l=c.ssl,a.customParameters=c.customParameters);d?k=a.adminTokenServiceUrl:(k=a.tokenServiceUrl,g=new r(k.toLowerCase()),N&&(C=(C=N.auth_tier)&&C.toLowerCase()),("web"===C||a.webTierAuth)&&c&&c.serverUrl&&!l&&
"http"===t.scheme&&(v.hasSameOrigin(t.uri,k,!0)||"https"===g.scheme&&t.host===g.host&&"7080"===t.port&&"7443"===g.port)&&(k=k.replace(/^https:/i,"http:").replace(/:7443/i,":7080")),z&&h&&(k=k.replace(/\/rest/i,"")));c=w.mixin({query:w.mixin({request:"getToken",username:b&&b.username,password:b&&b.password,serverUrl:e,token:f,expiration:n,referer:d||h?window.location.host:null,client:d?"referer":null,f:"json"},a.customParameters),method:z?"auto":"post",authMode:"anonymous",useProxy:this._useProxy(a,
c),responseType:"json"},c&&c.ioArgs);h||(c.withCredentials=!1);return x(k,c).then(function(c){c=c.data;if(!c||!c.token)return new q("identity-manager:authentication-failed","Unable to generate token");var d=a.server;B[d]||(B[d]={});b&&(B[d][b.username]=b.password);c.validity=n;return c})},isBusy:function(){return!!this._busy},checkSignInStatus:function(a){return this.getCredential(a,{prompt:!1}).then(function(a){return a.token?x(a.server+("portal"===a.scope?"/sharing/rest":"/rest/services"),{query:{f:"json",
token:a.token},authMode:"anonymous"}).then(function(){return a}).catch(function(b){if(498===b.code)throw a.destroy(),new q("identity-manager:not-authenticated","User is not signed in.");return a}):a})},setRedirectionHandler:function(a){this._redirectFunc=a},setProtocolErrorHandler:function(a){this._protocolFunc=a},signIn:function(){},oAuthSignIn:function(){},destroyCredentials:function(){if(this.credentials){var a=this.credentials.slice();l.forEach(a,function(a){a.destroy()})}this.emit("credentials-destroy")},
_getOAuthHash:function(){var a=window.location.hash;if(a){"#"===a.charAt(0)&&(a=a.substring(1));var a=P.queryToObject(a),b=!1;a.access_token&&a.expires_in&&a.state&&a.hasOwnProperty("username")?(a.state=JSON.parse(a.state),this._oAuthHash=a,b=!0):a.error&&a.error_description&&(console.log("IdentityManager OAuth Error: ",a.error," - ",a.error_description),"access_denied"===a.error&&(b=!0));b&&(!H("ie")||8<H("ie"))&&(window.location.hash="")}},_pageShowHandler:function(a){a.persisted&&this.isBusy()&&
this._rejectOnPersistedPageShow&&(a=new q("identity-manager:user-aborted","ABORTED"),this._errbackFunc(a))},_findCredential:function(a,b){var c=-1,d,e,f,k=b&&b.token;b=b&&b.resource;var g=this._isServerRsrc(a)?"server":"portal",m=l.filter(this.credentials,function(b){return this._hasSameServerInstance(b.server,a)&&b.scope===g},this);a=b||a;if(m.length)if(1===m.length)if(b=m[0],e=(d=(f=this.findServerInfo(b.server))&&f.owningSystemUrl)&&this.findCredential(d,b.userId),c=this._getIdenticalSvcIdx(a,
b),k)-1!==c&&(b.resources.splice(c,1),this._removeResource(a,e));else return-1===c&&b.resources.push(a),this._addResource(a,e),b;else{var h,t;l.some(m,function(b){t=this._getIdenticalSvcIdx(a,b);return-1!==t?(h=b,e=(d=(f=this.findServerInfo(h.server))&&f.owningSystemUrl)&&this.findCredential(d,h.userId),c=t,!0):!1},this);if(k)h&&(h.resources.splice(c,1),this._removeResource(a,e));else if(h)return this._addResource(a,e),h}},_findOAuthInfo:function(a){var b=this.findOAuthInfo(a);b||l.some(this.oAuthInfos,
function(c){this._isIdProvider(c.portalUrl,a)&&(b=c);return!!b},this);return b},_addResource:function(a,b){b&&-1===this._getIdenticalSvcIdx(a,b)&&b.resources.push(a)},_removeResource:function(a,b){var c=-1;b&&(c=this._getIdenticalSvcIdx(a,b),-1<c&&b.resources.splice(c,1))},_useProxy:function(a,b){return b&&b.isAdmin&&!v.hasSameOrigin(a.adminTokenServiceUrl,window.location.href)||!this._isPortalDomain(a.tokenServiceUrl)&&10.1==a.currentVersion&&!v.hasSameOrigin(a.tokenServiceUrl,window.location.href)},
_getOrigin:function(a){a=new r(a);return a.scheme+"://"+a.host+(null!=a.port?":"+a.port:"")},_getServerInstanceRoot:function(a){var b=a.toLowerCase(),c=b.indexOf(this._agsRest);-1===c&&this._isAdminResource(a)&&(c=b.indexOf("/admin"));-1===c&&(c=b.indexOf("/sharing"));-1===c&&"/"===b.substr(-1)&&(c=b.length-1);return-1<c?a.substring(0,c):a},_hasSameServerInstance:function(a,b){"/"===a.substr(-1)&&(a=a.slice(0,-1));a=a.toLowerCase();b=this._getServerInstanceRoot(b).toLowerCase();a=this._normalizeAGOLorgDomain(a);
b=this._normalizeAGOLorgDomain(b);a=a.substr(a.indexOf(":"));b=b.substr(b.indexOf(":"));return a===b},_normalizeAGOLorgDomain:function(a){var b=/^https?:\/\/.+\.maps\.arcgis\.com/i,c=/^https?:\/\/.+\.mapsdevext\.arcgis\.com/i,d=/^https?:\/\/.+\.mapsqa\.arcgis\.com/i;b.test(a)?a=a.replace(b,"https://www.arcgis.com"):c.test(a)?a=a.replace(c,"https://devext.arcgis.com"):d.test(a)&&(a=a.replace(d,"https://qaext.arcgis.com"));return a},_sanitizeUrl:function(a){var b=(R.request.proxyUrl||"").toLowerCase(),
c=b?a.toLowerCase().indexOf(b+"?"):-1;-1!==c&&(a=a.substring(c+b.length+1));a=v.normalize(a);return v.urlToObject(a).path},_isRESTService:function(a){return-1<a.indexOf(this._agsRest)},_isAdminResource:function(a){return this._agsAdmin.test(a)||this._adminSvcs.test(a)},_isServerRsrc:function(a){return this._isRESTService(a)||this._isAdminResource(a)},_isIdenticalService:function(a,b){var c;this._isRESTService(a)&&this._isRESTService(b)?(a=this._getSuffix(a).toLowerCase(),b=this._getSuffix(b).toLowerCase(),
c=a===b,c||(c=/(.*)\/(MapServer|FeatureServer).*/ig,c=a.replace(c,"$1")===b.replace(c,"$1"))):this._isAdminResource(a)&&this._isAdminResource(b)?c=!0:this._isServerRsrc(a)||this._isServerRsrc(b)||!this._isPortalDomain(a)||(c=!0);return c},_isPortalDomain:function(a){a=a.toLowerCase();var b=(new r(a)).authority,c=this._portalConfig,d=-1!==b.indexOf(this._agolSuffix);!d&&c&&(d=this._hasSameServerInstance(this._getServerInstanceRoot(c.restBaseUrl),a));d||(!this._arcgisUrl&&(c=y.getDeepValue("esri.arcgis.utils.arcgisUrl",
G))&&(this._arcgisUrl=(new r(c)).authority),this._arcgisUrl&&(d=this._arcgisUrl.toLowerCase()===b));d||(d=l.some(this._portals,function(b){return this._hasSameServerInstance(b,a)},this));return d=d||this._agsPortal.test(a)},_isIdProvider:function(a,b){var c=-1,d=-1;l.forEach(this._gwDomains,function(e,f){-1===c&&e.regex.test(a)&&(c=f);-1===d&&e.regex.test(b)&&(d=f)});var e=!1;if(-1<c&&-1<d)if(0===c||4===c){if(0===d||4===d)e=!0}else if(1===c){if(1===d||2===d)e=!0}else 2===c?2===d&&(e=!0):3===c&&3===
d&&(e=!0);if(!e){var f=this.findServerInfo(b),k=f&&f.owningSystemUrl;k&&M(f)&&this._isPortalDomain(k)&&this._isIdProvider(a,k)&&(e=!0)}return e},_isPublic:function(a){a=this._sanitizeUrl(a);return l.some(this._publicUrls,function(b){return b.test(a)})},_getIdenticalSvcIdx:function(a,b){var c=-1;l.some(b.resources,function(b,e){return this._isIdenticalService(a,b)?(c=e,!0):!1},this);return c},_getSuffix:function(a){return a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"$1")},_getTokenSvcUrl:function(a){var b,
c,d=this._isRESTService(a);if(d||this._isAdminResource(a))return c=a.toLowerCase().indexOf(d?this._agsRest:"/admin/"),b=a.substring(0,c)+"/admin/generateToken",a=a.substring(0,c)+(d?"/rest/info":"/info"),c=x(a,{query:{f:"json"},responseType:"json"}).then(function(a){return a.data}),{adminUrl:b,promise:c};if(this._isPortalDomain(a)){var e="";l.some(this._gwDomains,function(b){b.regex.test(a)&&(e=b.tokenServiceUrl);return!!e});e||l.some(this._portals,function(b){this._hasSameServerInstance(b,a)&&(e=
b+this._gwTokenUrl);return!!e},this);e||(c=a.toLowerCase().indexOf("/sharing"),-1!==c&&(e=a.substring(0,c)+this._gwTokenUrl));e||(e=this._getOrigin(a)+this._gwTokenUrl);e&&(b=(new r(a)).port,/^http:\/\//i.test(a)&&"7080"===b&&(e=e.replace(/:7080/i,":7443")),e=e.replace(/http:/i,"https:"));return e}if(-1!==a.toLowerCase().indexOf("premium.arcgisonline.com"))return"https://premium.arcgisonline.com/server/tokens"},_getPortalSelf:function(a,b){"https:"===window.location.protocol?a=a.replace(/^http:/i,
"https:").replace(/:7080/i,":7443"):/^http:/i.test(b)&&(a=a.replace(/^https:/i,"http:").replace(/:7443/i,":7080"));return x(a,{query:{f:"json"},authMode:"anonymous",responseType:"json",withCredentials:!0}).then(function(a){return a.data})},_hasPortalSession:function(){return!!this._getEsriAuthCookie()},_getEsriAuthCookie:function(){var a=null;if(D.isSupported()){var b=this._getAllCookies("esri_auth"),c;for(c=0;c<b.length;c++){var d=JSON.parse(b[c]);if(d.portalApp){a=d;break}}}a&&(b=null,a.expires&&
("number"===typeof a.expires?b=a.expires:"string"===typeof a.expires&&(b=Date.parse(a.expires)),isNaN(b)&&(b=null),a.expires=b),b&&b<Date.now()&&(a=null));return a},_getAllCookies:function(a){var b=[],c=document.cookie.match(new RegExp("(?:^|; )"+Q.escapeString(a)+"\x3d([^;]*)","g"));if(c)for(a=0;a<c.length;a++){var d=c[a],e=d.indexOf("\x3d");-1<e&&(d=d.substring(e+1),b.push(decodeURIComponent(d)))}return b},_doPortalSignIn:function(a){if(D.isSupported()){var b=this._getEsriAuthCookie(),c=this._portalConfig,
d=window.location.href,e=this.findServerInfo(a);if(this.useSignInPage&&(c||this._isPortalDomain(d)||b)&&(e?e.hasPortal||e.owningSystemUrl&&this._isPortalDomain(e.owningSystemUrl):this._isPortalDomain(a))&&(this._isIdProvider(d,a)||c&&(this._hasSameServerInstance(this._getServerInstanceRoot(c.restBaseUrl),a)||this._isIdProvider(c.restBaseUrl,a))||v.hasSameOrigin(d,a,!0)))return!0}return!1},_checkProtocol:function(a,b,c,d){var e=!0;d=d?b.adminTokenServiceUrl:b.tokenServiceUrl;0===d.trim().toLowerCase().indexOf("https:")&&
0!==window.location.href.toLowerCase().indexOf("https:")&&v.getProxyRule(d)&&(e=this._protocolFunc?!!this._protocolFunc({resourceUrl:a,serverInfo:b}):!1,e||(a=new q("identity-manager:aborted","Aborted the Sign-In process to avoid sending password over insecure connection."),c(a)));return e},_enqueue:function(a,b,c,d,e,f){d||(d=I.makeDeferredCancellingPending());d.resUrl_=a;d.sinfo_=b;d.options_=c;d.admin_=e;d.refresh_=f;this._busy?this._hasSameServerInstance(this._getServerInstanceRoot(a),this._busy.resUrl_)?
(this._oAuthDfd&&this._oAuthDfd.oAuthWin_&&this._oAuthDfd.oAuthWin_.focus(),this._soReqs.push(d)):this._xoReqs.push(d):this._doSignIn(d);return d.promise},_doSignIn:function(a){this._busy=a;this._rejectOnPersistedPageShow=!1;var b=this,c=function(c){var d=a.options_&&a.options_.resource,h=a.resUrl_,e=a.refresh_,z=!1;-1===l.indexOf(b.credentials,c)&&(e&&-1!==l.indexOf(b.credentials,e)?(e.userId=c.userId,e.token=c.token,e.expires=c.expires,e.validity=c.validity,e.ssl=c.ssl,e.creationTime=c.creationTime,
z=!0,c=e):b.credentials.push(c));c.resources||(c.resources=[]);c.resources.push(d||h);c.scope=b._isServerRsrc(h)?"server":"portal";c.emitTokenChange();var d=b._soReqs,f={};b._soReqs=[];l.forEach(d,function(a){if(!this._isIdenticalService(h,a.resUrl_)){var b=this._getSuffix(a.resUrl_);f[b]||(f[b]=!0,c.resources.push(a.resUrl_))}},b);a.resolve(c);l.forEach(d,function(a){this._hasSameServerInstance(this._getServerInstanceRoot(h),a.resUrl_)?a.resolve(c):this._soReqs.push(a)},b);b._busy=a.resUrl_=a.sinfo_=
a.refresh_=null;z||b.emit("credential-create",{credential:c});b._soReqs.length?b._doSignIn(b._soReqs.shift()):b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},d=function(c){a.reject(c);b._busy=a.resUrl_=a.sinfo_=a.refresh_=null;b._soReqs.length?b._doSignIn(b._soReqs.shift()):b._xoReqs.length&&b._doSignIn(b._xoReqs.shift())},e=function(e,f,k,l){var h=a.sinfo_,n=!a.options_||!1!==a.options_.prompt,g=h.hasPortal&&b._findOAuthInfo(a.resUrl_);b._doPortalSignIn(a.resUrl_)?(e=b._getEsriAuthCookie(),g=b._portalConfig,
e?(h.webTierAuth||"web"!==(e.auth_tier&&e.auth_tier.toLowerCase())||(h.webTierAuth=!0),c(new p({userId:e.email,server:h.server,token:e.token,expires:e.expires}))):n?(n="",e=window.location.href,n=b.signInPage?b.signInPage:g?g.baseUrl+g.signin:b._isIdProvider(e,a.resUrl_)?b._getOrigin(e)+"/home/signin.html":h.tokenServiceUrl.replace(b._rePortalTokenSvc,"")+"/home/signin.html",n=n.replace(/http:/i,"https:"),g&&!1===g.useSSL&&(n=n.replace(/https:/i,"http:")),0===e.toLowerCase().replace("https","http").indexOf(n.toLowerCase().replace("https",
"http"))?(h=new q("identity-manager:unexpected-error","Cannot redirect to Sign-In page from within Sign-In page. URL of the resource that triggered this workflow: "+a.resUrl_),d(h)):(b._rejectOnPersistedPageShow=!0,b._redirectFunc?b._redirectFunc({signInPage:n,returnUrlParamName:"returnUrl",returnUrl:e,resourceUrl:a.resUrl_,serverInfo:h}):window.location=n+"?returnUrl\x3d"+window.escape(e))):(h=new q("identity-manager:not-authenticated","User is not signed in."),d(h))):e?c(new p({userId:e,server:h.server,
token:k,expires:null!=l?Number(l):null,ssl:!!f})):g?(e=g._oAuthCred,e||(f=new K(g,window.localStorage),k=new K(g,window.sessionStorage),f.isValid()&&k.isValid()?f.expires>k.expires?(e=f,k.destroy()):(e=k,f.destroy()):e=f.isValid()?f:k,g._oAuthCred=e),e.isValid()?c(new p({userId:e.userId,server:h.server,token:e.token,expires:e.expires,ssl:e.ssl,_oAuthCred:e})):b._oAuthHash&&b._oAuthHash.state.portalUrl===g.portalUrl?(n=b._oAuthHash,h=new p({userId:n.username,server:h.server,token:n.access_token,expires:(new Date).getTime()+
1E3*Number(n.expires_in),ssl:"true"===n.ssl,oAuthState:n.state,_oAuthCred:e}),e.storage=n.persist?window.localStorage:window.sessionStorage,e.token=h.token,e.expires=h.expires,e.userId=h.userId,e.ssl=h.ssl,e.save(),b._oAuthHash=null,c(h)):n?a._pendingDfd=b.oAuthSignIn(a.resUrl_,h,g,a.options_).then(c,d):(h=new q("identity-manager:not-authenticated","User is not signed in."),d(h))):n?b._checkProtocol(a.resUrl_,h,d,a.admin_)&&(n=a.options_,a.admin_&&(n=n||{},n.isAdmin=!0),a._pendingDfd=b.signIn(a.resUrl_,
h,n).then(c,d)):(h=new q("identity-manager:not-authenticated","User is not signed in."),d(h))},f=function(){var e=a.sinfo_,f=e.owningSystemUrl,g=a.options_,k,m,n,u;g&&(k=g.token,m=g.error,n=g.prompt);(u=b._findCredential(f,{token:k,resource:a.resUrl_}))||l.some(b.credentials,function(a){this._isIdProvider(f,a.server)&&(u=a);return!!u},b);u?(g=b.findCredential(a.resUrl_,u.userId))?c(g):F(e,b._legacyFed)?(g=u.toJSON(),g.server=e.server,g.resources=null,c(new p(g))):(a._pendingDfd=b.generateToken(b.findServerInfo(u.server),
null,{serverUrl:a.resUrl_,token:u.token,ssl:u.ssl})).then(function(b){c(new p({userId:u.userId,server:e.server,token:b.token,expires:null!=b.expires?Number(b.expires):null,ssl:!!b.ssl,isAdmin:a.admin_,validity:b.validity}))},d):(b._busy=null,k&&(a.options_.token=null),(a._pendingDfd=b.getCredential(f.replace(/\/?$/,"/sharing"),{resource:a.resUrl_,owningTenant:e.owningTenant,token:k,error:m,prompt:n})).then(function(c){b._enqueue(a.resUrl_,a.sinfo_,a.options_,a,a.admin_)},function(a){d(a)}))};this._errbackFunc=
d;var k=a.sinfo_.owningSystemUrl,g=this._isServerRsrc(a.resUrl_),m=a.sinfo_._restInfoPms;m?m.promise.then(function(c){var d=a.sinfo_;d.adminTokenServiceUrl=d._restInfoPms.adminUrl;d._restInfoPms=null;d.tokenServiceUrl=y.getDeepValue("authInfo.tokenServicesUrl",c)||y.getDeepValue("authInfo.tokenServiceUrl",c)||y.getDeepValue("tokenServiceUrl",c);d.shortLivedTokenValidity=y.getDeepValue("authInfo.shortLivedTokenValidity",c);d.currentVersion=c.currentVersion;d.owningTenant=c.owningTenant;(c=d.owningSystemUrl=
c.owningSystemUrl)&&b._portals.push(c);g&&c?f():e()},function(){a.sinfo_._restInfoPms=null;var b=new q("identity-manager:server-identification-failed","Unknown resource - could not find token service endpoint.");d(b)}):g&&k?f():a.sinfo_._selfReq?a.sinfo_._selfReq.selfDfd.then(function(c){var d={},e,g,f,h;c&&(e=c.user&&c.user.username,d.username=e,d.allSSL=c.allSSL,g=c.supportsOAuth,f=c.currentVersion,"multitenant"===c.portalMode&&(h=c.customBaseUrl));a.sinfo_.webTierAuth=!!e;return e&&b.normalizeWebTierAuth?
b.generateToken(a.sinfo_,null,{ssl:d.allSSL}).always(function(a){d.portalToken=a&&a.token;d.tokenExpiration=a&&a.expires;return d}):!e&&g&&4.4<=parseFloat(f)&&!b._doPortalSignIn(a.resUrl_)?b._generateOAuthInfo({portalUrl:a.sinfo_.server,customBaseUrl:h,owningTenant:a.sinfo_._selfReq.owningTenant}).always(function(){return d}):d}).always(function(b){a.sinfo_._selfReq=null;b?e(b.username,b.allSSL,b.portalToken,b.tokenExpiration):e()}):e()},_generateOAuthInfo:function(a){var b=this,c,d=a.portalUrl,e=
a.customBaseUrl,f=a.owningTenant;if(a=!this.defaultOAuthInfo&&this._createDefaultOAuthInfo&&!this._hasTestedIfAppIsOnPortal){c=window.location.href;var k=c.indexOf("?");-1<k&&(c=c.slice(0,k));k=c.search(/\/(apps|home)\//);c=-1<k?c.slice(0,k):null}a&&c?(this._hasTestedIfAppIsOnPortal=!0,a=x(c+"/sharing/rest",{query:{f:"json"},responseType:"json"}).then(function(){b.defaultOAuthInfo=new L({appId:"arcgisonline",popup:!0,popupCallbackUrl:c+"/home/oauth-callback.html"})})):(a=new O,a.resolve(),a=a.promise);
return a.then(function(){if(b.defaultOAuthInfo)return d=d.replace(/^http:/i,"https:"),x(d+"/sharing/rest/oauth2/validateRedirectUri",{query:{accountId:f,client_id:b.defaultOAuthInfo.appId,redirect_uri:v.makeAbsolute(b.defaultOAuthInfo.popupCallbackUrl),f:"json"},responseType:"json"}).then(function(a){if(a.data.valid){var c=b.defaultOAuthInfo.clone();c.portalUrl=a.data.urlKey&&e?"https://"+a.data.urlKey+"."+e:d;b.oAuthInfos.push(c)}})})}});p=S.createSubclass([J],{declaredClass:"esri.identity.Credential",
constructor:function(a){a&&a._oAuthCred&&(this._oAuthCred=a._oAuthCred)},initialize:function(){this.resources=this.resources||[];null==this.creationTime&&(this.creationTime=(new Date).getTime())},_oAuthCred:null,properties:{creationTime:{},expires:{},isAdmin:{},oAuthState:{},resources:{},scope:{},server:{},ssl:{},token:{},tokenRefreshBuffer:2,userId:{},validity:{}},refreshToken:function(){var a=this,b=this.resources&&this.resources[0],c=m.id.findServerInfo(this.server),d=c&&c.owningSystemUrl,e=!!d&&
"server"===this.scope,f=e&&F(c,m.id._legacyFed),k=e&&m.id.findServerInfo(d),g,q=(g=c.webTierAuth)&&m.id.normalizeWebTierAuth,h=B[this.server],h=h&&h[this.userId],t={username:this.userId,password:h},p;if(!g||q)if(e&&!k&&l.some(m.id.serverInfos,function(a){m.id._isIdProvider(d,a.server)&&(k=a);return!!k}),g=k&&m.id.findCredential(k.server,this.userId),!e||g)if(f)g.refreshToken();else{if(e)p={serverUrl:b,token:g&&g.token,ssl:g&&g.ssl};else if(q)t=null,p={ssl:this.ssl};else if(h)this.isAdmin&&(p={isAdmin:!0});
else{var r;b&&(b=m.id._sanitizeUrl(b),this._enqueued=1,r=m.id._enqueue(b,c,null,null,this.isAdmin,this),r.then(function(){a._enqueued=0;a.refreshServerTokens()}).then(null,function(){a._enqueued=0}));return r}return m.id.generateToken(e?k:c,e?null:t,p).then(function(b){a.token=b.token;a.expires=null!=b.expires?Number(b.expires):null;a.creationTime=(new Date).getTime();a.validity=b.validity;a.emitTokenChange();a.refreshServerTokens()}).then(null,function(){})}},refreshServerTokens:function(){"portal"===
this.scope&&l.forEach(m.id.credentials,function(a){var b=m.id.findServerInfo(a.server),c=b&&b.owningSystemUrl;a!==this&&a.userId===this.userId&&c&&"server"===a.scope&&(m.id._hasSameServerInstance(this.server,c)||m.id._isIdProvider(c,this.server))&&(F(b,m.id._legacyFed)?(a.token=this.token,a.expires=this.expires,a.creationTime=this.creationTime,a.validity=this.validity,a.emitTokenChange()):a.refreshToken())},this)},emitTokenChange:function(a){clearTimeout(this._refreshTimer);var b=this.server&&m.id.findServerInfo(this.server),
c=(b=b&&b.owningSystemUrl)&&m.id.findServerInfo(b);!1===a||b&&"portal"!==this.scope&&(!c||!c.webTierAuth||m.id.normalizeWebTierAuth)||null==this.expires&&null==this.validity||this._startRefreshTimer();this.emit("token-change")},destroy:function(){this.userId=this.server=this.token=this.expires=this.validity=this.resources=this.creationTime=null;this._oAuthCred&&(this._oAuthCred.destroy(),this._oAuthCred=null);var a=l.indexOf(m.id.credentials,this);-1<a&&m.id.credentials.splice(a,1);this.emitTokenChange();
this.emit("destroy")},toJSON:function(){var a=w.fixJson({userId:this.userId,server:this.server,token:this.token,expires:this.expires,validity:this.validity,ssl:this.ssl,isAdmin:this.isAdmin,creationTime:this.creationTime,scope:this.scope}),b=this.resources;b&&0<b.length&&(a.resources=b.slice());return a},_startRefreshTimer:function(){clearTimeout(this._refreshTimer);var a=6E4*this.tokenRefreshBuffer,b=(this.validity?this.creationTime+6E4*this.validity:this.expires)-(new Date).getTime();0>b&&(b=0);
this._refreshTimer=setTimeout(this.refreshToken.bind(this),b>a?b-a:b)}});A.Credential=p;return A});