// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/DynamicLayer":function(){define("require exports ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../request ../core/Error ../core/promiseUtils ../core/accessorSupport/decorators ./Layer".split(" "),function(r,t,k,n,c,d,f,l,m){return function(p){function b(){return null!==p&&p.apply(this,arguments)||this}k(b,p);b.prototype.getImageUrl=function(a,h,b,c){throw new d("dynamiclayer:getImageUrl-not-implemented","getImageUrl() is not implemented");};b.prototype.fetchImage=
function(a,h,b,g){a=this.getImageUrl(a,h,b,g);var e={responseType:"image"};g&&g.timestamp&&(e.query={_ts:g.timestamp});var q;"string"===typeof a?(q=a,g=c(a,e)):g=a.then(function(a){q=a;return c(q,e)});return g.then(function(a){return a.data}).catch(function(a){return a&&"cancel"===a.dojoType?f.reject(a):q?f.reject(new d("dynamiclayer:image-fetch-error","Unable to load image: "+q,{error:a})):f.reject(new d("dynamiclayer:getImageUrl-error","Unable to create image url",{error:a}))})};b.prototype.importLayerViewModule=
function(a){switch(a.type){case "2d":return f.create(function(a){return r(["../views/2d/layers/MapImageLayerView2D"],a)});case "3d":return f.create(function(a){return r(["../views/3d/layers/MapImageLayerView3D"],a)})}};return b=n([l.subclass("esri.layers.DynamicLayer")],b)}(l.declared(m))})},"esri/layers/mixins/ArcGISDynamicMapService":function(){define("require exports ../../core/tsSupport/assignHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ../../geometry/support/scaleUtils ./ArcGISMapService ./ScaleRangeLayer ../support/ExportImageParameters".split(" "),
function(r,t,k,n,c,d,f,l,m,p){return function(b){function a(){var a=b.call(this)||this;a.dpi=96;a.gdbVersion=null;a.imageFormat="png24";a.imageMaxHeight=2048;a.imageMaxWidth=2048;a.imageTransparency=!0;a.loaded=!1;return a}n(a,b);a.prototype.readImageFormat=function(a,b){return(a=b.supportedImageFormatTypes)&&-1<a.indexOf("PNG32")?"png32":"png24"};a.prototype.createExportImageParameters=function(a,b,c,e){a&&10<=this.version&&(a=a.clone().shiftCentralMeridian());var h=new p({layer:this,scale:f.getScale({extent:a,
width:b})}),d=h.toJSON();h.layer=null;h.destroy();var h=!e||!e.rotation||10.3>this.version?{}:{rotation:-e.rotation},g=a&&a.spatialReference,g=g.wkid||JSON.stringify(g.toJSON());e&&null!=e.pixelRatio&&(d.dpi*=e.pixelRatio);return k({bbox:a&&a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,bboxSR:g,imageSR:g,size:b+","+c},d,h)};c([d.property()],a.prototype,"dpi",void 0);c([d.property()],a.prototype,"gdbVersion",void 0);c([d.property()],a.prototype,"imageFormat",void 0);c([d.reader("imageFormat",["supportedImageFormatTypes"])],
a.prototype,"readImageFormat",null);c([d.property({json:{origins:{service:{read:{source:"maxImageHeight"}}}}})],a.prototype,"imageMaxHeight",void 0);c([d.property({json:{origins:{service:{read:{source:"maxImageWidth"}}}}})],a.prototype,"imageMaxWidth",void 0);c([d.property()],a.prototype,"imageTransparency",void 0);c([d.property()],a.prototype,"loaded",void 0);return a=c([d.subclass("esri.layers.mixins.ArcGISDynamicMapService")],a)}(d.declared(l,m))})},"esri/layers/support/ExportImageParameters":function(){define("require exports ../../core/tsSupport/assignHelper ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/Accessor ../../core/accessorSupport/decorators ./sublayerUtils".split(" "),
function(r,t,k,n,c,d,f,l){var m={visible:"visibleSublayers",definitionExpression:"layerDefs",labelingInfo:"hasDynamicLayers",labelsVisible:"hasDynamicLayers",opacity:"hasDynamicLayers",minScale:"visibleSublayers",maxScale:"visibleSublayers",renderer:"hasDynamicLayers",source:"hasDynamicLayers"};return function(d){function b(){var a=null!==d&&d.apply(this,arguments)||this;a.scale=0;return a}n(b,d);Object.defineProperty(b.prototype,"dynamicLayers",{get:function(){if(!this.hasDynamicLayers)return null;
var a=this.visibleSublayers.map(function(a){return a.toExportImageJSON()});return a.length?JSON.stringify(a):null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"hasDynamicLayers",{get:function(){return l.isExportDynamic(this.visibleSublayers,this.layer.serviceSublayers,this.layer)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"layer",{set:function(a){var b=this;this._get("layer")!==a&&(this._set("layer",a),this._layerHandles&&(this._layerHandles.forEach(function(a){return a.remove()}),
this._layerHandles.length=0),a&&(this._layerHandles=[a.allSublayers.on("change",function(){return b.notifyChange("visibleSublayers")}),a.on("sublayer-update",function(a){return b.notifyChange(m[a.propertyName])})]))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"layers",{get:function(){var a=this.visibleSublayers;return a?a.length?"show:"+a.map(function(a){return a.id}).join(","):"show:-1":null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"layerDefs",{get:function(){var a=
this.visibleSublayers.filter(function(a){return null!=a.definitionExpression});return a.length?JSON.stringify(a.reduce(function(a,b){a[b.id]=b.definitionExpression;return a},{})):null},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"version",{get:function(){return(this._get("version")||0)+1},set:function(a){this._set("version",a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"visibleSublayers",{get:function(){var a=this,b=this.layer.sublayers,c=[],d=function(b){var f=
a.scale,g=0===b.minScale||f<=b.minScale,e=0===b.maxScale||f>=b.maxScale;b.visible&&(0===f||g&&e)&&(b.sublayers?b.sublayers.forEach(d):c.unshift(b))};b&&b.forEach(d);return c},enumerable:!0,configurable:!0});b.prototype.toJSON=function(){var a=this.layer,a={dpi:a.dpi,format:a.imageFormat,transparent:a.imageTransparency,gdbVersion:a.gdbVersion||null};this.hasDynamicLayers&&this.dynamicLayers?a.dynamicLayers=this.dynamicLayers:a=k({},a,{layers:this.layers,layerDefs:this.layerDefs});return a};c([f.property({readOnly:!0,
dependsOn:["hasDynamicLayers","visibleSublayers"]})],b.prototype,"dynamicLayers",null);c([f.property({readOnly:!0,dependsOn:["visibleSublayers","layer.serviceSublayers","layer.capabilities"]})],b.prototype,"hasDynamicLayers",null);c([f.property()],b.prototype,"layer",null);c([f.property({readOnly:!0,dependsOn:["visibleSublayers"]})],b.prototype,"layers",null);c([f.property({readOnly:!0,dependsOn:["visibleSublayers"]})],b.prototype,"layerDefs",null);c([f.property({type:Number})],b.prototype,"scale",
void 0);c([f.property({dependsOn:"layers layerDefs dynamicLayers layer.dpi layer.imageFormat layer.imageTransparency layer.gdbVersion".split(" ")})],b.prototype,"version",null);c([f.property({readOnly:!0,dependsOn:["layer.sublayers","scale"]})],b.prototype,"visibleSublayers",null);return b=c([f.subclass("esri.layers.mixins.ExportImageParameters")],b)}(f.declared(d))})},"*noref":1}});
define("require exports ../core/tsSupport/assignHelper ../core/tsSupport/declareExtendsHelper ../core/tsSupport/decorateHelper ../core/tsSupport/paramHelper dojo/io-query ../config ../request ../core/Error ../core/promiseUtils ../core/accessorSupport/decorators ../geometry/Extent ./DynamicLayer ./mixins/ArcGISDynamicMapService ./mixins/OperationalLayer ./mixins/PortalLayer ./mixins/RefreshableLayer ./mixins/ScaleRangeLayer ./mixins/SublayersOwner".split(" "),function(r,t,k,n,c,d,f,l,m,p,b,a,h,u,g,
e,q,v,w,x){return function(g){function e(a,b){a=g.call(this)||this;a.alwaysRefetch=!1;a.labelsVisible=!1;a.operationalLayerType="ArcGISMapServiceLayer";a.sublayers=null;a.type="map-image";return a}n(e,g);e.prototype.normalizeCtorArgs=function(a,b){return"string"===typeof a?k({url:a},b):a};e.prototype.load=function(){var a=this;this.addResolvingPromise(this.loadFromPortal({supportedTypes:["Map Service"]}).then(function(){return a._fetchService()}));return this.when()};e.prototype.getImageUrl=function(a,
c,d,e){var g=this,h=this.parsedUrl.path+"/export";a=k({},this.parsedUrl.query,this.createExportImageParameters(a,c,d,e),{f:"image",token:this.token,_ts:this.alwaysRefetch?(new Date).getTime():null});if(null!=a.dynamicLayers&&!this.capabilities.exportMap.supportsDynamicLayers)return b.reject(new p("mapimagelayer:dynamiclayer-not-supported","service "+this.url+" doesn't support dynamic layers, which is required to be able to change the sublayer's order, rendering, labeling or source.",{query:a}));c=
h+"?"+f.objectToQuery(a);return c.length>l.request.maxUrlLength?(a.f="json",m(h,{query:a,responseType:"json"}).then(function(a){if("imageData"in a.data)return a=a.data,"data:"+(a.contentType||"image")+";base64,"+a.imageData;a=a.data.href;return g.token?a+(-1===a.indexOf("?")?"?token\x3d"+g.token:"\x26token\x3d"+g.token):a})):c};e.prototype._fetchService=function(){var a=this;return b.resolve().then(function(){return a.resourceInfo?{ssl:!1,data:a.resourceInfo}:m(a.parsedUrl.path,{query:k({f:"json"},
a.parsedUrl.query),responseType:"json"})}).then(function(b){b.ssl&&(a.url=a.url.replace(/^http:/i,"https:"));a.read(b.data,{origin:"service",url:a.parsedUrl})})};c([a.property()],e.prototype,"alwaysRefetch",void 0);c([a.property({json:{read:!1,write:!1}})],e.prototype,"labelsVisible",void 0);c([a.property({json:{type:["ArcGISMapServiceLayer"]}})],e.prototype,"operationalLayerType",void 0);c([a.property()],e.prototype,"sublayers",void 0);c([a.property({json:{read:!1},readOnly:!0,value:"map-image"})],
e.prototype,"type",void 0);c([d(0,a.cast(h))],e.prototype,"getImageUrl",null);return e=c([a.subclass("esri.layers.MapImageLayer")],e)}(a.declared(u,x.default,g,e,q,v,w))});