// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../../core/tsSupport/declareExtendsHelper ../../../../../core/tsSupport/decorateHelper ../../../../../core/Accessor ../../../../../core/Handles ../../../../../core/accessorSupport/decorators ../../../lib/gl-matrix ../../../support/geometryUtils/boundedPlane ../../../support/geometryUtils/plane".split(" "),function(r,y,w,l,x,t,e,b,p,m){function u(k,c,a,g,f,n,d){b.vec3d.cross(c,a,d.basis2);b.vec3d.cross(d.basis2,c,d.basis1);b.vec3d.normalize(d.basis1);b.vec3d.scale(d.basis1,
f);b.vec3d.normalize(d.basis2);b.vec3d.scale(d.basis2,n);b.vec3d.set(c,d.origin);b.vec3d.scale(d.origin,-g);b.vec3d.add(d.origin,k);return p.fromValues(d.origin,d.basis1,d.basis2,d)}function q(b){return"mouse"!==b.pointerType||0===b.button}r=function(k){function c(a){a=k.call(this)||this;a._isPointerDown=!1;a._startPlane=m.create();a._planeOrigin=b.vec3d.create();a._planeNormal=b.vec3d.create();a._planeDepth=0;a._dragPlane=m.create();return a}w(c,k);c.prototype.initialize=function(){this._handles=
new t;this._viewHandles=new t};Object.defineProperty(c.prototype,"plane",{set:function(a){this._set("plane",a);this.view.slicePlane=a},enumerable:!0,configurable:!0});c.prototype.activate=function(){var a=this;this.plane=null;this._slicePlaneEnabled=!0;var c=this.view,f=b.vec3d.create(),n=b.vec3d.create(),d=b.vec3d.create(),e=b.vec3d.create();this._viewHandles.add([c.on("pointer-down",function(d){if(q(d)){var f=c.sceneIntersectionHelper.pickSelectorInScreen([d.x,c.height-d.y]),h=f.minResult;if(h.getIntersectionPoint(a._planeOrigin)){h.getTransformedNormal(a._planeNormal);
b.vec3d.scale(a._planeNormal,-1);a._planeDepth=0;a.plane=a._createInitialPlane(a.plane||p.create());p.toPlane(a.plane,a._startPlane);var h=a._planeOrigin,e=a._planeNormal,g=f.getDirection(),f=a._dragPlane,g=b.vec3d.cross(e,g,b.vec3d.create());b.vec3d.cross(g,e,g);m.fromPositionAndNormal(h,g,f);a._isPointerDown=!0;d.stopPropagation()}}}),c.on("pointer-drag",function(h){if(q(h)&&a._isPointerDown){c.sceneIntersectionHelper.getPickRay([h.x,c.height-h.y],f,n);b.vec3d.subtract(n,f,d);if(m.intersectRay(a._dragPlane,
f,d,e)){a._planeDepth=-m.distance(a._startPlane,e);var g=b.vec3d.length(a.plane.basis1),k=b.vec3d.length(a.plane.basis2),l=a.view.renderCoordsHelper.worldUpAtPosition(a._planeOrigin,v);a.plane=u(a._planeOrigin,a._planeNormal,l,a._planeDepth,g,k,a.plane)}h.stopPropagation()}}),c.on("click",function(a){q(a)&&a.stopPropagation()}),c.on("drag",function(b){a._isPointerDown&&b.stopPropagation()}),c.on("pointer-up",function(b){a._isPointerDown&&(a._isPointerDown=!1,b.stopPropagation())})])};c.prototype.deactivate=
function(){this.plane=null;this._slicePlaneEnabled=!1;this._handles.removeAll();this._viewHandles.removeAll()};c.prototype.destroy=function(){this._handles.destroy();this._handles=null;this._viewHandles.destroy();this._viewHandles=null};Object.defineProperty(c.prototype,"_slicePlaneEnabled",{set:function(a){this.view.allLayerViews.forEach(function(b){"slicePlaneEnabled"in b&&(b.slicePlaneEnabled=a)})},enumerable:!0,configurable:!0});c.prototype._createInitialPlane=function(a){var b=this.view.renderCoordsHelper.worldUpAtPosition(this._planeOrigin,
v),c=this.view,e=c._stage.getCamera(),c=.5*Math.min(c.width,c.height)*e.computePixelSizeAt(this._planeOrigin);return u(this._planeOrigin,this._planeNormal,b,this._planeDepth,c,c,a)};l([e.property({constructOnly:!0})],c.prototype,"view",void 0);l([e.property()],c.prototype,"plane",null);return c=l([e.subclass("esri.views.3d.interactive.analysisTools.slice.SliceTool")],c)}(e.declared(x));var v=b.vec3d.create();return r});