// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/libs/gl-matrix/mat4 ../../../core/libs/gl-matrix/vec3 ../../../core/libs/gl-matrix/vec4 ../GeometryUtils ./rendererUtils ../../webgl/VertexArrayObject".split(" "),function(x,y,r,t,q,v,w,u){return function(){function n(d){this._initialized=!1;this._programOptions={id:!1};this._programCache=d;this._viewProjMat=r.create();this._offsetVector=t.create();this._color=q.create();this._strokeColor=q.create()}n.prototype.dispose=function(){};n.prototype.render=function(d,
e,a,k,p,f,b,n,h){if(0!==e.triangleElementCount){this._initialized||this._initialize(d);var q=b.hasDataDrivenRadius?1:b.getPaintValue("circle-radius",a),c=b.hasDataDrivenColor?[1,1,1,1]:b.getPaintValue("circle-color",a),g=b.hasDataDrivenOpacity?1:b.getPaintValue("circle-opacity",a),t=b.hasDataDrivenStrokeWidth?1:b.getPaintValue("circle-stroke-width",a),l=b.hasDataDrivenStrokeColor?[1,1,1,1]:b.getPaintValue("circle-stroke-color",a),m=b.hasDataDrivenStrokeOpacity?1:b.getPaintValue("circle-stroke-opacity",
a),u=b.hasDataDrivenBlur?0:b.getPaintValue("circle-blur",a),g=g*c[3]*h;this._color[0]=g*c[0];this._color[1]=g*c[1];this._color[2]=g*c[2];this._color[3]=g;g=m*l[3]*h;this._strokeColor[0]=g*l[0];this._strokeColor[1]=g*l[1];this._strokeColor[2]=g*l[2];this._strokeColor[3]=g;h=f.tileTransform.transform;c=b.getPaintValue("circle-translate",a);if(0!==c[0]||0!==c[1])r.copy(this._viewProjMat,f.tileTransform.transform),h=c[0],c=c[1],m=l=0,m=(1<<f.key.level)/Math.pow(2,a)*(f.coordRange/512),1===b.getPaintValue("circle-translate-anchor",
a)?(p*=-v.C_DEG_TO_RAD,a=Math.sin(p),p=Math.cos(p),l=m*(h*p-c*a),m*=h*a+c*p):(l=m*h,m*=c),this._offsetVector[0]=l,this._offsetVector[1]=m,this._offsetVector[2]=0,r.translate(this._viewProjMat,this._viewProjMat,this._offsetVector),h=this._viewProjMat;if(a=this._getCircleVAO(d,f))d.bindVAO(a),k=3===k,a=this._programOptions,a.id=k,a=this._programCache.getProgram(5,k?1:0,a),d.bindProgram(a),a.setUniformMatrix4fv("u_transformMatrix",h),a.setUniformMatrix4fv("u_extrudeMatrix",n),a.setUniform2fv("u_normalized_origin",
f.tileTransform.displayCoord),a.setUniform1f("u_depth",b.z),a.setUniform1f("u_radius",q),a.setUniform4fv("u_color",this._color),a.setUniform1f("u_blur",u),a.setUniform1f("u_stroke_width",t),a.setUniform4fv("u_stroke_color",this._strokeColor),a.setUniform1f("u_antialiasingWidth",1.2),k&&(f=w.int32To4Bytes(e.layerID),a.setUniform4f("u_id",f[0],f[1],f[2],f[3])),d.drawElements(4,e.triangleElementCount,5125,12*e.triangleElementStart),d.bindVAO()}};n.prototype._initialize=function(d){if(this._initialized)return!0;
this._vertexAttributes={geometry:[{name:"a_pos",count:2,type:5122,offset:0,stride:16,normalized:!1,divisor:0},{name:"a_color",count:4,type:5121,offset:4,stride:16,normalized:!0,divisor:0},{name:"a_stroke_color",count:4,type:5121,offset:8,stride:16,normalized:!0,divisor:0},{name:"a_data",count:4,type:5121,offset:12,stride:16,normalized:!1,divisor:0}]};return this._initialized=!0};n.prototype._getCircleVAO=function(d,e){if(e.circleVertexArrayObject)return e.circleVertexArrayObject;var a=e.circleVertexBuffer,
k=e.circleIndexBuffer;if(!a||!k)return null;e.circleVertexArrayObject=new u(d,this._programCache.getProgramAttributes(5),this._vertexAttributes,{geometry:a},k);return e.circleVertexArrayObject};return n}()});