// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/libs/gl-matrix/mat4 ../GeometryUtils ./BackgroundRenderer ./CircleRenderer ./FadeRecorder ./FillRenderer ./LineRenderer ./SymbolRenderer ./TileInfoRenderer ./shaders/ProgramCache ../../webgl/FramebufferObject".split(" "),function(A,B,k,p,q,r,t,u,v,w,x,y,z){return function(){function e(){this._extrudeRotateVector=new Float32Array([0,0,1]);this._extrudeScaleVector=new Float32Array([1,1,1]);this._state={rotation:0,width:0,height:0};this._cachedRotation=this._cachedHeight=
this._cachedWidth=0;this._programCache=null}e.prototype.initialize=function(b,a,f){void 0===f&&(f=!0);this._SpriteMosaic=b;this._glyphMosaic=a;this._ignoreSpeed=!f;this._fadeRecorder=new t.FadeRecorder(300);this._extrudeMatrix=new Float32Array(16);this._extrudeNoRotationMatrix=new Float32Array(16);this._backgroundColor=new Float32Array([1,0,0,1])};e.prototype.dispose=function(){this._backgroundRenderer&&(this._backgroundRenderer.dispose(),this._backgroundRenderer=null);this._lineRenderer&&(this._lineRenderer.dispose(),
this._lineRenderer=null);this._fillRenderer&&(this._fillRenderer.dispose(),this._fillRenderer=null);this._symbolRenderer&&(this._symbolRenderer.dispose(),this._symbolRenderer=null);this._circleRenderer&&(this._circleRenderer.dispose(),this._circleRenderer=null);this._tileInfoRenderer&&(this._tileInfoRenderer.dispose(),this._tileInfoRenderer=null);this._hittestFBO&&(this._hittestFBO.dispose(),this._hittestFBO=null);this._programCache&&this._programCache.dispose()};e.prototype.initializeProgramCache=
function(b){if(null===this._programCache){var a=new y.default;a.initialize(b);this._backgroundRenderer=new q(a);this._lineRenderer=new v(a);this._fillRenderer=new u(a);this._symbolRenderer=new w(a);this._circleRenderer=new r(a);this._tileInfoRenderer=new x(a);this._programCache=a}};e.prototype.setStateParams=function(b,a,f){this._fadeRecorder.recordLevel(f);this._state=b;if(this._state.width!==this._cachedWidth||this._state.height!==this._cachedHeight||this._state.rotation!==this._cachedRotation)this._extrudeScaleVector[0]=
2/b.width,this._extrudeScaleVector[1]=-2/b.height,k.identity(this._extrudeMatrix),k.rotate(this._extrudeMatrix,this._extrudeMatrix,-b.rotation*p.C_DEG_TO_RAD,this._extrudeRotateVector),k.scale(this._extrudeMatrix,this._extrudeMatrix,this._extrudeScaleVector),k.transpose(this._extrudeMatrix,this._extrudeMatrix),k.identity(this._extrudeNoRotationMatrix),k.scale(this._extrudeNoRotationMatrix,this._extrudeNoRotationMatrix,this._extrudeScaleVector),k.transpose(this._extrudeNoRotationMatrix,this._extrudeNoRotationMatrix),
this._cachedWidth=this._state.width,this._cachedHeight=this._state.height,this._cachedRotation=this._state.rotation};e.prototype.drawClippingMasks=function(b,a){if(0!==a.length){b.setDepthWriteEnabled(!1);b.setDepthTestEnabled(!1);b.setStencilTestEnabled(!0);b.setBlendingEnabled(!1);b.setColorMask(!1,!1,!1,!1);b.setStencilOp(7680,7680,7681);b.setStencilWriteMask(255);b.setClearStencil(0);b.clear(b.gl.STENCIL_BUFFER_BIT);for(var f=0;f<a.length;f++){var d=a[f];d.attached&&d.visible&&(b.setStencilFunctionSeparate(1032,
519,d.stencilData.reference,d.stencilData.mask),this._backgroundRenderer.renderSolidColor(b,{u_matrix:d.tileTransform.transform,u_normalized_origin:d.tileTransform.displayCoord,u_coord_range:d.coordRange,u_depth:0,u_color:this._backgroundColor}))}b.setColorMask(!0,!0,!0,!0);b.setBlendingEnabled(!0)}};e.prototype.renderDebug=function(b,a){var f=a.key;this._backgroundColor.set([f.col%2,f.row%2,0===f.col%2&&0===f.row%2?1:0,.5]);this._backgroundRenderer.renderSolidColor(b,{u_matrix:a.tileTransform.transform,
u_normalized_origin:a.tileTransform.displayCoord,u_coord_range:a.coordRange,u_depth:0,u_color:this._backgroundColor})};e.prototype.renderBucket=function(b,a,f,d,c,g,h,e){if(!(void 0!==h.minzoom&&h.minzoom>f+1E-6||void 0!==h.maxzoom&&h.maxzoom<=f-1E-6))switch(a.type){case 0:2!==c&&this._renderBackground(b,a,f,c,g,h,e);break;case 1:2!==c&&this._renderFill(b,a,f,c,g,h,e);break;case 2:1!==c&&3!==c||this._renderLine(b,a,f,c,g,h,e);break;case 3:2!==c&&3!==c||this._renderSymbol(b,a,f,c,d,g,h,e);break;case 4:2!==
c&&3!==c||this._renderCircle(b,a,f,c,d,g,h,e)}};e.prototype.renderTileInfo=function(b,a){this._tileInfoRenderer.render(b,a)};e.prototype.needsRedraw=function(){return this._fadeRecorder.needsRedraw()};e.prototype.hitTest=function(b,a,f,d,c,g,h){var e=[0,0],m=[0,0],k=b.state;k.toMap(e,[0,0]);k.toMap(m,[g,g]);a=d.filter(function(a){return!(e[0]>a.bounds[2]||m[0]<a.bounds[0]||e[1]<a.bounds[3]||m[1]>a.bounds[1])});if(0===a.length)return[];a.sort(function(a,b){return a.key.level-b.key.level});f=a.length;
for(d=1;d<=f;d++){var l=a[d-1];l.attached&&(l.stencilData.reference=d,l.stencilData.mask=255)}h(k,c,a);c=b.context;this._hittestFBO||(this._hittestFBO=z.create(c,{colorTarget:0,depthStencilTarget:3,width:g,height:g}));h=c.getViewport();k=c.getBoundFramebufferObject();c.bindFramebuffer(this._hittestFBO);c.setViewport(0,0,g,g);d=c.gl;c.setDepthWriteEnabled(!0);c.setStencilWriteMask(255);c.setClearColor(1,1,1,1);c.setClearDepth(1);c.setClearStencil(0);c.clear(d.COLOR_BUFFER_BIT|d.DEPTH_BUFFER_BIT|d.STENCIL_BUFFER_BIT);
c.setDepthWriteEnabled(!1);this.drawClippingMasks(c,a);c.setBlendingEnabled(!1);c.setStencilWriteMask(0);c.setStencilOp(7680,7680,7681);c.setDepthFunction(515);c.setDepthTestEnabled(!0);c.setDepthWriteEnabled(!0);c.setStencilTestEnabled(!0);for(d=0;d<f;d++)l=a[d],l.attached&&l.doRender(b);c.setStencilTestEnabled(!1);c.setDepthTestEnabled(!1);this._readbackBuffer||(this._readbackBuffer=new Uint8Array(4*g*g),this._readbackBuffer32=new Uint32Array(this._readbackBuffer.buffer));this._hittestFBO.readPixels(0,
0,g,g,6408,5121,this._readbackBuffer);b=new Set;g*=g;a=this._readbackBuffer32[Math.round(g/2)];4294967295!==a&&b.add(a);for(d=0;d<g;d++)a=this._readbackBuffer32[d],4294967295!==a&&b.add(a);c.bindFramebuffer(k);c.setViewport(h.x,h.y,h.width,h.height);var n=[];b.forEach(function(a){n.push(a)});return n};e.prototype._renderBackground=function(b,a,f,d,c,g,e){this._backgroundRenderer.render(b,a,f,d,c,g,this._SpriteMosaic,this._SpriteMosaic.pixelRatio,e)};e.prototype._renderLine=function(b,a,f,d,c,g,e){this._lineRenderer.render(b,
a,f,d,this._state,c,g,this._SpriteMosaic,this._extrudeMatrix,this._SpriteMosaic.pixelRatio,e)};e.prototype._renderFill=function(b,a,f,d,c,g,e){this._fillRenderer.render(b,a,f,this._state.rotation,d,c,g,this._SpriteMosaic,this._extrudeMatrix,this._SpriteMosaic.pixelRatio,e)};e.prototype._renderCircle=function(b,a,f,d,c,e,h,k){var g=!0;c===e.key.level&&(g=!1);b.setStencilTestEnabled(g);this._circleRenderer.render(b,a,f,d,this._state.rotation,e,h,this._extrudeMatrix,k)};e.prototype._renderSymbol=function(b,
a,f,d,c,e,h,k){var g=!0;c===e.key.level&&(g=!1);b.setStencilTestEnabled(g);this._symbolRenderer.render(b,a,f,d,this._state.rotation,this._fadeRecorder.getFadeValues(this._ignoreSpeed),e,h,this._SpriteMosaic,this._glyphMosaic,this._extrudeMatrix,this._extrudeNoRotationMatrix,this._SpriteMosaic.pixelRatio,k)};return e}()});