// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../geometry ../../../../Graphic ../../../../core/Accessor ../../../../core/Handles ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ../../../../geometry/geometryEngine ../../../../geometry/support/boundsUtils ../../../../geometry/support/coordsUtils ../../../../symbols/SimpleFillSymbol ../../../../symbols/SimpleLineSymbol ../../../../symbols/SimpleMarkerSymbol ./drawUtils ./GraphicMover".split(" "),
function(J,K,v,e,g,k,w,x,l,f,p,q,t,u,y,r,m,z){var A=function(){return function(d,c,a,b){this.graphic=d;this.targetGraphic=c;this.dx=a;this.dy=b;this.type="move-start"}}(),B=function(){return function(d,c,a,b){this.graphic=d;this.targetGraphic=c;this.dx=a;this.dy=b;this.type="move"}}(),C=function(){return function(d,c,a,b){this.graphic=d;this.targetGraphic=c;this.dx=a;this.dy=b;this.type="move-stop"}}(),D=function(){return function(d,c,a){this.graphic=d;this.targetGraphic=c;this.angle=a;this.type=
"rotate-start"}}(),E=function(){return function(d,c,a){this.graphic=d;this.targetGraphic=c;this.angle=a;this.type="rotate"}}(),F=function(){return function(d,c,a){this.graphic=d;this.targetGraphic=c;this.angle=a;this.type="rotate-stop"}}(),G=function(){return function(d,c,a,b){this.graphic=d;this.targetGraphic=c;this.xScale=a;this.yScale=b;this.type="scale-start"}}(),H=function(){return function(d,c,a,b){this.graphic=d;this.targetGraphic=c;this.xScale=a;this.yScale=b;this.type="scale"}}(),I=function(){return function(d,
c,a,b){this.graphic=d;this.targetGraphic=c;this.xScale=a;this.yScale=b;this.type="scale-stop"}}();return function(d){function c(a){a=d.call(this,a)||this;a._centerGraphicSymbol=new r({type:"simple-marker",style:"circle",size:4,color:[255,255,255,1],outline:{color:[0,12,207],width:1}});a._defaultFillSymbol=new u({type:"simple-fill",color:[12,207,255,.075],outline:{join:"round",color:[0,12,207],width:2}});a._dashedFillSymbol=new u({type:"simple-fill",color:[0,0,0,0],outline:{style:"dash",color:[150,
150,150,.5],width:2}});a._defaultGraphicSymbol=new r({type:"simple-marker",style:"square",size:8,color:[255,255,255,1],outline:{color:[0,12,207],width:1}});a._handles=new x;a._initialGeometry=null;a._initialBoxGeometry=null;a._initialRotateGeometry=null;a._mover=null;a._activeHandleGraphic=null;a._rotateGraphicOffset=20;a._rotateGraphicHoverSymbol=new r({type:"simple-marker",style:"circle",size:10,color:[255,255,255,1],outline:{color:[0,12,207],width:1}});a._rotateGraphicSymbol=new r({type:"simple-marker",
style:"circle",size:8,color:[255,255,255,1],outline:{color:[0,12,207],width:1}});a._rotationAngle=0;a._rotateLineGraphic=null;a._rotateLineGraphicSymbol=new y({color:[0,12,207],width:2});a._startBox=null;a._totalDx=0;a._totalDy=0;a._xScale=1;a._yScale=1;a.callbacks={onMoveStart:function(a){},onMove:function(a){},onMoveStop:function(a){},onScaleStart:function(a){},onScale:function(a){},onScaleStop:function(a){},onRotateStart:function(a){},onRotate:function(a){},onRotateStop:function(a){}};a.centerGraphic=
null;a.backgroundGraphic=null;a.enableMovement=!0;a.enableRotation=!0;a.enableScaling=!0;a.graphic=null;a.handleGraphics=[];a.layer=null;a.rotateGraphic=null;a.showCenterGraphic=!0;a.uniformScaling=!1;a.view=null;return a}v(c,d);c.prototype.initialize=function(){var a=this;this.graphic&&this.layer&&(this._setUpGraphics(),this._setUpMover(),this._updateGraphics());this._handles.add([l.whenOnce(this,"view.ready",function(){a.view&&a.view.map&&a.view.map.add(a.layer)}),l.pausable(this,"uniformScaling",
function(){a._activeHandleGraphic&&(a._scaleGraphic(a._activeHandleGraphic),a._updateGraphics())}),l.pausable(this,"view.scale",function(){a._updateRotateGraphic();a._updateRotateLineGraphic()}),l.pausable(this,"graphic",function(){a.refresh()}),l.pausable(this,"layer",function(b,c){c&&a._cleanUpGraphics(c);a.refresh()})])};c.prototype.destroy=function(){this._reset();this._handles.removeAll();this._handles=null};Object.defineProperty(c.prototype,"graphics",{get:function(){var a=[];this.handleGraphics.length&&
(a=a.concat(this.handleGraphics));this.graphic&&a.push(this.graphic);this.backgroundGraphic&&a.push(this.backgroundGraphic);this.centerGraphic&&a.push(this.centerGraphic);this.rotateGraphic&&a.push(this.rotateGraphic);this._rotateLineGraphic&&a.push(this._rotateLineGraphic);return a},enumerable:!0,configurable:!0});c.prototype.move=function(a,b){this._mover&&this.graphic&&(a=m.move(this.graphic.geometry,a,b,this.view),this.graphic.geometry=a,this.refresh())};c.prototype.scale=function(a,b){this._mover&&
this.graphic&&(a=m.scale(this.graphic.geometry,a,b,this.view),this.graphic.geometry=a,this.refresh())};c.prototype.rotate=function(a,b){this._mover&&this.graphic&&(b||(b=new g.Point(this.handleGraphics[1].geometry.x,this.handleGraphics[3].geometry.y,this.view.spatialReference)),a=p.rotate(this.graphic.geometry,a,b),this.graphic.geometry=a,this.refresh())};c.prototype.refresh=function(){this._reset();this.graphic&&this.layer&&(this._setUpGraphics(),this._setUpMover(),this._updateGraphics())};c.prototype._reset=
function(){this._resetGraphicStateVars();this._cleanUpGraphics();this._mover&&this._mover.destroy();this._mover=null;this.view.container.style.cursor="default"};c.prototype._resetGraphicStateVars=function(){this._initialRotateGeometry=this._initialBoxGeometry=this._initialGeometry=this._activeHandleGraphic=this._startBox=null;this._totalDy=this._totalDx=0;this._yScale=this._xScale=1;this._rotationAngle=0};c.prototype._cleanUpGraphics=function(a){(a=a||this.layer)&&a.removeMany(this.handleGraphics);
a&&a.remove(this.backgroundGraphic);a&&a.remove(this.centerGraphic);a&&a.remove(this.rotateGraphic);a&&a.remove(this._rotateLineGraphic);this.handleGraphics.forEach(function(a){return a.destroy()});this._set("handleGraphics",[]);this.backgroundGraphic&&(this.backgroundGraphic.destroy(),this._set("backgroundGraphic",null));this.centerGraphic&&(this.centerGraphic.destroy(),this._set("centerGraphic",null));this.rotateGraphic&&(this.rotateGraphic.destroy(),this._set("rotateGraphic",null));this._rotateLineGraphic&&
(this._rotateLineGraphic.destroy(),this._rotateLineGraphic=null)};c.prototype._setUpMover=function(){var a=this,b=this.handleGraphics;this.enableMovement&&(b=b.concat(this.graphic,this.backgroundGraphic));this.enableRotation&&(b=b.concat(this.rotateGraphic));this.showCenterGraphic&&b.push(this.centerGraphic);this._mover=new z({view:this.view,graphics:b,callbacks:{onGraphicMoveStart:function(b){return a._onGraphicMoveStartCallback(b)},onGraphicMove:function(b){return a._onGraphicMoveCallback(b)},onGraphicMoveStop:function(b){return a._onGraphicMoveStopCallback(b)},
onGraphicPointerOver:function(b){return a._onGraphicPointerOverCallback(b)},onGraphicPointerOut:function(b){return a._onGraphicPointerOutCallback(b)}}})};c.prototype._onGraphicMoveStartCallback=function(a){var b=a.graphic,c=this.graphic.geometry,d=this.backgroundGraphic.geometry;this._resetGraphicStateVars();this.rotateGraphic.visible=!1;this._rotateLineGraphic.visible=!1;this.handleGraphics.forEach(function(a){a.visible=!1});var h=b.geometry,n=q.getRingsOrPathsBounds(d.rings),f=n[0],e=n[1],g=n[2],
n=n[3],m=a.dx;a=a.dy;this._startBox={width:Math.abs(g-f),height:Math.abs(n-e),centerX:(g+f)/2,centerY:(n+e)/2,startX:h.x,startY:h.y};this._initialGeometry=c;this._initialBoxGeometry=d;this._initialRotateGeometry=this.rotateGraphic.geometry;b===this.rotateGraphic?(this.backgroundGraphic.symbol=this._dashedFillSymbol,this.rotateGraphic.symbol=this._rotateGraphicHoverSymbol,this.callbacks.onRotateStart(new D(this.graphic,b,0))):-1<this.handleGraphics.indexOf(b)?(this._activeHandleGraphic=b,this.callbacks.onScaleStart(new G(this.graphic,
b,1,1))):(this.centerGraphic.visible=!1,this.callbacks.onMoveStart(new A(this.graphic,b,m,a)))};c.prototype._onGraphicMoveCallback=function(a){var b=a.graphic;if(-1<this.handleGraphics.indexOf(b))this._scaleGraphic(b),this._updateBackgroundGraphic(),this._updateCenterGraphic(),this.callbacks.onScale(new H(this.graphic,b,this._xScale,this._yScale));else if(b===this.rotateGraphic){a=new g.Point(this._startBox.startX,this._startBox.startY,this.view.spatialReference);var c=new g.Point(this._startBox.centerX,
this._startBox.centerY,this.view.spatialReference);a=this._getAngle(c,a,b.geometry);var d=p.rotate(this._initialGeometry,a,c),h=p.rotate(this._initialBoxGeometry,a,c),c=p.rotate(this._initialRotateGeometry,a,c);this.graphic.geometry=d;this.backgroundGraphic.geometry=h;this.rotateGraphic.geometry=c;this._rotationAngle=a;this.callbacks.onRotate(new E(this.graphic,b,a))}else{c=a.dx;a=a.dy;this._totalDx+=c;this._totalDy+=a;if(b===this.graphic||b===this.centerGraphic)this.backgroundGraphic.geometry=m.move(this.backgroundGraphic.geometry,
c,a,this.view);if(b===this.backgroundGraphic||b===this.centerGraphic)this.graphic.geometry=m.move(this.graphic.geometry,c,a,this.view);this.callbacks.onMove(new B(this.graphic,b,c,a))}};c.prototype._onGraphicMoveStopCallback=function(a){a=a.graphic;this._updateGraphics();this.enableRotation&&(this._rotateLineGraphic.visible=!0,this.rotateGraphic.visible=!0);this.showCenterGraphic&&(this.centerGraphic.visible=!0);this.enableScaling&&this.handleGraphics.forEach(function(a){a.visible=!0});if(a===this.rotateGraphic)this.rotateGraphic.symbol=
this._rotateGraphicSymbol,this.backgroundGraphic.symbol=this._defaultFillSymbol,this.callbacks.onRotateStop(new F(this.graphic,a,this._rotationAngle));else if(-1<this.handleGraphics.indexOf(a))this.callbacks.onScaleStop(new I(this.graphic,a,this._xScale,this._yScale));else this.callbacks.onMoveStop(new C(this.graphic,a,this._totalDx,this._totalDy));this._resetGraphicStateVars()};c.prototype._onGraphicPointerOverCallback=function(a){var b=this.view.rotation,c=a.index;a.graphic===this.rotateGraphic&&
(this.rotateGraphic.symbol=this._rotateGraphicHoverSymbol);8>c&&(c=0<=b&&45>b?c%8:45<=b&&90>b?(c+1)%8:90<=b&&135>b?(c+2)%8:135<=b&&180>b?(c+3)%8:180<=b&&225>b?(c+4)%8:225<=b&&270>b?(c+5)%8:270<=b&&315>b?(c+6)%8:(c+7)%8);switch(c){case 0:a="nwse-resize";break;case 1:a="ns-resize";break;case 2:a="nesw-resize";break;case 3:a="ew-resize";break;case 4:a="nwse-resize";break;case 5:a="ns-resize";break;case 6:a="nesw-resize";break;case 7:a="ew-resize";break;default:a="pointer"}this.view.container.style.cursor=
a};c.prototype._onGraphicPointerOutCallback=function(a){a.graphic===this.rotateGraphic&&(this.rotateGraphic.symbol=this._rotateGraphicSymbol);"default"!==this.view.container.style.cursor&&(this.view.container.style.cursor="default")};c.prototype._getBoxCoordinates=function(a){var b=new g.Point(a.xmin,a.ymax,this.view.spatialReference);a=new g.Point(a.xmax,a.ymin,this.view.spatialReference);var c=(b.x+a.x)/2,d=(b.y+a.y)/2;return[[b.x,b.y],[c,b.y],[a.x,b.y],[a.x,d],[a.x,a.y],[c,a.y],[b.x,a.y],[b.x,
d]]};c.prototype._scaleGraphic=function(a){var b=this.handleGraphics.indexOf(a),c=this._startBox,d=c.centerX,h=c.centerY,f=c.startX,c=c.startY;1!==b&&5!==b||this._updateX(a,d);3!==b&&7!==b||this._updateY(a,h);a=a.geometry;var e=this.view.toScreen(a),g=e.x,e=e.y;if(this.uniformScaling)h=this.view.toScreen(d,h),d=h.x,h=h.y,f=this.view.toScreen(f,c),this._xScale=this._yScale=this._getScaleRatio(d,h,g,e,f.x,f.y),this.graphic.geometry=m.scale(this._initialGeometry,this._xScale,this._yScale,this.view);
else{var e=this._startBox,g=e.width,e=e.height,k=a.x-f,l=c-a.y;if(1===b||5===b)k=0;else if(3===b||7===b)l=0;if(0!==k||0!==l){a=d+k/2;var p=h+l/2;this._xScale=(g+(f>d?k:-1*k))/g||1;this._yScale=(e+(c<h?l:-1*l))/e||1;if(1===b||5===b)this._xScale=1;else if(3===b||7===b)this._yScale=1;f=m.scale(this._initialGeometry,this._xScale,this._yScale,this.view);this.graphic.geometry=m.move(f,(a-d)/this.view.state.resolution,(p-h)/this.view.state.resolution,this.view,!0)}}};c.prototype._setUpGraphics=function(){this._set("centerGraphic",
new k(null,this._centerGraphicSymbol));this.showCenterGraphic&&this.layer.add(this.centerGraphic);this._set("backgroundGraphic",new k(null,this._defaultFillSymbol));this.layer.add(this.backgroundGraphic);this._rotateLineGraphic=new k(null,this._rotateLineGraphicSymbol);this.enableRotation&&this.layer.add(this._rotateLineGraphic);this._set("rotateGraphic",new k(null,this._rotateGraphicSymbol));this.enableRotation&&this.layer.add(this.rotateGraphic);for(var a=0;8>a;a++)this.handleGraphics.push(new k(null,
this._defaultGraphicSymbol));this.enableScaling&&this.layer.addMany(this.handleGraphics)};c.prototype._updateGraphics=function(){this._updateBackgroundGraphic();this._updateHandleGraphics();this._updateCenterGraphic();this._updateRotateGraphic();this._updateRotateLineGraphic()};c.prototype._updateHandleGraphics=function(){var a=this;if(this.graphic&&this.graphic.geometry){var b=t.geometryToCoordinates(this.graphic.geometry),b=q.getRingsOrPathsBounds(b),c=this._getBoxCoordinates({xmin:b[0],ymin:b[1],
xmax:b[2],ymax:b[3]});this.handleGraphics.forEach(function(b,d){d=c[d];a._updateXY(b,d[0],d[1])})}};c.prototype._updateBackgroundGraphic=function(){if(this.graphic&&this.graphic.geometry){var a=t.geometryToCoordinates(this.graphic.geometry),a=q.getRingsOrPathsBounds(a),a=this._getBoxCoordinates({xmin:a[0],ymin:a[1],xmax:a[2],ymax:a[3]});this.backgroundGraphic.geometry=new g.Polygon({rings:a,spatialReference:this.view.spatialReference})}};c.prototype._updateCenterGraphic=function(){if(this.graphic&&
this.graphic.geometry){var a=t.geometryToCoordinates(this.graphic.geometry),a=q.getRingsOrPathsBounds(a);this.centerGraphic.geometry=new g.Point((a[2]+a[0])/2,(a[3]+a[1])/2,this.view.spatialReference)}};c.prototype._updateRotateGraphic=function(){if(this.handleGraphics.length){var a=this.handleGraphics[1].geometry;this.rotateGraphic.geometry=new g.Point(a.x,a.y+this.view.state.resolution*this._rotateGraphicOffset,this.view.spatialReference)}};c.prototype._updateRotateLineGraphic=function(){if(this.handleGraphics.length&&
this.rotateGraphic&&this.rotateGraphic.geometry){var a=this.handleGraphics[1].geometry,b=this.rotateGraphic.geometry;this._rotateLineGraphic.geometry=new g.Polyline({paths:[[a.x,a.y],[b.x,b.y]],spatialReference:this.view.spatialReference})}};c.prototype._updateXY=function(a,b,c){a.geometry=new g.Point(b,c,this.view.spatialReference)};c.prototype._updateX=function(a,b){a.geometry=new g.Point(b,a.geometry.y,this.view.spatialReference)};c.prototype._updateY=function(a,b){a.geometry=new g.Point(a.geometry.x,
b,this.view.spatialReference)};c.prototype._getScaleRatio=function(a,b,c,d,e,f){return Math.sqrt((c-a)*(c-a)+(d-b)*(d-b))/Math.sqrt((e-a)*(e-a)+(f-b)*(f-b))};c.prototype._getAngle=function(a,b,c){return 180*Math.atan2(a.y-c.y,a.x-c.x)/Math.PI-180*Math.atan2(a.y-b.y,a.x-b.x)/Math.PI};e([f.property()],c.prototype,"_rotateLineGraphic",void 0);e([f.property()],c.prototype,"callbacks",void 0);e([f.property({readOnly:!0})],c.prototype,"centerGraphic",void 0);e([f.property({readOnly:!0})],c.prototype,"backgroundGraphic",
void 0);e([f.property()],c.prototype,"enableMovement",void 0);e([f.property()],c.prototype,"enableRotation",void 0);e([f.property()],c.prototype,"enableScaling",void 0);e([f.property()],c.prototype,"graphic",void 0);e([f.property({dependsOn:"graphic backgroundGraphic centerGraphic handleGraphics rotateGraphic _rotateLineGraphic".split(" "),readOnly:!0})],c.prototype,"graphics",null);e([f.property({readOnly:!0})],c.prototype,"handleGraphics",void 0);e([f.property()],c.prototype,"layer",void 0);e([f.property({readOnly:!0})],
c.prototype,"rotateGraphic",void 0);e([f.property()],c.prototype,"showCenterGraphic",void 0);e([f.property()],c.prototype,"uniformScaling",void 0);e([f.property()],c.prototype,"view",void 0);return c=e([f.subclass("esri.views.2d.draw.support.Box")],c)}(f.declared(w))});