// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../geometry ../../../../core/Accessor ../../../../core/Evented ../../../../core/Handles ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ./drawUtils ./input/GraphicMoverEvents".split(" "),function(u,v,m,g,n,p,q,k,r,f,t,h){return function(l){function c(a){a=l.call(this,a)||this;a._activeGraphic=null;a._dragEvent=null;a._handles=new k;a._hoverGraphic=null;
a._initialDragGeometry=null;a._pointerDownEvent=null;a._viewHandles=new k;a.callbacks={onGraphicClick:function(a){},onGraphicDoubleClick:function(a){},onGraphicMoveStart:function(a){},onGraphicMove:function(a){},onGraphicMoveStop:function(a){},onGraphicPointerOver:function(a){},onGraphicPointerOut:function(a){}};a.graphics=[];a.view=null;return a}m(c,l);c.prototype.initialize=function(){var a=this;this._handles.add([r.whenOnce(this,"view.ready",function(){a._viewHandles.add([a.view.on("click",function(b){return a._clickHandler(b)}),
a.view.on("double-click",function(b){return a._doubleClickHandler(b)}),a.view.on("pointer-down",function(b){return a._pointerDownHandler(b)}),a.view.on("pointer-move",function(b){return a._pointerMoveHandler(b)}),a.view.on("pointer-up",function(b){return a._pointerUpHandler(b)}),a.view.on("drag",function(b){return a._dragHandler(b)}),a.view.on("key-down",function(b){return a._keyDownHandler(b)})])})])};c.prototype.destroy=function(){this.reset();this._viewHandles.removeAll();this._handles.removeAll()};
Object.defineProperty(c.prototype,"state",{get:function(){var a=!!this.get("view.ready"),b=!!this.get("graphics.length"),e=this._activeGraphic;return a&&b?e?"moving":"active":a?"ready":"disabled"},enumerable:!0,configurable:!0});c.prototype.reset=function(){this._dragEvent=this._hoverGraphic=this._activeGraphic=null};c.prototype.updateGeometry=function(a,b){(a=this.graphics[a])&&a.set("geometry",b)};c.prototype._clickHandler=function(a){var b=this;this.view.hitTest(a).then(function(e){var d=e.results;
d.length&&d[0].graphic&&(d=d[0].graphic,-1<b.graphics.indexOf(d)&&(e=new h.GraphicClickEvent(d,b.graphics.indexOf(d),e.screenPoint,a),b.emit("graphic-click",e),b.callbacks.onGraphicClick&&b.callbacks.onGraphicClick(e)))})};c.prototype._doubleClickHandler=function(a){var b=this;this.view.hitTest(a).then(function(e){var d=e.results;d.length&&d[0].graphic&&(d=d[0].graphic,-1<b.graphics.indexOf(d)&&(e=new h.GraphicDoubleClickEvent(d,b.graphics.indexOf(d),e.screenPoint,a),b.emit("graphic-double-click",
e),b.callbacks.onGraphicDoubleClick&&b.callbacks.onGraphicDoubleClick(e)))})};c.prototype._pointerDownHandler=function(a){var b=this;this._pointerDownEvent=a;this.view.hitTest(a).then(function(a){a=a.results;a.length&&a[0].graphic?(a=a[0].graphic,-1<b.graphics.indexOf(a)?b._activeGraphic=a:a!==b._activeGraphic&&(b._pointerDownEvent=null,b._activeGraphic=null)):(b._pointerDownEvent=null,b._activeGraphic=null)})};c.prototype._pointerUpHandler=function(a){this._pointerDownEvent=null;this._dragEvent||
(this._activeGraphic=null)};c.prototype._pointerMoveHandler=function(a){var b=this;this._dragEvent||this.view.hitTest(a).then(function(e){var d=e.results;if(d.length&&d[0].graphic){d=d[0].graphic;if(d===b._hoverGraphic)return;if(-1<b.graphics.indexOf(d)){if(b._hoverGraphic){var c=b.graphics.indexOf(b._hoverGraphic),c=new h.GraphicPointerOutEvent(b.graphics[c],c,e.screenPoint,a);b._hoverGraphic=null;b.emit("graphic-pointer-out",c);b.callbacks.onGraphicPointerOut&&b.callbacks.onGraphicPointerOut(c)}c=
b.graphics.indexOf(d);e=new h.GraphicPointerOverEvent(d,c,e.screenPoint,a);b._hoverGraphic=d;b.emit("graphic-pointer-over",e);b.callbacks.onGraphicPointerOver&&b.callbacks.onGraphicPointerOver(e);return}}b._hoverGraphic&&(c=b.graphics.indexOf(b._hoverGraphic),e=new h.GraphicPointerOutEvent(b.graphics[c],c,e.screenPoint,a),b._hoverGraphic=null,b.emit("graphic-pointer-out",e),b.callbacks.onGraphicPointerOut&&b.callbacks.onGraphicPointerOut(e))})};c.prototype._dragHandler=function(a){if(this._pointerDownEvent&&
this._activeGraphic){a.stopPropagation();var b=this.graphics.indexOf(this._activeGraphic),c=this._activeGraphic.geometry,d=this._dragEvent?a.x-this._dragEvent.x:0,f=this._dragEvent?a.y-this._dragEvent.y:0,g=new n.ScreenPoint(a.x,a.y),k=c.clone();this._activeGraphic.set("geometry",t.move(k,d,f,this.view));this._dragEvent=a;"start"===a.action?(this._initialDragGeometry=c.clone(),a=new h.GraphicMoveStartEvent(this._activeGraphic,b,d,f,g,a),this.emit("graphic-move-start",a),this.callbacks.onGraphicMoveStart&&
this.callbacks.onGraphicMoveStart(a),a.defaultPrevented&&this._activeGraphic.set("geometry",c)):"update"===a.action?(a=new h.GraphicMoveEvent(this._activeGraphic,b,d,f,g,a),this.emit("graphic-move",a),this.callbacks.onGraphicMove&&this.callbacks.onGraphicMove(a),a.defaultPrevented&&this._activeGraphic.set("geometry",c)):(this._dragEvent=this._activeGraphic=null,a=new h.GraphicMoveStopEvent(this.graphics[b],b,d,f,g,a),this.emit("graphic-move-stop",a),this.callbacks.onGraphicMoveStop&&this.callbacks.onGraphicMoveStop(a),
a.defaultPrevented&&this.graphics[b].set("geometry",this._initialDragGeometry),this._initialDragGeometry=null)}};c.prototype._keyDownHandler=function(a){"a"!==a.key&&"d"!==a.key&&"n"!==a.key||"moving"!==this.state||a.stopPropagation()};g([f.property()],c.prototype,"_activeGraphic",void 0);g([f.property()],c.prototype,"callbacks",void 0);g([f.property()],c.prototype,"graphics",void 0);g([f.property({dependsOn:["view.ready","graphics.length","_activeGraphic"],readOnly:!0})],c.prototype,"state",null);
g([f.property()],c.prototype,"view",void 0);return c=g([f.subclass("esri.views.2d.draw.support.GraphicMover")],c)}(f.declared(p,q))});