// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/tsSupport/declareExtendsHelper ../../../../core/tsSupport/decorateHelper ../../../../geometry ../../../../Graphic ../../../../core/Accessor ../../../../core/Handles ../../../../core/watchUtils ../../../../core/accessorSupport/decorators ../../../../geometry/support/coordsUtils ../../../../symbols/SimpleMarkerSymbol ./drawUtils ./GraphicMover".split(" "),function(L,M,y,h,q,p,z,w,r,l,v,u,A,B){var C=function(){return function(d,b){this.graphic=d;this.targetGraphic=
b;this.type="reshape-start"}}(),D=function(){return function(d,b){this.graphic=d;this.targetGraphic=b;this.type="reshape"}}(),E=function(){return function(d,b){this.graphic=d;this.targetGraphic=b;this.type="reshape-stop"}}(),F=function(){return function(d,b,a){this.graphic=d;this.dx=b;this.dy=a;this.type="move-start"}}(),G=function(){return function(d,b,a){this.graphic=d;this.dx=b;this.dy=a;this.type="move"}}(),H=function(){return function(d,b,a){this.graphic=d;this.dx=b;this.dy=a;this.type="move-stop"}}(),
I=function(){return function(d){this.graphics=d;this.type="select"}}(),x=function(){return function(d){this.graphics=d;this.type="deselect"}}(),J=function(){return function(d,b,a){this.added=d;this.graphic=b;this.oldGraphic=a;this.type="vertex-add"}}(),K=function(){return function(d,b,a){this.removed=d;this.graphic=b;this.oldGraphic=a;this.type="vertex-remove"}}();return function(d){function b(a){a=d.call(this,a)||this;a._handles=new w;a._mover=null;a._viewHandles=new w;a.callbacks={onReshapeStart:function(a){},
onReshape:function(a){},onReshapeStop:function(a){},onMoveStart:function(a){},onMove:function(a){},onMoveStop:function(a){}};a.graphic=null;a.handleGraphics=[];a.handleHoverSymbol=new u({type:"simple-marker",style:"circle",size:8,color:[33,205,255],outline:{color:[0,12,255],width:1}});a.handleSelectionSymbol=new u({type:"simple-marker",style:"circle",size:8,color:[255,255,255],outline:{color:[0,12,255],width:1}});a.handleSymbol=new u({type:"simple-marker",style:"circle",size:6,color:[33,205,255],
outline:{color:[0,12,255],width:1}});a.layer=null;a.midpointGraphics=[];a.midpointSymbol=new u({type:"simple-marker",style:"circle",size:6,color:[200,200,200],outline:{color:[100,100,100],width:1}});a.midpointsEnabled=!0;a.selectedGraphics=[];a.view=null;return a}y(b,d);b.prototype.initialize=function(){var a=this;this.graphic&&this.layer&&(this._setUpGraphics(),this._setUpMover());this._handles.add([r.whenOnce(this,"view.ready",function(){a.view&&a.view.map&&a.view.map.add(a.layer);a._viewHandles.add([a.view.on("key-down",
function(c){return a._keyDownHandler(c)})])}),r.pausable(this,"graphic",function(){a.refresh()}),r.pausable(this,"layer",function(c,n){n&&(a._clearSelection(),a._resetGraphics(n));a.refresh()}),r.pausable(this,"midpointsEnabled",function(){a.refresh()})])};b.prototype.destroy=function(){this._reset();this._mover&&this._mover.destroy();this._mover=null;this._handles.removeAll();this._handles=null;this._viewHandles.removeAll();this._viewHandles=null};Object.defineProperty(b.prototype,"graphics",{get:function(){return[].concat(this.graphic,
this.handleGraphics,this.midpointGraphics)},enumerable:!0,configurable:!0});b.prototype.refresh=function(){this._reset();this.graphic&&this.layer&&(this._setUpGraphics(),this._setUpMover())};b.prototype.clearSelection=function(){this._clearSelection()};b.prototype._reset=function(){this._clearSelection();this._resetGraphics();this._mover&&this._mover.destroy();this._mover=null;this.view.container.style.cursor="default"};b.prototype._resetGraphics=function(a){(a=a||this.layer)&&a.removeMany(this.handleGraphics);
a&&a.removeMany(this.midpointGraphics);this.handleGraphics.forEach(function(a){return a.destroy()});this.midpointGraphics.forEach(function(a){return a.destroy()});this._set("handleGraphics",[]);this._set("midpointGraphics",[]);this._set("selectedGraphics",[])};b.prototype._setUpGraphics=function(){var a=this.graphic.geometry,c=v.geometryToCoordinates(a.clone());if("polygon"===a.type)for(a=0;a<c.length;a++){var n=c[a],b=n[n.length-1];n[0][0]===b[0]&&n[0][1]===b[1]&&2<n.length&&n.pop()}this._set("handleGraphics",
this._createHandleGraphics(c));this.midpointsEnabled&&this._set("midpointGraphics",this._createMidpointGraphics(c));this._saveRelatedIndices(this.handleGraphics);this.layer.addMany(this.midpointGraphics);this.layer.addMany(this.handleGraphics)};b.prototype._createHandleGraphics=function(a){for(var c=[],b=0;b<a.length;b++)for(var m=a[b],f=a.indexOf(m),g=0,e=m;g<e.length;g++){var k=e[g],t=m.indexOf(k);c.push(new p({geometry:new q.Point({x:k[0],y:k[1],spatialReference:this.view.spatialReference}),symbol:this.handleSymbol,
attributes:{pathIndex:f,pointIndex:t}}))}return c};b.prototype._createMidpointGraphics=function(a){for(var c=[],b=0;b<a.length;b++)for(var m=a[b],f=a.indexOf(m),g=0,e=m;g<e.length;g++){var k=e[g],t=m.indexOf(k),d=k[0],l=k[1],k=m[t+1]?t+1:0;if("polyline"!==this.graphic.geometry.type||0!==k){var h=m[k],d=v.getMidpoint([d,l],[h[0],h[1]]);c.push(new p({geometry:new q.Point({x:d[0],y:d[1],spatialReference:this.view.spatialReference}),symbol:this.midpointSymbol,attributes:{pathIndex:f,pointIndexStart:t,
pointIndexEnd:k}}))}}return c};b.prototype._saveRelatedIndices=function(a){for(var c=0;c<a.length;c++){for(var b=a[c],m=a.indexOf(b),f=[],g=b.geometry,e=g.x,g=g.y,k=0,d=a;k<d.length;k++){var h=d[k],l=a.indexOf(h);if(m!==l){var h=h.geometry,p=h.y;e===h.x&&g===p&&f.push(l)}}b.attributes.relatedGraphicIndices=f}};b.prototype._setUpMover=function(){var a=this;this._mover=new B({graphics:[].concat(this.handleGraphics,this.graphic,this.midpointGraphics),view:this.view,callbacks:{onGraphicClick:function(c){return a._onGraphicClickCallback(c)},
onGraphicMoveStart:function(c){return a._onGraphicMoveStartCallback(c)},onGraphicMove:function(c){return a._onGraphicMoveCallback(c)},onGraphicMoveStop:function(c){return a._onGraphicMoveStopCallback(c)},onGraphicPointerOver:function(c){return a._onGraphicPointerOverCallback(c)},onGraphicPointerOut:function(c){return a._onGraphicPointerOutCallback(c)}}})};b.prototype._onGraphicClickCallback=function(a){var c=a.graphic;c===this.graphic?this.clearSelection():-1<this.midpointGraphics.indexOf(c)?(a.viewEvent.stopPropagation(),
2!==a.viewEvent.button&&(a=this.graphic.clone(),this._createHandleFromMidpoint(c),this.refresh(),this.callbacks.onVertexAdd&&this.callbacks.onVertexAdd(new J([c],this.graphic,a)))):-1<this.handleGraphics.indexOf(c)&&(a.viewEvent.stopPropagation(),2===a.viewEvent.button?this._removeVertex(c):(a.viewEvent.native.ctrlKey||this._clearSelection(),-1===this.selectedGraphics.indexOf(c)?this._addToSelection(c):this._removeFromSelection(c,!0)))};b.prototype._onGraphicMoveStartCallback=function(a){var c=a.graphic;
c===this.graphic?(c=a.dx,a=a.dy,this._clearSelection(),this.callbacks.onMoveStart&&this.callbacks.onMoveStart(new F(this.graphic,c,a))):(-1<this.midpointGraphics.indexOf(c)?(this._clearSelection(),this._createHandleFromMidpoint(c),this._addToSelection(c)):-1===this.selectedGraphics.indexOf(c)&&(this._clearSelection(),this._addToSelection(c)),this.callbacks.onReshapeStart&&this.callbacks.onReshapeStart(new C(this.graphic,c)))};b.prototype._onGraphicMoveCallback=function(a){var c=a.graphic,b=a.dx;a=
a.dy;c===this.graphic?(this._syncGraphicsWithGeometry(),this.callbacks.onMove&&this.callbacks.onMove(new G(this.graphic,b,a))):(this._syncGeometryAfterHandleMove(c,b,a),this.callbacks.onReshape&&this.callbacks.onReshape(new D(this.graphic,c)))};b.prototype._onGraphicMoveStopCallback=function(a){var c=a.graphic,b=a.dx;a=a.dy;c===this.graphic?(this._syncGraphicsWithGeometry(),this.callbacks.onMoveStop&&this.callbacks.onMoveStop(new H(this.graphic,b,a))):(this._syncGeometryAfterHandleMove(c,b,a),-1<
this.midpointGraphics.indexOf(c)&&this.refresh(),this.callbacks.onReshapeStop&&this.callbacks.onReshapeStop(new E(this.graphic,c)))};b.prototype._syncGraphicsWithGeometry=function(){var a=this.graphic.geometry,a="polyline"===a.type?a.paths:a.rings;this._updateHandleGraphicLocations(a);this._updateMidpointGraphicLocations(a)};b.prototype._updateHandleGraphicLocations=function(a){for(var c=0,b=this.handleGraphics;c<b.length;c++){var m=b[c],f=m.attributes,f=a[f.pathIndex][f.pointIndex];m.set("geometry",
new q.Point(f[0],f[1],this.view.spatialReference))}};b.prototype._updateMidpointGraphicLocations=function(a){for(var c=0,b=this.midpointGraphics;c<b.length;c++){var m=b[c],f=m.attributes,g=f.pathIndex,e=a[g][f.pointIndexStart],f=a[g][f.pointIndexEnd],e=v.getMidpoint([e[0],e[1]],[f[0],f[1]]);m.geometry=new q.Point({x:e[0],y:e[1],spatialReference:this.view.spatialReference})}};b.prototype._syncGeometryAfterHandleMove=function(a,c,b){var n=this.graphic.geometry.clone(),f="polyline"===n.type?n.paths:
n.rings,g=a.attributes,e=g.pathIndex,k=g.pointIndex,d=a.geometry,g=d.x,d=d.y;f[e][k]=[g,d];"polygon"===n.type&&0===k&&(f[e][f[e].length-1]=[g,d]);if(-1<this.handleGraphics.indexOf(a)){for(var k=0,h=a.attributes.relatedGraphicIndices;k<h.length;k++){var e=h[k],e=this.handleGraphics[e],l=e.attributes;f[l.pathIndex][l.pointIndex]=[g,d];e.geometry=a.geometry}g=0;for(d=this.selectedGraphics;g<d.length;g++)if(e=d[g],e!==a){var k=e.attributes,h=k.pathIndex,l=k.pointIndex,p=k.relatedGraphicIndices,k=A.move(e.geometry,
c,b,this.view);f[h][l]=[k.x,k.y];e.geometry=k;h=0;for(l=p;h<l.length;h++)e=l[h],e=this.handleGraphics[e],p=e.attributes,f[p.pathIndex][p.pointIndex]=[k.x,k.y],e.geometry=k}this._updateMidpointGraphicLocations(f)}this.graphic.geometry=n};b.prototype._onGraphicPointerOverCallback=function(a){a=a.graphic;-1<this.handleGraphics.indexOf(a)&&-1===this.selectedGraphics.indexOf(a)&&(a.symbol=this.handleHoverSymbol);"pointer"!==this.view.container.style.cursor&&(this.view.container.style.cursor="pointer")};
b.prototype._onGraphicPointerOutCallback=function(a){a=a.graphic;-1<this.handleGraphics.indexOf(a)&&-1===this.selectedGraphics.indexOf(a)&&(a.symbol=this.handleSymbol);"default"!==this.view.container.style.cursor&&(this.view.container.style.cursor="default")};b.prototype._createHandleFromMidpoint=function(a){var c=this.graphic.geometry.clone(),b=a.attributes,d=b.pathIndex,f=b.pointIndexStart,g=b.pointIndexEnd,b=a.geometry,f=0===g?f+1:g;("polyline"===c.type?c.paths:c.rings)[d].splice(f,0,[b.x,b.y]);
a.attributes={pathIndex:d,pointIndex:f,relatedGraphicIndices:[]};this.graphic.geometry=c};b.prototype._removeHandles=function(a){var b=this.graphic.geometry.clone(),d="polygon"===b.type?b.rings:b.paths;a instanceof p&&(a=[a]);for(var h=0,f=a;h<f.length;h++){var g=f[h].geometry;a=g.x;var g=g.y,e;for(e in d){var k=d[e],l;for(l in k){var q=k[l],r=q[1];a===q[0]&&g===r&&d[e].splice(Number(l),1)}}}if("polygon"===b.type)for(h=0;h<d.length;h++)e=d[h],g=e[0],a=g[0],g=g[1],f=e[e.length-1],l=f[0],f=f[1],(1===
e.length||3>e.length&&a===l&&g===f)&&d.splice(d.indexOf(e),1),2<e.length&&(a!==l||g!==f)&&e.push(e[0]);else for(a=0;a<d.length;a++)g=d[a],1===g.length&&d.splice(d.indexOf(g),1);this.graphic.geometry=b};b.prototype._addToSelection=function(a){a instanceof p&&(a=[a]);for(var b=0,d=a;b<d.length;b++)d[b].symbol=this.handleSelectionSymbol;this._set("selectedGraphics",this.selectedGraphics.concat(a));this.callbacks.onSelect&&this.callbacks.onSelect(new I(a))};b.prototype._removeFromSelection=function(a,
b){b=b?this.handleHoverSymbol:this.handleSymbol;a instanceof p&&(a=[a]);for(var c=0,d=a;c<d.length;c++){var f=d[c];this.selectedGraphics.splice(this.selectedGraphics.indexOf(f),1);f.symbol=b}this.callbacks.onDeselect&&this.callbacks.onDeselect(new x(a))};b.prototype._clearSelection=function(){if(this.selectedGraphics.length){for(var a=this.selectedGraphics,b=0,d=this.selectedGraphics;b<d.length;b++)d[b].symbol=this.handleSymbol;this._set("selectedGraphics",[]);this.callbacks.onDeselect&&this.callbacks.onDeselect(new x(a))}};
b.prototype._keyDownHandler=function(a){"Backspace"===a.key&&!a.repeat&&this.selectedGraphics.length&&this._removeVertex(this.selectedGraphics)};b.prototype._removeVertex=function(a){if(!("polygon"===this.graphic.geometry.type&&4>this.handleGraphics.length||3>this.handleGraphics.length)){var b=this.graphic.clone();a instanceof p&&(a=[a]);this._removeHandles(a);this.refresh();this.callbacks.onVertexRemove&&this.callbacks.onVertexRemove(new K(a,this.graphic,b))}};h([l.property()],b.prototype,"callbacks",
void 0);h([l.property()],b.prototype,"graphic",void 0);h([l.property({dependsOn:["graphic","handleGraphics","midpointGraphics"],readOnly:!0})],b.prototype,"graphics",null);h([l.property({readOnly:!0})],b.prototype,"handleGraphics",void 0);h([l.property()],b.prototype,"handleHoverSymbol",void 0);h([l.property()],b.prototype,"handleSelectionSymbol",void 0);h([l.property()],b.prototype,"handleSymbol",void 0);h([l.property()],b.prototype,"layer",void 0);h([l.property({readOnly:!0})],b.prototype,"midpointGraphics",
void 0);h([l.property()],b.prototype,"midpointSymbol",void 0);h([l.property()],b.prototype,"midpointsEnabled",void 0);h([l.property({readOnly:!0})],b.prototype,"selectedGraphics",void 0);h([l.property()],b.prototype,"view",void 0);return b=h([l.subclass("esri.views.2d.draw.support.Reshape")],b)}(l.declared(z))});