// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.9/esri/copyright.txt for details.
//>>built
define("require exports ./core/tsSupport/assignHelper dojo/Deferred dojo/has!host-webworker?./core/workers/request dojo/io-query dojo/_base/url dojo/errors/CancelError dojo/request/xhr ./config ./core/deferredUtils ./core/Error ./core/global ./core/has ./core/lang ./core/promiseUtils ./core/urlUtils".split(" "),function(N,Z,u,D,G,O,H,P,I,Q,R,z,S,r,v,l,g){function J(a,c){void 0===c&&(c=!1);g.isBlobProtocol(a.url)||g.isDataProtocol(a.url)||!a.content||(a.preventCache&&(a.content["request.preventCache"]=
Date.now()),a.url=g.addQueryParameters(a.url,a.content));var b=new Image;b.crossOrigin=a.withCredentials?"use-credentials":"anonymous";var e=!1,d=new D(function(){e=!0;b.onload=b.onerror=b.onabort=null;b.src=""}),f=function(){b.onload=b.onerror=b.onabort=null;c&&URL.revokeObjectURL(this.src);e||d.reject(Error("Unable to load the resource"))};b.onload=function(){b.onload=b.onerror=b.onabort=null;c&&URL.revokeObjectURL(this.src);e||d.resolve(this)};b.onerror=f;b.onabort=f;b.alt="";b.src=a.url;return d.promise}
function T(a){a=new H(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function U(){return E?E:E=l.create(function(a){N(["./identity/IdentityManager"],a)}).then(function(a){m=a})}function V(a,c){var b=!!a.useProxy,e=a.method||"auto";a=u({},a);a.content=a.content||{};a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));var d=a.url,f=g.isBlobProtocol(d)||g.isDataProtocol(d);a._token&&(a.content.token=a._token);var q=0,h;f||(h=O.objectToQuery(a.content),q=h.length+d.length+1,r("esri-url-encodes-apostrophe")&&
(q=h.replace(/'/g,"%27").length+d.length+1));a.timeout=null!=a.timeout?a.timeout:p.timeout;a.handleAs=a.handleAs||"json";try{var t=h=void 0,l=!f&&("post"===e||!!a.body||q>p.maxUrlLength),A=!f&&(b||!!g.getProxyRule(a.url)),n;if(n=!A&&"image"===a.handleAs&&p.proxyUrl&&!f){var y=g.getOrigin(a.url);n=!(!y||v.endsWith(y,".arcgis.com")||g.hasSameOrigin(y,g.appUrl)||-1!==w._corsServers.indexOf(y)||g.isTrustedServer(y))}n&&(a.handleAs="blob");A&&(r("host-browser")||r("host-webworker"))&&(h=g.getProxyUrl(d),
t=h.path,!l&&t.length+1+q>p.maxUrlLength&&(l=!0),h.query&&(a.content=u({},h.query,a.content)),l||(a.preventCache&&(a.content["request.preventCache"]=Date.now(),a.preventCache=!1),a.url=g.addQueryParameters(a.url,a.content),a.content=null),a.url=t+"?"+a.url);if(!f){var k=a.headers;!r("host-browser")&&!r("host-webworker")||k&&k.hasOwnProperty("X-Requested-With")||(k=a.headers=k||{},k["X-Requested-With"]=null);if(r("host-browser")&&c){var F=a.content&&a.content.token;F&&(c.set?c.set("token",F):c.append("token",
F));a.contentType=!1}if(!a.hasOwnProperty("withCredentials"))if(b=A?t:d,g.isTrustedServer(b))a.withCredentials=!0;else if(m){var K=m.findServerInfo(b);K&&K.webTierAuth&&(a.withCredentials=!0)}}if(l)return"image"===a.handleAs&&(a.handleAs="blob"),a.body?(a.data=c||a.body,a.query=a.content):a.data=a.content,delete a.body,delete a.content,!A&&r("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+W++),I.post(a.url,a);if("image"===a.handleAs)return J(a);a.query=a.content;
delete a.content;return I.get(a.url,a)}catch(X){return a=new D,a.reject(X),a.promise}}function B(a,c,b,e){function d(a){a._pendingDfd=V(b,t);var c=!!a._pendingDfd.response;(a._pendingDfd.response||a._pendingDfd).then(function(a){if(!c||!a.data)return a;p.proxyUrl&&!v.startsWith(a.url,p.proxyUrl)&&L(a.url);var b=a.getHeader("Content-Type");if(b&&(b=b.toLowerCase(),-1===b.indexOf("text/plain")&&-1===b.indexOf("application/json")))return a;b=a.data;if(b instanceof ArrayBuffer&&750>=b.byteLength)b=new Blob([b]);
else if(!(b instanceof Blob&&750>=b.size))return a;var d=new D,k=new FileReader;k.readAsText(b);k.onloadend=function(){if(!k.error)try{var b=JSON.parse(k.result);b.error&&(Object.isExtensible(a)||(a=u({},a)),a._jsonData=b)}catch(aa){}d.resolve(a)};return d.promise}).then(function(a){return c&&!a._jsonData&&"image"===e.requestOptions.responseType&&a.data instanceof Blob?(c=!1,b.url=URL.createObjectURL(a.data),J(b,!0)):a}).then(function(b){var d=c?b.data:b,k=c?b.getHeader.bind(b):C;if(d&&(b=c&&b._jsonData||
d,b.error||"error"===b.status))throw d=v.mixin(Error(),b.error||b),d.getHeader=k,d;a.resolve({data:d,url:e.url,requestOptions:e.requestOptions,getHeader:k});a._pendingDfd=null}).catch(function(c){var d,k,h,n;c&&(d=Number(c.code),k=c.hasOwnProperty("subcode")?Number(c.subcode):null,h=(h=c.messageCode)&&h.toUpperCase(),n=c.response);if(n&&0===n.status&&p.proxyUrl&&!f&&"post"!==b.method&&n.url&&!v.startsWith(n.url,p.proxyUrl))g.addProxyRule({proxyUrl:p.proxyUrl,urlPrefix:g.removeFile(g.urlToObject(b.url).path)}),
B(a,!0,b,e);else{if(403===d&&(4===k||c.message&&-1<c.message.toLowerCase().indexOf("ssl")&&-1===c.message.toLowerCase().indexOf("permission"))){if(!b._ssl){b._ssl=b._sslFromServer=!0;B(a,!0,b,e);return}}else if(q&&"no-prompt"!==b.authMode&&m._errorCodes&&-1!==m._errorCodes.indexOf(d)&&!m._isPublic(b.url)&&(403!==d||M&&-1===M.indexOf(h)&&(null==k||2===k&&b._token))){Y(a,b,e,x("request:server",c,e));return}n&&0<n.status&&n.url&&p.proxyUrl&&!v.startsWith(n.url,p.proxyUrl)&&L(n.url);a.reject(x("request:server",
c,e));a._pendingDfd=null}})}var f=b.body,q=b.useIdentity,h,t=null,l=f instanceof FormData;if(l||f&&f.elements)t=l?f:new FormData(f);var r=!!(-1!==b.url.toLowerCase().indexOf("token\x3d")||b.content&&b.content.token||t&&t.get&&t.get("token")||f&&f.elements&&f.elements.token);c||(!q||r||b._token||m._isPublic(b.url)||(c=function(a){a&&(b._token=a.token,b._ssl=a.ssl)},"immediate"===b.authMode?h=m.getCredential(b.url).then(c):"no-prompt"===b.authMode?h=m.checkSignInStatus(b.url).then(c).catch(function(){}):
c(m.findCredential(b.url))),a.then(function(a){(/\/sharing\/rest\/accounts\/self/i.test(b.url)||/\/sharing\/rest\/portals\/self/i.test(b.url))&&!r&&!b._token&&a.user&&a.user.username&&(g.isTrustedServer(b.url)||p.trustedServers.push(T(b.url)));var c=b._credential;if(c){var d=m.findServerInfo(c.server),d=d&&d.owningSystemUrl,e=void 0;d&&(d=d.replace(/\/?$/,"/sharing"),(e=m.findCredential(d,c.userId))&&-1===m._getIdenticalSvcIdx(d,e)&&e.resources.splice(0,0,d))}return a}).always(function(a){delete b._credential;
if(a){var c=!!b._ssl;a instanceof z?a.details.ssl=c:a.ssl=c}}));h?h.then(function(){a.isCanceled()||d(a)}).catch(function(b){a.reject(b)}):d(a);return a.promise}function Y(a,c,b,e){a._pendingDfd=m.getCredential(c.url,{error:e,token:c._token});a._pendingDfd.then(function(d){c._token=d.token;c._credential=d;c._ssl=c._sslFromServer||d.ssl;B(a,!0,c,b)}).catch(function(b){a.reject(b);a._pendingDfd=null})}function x(a,c,b){var e="Error",d={url:b.url,requestOptions:b.requestOptions,getHeader:C};if(c instanceof
z)return c.details?(c.details=v.clone(c.details),c.details.url=b.url,c.details.requestOptions=b.requestOptions):c.details=d,c;if(c){var f=c.response;b=f&&f.getHeader;var f=f&&f.status,g=c.message;b=c.getHeader||b;g&&(e=g);b&&(d.getHeader=b);d.httpStatus=(null!=c.httpCode?c.httpCode:c.code)||f;d.subCode=c.subcode;d.messageCode=c.messageCode;d.messages="string"===typeof c.details?[c.details]:c.details}a=new z(a,e,d);c&&"cancel"===c.dojoType&&(a.name="AbortError",a.dojoType="cancel");return a}function L(a){g.isBlobProtocol(a)||
g.isDataProtocol(a)||(a=g.getOrigin(a))&&-1===w._corsServers.indexOf(a)&&w._corsServers.push(a)}function w(a,c){if(G&&S.invokeStaticMessage)return G.execute(a,c);g.isBlobProtocol(a)||g.isDataProtocol(a)||(a=g.normalize(a));var b={url:a,requestOptions:u({},c)},e=g.getInterceptor(a);if(e){if(null!=e.responseData)return l.resolve({data:e.responseData,requestOptions:b.requestOptions,getHeader:C,url:a});e.headers&&(b.requestOptions.headers=u({},b.requestOptions.headers,e.headers));e.query&&(b.requestOptions.query=
u({},b.requestOptions.query,e.query));if(e.before&&(c=e.before(b),null!=c))return c instanceof Error||c instanceof z?l.reject(x("request:interceptor",c,b)):l.resolve({data:c,requestOptions:b.requestOptions,getHeader:C,url:b.url})}var d=u({url:b.url},b.requestOptions);d.content=d.query;delete d.query;d.preventCache=!!d.cacheBust;delete d.cacheBust;d.handleAs=d.responseType;delete d.responseType;"array-buffer"===d.handleAs&&(d.handleAs="arraybuffer");if("image"===d.handleAs){if(r("host-webworker"))return l.reject(x("request:invalid-parameters",
Error("responseType 'image' is not supported in Web Workers or Node environment"),b))}else if(g.isDataProtocol(a))return l.reject(x("request:invalid-parameters",Error("Data URLs are not supported for responseType \x3d "+d.handleAs),b));var f=p.useIdentity;"anonymous"===d.authMode&&(f=!1);d.useIdentity=f;d.urlObj=new H(d.url);var q=R.makeDeferredCancellingPending(),h;b.requestOptions.signal&&(a=b.requestOptions.signal,h=function(){q.cancel(x("AbortError",new P("Request canceled"),b))},a.aborted?h():
a.addEventListener("abort",h));l.resolve().then(function(){if(f&&!m)return U()}).always(function(){q.isCanceled()||B(q,!1,d,b)});return q.then(function(a){b.requestOptions.signal&&b.requestOptions.signal.removeEventListener("abort",h);e&&e.after&&e.after(a);return a}).catch(function(a){b.requestOptions.signal&&b.requestOptions.signal.removeEventListener("abort",h);throw a;})}var p=Q.request,M=["COM_0056","COM_0057"],W=0,C=function(){return null},m,E;(w||(w={}))._corsServers=["https://server.arcgisonline.com",
"https://services.arcgisonline.com"];return w});